- source/manage-apps/configure/config/sync.txt
- https://jira.mongodb.org/browse/DOCSP-19895
- [Realm Sync Configuration Files](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19895/manage-apps/configure/config/sync/)
> (DOCSP-19895): Add flexible sync config object and definitions

- source/sync/data-access-patterns/permissions.txt
- source/sync/learn/overview.txt
- https://jira.mongodb.org/browse/DOCSP-20231
- [Realm Sync Overview](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20231/sync/learn/overview/)
> (DOCSP-20231): Update Sync overview page for Flexible Sync

- source/manage-apps/secure.txt
- https://jira.mongodb.org/browse/DOCSP-19897
- [Application Security](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19897/manage-apps/secure/#mongodb-realm-applications-with-sync)
> (DOCSP-19897): Update App Security page for Flexible Sync permissions

- source/authentication/custom-jwt.txt
- (DOCSP-12549): [REALM] Document Custom JWT mappings
- [Custom JWT Payload](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/jwt/authentication/custom-jwt/#jwt-payload)
> (DOCSP-12549): [REALM] Document Custom JWT mappings

- source/logs/sync.txt
- https://jira.mongodb.org/browse/DOCSP-19896
- [Sync Logs](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19896/logs/sync/)
> (DOCSP-19896): Update Sync Logs page for Flexible Sync

- source/sdk/android/fundamentals/realms.txt
- source/sdk/dotnet/fundamentals/realms.txt
- https://jira.mongodb.org/browse/DOCSP-19899
I've mostly updated the "Synced Realms" section linked here to add FS info, but also made a few small tweaks where `partition` info appears on the page.
- [Android -> Fundamentals -> Realms](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19899/sdk/android/fundamentals/realms/#synced-realms)
- [.Net -> Fundamentals -> Realms](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19899/sdk/dotnet/fundamentals/realms/)
> (DOCSP-19899): Update SDK Realms page for Flexible Sync

- source/cloud.txt
- source/manage-apps.txt
- Sumedha suggestion
- [Manage & Deploy Realm Apps](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/deployment-easy-find/manage-apps/deploy/)
> Make Deployment Section Easier to Find

- examples/dart/bin/models/car.dart
- examples/dart/bin/models/car.g.dart
- examples/dart/bin/myapp.dart
- examples/dart/scripts/bluehawk_create_snippets.sh
- examples/dart/test/define_realm_model_test.dart
- examples/dart/test/define_realm_model_test.g.dart
- examples/dart/test/quick_start_test.dart
- source/examples/generated/flutter/define_realm_model_test.codeblock.define-model-dart.dart
- source/examples/generated/flutter/define_realm_model_test.codeblock.define-model-flutter.dart
- source/examples/generated/flutter/quick_start_test.codeblock.create-realm-object.dart
- source/examples/generated/flutter/quick_start_test.codeblock.query-realm-objects-with-sort.dart
- source/includes/steps-install-dart.yaml
- source/includes/steps-mdb-rules-process.yaml
- source/sdk/flutter.txt
- source/sdk/flutter/install.txt
- source/sdk/flutter/quick-start.txt
Implement initial feedback for Flutter Alpha SDK. 
Overview of changes:
- make clearer dart standalone getting started 
- rename 'dart only' to 'dart standalone'
- update model definitions per lubo feedback
N/A
- [Flutter section](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/flutter_fixes/sdk/flutter/)
> Flutter Alpha Feedback

- source/sync/error-handling/errors.txt
- https://jira.mongodb.org/browse/DOCSP-19901
- [Sync Errors](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19901/sync/error-handling/errors/): Moves the Partition-Based Sync error into a new section, and adds a section for Flexible Sync errors
> (DOCSP-19901): Update Sync Errors page for Flexible Sync

- source/sync/configure/pause-or-terminate-sync.txt
- source/sync/error-handling/errors.txt
- https://jira.mongodb.org/browse/DOCSP-19838
- [Sync Errors](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fatal-sync-error/sync/error-handling/errors/)
> (DOCSP-19838): Document translator fatal error / ChangeStreamHistoryLost

- source/includes/steps-github-deploy.yaml
- source/manage-apps/deploy/automated/deploy-automatically-with-github.txt
- source/sync/data-model/update-schema.txt
- https://jira.mongodb.org/browse/DOCSP-20606
- [Deploy Automatically with GitHub](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20606/manage-apps/deploy/automated/deploy-automatically-with-github/#make-changes-to-your-application): Add note about making destructive changes in the UI, update summary from "When" to "While"
- [Update Schema](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20606/sync/data-model/update-schema/#destructive-changes): Add note about making destructive changes in the UI
> (DOCSP-20606): Add info about making destructive changes via the Realm UI

- source/cloud.txt
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/main/cloud/
> fix Sync link

- examples/node/package.json
> Quickfix - remove accidentally pushed --onlyChanged in JS unit tests

- source/sync/data-access-patterns/flexible-sync.txt
- [Flexible Sync (backend) - Create Queries in Your Client Application](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fix-SDK-links/sync/data-access-patterns/flexible-sync/#create-queries-in-your-client-application)
> Fix Flexible Sync SDK Links

- examples/node/Examples/flexible-sync.js
- source/examples/generated/node/flexible-sync.codeblock.remove-all-subscriptions-of-object-type.js
- source/examples/generated/node/flexible-sync.codeblock.remove-all-subscriptions.js
- source/examples/generated/node/flexible-sync.codeblock.remove-single-subscription.js
- source/examples/generated/node/flexible-sync.codeblock.remove-subscription-by-name.js
- source/examples/generated/node/flexible-sync.codeblock.remove-subscription-by-reference.js
- source/examples/generated/node/flexible-sync.codeblock.subscribe-to-queryable-fields-await-form.js
- source/examples/generated/node/flexible-sync.codeblock.subscribe-to-queryable-fields.js
- source/examples/generated/node/flexible-sync.codeblock.update-subscriptions.js
- source/examples/generated/node/flexible-sync.codeblock.wait-for-synchronization.js
- source/sdk/node/examples/flexible-sync.txt
N/A
- [Flexible Sync - Node.js SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/remove-destructuring-from-node-app/sdk/node/examples/flexible-sync/)
> Quickfix - removed destructuring from node subscriptions.update() method

- source/sdk/android/advanced-guides/link-user-identities.txt
- source/sdk/dotnet/advanced-guides/link-user-identities.txt
- source/sdk/node/advanced/link-identities.txt
- source/sdk/react-native/advanced/link-identities.txt
- source/sdk/swift/examples/users/link-user-identities.txt
When the page updates are approved, I'll expand the PR to apply the readability improvements to all SDKs.
- https://jira.mongodb.org/browse/DOCSP-19167
- [Swift SDK -> Link User Identities](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19167/sdk/swift/examples/users/link-user-identities/)
> (DOCSP-19167): Refactor for readability

- source/authentication.txt
- source/sdk/android/examples/authenticate-users.txt
- source/sdk/node/examples/authenticate-users.txt
- source/sdk/react-native/examples/authenticate-users.txt
- source/sdk/swift/examples/work-with-users.txt
- https://jira.mongodb.org/browse/DOCSP-19161
- [Users & Authentication](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19161/authentication/)
> (DOCSP-19161): Refactor Users & Authentication page to improve readability 

- source/triggers/scheduled-triggers.txt
Clarify Scheduled Triggers based on UTC
- https://jira.mongodb.org/browse/DOCSP-15073
- [Scheduled Triggers](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/15073/triggers/scheduled-triggers/)
> (DOCSP-15073): Clarify Scheduled Triggers based on UTC

- source/schemas.txt
- source/schemas/types.txt
- https://jira.mongodb.org/browse/DOCSP-20791
- [Schemas](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20791/schemas/)
> (DOCSP-20791): add Binary Data type to backend schema

- source/includes/steps-use-a-custom-domain-name-import-export.yaml
- source/includes/steps-use-a-custom-domain-name-realm-ui.yaml
add suggestion for adding CNAME record  to DNS provider
- https://jira.mongodb.org/browse/DOCSP-18573
- [Use a Custom Domain Name](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18573/hosting/use-a-custom-domain-name/#add-a-validation-cname-record)
> (DOCSP-18573): Suggest omitting domain at end of hostname when adding CNAME validation record for Realm hosting

- source/includes/note-get-schema-ui-dev-mode-disabled.rst
- source/sdk/dotnet/quick-start-with-sync.txt
- source/sdk/node/examples/authenticate-users.txt
- source/sdk/node/examples/open-and-close-a-realm.txt
- source/sdk/node/quick-start.txt
- source/sdk/react-native/examples/authenticate-users.txt
- source/sdk/react-native/examples/open-and-close-a-realm.txt
- source/sdk/react-native/quick-start.txt
- source/sdk/swift/quick-start-with-sync.txt
- https://jira.mongodb.org/browse/DOCSP-20790
- [site](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20790/)
> (DOCSP-20790): Copy edits and refactor schema note into include

- source/tutorial/ios-swift.txt
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/ios_tuts/tutorial/ios-swift/#part-1--set-up-the-mobile-app
**and** 
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/ios_tuts/tutorial/ios-swift/#part-2--add-sync-to-the-mobile-app
> Add video links

- tutorial/swift-ios/Task Tracker/AppDelegate.swift
- tutorial/swift-ios/Task Tracker/ManageTeamViewController.swift
- tutorial/swift-ios/Task Tracker/Models.swift
- tutorial/swift-ios/Task Tracker/ProjectsViewController.swift
- tutorial/swift-ios/Task Tracker/SceneDelegate.swift
- tutorial/swift-ios/Task Tracker/TasksViewController.swift
- tutorial/swift-ios/Task Tracker/WelcomeViewController.swift
- https://jira.mongodb.org/browse/DOCSP-20893
> (DOCSP-20893): Update Copyright date for ios-swift tutorial

- source/sdk/dotnet/examples/modify-an-object-schema.txt
- source/sdk/node/examples/modify-an-object-schema.txt
- source/sdk/react-native/examples/modify-an-object-schema.txt
- source/sdk/swift/examples/modify-an-object-schema.txt
- https://jira.mongodb.org/browse/DOCSP-15325
- [Modify an Object Schema](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15325/sdk/dotnet/examples/modify-an-object-schema/#migration-functions): New tip about deleting instead of migrating a realm
> (DOCSP-15325): .Net SDK: Add tip about deleting vs. migrating a realm

- source/services/replace-with-npm-modules.txt
- (DOCSP-20172): How to migrate off of services
- [Replace Services with npm Modules](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/no-more-services/services/replace-with-npm-modules/)
> (DOCSP-20172): How to migrate off of services

- source/endpoints.txt
- source/includes/steps-create-an-endpoint-cli.yaml
- source/manage-apps/configure/config/http_endpoints.txt
- (DOCSP-20938): Update config file reference for HTTPS Endpoints
- [HTTP Endpoint Configuration Files](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/endpoints/manage-apps/configure/config/http_endpoints/)
- [Configure HTTPS Endpoints](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/endpoints/endpoints/configure/)
> (DOCSP-20938): Update config file reference for HTTPS Endpoints

- source/includes/steps-configure-flexible-sync-ui.yaml
- https://jira.mongodb.org/browse/DOCSP-21004
- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21004/sync/configure/enable-sync/#select-development-details-1)
> DOCSP-21004: Remove callout about shared clusters not running MDB 5.0

- source/openapi-admin-v3.yaml
- (DOCSP-20975): [Admin API] HTTPS Endpoints
- [Custom HTTPS Endpoint APIs](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/endpoints-admin/admin/api/v3/#tag/endpoints)
> (DOCSP-20975): [Admin API] HTTPS Endpoints

- source/openapi-admin-v3.yaml
- Fixes a few typos
- Distinguishes short `summary` from longer `description` to make our Redoc less redundant and more helpful
- Rearranges and simplifies the `tags` array (alphabetical order)
- [Admin API](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/admin-api-cleanup/admin/api/v3/)
> Admin API Cleanup

- config/redirects
> Fix redirect loop

- source/includes/steps-api-export.yaml
- (DOCSP-21024): Fix export app procedure
- [Export a Realm App with Realm API](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/export-api/manage-apps/configure/export/export-with-api/)
> (DOCSP-21024): Fix export app procedure

- source/includes/steps-define-a-function-import-export.yaml
- source/includes/steps-define-a-function-realm-ui.yaml
- (DOCSP-21025): You can nest functions in folders
- [Define a Function](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/nested-functions/functions/define-a-function/)
> (DOCSP-21025): You can nest functions in folders

- source/sdk/dotnet/data-types/field-types.txt
- https://jira.mongodb.org/browse/DOCSP-21021
- 
> (DOCSP-21021): Add note that timezone information is lost

- source/sdk/node/examples/sync-changes-between-devices.txt
- source/sdk/react-native/examples/sync-changes-between-devices.txt
- source/sync/data-access-patterns/partitions.txt
clarify partition strategy in JS sync docs. changes are same for React Native and Node pages
- https://jira.mongodb.org/browse/DOCSP-21092
- [Sync Changes Between Devices (React Native)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21092/sdk/react-native/examples/sync-changes-between-devices/#pause-or-resume-a-sync-session)
- [Sync Changes Between Devices (Node)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21092/sdk/node/examples/sync-changes-between-devices/#pause-or-resume-a-sync-session)
- [Partitions](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21092/sync/data-access-patterns/partitions/#std-label-partition-strategy)
[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/RE …
> (DOCSP-21092): Explain "MyPartitionValue" on JS sync docs

- source/sdk/dotnet/examples/mongodb-remote-access.txt
- source/sdk/java/advanced-guides/custom-user-data.txt
- source/sdk/java/examples/mongodb-remote-access.txt
- source/sdk/node/examples/query-mongodb.txt
- source/sdk/react-native/examples/query-mongodb.txt
- source/sdk/swift/examples/mongodb-remote-access.txt
- source/sdk/swift/examples/users/custom-user-data.txt
- source/sync/data-model/update-schema.txt
- https://jira.mongodb.org/browse/DOCS-15100
- [Query MongoDB - Node.js SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCS-15100/sdk/node/examples/query-mongodb/#use-cases)
- [Query MongoDB - RN SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCS-15100/sdk/react-native/examples/query-mongodb/)
- [Query MongoDB - Java SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCS-15100/sdk/java/examples/mongodb-remote-access/#use-cases)
- [Query MongoDB - Swift SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCS-15100/sdk/swift/examples/mongodb-remote-access/#use-cases)
- [Query MongoDB - .Net SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCS-151 …
> (DOCS-15100): Add use cases for why query MongoDB remotely

- source/endpoints.txt
- source/includes/appschema-configuration.rst
- source/manage-apps/configure/config/app.txt
- source/manage-apps/configure/copy-realm-app.txt
- source/manage-apps/deploy/deployment-models-and-regions.txt
- source/sync/learn/overview.txt
- (DOCSP-20236): Local Base URLs for Endpoints
- [Endpoints](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/endpoints-url/endpoints/)
> (DOCSP-20236): Local Base URLs for Endpoints

- source/includes/steps-realm-with-electron.yaml
- source/sdk/dotnet/examples/flexible-sync.txt
- source/sdk/dotnet/examples/react-to-changes.txt
- source/sdk/java/examples/open-and-close-a-realm.txt
- source/sdk/kotlin/app-services/authenticate-users.txt
- source/sdk/kotlin/migrate-from-java-sdk-to-kotlin-sdk.txt
- source/sdk/kotlin/realm-database/open-and-close-a-realm.txt
- source/sdk/node/advanced/bundle.txt
- source/tutorial/web-graphql.txt
- https://jira.mongodb.org/browse/DOCSP-21118
- Refer to this spreadsheet: https://docs.google.com/spreadsheets/d/1Uy1MjZoaq1kTimGpYs6ONKmQPEx5omtLUs8UUOXSOak/edit#gid=620443762
All links except the java/api links should be fixed or removed. Also spruced up some nearby language.
- [There are a lot of pages to link. Consult the sheet.](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21118/)
> (DOCSP-21118): Fix broken links

- .github/workflows/docusaurus-staging.yml
based on https://github.com/marketplace/actions/comment-pull-request#disclaimer
and https://github.com/actions/github-script
> add PR comment w link

- docusaurus/docs/sdk/java/intro.mdx
- docusaurus/docs/sdk/kotlin/intro.mdx
> smol changes

- .github/workflows/docusaurus-staging.yml
- README.rst
- docusaurus/docs/sdk/java/intro.mdx
- docusaurus/docs/sdk/kotlin/intro.mdx
- docusaurus/docs/sdk/kotlin/quick-start.mdx
- see https://github.com/mongodb/docs-realm/pull/1720 for an example of repeat commits, but only one comment. This way the Docusaurus staging github action doesn't spam everyone involved on every commit.
> Create Or Update Staging Comment - Docusaurus builds

- examples/dart/test/task_project_models_test.dart
- examples/dart/test/task_project_models_test.g.dart
- source/examples/generated/flutter/task_project_models_test.codeblock.task-project-models.dart
- source/includes/rql.rst
- source/sdk/flutter.txt
- source/sdk/flutter/query-language.txt
- source/sdk/flutter/quick-start.txt
- source/sdk/flutter/read-and-write-data.txt
Add pages for Read & Write data and Realm Query Language for Flutter SDK
- https://jira.mongodb.org/browse/DOCSP-21138
- https://jira.mongodb.org/browse/DOCSP-21155
- [Read & Write Data (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21138/sdk/flutter/read-and-write-data/)
- [Realm Query Language (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21138/sdk/flutter/query-language/)
> (DOCSP-21138 & DOCSP-21155): Read/Write Data & RQL pages for Flutter SDK

- examples/dotnet/ConsoleTests/Program.cs
- examples/dotnet/Examples/AggregationExamples.cs
- examples/dotnet/Examples/AuthenticationExamples.cs
- examples/dotnet/Examples/BundleARealmExamples.cs
- examples/dotnet/Examples/ClientResetExamples.cs
- examples/dotnet/Examples/DecimalExamples.cs
- examples/dotnet/Examples/ErrorHandler.cs
- examples/dotnet/Examples/FunctionExamples.cs
- examples/dotnet/Examples/MongoDBExamples.cs
- examples/dotnet/Examples/OpenARealmExamples.cs
- examples/dotnet/Examples/ProgressNotifications.cs
- examples/dotnet/Examples/QueryEngineExamples.cs
- examples/dotnet/Examples/QuickStartExamples.cs
- examples/dotnet/Examples/Unity.cs
- source/examples/generated/dotnet/BundleARealmExamples.codeblock.copy_a_synced_realm.cs
- source/examples/generated/dotnet/BundleARealmExamples.codeblock.extract_and_copy_realm.cs
- source/examples/generated/dotnet/OpenARealmExamples.codeblock.check-if-offline.cs
- source/examples/generated/dotnet/OpenARealmExamples.codeblock.open-synced-realm.cs
- source/examples/generated/dotnet/OpenARealmExamples.codeblock.scope.cs
- source/examples/generated/dotnet/QuickStartExamples.codeblock.config.cs
- source/examples/generated/dotnet/Unity.codeblock.read_a_realm_unity.cs
- source/sdk/dotnet/examples/authenticate.txt
- source/sdk/dotnet/examples/open-a-realm.txt
- source/sdk/dotnet/quick-start-with-sync.txt
- https://jira.mongodb.org/browse/DOCSP-20797
N/A 
> (DOCSP-20797): Replace SyncConfiguration with PartitionSyncConfiguration on .NET SDK

- docusaurus/docs/sdk/java/install.mdx
- source/sdk/java/install.txt
- https://jira.mongodb.org/browse/DOCSP-18521
- [Java - Install](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18521/sdk/java/install)
> (DOCSP-18521): Bump required JDK version to 9

- examples/ios/Examples/QueryEngine.swift
- examples/ios/Podfile.lock
- examples/ios/RealmExamples.xcodeproj/project.pbxproj
- source/examples/generated/code/start/QueryEngine.codeblock.tsq-collections-contains.swift
- source/examples/generated/code/start/QueryEngine.codeblock.tsq-collections-in.swift
- source/sdk/swift/examples/filter-data.txt
- https://jira.mongodb.org/browse/DOCSP-20570
- [Filter Data](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20570/sdk/swift/examples/filter-data/#collections): the "New in version..." at the bottom of this linked section
> (DOCSP-20570): Add IN type safe query example for 10.23.0

- source/includes/destructive-schema-change-app-update.rst
- source/includes/steps-perform-destructive-changes-synced-schema.yaml
- source/sync/configure-your-data-model.txt
- source/sync/data-model/development-mode.txt
- source/sync/data-model/migrate-schema-partner-collection.txt
- source/sync/data-model/update-schema.txt
- source/sync/error-handling/client-resets.txt
- source/sync/learn/overview.txt
Note for a reviewer: this goes a bit beyond the basic renaming that we discussed in the doc, but I realized there's also a lot of conflating between schema and object model, so wanted to provide more explicit info about things.
Please, if you spot anything that is inaccurate or needs elaboration, I would appreciate it!
After this page is approved, I'll make the rest of the changes to the docs set to match the naming and apply relevant updates elsewhere.
- https://jira.mongodb.org/browse/DOCSP-20720
- [Update Your Schema](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20720/sync/data-model/update-schema/)
> (DOCSP-20720): Breaking vs. Non-Breaking Schema/Model Updates

- source/openapi-admin-v3.yaml
- source/sdk/swift/examples/filter-data.txt
- [DOCS-15167](https://jira.mongodb.org/browse/DOCS-15167)
- [Admin API - adminGetLogs](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15167/admin/api/v3/#operation/adminGetLogs)
> (DOCSP-15167) Add/improve "type" and "error_only" information in adminGetLogs API endpoint

- docusaurus/sdk-sites/kotlin/docs/install/android.mdx
- source/sdk/kotlin/install/android.txt
- follow-up fix to truly fix last fix
- [Kotlin SDK - Install (Android)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)
> install updates for kotlin sdk -android

- docusaurus/sdk-sites/kotlin/docs/install/android.mdx
- source/sdk/kotlin/install/android.txt
- tools/autobuilder/src/index.ts
- Feedback from eng
- [Kotlin - Install](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fixKotlinInstallGuide/sdk/kotlin/install/android)
> Reliable Android Installation for Kotlin SDK

- docusaurus/package-lock.json
- docusaurus/package.json
- docusaurus/src/components/VersionChanger.tsx
- docusaurus/src/theme/DocSidebar/index.js
Create prototype of the SDK version changer. 
note that this is just a prototype and the code will need significant refactoring for the production site. it should also be noted that the version selector does not currently work on the mobile site. this functionality should also be added. 
> Prototype Docusaurus version changer

- source/authentication/custom-jwt.txt
- (DOCSP-20413): Custom JWT kid header for JWKS
- [Custom JWT > JWT Headers > `kid`](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/jwt-kid/authentication/custom-jwt/#mongodb-data-kid)
> (DOCSP-20413): Custom JWT kid header for JWKS

- source/sync/data-access-patterns/flexible-sync.txt
- https://jira.mongodb.org/browse/DOCSP-21418
- [Flexible Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21418/sync/data-access-patterns/flexible-sync/#eligible-field-types): New seealso in Eligible Field Types
> (DOCSP-21418): Add link to RQL page

- source/sync/data-model/update-schema.txt
- https://jira.mongodb.org/browse/DOCSP-21333
- [Update Your Schema](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21333/sync/data-model/update-schema/#change-a-property-name): New tip in the section about how to rename a property
> (DOCSP-21333): Add tip about changing property name without triggering migration

- examples/ios/RealmExamples.xcodeproj/project.pbxproj
- examples/ios/SwiftUIExamples/ExampleApp.swift
- source/examples/generated/swiftui/migration/ExampleApp.codeblock.add-property-to-model.swift
- source/examples/generated/swiftui/migration/ExampleApp.codeblock.auto-open-synced-realm.swift.code-block.rst
- source/examples/generated/swiftui/migration/ExampleApp.codeblock.implicitly-open-realm.swift.code-block.rst
- source/examples/generated/swiftui/migration/ExampleApp.codeblock.pass-environment-object-to-local-content-view.swift.code-block.rst
- source/examples/generated/swiftui/migration/ExampleApp.codeblock.pass-realm-config-as-environment-object.swift
- source/examples/generated/swiftui/migration/ExampleApp.codeblock.pass-realm-config-to-synced-realm-view.swift.code-block.rst
- source/examples/generated/swiftui/migration/ExampleApp.codeblock.realm-configuration-increment-schema.swift
- source/sdk/swift/examples/swiftui-guide.txt
- source/sdk/swift/swiftui.txt
- https://jira.mongodb.org/browse/DOCSP-21189
- [SwiftUI Guide -> SwiftUI Realm Migrations](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21189/sdk/swift/examples/swiftui-guide/#swiftui-realm-migrations)
> (DOCSP-21189): Add migration info for SwiftUI

- examples/functions/functions_tester/functions/copyTaskObjectToTaskV2.js
- examples/functions/functions_tester/functions/copyTaskV2ObjectToTask.js
- source/examples/generated/functions/copyTaskObjectToTaskV2.codeblock.copyTaskObject.js
- source/examples/generated/functions/copyTaskV2ObjectToTask.codeblock.copyTaskV2Object.js
- https://jira.mongodb.org/browse/DOCSP-21327
- [Make Breaking Schema Changes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21327/sync/data-model/migrate-schema-partner-collection/#add-trigger-functions): Both functions in step 3 have 3 new lines from lines 4-6
> (DOCSP-21327): Add early return to functions to avoid errors

- docusaurus/sdk-sites/kotlin/docs/install/android.mdx
- source/sdk/dotnet.txt
- source/sdk/flutter.txt
- source/sdk/java.txt
- source/sdk/kotlin.txt
- source/sdk/node.txt
- source/sdk/node/examples/flexible-sync.txt
- source/sdk/react-native.txt
- source/sdk/swift.txt
- tools/autobuilder/src/index.ts
- https://jira.mongodb.org/browse/DOCSP-21387
- [All SDKs -- Sidebar](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21387/sdk/)
- [Node - Flexible Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21387/sdk/node/examples/flexible-sync/)
> (DOCSP-21387): Improve API Reference Visibility (in Node & Beyond)

- source/sdk/dotnet/examples/flexible-sync.txt
- source/sync/data-access-patterns/flexible-sync.txt
- https://jira.mongodb.org/browse/DOCSP-21378
- https://jira.mongodb.org/browse/DOCSP-21379
- https://jira.mongodb.org/browse/DOCSP-21397
- [21378 and 21379](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fscarb/sdk/dotnet/examples/flexible-sync)
- [21397](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fscarb/sync/data-access-patterns/flexible-sync/)
> .NET flexsync updates

- examples/dotnet/ConsoleTests/ConsoleTests.csproj
- examples/dotnet/ConsoleTests/FodyWeavers.xsd
- examples/dotnet/Examples/Examples.csproj
- examples/dotnet/Examples/FodyWeavers.xsd
- examples/dotnet/LocalOnly/FodyWeavers.xsd
- examples/dotnet/LocalOnly/LocalOnly.csproj
- examples/dotnet/README.md
https://jira.mongodb.org/browse/DOCSP-21436
N/A
> Fix Realm .NET version

- examples/dotnet/Examples/ErrorHandler.cs
- source/examples/generated/dotnet/ErrorHandler.codeblock.set-log-level.cs
- source/sdk/dotnet/examples/sync-changes-between-devices.txt
- https://jira.mongodb.org/browse/DOCSP-21398
- [Set the Client Log Level](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21398/sdk/dotnet/examples/sync-changes-between-devices/#set-the-client-log-level)
> (DOCSP-21398): Update deprecated .NET Log method usage to replacement

- examples/dotnet/Examples/QueryEngineExamples.cs
- source/examples/generated/dotnet/QueryEngineExamples.codeblock.rql.cs
- source/includes/rql.rst
- source/includes/tip-realm-query-language-reference-examples.rst
- source/sdk/dotnet/examples/flexible-sync.txt
- source/sdk/dotnet/fundamentals/query-engine.txt
- source/sdk/java/examples/filter-data.txt
- source/sdk/java/examples/flexible-sync.txt
- source/sdk/java/fundamentals/query-engine.txt
- source/sdk/node/advanced/query-engine.txt
- source/sdk/node/examples/flexible-sync.txt
- source/sdk/react-native/advanced/query-engine.txt
- source/sdk/react-native/examples/flexible-sync.txt
* clarify what is RQL on Java, .NET, and JS SDK pages
* add links to SDK pages on RQL reference
* update JS & .NET flexible sync pages to more clearly reference queries
- https://jira.mongodb.org/browse/DOCSP-21395
- [Realm Query Language Reference](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21395/reference/realm-query-language)
- [Query Engine (Java SDK)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21395/sdk/java/fundamentals/query-engine/)
- [Query Engine (.NET SDK)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21395/sdk/dotnet/fundamentals/query-engine/)
- [Flexible Sync (.NET SDK)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21395/sdk/dotnet/exampl …
> (DOCSP-21395): Update language around Flexible Sync and RQL

- source/sdk/node/examples/flexible-sync.txt
- source/sdk/react-native/examples/flexible-sync.txt
- https://jira.mongodb.org/browse/DOCSP-21396
- [Flexible Sync - Node.js](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21396-Add-SDK-Links/sdk/node/examples/flexible-sync/)
- [Flexible Sync - React Native](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21396-Add-SDK-Links/sdk/react-native/examples/flexible-sync/)
> (DOCSP-21396): Add SDK Links to Flexible Sync JS Docs

- examples/node/Examples/data-types.js
Refactored NodeJS data type unit tests. High level summary of changes:
- Made tests more easily idempotent by deleting realm files after each test
- defined realm variable w/in each test to avoid potentially passing wrong reference around and not require as much bluehawkification
- misc bluehawk cleanup and removing unused code
- https://jira.mongodb.org/browse/DOCSP-19467
N/A
> (DOCSP-19467): Refactor NodeJS data type tests

- source/schemas/relationships.txt
- https://jira.mongodb.org/browse/DOCSP-21382
- https://jira.mongodb.org/browse/DOCSP-21383
- [Relationships](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21382/schemas/relationships/#embedded-object-relationships-with-foreign-collections): New section for Embedded Object Relationships
> (DOCSP-21382): New section with embedded object relationship examples

- source/sdk/swift/examples/swiftui-guide.txt
Note for reviewer: the syntax is tested locally & verified by the Swift SDK team. 
- https://jira.mongodb.org/browse/DOCSP-21188
- [SwiftUI Guide](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21188/sdk/swift/examples/swiftui-guide/#filter-or-query-a-realm-with-observedresults): New section: `Filter or Query a Realm with ObservedResults`
> (DOCSP-21188): Add ObservedResults filter example

- source/manage-apps/secure.txt
https://jira.mongodb.org/browse/DOCSP-21079
https://docs-mongodbcom-staging.corp.mongodb.com/realm/21079/manage-apps/secure/#api-access-list
> add tiny blurb about x509 certificates

- .github/workflows/dart.yaml
branch for testing dart test GH action
> add dart test GH action

- examples/ios/Examples/ObjectModels.swift
- source/examples/generated/code/start/ObjectModels.codeblock.any-realm-collection.swift
- https://jira.mongodb.org/browse/DOCSP-20388
- [Swift SDK -> Collections/AnyRealmCollection](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20388/sdk/swift/data-types/collections/#anyrealmcollection)
> (DOCSP-20388): Update AnyRealmCollection example to eliminate error

- examples/ios/Examples/Authenticate.swift
- examples/ios/Examples/Encrypt.swift
- examples/ios/Examples/FlexibleSync.swift
- examples/ios/Podfile
- examples/ios/Podfile.lock
- examples/ios/RealmExamples.xcodeproj/project.pbxproj
- source/examples/generated/code/start/Authenticate.codeblock.google-with-googleId.swift
- source/examples/generated/code/start/Authenticate.codeblock.google-with-serverAuthCode.swift
- source/sdk/swift/examples/users/authenticate-users.txt
- https://jira.mongodb.org/browse/DOCSP-21489
- [Authenticate Users -> Google User](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21489/sdk/swift/examples/users/authenticate-users/#google-user): Provide tabs with example of ID token auth (preferred?) first, add comment to serverAuthCode example that it returns nil on subsequent logins
> (DOCSP-21489): Add code example for Google ID auth

- source/sdk/java/api/io.txt
- source/sdk/java/api/io/realm.txt
- source/sdk/java/api/io/realm/annotations.txt
- source/sdk/java/api/io/realm/coroutines.txt
- source/sdk/java/api/io/realm/exceptions.txt
- source/sdk/java/api/io/realm/log.txt
- source/sdk/java/api/io/realm/mongodb.txt
- source/sdk/java/api/io/realm/mongodb/auth.txt
- source/sdk/java/api/io/realm/mongodb/functions.txt
- source/sdk/java/api/io/realm/mongodb/log/obfuscator.txt
- source/sdk/java/api/io/realm/mongodb/mongo.txt
- source/sdk/java/api/io/realm/mongodb/mongo/MongoCollection.txt
- source/sdk/java/api/io/realm/mongodb/mongo/events.txt
- source/sdk/java/api/io/realm/mongodb/mongo/iterable.txt
- source/sdk/java/api/io/realm/mongodb/mongo/options.txt
- source/sdk/java/api/io/realm/mongodb/mongo/result.txt
- source/sdk/java/api/io/realm/mongodb/push.txt
- source/sdk/java/api/io/realm/mongodb/sync.txt
- source/sdk/java/api/io/realm/rx.txt
This uses the updated yokedox javadoc plugin to add titles to every index page so as to avoid breadcrumb issues from google.
- https://jira.mongodb.org/browse/DOCSP-21246
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/javadoc/sdk/java/api/io/realm/
> (DOCSP-21246): Update Javadoc

- config/redirects
fix broken redirects that were part of the subdomain consolidation
> Fix broken redirects

- source/sdk/dotnet/examples/sync-changes-between-devices.txt
https://jira.mongodb.org/browse/DOCSP-12668
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/12668/sdk/dotnet/examples/sync-changes-between-devices/#handle-sync-errors
> add note about HelpLink and clean up another admonition

- source/manage-apps/create/template-apps.txt
- https://jira.mongodb.org/browse/DOCSP-21624
- [Template Apps](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21624/manage-apps/create/template-apps/)
> (DOCSP-21624): Add the SwiftUI template app to the list

- source/includes/steps-realm-with-electron-using-create-react-app.yaml
- source/mongodb.txt
- source/mongodb/tables/read-preference-modes.rst
- source/openapi-admin-v3.yaml
- source/sdk/dotnet/fundamentals/query-engine.txt
- source/sdk/dotnet/unity.txt
- source/sdk/flutter/data-types.txt
- source/sdk/flutter/quick-start.txt
- source/sdk/react-native/advanced/bundle.txt
- source/sdk/swift.txt
fix broken links IDed on the docs site
- https://jira.mongodb.org/browse/DOCSP-21611
N/A
> (DOCSP-21611): Fix broken links

- source/release-notes/changelogs/backend/changelog-backend-2022.rst
- https://jira.mongodb.org/browse/DOCSP-21501
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/update/release-notes/backend/
> 3-25 release notes

- source/sdk/swift/fundamentals/object-models-and-schemas.txt
- source/sdk/swift/fundamentals/relationships.txt
With these updates, this page gets a B in Readable or grade 9 in HemingwayApp.
- https://jira.mongodb.org/browse/DOCSP-21152
- [Swift SDK -> Fundamentals -> Relationships](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21152/sdk/swift/fundamentals/relationships/)
> (DOCSP-21152): Refactor for readability

- source/release-notes/backend.txt
Noticed this when I was looking at the release notes for the week and figured it was a quick fix so I didn't need to make a Jira ticket for it.
- [Release Notes (Pending snooty build)]()
> Remove outdated note from changelog page

- source/sdk/swift/advanced-guides/threading.txt
- https://jira.mongodb.org/browse/DOCSP-17434
- [Threading](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17434/sdk/swift/advanced-guides/threading/#sendable-conformance)
> (DOCSP-17434): [Swift] Add note about ThreadSafeReference conforming to Sendable

- examples/java/sync/app/src/androidTest/java/com/mongodb/realm/examples/java/LinkUserIdentitiesTest.java
- examples/java/sync/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/LinkUserIdentitiesTest.kt
- source/examples/generated/java/LinkUserIdentitiesTest.codeblock.link-users.java
- source/examples/generated/java/sync/LinkUserIdentitiesTest.codeblock.link-users.java
- source/examples/generated/java/sync/LinkUserIdentitiesTest.codeblock.link-users.kt
- source/examples/generated/kotlin/LinkUserIdentitiesTest.codeblock.link-users.kt
- source/sdk/java/advanced-guides/link-user-identities.txt
https://jira.mongodb.org/browse/DOCSP-12594
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/12594/sdk/java/advanced-guides/link-user-identities/
> update info about linking to a e/p account and fix code formatting a bit

- examples/ios/RealmExamples.xcodeproj/project.pbxproj
- examples/ios/SwiftUIExamples/ExampleApp.swift
- source/examples/generated/swiftui/migration/ExampleApp.codeblock.explicitly-provide-config-to-property-wrappers.swift
- source/sdk/swift/examples/swiftui-guide.txt
- https://jira.mongodb.org/browse/DOCSP-21495
- [SwiftUI Guide](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21495/sdk/swift/examples/swiftui-guide/#swiftui-realm-migrations): Minor tweaks to the Migrations section
> (DOCSP-21495): Add explicit config details for migration

- source/sdk/dotnet/unity.txt
- https://jira.mongodb.org/browse/DOCSP-21090
- [Integrate Realm with Unity - .NET SDK # Known Issues When Developing With Unity](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21090-dotnet-unity-macWindowsEnv/sdk/dotnet/unity/)
> (DOCSP-21090): Fix note - known issues .NET Unity

- source/authentication/anonymous.txt
- https://jira.mongodb.org/browse/DOCSP-21621
- [Anonymous Authentication](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21621/authentication/anonymous/)
> (DOCSP-21621): Update anonymous user refresh token expiration references

- source/examples/generated/node/test-and-debug.codeblock.clean-up-test.js
- source/sdk/react-native.txt
- source/sdk/react-native/test-and-debug.txt
Add page on debugging and testing React Native. mostly refactor of content from the SDK readme
- https://jira.mongodb.org/browse/DOCSP-21722
- [Debug and Test (React Native)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21722/sdk/react-native/debug-and-test/)
> (DOCSP-21722): Debug and Test React Native

- source/includes/steps-configure-user-metadata-import-export.yaml
- source/includes/steps-configure-user-metadata-realm-ui.yaml
- source/users/enable-user-metadata.txt
The rewrites in this PR bring this page up to a "B" rating in Readable, or down to a "Grade 7" rating in HemingwayApp.
- https://jira.mongodb.org/browse/DOCSP-21151
- [Enable User Metadata](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21151/users/enable-user-metadata/)
> (DOCSP-21151): Refactor to improve readability

- source/includes/android-6-trusted-certificate.rst
- source/sdk/java/install.txt
- https://jira.mongodb.org/browse/DOCSP-21768
- [Java SDK - Install](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21768/sdk/java/install/)
> (DOCSP-21768): Remove Android 6 Certificate warning

- source/includes/steps-auto-schema-generation.yaml
- source/sdk/dotnet/fundamentals/object-models-and-schemas.txt
- source/sdk/node/examples/define-a-realm-object-model.txt
- source/sdk/react-native/examples/define-a-realm-object-model.txt
- https://jira.mongodb.org/browse/DOCSP-21749
- took the libery of updating a few primary key/index SDK references with out-of-date type lists, too
- [Create a Schema - Define a Realm Schema](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21749/sync/data-model/create-a-schema/#define-a-realm-schema)
> (DOCSP-21749): Add UUID to list of primary key types

- docusaurus/docs/includes/_query-language.md
- source/includes/rql-aggregation.rst
- According to James Stone, this limitation is not there
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/master/reference/realm-query-language/
> Feedback widget: fix RQL @count limitation

- source/manage-apps/create/template-apps.txt
https://github.com/mongodb/docs-realm/pull/1831
- [Template Apps](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/quickfix-template-apps-page-typos/manage-apps/create/template-apps/)
> fix wording + small improvements to Template Apps page

- source/openapi-admin-v3.yaml
Update Admin API response object for Create Functions endpoint. 
- https://jira.mongodb.org/browse/DOCSP-21880
- [Admin API Reference, Create Function endpoint](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21880/admin/api/v3/#operation/adminCreateFunction)
> (DOCSP-21880): Update create function endpoint

- source/sdk/node/fundamentals/realms.txt
- source/sdk/swift/fundamentals/realms.txt
N/A
- [Realms - Swift SDK # Synced Realms](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/quickfix-typos-in-realms-page/sdk/swift/fundamentals/realms/#synced-realms)
- [Realms - Node.js SDK # Synced Realms](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/quickfix-typos-in-realms-page/sdk/node/fundamentals/realms/#synced-realms)
> Quickfix - typos in the realms page

- source/authentication/providers.txt
- https://jira.mongodb.org/browse/DOCSP-21146
- [Authentication Providers](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21146/authentication/providers/)
> (DOCSP-21146): Refactor to improve readability from C to B or grade 15 to grade 8

- .github/workflows/ios.yml
- examples/ios/Examples/ClientReset.swift
- source/examples/generated/code/start/ClientReset.codeblock.client-reset-discard-changes-with-blocks.swift
- source/sdk/swift/advanced-guides/client-reset.txt
Dear Reviewer, the CI will not currently run due to waiting on GitHub to update their macOS image to a version that supports Xcode 13.3. (The [PR is open and reviewed, though!](https://github.com/actions/virtual-environments/pull/5397))
I super duper promise this runs locally and all the tests pass.
- https://jira.mongodb.org/browse/DOCSP-21946
- [Client Resets (Swift SDK)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21946/sdk/swift/advanced-guides/client-reset/)
> (DOCSP-21946): Incorporate feedback from tech review on PR #1810

- source/openapi-admin-v3.yaml
- source/sdk/flutter/define-realm-object-schema.txt
- source/web.txt
fix broken links in realm docs
- https://jira.mongodb.org/browse/DOCSP-22046
- [staging build](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22046/)
> (DOCSP-22046): fix broken links

- examples/web/package.json
- examples/web/src/__tests__/authentication-log-in-and-out.test.js
- examples/web/yarn.lock
- source/authentication/custom-jwt.txt
- source/examples/generated/web/authentication-log-in-and-out.test.codeblock.custom-jwt-firebase.js
Add documentation for Custom JWT authentication with Firebase Authentication
- https://jira.mongodb.org/browse/DOCSP-11189
- [Custom JWT Authentication](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-11189/authentication/custom-jwt/)
> (DOCSP-11189): Add Custom JWT with Firebase docs

- source/sync/data-access-patterns/partitions.txt
- https://jira.mongodb.org/browse/DOCSP-21150
- [Partitioned-Based Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21150/sync/data-access-patterns/partitions/): Refactor to improve readability from C/80% reach in Readable to A/100% reach, or grade 10 in Hemingway down to 7 (screenshots attached to Jira ticket)
> (DOCSP-21150): Refactor for readability to grade 7 or A grade

- source/triggers/overview.txt
- https://jira.mongodb.org/browse/DOCSP-21148
- [About Triggers](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21148/triggers/overview/): Refactor to improve readability from C to B in Readability, or grade 11 to grade 8 in Hemingway. Screenshots in attached Jira ticket.
> (DOCSP-21148): Refactor Triggers Overview to improve readability to B grade or grade 8

- source/reference/realm-query-language.txt
- source/release-notes/changelogs/backend/changelog-backend-2022.rst
- source/sync/data-access-patterns/flexible-sync.txt
- 🌿😶‍🌫️🔥
- For information about flexible sync RQL limitations, check out https://docs.google.com/document/d/1xu8CimGLxfBJ6MlKEOW34QRB2I_9_vMQrxtcH_AQcXE/edit
- https://jira.mongodb.org/browse/DOCSP-22082
- [Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22082/release-notes/backend/)
- [Realm Query Language](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22082/reference/realm-query-language/) (updated query language limitations section)
- [Flexible Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22082/sync/data-access-patterns/flexible-sync/) (arrays of primitives are now eligible for Flexible Sync queries)
[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVI …
> (DOCSP-22082) 4/20 release notes

- source/sdk/java/examples/adapters.txt
- https://jira.mongodb.org/browse/DOCSP-21145
- [Display Collections - Java SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21145/sdk/java/examples/adapters/): Refactor to improve readability from D/63% reach to C/74% reach in Readable, or Grade 13 to grade 11 in Hemingway. I had a hard time improving past that point with all of the long method names on the page. 
> (DOCSP-21145): Refactor to improve readability to C grade or grade 11

- source/includes/destructive-schema-change-app-update.rst
- source/sdk/java/examples/reset-a-client-realm.txt
- https://jira.mongodb.org/browse/DOCSP-21149
- [Reset a Client Realm - Java SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21149/sdk/java/examples/reset-a-client-realm/): Refactor to improve readability from grade C/73% reach to grade B/93% reach in Readable, or grade 12 to 8 in Hemingway. Screenshots in attached Jira ticket.
> (DOCSP-21149): Refactor to improve readability from grade C to B, or grade 12 to 8

- source/sdk/node/fundamentals/write-transactions.txt
- source/sdk/react-native/fundamentals/write-transactions.txt
- https://jira.mongodb.org/browse/DOCSP-21153
- [Write Transactions - Node.js SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21153/sdk/node/fundamentals/write-transactions/): Refactor to improve readability from C/80% reach to B/96% reach in Readable, or grade 9 to grade 7 in Hemingway. Screenshots in attached Jira ticket.
- [Write Transactions - React Native SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21153/sdk/react-native/fundamentals/write-transactions/): Same page as above w/same refactors.
> (DOCSP-21153): Refactor to improve readability from grade C to B or grade 9 to 7

- docs-relese-notes.md
Adding the running docs-realm release notes from mid-Feb to present. For future docs-realm release notes, we'll add updates to this file in addition to posting them in Slack.
> Add docs-realm release notes to repo

- source/includes/offline-login.rst
- source/sdk/dotnet/examples/authenticate.txt
https://jira.mongodb.org/browse/DOCSP-22071
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/offline_login/sdk/dotnet/examples/authenticate/#offline-login
> Add Offline Login to .NET docs

- source/openapi-admin-v3.yaml
- (DOCS-15264): [Realm Admin API] Add unordered field to DB triggers
- [Admin API v3 > Triggers](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/unordered/admin/api/v3/#tag/triggers)
> (DOCS-15264): [Realm Admin API] Add unordered field to DB triggers

- config/redirects
- source/functions/mongodb.txt
- source/functions/mongodb/aggregate.txt
- source/mongodb.txt
- source/mongodb/crud-and-aggregation-apis.txt
- source/mongodb/link-a-data-source.txt
- source/reference/service-limitations.txt
- source/sdk/dotnet/examples/mongodb-remote-access.txt
- source/sdk/java/examples/mongodb-remote-access.txt
- source/sdk/swift/examples/mongodb-remote-access.txt
- source/web/mongodb.txt
- **NOTE** Rebased on top of https://github.com/mongodb/docs-realm/pull/1868 - contains commits from the other PR.
- (DOCSP-21900): Query > Aggregate
- [Functions > Query MongoDB Atlas > Aggregate](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fns-mql-aggregate/functions/mongodb/aggregate/)
> (DOCSP-21900): Query > Aggregate

- source/includes/note-partition-relationships.rst
- source/reference/service-limitations.txt
- source/schemas/relationships.txt
- source/sdk/dotnet/examples/open-a-realm.txt
- source/web/manage-email-password-users.txt
- https://jira.mongodb.org/browse/DOCSP-21515
- https://jira.mongodb.org/browse/DOCSP-22377
- https://jira.mongodb.org/browse/DOCSP-22199
- https://jira.mongodb.org/browse/DOCSP-21514
- [21515](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/lhf2/sdk/dotnet/examples/open-a-realm/#open-a-synced-realm-with-a-flexible-sync-configuration)
- [22377](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/lhf2/web/manage-email-password-users/#confirm-a-new-user-s-email-address)
- [22199](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/lhf2/reference/service-limitations/#request-traffic)
- [21514](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/lhf2/schemas/relationships/#overview)
> Small Ticket Bulk PR

- examples/node/Examples/read-and-write-data.js
- source/examples/generated/node/read-and-write-data.codeblock.read-and-write-bulk-update.js
- source/sdk/node/examples/read-and-write-data.txt
- source/sdk/react-native/examples/read-and-write-data.txt
- https://jira.mongodb.org/browse/DOCSP-22152
- [Read & Write Data - Node.js SDK # Bulk Update a Collection](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22152-replace-forEach-with-forOf/sdk/node/examples/read-and-write-data/#bulk-update-a-collection)
- [Read & Write Data - React Native SDK # Bulk Update a Collection](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22152-replace-forEach-with-forOf/sdk/react-native/examples/read-and-write-data/#bulk-update-a-collection)
> (DOCSP-22152): Replace forEach with for...of for improved performance

- docs-relese-notes.md
- https://jira.mongodb.org/browse/DOCSP-22408
> (DOCSP-22408): Add release notes for w/e April 29, 2022

- source/openapi-admin-v3.yaml
Document 2 previously undocumented endpoints for enable/disable hosting and seeing hosting config.
also included minor change for [DOCSP-22400](https://jira.mongodb.org/browse/DOCSP-22400)
- https://jira.mongodb.org/browse/DOCSP-22447
- [Admin API Reference, Hosting section](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22447/admin/api/v3/#tag/hosting)
> (DOCSP-22447): Add hosting config endpoint docs

- source/includes/steps-configure-advanced-rules-realm-ui.yaml
- https://jira.mongodb.org/browse/DOCSP-20184
- [Configure Advanced Rules](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20184/mongodb/configure-advanced-rules/#define-the-collection-rules)
> (DOCSP-20184): Add link to configure relationships in advanced mode

- source/functions/call-a-function.txt
- source/includes/important-sanitize-client-data-in-functions.rst
- source/sdk/dotnet/examples/call-a-function.txt
- source/sdk/java/examples/call-a-function.txt
- source/sdk/node/examples/call-a-function.txt
- source/sdk/react-native/examples/call-a-function.txt
- source/sdk/swift/examples/call-a-function.txt
- https://jira.mongodb.org/browse/DOCSP-11296
- [Functions -> Call a Function](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-11296/functions/call-a-function/#call-from-a-client-application)
- [Call a Function - every SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-11296/sdk/java/examples/call-a-function/#call-a-function-by-name)
> (DOCSP-11296): Functions: Add include reminding devs to sanitize client data

- source/includes/steps-remove-a-schema-ui.yaml
- source/schemas.txt
- source/schemas/remove-a-schema.txt
- https://jira.mongodb.org/browse/DOCSP-14873
- [Remove a Schema](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14873/schemas/remove-a-schema/): New page/procedure
> (DOCSP-14873): Document the procedure to remove a schema

- source/triggers/database-triggers.txt
- https://jira.mongodb.org/browse/DOCSP-19881
- [Database Triggers](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19881/triggers/database-triggers/#use-project-expressions-to-reduce-input-data-size)
> (DOCSP-19881): Explicitly state that project is inclusive only

- source/sync/data-model/development-mode.txt
- https://jira.mongodb.org/browse/DOCSP-22413
- [Development Mode](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22413/sync/data-model/development-mode/#development-database)
> DOCSP-22413: Clarify development mode write permissions

- docs-relese-notes.md
- https://jira.mongodb.org/browse/DOCSP-22504
> (DOCSP-22504): Add release notes for w/e May 6, 2022

- source/sync/data-access-patterns/flexible-sync-permissions-guide.txt
https://jira.mongodb.org/browse/DOCSP-22230
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/premissions-guide-admin/sync/data-access-patterns/flexible-sync-permissions-guide/#administrator-privileges
> Permissions guide: Admin Privileges

- source/sdk/react-native/examples/reset-a-client-realm.txt
> Fixed title on React Native page.

- examples/node/Examples/open-and-close-a-realm.js
- source/examples/generated/node/open-and-close-a-realm.codeblock.open-synced-realm-config.js
- source/examples/generated/node/open-and-close-a-realm.codeblock.open-synced-realm-offline-with-car-schema.js
- source/examples/generated/node/open-and-close-a-realm.codeblock.open-synced-realm-with-background-sync.js
- source/examples/generated/node/open-and-close-a-realm.codeblock.use-cached-user-to-login.js
- source/includes/node-open-a-synced-realm.rst
- source/sdk/node/examples/authenticate-users.txt
- source/sdk/node/examples/open-and-close-a-realm.txt
- source/sdk/react-native/examples/authenticate-users.txt
- source/sdk/react-native/examples/open-and-close-a-realm.txt
- https://jira.mongodb.org/browse/DOCSP-22069
- [Open and Close a Realm - Node.js](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22069-offline-login/sdk/node/examples/open-and-close-a-realm/)
- [Authenticate Users - Node.js](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22069-offline-login/sdk/node/examples/authenticate-users/)
- [Open and Close a Realm - React Native](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22069-offline-login/sdk/react-native/examples/open-and-close-a-realm/)
- [Authenticate Users - React Native](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22069-offline-login/sdk/react-native/examples/authenticate-users/) …
> (DOCSP-22069): offline login - Node.js

- docs-relese-notes.md
- https://jira.mongodb.org/browse/DOCSP-22661
> (DOCSP-22661): Add release notes for w/e May 13, 2022

- .github/workflows/ios.yml
- examples/ios/Examples/ReadWriteData.swift
- examples/ios/RealmExamples.xcodeproj/project.pbxproj
- source/examples/generated/code/start/ReadWriteData.codeblock.async-transaction.swift
- source/examples/generated/code/start/ReadWriteData.codeblock.transaction.swift
- source/sdk/swift/advanced-guides/threading.txt
- source/sdk/swift/examples/read-and-write-data.txt
TODO Before Merge:
- https://jira.mongodb.org/browse/DOCSP-19840
- [Read & Write Data](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19840/sdk/swift/examples/read-and-write-data/#perform-a-background-write): New section "Perform a Background Write" that covers Swift async writes
- [Threading](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19840/sdk/swift/advanced-guides/threading/): Add a "see also" to the top of the page pointing people at the async write documentation
> (DOCSP-19840): [Swift] Async Write documentation

- docs-relese-notes.md
- https://jira.mongodb.org/browse/DOCSP-22820
> (DOCSP-22820): Add release notes for w/e May 20, 2022

- source/includes/steps-install-swift-static-framework.yaml
- https://jira.mongodb.org/browse/DOCSP-22850
- [Install Realm - Swift SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22850/sdk/swift/install/#link-binaries): Add missing library to Static Framework, step 3.
> (DOCSP-22850): [Swift] Add libcompression.tbd to static install instructions

- source/index.txt
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/sdk-upgrade/
> Experiment: SDKs up one level

- source/sdk/java/api/io/realm/DynamicRealm.txt
- source/sdk/java/api/io/realm/MutableRealmInteger.txt
- source/sdk/java/api/io/realm/Realm.txt
- source/sdk/java/api/io/realm/RealmConfiguration.txt
- source/sdk/java/api/io/realm/annotations/LinkingObjects.txt
- source/sdk/java/api/io/realm/annotations/PrimaryKey.txt
- source/sdk/java/api/io/realm/mongodb/sync/SyncConfiguration.txt
- source/sdk/java/api/io/realm/mongodb/sync/SyncConfiguration/Builder.txt
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/yokedox-2/sdk/java/api/io/realm/annotations/LinkingObjects/
> Link improvements on yokedox

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-22994
> (DOCSP-22994): Add release notes for w/e May 27, 2022

- source/sdk/dotnet/advanced-guides/client-reset.txt
- source/sdk/dotnet/examples/sync-changes-between-devices.txt
https://jira.mongodb.org/browse/DOCSP-23078
Link to ProgressDirection:
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/main/sdk/dotnet/examples/sync-changes-between-devices/#monitor-sync-progress
All links in:
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/main/sdk/dotnet/advanced-guides/client-reset/
> fix TBD and /latest issues

- examples/dart/test/manage_sync_session_test.dart
- source/examples/generated/flutter/manage_sync_session_test.snippet.add-subscription.dart
- source/includes/note-flexible-sync-prerequisite.txt
- source/sdk/flutter/sync/open-synced-realm.txt
Fixes some code sniped and links to Flutter doc API
> Fix some code snippets

- examples/dart/pubspec.yaml
- examples/dart/test/manage_sync_session_test.dart
- snooty.toml
- source/examples/generated/flutter/manage_sync_session_test.snippet.add-subscription.dart
- source/includes/note-flexible-sync-prerequisite.txt
- source/sdk/dotnet/fundamentals/device-sync.txt
- source/sdk/flutter/app-services.txt
- source/sdk/flutter/realm-database.txt
- source/sdk/flutter/realm-database/data-types.txt
- source/sdk/flutter/realm-database/define-realm-object-schema.txt
- source/sdk/flutter/sync.txt
- source/sdk/flutter/sync/open-synced-realm.txt
- source/sdk/flutter/users/multiple-users.txt
- source/sdk/java/api/io/realm/mongodb/AppConfiguration.txt
- source/sdk/java/fundamentals/device-sync.txt
- source/sdk/kotlin/app-services/overview.txt
- source/sdk/kotlin/sync/overview.txt
- source/sdk/node/fundamentals/device-sync.txt
- source/sdk/react-native/fundamentals/device-sync.txt
- source/sdk/swift/fundamentals/device-sync.txt
- n/a
- [Flutter SDK section (minor things throughout)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/flutter_fix/sdk/flutter)
> Misc Flutter fixes

- source/sdk/node/examples/define-a-realm-object-model.txt
- [Define a Realm Object Schema - Node.js SDK # Define an Asymmetric Object](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fix-asymmetric-sync-pageOrder/sdk/node/examples/define-a-realm-object-model/#define-an-asymmetric-object)
> Quickfix - rearrange Asymmetric Sync section order

- examples/dotnet/Examples/FlexibleSyncExamples.cs
- source/examples/generated/dotnet/FlexibleSyncExamples.snippet.botostrap-a-subscription.cs
- source/examples/generated/dotnet/Guitar.codeblock.guitar-object.cs
- source/examples/generated/dotnet/Program.codeblock.collection-notifications.cs
- source/examples/generated/dotnet/Program.codeblock.delete.cs
- source/examples/generated/dotnet/Program.codeblock.get-instance.cs
- source/examples/generated/dotnet/Program.codeblock.read-filter-sort.cs
- source/examples/generated/dotnet/Program.codeblock.update.cs
- source/examples/generated/dotnet/Program.codeblock.write.cs
- source/sdk/dotnet/examples/flexible-sync.txt
https://jira.mongodb.org/browse/DOCSP-22536
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/bootstrap/sdk/dotnet/examples/flexible-sync/#add-a-query-to-the-set-of-subscriptions
> Add info & code for bootstrapping realm with initial subscription

- source/sdk/swift/examples/modify-an-object-schema.txt
- source/sdk/swift/examples/swiftui-guide.txt
- https://jira.mongodb.org/browse/DOCSP-23245
- [Modify an Object Schema](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-23245/sdk/swift/examples/modify-an-object-schema/): New `seealso` near the top of the page pointing folks to the SwiftUI migration examples
- [SwiftUI Guide](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-23245/sdk/swift/examples/swiftui-guide/#inject-an-opened-realm): Clarify wording in the `Inject an Opened Realm` section
> (DOCSP-23245): Clarify SwiftUI migration details based on user feedback

- source/sdk/kotlin/app-services/authenticate-users.txt
- https://jira.mongodb.org/browse/DOCSP-22992
- [Auth Users, Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22992/sdk/kotlin/app-services/authenticate-users/)
> (DOCSP-22992): Multiplatform auth for Kotlin SDK

- examples/dart/pubspec.lock
- examples/dart/pubspec.yaml
- examples/dart/test/manage_sync_session_test.dart
- source/examples/generated/flutter/manage_sync_session_test.snippet.add-subscription.dart
- source/examples/generated/flutter/manage_sync_session_test.snippet.remove-all-subscriptions.dart
- source/examples/generated/flutter/manage_sync_session_test.snippet.remove-subscriptions-by-name.dart
- source/examples/generated/flutter/manage_sync_session_test.snippet.remove-subscriptions-by-query.dart
- source/examples/generated/flutter/manage_sync_session_test.snippet.remove-subscriptions-by-reference.dart
- source/examples/generated/flutter/manage_sync_session_test.snippet.update-subscriptions-new-query.dart
- source/examples/generated/flutter/read_write_data_test.snippet.query-realm-list.dart
- source/sdk/flutter/sync/manage-sync-session.txt
- update flutter sdk code examples to make all tests pass (previously some were skipped)
- update docs on behavior of update a flex sync subscription
- https://jira.mongodb.org/browse/DOCSP-23193
- [Manage Sync Session (Flutter SDK)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-23193/sdk/flutter/sync/manage-sync-session)
> (DOCSP-23193): Update Flutter Manage Sync Session

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-23375
- https://jira.mongodb.org/browse/DOCSP-23381
> (DOCSP-23381): Add release notes for w/e June 17 and June 24

- source/sdk/swift/event-library.txt
This PR incorporates tech review feedback left on #1917 
- [Event Library](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/event-library-tech-review-feedback/sdk/swift/event-library/)
> Swift SDK Event Library page: Incorporate tech review feedback

- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AppClientTest.kt
- snooty.toml
- source/examples/generated/kotlin/AppClientTest.snippet.handle-errors.kt
- source/sdk/kotlin.txt
- source/sdk/kotlin/errors.txt
- source/sdk/kotlin/errors/app.txt
- source/sdk/kotlin/errors/realm.txt
- source/sdk/kotlin/sync/open-a-synced-realm.txt
- https://jira.mongodb.org/browse/DOCSP-22453
- [Handle Errors - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22453/sdk/kotlin/errors/) (Whole section)
- [App Errors](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22453/sdk/kotlin/errors/app/)
- [Realm Errors](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22453/sdk/kotlin/errors/realm/)
> (DOCSP-22453): Errors API, Kotlin SDK 1.0.0

- examples/ios/SwiftUIFlexSyncExample/SwiftUIFlexSyncExampleApp.swift
- source/examples/generated/swiftui/examples/SwiftUIFlexSyncExampleApp.snippet.item-details-view.swift
- source/examples/generated/swiftui/examples/SwiftUIFlexSyncExampleApp.snippet.preview-detail-view.swift
- source/examples/generated/swiftui/examples/SwiftUIFlexSyncExampleApp.snippet.preview-extend-model-class-with-objects.swift
- source/examples/generated/swiftui/examples/SwiftUIFlexSyncExampleApp.snippet.preview-extend-model-class-with-realm.swift
- source/examples/generated/swiftui/examples/SwiftUIFlexSyncExampleApp.snippet.preview-view-associated-with-sync.swift
- source/examples/generated/swiftui/examples/SwiftUIFlexSyncExampleApp.snippet.preview-with-realm.swift
- source/sdk/swift/examples/swiftui-guide.txt
Note for reviewer: please ignore the failing CI; it is failing due to a sync issue not related to this PR.
- https://jira.mongodb.org/browse/DOCSP-23033
- [SwiftUI Guide -> Use Realm with SwiftUI Previews](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-23033/sdk/swift/examples/swiftui-guide/#use-realm-with-swiftui-previews): New section w/guidance on using Realm with SwiftUI Previews
> (DOCSP-23033): Add guidance around using Realm with SwiftUI Previews

- source/sdk/swift/examples/swiftui-guide.txt
- https://jira.mongodb.org/browse/DOCSP-23481
- [SwiftUI Guide/Open a Realm with a Configuration](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-23481/sdk/swift/examples/swiftui-guide/#open-a-realm-with-a-configuration)
> (DOCSP-23481): Incorporate docs feedback to clarify using configurations w/SwiftUI

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-23432
> (DOCSP-23432): Add docs release notes for w/e July 1, 2022

- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SchemaTest.kt
- source/examples/generated/kotlin/SchemaTest.snippet.to-many-relationship.kt
- reported through feedback widget
- [Relationships - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/to-many-relationship-fix/sdk/kotlin/realm-database/schemas/relationships/)
> Fix "To-Many" relationship example snippet

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-23626
> (DOCSP-23626): Add docs release notes for w/e July 7, 2022

- examples/dart/test/task_project_models_test.dart
- examples/dart/test/task_project_models_test.g.dart
- source/examples/generated/flutter/task_project_models_test.snippet.task-project-models.dart
- source/introduction.txt
fixes https://github.com/realm/realm-dart/issues/716
n/a 
- [Realm Query Language](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fix_rql_flutter_oid/reference/realm-query-language)
> Add ObjectId to Flutter RQL example

- source/examples/generated/flutter/task_project_models_test.snippet.task-project-models.dart
fix error in code snipper with duplicate `@PrimaryKey()` annotation
n/a
- [Realm Query Language](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/hotfix_flutter_rql_example/reference/realm-query-language/)
> Fix code example error

- config/redirects
- source/includes/realm-database.rst
- source/sdk/swift.txt
- https://jira.mongodb.org/browse/DOCSP-23762
> (DOCSP-23762): Fix snooty build errors

- examples/kotlin/README.md
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/MigrateFromJavaToKotlinSDKTest.kt
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SchemaTest.kt
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SyncTest.kt
- source/examples/generated/kotlin/AppClientTest.snippet.handle-errors.kt
- source/examples/generated/kotlin/MigrateFromJavaToKotlinSDKTest.snippet.open-a-realm.kt
- source/examples/generated/kotlin/SyncTest.snippet.configure-a-flexible-sync-realm.kt
- source/examples/generated/kotlin/SyncTest.snippet.remove-all-subscriptions-to-an-object-type.kt
- chatted with Ben, fixing the tests for y'alls benefit
- also added a README so other people can run the tests more easily
- Example app only
> Fixing Kotlin SDK tests from infinite hang wonkiness

- examples/dotnet/Examples/WriteExamples.cs
- source/examples/CRUD/BatchUpdate.cs
- source/examples/generated/dotnet/WriteExamples.snippet.transaction.cs
- source/examples/generated/dotnet/WriteExamples.snippet.update-collection.cs
- https://jira.mongodb.org/browse/DOCSP-23629
> (DOCSP-23629): Fix typo in code examples

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-23720
> (DOCSP-23720): Add docs release notes for w/e July 15, 2022

- examples/node/Examples/relationships-and-embedded-objects.js
- examples/node/Examples/relationships-and-embedded-objects.ts
- examples/node/package-lock.json
- source/examples/generated/node/relationships-and-embedded-objects.snippet.obtain-inverse-relationship-dynamically.js
- source/examples/generated/node/relationships-and-embedded-objects.snippet.obtain-inverse-relationship-dynamically.ts
- source/sdk/node/fundamentals/relationships-and-embedded-objects.txt
- source/sdk/react-native/fundamentals/relationships-and-embedded-objects.txt
- https://jira.mongodb.org/browse/DOCSP-12992
- [Relationships & Embedded Objects - Node.js SDK # Dynamically Obtain an Inversely Linked Object](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-12992-inverseRelationships-JS/sdk/node/fundamentals/relationships-and-embedded-objects/#dynamically-obtain-an-inversely-linked-object)
- [Relationships & Embedded Objects - React Native SDK # Dynamically Obtain an Inversely Linked Object](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-12992-inverseRelationships-JS/sdk/react-native/fundamentals/relationships-and-embedded-objects/#dynamically-obtain-an-inversely-linked-object)
> (DOCSP-12992): document that inverse relationships can also be dynamic - JS

- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/NotificationsTest.kt
- source/examples/generated/kotlin/CRUDTest.snippet.filter.kt
- source/examples/generated/kotlin/NotificationsTest.snippet.cancel-change-listener.kt
- source/examples/generated/kotlin/NotificationsTest.snippet.query-change-listener.kt
- source/examples/generated/kotlin/NotificationsTest.snippet.realm-list-change-listener.kt
- source/examples/generated/kotlin/NotificationsTest.snippet.realm-object-change-listener.kt
- source/examples/generated/kotlin/NotificationsTest.snippet.sample-data-models.kt
- source/examples/generated/kotlin/NotificationsTest.snippet.sample-data-seed.kt
- source/sdk/kotlin/realm-database.txt
- source/sdk/kotlin/realm-database/frozen-arch.txt
- source/sdk/kotlin/realm-database/react-to-changes.txt
- Robust Notifications documentation for Kotlin SDK
- [React to Changes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/kotlinnotifications/sdk/kotlin/realm-database/react-to-changes/)
> Notifications for Kotlin SDK (Object, Results, List)

- source/sdk/swift/react-to-changes.txt
- https://jira.mongodb.org/browse/DOCSP-24002
- [React to Changes - Swift SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24002/sdk/swift/react-to-changes/#register-a-collection-change-listener): New "Important" callout in the Register a Collection Change Listener section
> (DOCSP-24002): Add note about collection change listener throwing an error

- source/sdk/node/advanced/access-custom-user-data.txt
- source/sdk/react-native/advanced/access-custom-user-data.txt
Updated the formatting of code blocks in Access Custom User Data pages for Node.js and React Native SDKs to match that of the general Access Custom User Data page -- with js formatting.
- https://jira.mongodb.org/browse/DOCSP-23846
- [Access Custom User Data - Node.js SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-23846/sdk/node/advanced/access-custom-user-data/)
> (DOCSP-23846): Updated Formatting in Code Examples

- .github/workflows/readability.yml
- Calculate_Readability_Score.py
This PR adds the Readability workflow to score changed docs pages for readability.
See working demo at: https://github.com/dacharyc/ghaction-readability-demo/pull/31
> Add readability check to Realm docs

- source/studio/open-realm-file.txt
- https://jira.mongodb.org/browse/DOCSP-23816
- [Open a Realm File](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-23816/studio/open-realm-file/#error-opening-realm-file): New "Error Opening Realm File" section
> (DOCSP-23816): Add troubleshooting info for realm file mismatch errors

- source/sdk/swift/model-data/model-data-device-sync.txt
- https://jira.mongodb.org/browse/DOCSP-24026
- [Model Data with Device Sync - Swift SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24026/sdk/swift/model-data/model-data-device-sync/#create-object-models-and-schemas): New section "Create Object Models and Schemas"
> (DOCSP-24026): Add info about generating matching schema and realm models

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-23843
- https://jira.mongodb.org/browse/DOCSP-23960
> Add docs release notes for w/e July 22 and July 29

- examples/dotnet/Examples/EmbeddedExamples.cs
- examples/dotnet/Examples/WorkWithRealm.cs
- source/examples/generated/dotnet/WorkWithRealm.snippet.call-handle-collection-changed.cs
- source/examples/generated/dotnet/WorkWithRealm.snippet.clear-collection.cs
- source/examples/generated/dotnet/WorkWithRealm.snippet.define-handle-collection-changed.cs
- source/examples/generated/dotnet/WorkWithRealm.snippet.get-notification-if-collection-is-cleared.cs
- source/sdk/dotnet/examples/react-to-changes.txt
- https://jira.mongodb.org/browse/DOCSP-23222
- [React to Changes - .NET SDK # Check if the ChangeSet Has Been Cleared](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-23222-ChangeSet-IsCleared-dotnet/sdk/dotnet/examples/react-to-changes/#check-if-the-changeset-has-been-cleared)
> (DOCSP-23222): Change Set is cleared - .NET SDK

- examples/node/Examples/landing-page.js
- source/examples/generated/node/landing-page.snippet.node-landing-update-live-objects.js
- [Realm Node.js SDK (landing-page) # Update Live Objects](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24461-nodeLandingPage-update-live-objects-code-fix/sdk/node/#update-live-objects)
> (DOCSP-24461): Node.js landing page - "Update Live Objects" bug fix

- examples/web/nextjs-blog/env.local.example
- examples/web/nextjs-blog/package-lock.json
- examples/web/nextjs-blog/package.json
- examples/web/nextjs-blog/pages/_app.js
- examples/web/nextjs-blog/pages/graphQL.js
- examples/web/nextjs-blog/pages/index.js
- examples/web/nextjs-blog/pages/mongodb-data-access.js
- examples/web/nextjs-blog/pages/server-side-rendering.js
- examples/web/nextjs-blog/realm/AppServicesContext.js
- examples/web/nextjs-blog/realm/auth.js
> Server side rendering

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-24387
> (DOCSP-24387): Add docs release notes for w/e August 12

- examples/dart/pubspec.lock
- examples/dart/pubspec.yaml
- examples/dart/test/authenticate_users_test.dart
- source/examples/generated/flutter/authenticate_users_test.snippet.delete-user.dart
- source/examples/generated/flutter/task_project_models_test.snippet.task-project-models.dart
- source/sdk/flutter/users.txt
- source/sdk/flutter/users/authenticate.txt
- source/sdk/flutter/users/delete-user.txt
document deleting users in realm flutter sdk
- https://jira.mongodb.org/browse/DOCSP-22353
- [Delete Users (Flutter SDK)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22353/sdk/flutter/users/delete-user)
> (DOCSP-22353): Flutter Delete User

- source/sdk/flutter/users/delete-user.txt
address missed comment in #2099 
> fix verb tense

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-24524
> (DOCSP-24524): Add docs release notes for w/e August 19

- source/tutorial/dotnet.txt
- source/tutorial/swiftui.txt
- https://jira.mongodb.org/browse/DOCSP-24832
- [.NET (Xamarin) Tutorial # Start with the Template](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fix-broken-link-swift-xamarin/tutorial/dotnet/#start-with-the-template)
- [.iOS Swift Tutorial # Start with the Template](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fix-broken-link-swift-xamarin/tutorial/swiftui/#start-with-the-template)
> (DOCSP-24832): Fix broken links 'template-apps' in Xamarin and SwiftUI

- source/sdk/kotlin/sync/subscribe.txt
- https://jira.mongodb.org/browse/DOCSP-24865
- [Subscribe to Queryable Fields - Kotlin SDK # Update Subscriptions with a New Query](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fix-comment-kotlin-flexsync-page/sdk/kotlin/sync/subscribe/#update-subscriptions-with-a-new-query
> (DOCSP-24865): Fix Incorrect Name for Update Subscription Example - Kotlin SDK

- examples/dart/pubspec.lock
- examples/dart/pubspec.yaml
- examples/dart/test/authenticate_users_test.dart
- examples/dart/test/open_realm_test.dart
- source/examples/generated/flutter/open_realm_test.snippet.default-realm-name-path.dart
- source/examples/generated/flutter/open_realm_test.snippet.default-storage-path.dart
- source/sdk/flutter/install.txt
- source/sdk/flutter/realm-database/open-and-close-a-realm.txt
Document default configuration info for Flutter
- https://jira.mongodb.org/browse/DOCSP-24561
- [Open and Close a Realm (Flutter SDK)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24561/sdk/flutter/realm-database/open-and-close-a-realm/#customize-default-configuration)
> (DOCSP-24561): Flutter default config docs

- source/tutorial/swiftui.txt
- [SwiftUI iOS Tutorial](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/swiftui-tutorial-tweaks/tutorial/swiftui/)
> Small SwiftUI tutorial improvements

- source/sdk/dotnet/fundamentals/data-binding.txt
https://github.com/mongodb/docs-realm/pull/2115
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/quickfix/sdk/dotnet/fundamentals/data-binding/
> Quick fix of grammatical and format errors

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-24899
> (DOCSP-24899): Add early docs release notes for w/e September 1

- docs-release-notes.md
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/QuickStartTest.kt
- source/examples/generated/kotlin/QuickStartTest.snippet.quick-start-open-a-synced-realm.kt
- source/examples/generated/kotlin/QuickStartTest.snippet.quick-start.kt
- source/index.txt
- source/sdk/dotnet/fundamentals/data-binding.txt
- source/sdk/kotlin/quick-start.txt
- source/tutorial.txt
- source/tutorial/dotnet.txt
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/tutorials_phase1/tutorial/
and
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/tutorials_phase1/tutorial/dotnet/
> two small link fixes

- source/sdk/flutter/realm-database/define-realm-object-schema.txt
update supported types on PKS for all currently supported types
- https://jira.mongodb.org/browse/DOCSP-25020
- [Define a Realm Object Schema - Flutter SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-25020/sdk/flutter/realm-database/define-realm-object-schema/)
> (DOCSP-25020): Update Flutter supported PK types

- source/includes/flex-sync-limitations.rst
- source/sdk/dotnet/advanced-guides/threading.txt
- source/sdk/dotnet/examples/open-a-realm.txt
- source/sdk/dotnet/troubleshooting.txt
- source/sdk/swift/model-data/define-model/object-models.txt
- source/sdk/swift/test-and-debug.txt
- Replace smart quotes (“ and ”) with mono quotes (")
> Remove smart quotes

- examples/node/Examples/realm-query-language.js
- examples/node/package-lock.json
- examples/node/package.json
- source/examples/generated/realm-query-language/realm-query-language.snippet.comparison-operators.js
- source/examples/generated/realm-query-language/realm-query-language.snippet.list-comparisons-collection.js
- source/examples/generated/realm-query-language/realm-query-language.snippet.list-comparisons-parameterized.js
- source/examples/generated/realm-query-language/realm-query-language.snippet.list-comparisons-static.js
- source/examples/generated/realm-query-language/realm-query-language.snippet.set-operators.js
- source/includes/flex-sync-limitations.rst
- source/realm-query-language.txt
- (DOCSP-23965): RQL list query comparisons
- [Realm Query Language](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/rql-lists/realm-query-language/)
> (DOCSP-23965): RQL list query comparisons

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-24997
> (DOCSP-24492): Add docs release notes for w/e September 9, 2022

- snooty.toml
new C++ landing page not in sidebar. this PR fixes
n/a
- [C++ (Alpha)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fix_cpp_landing/sdk/cpp)
> Add C++ landing page to sidebar

- source/sdk/flutter/realm-database/data-types.txt
remove incorrect sentence that should have been removed before and conflicts with the subsequent (correct) sentence.
n/a
- [Data Types (Flutter SDK)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/dart_supported_types_fix/sdk/flutter/realm-database/data-types/)
> fix incorrect & conflicting sentence

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-25156
> (DOCSP-25156): Add docs release notes for w/e September 16, 2022

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-25346
> (DOCSP-25346): Add docs release notes for w/e September 23, 2022

- source/web.txt
Adjust Next.js Guide TOC position. move upwards
n/a
- [Next.js guide (see TOC)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/nextjs_in_toc_adjust/web/nextjs)
> Adjust Next.js Guide TOC position

- examples/dart/scripts/bluehawk_create_snippets.sh
- examples/dart/scripts/test.sh
- examples/dart/test/open_flexible_sync_realm_test.dart
- source/examples/generated/flutter/open_flexible_sync_realm_test.snippet.sync-error-handler.dart
- source/sdk/flutter/sync.txt
- source/sdk/flutter/sync/handle-sync-errors.txt
- source/sdk/flutter/sync/open-synced-realm.txt
document sync error handling
- https://jira.mongodb.org/browse/DOCSP-25077
- [Handle Sync Errors (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-25077/sdk/flutter/sync/handle-sync-errors/)
> (DOCSP-25077): Handle sync errors 

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-25447
> (DOCSP-25447): Add docs release notes for w/e September 30, 2022

- source/sdk/kotlin/quick-start.txt
N/A
- [Quick Start - Kotlin](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/kotlin-quickstart-fixes/sdk/kotlin/quick-start/)
> Kotlin QuickStart fixes

- examples/kotlin/settings.gradle.kts
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.user-delete.kt
- source/includes/note-deleting-user-doesnt-delete-custom-data.rst
- source/sdk/kotlin/app-services.txt
- source/sdk/kotlin/app-services/delete-users.txt
- source/sdk/swift/users/create-and-delete-users.txt
- https://jira.mongodb.org/browse/DOCSP-20093
- [Delete Users - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20093-delete-user-kotlin/sdk/kotlin/app-services/delete-users/)
> (DOCSP-20093): Delete user - Kotlin

- source/sdk/dotnet.txt
- source/sdk/dotnet/install.txt
- https://jira.mongodb.org/browse/DOCSP-25563
- [Realm .NET SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-25563/sdk/dotnet/): New landing page adapted from the [Swift SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-25563/sdk/swift/). Curious if we would want to feature different content in "Recommended Reading" - I picked a few things to put there, but am not sure what's top-of-mind for .NET devs.
- [Install Realm for .NET](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-25563/sdk/dotnet/install/): Move "Supported Platforms" from old landing page to Install page
> (DOCSP-25563): Update .NET landing page to new style

- examples/kotlin/settings.gradle.kts
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/QuickStartTest.kt
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/RegistrationTest.kt
- source/examples/generated/kotlin/QuickStartTest.snippet.quick-start-open-a-synced-realm.kt
- source/examples/generated/kotlin/QuickStartTest.snippet.quick-start.kt
- source/examples/generated/kotlin/RegistrationTest.snippet.email-password-registration.kt
- https://jira.mongodb.org/browse/DOCSP-25707
- [QuickStart - Kotlin](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/realmresults-query-kotlin/sdk/kotlin/quick-start/)
- [Register Users - Kotlin](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/realmresults-query-kotlin/sdk/kotlin/app-services/register-users/)
> (DOCSP-25707): realm-kotlin@1.2.0: Change user.identity to user.id

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-25551
> (DOCSP-25551): Add docs release notes for w/e October 7, 2022

- source/sdk/flutter/realm-database/define-realm-object-schema.txt
add nullability to primary keys
- https://jira.mongodb.org/browse/DOCSP-24582
- [Define a Realm Object Schema (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24582/sdk/flutter/realm-database/define-realm-object-schema/)
> (DOCSP-24582): Nullable PKs

- source/sdk/flutter/realm-database/data-types.txt
Nullable types in Lists support
- https://jira.mongodb.org/browse/DOCSP-24579
- [Data Types (FLutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24579/sdk/flutter/realm-database/data-types)
> (DOCSP-24579): Nullable types in Lists support

- examples/cpp/examples.cpp
- source/examples/generated/cpp/examples.snippet.define-models.cpp
- source/sdk/cpp.txt
- https://jira.mongodb.org/browse/DOCSP-25729
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cpp17/sdk/cpp/
> (DOCSP-25729): Update for C++17 support

- source/web.txt
- source/web/quickstart.txt
- source/web/react-web-quickstart.txt
- https://jira.mongodb.org/browse/DOCSP-25850
- [Quick Start - Realm Web SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/rename-web-quickstart/web/quickstart/)
- [Quick Start with React - Realm Web SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/rename-web-quickstart/web/react-web-quickstart/)
> (DOCSP-25850): Rename Realm QuickStart with React

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-25768
> (DOCSP-25768): Add docs release notes for w/e October 14

- source/sdk/flutter.txt
Refactor Flutter SDK landing page 
- https://jira.mongodb.org/browse/DOCSP-25560
- [Flutter SDK (landing page)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-25560/sdk/flutter/)
> (DOCSP-25560): Refactor Flutter landing page 

- source/sdk/flutter/realm-database/bundle.txt
- source/sdk/flutter/realm-database/freeze.txt
- source/sdk/flutter/realm-database/update-realm-object-schema.txt
implement @desistefanova post Realm Flutter SDK 0.5.0+beta release feedback. 
Feedback in the closed PRs for the features: 
- https://github.com/mongodb/docs-realm/pull/2202
- https://github.com/mongodb/docs-realm/pull/2198
- https://github.com/mongodb/docs-realm/pull/2211
- https://github.com/mongodb/docs-realm/pull/2190
- https://jira.mongodb.org/browse/DOCSP-26026
- [Bundle (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26026/sdk/flutter/realm-database/bundle/)
- [Freeze (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26026/sdk/flutter/realm-database/freeze/)
- [Update Realm Object Schema (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26026/sdk/flutter/realm-da …
> (DOCSP-26026): Flutter SDK 0.5.0+beta docs feedback

- examples/ios/Examples/ReadRealmObjects.swift
- examples/ios/RealmExamples.xcodeproj/project.pbxproj
- examples/ios/SwiftUICatalog/Model.swift
- examples/ios/SwiftUICatalog/SwiftUICatalogApp.swift
- examples/ios/SwiftUICatalog/Views/FilterData.swift
- examples/ios/SwiftUICatalog/Views/SectionedResults.swift
- examples/ios/SwiftUICatalogUITests/SwiftUICatalogUITests.swift
- source/examples/generated/code/start/ReadRealmObjects.snippet.get-sectioned-results.swift
- source/examples/generated/code/start/ReadRealmObjects.snippet.models.swift
- source/examples/generated/code/start/ReadRealmObjects.snippet.section-query-results-callback.swift
- source/examples/generated/code/start/ReadRealmObjects.snippet.section-query-results.swift
- source/examples/generated/code/start/ReadRealmObjects.snippet.sectioned-result-variable.swift
- source/examples/generated/swiftui/FilterData.snippet.observed-filtered-sectioned-results.swift
- source/examples/generated/swiftui/Model.snippet.computed-var-sectioned-results.swift
- source/examples/generated/swiftui/Model.snippet.objects.swift
- source/examples/generated/swiftui/SectionedResults.snippet.observed-sectioned-results.swift
- source/examples/generated/swiftui/SectionedResults.snippet.sectioned-dogs-list-view.swift
- source/sdk/swift/crud/read.txt
- source/sdk/swift/model-data/define-model/supported-types.txt
- source/sdk/swift/realm-database.txt
- source/sdk/swift/swiftui/filter-data.txt
- source/sdk/swift/swiftui/react-to-changes.txt
- https://jira.mongodb.org/browse/DOCSP-25134
- [Why Realm Database?](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-25134/sdk/swift/realm-database/#live-queries): Add mention of sectioned results to "Live Queries"
- [Supported Types](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-25134/sdk/swift/model-data/define-model/supported-types/): Move some info around in "Collections" section, add subheadings, add details around Sectioned Results
- [CRUD/Read](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-25134/sdk/swift/crud/read/#section-query-results): New "Section Query Results" section w/code examples & info
- [SwiftUI/React to Changes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docswo …
> (DOCSP-25134): [Swift] Document Sectioned Results

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-25913
> (DOCSP-25913): Add docs release notes for w/e October 21

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-26072
> (DOCSP-26072): Add docs release notes for w/e October 28

- source/sdk/dotnet.txt
- source/sdk/dotnet/install.txt
- https://jira.mongodb.org/browse/DOCSP-24237
- [.NET SDK landing page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24237-update-supported-dotnet-platforms/sdk/dotnet/)
- [Install Realm for .NET: Supported Platforms](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24237-update-supported-dotnet-platforms/sdk/dotnet/install/)
> (DOCSP-24237): Updating .NET supported platforms on landing page

- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.link-credentials.kt
- source/includes/link-user-identities.rst
- source/sdk/java/advanced-guides/link-user-identities.txt
- source/sdk/kotlin/app-services.txt
- source/sdk/kotlin/app-services/link-credentials.txt
- https://jira.mongodb.org/browse/DOCSP-25673
- [Link User Identities](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-25673-link-credentials-kotlin/sdk/kotlin/app-services/link-credentials/)
> (DOCSP-25673): Link credentials Kotlin

- source/includes/note-realmreact-version-requirements-for-realmjs.rst
- source/sdk/react-native/use-realm-react.txt
- https://jira.mongodb.org/browse/DOCSP-26028
- [Use Realm React](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26028-Realm-React-Version-Reqs/sdk/react-native/use-realm-react/)
> (DOCSP-26028): version requirement for Realm React

- source/sdk/kotlin/sync/open-a-synced-realm.txt
- https://jira.mongodb.org/browse/DOCSP-26290
- [Open a Synced Realm - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/swap-fs-and-pbs-tabs-in-kotlin/sdk/kotlin/sync/open-a-synced-realm/)
> (DOCSP-26290): swap flex sync and pbs tab order - Kotlin

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-26222
> (DOCSP-26222): Add docs release notes for w/e November 4

- source/sdk/flutter/realm-database/define-realm-object-schema.txt
Update documentation on indexable fields to include all indexable fields that have been added in https://github.com/realm/realm-dart/pull/875. 
- https://jira.mongodb.org/browse/DOCSP-24589
- [Define a Realm Object Schema (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24589/sdk/flutter/realm-database/define-realm-object-schema)
> (DOCSP-24589): Flutter indexable fields

- source/index.txt
- Move Java below the fold
- Realm is a database now
- 
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/index-update/
> Update text on landing page, re-order cards

- examples/dart/pubspec.lock
- examples/dart/pubspec.yaml
- examples/dart/test/backlinks_test.dart
- examples/dart/test/backlinks_test.g.dart
- source/examples/generated/flutter/backlinks_test.snippet.backlink-models.dart
- source/sdk/flutter/realm-database/define-realm-object-schema.txt
Document backlinks support for Flutter.
- https://jira.mongodb.org/browse/DOCSP-24573
- [Define Realm Object Schema (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24573/sdk/flutter/realm-database/define-realm-object-schema/#inverse-relationship)
> (DOCSP-24573): Flutter - backlinks

- examples/dart/test/backlinks_test.dart
- examples/dart/test/client_reset_test.dart
- source/examples/generated/flutter/client_reset_test.snippet.discard.dart
- source/examples/generated/flutter/client_reset_test.snippet.manual-fallback.dart
- source/examples/generated/flutter/client_reset_test.snippet.manual.dart
- source/examples/generated/flutter/client_reset_test.snippet.recover-or-discard.dart
- source/examples/generated/flutter/client_reset_test.snippet.recover.dart
- source/includes/client-recovery-rules.rst
- source/sdk/flutter/sync/handle-sync-errors.txt
Document client reset for Realm Flutter SDK
- https://jira.mongodb.org/browse/DOCSP-24570
- [Handle Sync Errors (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24570/sdk/flutter/sync/handle-sync-errors/)
> (DOCSP-24570): Flutter Client Reset docs

- source/includes/cli-login.rst
- (DOCSP-25471) Remove Realm CLI
- [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli/)
> (DOCSP-25471) Remove Realm CLI

- examples/web/src/__tests__/authentication-log-in-and-out.test.js
- source/examples/generated/web/authentication-log-in-and-out.test.snippet.email-password-auth.js
- (DOCSP-26406) typo in realm-web auth
- [Authenticate a User - Web SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/web-typo/web/authenticate/#std-label-web-login-email-password)
> (DOCSP-26406) typo in realm-web auth

- source/sdk/react-native/examples/define-a-realm-object-model.txt
- https://jira.mongodb.org/browse/DOCSP-26456
> (DOCSP-26456): Make UUID Indexable - React Native SDK

- examples/dotnet/Examples/Convert.cs
- examples/dotnet/Examples/ErrorHandler.cs
- source/examples/generated/dotnet/Convert.snippet.nonsync-to-sync.cs
- source/examples/generated/dotnet/ErrorHandler.snippet.cancel-token.cs
- source/sdk/dotnet/examples/sync-changes-between-devices.txt
https://jira.mongodb.org/browse/DOCSP-20211 
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20211/sdk/dotnet/examples/sync-changes-between-devices/#cancel-a-sync-session
> add cancellationtoken info

- source/sdk/dotnet/fundamentals/object-models-and-schemas.txt
- source/sdk/flutter/realm-database/define-realm-object-schema.txt
- source/sdk/java/fundamentals/object-models-and-schemas.txt
- source/sdk/kotlin/realm-database/schemas/index.txt
- source/sdk/node/examples/define-a-realm-object-model.txt
- source/sdk/react-native/examples/define-a-realm-object-model.txt
- source/sdk/swift/model-data/define-model/object-models.txt
- https://jira.mongodb.org/browse/DOCSP-12674
- [Object Models and Schemas - Java SDK # Indexes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-12674-RealmDB-Index-Details/sdk/java/fundamentals/object-models-and-schemas/#indexes)
- [Index a Field - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-12674-RealmDB-Index-Details/sdk/kotlin/realm-database/schemas/index/)
- [Object Models and Schemas - Java SDK # Indexes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-12674-RealmDB-Index-Details/sdk/dotnet/fundamentals/object-models-and-schemas/#indexes)
- [Define a Realm Object Schema - Node.js SDK # Index a Property](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/D …
> (DOCSP-12674): Add Index Details 

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-26354
> (DOCSP-26354): Add docs release notes for w/e November 11

- source/includes/sync-memory-performance.rst
- source/sdk/dotnet/fundamentals/device-sync.txt
- source/sdk/flutter/sync.txt
- source/sdk/java/fundamentals/device-sync.txt
- source/sdk/kotlin/sync/overview.txt
- source/sdk/node/fundamentals/device-sync.txt
- source/sdk/react-native/fundamentals/device-sync.txt
- source/sdk/swift/application-services.txt
- source/sdk/swift/quick-start.txt
- source/sdk/swift/sync/add-sync-to-app.txt
- source/sdk/swift/sync/flexible-sync.txt
This PR guides developers using sync to keep edited objects in memory until all edits to the object have been completed. This prevents excessive writes.
- https://jira.mongodb.org/browse/DOCSP-14225
I added the same section to all of these SDK pages. @dacharyc, I felt like there were two locations in the Swift docs that this could go. I added it to both for now, but would love to get your thoughts on where it should go.
- [Flutter](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14225/sdk/flutter/sync/#group-updates-for-improved-performance)
- [Java](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14225/sdk/java/fundamentals/device-sync/#group-updates-for-improved-performance)
- …
> (DOCSP-14225): Add generic sync performance improvement note

- examples/dart/pubspec.lock
- examples/dart/pubspec.yaml
- examples/dart/test/quick_start_test.dart
- source/examples/generated/flutter/quick_start_test.snippet.create-many-realm-objects.dart
- source/examples/generated/flutter/schemas.snippet.sync-schema.dart
- source/sdk/flutter/quick-start.txt
- source/sdk/flutter/realm-database/read-and-write-data.txt
Document the Flutter SDK `Realm.addAll()` method.
- https://jira.mongodb.org/browse/DOCSP-26080
- [Quick Start (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26080/sdk/flutter/quick-start/)
- [Read & Write Data (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26080/sdk/flutter/realm-database/read-and-write-data/)
- 
> (DOCSP-26080): Flutter document Realm.addAll()

- examples/ios/Examples/AddSyncToApp.swift
- examples/ios/Examples/AsymmetricSync.swift
- examples/ios/Examples/BundleRealms.swift
- examples/ios/Examples/ConvertSyncLocalRealms.swift
- examples/ios/Examples/FlexibleSync.swift
- examples/ios/Examples/QuickStartFlexSync.swift
- source/examples/generated/code/start/AddSyncToApp.snippet.create-todo.swift
- source/examples/generated/code/start/AddSyncToApp.snippet.open-synced-realm.swift
- source/examples/generated/code/start/AsymmetricSync.snippet.create-asymmetric-object.swift
- source/examples/generated/code/start/AsymmetricSync.snippet.open-asymmetric-sync-realm.swift
- source/examples/generated/code/start/BundleRealms.snippet.copy-synced-realm-for-bundling.swift
- source/examples/generated/code/start/BundleRealms.snippet.open-bundled-synced-realm.swift
- source/examples/generated/code/start/ConvertSyncLocalRealms.snippet.convert-local-to-sync.swift
- source/examples/generated/code/start/ConvertSyncLocalRealms.snippet.convert-sync-to-local.swift
- source/examples/generated/code/start/ConvertSyncLocalRealms.snippet.convert-sync-to-sync.swift
- source/examples/generated/code/start/FlexibleSync.snippet.add-multiple-subscriptions.swift
- source/examples/generated/code/start/FlexibleSync.snippet.add-single-subscription.swift
- source/examples/generated/code/start/FlexibleSync.snippet.check-before-adding-subscription.swift
- source/examples/generated/code/start/FlexibleSync.snippet.flex-sync-open-realm.swift
- source/examples/generated/code/start/FlexibleSync.snippet.remove-all-subscriptions.swift
- source/examples/generated/code/start/FlexibleSync.snippet.remove-single-subscription.swift
- source/examples/generated/code/start/FlexibleSync.snippet.remove-subscriptions-to-object-type.swift
- source/examples/generated/code/start/FlexibleSync.snippet.subscribe-to-all-objects-of-a-type.swift
- source/examples/generated/code/start/FlexibleSync.snippet.update-subscription-by-name.swift
- source/examples/generated/code/start/FlexibleSync.snippet.update-subscription.swift
- source/examples/generated/code/start/QuickStartFlexSync.snippet.open-synced-realm.swift
- source/examples/generated/code/start/QuickStartFlexSync.snippet.use-realm.swift
- source/sdk/swift/quick-start.txt
- source/sdk/swift/sync/flexible-sync.txt
- https://jira.mongodb.org/browse/DOCSP-25178
Updated code examples can be seen on these pages:
- [Add Device Sync to an App](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-25178/sdk/swift/sync/add-sync-to-app/)
- [Stream Data to Atlas](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-25178/sdk/swift/sync/stream-data-to-atlas/)
- [Bundle Synchronized Realms](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-25178/sdk/swift/realm-files/bundle-a-realm/)
- [Open a Synced Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-25178/sdk/swift/sync/configure-and-open-a-synced-realm/#open-a-synced-realm)
- [Manage Flexible Sync …
> (DOCSP-25178): Swift - refactor async code examples to show MainActor

- source/includes/encrypt-atlas-device-sync.rst
- source/includes/encrypt-mult-processes.rst
- source/sdk/dotnet/examples/encrypt-a-realm.txt
- source/sdk/dotnet/fundamentals/realm-encryption.txt
- source/sdk/flutter/realm-database/encrypt.txt
- source/sdk/java/advanced-guides/encryption.txt
- source/sdk/node/advanced/encrypt.txt
- source/sdk/react-native/advanced/encrypt.txt
- source/sdk/swift/realm-files/encrypt-a-realm.txt
- https://jira.mongodb.org/browse/DOCSP-19850
- [Encrypt a Realm - Flutter](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-19850-encryption-with-atlas/sdk/flutter/realm-database/encrypt/)
- [Encrypt a Realm - Java](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-19850-encryption-with-atlas/sdk/java/advanced-guides/encryption/)
- [Encryption - .NET](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-19850-encryption-with-atlas/sdk/dotnet/fundamentals/realm-encryption/)
- [Encrypt a Realm - Node.js](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-19850-encryption-with-atlas/sdk/node/advanced/encrypt/)
- [Encrypt a Realm - React …
> (DOCSP-19850): Update realm encryption with Device Sync description

- source/sdk/flutter/app-services/call-function.txt
Flutter Add example Function to Call a Function page for flutter sdk.
- https://jira.mongodb.org/browse/DOCSP-26402
- [Call a Function (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26402/sdk/flutter/app-services/call-function/)
> (DOCSP-26402): Flutter Add example Function to Call a Function page

- examples/dart/pubspec.lock
- examples/dart/pubspec.yaml
- examples/dart/test/functions_test.dart
- source/examples/generated/flutter/functions_test.snippet.call-function.dart
- source/examples/generated/flutter/schemas.snippet.sync-schema.dart
Small update to how calling Atlas Functions works for Flutter SDK release 0.8.0+rc.
- https://jira.mongodb.org/browse/DOCSP-26551
- [Call a Function (Flutter](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26551/sdk/flutter/app-services/call-function)
> (DOCSP-26551): Flutter 0.8.0+rc Functions update

- .github/workflows/swiftui.yml
- examples/ios/Examples/SwiftUI.swift
- examples/ios/RealmExamples.xcodeproj/project.pbxproj
- examples/ios/SwiftUICatalog/Model.swift
- examples/ios/SwiftUICatalog/SwiftUICatalogApp.swift
- examples/ios/SwiftUICatalog/Views/CreateObjects.swift
- examples/ios/SwiftUICatalogUITests/SwiftUICatalogUITests.swift
- source/examples/generated/code/start/SwiftUI.snippet.copy-to-realm-with-create.swift
- source/examples/generated/code/start/SwiftUI.snippet.get-an-object-realm.swift
- source/examples/generated/code/start/SwiftUI.snippet.swiftui-company-model.swift
- source/examples/generated/code/start/SwiftUI.snippet.thaw-the-passed-in-object.swift
- source/examples/generated/code/start/SwiftUI.snippet.write-with-swiftui-observed-realm-object.swift
- source/examples/generated/swiftui/CreateObjects.snippet.add-dog-to-person-view.swift
- source/examples/generated/swiftui/CreateObjects.snippet.add-dog-to-person-view.swift.rst
- source/sdk/swift/swiftui/write.txt
- https://jira.mongodb.org/browse/DOCSP-25034
- [Write Data - SwiftUI](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-25034/sdk/swift/swiftui/write/#append-an-object-to-a-list): New sections starting with "Append an Object to a List"
> (DOCSP-25034): SwiftUI - add details around more complex write cases

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-26511
> (DOCSP-26511): Add docs release notes for w/e November 18

- snooty.toml
- source/sdk/flutter/users.txt
Flutter "User Management" landing page
- https://jira.mongodb.org/browse/DOCSP-26078
- [User Management (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26078/sdk/flutter/users/)
> (DOCSP-26078):  Flutter "User Management" landing page

- source/web/install.txt
if you are not using AWS.
- https://jira.mongodb.org/browse/HELP-39788
> Use a recent version of Realm Web. v1.5.1 uses a base URL which fails

- source/studio/modify-objects.txt
https://jira.mongodb.org/browse/DOCSP-26690
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26690/studio/modify-objects/#save-the-data
> Add info about "flatted" and reorder the section

- source/sdk/kotlin/quick-start.txt
- https://jira.mongodb.org/browse/DOCSP-26693
- [Quick Start - Kotlin SDK # Authenticate a User](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/kotlin-link-fix/sdk/kotlin/quick-start/#authenticate-a-user)
> (DOCSP-26693): kotlin quickstart broken link fix

- source/sdk/flutter.txt
Add Dart/Flutter example projects to sidenav
- https://jira.mongodb.org/browse/DOCSP-26656
- [Flutter SDK (just look at sidenav)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26656/sdk/flutter/)
> (DOCSP-26656): Add Dart/Flutter example projects to sidenav

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-26634
> (DOCSP-26634): Add docs release notes for w/e November 25

- .github/pull_request_template.md
See https://github.com/mongodb/docs-app-services/pull/244
> (DOCSP-19610): Add reminder checklist to PR template

- source/sdk/dotnet/quick-start.txt
https://jira.mongodb.org/browse/DOCSP-26531
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26531/sdk/dotnet/quick-start/#open-a-synced-realm
> Clean up .NET Quickstart

- examples/cpp/README.md
- https://jira.mongodb.org/browse/DOCSP-26776
> (DOCSP-26776): Add a README for the CPP examples project

- source/sdk/dotnet/crud/filter.txt
https://jira.mongodb.org/browse/DOCSP-14921
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14921/sdk/dotnet/crud/filter/#unsupported-linq-operators
> Add unsupported LINQ types info

- source/sdk/react-native/install.txt
- source/sdk/react-native/quick-start.txt
* Updated the section for Prerequisites to the current status.
* Changed Node SDK to React Native SDK in quick start page.
> React Native Doc Updates

- examples/dotnet/Examples/AuthenticationExamples.cs
- source/examples/generated/dotnet/AuthenticationExamples.snippet.get_user_token.cs
- source/includes/user-access-token.rst
- source/sdk/dotnet/manage-users/authenticate.txt
https://jira.mongodb.org/browse/DOCSP-26771
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26771/sdk/dotnet/manage-users/authenticate/#get-a-user-access-token
> add new snippet & bluehawk it

- source/sdk/dotnet/quick-start.txt
- source/sdk/dotnet/sync/add-sync-to-app.txt
fix swift -> .net copy pasta
n/a
n/a
> Fix Swfit -> .NET copy/paste errors

- source/sdk/flutter/install.txt
add extra step for using Flutter SDK w macOS emulator
- https://jira.mongodb.org/browse/DOCSP-26279
- [Install (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26279/sdk/flutter/install)
> (DOCSP-26279): macOS emulator install instructions

- .gitmodules
- examples/cpp/.gitignore
- examples/cpp/CMakeLists.txt
- examples/cpp/README.md
Confirmed this successfully compiles, builds, and runs with cmake/make.
- https://jira.mongodb.org/browse/DOCSP-26811
> (DOCSP-26811): Remove cpprealm git submodule, use FetchContent instead

- examples/cpp/README.md
- examples/cpp/examples.cpp
- source/examples/generated/cpp/examples.snippet.open-a-synced-realm.cpp
- source/examples/generated/cpp/examples.snippet.open-default-realm.cpp
- source/examples/generated/cpp/examples.snippet.open-realm-at-path.cpp
- source/sdk/cpp.txt
- source/sdk/cpp/realm-files/configure-and-open-a-realm.txt
- https://jira.mongodb.org/browse/DOCSP-26727
- [Configure & Open a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26727/sdk/cpp/realm-files/configure-and-open-a-realm/): New page based on the Swift SDK "Configure & Open a Realm" page
> (DOCSP-26727): [CPP] Configure and open a realm page

- source/sdk/flutter/quick-start.txt
typo and link text fixes on Flutter Quick Start 
n/a
- [Quick Start (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/flutter_quick_start_fixes/sdk/flutter/quick-start)
> Flutter Quick Start edits

- source/sdk/react-native/quick-start.txt
- source/sdk/react-native/sync-data/open-a-synced-realm.txt
- source/sdk/react-native/test-and-debug/testing.txt
- source/sdk/react-native/use-realm-react.txt
- https://jira.mongodb.org/browse/DOCSP-26851
N/A
> (DOCSP-26851): fix refs + lower title underline

- examples/cpp/README.md
This PR doesn't have its own Jira, as I was working through the example repo to learn. I noticed some minor ways we can improve the readme, so this is kind of a follow-up.
- https://jira.mongodb.org/browse/DOCSP-26490
> Minor C++ example readme updates

- source/web.txt
fix broken link noted in feedback widget
n/a
- [Web SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fix_nextjs_link/web/)
> fix broken link

- examples/dotnet/README.md
- source/index.txt
- source/sdk.txt
- source/sdk/dotnet/compatibility.txt
- source/sdk/dotnet/crud/threading.txt
- source/sdk/dotnet/install.txt
- source/sdk/dotnet/model-data/define-object-model.txt
- source/sdk/dotnet/realm-files/bundle-a-realm.txt
- source/sdk/dotnet/realm-files/encrypt-a-realm.txt
https://jira.mongodb.org/browse/DOCSP-23233
- [Encrypting Files](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/maui/sdk/dotnet/realm-files/encrypt-a-realm)
- [Compatability](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/maui/sdk/dotnet/compatibility/) 
- [Install](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/maui/sdk/dotnet/install/)
> Adding maui and links

- source/sdk/java/examples/sync-changes-between-devices.txt
- https://jira.mongodb.org/browse/DOCSP-26888
- [Sync Changes Between Devices - Java SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-26888-fix-typo/sdk/java/examples/sync-changes-between-devices/#check-upload---download-progress-for-a-sync-session)
> (DOCSP-26888): Fixing typo in Java ProgressListener

- examples/dart/test/authenticate_users_test.dart
- examples/dart/test/writeCustomUserData.js
- source/examples/generated/flutter/authenticate_users_test.snippet.write-custom-user-data-function.dart
- source/examples/generated/flutter/writeCustomUserData.snippet.write-custom-user-data.js
- source/sdk/flutter/app-services.txt
- source/sdk/flutter/app-services/call-function.txt
- source/sdk/flutter/users/custom-user-data.txt
Light documentation on how you can write custom user data from Atlas Function. 
Adding b/c there won't be MongoDB Data Access for GA, but should be documented way to write to custom user data. 
- https://jira.mongodb.org/browse/DOCSP-26617
- [Custom User Data](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26617/sdk/flutter/users/custom-user-data)
> (DOCSP-26617): Write Custom User Data from Function

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-26848
> (DOCSP-26848): Add docs release notes for w/e December 9

- source/sdk/java/fundamentals/relationships.txt
- source/sdk/kotlin/realm-database/schemas/relationships.txt
- source/sdk/kotlin/realm-database/schemas/supported-types.txt
- https://jira.mongodb.org/browse/DOCSP-26537
- [Supported Types - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-26537-kotlin-primitives-list/sdk/kotlin/realm-database/schemas/supported-types/)
> (DOCSP-26537): Updating list of Kotlin-supported data types

- source/sdk/dotnet/unity.txt
I hope that this will render correctly!
> Corrected section title for .NET

- source/includes/flex-sync-unsupported-progress-notifications.rst
- source/sdk/dotnet/sync/sync-progress.txt
- source/sdk/java/examples/sync-changes-between-devices.txt
- source/sdk/node/examples/sync-changes-between-devices.txt
- source/sdk/react-native/sync-data/check-upload-download-progress.txt
- source/sdk/swift/sync/sync-progress.txt
- https://jira.mongodb.org/browse/DOCSP-26906
- [Java SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26906/sdk/java/examples/sync-changes-between-devices/#check-upload---download-progress-for-a-sync-session)
- [.NET SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26906/sdk/dotnet/sync/sync-progress/#monitor-sync-progress)
- [Node.js SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26906/sdk/node/examples/sync-changes-between-devices/#check-upload---download-progress-for-a-sync-session)
- [React Native SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26906/sdk/react-native/sync-data/check-upload-download-progress/)
- [Swift …
> (DOCSP-26906): Add note about unsupported Sync progress notifications to SDKs

- examples/cpp/CMakeLists.txt
- examples/cpp/README.md
- examples/cpp/define-object-model.cpp
- examples/cpp/examples.cpp
- source/examples/generated/cpp/define-object-model.snippet.model-with-embedded-object.cpp
- source/examples/generated/cpp/define-object-model.snippet.model-with-embedded-object.cpp.rst
- source/examples/generated/cpp/define-object-model.snippet.model-with-ignored-field.cpp
- source/examples/generated/cpp/define-object-model.snippet.to-many-relationship.cpp
- source/examples/generated/cpp/define-object-model.snippet.to-one-relationship.cpp
- source/examples/generated/cpp/examples.snippet.define-a-schema.cpp
- source/sdk/cpp.txt
- source/sdk/cpp/model-data.txt
- source/sdk/cpp/model-data/object-models.txt
- source/sdk/cpp/model-data/relationships.txt
- source/sdk/cpp/model-data/supported-types.txt
- source/sdk/cpp/realm-files/configure-and-open-a-realm.txt
- https://jira.mongodb.org/browse/DOCSP-26728
- [Object Types and Schemas](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26728/sdk/cpp/model-data/object-models/)
- [Supported Data Types](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26728/sdk/cpp/model-data/supported-types/)
- [Relationships](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26728/sdk/cpp/model-data/relationships/)
Since we don't yet have CI to automatically run the tests, here is the output of running these tests locally:
```shell
Randomness seeded to: 3770930234
Business: {
: 
: MongoDB
: {
: email@example.com
: 123-456-7890
}
}
Point of Interest: Grand Canyon Village
POI Latitude: 36.0554
Company named:Dunder Mifflin
dog: {
: …
```
> (DOCSP-26728): C++ Model Data Section

- examples/kotlin/build.gradle.kts
- examples/kotlin/settings.gradle.kts
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/NotificationsTest.kt
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SchemaTest.kt
- https://jira.mongodb.org/browse/DOCSP-27100
N/A
> Bug fix: java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.ir.declarations.IrValueParameter

- source/sdk/flutter/install.txt
Document how to update Dart Standalone/Flutter SDKs.
- https://jira.mongodb.org/browse/DOCSP-26079
- [Install (Flutter), Update Package Version section](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26079/sdk/flutter/install#update-package-version)
> (DOCSP-26079): Update Dart Standalone/Flutter SDKs

- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/OpenARealmTest.kt
- source/examples/generated/kotlin/OpenARealmTest.snippet.open-an-in-memory-realm.kt
- source/sdk/kotlin/realm-database/open-and-close-a-realm.txt
- https://jira.mongodb.org/browse/DOCSP-26258
- [Open a Realm - Kotlin SDK # Open an In Memory Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/kotlin-in-memory/sdk/kotlin/realm-database/open-and-close-a-realm/#open-an-in-memory-realm)
> (DOCSP-26258): In Memory Realm Support - Kotlin SDK

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-27024
> (DOCSP-27024): Add docs release notes for w/e December 16

- examples/ios/.swiftlint.yml
- examples/ios/Examples/BundleRealms.swift
- examples/ios/Examples/ObjectModels.swift
- examples/ios/RealmExamples.xcodeproj/project.pbxproj
- source/examples/generated/code/start/ObjectModels.snippet.rename-a-property.swift
- https://jira.mongodb.org/browse/DOCSP-26827
> (DOCSP-26827): Update SwiftLint & fix a couple of linting errors

- examples/cpp/authentication.cpp
- source/examples/generated/cpp/authentication.snippet.log-user-in.cpp
- source/examples/generated/cpp/authentication.snippet.register-user.cpp
Super small fix for C++ that I didn't include in my [recent PR](https://github.com/mongodb/docs-realm/pull/2419).
> [C++] Make non-constants not capitalized

- source/sdk/cpp/app-services/connect-to-app.txt
- source/sdk/cpp/install.txt
- source/sdk/cpp/realm-files/configure-and-open-a-realm.txt
- https://jira.mongodb.org/browse/DOCSP-27127
- [Install Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27127/sdk/cpp/install/#build-an-android-app)
- [Configure & Open a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27127/sdk/cpp/realm-files/configure-and-open-a-realm/#open-a-non-sync-realm)
- [Connect to App Services](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27127/sdk/cpp/app-services/connect-to-app/#access-the-app-client)
> (DOCSP-27127): [C++] Add information about building an app with Android

- examples/dart/test/authenticate_users_test.dart
- source/examples/generated/flutter/authenticate_users_test.snippet.user-metadata.dart
- source/sdk/flutter/users.txt
- source/sdk/flutter/users/user-metadata.txt
Flutter user metadata page.
Also fix broken tests.
- https://jira.mongodb.org/browse/DOCSP-27163
- [User Metadata (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27163/sdk/flutter/users/user-metadata/)
> (DOCSP-27163): Flutter user metadata

- source/sdk/flutter/users/user-metadata.txt
https://jira.mongodb.org/browse/DOCSP-27189
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/bugfix-header-flutter-user-metadata/sdk/flutter/users/user-metadata/
> (DOCSP-27189): Bug fix -  "Flutter/User-Metadata" rST issue with title underline

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-27121
N/A
> (DOCSP-27121): Release Notes for 12/23/2022

- examples/node/Examples/define-a-realm-object-schema.js
- source/examples/generated/node/define-a-realm-object-schema.snippet.define-a-realm-object-schema-define-js-classes.js
- source/examples/generated/node/define-a-realm-object-schema.snippet.define-a-realm-object-schema-js-classes-open-and-access-properties.js
- source/examples/generated/node/define-a-realm-object-schema.snippet.define-object-properties.js
- source/examples/generated/node/define-a-realm-object-schema.snippet.define-schema-as-object.js
- source/sdk/node/examples/define-a-realm-object-model.txt
This is a fast follow update to clean up work done in a [previous PR](https://github.com/mongodb/docs-realm/pull/2437).
- [Define a Realm Object Model](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/bluehawkify-fast-follow/sdk/node/examples/define-a-realm-object-model/)
> Bluehawkify fast follow updates

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-27187
> Add docs release notes for w/e December 30

- source/sdk/react-native/realm-database/schemas/primary-key.txt
-https://jira.mongodb.org/browse/DOCSP-26987
- [Specify a Primary Key - React Native SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/specify-primary-key/sdk/react-native/realm-database/schemas/primary-key/)
> (DOCSP-26987): @realm/react-ify 'Specify a Primary Key'

- source/examples/generated/kotlin/QuickStartTest.snippet.quick-start-open-a-local-realm.kt
- source/sdk/kotlin/install/android.txt
- source/sdk/kotlin/install/kotlin-multiplatform.txt
- source/sdk/kotlin/quick-start.txt
- source/sdk/kotlin/sync/overview.txt
Incorporated changes from https://docs.google.com/document/d/1M2QoA-auyOaWZ88PeL1_6QylcEkqt3Aqv3ppOvuuGtI/edit#heading=h.watv1kfii35
> Kotlin Sync Feedback Document changes

- source/sdk/react-native/realm-database/schemas/optional.txt
- https://jira.mongodb.org/browse/DOCSP-26986
- [Specify an Optional Property - React Native SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/specify-optional-property/sdk/react-native/realm-database/schemas/optional/)
> (DOCSP-26986): @realm/react-ify 'Specify an Optional Property'

- examples/react-native/__tests__/js/models/Car.js
- examples/react-native/__tests__/ts/models/Car.ts
- source/examples/generated/react-native/js/Car.snippet.js-car-schema.js
- source/examples/generated/react-native/ts/Car.snippet.ts-car-schema.ts
- source/sdk/react-native/realm-database/schemas/default-value.txt
- https://jira.mongodb.org/browse/DOCSP-26990
- [Define a Default Property Value - React Native SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26990-default/sdk/react-native/realm-database/schemas/default-value/)
> (DOCSP-26990): @realm/react-ify 'Define a Default Property Value'

- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.access-token-get.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.access-token-refresh.kt
- source/sdk/kotlin/app-services/authenticate-users.txt
- https://jira.mongodb.org/browse/DOCSP-26302
- Kotlin SDK - [Authenticate Users](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-26302-kotlin-user-methods/sdk/kotlin/app-services/authenticate-users/#get-a-user-access-token)
> (DOCSP-26302): Documenting New Kotlin User Properties

- examples/cpp/define-object-model.cpp
- examples/cpp/examples.cpp
- source/examples/generated/cpp/define-object-model.snippet.check-size-and-access-results.cpp
- source/examples/generated/cpp/define-object-model.snippet.create-embedded-object.cpp
- source/examples/generated/cpp/define-object-model.snippet.create-object-with-to-many-relationship.cpp
- source/examples/generated/cpp/define-object-model.snippet.create-object-with-to-one-relationship.cpp
- source/examples/generated/cpp/define-object-model.snippet.filter-using-type-safe-query.cpp
- source/examples/generated/cpp/define-object-model.snippet.read-objects-from-realm.cpp
- source/examples/generated/cpp/define-object-model.snippet.update-embedded-object.cpp
- source/examples/generated/cpp/examples.snippet.create-an-object.cpp
- source/examples/generated/cpp/examples.snippet.delete-an-object.cpp
- source/examples/generated/cpp/examples.snippet.single-object-model.cpp
- source/examples/generated/cpp/examples.snippet.update-an-object.cpp
- source/sdk/cpp.txt
- source/sdk/cpp/crud.txt
- source/sdk/cpp/crud/create.txt
- source/sdk/cpp/crud/delete.txt
- source/sdk/cpp/crud/read.txt
- source/sdk/cpp/crud/update.txt
- https://jira.mongodb.org/browse/DOCSP-26729
- [Create](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26729/sdk/cpp/crud/create/)
- [Read](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26729/sdk/cpp/crud/read/)
- [Update](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26729/sdk/cpp/crud/update/)
- [Delete](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26729/sdk/cpp/crud/delete/)
Since we don't yet have CI to automatically run the tests, here is the output of running these tests locally:
```shell
Randomness seeded to: 1000146614
Business: {
: 
: MongoDB
: {
: email@example.com
: 123-456-7890
}
}
Point of Interest: Grand Canyon Village
POI Latitude: 36.0554 …
```
> (DOCSP-26729): C++ CRUD section

- examples/react-native/__tests__/js/models/Employee.js
- examples/react-native/__tests__/ts/models/Employee.ts
- source/examples/generated/react-native/js/Employee.snippet.js-employee-schema.js
- source/examples/generated/react-native/ts/Employee.snippet.ts-employee-schema.ts
- source/sdk/react-native/realm-database/schemas/remap.txt
- https://jira.mongodb.org/browse/DOCSP-26991
- [Remap a Property - React Native](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-26991-remap-a-property/sdk/react-native/realm-database/schemas/remap/)
> (DOCSP-26991): @realm-react-ify 'Remap a Property'

- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/DeleteARealm.kt
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/EncryptARealmTest.kt
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SchemaTest.kt
- source/examples/generated/kotlin/EncryptARealmTest.snippet.encrypt-a-realm.kt
- source/sdk/kotlin/realm-files.txt
- source/sdk/kotlin/realm-files/encrypt-a-realm.txt
- https://jira.mongodb.org/browse/DOCSP-26509
- [Encrypt a Realm - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/encrypt-a-realm-kt/sdk/kotlin/realm-files/encrypt-a-realm/)
> (DOCSP-26509): Encrypt a Realm - Kotlin SDK

- examples/dart/test/data_types_test.dart
- examples/dart/test/data_types_test.g.dart
- source/examples/generated/flutter/data_types_test.snippet.realmlist-model.dart
- source/examples/generated/flutter/data_types_test.snippet.realmlist-use.dart
- source/examples/generated/flutter/data_types_test.snippet.realmresults-use.dart
- source/sdk/flutter/model-data.txt
- source/sdk/flutter/model-data/collections.txt
- source/sdk/flutter/model-data/data-types.txt
- source/sdk/flutter/realm-database.txt
Expand documentation for Flutter collections.
Also expand docs on Realm Database overview. content adapted from .NET.
- https://jira.mongodb.org/browse/DOCSP-27153
- [Collections (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27153/sdk/flutter/model-data/collections/)
- [Data Types (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27153/sdk/flutter/model-data/data-types/)
- [Realm Database Overview (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27153/sdk/flutter/realm-database/)
[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md …
> (DOCSP-27153): Flutter collections

- examples/dart/test/quick_start_test.dart
- examples/dart/test/read_write_data_test.dart
- examples/dart/test/read_write_data_test.g.dart
- source/examples/generated/flutter/quick_start_test.snippet.query-realm-objects-with-filter.dart
- source/examples/generated/flutter/read_write_data_test.snippet.create-multiple-objects.dart
- source/examples/generated/flutter/read_write_data_test.snippet.create-object.dart
- source/examples/generated/flutter/read_write_data_test.snippet.delete-all-objects-of-type.dart
- source/examples/generated/flutter/read_write_data_test.snippet.delete-multiple-objects.dart
- source/examples/generated/flutter/read_write_data_test.snippet.delete-one-object.dart
- source/examples/generated/flutter/read_write_data_test.snippet.filter.dart
- source/examples/generated/flutter/read_write_data_test.snippet.models.dart
- source/examples/generated/flutter/read_write_data_test.snippet.query-all-objects.dart
- source/examples/generated/flutter/read_write_data_test.snippet.query-object-by-pk.dart
- source/examples/generated/flutter/read_write_data_test.snippet.query-realm-list.dart
- source/examples/generated/flutter/read_write_data_test.snippet.return-from-write.dart
- source/examples/generated/flutter/read_write_data_test.snippet.sort.dart
- source/examples/generated/flutter/read_write_data_test.snippet.update-object.dart
- source/examples/generated/flutter/read_write_data_test.snippet.upsert.dart
- source/examples/generated/flutter/read_write_data_test.snippet.write-async.dart
- source/sdk/flutter/read-and-write-data.txt
Misc improvements and added methods to Flutter Read & Write Data and Quick Start pages.
- https://jira.mongodb.org/browse/DOCSP-27158
- [Read & Write Data (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27158/sdk/flutter/read-and-write-data)
- [Quick Start (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27158/sdk/flutter/quick-start)
> (DOCSP-27158): Flutter Read & Write Data and Quick Start improvements

- .github/workflows/c++.yml
- examples/cpp/README.md
- examples/cpp/authentication.cpp
Also runs format-on-save on the C++ README...
https://jira.mongodb.org/browse/DOCSP-26812
> (DOCSP-26812): Add C++ CI

- source/sdk/swift/model-data/define-model/supported-types.txt
- https://jira.mongodb.org/browse/DOCSP-27294
- [Supported Types](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27294/)
> (DOCSP-27294): Fix typo and missing optional UUID

- examples/ios/Examples/QueryEngine.swift
- source/examples/generated/code/start/QueryEngine.snippet.models.swift
- source/examples/generated/code/start/QueryEngine.snippet.tsq-collections-contains-any.swift
- source/examples/generated/code/start/QueryEngine.snippet.tsq-collections-contains.swift
- source/sdk/swift/crud/filter-data.txt
- https://jira.mongodb.org/browse/DOCSP-25733
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/tsq-collections/sdk/swift/crud/filter-data/#collections
> (DOCSP-25733): Update type-safe-query for collections examples

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-27211
> (DOCSP-27211): Add docs release notes for w/e January 6, 2023

- source/sdk/react-native/bootstrap-with-expo.txt
- https://jira.mongodb.org/browse/DOCSP-27336
- [Bootstrap with Expo - React Native SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)
> (DOCSP-27336): link to Expo template on NPM

- examples/cpp/CMakeLists.txt
- examples/cpp/README.md
- examples/cpp/authentication.cpp
- examples/cpp/supported-types.cpp
- source/examples/generated/cpp/supported-types.snippet.optional-binary-data.cpp
- source/examples/generated/cpp/supported-types.snippet.optional-bool.cpp
- source/examples/generated/cpp/supported-types.snippet.optional-date.cpp
- source/examples/generated/cpp/supported-types.snippet.optional-double.cpp
- source/examples/generated/cpp/supported-types.snippet.optional-enum.cpp
- source/examples/generated/cpp/supported-types.snippet.optional-int.cpp
- source/examples/generated/cpp/supported-types.snippet.optional-string.cpp
- source/examples/generated/cpp/supported-types.snippet.optional-uuid.cpp
- source/examples/generated/cpp/supported-types.snippet.required-binary-data.cpp
- source/examples/generated/cpp/supported-types.snippet.required-bool.cpp
- source/examples/generated/cpp/supported-types.snippet.required-date.cpp
- source/examples/generated/cpp/supported-types.snippet.required-double.cpp
- source/examples/generated/cpp/supported-types.snippet.required-enum.cpp
- source/examples/generated/cpp/supported-types.snippet.required-int.cpp
- source/examples/generated/cpp/supported-types.snippet.required-list.cpp
- source/examples/generated/cpp/supported-types.snippet.required-mixed-type.cpp
- source/examples/generated/cpp/supported-types.snippet.required-string.cpp
- source/examples/generated/cpp/supported-types.snippet.required-uuid.cpp
- source/sdk/cpp/model-data/supported-types.txt
Note: currently I'm running into an error with optional binary data, so I've commented that out and could use some help debugging.
- https://jira.mongodb.org/browse/DOCSP-27286
- [Supported Types](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27286/sdk/cpp/model-data/supported-types/)
> (DOCSP-27286): [C++] Test and bluehawk supported type declarations

- examples/kotlin/shared/build.gradle.kts
- examples/kotlin/shared/src/commonMain/kotlin/com/mongodb/realm/realmkmmapp/Log.kt
- https://jira.mongodb.org/browse/DOCSP-27408
N/A
> (DOCSP-27408): Replace Kotlin Logger w/ Kermit Logger

- source/sdk/flutter/model-data/update-realm-object-schema.txt
Document `LocalConfiguration.shouldDeleteIfMigrationNeeded`.
- https://jira.mongodb.org/browse/DOCSP-26114
- [Update Realm Object Schema](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26114/sdk/flutter/model-data/update-realm-object-schema)
> (DOCSP-26114): Document `LocalConfiguration.shouldDeleteIfMigrationNeeded`

- examples/ios/Examples/SyncedRealmCRUD.swift
- examples/ios/RealmExamples.xcodeproj/project.pbxproj
- source/examples/generated/code/start/SyncedRealmCRUD.snippet.flexible-sync-crud-model.swift
- source/examples/generated/code/start/SyncedRealmCRUD.snippet.flexible-sync-subscription-setup.swift
- source/examples/generated/code/start/SyncedRealmCRUD.snippet.successful-write.swift
- source/examples/generated/code/start/SyncedRealmCRUD.snippet.write-outside-flexible-sync-query.swift
- source/examples/generated/code/start/SyncedRealmCRUD.snippet.write-outside-permissions.swift
- source/sdk/swift/sync.txt
- source/sdk/swift/sync/configure-and-open-a-synced-realm.txt
- source/sdk/swift/sync/write-to-synced-realm.txt
- https://jira.mongodb.org/browse/DOCSP-27219
- [Write to a Synced Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27219/sdk/swift/sync/write-to-synced-realm/): New page
> (DOCSP-27219): (Swift SDK) Add a Write to a Synced Realm page

- source/includes/realm-database.rst
- source/sdk/kotlin/realm-database/overview.txt
Addresses https://github.com/mongodb/docs-realm/issues/2487
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/room-not-core-data/sdk/kotlin/realm-database/overview/
> Update Kotlin comparison - use Room instead of Core Data

- examples/ios/Examples/QueryEngine.swift
- source/examples/generated/code/start/QueryEngine.snippet.models.swift
- source/examples/generated/code/start/QueryEngine.snippet.tsq-set-operators.swift
- source/sdk/swift/crud/filter-data.txt
- https://jira.mongodb.org/browse/DOCSP-26022
- [Filter Data - Swift SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26022/sdk/swift/crud/filter-data/#set-operators)
> (DOCSP-26022): Add TSQ Set examples, move subqueries

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-27334
> (DOCSP-27334): Add docs release notes for w/e January 13, 2023

- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
- https://jira.mongodb.org/browse/DOCSP-27442
N/A
> (DOCSP-27442): fix 'invalid api key' error in kotlin unit test suite

- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/UserAPIKeysTest.kt
- source/examples/generated/kotlin/UserAPIKeysTest.snippet.create-api-key.kt
- source/examples/generated/kotlin/UserAPIKeysTest.snippet.delete-api-key.kt
- source/examples/generated/kotlin/UserAPIKeysTest.snippet.enable-api-key.kt
- source/examples/generated/kotlin/UserAPIKeysTest.snippet.fetch-api-key.kt
- source/sdk/kotlin/app-services.txt
- source/sdk/kotlin/app-services/manage-user-api-keys.txt
Adding new page for Kotlin's [ApiKeyAuth](https://github.com/realm/realm-kotlin/issues/432).  
- https://jira.mongodb.org/browse/DOCSP-26259
- [Create & Manage User API Keys - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-26259-kotlin-api-auth/sdk/kotlin/app-services/manage-user-api-keys/)
> (DOCSP-26259): Kotlin Create & Manage User API Keys

- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SchemaTest.kt
- source/examples/generated/kotlin/SchemaTest.snippet.ignore.kt
- source/examples/generated/kotlin/SchemaTest.snippet.index.kt
- source/examples/generated/kotlin/SchemaTest.snippet.inverse-relationship-post.kt
- source/examples/generated/kotlin/SchemaTest.snippet.inverse-relationship-user.kt
- source/examples/generated/kotlin/SchemaTest.snippet.optional.kt
- source/examples/generated/kotlin/SchemaTest.snippet.primary-key.kt
- source/examples/generated/kotlin/SchemaTest.snippet.to-many-relationship.kt
- source/examples/generated/kotlin/SchemaTest.snippet.to-one-relationship.kt
- source/sdk/kotlin/realm-database/schemas/relationships.txt
- https://jira.mongodb.org/browse/DOCSP-26260
- [Relationships - Kotlin SDK #Inverse Relationships](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26260-inverse-relationships-kotlin/sdk/kotlin/realm-database/schemas/relationships/#inverse-relationships)
> (DOCSP-26260): Kotlin Backlinks + used new KBSON ObjectId import

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-27421
> (DOCSP-27421): Add docs release notes for w/e January 20

- examples/dart/pubspec.lock
- examples/dart/pubspec.yaml
- examples/dart/test/add_sync_to_app.g.dart
- examples/dart/test/client_reset_test.g.dart
- examples/dart/test/data_types_test.dart
- examples/dart/test/data_types_test.g.dart
- examples/dart/test/manage_sync_session_test.g.dart
- examples/dart/test/manage_sync_subscription_test.g.dart
- examples/dart/test/open_flexible_sync_realm_test.g.dart
- examples/dart/test/schemas.g.dart
- examples/dart/test/sync_schemas.g.dart
- examples/dart/test/task_project_models_test.g.dart
- examples/dart/test/write_to_synced_realm_test.g.dart
- source/examples/generated/flutter/data_types_test.snippet.realm-set-examples.dart
- source/examples/generated/flutter/data_types_test.snippet.realm-set-model.dart
- source/sdk/flutter/realm-database/model-data/collections.txt
- source/sdk/flutter/realm-database/model-data/data-types.txt
Flutter RealmSet docs. Additional small tweaks to the rest of the Collection docs for clarity and consistency.
- https://jira.mongodb.org/browse/DOCSP-26116
- [Collections (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26116/sdk/flutter/realm-database/model-data/collections/)
- [Data Types (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26116/sdk/flutter/realm-database/model-data/data-types/)
> (DOCSP-26116): Flutter RealmSet docs

- source/sdk/react-native.txt
update Node.js Reference in RN TOC
- https://jira.mongodb.org/browse/DOCSP-27018
- [React Native SDK (just look at TOC)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27018/sdk/react-native)
> (DOCSP-27018): update Node.js Reference in RN TOC

- examples/dart/test/define_realm_model_test.dart
- examples/dart/test/define_realm_model_test.g.dart
- source/examples/generated/flutter/define_realm_model_test.snippet.map-to.dart
- source/sdk/flutter/realm-database/model-data/define-realm-object-schema.txt
Flutter MapTo for realm models
> **Note**
> 
> Intentionally not going into much detail in the description b/c i think each of these topics would take up a lot of space. Whereas here I just am going for a minimalist API description of this utility annotations so that users can decide what they do with it.
- https://jira.mongodb.org/browse/DOCSP-27544
- [Define a Realm Object Schema (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27544/sdk/flutter/realm-database/model-data/define-realm-object-schema/)
> (DOCSP-27544): Flutter MapTo for realm models

- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/NotificationsTest.kt
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/RQLTest.kt
- source/examples/generated/kotlin/RQLTest.snippet.rql-schema-example.kt
- Fix data type in Kotlin example _(+ a small update to `NotificationTest.kt` to keep job from hanging)_
- https://github.com/mongodb/docs-realm/issues/2542
- [Realm Query Language](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/no-jira-kotlin-rql-fix/realm-query-language/#examples-on-this-page) - Kotlin SDK Example
> (Issue #2542): Fix Kotlin data type def in RQL doc

- examples/cpp/examples.cpp
- source/examples/generated/cpp/examples.snippet.call-a-function.cpp
- source/sdk/cpp.txt
- source/sdk/cpp/app-services/call-a-function.txt
- https://jira.mongodb.org/browse/DOCSP-27630
- [Call a Function](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27630/sdk/cpp/app-services/call-a-function)
> (DOCSP-27630): C++: Add a Call a Function page

- source/sdk/kotlin/realm-database/schemas/supported-types.txt
- https://jira.mongodb.org/browse/DOCSP-27034
- [Supported Types](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-27034/sdk/kotlin/realm-database/schemas/supported-types/)
> (DOCSP-27034): Add Decimal128 to Kotlin supported types list

- examples/dotnet/Examples/WorkWithRealm.cs
- source/examples/generated/dotnet/WorkWithRealm.snippet.unsubscribe.cs
- source/sdk/dotnet/react-to-changes.txt
https://github.com/mongodb/docs-realm/pull/2525/
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/24126_addendum/sdk/dotnet/react-to-changes/
previous branch was deleted, hence the new PR & branch.
> more changes from docs-24126 PR (https://github.com/mongodb/docs-realm/pull/2525/)

- source/web/access-custom-user-data.txt
- source/web/atlas-app-services.txt
- source/web/call-a-function.txt
- source/web/create-delete-user.txt
- source/web/create-manage-api-keys.txt
- source/web/graphql-apollo-react.txt
- source/web/init-app-client.txt
- source/web/install.txt
- source/web/link-identities.txt
- source/web/manage-email-password-users.txt
- source/web/migrate.txt
- source/web/mongodb.txt
- source/web/nextjs.txt
- source/web/quickstart.txt
- source/web/react-web-quickstart.txt
- source/web/telemetry.txt
- source/web/work-with-multiple-users.txt
Add '- Web SDK' to end of titles for Realm Web SDK
n/a
- [Realm Web SDK (changes throughout section)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/web_sdk_title_postfix/web)
> Add '- Web SDK' to end of titles for Realm Web SDK

- config/redirects
Fix broken redirect. Page getting caught in a redirect loop.
For more info, see https://github.com/realm/realm-dart/issues/1138
- https://jira.mongodb.org/browse/DOCSP-27834
n/a
> (DOCSP-27834): Fix broken redirect

- examples/cpp/CMakeLists.txt
- examples/cpp/supported-types.cpp
- source/examples/generated/cpp/supported-types.snippet.optional-binary-data.cpp
- source/examples/generated/cpp/supported-types.snippet.optional-int.cpp
- source/examples/generated/cpp/supported-types.snippet.required-int.cpp
- source/sdk/cpp/model-data/supported-types.txt
- https://jira.mongodb.org/browse/DOCSP-26732
- [Supported Types](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/update-cpp-supported-types/sdk/cpp/model-data/supported-types/)
> (DOCSP-26732): C++: Update supported types

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-27652
> (DOCSP-27652): Add docs release notes for w/e February 3

- examples/cpp/CMakeLists.txt
- examples/cpp/authentication.cpp
- source/examples/generated/cpp/authentication.snippet.anonymous-login.cpp
- source/examples/generated/cpp/authentication.snippet.api-key.cpp
- source/examples/generated/cpp/authentication.snippet.apple.cpp
- source/examples/generated/cpp/authentication.snippet.custom-function.cpp
- source/examples/generated/cpp/authentication.snippet.custom-jwt.cpp
- source/examples/generated/cpp/authentication.snippet.facebook.cpp
- source/examples/generated/cpp/authentication.snippet.get-user-access-token.cpp
- source/examples/generated/cpp/authentication.snippet.google-auth-code.cpp
- source/examples/generated/cpp/authentication.snippet.google-id-token.cpp
- source/examples/generated/cpp/authentication.snippet.log-user-in.cpp
- source/examples/generated/cpp/authentication.snippet.register-user.cpp
- source/sdk/cpp.txt
- source/sdk/cpp/users/authenticate-users.txt
- source/sdk/cpp/users/manage-email-password-users.txt
- https://jira.mongodb.org/browse/DOCSP-26732
- [Authenticate Users](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26732/sdk/cpp/users/authenticate-users/): New page 
- [Manage Email/Password Users](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26732/sdk/cpp/users/manage-email-password-users/): Minor tweaks
> (DOCSP-26732): C++: Create User Authentication page

- source/sdk/dotnet/app-services/mongodb-remote-access.txt
- source/sdk/java/examples/mongodb-remote-access.txt
- source/sdk/node/examples/query-mongodb.txt
- source/sdk/react-native/app-services/query-mongodb.txt
- source/sdk/swift/app-services/mongodb-remote-access.txt
- source/web/mongodb.txt
Add standardized introductions and 'Prerequisites' sections for SDKs' MongoDB Data Access pages
> **Note**
>
> Must be merged after https://github.com/mongodb/docs-app-services/pull/304. This PR is dependent on a ref created in that PR.
- https://jira.mongodb.org/browse/DOCSP-27346
- [Query MongoDB (.NET)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27346/sdk/dotnet/app-services/mongodb-remote-access/)
- [Query MongoDB (Java)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27346/sdk/java/examples/mongodb-remote-access/)
- [Query MongoDB (Node.js)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27346/sdk/node/examples/query-mongodb/)
- [Query MongoDB (React …
> (DOCSP-27346): Intros & Prereqs for MongoDB Data Access pages

- source/index.txt
- source/sdk/flutter.txt
Flutter going GA! Removing RC info. 
n/a
- [Flutter SDK (homepage)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/flutter_ga/sdk/flutter)
> Flutter GA

- source/sdk/react-native/quick-start.txt
Fixes a very minor typo a reader mentioned.
> React Native quickstart minor typo fix

- source/sdk/react-native/realm-database/define-a-realm-object-model.txt
I didn't need to Bluehawk anything new here. Just used existing examples and adjusted surrounding text to fit the `@realm/react` context.
The page has IA/structure issues that we should address later on.
- https://jira.mongodb.org/browse/DOCSP-26980
- [Define a Realm Object Model](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26980/sdk/react-native/realm-database/define-a-realm-object-model/)
> (DOCSP-26980) Realm Reactify "Define a Realm Object Model" page

- examples/kotlin/gradle.properties
- examples/kotlin/settings.gradle.kts
- examples/kotlin/shared/build.gradle.kts
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/EncryptARealmTest.kt
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/RealmTest.kt
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SyncTest.kt
- Update Kotlin test suite to v[1.6.1](https://github.com/realm/realm-kotlin/blob/main/CHANGELOG.md#161-2023-02-02)
- Update `SyncTest.kt` to use random `syncRootDirectory`
> Update Kotlin test suite version to 1.6.1

- examples/dart/bundle_example/pubspec.lock
- examples/dart/pubspec.lock
- examples/dart/pubspec.yaml
- examples/dart/test/sync_multiple_processes_test.dart
- examples/dart/test/sync_multiple_processes_test.g.dart
- examples/dart/test_sdk_example/pubspec.lock
- source/examples/generated/flutter/sync_multiple_processes_test.snippet.refresh-async.dart
- source/examples/generated/flutter/sync_multiple_processes_test.snippet.refresh-main-process.dart
- source/examples/generated/flutter/sync_multiple_processes_test.snippet.refresh-secondary-process.dart
- source/sdk/flutter/sync/sync-multiple-processes.txt
Document `Realm.refresh()` and `Realm.refreshAsync()` for Flutter SDK. 
Note that the docs here are pretty limited b/c this method is only really needed for multi-processing, and we've decided to only talk about multi-processing in the context of syncing on multiple processes *for now*. 
In future docs changes where we talk more about working with Realm on multiple Dart/Flutter processes, there'll be further documentation of these methods.
- https://jira.mongodb.org/browse/DOCSP-26120
- [Sync Multiple Processes (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26120/sdk/flutter/sync/sync-multiple-processes/) …
> (DOCSP-26120): Realm.refresh() and Realm.refreshAsync() for Flutter

- examples/cpp/CMakeLists.txt
- examples/cpp/filter-data.cpp
- source/examples/generated/cpp/filter-data.snippet.comparison-operators.cpp
- source/examples/generated/cpp/filter-data.snippet.logical-operators.cpp
- source/examples/generated/cpp/filter-data.snippet.models.cpp
- source/examples/generated/cpp/filter-data.snippet.set-up-filter-data-tests.cpp
- source/examples/generated/cpp/filter-data.snippet.string-operators.cpp
- source/sdk/cpp/crud.txt
- source/sdk/cpp/crud/filter-data.txt
Note for reviewer: Git shenanigans resulted in #2562 being closed when the feature branch it was working against got merged. This PR was approved in #2562 but had a couple of pieces of feedback, which I incorporated here.
- https://jira.mongodb.org/browse/DOCSP-26736
- [Filter Data](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26736-updated/sdk/cpp/crud/filter-data/)
> (DOCSP-26736): C++: Add a Filter Data page

- source/sdk/react-native/manage-users/multi-user-applications.txt
@realm/reactify Multi-user Applications page. 
Also added some missing content that's in other SDKs.
- https://jira.mongodb.org/browse/DOCSP-27006
- [Multi-User Applications (React Native)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27006/sdk/react-native/manage-users/multi-user-applications/)
> (DOCSP-27006): Multi-user applications

- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/DataTypesTest.kt
- source/examples/generated/kotlin/DataTypesTest.snippet.create-embedded-object.kt
- source/examples/generated/kotlin/DataTypesTest.snippet.delete-embedded-object.kt
- source/examples/generated/kotlin/DataTypesTest.snippet.embedded-object-model.kt
- source/examples/generated/kotlin/DataTypesTest.snippet.open-realm-embedded-object.kt
- source/examples/generated/kotlin/DataTypesTest.snippet.overwrite-embedded-object.kt
- source/examples/generated/kotlin/DataTypesTest.snippet.query-embedded-objects.kt
- source/examples/generated/kotlin/DataTypesTest.snippet.update-embedded-object.kt
- source/sdk/kotlin/realm-database/schemas.txt
- source/sdk/kotlin/realm-database/schemas/embedded-objects.txt
- source/sdk/kotlin/realm-database/schemas/relationships.txt
- https://jira.mongodb.org/browse/DOCSP-26755
- [Embedded Objects - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-26755-linking-obj/sdk/kotlin/realm-database/schemas/embedded-objects/)
> (DOCSP-26755): Kotlin Embedded Objects page

- config/redirects
there were some circular redirects for flutter. fixed now. 
- https://jira.mongodb.org/browse/DOCSP-27834
n/a
> (DOCSP-27834): Fix broken flutter redirects

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-27840
> (DOCSP-27840): Add docs release notes for w/e February 10

- examples/cpp/CMakeLists.txt
- examples/cpp/define-object-model.cpp
- examples/cpp/supported-types.cpp
- source/examples/generated/cpp/define-object-model.snippet.create-map-object.cpp
- source/examples/generated/cpp/define-object-model.snippet.delete-map-value.cpp
- source/examples/generated/cpp/define-object-model.snippet.dog-map-model.cpp
- source/examples/generated/cpp/define-object-model.snippet.model-with-map-property.cpp
- source/examples/generated/cpp/define-object-model.snippet.overwrite-embedded-object.cpp
- source/examples/generated/cpp/define-object-model.snippet.read-map-value.cpp
- source/examples/generated/cpp/define-object-model.snippet.update-map-value.cpp
- source/examples/generated/cpp/supported-types.snippet.required-map-type.cpp
- source/sdk/cpp/crud/create.txt
- source/sdk/cpp/crud/delete.txt
- source/sdk/cpp/crud/read.txt
- source/sdk/cpp/crud/update.txt
- source/sdk/cpp/model-data/supported-types.txt
The work for embedded object cleanup was minimal, so I combined it with adding docs for Map - this work is mainly about the Map docs.
- https://jira.mongodb.org/browse/DOCSP-27496
- https://jira.mongodb.org/browse/DOCSP-27947
- [Supported Data Types](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27947/sdk/cpp/model-data/supported-types/#map-dictionary): New section for Map, new supported property declaration example of map
- [Create](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27947/sdk/cpp/crud/create/#create-an-object-with-a-map-property): New section for creating an object with a map property
- [Read](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27947/sdk/cpp/crud/read/#read-a-map-prope …
> (DOCSP-27496): C++: Add Map docs, clean up embedded object docs

- examples/react-native/__tests__/ts/authentication/read-refresh-custom-user-data.test.tsx
- examples/react-native/__tests__/ts/authentication/refresh-custom-user-data.test.tsx
- examples/react-native/__tests__/ts/authentication/write-custom-user-data.test.tsx
- source/examples/generated/react-native/ts/read-refresh-custom-user-data.test.snippet.read-refresh-custom-user-data.tsx
- source/examples/generated/react-native/ts/write-custom-user-data.test.snippet.write-custom-user-data.tsx
- source/sdk/react-native/manage-users/custom-user-data.txt
@realm/react-ify Custom User Data page
- https://jira.mongodb.org/browse/DOCSP-27004
- [Custom User Data (React Native)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27004/sdk/react-native/manage-users/custom-user-data/)
> (DOCSP-27004): @realm/react-ify Custom User Data page

- examples/react-native/__tests__/ts/authentication/user-api-keys.test.tsx
- source/examples/generated/react-native/ts/user-api-keys.test.snippet.user-api-key.tsx
- source/sdk/react-native/manage-users/manage-user-api-keys.txt
@realm/react for User API Keys page
- https://jira.mongodb.org/browse/DOCSP-27008
- [User API Keys (React Native)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27008/sdk/react-native/manage-users/manage-user-api-keys/)
> (DOCSP-27008): @realm/react for User API Keys page

- examples/react-native/package-lock.json
- examples/react-native/package.json
- examples/react-native/patches/@realm+react+0.4.1.patch
Note to @krollins-mdb: once this has been merged to `realm-react-guidance`, perform the following:
1. `git pull upstream realm-react-guidance`
2. rebase any branches that need this patch on top of realm-react-guidance
3. delete node modules folder `rm -rf node_modules`
4. reinstall node modules and the patch will be applied, `npm i`
> patch to propagate realm open errors

- examples/react-native/__tests__/ts/RealmConfig.js
- examples/react-native/__tests__/ts/realm-database/change-an-object-model-test.tsx
- examples/react-native/__tests__/ts/realm-database/schemas/dictionary-test.tsx
- examples/react-native/__tests__/ts/realm-database/schemas/embedded-objects-test.tsx
- examples/react-native/__tests__/ts/realm-database/schemas/mixed-test.tsx
- examples/react-native/__tests__/ts/realm-database/schemas/relationships-test.tsx
- examples/react-native/__tests__/ts/realm-database/schemas/sets-test.tsx
- examples/react-native/__tests__/ts/realm-database/schemas/uuid.test.tsx
This PR removes duplicate model directory that only has a letter case difference.
> Change "Model" directory to "model:

- source/sdk/cpp.txt
- source/sdk/cpp/telemetry.txt
- https://jira.mongodb.org/browse/DOCS-15912
- [SDK Telemetry](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCS-15912/sdk/cpp/telemetry)
> (DOCS-15912): Add an SDK Telemetry page for C++ SDK

- examples/ios/Examples/EventLibrary.swift
- examples/ios/RealmExamples.xcodeproj/project.pbxproj
- source/examples/generated/code/start/EventLibrary.snippet.cancel-event-scope.swift
- source/examples/generated/code/start/EventLibrary.snippet.check-event-scope.swift
- source/examples/generated/code/start/EventLibrary.snippet.record-read-and-write-events.swift
- source/examples/generated/code/start/EventLibrary.snippet.scoped-event-with-completion.swift
- source/examples/generated/code/start/EventLibrary.snippet.update-event-metadata.swift
- source/sdk/swift/sync/event-library.txt
- https://jira.mongodb.org/browse/DOCSP-28135
- [Event Library](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28135/sdk/swift/sync/event-library/)
> (DOCSP-28135): Update event library details for new Scope object

- source/includes/note-observedresults-swiftui-view.rst
- source/sdk/swift/swiftui/configure-and-open-realm.txt
- source/sdk/swift/swiftui/filter-data.txt
- source/sdk/swift/swiftui/react-to-changes.txt
- source/sdk/swift/swiftui/write.txt
- https://jira.mongodb.org/browse/DOCSP-28049
- [Configure & Open a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28049/sdk/swift/swiftui/configure-and-open-realm/#open-a-realm-with-a-configuration): Add include
- [Filter Data](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28049/sdk/swift/swiftui/filter-data/#observe-in-swiftui-views): Add section at the top of the page about ObservedResults throughout page
- [React to Changes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28049/sdk/swift/swiftui/react-to-changes/#observe-query-results): Add include
- [Write Data](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28049/sdk/swift/swiftui/write/#update-an-obs …
> (DOCSP-28049): Note that ObservedResults is intended for use in a SwiftUI View

- examples/ios/Examples/Sync.swift
- examples/ios/RealmExamples.xcodeproj/xcshareddata/xcschemes/Test Examples.xcscheme
- source/examples/generated/code/start/Sync.snippet.set-custom-logger.swift
- source/sdk/swift/sync/handle-sync-errors.txt
- source/sdk/swift/sync/log-level.txt
- https://jira.mongodb.org/browse/DOCSP-28032
- [Set the Client Log Level](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28032/sdk/swift/sync/log-level/)
- [Handle Sync Errors](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28032/sdk/swift/sync/handle-sync-errors/)
> (DOCSP-28032): Swift: Add custom logger information

- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/OpenARealmTest.kt
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/RealmTest.kt
- source/examples/generated/kotlin/OpenARealmTest.snippet.in-memory-to-local-realm.kt
- source/examples/generated/kotlin/OpenARealmTest.snippet.sync-to-local-realm.kt
- source/examples/generated/kotlin/OpenARealmTest.snippet.unencrypted-to-encrypted-realm.kt
- source/sdk/kotlin/realm-database/realm-files/open-and-close-a-realm.txt
Add **Copy Data into a New Realm** section to existing **Open a Realm - Kotlin SDK** page
- https://jira.mongodb.org/browse/DOCSP-25095
- [Open a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-25095-copy-realm/sdk/kotlin/realm-database/realm-files/open-and-close-a-realm/#copy-data-into-a-new-realm)
> (DOCSP-25095): Kotlin writeCopyTo()

- examples/react-native/__tests__/js/authentication/manage-email-password-users.test.jsx
- examples/react-native/__tests__/ts/authentication/manage-email-password-users.test.tsx
- examples/react-native/jest.config.json
- examples/react-native/package-lock.json
- examples/react-native/package.json
- source/examples/generated/react-native/js/manage-email-password-users.test.snippet.register-user.jsx
- source/examples/generated/react-native/ts/manage-email-password-users.test.snippet.register-user.tsx
- source/sdk/react-native/manage-users/manage-email-password-users.txt
@realm/react-ify Manage Email/Password Users page
> **Note**
>
> Had to update some dependencies to make tests pass. Don't fully understand why. RN testing confuses me.
- https://jira.mongodb.org/browse/DOCSP-27005
- [Manage Email Password Users (RN)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27005/sdk/react-native/manage-users/manage-email-password-users/)
> (DOCSP-27005): @realm/react-ify Manage Email/Password Users page

- examples/react-native/__tests__/ts/realm-database/encrypted-realm.test.tsx
- examples/react-native/jest.config.json
- examples/react-native/package.json
- source/examples/generated/react-native/ts/encrypted-realm.test.snippet.encrypted-realm.tsx
- source/sdk/react-native/realm-database/encrypt.txt
@realm/react-ify Encrypt Realm page
- https://jira.mongodb.org/browse/DOCSP-26997
- [Encrypt a Realm (RN)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26997/sdk/react-native/realm-database/encrypt/)
> (DOCSP-26997): @realm/react-ify Encrypt Realm page

- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.anonymous-authentication-reuse-existing.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.custom-function-authentication.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.retrieve-current-user.kt
- source/sdk/kotlin/app-services/authenticate-users.txt
- Add Custom Function section to existing Authenticate Users page
- Small QC updates to Authenticate Users page
- https://jira.mongodb.org/browse/DOCSP-26563
- [Authenticate Users - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-26563-function-creds/sdk/kotlin/app-services/authenticate-users/)
> (DOCSP-26563): Kotlin Custom Function Authentication

- source/sdk/react-native/realm-database/schemas/dictionaries.txt
- source/sdk/react-native/realm-database/schemas/mixed.txt
- source/sdk/react-native/realm-database/schemas/sets.txt
- source/sdk/react-native/realm-database/schemas/uuid.txt
- source/sdk/react-native/sync-data/flexible-sync.txt
- source/sdk/react-native/sync-data/open-a-synced-realm.txt
clarify from what package feature was added in version admonitions
- https://jira.mongodb.org/browse/DOCSP-28173
- [React Native (changes throughout section)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28173/sdk/react-native/)
> (DOCSP-28173): Clarify `.. version...:` packages

- source/sdk/react-native/app-services/connect-to-app-services-app.txt
- source/sdk/react-native/app-services/query-mongodb.txt
- source/sdk/react-native/bootstrap-with-expo.txt
- source/sdk/react-native/manage-users/authenticate-users.txt
- source/sdk/react-native/manage-users/manage-email-password-users.txt
- source/sdk/react-native/manage-users/manage-user-api-keys.txt
- source/sdk/react-native/manage-users/multi-user-applications.txt
- source/sdk/react-native/realm-database/configure-a-realm.txt
- source/sdk/react-native/use-realm-react.txt
Wrap component names in angle brackets (`<>`) - React Native SDK
- https://jira.mongodb.org/browse/DOCSP-28071
- [React Native SDK (changes throughout](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28071/sdk/react-native/)
> (DOCSP-28071): Wrap component names in angle brackets (`<>`) - React Native SDK

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-28162
> (DOCSP-28162): Add docs release notes for w/e February 24

- source/sdk/flutter/install.txt
Flutter supported platform section
- https://jira.mongodb.org/browse/DOCSP-26380
- [Install (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26380/sdk/flutter/install)
> (DOCSP-26380): Flutter supported platform section

- source/sdk/dotnet/crud/threading.txt
- source/sdk/swift/crud/threading.txt
Note: this page doesn't exist on Flutter, Kotlin, or the JS pages (it wouldn't apply). We are choosing not to update the Java version.
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/thread-update/
> Apply threading text update to other SDKs

- snooty.toml
- source/includes/note-class-char-limit.rst
- source/sdk/cpp/model-data/object-models.txt
- source/sdk/dotnet/model-data/define-object-model.txt
- source/sdk/flutter/realm-database/model-data/define-realm-object-schema.txt
- source/sdk/java/examples/define-a-realm-object-model.txt
- source/sdk/kotlin/realm-database/define-realm-object-model.txt
- source/sdk/node/examples/define-a-realm-object-model.txt
- source/sdk/react-native/realm-database/define-a-realm-object-model.txt
- source/sdk/swift/model-data/define-model/object-models.txt
Create shared note to specify the character limit for class names
Add to each SDK's doc for defining a schema
See https://github.com/mongodb/docs-app-services/pull/370 for corresponding app-services update
- https://jira.mongodb.org/browse/DOCSP-24875
- [Object Models - C++ SDK (Alpha)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-24875-char-limit/sdk/cpp/model-data/object-models/#define-a-new-object-type)
- [Define a Realm Object Schema - Flutter SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-24875-char-limit/sdk/flutter/realm-database/model-data/define-realm-object-schema/#create-realmmodel)
- [Define a Realm Object Schema - Java SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-24875 …
> (DOCSP-24875): Note class name character limit

- source/web/authenticate.txt
Fix Google auth arg for redirect flow
- https://jira.mongodb.org/browse/DOCSP-28363
- [Authenticate Users (Web SDK)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28363/web/authenticate/)
> (DOCSP-28363): Fix Google auth arg

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-28277
> (DOCSP-28277): Add docs release notes for w/e March 3

- Calculate_Readability_Score.py
For Skunkworks, I've been making improvements to the readability rST parsing. I've already merged a PR to docdoctor to improve rST parsing. The other element of improving our readability scoring is to add a second heuristic to the readability scoring Python script - Flesch Kinkaid Grade Level - and to make a recommendation about where you can go to get suggestions to improve readability.
> Add Grade Level to readability scoring, link to Hemingway App

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-28408
> (DOCSP-28408): Add docs release notes for w/e March 10

- examples/ios/Examples/CustomUserData.m
- examples/ios/Examples/CustomUserData.swift
- examples/ios/Examples/Errors.swift
- examples/ios/Examples/EventLibrary.swift
- examples/ios/Examples/MultipleUsers.swift
- examples/ios/RealmExamples.xcodeproj/project.pbxproj
- examples/ios/RealmExamples.xcodeproj/xcshareddata/xcschemes/RealmExamplesHostApp.xcscheme
- source/examples/generated/code/start/Errors.snippet.access-compensating-write.swift
- source/sdk/swift/sync/write-to-synced-realm.txt
- https://jira.mongodb.org/browse/DOCSP-28642
- [Write to a Synced Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28642/sdk/swift/sync/write-to-synced-realm/)
> (DOCSP-28642): Swift: Add information about new compensating write error information

- source/sdk/dotnet/realm-files/bundle-a-realm.txt
- source/sdk/java/examples/bundle-a-realm.txt
- source/sdk/node/advanced/bundle.txt
- source/sdk/react-native/realm-database/bundle.txt
- source/sdk/swift/realm-files/bundle-a-realm.txt
- https://jira.mongodb.org/browse/DOCSP-28046
- [Swift Bundle a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28046/sdk/swift/realm-files/bundle-a-realm/)
- [.NET Bundle a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28046/sdk/dotnet/realm-files/bundle-a-realm/)
- [Java Bundle a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28046/sdk/java/examples/bundle-a-realm/)
- [Node Bundle a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28046/sdk/node/advanced/bundle/)
- [React Native Bundle a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28046/sdk/react-native/realm-database/bundle/)
If your PR …
> DOCSP-28046 Remove Advanced Backend Compaction

- source/sdk/flutter/realm-database/realm-files/compact.txt
Compact on open for Flutter SDK w sync.
- https://jira.mongodb.org/browse/DOCSP-28701
- [Compact a Realm (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28701/sdk/flutter/realm-database/realm-files/compact/)
> (DOCSP-28701): Compact on open for Flutter SDK w sync

- source/sdk/dotnet/realm-files/compact-realm.txt
- source/sdk/flutter/realm-database/realm-files/compact.txt
- https://jira.mongodb.org/browse/DOCSP-27044
- [Reduce Realm File Size - .NET SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27044/sdk/dotnet/realm-files/compact-realm/)
> DOCSP-27044 .NET continuous defragmentation edits

- examples/ios/Examples/CustomUserData.m
- examples/ios/Examples/CustomUserData.swift
- examples/ios/Examples/EventLibrary.swift
- examples/ios/RealmExamples.xcodeproj/xcshareddata/xcschemes/RealmExamplesHostApp.xcscheme
- https://jira.mongodb.org/browse/DOCSP-28669
> (DOCSP-28669): Swift: Fix failing unit tests

- config/redirects
- https://jira.mongodb.org/browse/DOCSP-28486
- None
> (DOCSP-28486): Add redirects to fix SEO impact 404s

- source/sdk/dotnet/compatibility.txt
https://jira.mongodb.org/browse/DOCSP-27760
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/tvos/sdk/dotnet/compatibility/
> Add tvOS support

- source/examples/generated/kotlin/SyncTest.snippet.configure-a-synced-realm.kt
- source/examples/generated/kotlin/SyncTest.snippet.open-a-synced-realm.kt
No Jira -- re-adding Kotlin `SyncTest.kt` snippets that were erroneously deleted
> Re-add deleted Kotlin sync snippets

- source/sdk/kotlin/realm-database/realm-files/open-and-close-a-realm.txt
- https://jira.mongodb.org/browse/DOCSP-27045
- [Open a Realm - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27045/sdk/kotlin/realm-database/realm-files/open-and-close-a-realm/)
> (DOCSP-27045): Kotlin Continuous Defragmentation Note

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-28697
> (DOCSP-28697): Add docs release notes for w/e March 24

- examples/cpp/notifications.cpp
- source/examples/generated/cpp/notifications.snippet.collection-model.cpp
- source/examples/generated/cpp/notifications.snippet.collection.cpp
- source/sdk/cpp/react-to-changes.txt
- https://jira.mongodb.org/browse/DOCSP-28197
- [React to Changes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28197/sdk/cpp/react-to-changes/)
> (DOCSP-28197): C++: Add a Collection change listener section

- examples/dart/test/write_to_synced_realm_test.dart
- source/examples/generated/flutter/write_to_synced_realm_test.snippet.not-match-permissions.dart
- source/examples/generated/flutter/write_to_synced_realm_test.snippet.not-match-query-subscription.dart
- source/examples/generated/flutter/write_to_synced_realm_test.snippet.write-synced-realm.dart
- source/sdk/flutter/sync/write-to-synced-realm.txt
- source/sdk/swift/sync/write-to-synced-realm.txt
Flutter Upgrade Write to a Synced Realm page
- https://jira.mongodb.org/browse/DOCSP-27850
- [Write to a Synced Realm (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27850/sdk/flutter/sync/write-to-synced-realm/)
> (DOCSP-27850): Flutter Upgrade Write to a Synced Realm page

- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/customUserData.js
- source/examples/generated/kotlin/AuthenticationTest.snippet.delete-custom-user-data.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.read-custom-user-data.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.refresh-custom-user-data.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.write-custom-user-data.kt
- source/examples/generated/kotlin/customUserData.snippet.delete-custom-user-data.js
- source/examples/generated/kotlin/customUserData.snippet.write-custom-user-data.js
- source/sdk/kotlin/app-services.txt
- source/sdk/kotlin/app-services/custom-user-data.txt
- https://jira.mongodb.org/browse/DOCSP-26752
- [Custom User Data - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-26752-user-custom-data/sdk/kotlin/app-services/custom-user-data/)
> (DOCSP-26752): Add new Custom User Data - Kotlin SDK page

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-28827
> (DOCSP-28827): Add docs release notes for w/e March 31

- examples/react-native/__tests__/js/Models/Car.js
- examples/react-native/__tests__/js/Models/Dog.js
- examples/react-native/__tests__/ts/Models/Car.ts
- examples/react-native/__tests__/ts/Models/Dog.ts
- source/examples/generated/react-native/js/Car.snippet.js-car-schema.js
- source/examples/generated/react-native/js/Dog.snippet.js-dog-schema.js
- source/examples/generated/react-native/ts/Car.snippet.ts-car-schema.ts
- source/examples/generated/react-native/ts/Dog.snippet.ts-dog-schema.ts
- source/sdk/react-native/realm-database/crud/read.txt
- source/sdk/react-native/realm-database/crud/update.txt
- source/sdk/react-native/realm-database/schemas/default-value.txt
- source/sdk/react-native/realm-database/schemas/optional.txt
Covers items 2 - 4 in the Jira ticket.
- https://jira.mongodb.org/browse/DOCSP-28190
- [CRUD - Read](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28190-round2/sdk/react-native/realm-database/crud/read/)
- [CRUD - Update](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28190-round2/sdk/react-native/realm-database/crud/update/)
- [Schema - Default value](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28190-round2/sdk/react-native/realm-database/schemas/default-value/)
- [Schema - Optional property](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28190-round2/sdk/react-native/realm-database/schemas/optional/)
If your PR modifies the docs, you might need to also …
> (DOCSP-28190) Implement Andrew's RN SDK docs feedback - Round 2

- examples/react-native/__tests__/ts/Models/BookReqProperties.ts
- source/examples/generated/react-native/ts/BookReqProperties.snippet.book-model-req-properties.ts
- source/sdk/react-native/realm-database/define-a-realm-object-model.txt
- https://jira.mongodb.org/browse/DOCSP-28551
- [Define a Realm Object Model](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28551/sdk/react-native/realm-database/define-a-realm-object-model/#typescript-and-required-properties)
> (DOCSP-28551) Doc required properties for TS class schemas

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-28947
> (DOCSP-28947) Add docs release notes for w/e April 07

- examples/react-native/__tests__/js/app-services/mongodb-watch.test.jsx
- examples/react-native/__tests__/ts/app-services/mongodb-watch.test.tsx
- examples/react-native/package-lock.json
- examples/react-native/package.json
- source/examples/generated/react-native/js/mongodb-watch.test.snippet.mongodb-watch.jsx
- source/examples/generated/react-native/ts/index.snippet.watch-polyfills.js
- source/examples/generated/react-native/ts/mongodb-watch.test.snippet.mongodb-watch.tsx
- source/sdk/react-native/app-services/query-mongodb.txt
- https://jira.mongodb.org/browse/DOCSP-27962
- [Query MongoDB](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27962/sdk/react-native/app-services/query-mongodb/#real-time-change-notifications)
> (DOCSP-27962) Document React Native Polyfills for RN .watch() method

- source/sdk/swift/realm-files/encrypt-a-realm.txt
- https://jira.mongodb.org/browse/DOCSP-29048
- [Encrypt a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29048/sdk/swift/realm-files/encrypt-a-realm/)
> (DOCSP-29048): Swift: Update docs for encrypted realm multiprocess support

- source/sdk/cpp.txt
- https://jira.mongodb.org/browse/DOCSP-28756
- [C++ SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28756/sdk/cpp/): New link in sidebar: "Example Projects"
> (DOCSP-28756): C++: Add link to realm-cpp example projects

- source/sdk/node/advanced/encrypt.txt
- source/sdk/react-native/realm-database/encrypt.txt
- https://jira.mongodb.org/browse/DOCSP-29053
- https://jira.mongodb.org/browse/DOCSP-29055
- [Encrypt a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29053/sdk/react-native/realm-database/encrypt/#accessing-an-encrypted-realm-from-multiple-processes) - React Native
- [Encrypt a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29053/sdk/node/advanced/encrypt/#accessing-an-encrypted-realm-from-multiple-processes) - Node.js
> (DOCSP-29053, DOCSP-29055) Update Node and RN docs for encrypted realm multiprocess support

- examples/kotlin/settings.gradle.kts
- examples/kotlin/shared/build.gradle.kts
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/OpenARealmTest.kt
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/RQLTest.kt
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SchemaTest.kt
- source/examples/generated/kotlin/OpenARealmTest.snippet.sync-to-local-realm.kt
- source/examples/generated/kotlin/RQLTest.snippet.rql-schema-example.kt
- source/examples/generated/kotlin/SchemaTest.snippet.inverse-relationship-post.kt
- source/examples/generated/kotlin/SchemaTest.snippet.inverse-relationship-user.kt
- source/examples/generated/kotlin/SchemaTest.snippet.to-many-relationship.kt
- source/examples/generated/kotlin/SchemaTest.snippet.to-one-relationship.kt
Update to Kotlin SDK v1.7.0
- convert val to var for any persisted fields
- [staged build](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/no-jira-update-kotlin-test-suite/)
> Update Kotlin test suite to 1.7.0

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-29044
> (DOCSP-29044): Add docs release notes for w/e 4/14

- source/sdk/flutter/realm-database/model-data/update-realm-object-schema.txt
- (DOCSP-29109) Fix "Delete a schema property" example for Flutter SDK
- [Update a Realm Object Schema - Flutter SDK > Delete a Property](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/delete-example-fix/sdk/flutter/realm-database/model-data/update-realm-object-schema/#std-label-flutter-delete-a-property)
> (DOCSP-29109) Fix "Delete a schema property" example for Flutter SDK

- examples/node/Examples/quickstart.js
- source/examples/generated/node/quickstart.snippet.open-realm-with-subscriptions.js
- (DOCSP-29305) Fix sync query in the Node SDK quickstart
- [Quick Start - Node.js SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/quickstart-fix/sdk/node/quick-start/#open-a-synced-realm)
> (DOCSP-29305) Fix sync query in the Node SDK quickstart

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-29273
> (DOCSP-29273): Add docs release notes for w/e April 21

- config/redirects
- source/sdk/java/migrate/index.txt
- source/sdk/kotlin/realm-database/realm-files.txt
- source/sdk/kotlin/realm-database/realm-files/bundle-a-realm/index.txt
- https://jira.mongodb.org/browse/DOCSP-29107
- [Kotlin/Realm Files](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29107/sdk/kotlin/realm-database/realm-files/): File removed from ToC
> (DOCSP-29107): Kotlin: Temporarily remove Bundle a Realm page

- source/examples/generated/cpp/quick-start.snippet.sync-session.cpp
- source/examples/generated/cpp/quick-start.snippet.sync-state.cpp
- source/examples/generated/cpp/quick-start.snippet.wait-for-download.cpp
- https://jira.mongodb.org/browse/DOCSP-29475
- [Manage Sync Sessions](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29475/sdk/cpp/sync/manage-sync-session/)
> (DOCSP-29475): C++: Restore code examples using states

- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/CreateTest.kt
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/DeleteTest.kt
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/ReadTest.kt
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/UpdateTest.kt
- source/examples/generated/kotlin/CreateTest.snippet.create-dictionary.kt
- source/examples/generated/kotlin/CreateTest.snippet.define-realm-dictionary-property.kt
- source/examples/generated/kotlin/DeleteTest.snippet.delete-realm-dictionary.kt
- source/examples/generated/kotlin/ReadTest.snippet.read-realm-dictionary.kt
- source/examples/generated/kotlin/UpdateTest.snippet.update-realm-dictionary.kt
- source/sdk/cpp/model-data/object-models.txt
- source/sdk/kotlin/realm-database/crud/create.txt
- source/sdk/kotlin/realm-database/crud/delete.txt
- source/sdk/kotlin/realm-database/crud/read.txt
- source/sdk/kotlin/realm-database/crud/update.txt
- source/sdk/kotlin/realm-database/react-to-changes.txt
- source/sdk/kotlin/realm-database/schemas/supported-types.txt
- source/sdk/swift/app-services/mongodb-remote-access.txt
- source/sdk/swift/model-data/object-models.txt
- https://jira.mongodb.org/browse/DOCSP-28704
- [Data Types](https://docs-mongodbcom-staging.corp.mongodb.com/db1cd986/53c3b1b/realm/docsworker-xlarge/master/sdk/kotlin/realm-database/schemas/supported-types/#realmdictionary-realmmap): New RealmDictionary/RealmMap section
- [CRUD/Create](https://docs-mongodbcom-staging.corp.mongodb.com/db1cd986/53c3b1b/realm/docsworker-xlarge/master/sdk/kotlin/realm-database/crud/create/#create-an-object-with-a-dictionary-property): New section: Create an Object with a Dictionary Property
- [CRUD/Read](https://docs-mongodbcom-staging.corp.mongodb.com/db1cd986/53c3b1b/realm/docsworker-xlarge/master/sdk/kotlin/realm-database/crud/read/#read-an-object-with-a-dictionary-property): New section: Read an Object with a Dictionary Property
- …
> Kotlin: Add docs for Map data type

- source/sdk/kotlin/realm-database/schemas/relationships.txt
- https://jira.mongodb.org/browse/DOCSP-28420
- [Relationships](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28420/sdk/kotlin/realm-database/schemas/relationships/#to-one-relationship)
> (DOCSP-28420): Kotlin To-One Relationship: Update description to match example

- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/NotificationsTest.kt
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/QuickStartTest.kt
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SchemaTest.kt
- source/examples/generated/kotlin/NotificationsTest.snippet.realm-list-change-listener.kt
- source/examples/generated/kotlin/NotificationsTest.snippet.realm-object-change-listener.kt
- source/examples/generated/kotlin/OpenARealmTest.snippet.delete-realm-if-migration-needed.kt
- source/examples/generated/kotlin/OpenARealmTest.snippet.open-a-realm.kt
- source/examples/generated/kotlin/OpenARealmTest.snippet.open-an-in-memory-realm.kt
- https://jira.mongodb.org/browse/DOCSP-29401
- [Staged Kotlin docs](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29401/sdk/kotlin/)
> (DOCSP-29401): Kotlin: Update Bluehawk markup, update and remove code example snippets

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-29375
> (DOCSP-29375): Add docs release notes for w/e April 28

- examples/kotlin/shared/src/commonMain/kotlin/com/mongodb/realm/realmkmmapp/RealmModels.kt
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/QuickStartTest.kt
- source/examples/generated/kotlin/QuickStartTest.snippet.quick-start-model.kt
- source/sdk/kotlin/quick-start.txt
- https://jira.mongodb.org/browse/DOCSP-28910
- [Kotlin Quick Start](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28910/sdk/kotlin/quick-start/)
> (DOCSP-28901): Kotlin: Update Quick Start Define Model code example

- source/sdk/kotlin/realm-database/realm-files/encrypt-a-realm.txt
- https://jira.mongodb.org/browse/DOCSP-29052
- [Encrypt a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29052/sdk/kotlin/realm-database/realm-files/encrypt-a-realm/)
> Kotlin: Add note about multiprocess encrypted realm support

- source/realm-query-language.txt
- source/sdk/cpp/crud/filter-data.txt
- https://jira.mongodb.org/browse/DOCSP-29577
- [Realm Query Language](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29577/realm-query-language/)
- [Filter Data - C++ SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29577/sdk/cpp/crud/filter-data/)
> DOCSP-29577 Link to C++ Filter Page from RQL Page

- examples/ios/Examples/Sync.swift
- source/examples/generated/code/start/Sync.snippet.set-default-logger.swift
- source/examples/generated/code/start/Sync.snippet.set-log-level-logger.swift
- source/sdk/swift/sync/log-level.txt
This is a fast follow to #2773 to incorporate Diana's technical review feedback.
- https://jira.mongodb.org/browse/DOCSP-29615
- [Set the Client Log Level](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/swift-log-level-feedback/sdk/swift/sync/log-level/)
> (DOCSP-29615): Swift Log Level Docs Updates

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-29583
> (DOCSP-29583): Add docs release notes for w/e May 5

- examples/node/Examples/compacting.js
- source/examples/generated/node/compacting.snippet.compactNode.js
- source/examples/generated/node/compacting.snippet.shouldCompactNode.js
- source/sdk/node/realm-files/compact-realm.txt
- https://jira.mongodb.org/browse/DOCSP-29330
- [Node.js Compaction](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29330/sdk/node/realm-files/compact-realm/)
> DOCSP-29330 Fix Node.js Compaction Code Test

- examples/dotnet/ConsoleTests/ConsoleTests.csproj
- examples/dotnet/DataBinding/DataBinding.csproj
- examples/dotnet/Examples/ErrorHandler.cs
- examples/dotnet/Examples/Examples.csproj
- examples/dotnet/Examples/Indexing.cs
- examples/dotnet/Examples/Migrations.cs
- examples/dotnet/Examples/NullabilityTest.cs
- examples/dotnet/Examples/Objects.cs
- examples/dotnet/Examples/QuickStartExamples.cs
- examples/dotnet/Examples/Schemas.cs
- examples/dotnet/Examples/WorkWithRealm.cs
- examples/dotnet/LocalOnly/LocalOnly.csproj
- source/examples/generated/dotnet/ErrorHandler.snippet.handle-errors.cs
- source/examples/generated/dotnet/Indexing.snippet.linq-query-fts.cs
- source/examples/generated/dotnet/Indexing.snippet.rql-query-fts.cs
- source/examples/generated/dotnet/Migrations.snippet.migrate.cs
- source/examples/generated/dotnet/Objects.snippet.fts-index.cs
- source/examples/generated/dotnet/Objects.snippet.index.cs
- source/examples/generated/dotnet/QuickStartExamples.snippet.create.cs
- source/examples/generated/dotnet/Schemas.snippet.schema_property.cs
- source/examples/generated/dotnet/WorkWithRealm.snippet.collection-notifications.cs
- source/examples/generated/dotnet/WorkWithRealm.snippet.subscribe.cs
- source/examples/generated/dotnet/WorkWithRealm.snippet.unsub-collection-notifications.cs
- source/sdk/dotnet/crud.txt
- source/sdk/dotnet/crud/filter.txt
- source/sdk/dotnet/model-data/change-an-object-model.txt
- source/sdk/dotnet/model-data/define-object-model.txt
- source/sdk/dotnet/sync/add-sync-to-app.txt
NOTE: changed URLs to new branch!
https://jira.mongodb.org/browse/DOCSP-29725
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/11.0.0_updates/sdk/dotnet/model-data/define-object-model/#indexes
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/11.0.0_updates/sdk/dotnet/crud/filter/
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/11.0.0_updates/sdk/dotnet/sync/add-sync-to-app/#use-the-realm
> 11.0.0 updates

- source/sdk/swift/model-data/object-models.txt
- https://jira.mongodb.org/browse/DOCSP-29876
- [Define a Realm Object Model](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29876/sdk/swift/model-data/object-models/#declare-enum-properties)
> (DOCSP-29876): Swift: Clarify PersistableEnum types

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-29717
> (DOCSP-29717): Add docs release notes for w/e May 12

- source/sdk/dotnet/realm-files/encrypt-a-realm.txt
- https://jira.mongodb.org/browse/DOCSP-29054
- [Encrypt a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29054/sdk/dotnet/realm-files/encrypt-a-realm/#accessing-an-encrypted-realm-from-multiple-process)
> (DOCSP-29054): .NET: Open an encrypted realm from multiple processes

- source/includes/note-bundling-synced-realms.rst
- source/sdk/dotnet/realm-files/bundle-a-realm.txt
- source/sdk/java/realm-files/bundle-a-realm.txt
- source/sdk/node/realm-files/bundle.txt
- source/sdk/swift/realm-files/bundle-a-realm.txt
- https://jira.mongodb.org/browse/DOCSP-29720
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/clarify-trimming/
> (DOCSP-29720): Clarify trimming message - applies to Flex Sync only

- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
- https://jira.mongodb.org/browse/DOCSP-28251
This didn't actually change any code examples so there are no staged changes to review.
> (DOCSP-28251): Kotlin: Add tests for auth code examples

- examples/react-native/__tests__/js/realm-database/change-an-object-model-test.jsx
- examples/react-native/__tests__/ts/realm-database/change-an-object-model-test.tsx
- source/examples/generated/react-native/js/change-an-object-model-test.snippet.add-a-property-to-schema.jsx
- source/examples/generated/react-native/js/change-an-object-model-test.snippet.modify-a-property-type.jsx
- source/examples/generated/react-native/js/change-an-object-model-test.snippet.rename-a-property-of-a-schema.jsx
- source/examples/generated/react-native/ts/change-an-object-model-test.snippet.add-a-property-to-schema.tsx
- source/examples/generated/react-native/ts/change-an-object-model-test.snippet.delete-a-property-from-a-schema.tsx
- source/examples/generated/react-native/ts/change-an-object-model-test.snippet.modify-a-property-type.tsx
- source/examples/generated/react-native/ts/change-an-object-model-test.snippet.rename-a-property-of-a-schema.tsx
Fixed tests that weren't properly set up. Generated new samples.
- [Change an Object Model](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/feedback-fix-rn-migration-tests/sdk/react-native/model-data/change-an-object-model/)
> Docs Feedback: Fix React Native migration tests

- examples/dart/pubspec.lock
- examples/dart/test/read_write_data_test.dart
- examples/dart/test/task_project_models_test.g.dart
- source/examples/generated/flutter/read_write_data_test.snippet.limit.dart
- source/sdk/flutter/realm-database/read-and-write-data.txt
- https://jira.mongodb.org/browse/DOCSP-29932
- [Read & Write Data](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29932/sdk/flutter/realm-database/read-and-write-data/#limit-results)
> (DOCSP-29932) Add Flutter-specific example of limiting results

- examples/cpp/CMakeLists.txt
- examples/cpp/logger.cpp
- examples/cpp/quick-start.cpp
- source/examples/generated/cpp/logger.snippet.create-custom-logger.cpp
- source/examples/generated/cpp/logger.snippet.initialize-logger.cpp
- source/examples/generated/cpp/logger.snippet.set-default-log-level.cpp
- source/examples/generated/cpp/quick-start.snippet.set-sync-log-level.cpp
- source/sdk/cpp.txt
- source/sdk/cpp/logging.txt
- source/sdk/cpp/sync.txt
- source/sdk/cpp/sync/log-level.txt
- https://jira.mongodb.org/browse/DOCSP-29474
- [Sync Client Log Level](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29474/sdk/cpp/sync/log-level/)
- [Logging](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29474/sdk/cpp/logging/)
> (DOCSP-29474): C++: Add logging docs

- examples/ios/Examples/ReadRealmObjects.swift
- source/examples/generated/code/start/ReadRealmObjects.snippet.sort-type-safe.swift
- source/sdk/swift/crud/read.txt
- https://jira.mongodb.org/browse/DOCSP-30185
- [CRUD/Read](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-30185/sdk/swift/crud/read/#sort-query-results)
> (DOCSP-30185): Swift: Add sort by type-safe keyPath

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-30069
> (DOCSP-30069): Add docs release notes for w/e May 26

- source/sdk/swift/install.txt
DO NOT MERGE until the next Swift SDK release when this change takes effect. Confirm the version number before merging.
- https://jira.mongodb.org/browse/DOCSP-29730
- [Install Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29730/sdk/swift/install/)
> (DOCSP-29730): Swift: Drop Xcode 13 support in the upcoming Swift SDK release

- examples/dotnet/Examples/DataTypesSectionExamples.cs
- examples/dotnet/Examples/ProgressNotifications.cs
- source/examples/generated/dotnet/DataTypesSectionExamples.snippet.query-lists.cs
- source/examples/generated/dotnet/ProgressNotifications.snippet.notify-dictionary-change.cs
- source/examples/generated/dotnet/ProgressNotifications.snippet.notify-list-change.cs
- source/examples/generated/dotnet/ProgressNotifications.snippet.notify-sample-class.cs
- source/examples/generated/dotnet/ProgressNotifications.snippet.notify-set-change.cs
- source/sdk/dotnet/model-data/data-types.txt
- source/sdk/dotnet/model-data/data-types/collections.txt
- source/sdk/dotnet/model-data/data-types/dictionaries.txt
- source/sdk/dotnet/model-data/data-types/lists.txt
- source/sdk/dotnet/model-data/data-types/sets.txt
https://jira.mongodb.org/browse/DOCSP-29852
See also: https://github.com/realm/realm-dotnet/issues/3308
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-29852/sdk/dotnet/model-data/data-types/collections/ (pruned)
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-29852/sdk/dotnet/model-data/data-types/lists/ (new)
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-29852/sdk/dotnet/model-data/data-types/dictionaries/#watching-for-changes (added section)
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-29852/sdk/dotnet/model-data/data-types/sets/#watching-for-changes  (added section)
> Add Code on Watching for Collection Changes

- source/sdk/cpp.txt
- source/sdk/cpp/install.txt
- https://jira.mongodb.org/browse/DOCSP-30352
- [Install Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-30352/sdk/cpp/install/): Updates the instructions on the `CMake` tab
> (DOCSP-30352): C++: Update Install instructions to use release tags

- examples/dart/bundle_example/pubspec.lock
- examples/dart/pubspec.lock
- examples/dart/pubspec.yaml
- examples/dart/test/logger.dart
- examples/dart/test_sdk_example/pubspec.lock
- source/examples/generated/flutter/logger.snippet.attach-to-logger.dart
- source/examples/generated/flutter/logger.snippet.change-log-level.dart
- source/examples/generated/flutter/logger.snippet.clear-listeners.dart
- source/examples/generated/flutter/logger.snippet.set-custom-logger.dart
- source/examples/generated/flutter/logger.snippet.set-log-level-to-off.dart
- source/examples/generated/flutter/logger.snippet.set-the-log-level.dart
- source/sdk/flutter.txt
- source/sdk/flutter/logging.txt
- source/sdk/flutter/sync/log-level.txt
- https://jira.mongodb.org/browse/DOCSP-30207
- [Logging](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-30207/sdk/flutter/logging/)
- [Sync/Set Sync Log Level](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-30207/sdk/flutter/sync/log-level/)
> (DOCSP-30207): Flutter: Add docs for Core Logging

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-30204
> (DOCSP-30204): Add docs release notes for w/e June 2

- source/sdk/cpp/crud/read.txt
- source/sdk/dotnet/crud/update.txt
- source/sdk/flutter/quick-start.txt
- source/sdk/flutter/realm-database/freeze.txt
- source/sdk/flutter/realm-database/model-data/update-realm-object-schema.txt
- source/sdk/flutter/sync/handle-sync-errors.txt
- source/sdk/flutter/sync/manage-sync-session.txt
- source/sdk/java/api/io/realm/mongodb/App.txt
- source/sdk/kotlin/realm-database/crud/delete.txt
- source/sdk/kotlin/realm-database/crud/update.txt
- source/sdk/kotlin/realm-database/schemas/supported-types.txt
- source/sdk/react-native/app-services/query-mongodb.txt
- source/sdk/react-native/bootstrap-with-expo.txt
https://jira.mongodb.org/browse/DOCSP-30385
> Fix broken links

- source/sdk/swift/install.txt
- source/sdk/swift/swift-concurrency.txt
- https://jira.mongodb.org/browse/DOCSP-30438
- [Install](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-30438/sdk/swift/install/)
> (DOCSP-30438): Swift: Update compatibility information

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-30369
> (DOCSP-30369): Add docs release notes for w/e June 8

- examples/node/Examples/realm-query-language.js
- source/examples/generated/realm-query-language/realm-query-language.snippet.aggregate-operators.js
- source/examples/generated/realm-query-language/realm-query-language.snippet.comparison-operators.js
- source/examples/generated/realm-query-language/realm-query-language.snippet.date-alt-representation.js
- source/examples/generated/realm-query-language/realm-query-language.snippet.dictionary-operators.js
- source/examples/generated/realm-query-language/realm-query-language.snippet.logical-operators.js
- source/examples/generated/realm-query-language/realm-query-language.snippet.set-operators.js
- source/examples/generated/realm-query-language/realm-query-language.snippet.string-operators.js
- source/realm-query-language.txt
- https://jira.mongodb.org/browse/DOCSP-29875
- [RQL](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29875/realm-query-language/)
> DOCSP-29875 Parameterized Queries on RQL page

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-30625
> (DOCSP-30625): Add docs release notes for w/e June 16

- examples/cpp/beta/asymmetric/CMakeLists.txt
- examples/cpp/beta/asymmetric/asymmetric-sync.cpp
- examples/cpp/beta/sync/CMakeLists.txt
- examples/cpp/beta/sync/authentication.cpp
- examples/cpp/beta/sync/call-function.cpp
- examples/cpp/beta/sync/custom-user-data.cpp
- examples/cpp/beta/sync/quick-start.cpp
- source/examples/generated/cpp/authentication.snippet.get-user-access-token.cpp
- source/examples/generated/cpp/authentication.snippet.log-user-out.cpp
- source/examples/generated/cpp/call-function.snippet.beta-call-a-function.cpp
- source/examples/generated/cpp/custom-user-data.snippet.beta-create.cpp
- source/examples/generated/cpp/custom-user-data.snippet.delete.cpp
- source/examples/generated/cpp/custom-user-data.snippet.read.cpp
- source/examples/generated/cpp/custom-user-data.snippet.update.cpp
- source/examples/generated/cpp/quick-start.snippet.beta-wait-for-download.cpp
- source/examples/generated/cpp/quick-start.snippet.beta-wait-for-upload.cpp
- source/examples/generated/cpp/quick-start.snippet.wait-for-download.cpp
- source/examples/generated/cpp/quick-start.snippet.wait-for-upload.cpp
- source/sdk/cpp/sync/manage-sync-session.txt
- source/sdk/cpp/users/authenticate-users.txt
Remove `get_future()` and update both the sync test suites to the latest eng commit.
- https://jira.mongodb.org/browse/DOCSP-30881
- [Call a Function](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-30881/sdk/cpp/app-services/call-a-function/)
- [Authenticate Users](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-30881/sdk/cpp/users/authenticate-users/)
- [Manage Email/Password Users](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-30881/sdk/cpp/users/manage-email-password-users/)
- [Custom User Data](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-30881/sdk/cpp/users/custom-user-data/)
- [Manage Sync Sessions](https://docs-mongodbcom-staging.corp.mongodb.com/realm/do …
> (DOCSP-30881): C++ Preview: Update Sync-related examples

- examples/cpp/beta/local/CMakeLists.txt
- examples/cpp/beta/local/crud.cpp
- examples/cpp/beta/local/filter-data.cpp
- examples/cpp/beta/local/notifications.cpp
- examples/cpp/beta/local/relationships.cpp
- source/examples/generated/cpp/crud.snippet.beta-create-embedded-object.cpp
- source/examples/generated/cpp/crud.snippet.beta-employee-model.cpp
- source/examples/generated/cpp/crud.snippet.beta-model-with-embedded-object.cpp
- source/examples/generated/cpp/crud.snippet.beta-overwrite-embedded-object.cpp
- source/examples/generated/cpp/crud.snippet.beta-person-model.cpp
- source/examples/generated/cpp/crud.snippet.beta-realm-define-model.cpp
- source/examples/generated/cpp/filter-data.snippet.beta-models.cpp
- source/examples/generated/cpp/filter-data.snippet.beta-set-up-filter-data-tests.cpp
- source/examples/generated/cpp/notifications.snippet.beta-collection-model.cpp
- source/examples/generated/cpp/notifications.snippet.beta-collection.cpp
- source/examples/generated/cpp/relationships.snippet.beta-create-inverse-relationship.cpp
- source/examples/generated/cpp/relationships.snippet.beta-create-to-many-relationship.cpp
- source/examples/generated/cpp/relationships.snippet.beta-create-to-one-relationship.cpp
- source/examples/generated/cpp/relationships.snippet.beta-define-inverse-relationship.cpp
- source/examples/generated/cpp/relationships.snippet.beta-delete-inverse-relationship.cpp
- source/examples/generated/cpp/relationships.snippet.beta-to-many-relationship.cpp
- source/examples/generated/cpp/relationships.snippet.beta-to-one-relationship.cpp
- source/examples/generated/cpp/relationships.snippet.beta-update-inverse-relationship.cpp
- source/sdk/cpp/crud/create.txt
- source/sdk/cpp/crud/delete.txt
- source/sdk/cpp/crud/update.txt
- source/sdk/cpp/model-data/relationships.txt
- source/sdk/cpp/react-to-changes.txt
This PR adds inverse relationships, and also updates a bunch of code examples for changes that the engineering PR has made.
- https://jira.mongodb.org/browse/DOCSP-29741
- [Relationships](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29741/sdk/cpp/model-data/relationships/)
- [CRUD/Create](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29741/sdk/cpp/crud/create/)
- [CRUD/Update](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29741/sdk/cpp/crud/update/)
- [CRUD/Delete](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29741/sdk/cpp/crud/delete/)
- [React to Changes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29741/sdk/cpp/react-to- …
> (DOCSP-29741): C++: Add inverse relationships, update examples for eng updates

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-30806
> (DOCSP-30806): Add docs release notes for w/e June 23

- examples/react-native/__tests__/js/realm-database/change-an-object-model-test.jsx
- examples/react-native/__tests__/ts/realm-database/change-an-object-model-test.tsx
- source/examples/generated/react-native/js/change-an-object-model-test.snippet.add-a-property-to-schema.jsx
- source/examples/generated/react-native/js/change-an-object-model-test.snippet.delete-a-property-from-a-schema.jsx
- source/examples/generated/react-native/js/change-an-object-model-test.snippet.modify-a-property-type.jsx
- source/examples/generated/react-native/js/change-an-object-model-test.snippet.rename-a-property-of-a-schema.jsx
- source/examples/generated/react-native/ts/change-an-object-model-test.snippet.add-a-property-to-schema.tsx
- source/examples/generated/react-native/ts/change-an-object-model-test.snippet.delete-a-property-from-a-schema.tsx
- source/examples/generated/react-native/ts/change-an-object-model-test.snippet.modify-a-property-type.tsx
- source/examples/generated/react-native/ts/change-an-object-model-test.snippet.rename-a-property-of-a-schema.tsx
- source/sdk/react-native/model-data/change-an-object-model.txt
Fixed a TypeScript issue I introduced a while back. Also, standardized code comment formatting/style.
- https://jira.mongodb.org/browse/DOCSP-30787
- [Change an Object Model](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-30787/sdk/react-native/model-data/change-an-object-model/#modify-a-property-type)
> (DOCSP-30787) Fix TypeScript in React Native migrate example

- source/sdk/node/realm-files/open-and-close-a-realm.txt
- https://jira.mongodb.org/browse/DOCSP-31016
- [Configure, Open, and Close a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31016/sdk/node/realm-files/open-and-close-a-realm/#use-an-http-proxy)
> (DOCSP-31016) Port realm-js repo proxy content

- source/web.txt
- source/web/sync.txt
**This assumes the changes in https://github.com/realm/realm-js/pull/5938 are merged**
- (DOCSP-30830) Realm Web Sync QuickStart
- [Web > Atlas Device Sync (Preview)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/web-sync/web/sync/)
> (DOCSP-30830) Realm Web Sync QuickStart

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-30981
> DOCSP-30981 Add docs release notes for w/e June 30

- examples/dart/bundle_example/lib/main.dart
- examples/dart/bundle_example/lib/realm/schemas.g.dart
- examples/dart/bundle_example/pubspec.lock
- examples/dart/bundle_example/pubspec.yaml
- examples/dart/pubspec.yaml
- examples/dart/test_sdk_example/pubspec.yaml
Also included a couple of minor version fixes.
The dart version was updated in the template app in this PR: https://github.com/mongodb-university/realm-template-apps/pull/158
- https://jira.mongodb.org/browse/DOCSP-30404
- Test env changes - see files tab.
> (DOCSP-30404) Update Flutter environment dependencies

- source/sdk/flutter/install.txt
Update Dart and Flutter supported version info on the _Install Realm_ page.
- https://jira.mongodb.org/browse/DOCSP-30404
- [Install Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-30404/sdk/flutter/install/)
> (DOCSP-30404) Update supported version info

- CONTRIBUTING.md
- source/web/api-reference.txt
> fix typos contributing and web api reference docs

- source/realm-query-language.txt
- https://jira.mongodb.org/browse/DOCSP-31339
- [RQL](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31339/realm-query-language/#sort--distinct---limit)
> (DOCSP-31339): RQL Sort order is required, not optional

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-31226
> (DOCSP-31226): Add docs release notes for w/e July 14

- source/includes/dotnet-frameworks.rst
- source/sdk/dotnet.txt
- source/sdk/dotnet/install.txt
- source/sdk/dotnet/model-data/data-binding.txt
https://jira.mongodb.org/browse/DOCSP-30965
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-30965/sdk/dotnet/
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-30965/sdk/dotnet/model-data/data-binding/
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-30965/sdk/dotnet/install/
> Add Avalonia. Remove deprectated ..container

- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/CRUDTest.kt
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/ReadTest.kt
- source/examples/generated/kotlin/CRUDTest.snippet.filter.kt
- source/examples/generated/kotlin/CRUDTest.snippet.sort.kt
- source/examples/generated/kotlin/ReadTest.snippet.kotlin-fts-query.kt
- source/examples/generated/kotlin/ReadTest.snippet.read-realm-dictionary.kt
- https://jira.mongodb.org/browse/DOCSP-30701
- [Read Realm Objects](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-30701/sdk/kotlin/realm-database/crud/read/)
> (DOCSP-30701) Kotlin Parametrize Queries

- source/includes/swift-supported-operating-systems.rst
- source/sdk/swift/app-services/connect-to-app-services-backend.txt
- source/sdk/swift/application-services.txt
- source/sdk/swift/install.txt
- source/sdk/swift/sync.txt
- https://jira.mongodb.org/browse/DOCS-16240
- [Sync Data landing page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCS-16240/sdk/swift/sync/)
- [Application Services landing page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCS-16240/sdk/swift/application-services/)
- [Connect to an App Services App](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCS-16240/sdk/swift/app-services/connect-to-app-services-backend/)
> (DOCS-16240): Swift: Note supported operating systems for App Services functionality

- source/sdk/cpp/install.txt
- https://jira.mongodb.org/browse/DOCSP-29734
- [Install Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29734/sdk/cpp/install/)
> (DOCSP-29734): C++: Add Windows install requirements

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-31393
> (DOCSP-31393) Add docs release notes for w/e July 21

- source/sdk/kotlin/realm-database/schemas/define-realm-object-model.txt
- https://jira.mongodb.org/browse/DOCSP-30140
- [Define an Object Model](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-30140/sdk/kotlin/realm-database/schemas/define-realm-object-model/#unsupported-kotlin-language-features): New "Unsupported Language Features" section
> (DOCSP-30140): Kotlin: Add information about Kotlin language features that are not supported

- source/sdk/swift/sync/stream-data-to-atlas.txt
- https://jira.mongodb.org/browse/DOCSP-31617
- [Stream Data to Atlas](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31617/sdk/swift/sync/stream-data-to-atlas/#open-a-realm): Update the "Tip" callout in the "Open a Realm" step
> (DOCSP-31617): Clarify details about local realm incompatibility with AsymmetricObject

- .github/workflows/check-links.yml
- config/link_checker_bypass_list.json
- source/test file -- delete me
https://jira.mongodb.org/browse/DOCSP-31614
https://github.com/mongodb/docs-realm/actions/runs/5660195687/job/15335385971
> Link checker action

- config/link_checker_bypass_list.json
- source/sdk/kotlin/users/custom-user-data.txt
- source/sdk/node/users/authenticate-users.txt
- source/sdk/swift/react-to-changes.txt
Fix links reported in broken link checker [log](https://github.com/mongodb/docs-realm/actions/runs/5660195687/job/15335385971?pr=2908.) 
- https://jira.mongodb.org/browse/DOCSP-31627
- https://docs-mongodborg-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-31627-links/
> DOCSP-31627: Update links caught by broken link checker

- examples/node/v12/jest.config.ts
- examples/node/v12/jestSetup.ts
- examples/node/v12/package.json
- examples/node/v12/readme.md
This small PR makes some minor updates to the Node.js SDK docs test suite. Mainly, it allows for running a single test file instead of a project or or the whole suite.
> Update node v12 suite

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-31560
> (DOCSP-31560): Add docs release notes for w/e July 28

- source/sdk/react-native/crud/delete.txt
- source/sdk/react-native/crud/update.txt
- source/sdk/react-native/install.txt
- source/sdk/react-native/model-data/data-types/dictionaries.txt
- source/sdk/react-native/model-data/data-types/embedded-objects.txt
- source/sdk/react-native/model-data/data-types/mixed.txt
- source/sdk/react-native/model-data/data-types/sets.txt
- source/sdk/react-native/model-data/data-types/uuid.txt
- source/sdk/react-native/quick-start.txt
- source/sdk/react-native/realm-files/configure-a-realm.txt
Updated links to old React docs to point to the new React docs.
- https://jira.mongodb.org/browse/DOCSP-31246
- [CRUD - Delete](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31246/sdk/react-native/crud/delete/)
- [CRUD - Update](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31246/sdk/react-native/crud/update/)
- [Install Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31246/sdk/react-native/install/)
- [Dictionaries](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31246/sdk/react-native/model-data/data-types/dictionaries/)
- [Embedded Objects](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31246/sdk/react-native/model-data/da …
> (DOCSP-31246) Point React links to new React docs

- source/sdk/kotlin/realm-database/crud/create.txt
- source/sdk/kotlin/realm-database/crud/delete.txt
- source/sdk/kotlin/realm-database/crud/read.txt
- source/sdk/kotlin/realm-database/crud/update.txt
- source/sdk/kotlin/realm-database/schemas/define-realm-object-model.txt
- source/sdk/kotlin/realm-database/schemas/relationships.txt
Move embedded object content from [Relationships](https://www.mongodb.com/docs/realm/sdk/kotlin/realm-database/schemas/relationships/#define-an-embedded-object) page to respective CRUD pages
- https://jira.mongodb.org/browse/DOCSP-30340
- [Relationships](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-30340-relationships/sdk/kotlin/realm-database/schemas/relationships/)
- [Define an Object Model](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-30340-relationships/sdk/kotlin/realm-database/schemas/define-realm-object-model/)
- [Create](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-30340-relationships/sdk/kotlin/realm-database/crud/create/)
- …
> DOCSP-30340: Update Relationships - Kotlin SDK page

- source/sdk/cpp/app-services/connect-to-app.txt
- source/sdk/cpp/application-services.txt
- source/sdk/cpp/crud/create.txt
- source/sdk/cpp/crud/delete.txt
- source/sdk/cpp/crud/filter-data.txt
- source/sdk/cpp/crud/read.txt
- source/sdk/cpp/crud/threading.txt
- source/sdk/cpp/crud/update.txt
- source/sdk/cpp/manage-users.txt
- source/sdk/cpp/model-data/object-models.txt
- source/sdk/cpp/model-data/relationships.txt
- source/sdk/cpp/model-data/supported-types.txt
- source/sdk/cpp/realm-files/configure-and-open-a-realm.txt
- source/sdk/cpp/sync.txt
- source/sdk/cpp/sync/sync-subscriptions.txt
- https://jira.mongodb.org/browse/DOCSP-29747
- [Staged C++ Docs](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29747/sdk/cpp/)
> (DOCSP-29747): C++: Remove unnecessary page headers, Key Concept verbiage

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-31787
> (DOCSP-31787): Add docs release notes for w/e August 4

- source/includes/tip-cpp-beta-experimental-features.rst
- source/sdk/cpp/install.txt
- source/sdk/cpp/quick-start.txt
- https://jira.mongodb.org/browse/DOCSP-31933
- [Install](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31933/sdk/cpp/install/#experimental-preview-features)
- [Quick Start](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31933/sdk/cpp/quick-start/)
- [Model Data/Object Models](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31933/sdk/cpp/model-data/object-models/#define-a-new-object-type): For an example of the "tip" which appears on _many_ pages throughout the SDK
> (DOCSP-31933): C++ SDK: Note minimum version for experimental namespace

- source/sdk/cpp/model-data/supported-types.txt
- https://jira.mongodb.org/browse/DOCSP-29746
- [Supported Types](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29746/sdk/cpp/model-data/supported-types/#collection-types): New "Collection Types" section based on [the Swift page](https://www.mongodb.com/docs/realm/sdk/swift/model-data/supported-types/)
> (DOCSP-29746): C++: Add collection type info

- source/sdk/react-native/crud.txt
- source/sdk/react-native/crud/create.txt
- source/sdk/react-native/crud/delete.txt
- source/sdk/react-native/crud/update.txt
- source/sdk/react-native/model-data/change-an-object-model.txt
- source/sdk/react-native/model-data/data-types/embedded-objects.txt
- source/sdk/react-native/model-data/data-types/property-types.txt
- source/sdk/react-native/model-data/define-a-realm-object-model.txt
- source/sdk/react-native/quick-start.txt
- source/sdk/react-native/realm-files/bundle.txt
- source/sdk/react-native/realm-files/compact-realm.txt
- source/sdk/react-native/sync-data/client-reset-data-recovery.txt
- source/sdk/react-native/sync-data/flexible-sync.txt
- source/sdk/react-native/sync-data/handle-sync-errors.txt
- source/sdk/react-native/sync-data/stream-data-to-atlas.txt
- source/sdk/react-native/test-and-debug/testing.txt
- source/sdk/react-native/use-realm-react.txt
This PR adds links to `@realm/react` API reference docs. It does not try to solve the larger problem of mixing `:js-sdk:` and `:realm-react-sdk:` links on the same page (potentially confusing readers). Ideally, we could link to just `:realm-react-sdk:` in the React Native docs, but that docs set doesn't include all of the regular Realm APIs.
There are a couple of other ongoing pieces of work to address this linking confusion.
- https://jira.mongodb.org/browse/DOCSP-27370
This PR affects lots of pages. I'll try to include all direct links here:
- [CRUD](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27370/sdk/react-native/crud/)
- [CRUD - Create](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27370/sdk/react-native/crud/create/ …
> (DOCSP-27370) Include @realm/react reference docs in React Native SDK docs

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-32037
> (DOCSP-32037): Add docs release notes for w/e August 11

- source/sdk/swift.txt
- https://jira.mongodb.org/browse/DOCSP-32289
- [Swift SDK landing page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-32289/sdk/swift/)
> (DOCSP-32289): Swift: Add offline realm access example to landing page

- source/sdk/dotnet/realm-files/realms.txt
- source/sdk/dotnet/sync/configure-and-open-a-synced-realm.txt
- source/sdk/java/crud/filter-data.txt
- source/sdk/java/crud/read.txt
- source/sdk/java/model-data/relationships.txt
- source/sdk/react-native/realm-files/configure-a-realm.txt
- source/sdk/swift/crud/read.txt
- source/sdk/swift/crud/update.txt
- source/sdk/swift/model-data/change-an-object-model.txt
- source/sdk/swift/model-data/model-data-device-sync.txt
- source/sdk/swift/model-data/relationships.txt
- source/sdk/swift/model-data/supported-types.txt
- source/sdk/swift/realm-files/compacting.txt
- source/sdk/swift/swiftui/model-data/define-a-realm-object-model.txt
- source/sdk/swift/sync/configure-and-open-a-synced-realm.txt
- https://jira.mongodb.org/browse/DOCSP-29403
- [Update Data .NET (Many other pages updated, please check RST)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)
> DOCSP-29403 Remove 'Key Concept' Headers

- source/sdk/kotlin/realm-database/schemas/define-realm-object-model.txt
- source/sdk/kotlin/realm-database/schemas/supported-types.txt
Add `RealmAny` to Supported Types list
https://github.com/realm/realm-kotlin/issues/1392#issuecomment-1683806572
- [Supported Types - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/add-realm-any/sdk/kotlin/realm-database/schemas/supported-types/)
> Update supported types list with RealmAny

- source/includes/manage-user-sessions.rst
- source/includes/refresh-token-expiry.rst
- source/includes/user-access-token.rst
- source/sdk/cpp/manage-users.txt
- source/sdk/cpp/users/authenticate-users.txt
- source/sdk/dotnet/manage-users/authenticate.txt
- source/sdk/dotnet/work-with-users.txt
- source/sdk/flutter/users.txt
- source/sdk/flutter/users/access-token.txt
- source/sdk/flutter/users/authenticate.txt
- source/sdk/kotlin/users.txt
- source/sdk/kotlin/users/authenticate-users.txt
- source/sdk/node/manage-users.txt
- source/sdk/node/users/authenticate-users.txt
- source/sdk/react-native/manage-users.txt
- source/sdk/react-native/manage-users/authenticate-users.txt
- source/sdk/swift/users/authenticate-users.txt
- source/sdk/swift/work-with-users.txt
- source/web/authenticate.txt
- source/web/users.txt
For each SDK, update: 
- Authenticate Users page with new Refresh Token Expiration subsection
- Manage Users page with info on refresh token expiry
- https://jira.mongodb.org/browse/DOCSP-29282
- C++
- [Auth Users](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-29282-token-expiry/sdk/cpp/users/authenticate-users/#refresh-token-expiration)
- [Manage Users](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-29282-token-expiry/sdk/cpp/manage-users/#user-sessions)
- Flutter
- [Get an Access Token](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-29282-token-expiry/sdk/flutter/users/access-token/#refresh-token-expiration)
- [Manage Users](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xl …
> DOCSP-29282: Add info about refresh token expiration

- .github/workflows/ios.yml
- .github/workflows/swiftui.yml
- source/sdk/swift/swiftui/write.txt
- https://jira.mongodb.org/browse/DOCSP-27734
- [Write Data - SwiftUI](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27734/sdk/swift/swiftui/write/#add-or-remove-objects-in-an-observedresults-collection)
> (DOCSP-27734): SwiftUI: Clarify adding and removing from ObservedResults

- source/sdk/react-native/install.txt
This PR cannot be merged until Realm.js v12 is released in GA.
- https://jira.mongodb.org/browse/DOCSP-31311
- [Install Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31311/sdk/react-native/install/)
> (DOCSP-31311) Update version info on install page [Realm.js v12]

- source/example-projects.txt
- https://jira.mongodb.org/browse/DOCSP-32464
- [Example projects](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-32464/example-projects/)
> (DOCSP-32464): Updated List of Example Projects

- source/sdk/cpp/crud/create.txt
- source/sdk/cpp/crud/delete.txt
- source/sdk/cpp/crud/filter-data.txt
- source/sdk/cpp/crud/threading.txt
- source/sdk/cpp/crud/update.txt
- source/sdk/cpp/model-data/object-models.txt
- source/sdk/cpp/model-data/relationships.txt
- source/sdk/cpp/model-data/supported-types.txt
- source/sdk/cpp/quick-start.txt
- source/sdk/cpp/react-to-changes.txt
- source/sdk/cpp/realm-files/configure-and-open-a-realm.txt
- source/sdk/cpp/sync/handle-sync-errors.txt
- source/sdk/cpp/sync/stream-data-to-atlas.txt
- source/sdk/cpp/sync/sync-subscriptions.txt
- https://jira.mongodb.org/browse/DOCSP-32595
- [C++ SDK docs staged](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-32595/sdk/cpp)
> (DOCSP-32595): C++: Present experimental code examples as Current

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-32479
> DOCSP-32479 Add docs release notes for w/e August 25

- examples/dart/pubspec.lock
- examples/dart/pubspec.yaml
- examples/dart/test/read_write_data_test.dart
- source/examples/generated/flutter/car.snippet.define-model-flutter.dart
- source/examples/generated/flutter/read_write_data_test.snippet.filter-iterable.dart
- source/sdk/flutter/realm-database/read-and-write-data.txt
- https://jira.mongodb.org/browse/DOCSP-30214
- [Read and Write Data](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-30214/sdk/flutter/realm-database/read-and-write-data/#filter-results)
> (DOCSP-30214) Flutter: Create new filter example with iterable argument

- source/example-projects.txt
Apple Sign in authentication ([https://github.com/realm/realm-swift-samples/tree/main/AppleSignInAuthentication](https://github.com/realm/realm-swift-samples/tree/main/AppleSignInAuthentication))
Kotlin Examples (https://github.com/realm/realm-kotlin-samples/tree/main
.NET Atlas Search (https://github.com/realm/realm-dotnet-samples/tree/main/AtlasSearch
- https://jira.mongodb.org/browse/DOCSP-32705
- [Example Projects page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-32705/example-projects/)
> DOCSP-32705 Update Example Projects Table

- source/sdk/node/quick-start.txt
- https://jira.mongodb.org/browse/DOCSP-32526
- [Node.js Quick Start](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32526/sdk/node/quick-start/)
> (DOCSP-32526): Quick Start: Update JS API reference links

- source/sdk/node/model-data/define-a-realm-object-model.txt
- source/sdk/node/model-data/modify-an-object-schema.txt
The linked Jira ticket calls to also update the Relationships & Embedded Objects page, but I've got a different PR out for that page already, so I'll update those links in that PR.
- https://jira.mongodb.org/browse/DOCSP-32528
- [Node.js - Define an Object Model](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32528/sdk/node/model-data/define-a-realm-object-model/)
- [Node.js - Change an Object Model](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32528/sdk/node/model-data/modify-an-object-schema/)
> (DOCSP-32528): Node.js Model Data: Update JS API reference links

- source/sdk/node/crud/create.txt
- source/sdk/node/crud/delete.txt
- source/sdk/node/crud/query-data.txt
- source/sdk/node/crud/read.txt
- source/sdk/node/crud/update.txt
- https://jira.mongodb.org/browse/DOCSP-32530
- [Create](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32530/sdk/node/crud/create/)
- [Read](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32530/sdk/node/crud/read/)
- [Update](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32530/sdk/node/crud/update/)
- [Delete](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32530/sdk/node/crud/delete/)
- [Query Data](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32530/sdk/node/crud/query-data/)
> (DOCSP-32530): CRUD: Update JS API reference links

- examples/react-native/v12/TestApp/App.tsx
- examples/react-native/v12/TestApp/__tests__/models/ObjectModels.test.tsx
- examples/react-native/v12/TestApp/__tests__/models/readme.md
- examples/react-native/v12/TestApp/src/components/ObjectModels.tsx
- source/examples/generated/react-native/v12/ObjectModels.snippet.model-optional-properties.tsx.rst
- source/sdk/react-native/model-data/define-a-realm-object-model.txt
- [Define a Realm Object Model](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fix-rn-optional-property-example/sdk/react-native/model-data/define-a-realm-object-model/#declare-an-optional-property)
> React Native: Fix incorrect optional properties example

- source/sdk/node/integrations/electron-cra.txt
- source/sdk/node/integrations/electron.txt
- https://jira.mongodb.org/browse/DOCSP-32538
- [Quick Start with Electron](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32538/sdk/node/integrations/electron/)
- [Quick Start with Electron Using React](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32538/sdk/node/integrations/electron-cra/)
> (DOCSP-32538): Node.js Integration Guides: Update API reference links for v12

- source/sdk/node/react-to-changes.txt
- https://jira.mongodb.org/browse/DOCSP-32532
- [React to Changes](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32532/sdk/node/react-to-changes/)
> (DOCSP-32532): React to Changes: Update JS API reference links

- source/includes/node-open-a-synced-realm.rst
- source/sdk/node/sync/client-reset-data-recovery.txt
- source/sdk/node/sync/flexible-sync.txt
- source/sdk/node/sync/handle-sync-errors.txt
- source/sdk/node/sync/log-level.txt
- source/sdk/node/sync/partition-based-sync.txt
- source/sdk/node/sync/stream-data-to-atlas.txt
The linked Jira tickets cover updating the entire Sync section. I already did the "Configure and Open a Synced Realm" and "Manage Sync Sessions" pages as part of a different PR.
- https://jira.mongodb.org/browse/DOCSP-32536
- https://jira.mongodb.org/browse/DOCSP-32537
- [Manage Flexible Sync Subscriptions](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32537/sdk/node/sync/flexible-sync/)
- [Handle Sync Errors](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32537/sdk/node/sync/handle-sync-errors/)
- [Manual Client Reset Data Recovery](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32537/sdk/node/sync/client-reset-data-recovery/)
- [Set the Client Log Level](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32537/sdk/node/sync/log-level/)
- [Stream Data to …
> (DOCSP-32537): Sync: Update JS API reference links for v12

- source/includes/multiple-app-client-details-and-app-config-cache.rst
- source/sdk/dotnet/app-services/connect-to-app-services-backend.txt
- source/sdk/flutter/app-services/connect-to-app.txt
- source/sdk/java/app-services/connect-to-app-services-backend.txt
- source/sdk/kotlin/app-services/connect-to-app-services-backend.txt
- source/sdk/node/app-services/connect-to-app-services-backend.txt
- source/sdk/react-native/app-services/connect-to-app-services-app.txt
- source/sdk/swift/app-services/connect-to-app-services-backend.txt
- https://jira.mongodb.org/browse/DOCSP-32151
- [Connect to an Atlas App](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-32151/sdk/swift/app-services/connect-to-app-services-backend/)
> (DOCSP-32151): Swift: Add info about not changing App config after initialization

- source/includes/flex-sync-limitations.rst
- source/sdk/dotnet/sync/flexible-sync.txt
- source/sdk/flutter/sync/manage-sync-subscriptions.txt
- source/sdk/java/sync/flexible-sync.txt
- source/sdk/kotlin/sync/subscribe.txt
- source/sdk/node/sync/flexible-sync.txt
- source/sdk/react-native/sync-data/flexible-sync.txt
- source/sdk/swift/sync/flexible-sync.txt
This is related to the corresponding [App Services docs PR](https://github.com/mongodb/docs-app-services/pull/565), and the ref used in the link in this PR points to the new content in App Services. That must be merged first, and this link is expected to not work at this time.
- https://jira.mongodb.org/browse/DOCSP-31839
- [Manage Sync Subscriptions for every SDK that has it (this is Flutter)](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-31839/sdk/flutter/sync/manage-sync-subscriptions/#flexible-sync-rql-requirements-and-limitations)
> (DOCSP-31839): Add indexed queryable fields query requirements

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-32890
> DOCSP-32890 Add docs release notes for w/e September 8

- source/sdk/cpp/sync/stream-data-to-atlas.txt
- source/sdk/dotnet/sync/asymmetric-sync.txt
- source/sdk/kotlin/sync/stream-data-to-atlas.txt
- source/sdk/node/sync/stream-data-to-atlas.txt
- source/sdk/react-native/sync-data/stream-data-to-atlas.txt
- source/sdk/swift/sync/stream-data-to-atlas.txt
- https://jira.mongodb.org/browse/DOCS-16377
- [C++ - Stream Data to Atlas](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCS-16377/sdk/cpp/sync/stream-data-to-atlas/#create-asymmetric-objects)
- [Kotlin - Stream Data to Atlas](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCS-16377/sdk/kotlin/sync/stream-data-to-atlas/#create-asymmetric-objects)
- [.NET - Stream Data to Atlas](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCS-16377/sdk/dotnet/sync/asymmetric-sync/)
- [Node.js - Stream Data to Atlas](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCS-16377/sdk/node/sync/stream-data-to-atlas/#create-asymmetric-objects)
- [React Native SDK - Stream Data to Atlas](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCS-16377/sdk/react-native/sync-data/stream-data-to-atlas/) …
> (DOCS-16377): Clarify Data Ingest does not leave objects in realms

- source/studio/install.txt
- https://jira.mongodb.org/browse/DOCSP-33019
- [Install Realm Studio](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-33019/studio/install/)
> Realm Studio: Clarify Install instructions/links

- source/example-projects.txt
- https://jira.mongodb.org/browse/DOCSP-32940
- [Example Projects](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-32940/example-projects/)
> DOCSP-32940 Update Example Projects page

- source/studio/install.txt
- https://jira.mongodb.org/browse/DOCSP-33110
- [Install Realm Studio](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-33110/studio/install/)
> (DOCSP-33110): Realm Studio: Add more relevant info for selecting a version

- examples/cpp/beta/sync/CMakeLists.txt
- examples/cpp/beta/sync/authentication.cpp
- source/examples/generated/cpp/authentication.snippet.beta-get-current-user.cpp
- source/examples/generated/cpp/authentication.snippet.check-user-is-logged-in.cpp
- source/sdk/cpp/users/authenticate-users.txt
- https://jira.mongodb.org/browse/DOCSP-32489
- [Authenticate Users](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32489/sdk/cpp/users/authenticate-users/#get-the-current-user)
> (DOCSP-32489): C++: Add app::get_current_user() and user::is_logged_in()

- source/index.txt
- https://jira.mongodb.org/browse/DOCSP-32296
- [Realm Landing Page](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32296/): Add a link to Atlas App Services and move the App Services card to the top of the stack
> (DOCSP-32296): Add link to App Services per Top 250 CTA request

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-33012
> (DOCSP-33012): Add docs release notes for w/e Sept 15

- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AppClientTest.kt
- source/examples/generated/kotlin/AppClientTest.snippet.close-app-client.kt
- source/examples/generated/kotlin/AppClientTest.snippet.configure-app-client.kt
- source/examples/generated/kotlin/AppClientTest.snippet.initialize-app-client.kt
- source/examples/generated/kotlin/AppClientTest.snippet.set-custom-http-headers.kt
- source/sdk/kotlin/app-services.txt
- source/sdk/kotlin/app-services/connect-to-app-services-backend.txt
- Add info for custom HTTP headers 
- Update existing [Connect to App Services](https://www.mongodb.com/docs/realm/sdk/kotlin/app-services/connect-to-app-services-backend/) page
- https://jira.mongodb.org/browse/DOCSP-32926
- https://jira.mongodb.org/browse/DOCSP-32216
- [Connect to Atlas App Services - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-32926-http-headers/sdk/kotlin/app-services/connect-to-app-services-backend/)
> (DOCSP-32926 & DOCSP- 32216): Custom HTTP Headers for Kotlin

- source/example-projects.txt
Added the following projects:
- Vehicle Simulator and Controller (Swift)
- Analytics (Node.js)
- Smart Factory Interface (.NET)
- https://jira.mongodb.org/browse/DOCSP-33155
- [Example Projects](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-33155/example-projects/)
> DOCSP-33155 Example Projects Update 9/20/23

- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
- snooty.toml
- source/examples/generated/kotlin/AuthenticationTest.snippet.access-token-refresh.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.anonymous-authentication-reuse-existing.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.anonymous-authentication.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.api-key-authentication.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.apple-authentication.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.auth-change-listener.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.create-new-user.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.custom-function-authentication.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.email-password-authentication.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.jwt-authentication.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.link-credentials.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.log-out.kt
- source/includes/tip-acct-deletion-reqs.rst
- source/sdk/kotlin/users.txt
- source/sdk/kotlin/users/authenticate-users.txt
- source/sdk/kotlin/users/custom-user-data.txt
- source/sdk/kotlin/users/delete-users.txt
- source/sdk/kotlin/users/user-metadata.txt
- Convert existing [Manage Users](https://www.mongodb.com/docs/realm/sdk/kotlin/users/) landing page to a container page
- Move all relevant information to any child pages 
- Update and rename existing [Authenticate Users](https://www.mongodb.com/docs/realm/sdk/kotlin/users/authenticate-users/) page to Create and Authenticate Users
- Split existing [Create and Delete Users](https://www.mongodb.com/docs/realm/sdk/kotlin/users/delete-users/) page to only Delete Users 
- Clean up any example in test suite
- https://jira.mongodb.org/browse/DOCSP-30347
- [Create & Authenticate Users - Kotlin SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/30347-manage-users-page/sdk/kotlin/users/authenticate-users/) - updated 
- [Delete Users - Kotlin …
> DOCSP-30347: Convert Manage Users landing page

- examples/dotnet/ConsoleTests/ConsoleTests.csproj
- examples/dotnet/DataBinding/DataBinding.csproj
- examples/dotnet/Examples/DataTypesSectionExamples.cs
- examples/dotnet/Examples/ErrorHandler.cs
- examples/dotnet/Examples/Examples.csproj
- examples/dotnet/LocalOnly/LocalOnly.csproj
- source/examples/generated/dotnet/Convert.snippet.sync-to-nosync.cs
- source/examples/generated/dotnet/ErrorHandler.snippet.handle-errors.cs
https://jira.mongodb.org/browse/DOCSP-33269
n/a
> update nuget package, re-enable unit test, and remove new warning

- snooty.toml
**To be merged & deployed 9/26 5:55am ET**
See https://github.com/mongodb/docs-app-services/pull/587 for App Services-side PR
- https://jira.mongodb.org/browse/DOCSP-32998
- https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-32998-banner/
> DOCSP-32998: Add Atlas Device SDK banner to entire project

- source/introduction.txt
- source/sdk/react-native.txt
- source/sdk/swift.txt
Hey @dacharyc!
Here are the manual tags for the Realm repo.  This is it for the tagging for Paris.  If everything looks good, please merge when you have a moment.
Thank you!
Sarah
- https://jira.mongodb.org/browse/DOCSP-27817
> DOCSP-27817 manual tags for realm repo

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-33144
> DOCSP-33144 Add docs release notes for w/e Sept 22

- examples/node/v12/__tests__/full-text-search.test.ts
- source/examples/generated/node/v12/full-text-search.test.snippet.node-fts-annotation.ts
- source/examples/generated/node/v12/full-text-search.test.snippet.node-fts-query.ts
- source/sdk/node/crud/query-data.txt
- source/sdk/node/model-data/define-a-realm-object-model.txt
- https://jira.mongodb.org/browse/DOCSP-32587
- [Query Data (new section)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-32587/sdk/node/crud/query-data/#filter-with-full-text-search)
- [Define an Object Model (new section)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-32587/sdk/node/model-data/define-a-realm-object-model/)
> DOCSP-32587 Node.js Full Text Search

- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.add-a-new-user.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.delete-user.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.list-all-users.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.log-out-a-user.kt
- source/examples/generated/kotlin/AuthenticationTest.snippet.remove-a-user.kt
- source/sdk/kotlin/users.txt
- source/sdk/kotlin/users/authenticate-users.txt
- source/sdk/kotlin/users/multi-user-applications.txt
Add new Manage Multi-User Applications page based on [existing Java](https://www.mongodb.com/docs/realm/sdk/java/users/multi-user-applications/) page
- https://jira.mongodb.org/browse/DOCSP-30335
- [Manage Multi-User Applications - Kotlin SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-30335-multi-user-app/sdk/kotlin/users/multi-user-applications/)
> DOCSP-30335: Add Manage Multi-User Applications page to Kotlin

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-33266
> (DOCSP-33266): Add docs release notes for w/e September 29

- source/example-projects.txt
Added:
- Netflix-like Movie App (React Native)
- Split Data into Multiple Realms (Netflix-like Movie App in Core Project section)
- https://jira.mongodb.org/browse/DOCSP-33302
- [Realm Example Projects](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-33302/example-projects/)
> DOCSP-33302 Update Example Projects Page 9/27/23

- source/includes/change-notification-limit.rst
- source/sdk/cpp/react-to-changes.txt
- source/sdk/dotnet/react-to-changes.txt
- source/sdk/flutter/realm-database/react-to-changes.txt
- source/sdk/java/react-to-changes.txt
- source/sdk/kotlin/realm-database/react-to-changes.txt
- source/sdk/node/react-to-changes.txt
- source/sdk/react-native/react-to-changes.txt
- source/sdk/swift/react-to-changes.txt
- https://jira.mongodb.org/browse/DOCS-16393
- [C++ - React to Changes](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCS-16393/sdk/cpp/react-to-changes/#change-notification-limits)
- [Flutter - React to Changes](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCS-16393/sdk/flutter/realm-database/react-to-changes/#change-notification-limits)
- [Java - React to Changes](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCS-16393/sdk/java/react-to-changes/#change-notification-limits)
- [Kotlin - React to Changes](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCS-16393/sdk/kotlin/realm-database/react-to-changes/#change-notification-limits)
- [.NET - React to Changes](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCS-16393/sdk/dotnet/react-to-changes/#change-notification-lim …
> (DOCS-16393): Document the change notification limit

- source/examples/generated/node/v12/errors.test.snippet.handle-compensating-write-error.js
- source/examples/generated/node/v12/errors.test.snippet.handle-compensating-write-error.ts
- source/sdk/node/sync/handle-sync-errors.txt
- [Handle Sync Errors](https://preview-mongodbdacharyc.gatsbyjs.io/realm/fix-missing-node-snippet-errors/sdk/node/sync/handle-sync-errors/#handle-compensating-write-errors)
> Node.js: Fix missing snippet errors

- examples/ios/Examples/Logging.swift
- source/examples/generated/code/start/Logging.snippet.define-custom-logger.swift
- source/examples/generated/code/start/Logging.snippet.set-default-logger.swift
- source/sdk/swift/logging.txt
- https://jira.mongodb.org/browse/DOCSP-33073
- [Logging - Swift SDK](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-33073/sdk/swift/logging/)
> (DOCSP-33073): Clarify requirement to set a logger before initializing an App

- source/includes/ios-ipados-bad-alloc.rst
- source/sdk/dotnet/troubleshooting.txt
- source/sdk/flutter/troubleshooting.txt
- source/sdk/kotlin.txt
- source/sdk/kotlin/troubleshooting.txt
- source/sdk/react-native/test-and-debug.txt
- source/sdk/react-native/test-and-debug/troubleshooting.txt
- source/sdk/swift/test-and-debug.txt
- https://jira.mongodb.org/browse/DOCSP-32960
- [Troubleshooting - Flutter](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32960/sdk/flutter/troubleshooting/#ios-ipad-os-bad-alloc-not-enough-memory-available)
- [Troubleshooting - Kotlin](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32960/sdk/kotlin/troubleshooting/)
- [Troubleshooting - .NET](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32960/sdk/dotnet/troubleshooting/#ios-ipad-os-bad-alloc-not-enough-memory-available)
- [Troubleshooting - React Native ](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32960/sdk/react-native/test-and-debug/troubleshooting/)
- [Test and Debug - Swift](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32960/sdk/swift/test-and-debug/#bad-alloc-not-enough-memory-ava …
> (DOCSP-32960): Add info about Apple extended virtual addressing entitlement usage

- examples/cpp/beta/asymmetric/CMakeLists.txt
- examples/cpp/beta/asymmetric/asymmetric-sync.cpp
- source/examples/generated/cpp/asymmetric-sync.snippet.beta-open-asymmetric-synced-realm.cpp
- source/sdk/cpp/realm-files/configure-and-open-a-realm.txt
- source/sdk/cpp/sync/stream-data-to-atlas.txt
- https://jira.mongodb.org/browse/DOCSP-33119
- [Configure & Open a Realm](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-33119/sdk/cpp/realm-files/configure-and-open-a-realm/#open-a-synced-realm)
- [Stream Data to Atlas](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-33119/sdk/cpp/sync/stream-data-to-atlas/)
> (DOCSP-33119): C++: Update asymmetric sync for 0.3.0-preview

- examples/ios/Examples/FlexibleSync.swift
- examples/ios/Examples/RealmActor.swift
- examples/ios/RealmExamples.xcodeproj/project.pbxproj
- examples/ios/RealmExamples.xcodeproj/xcshareddata/xcschemes/Test Examples.xcscheme
- examples/ios/TestUtils/SyncTestUtils.swift
- source/examples/generated/code/start/FlexibleSync.snippet.flex-sync-open-realm.swift
- source/examples/generated/code/start/FlexibleSync.snippet.initialize-app-authenticate-user.swift
- source/examples/generated/code/start/FlexibleSync.snippet.remove-all-unnamed-subscriptions.swift
- source/examples/generated/code/start/FlexibleSync.snippet.subscribe-api-unsubscribe.swift
- source/examples/generated/code/start/FlexibleSync.snippet.subscribe-to-results-on-custom-actor.swift
- source/examples/generated/code/start/FlexibleSync.snippet.subscribe-to-results-on-main-actor.swift
- source/examples/generated/code/start/FlexibleSync.snippet.subscribe-to-results-unnamed.swift
- source/examples/generated/code/start/FlexibleSync.snippet.subscribe-to-results-with-name.swift
- source/examples/generated/code/start/FlexibleSync.snippet.subscribe-wait-for-sync.swift
- source/sdk/swift/sync/flexible-sync.txt
DO NOT MERGE until this feature ships. It depends on realm-swift PR #8244. After release:
- https://jira.mongodb.org/browse/DOCSP-29399
- [Manage Flexible Sync Subscriptions](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29399/sdk/swift/sync/flexible-sync/)
> (DOCSP-29399): Swift: Subscribe API documentation

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-33420
> DOCSP-33420 Add docs release notes for w/e October 6

- source/sdk/node/install.txt
> Fix Node.js Realm import example

- source/example-projects.txt
- ObjectAsAPI (.NET)
- Flexible Sync Playground (Node.js)
- Connection State Change & Error Handling (React Native)
- Offline Support and Realm Access (React Native, Electron, Web, and Node)
- https://jira.mongodb.org/browse/DOCSP-33485
- [Example Projects](https://preview-mongodblindseymoore.gatsbyjs.io/realm/DOCSP-33485/example-projects/)
> DOCSP-33485 Example Projects Page Update

- examples/react-native/v12/TestApp/ios/Podfile.lock
- examples/react-native/v12/TestApp/ios/TestApp.xcodeproj/project.pbxproj
- examples/react-native/v12/TestApp/metro.config.js
- examples/react-native/v12/TestApp/package-lock.json
- examples/react-native/v12/TestApp/package.json
Upgraded various bundler dependencies in package.json.
> update metro bundler dependencies

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-33553
> DOCSP-33553 Add docs release notes for w/e October 13

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-33716
> DOCSP-33716 Add docs release notes for w/e October 20

- examples/cpp/beta/local/CMakeLists.txt
- examples/cpp/beta/local/crud.cpp
- examples/cpp/beta/local/supported-types.cpp
- source/examples/generated/cpp/crud.snippet.beta-model-with-set-property.cpp
- source/examples/generated/cpp/crud.snippet.delete-set.cpp
- source/examples/generated/cpp/crud.snippet.read-set.cpp
- source/examples/generated/cpp/crud.snippet.update-set.cpp
- source/examples/generated/cpp/crud.snippet.write-set-object.cpp
- source/examples/generated/cpp/supported-types.snippet.beta-required-set.cpp
- source/sdk/cpp/crud/create.txt
- source/sdk/cpp/crud/delete.txt
- source/sdk/cpp/crud/read.txt
- source/sdk/cpp/crud/update.txt
- source/sdk/cpp/model-data/relationships.txt
- source/sdk/cpp/model-data/supported-types.txt
- source/sdk/cpp/react-to-changes.txt
- https://jira.mongodb.org/browse/DOCSP-29739
- [Supported Types](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-29739/sdk/cpp/model-data/supported-types/#set)
- [CRUD/Create](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-29739/sdk/cpp/crud/create/#create-an-object-with-a-set-property)
- [CRUD/Read](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-29739/sdk/cpp/crud/read/#read-a-set-property)
- [CRUD/Update](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-29739/sdk/cpp/crud/update/#update-a-set-property)
- [CRUD/Delete](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-29739/sdk/cpp/crud/delete/#delete-set-values)
- [React to Changes](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-29739/sdk/cpp/react-to-changes/#register-a-collection-change- …
> (DOCSP-29739): C++: Add documentation for Set data type

- source/sdk/cpp/model-data/object-models.txt
- https://jira.mongodb.org/browse/DOCSP-33254
- [Object Types and Schemas](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-33254/sdk/cpp/model-data/object-models/#define-an-asymmetric-object)
> (DOCSP-33254): C++: Doc asymmetric object link change that came with core update

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-33933
> (DOCSP-33933): Add docs release notes for w/e Nov 3

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-34097
> (DOCSP-34097): Add docs release notes for w/e November 10

- docs-release-notes.md
- https://jira.mongodb.org/browse/DOCSP-34366
> DOCSP-34366 Add docs release notes for w/e November 17

- source/index.txt
- source/introduction.txt
- source/sdk/react-native.txt
- source/sdk/swift.txt
Hey @dacharyc!  I'm on to the next round of top 250 updates.  Please feel free to edit the descriptions I put in--I just picked a sentence from each page that looked good.  We need something; doesn't have to be perfect but if you think something else would be better, please change!
Thanks!
Sarah
- https://jira.mongodb.org/browse/DOCSP-33172
- Staging link: https://preview-mongodbsarahemlin.gatsbyjs.io/realm/DOCSP-33172/
- Build log: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=655bb2245b686d6bd9341da5
> DOCSP-33172 add meta::description for top 250

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-34573
> (DOCSP-34573): Add docs release notes for w/e November 24

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-34625
> DOCSP-34625 Add docs release notes for w/e December 1

- sdk-reference/index.html
Jira ticket: https://jira.mongodb.org/browse/DOCSP-34639
No staging page because this page isn't built as part of `docs-realm`. The live page is here: https://www.mongodb.com/docs/realm-sdks/
Don't include in release notes
> (DOCSP-34639) Add Flutter link to API ref landing page

- .github/pull_request_template.md
This PR adds a reminder about content tags to the PR checklist.
> Add tagging checklist item

- source/studio.txt
- source/studio/view-atlas-data-sync.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-34626
- [View Data with Device Sync](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-34626/studio/view-atlas-data-sync/): New page describing the new functionality and how to use it.
- [Realm Studio landing page](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-34626/studio/): Tweak the intro to mention the new functionality and reword "create Realm files."
- **Realm Studio**
- Landing Page: Add a bullet listing the ability to connect, view, and modify data using Device Sync.
- View Data with Device Sync: New page describing how to use Realm Studio to test subscriptions and view Atlas data changes in real time with Device Sync. …
> (DOCSP-34626): Realm Studio: New View Atlas Data with Device Sync page

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-34725
> (DOCSP-34725): Add docs release notes for w/e Dec 8

- source/sdk/cpp/react-to-changes.txt
- source/sdk/flutter/realm-database/model-data/define-realm-object-schema.txt
- source/sdk/kotlin/realm-database/crud/read.txt
- source/sdk/kotlin/realm-database/schemas/supported-types.txt
- source/sdk/kotlin/sync/manage-sync-session.txt
- source/sdk/kotlin/sync/write-to-synced-realm.txt
- source/sdk/node/model-data/modify-an-object-schema.txt
- source/sdk/react-native/bootstrap-with-expo.txt
- source/sdk/react-native/sync-data/flexible-sync.txt
- source/sdk/swift/sync/flexible-sync.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-34871
- [CPP/React to Changes](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-34871/sdk/cpp/react-to-changes/#register-a-collection-change-listener)
- [Flutter/Define a Realm Object Schema](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-34871/sdk/flutter/realm-database/model-data/define-realm-object-schema/#generate-the-realmobject)
- [Kotlin/Read](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-34871/sdk/kotlin/realm-database/crud/read/)
- [Kotlin/Manage Sync Sessions](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-34871/sdk/kotlin/sync/manage-sync-session/#sync-sessions)
- [Kotlin/Write to a Synced Realm](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-34871/sdk/kotlin/sync/write-to-synced-realm …
> (DOCSP-34871): Fix broken links

- source/includes/note-electron-packaging.rst
- source/sdk/node/integrations/electron-cra.txt
- source/sdk/node/integrations/electron.txt
- No Jira ticket but mentioned in https://github.com/realm/realm-js/issues/5153#issuecomment-1621820049
> Add a note about removing RN binaries from Electron builds

- source/sdk/react-native/install.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-33872
- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/): simple Proguard configuration for React Native on Android
- genre
> DOCSP-33872: Proguard configuration for RN Android

- source/includes/important-cant-persist-geospatial.rst
- source/sdk/dotnet/model-data/data-types/geospatials.txt
- source/sdk/dotnet/sync/flexible-sync.txt
- source/sdk/kotlin/realm-database/schemas/geospatials.txt
- source/sdk/kotlin/sync/subscribe.txt
- source/sdk/node/model-data/data-types/geospatial.txt
- source/sdk/node/sync/flexible-sync.txt
- source/sdk/react-native/model-data/data-types/geospatial.txt
- source/sdk/react-native/sync-data/flexible-sync.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-33572
- .NET
- [Geospatial Data Types - .NET SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-33572-geo-sync/sdk/dotnet/model-data/data-types/geospatials/#geospatial-data-types---.net-sdk)
- [Manage Flexible Sync Subscriptions- .NET SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-33572-geo-sync/sdk/dotnet/sync/flexible-sync/#manage-your-subscriptions)
- Kotlin
- [Geospatial Data - Kotlin SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-33572-geo-sync/sdk/kotlin/realm-database/schemas/geospatials/#geospatial-data---kotlin-sdk)
- [Manage Sync Subscriptions - Kotlin SDK ](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-33572-geo-sync/sdk/kotlin/sync/subscribe/#std-label-kotl …
> DOCSP-33752: Atlas Device Sync support for geospatial queries

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-34893
> DOCSP-34893 Add docs release notes for w/e December 15

- examples/dart/test/geospatial_data_test.dart
- examples/dart/test/geospatial_data_test.g.dart
- source/examples/generated/flutter/geospatial_data_test.snippet.define-geopoint-class.dart
- source/examples/generated/flutter/geospatial_data_test.snippet.geobox-query.dart
- source/examples/generated/flutter/geospatial_data_test.snippet.geobox.dart
- source/examples/generated/flutter/geospatial_data_test.snippet.geocircle-query.dart
- source/examples/generated/flutter/geospatial_data_test.snippet.geocircle.dart
- source/examples/generated/flutter/geospatial_data_test.snippet.use-geopoint-class.dart
- source/examples/generated/flutter/geospatial_data_test.snippet.write-geospatial-object.dart
- source/sdk/flutter/realm-database/model-data.txt
- source/sdk/flutter/realm-database/model-data/geospatial.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-34471
- [Geospatial](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-34471/sdk/flutter/realm-database/model-data/geospatial/): New page with info and tested, Bluehawked code examples for persisting and querying geospatial data.
- genre
- Realm Database/Model Data/Geospatial Data: New page with info and tested, Bluehawked code examples for persisting and querying geospatial data.
> (DOCSP-34471): Flutter SDK: Add geospatial docs

- source/example-projects.txt
- source/index.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-35137
- [Example Projects Page](https://preview-mongodblindseymoore.gatsbyjs.io/realm/DOCSP-35137/example-projects/): Update page title and description to reflect new Atlas Device SDK naming.
- genre
Other
- Example Projects Page: Update page title and description to reflect new Atlas Device SDK naming.
> DOCSP-35137 Update Example Projects title naming

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-35102
> (DOCSP-35102): Add docs release notes for w/e December 21

- examples/cpp/close-realm/CMakeLists.txt
- examples/cpp/close-realm/close-realm.cpp
- source/examples/generated/cpp/close-realm.snippet.close-realm-and-related-methods.cpp
- source/examples/generated/cpp/close-realm.snippet.close-realm.cpp
- source/sdk/cpp/quick-start.txt
- source/sdk/cpp/realm-files/configure-and-open-a-realm.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-35188
- [Configure & Open a Realm](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-35188/sdk/cpp/realm-files/configure-and-open-a-realm/#close-a-realm): New "Close a Realm" section with code example
- [Quick Start](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-35188/sdk/cpp/quick-start/#close-a-realm): New "Close a Realm" section with code example
- genre
- **C++ SDK**
- Quick Start: New "Close a Realm" section with Bluehawked, tested code example.
- Realm Files/Configure & Open a Realm: New "Close a Realm" section with Bluehawked, tested code example.
> (DOCSP-35188): C++: Close a realm

- source/sdk/cpp/app-services/connect-to-app.txt
- source/sdk/cpp/crud/create.txt
- source/sdk/cpp/crud/delete.txt
- source/sdk/cpp/crud/read.txt
- source/sdk/cpp/crud/threading.txt
- source/sdk/cpp/crud/update.txt
- source/sdk/cpp/model-data/supported-types.txt
- source/sdk/cpp/react-to-changes.txt
- source/sdk/cpp/sync/write-to-synced-realm.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-35019
- [C++ Staged Docs (Throughout)](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-35019/sdk/cpp/): Updated broken API reference links
> (DOCSP-35019): C++: Update API reference links for GA

- .github/workflows/c++.yml
- examples/cpp/sync/CMakeLists.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-35298
> (DOCSP-35298): Troubleshoot C++ Sync tests in CI

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-35231
> (DOCSP-35231): Add docs release notes for w/e January 5

- examples/ios/Examples/RealmApp.swift
- examples/ios/RealmExamples.xcodeproj/project.pbxproj
Jira ticket: https://jira.mongodb.org/browse/DOCSP-35393
- Swift SDK
- Internal: Update test suite versions.
> (DOCSP-35393): Swift: Fix failing unit tests in CI

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-35339
> (DOCSP-35339): Add docs release notes for w/e January 12

- source/sdk/flutter/realm-database/react-to-changes.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-35260
- [React to Changes - Flutter SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-35260-flutter-map-change/sdk/flutter/realm-database/react-to-changes/#register-collection-change-listeners): Update page to document support for RealmMap change listeners
- genre
- Realm/Realm Database/React to Changes: Add information on registering a change listener on a RealmMap.
-->
> DOCS-35260: Document MapChangeSet for Flutter 

- config/redirects
Jira ticket: https://jira.mongodb.org/browse/DOCSP-35890
> (DOCSP-35890): Updates to correct missing redirects

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-35771
> DOCSP-35771 Add docs release notes for w/e January 26

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-35996
> (DOCSP-35996): Add docs release notes for w/e Feb 2

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-36317
> DOCSP-36317 Add docs release notes for w/e February 9

- source/sdk/react-native/bootstrap-with-expo.txt
- [Bootstrap with Expo](https://preview-mongodbkrollinsmdb.gatsbyjs.io/realm/expo-update/sdk/react-native/bootstrap-with-expo/): Updated shell commands for creating and running the Expo app.
- genre
- **React Native SDK**
- Bootstrap with Expo: Update shell commands and clarify how to get an Expo app working.
> Update React Native Expo shell commands

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-36725
> (DOCSP-36725): Add docs release notes for w/e Feb 16

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-37028
> DOCSP-37028 Add docs release notes for w/e Feb 23

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-37205
> (DOCSP-37205): Add docs release notes for w/e March 1

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-37406
> DOCSP-37406 Add docs release notes for w/e March 8

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-37644
> (DOCSP-37644): Add docs release notes for w/e March 15

- examples/kotlin/settings.gradle.kts
- examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AppClientTest.kt
- source/examples/generated/kotlin/AppClientTest.snippet.enable-platform-networking.kt
- source/examples/generated/kotlin/AppClientTest.snippet.encrypted-app-client.kt
- source/sdk/kotlin/app-services/connect-to-app-services-backend.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-32239
- [Connect to Atlas App Services - Kotlin SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-32239-platform-networking/sdk/kotlin/app-services/connect-to-app-services-backend/#enable-platform-networking): Add new Enable Platform Networking section describing the new feature 
- genre
- **Kotlin** SDK
- Realm/Connect to Atlas/Connect to App Services: Add new Enable Platform Networking section detailing the new feature with tested, Bluehawked code examples.
> DOCSP-32239: Platform Networking for Kotlin

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-38056
> DOCSP-38056: Add docs release notes for w/e March 29

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-38157
> DOCSP-38157 Add docs release notes for w/e April 5

- examples/web/package.json
- examples/web/yarn.lock
Updating Web example test suite dependencies to address security vulnerabilities. This PR updates packages to the latest available versions to resolve the vulnerabilities detailed in these Snyk PRs:
- https://github.com/mongodb/docs-realm/pull/3226
- https://github.com/mongodb/docs-realm/pull/3227
- https://github.com/mongodb/docs-realm/pull/3228
Confirmed all tests pass locally.
- **Internal**
- Web SDK test suite: update dependencies to resolve security vulnerabilities.
> Upgrade package versions based on Snyk PRs

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-38684
> (DOCSP-38684): Add docs release notes for w/e April 19

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-38871
> DOCSP-38871 Add docs release notes for w/e April 26

- source/sdk/swift/install.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-37946
- [Install](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-37946/sdk/swift/install/): Drop Xcode 14 support. Refactor minimum OS and Xcode requirements to remove duplicate information.
- genre
- Install: Drop Xcode 14 support. Refactor minimum OS and Xcode requirements to remove duplicate information.
> (DOCSP-37946): Swift: Drop support for Xcode 14

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-39069
> DOCSP-39069 Add docs release notes for w/e May 3

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-39238
> (DOCSP-39238): Add docs release notes for w/e May 10

- examples/web/package.json
- examples/web/yarn.lock
Closes #3242
Closes #3241 
Also closes a handful of Dependabot security alerts.
Tested locally and everything passes.
> Update web dependencies

- examples/web/package.json
- examples/web/yarn.lock
Update the apollo/client Web SDK dependency per the latest Snyk PR.
Closes #3258
> Close new Snyk PR

- .github/workflows/readability.yml
Resolves a Dependabot security vulnerability.
> Update GitHub action version in the Readability workflow

- .github/workflows/check-links.yml
- .github/workflows/check-redirects.yml
- source/sdk/flutter/users/custom-user-data.txt
- source/sdk/kotlin/sync/partition-based-sync.txt
> change redirect title and update checker to run on pull_request

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-39461
> (DOCSP-39461): Add docs release notes for w/e May 17

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-39647
> DOCSP-39647 Add docs release notes for w/e May 24

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-39975
> DOCSP-39975: Add docs release notes for w/e May 31

- source/sdk/kotlin/realm-database/crud/read.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-40104
- genre
- programming_language
- **Kotlin SDK**
- Realm Database > CRUD > read: fix typo
[REVIEWING.md](https://github.com/mongodb/docs-app-services/blob/master/REVIEWING.md)
> DOCSP-40104: Fixed typo in read.txt 

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-40112
> DOCSP-40112 Add docs release notes for w/e June 7

- source/sdk/react-native/app-services.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-40323
*Staged Page*
- [Atlas Device SDKs](https://preview-mongodbosharafmdb.gatsbyjs.io/realm/DOCSP-40232-formatting-typo/)
Before requesting a review for your PR, please check these items:
- genre
> DOCSP-40232 formatting typo

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-40330
> DOCSP-40330 Add docs release notes for w/e June 14

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-40552
> (DOCSP-40552): Add docs release notes for w/e June 21

- source/example-projects.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-40539
*Staged Page*
- [Example Projects](https://preview-mongodblindseymoore.gatsbyjs.io/realm/DOCSP-40539/example-projects/)
Before requesting a review for your PR, please check these items:
- genre
> DOCSP-40539 Add Airbnb project to Example Projects

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-40768
> DOCSP-40768 Docs release ntoes for w/e June 28

- examples/dotnet/Examples/AuthenticationExamples.cs
- examples/dotnet/Examples/ProgressNotifications.cs
- source/examples/generated/dotnet/ProgressNotifications.snippet.upload-download-progress-notification.cs
- source/sdk/dotnet/sync/sync-progress.txt
Jira ticket: [DOCSP-39224](https://jira.mongodb.org/browse/DOCSP-39224)
*Staged Page*
- [Check Upload and Download Progress](https://deploy-preview-3317--device-sdk.netlify.app/sdk/dotnet/sync/sync-progress/#monitor-sync-progress)
> Re-add unit test, update text about the snippet, and fix older tests.

- examples/web/package.json
- examples/web/yarn.lock
Resolve Snyk dependency updates:
- Closes #3324 
- Closes #3325 
- Closes #3327
> Snyk dependency updates 07 19 24

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-41465
> DOCSP 41465: docs realm release notes w/e 07/19

- source/sdk/node/model-data/data-types/counters.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-41659
- [Counters - Node.js](https://preview-mongodbosharafmdb.gatsbyjs.io/realm/DOCSP-41659-nodejs-counters-typo/sdk/node/model-data/data-types/counters/): fixed a small typo
- [N/A] Did you tag pages appropriately?
- genre
- programming_language
- [N/A] Create a Jira ticket for related docs-realm work, if any
- **Node.js SDK**
- Model Data/Data Types/Counters: Fix typos on the Node.js SDK Counters page.
[REVIEWING.md](https://github.com/mongodb/docs-app-services/blob/master/REVIEWING.md)
> DOCSP-41659: small typo fix

- docs-release-notes.md
Jira ticket: https://jira.mongodb.org/browse/DOCSP-41669
> DOCSP-41669 release notes week ending 7/26

- .github/workflows/node.js-legacy.yml
- .github/workflows/node.js.yml
- .github/workflows/react-native-legacy.yml
- .github/workflows/react-native.yml
Re-add path to v12 tests, update RN tests to use same logic; clean up legacy node tests; use checkout 4 to remove warning
Jira ticket: https://jira.mongodb.org/browse/DOCSP-41888
> Node and RN test updates

- source/sdk/react-native/crud/create.txt
- source/sdk/react-native/model-data/define-a-realm-object-model.txt
Fix typo per reported feedback
> Fix typo in RN pages

- README.rst
Jira ticket: https://jira.mongodb.org/browse/DOCSP-NNNNN
No pages to preview
*Page Source*
Add links to every SDK's pages where you got the SDK-specific information:
- [PAGE_NAME](https://www.mongodb.com/docs/atlas/device-sdks/LIVE-DOCS-LINK)
Before requesting a review for your PR, please check these items:
- genre
As a reviewer, please check these items:
> Update warning in README

- examples/dart/test/app_services_test.dart
- source/examples/generated/flutter/app_services_test.snippet.change-base-url.dart
- source/index.txt
- source/sdk/dotnet/app-services/connect-to-app-services-backend.txt
- source/sdk/flutter/app-services/connect-to-app.txt
- source/sdk/kotlin/app-services/connect-to-app-services-backend.txt
- source/sdk/kotlin/realm-database/crud/read.txt
- source/sdk/kotlin/realm-database/open-and-close-a-realm.txt
- source/sdk/node/app-services/connect-to-app-services-backend.txt
- source/sdk/node/model-data/data-types/counters.txt
- source/sdk/react-native/app-services/connect-to-app-services-app.txt
- source/sdk/swift/app-services/connect-to-app-services-backend.txt
- source/sdk/swift/realm-files.txt
- source/studio/view-atlas-data-sync.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-43675
<li><a href=https://deploy-preview-3382--device-sdk.netlify.app/index>index</a></li><li><a href=https://deploy-preview-3382--device-sdk.netlify.app/sdk/dotnet/app-services/connect-to-app-services-backend>sdk/dotnet/app-services/connect-to-app-services-backend</a></li><li><a href=https://deploy-preview-3382--device-sdk.netlify.app/sdk/flutter/app-services/connect-to-app>sdk/flutter/app-services/connect-to-app</a></li><li><a href=https://deploy-preview-3382--device-sdk.netlify.app/sdk/kotlin/app-services/connect-to-app-services-backend>sdk/kotlin/app-services/connect-to-app-services-backend</a></li><li><a href=https://deploy-preview-3382--device-sdk.netlify.app/sdk/kotlin/realm-database/crud/read>sdk/kotlin/realm-database/crud/read</a> …
> remove mentions of Edge Server

- source/deprecation.txt
Add more information to the deprecations page about App Services that are affected by SDK deprecation since they rely on the SDKs.
<li><a href=https://deploy-preview-3383--device-sdk.netlify.app/deprecation>deprecation</a></li>
> Add info about affected app services

- config/redirects
Jira ticket: https://jira.mongodb.org/browse/DOCSP-45013
> (DOCSP-45013) Attempt #2

- config/redirects
Jira ticket: https://jira.mongodb.org/browse/DOCSP-45013
> (DOCSP-45013) Redirect fix attempt 3

- config/redirects
Jira ticket: https://jira.mongodb.org/browse/DOCSP-48490
Related to PRs #3389 and #3391 - updating syntax to try `deviceSDKsPrefix` on the left and `deviceSDKsBase` on the right.
> (DOCSP-48490): More 404 finagling

- .github/workflows/netflify-preview-links.yml
- .github/workflows/readability.yml
Jira ticket: https://jira.mongodb.org/browse/DOCSP-48584
> pin to commit hash
