source/data-model/realms.txt
source/index.txt

- [(DOCSP-7048): Data Model - Realms](https://jira.mongodb.org/browse/DOCSP-7048)
- [Data Model: Realms](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nick/data-model/data-model/realms.html)

(DOCSP-7048): Data Model - Realms

---

source/crud/collections.txt
source/index.txt

https://jira.mongodb.org/browse/DOCSP-7054
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/collections/crud/collections.html

(DOCSP-7054): Add Collections page

---

source/get-started/what-is-realm.txt
source/index.txt

- First pass at the What is Realm? page
- Merged intro into one page, no point being wordy
- "Realm Cloud" nomenclature not official, still TBD
- End of page links to be updated later
- Probably needs images or visual help
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker/realm-intro/get-started/what-is-realm
https://jira.mongodb.org/browse/DOCSP-7031

(DOCSP-7031): What is Realm? page

---

source/get-started/install-android.txt
source/get-started/install-dotnet.txt

Per Brian's comments:
https://docs.google.com/document/d/18zollLwNV44w8BUSEKmuV1amxnIK4U0BzuARTELbA1A/edit
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/master/get-started/install-android.html

Incorporate feedback

---

conf.py
source/authentication/anonymous.txt
source/authentication/providers.txt
source/index.txt

[JIRA](https://jira.mongodb.org/browse/DOCSP-8760)
[staging](https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-8760/authentication/anonymous.html)

(DOCSP-8760): Port auth provider: Anonymous Auth

---

source/authentication.txt
source/index.txt

- [(DOCSP-8758): Port Overview: Users & Authentication](https://jira.mongodb.org/browse/DOCSP-8758)
- [Users & Authentication](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker/users-authentication/authentication)

(DOCSP-8758): Overview: Users & Authentication

---

source/authentication/email-password.txt
source/index.txt

[JIRA](https://jira.mongodb.org/browse/DOCSP-8761)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-8761-4-realsies/authentication/email-password.html)

(DOCSP-8761): Port auth provider: Email/Password

---

source/authentication/google.txt
source/includes/steps-auth-google-project-setup.yaml
source/index.txt

- [(DOCSP-8765): Port Auth Provider: Google](https://jira.mongodb.org/browse/DOCSP-8765)
- [Google Authentication](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker/auth-google/authentication/google)

(DOCSP-8765): Port Auth Provider: Google

---

source/authentication/api-key.txt
source/index.txt

[JIRA](https://jira.mongodb.org/browse/DOCSP-8762)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-8762/authentication/api-key.html)

(DOCSP-8762): Port auth provider: API Key

---

source/authentication/anonymous.txt
source/authentication/email-password.txt
source/authentication/providers.txt

Staging link: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/realm-cli-and-summaries/authentication/providers.html

Summaries, link fixes, and recaps

---

source/authentication.txt

Port of the updated example included in https://github.com/10gen/baas-docs/pull/445

(DOCSP-8478): Clarify User Context in System Functions (Port)

---

source/hosting/use-a-custom-domain-name.txt
source/includes/steps-use-a-custom-domain-name-import-export.yaml
source/includes/steps-use-a-custom-domain-name-realm-ui.yaml
source/index.txt

- [(DOCSP-8930): Port: Use a Custom Domain Name](https://jira.mongodb.org/browse/DOCSP-8930)
- [Use a Custom Domain Name](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker/hosting-custom-domain/hosting/use-a-custom-domain-name)

(DOCSP-8930): Port: Use a Custom Domain Name

---

source/hosting/configure-file-metadata.txt
source/hosting/file-metadata-attributes.txt
source/hosting/includes/metadata-config-json.rst
source/hosting/includes/note-infer-content-type.rst
source/includes/steps-configure-file-metadata-import-export.yaml
source/includes/steps-configure-file-metadata-realm-ui.yaml
source/index.txt

- [(DOCSP-8927): Port: Configure File Metadata](https://jira.mongodb.org/browse/DOCSP-8927)
- [(DOCSP-8932): Port: File Metadata Attributes](https://jira.mongodb.org/browse/DOCSP-8932)
- [Configure File Metadata](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker/hosting-metadata/hosting/configure-file-metadata)
- [File Metadata Attributes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker/hosting-metadata/hosting/file-metadata-attributes)

(DOCSP-8927,8932): Port: Hosting Metadata

---

source/application-deployment/deploy-cli.txt
source/includes/steps-deploy-cli.yaml
source/index.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-8919
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-8919/application-deployment/deploy-cli.html

(DOCSP-8919): Port CLI Deploy

---

source/application-deployment/deploy-ui.txt
source/includes/steps-deploy-draft-ui-changes.yaml
source/index.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-8917
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-8917/application-deployment/deploy-ui.html

(DOCSP-8917): Port UI Deploy

---

source/index.txt
source/logs.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-8937
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-8937/logs.html

(DOCSP-8937): Port Application Logs: Overview

---

source/hosting.txt
source/hosting/flush-the-cdn-cache.txt
source/index.txt

JIRA:
-----
* https://jira.mongodb.org/browse/DOCSP-8924
Stage:
------
* https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-8924-Port-Hosting-Overview/hosting.html#hosting
Original Stitch Page:
--------------------
* https://docs.mongodb.com/stitch/hosting/#hosting

(DOCSP-8924): port hosting overview

---

source/logs/authentication.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-8938
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-8938/logs/authentication.html

(DOCSP-8938: Port Authentication Logs

---

source/logs.txt
source/logs/changestream.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-8939
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-8939/logs/changestream.html

(DOCSP-8939): Port Change Stream Logs

---

source/logs/function.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-8940
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-8940/logs/function.html

(DOCSP-8940): Port Function Logs

---

source/logs/trigger.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-8941
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-8941/logs/trigger.html

(DOCSP-8941): Port Trigger Logs

---

source/logs/service.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-8942
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-8942/logs/service.html

(DOCSP-8942): Port Service Logs

---

source/logs.txt
source/logs/api.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-8944
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-8944/logs/api.html

(DOCSP-8944): Port Access Logs With Admin API

---

conf.py
source/functions.txt
source/index.txt

- [(DOCSP-8945): Functions Overview](https://jira.mongodb.org/browse/DOCSP-8945)
- [Functions Overview](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker/functions/functions)

(DOCSP-8945): Functions Overview

---

source/admin/users-and-groups.txt
source/index.txt

JIRA:
-----
* https://jira.mongodb.org/browse/DOCSP-8934
Old/Adjacent Stitch Doc:
-------------------------
* https://docs.mongodb.com/stitch/admin/users-and-groups/
Stage:
-------
* https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-8934-Port-Administration-MongoDB-Cloud-Users/admin/users-and-groups.html

(DOCSP-8934): Port - Administation MongoDB Cloud Users

---

source/functions/call-a-function.txt
source/index.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-8948
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-8948/functions/call-a-function.html

(DOCSP-8948): Port Call a Function

---

conf.py
source/functions/access-function-context.txt
source/index.txt
source/services/examples/webhook-http-method-handler.rst

JIRA: https://jira.mongodb.org/browse/DOCSP-8950
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-8950/functions/access-function-context.html

(DOCSP-8950): Port Access Function Context

---

source/functions/import-external-dependencies.txt
source/index.txt

Jira:
----
* https://jira.mongodb.org/browse/DOCSP-8949
Original/Adjacent Stitch Doc:
-----------------------------
* https://docs.mongodb.com/stitch/functions/import-external-dependencies/
Stage:
------
* https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-8949-port-import-external-dependencies/functions/import-external-dependencies.html

(DOCSP-8949): Port - Import External Dependencies

---

source/includes/extracts-service-actions.yaml

figures that I would miss one single yaml file
https://docs-mongodborg-staging.corp.mongodb.com/realm/docsworker-xlarge/fixActionsNextGen/

add missing admonition

---

conf.py
source/graphql.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-9181
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-9181/graphql.html

(DOCSP-9181): Port GraphQL Overview

---

source/graphql/authenticate.txt
source/index.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-9183
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-9183/graphql/authenticate.html

(DOCSP-9183): Port GraphQL Auth

---

source/graphql.txt

Porting over https://github.com/10gen/baas-docs/pull/453 from baas-docs to docs-realm

(DOCSP-9267): Change jmp parameter to tck

---

source/triggers.txt
source/triggers/cron-expressions.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-9193
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-9193/triggers/cron-expressions.html

(DOCSP-9193): Port CRON Expressions

---

source/triggers.txt
source/triggers/trigger-snippets.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-9192
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-9192/triggers/trigger-snippets.html

(DOCSP-9192): Port Trigger Snippets

---

source/mongodb.txt
source/mongodb/crud-and-aggregation-apis.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-9165
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-9165/mongodb/crud-and-aggregation-apis.html

(DOCSP-9165): Port MongoDB CRUD & Aggregation APIs

---

source/mongodb.txt
source/mongodb/service-limitations.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-9164
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-9164/mongodb/service-limitations.html

(DOCSP-9164): Port MongoDB Service Limitations

---

source/mongodb.txt
source/mongodb/connection-strings.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-9163
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-9163/mongodb/connection-strings.html

(DOCSP-9163): Port MongoDB Connection Strings

---

source/mongodb.txt
source/mongodb/query-filters.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-9161
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-9161/mongodb/query-filters.html

(DOCSP-9161): Port Query Filters

---

source/mongodb.txt
source/mongodb/document-schemas.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-9162
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-9162/mongodb/document-schemas.html

(DOCSP-9162): Port Document Schemas

---

source/graphql/expose-data.txt
source/index.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-9182
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-9182/graphql/expose-data.html

(DOCSP-9182): Port GraphQL Expose Data in a Collection

---

source/mongodb.txt
source/mongodb/connect-over-the-wire-protocol.txt

JIRA:
-----
* https://jira.mongodb.org/browse/DOCSP-9159
Original/Adjacent Stitch Doc:
-----------------------------
* https://docs.mongodb.com/stitch/mongodb/connect-over-the-wire-protocol/
Stage:
-------
* https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-9159-Port-Connect-Over-Wire-Protocol/mongodb/connect-over-the-wire-protocol.html
Changes outside of general wording & passive voice fixes/typos/ "stitch" -> "realm" word:
-----------------------------------------------------------------------------------------
1. Removed Perl code snippets, since the MongoDB Perl Driver will be end of life'd on August 13th, 2020 which is just a little over 1 month after MongoDB World 
(https://www.mongodb.com/blog/post/the-mongodb-perl-driver-is-being-deprecated) 
2. Changed …

(DOCSP-9159): Port - Connect Over the Wire Protocol

---

source/deploy/create-with-cli.txt
source/includes/steps-cli-create.yaml
source/index.txt

Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/createWithCLI/deploy/create-with-cli.html

Added Realm CLI App Creation page

---

conf.py
source/admin/api/v3.txt
source/includes/steps-admin-api-deploy-a-draft.yaml
source/index.txt
source/openapi-admin-v3.yaml

Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/AdminAPI/admin/api/v3.html

Port Admin API Reference

---

conf.py
source/graphql/execute.txt

_**Mirrors https://github.com/10gen/baas-docs/pull/458**_
- [(DOCSP-8776): Direct link from 'run a query/mutation' to resolver documentation](https://jira.mongodb.org/browse/DOCSP-8776)
- [Run a Query](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nick/graphql/graphql/execute.html#run-a-query)
- [Run a Mutation](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nick/graphql/graphql/execute.html#run-a-mutation)

(DOCSP-8776): Direct link from 'run a query/mutation' to resolver documentation

---

source/index.txt
source/logs/api.txt
source/procedures/init-realmclient.txt

Add missing files to the TOC to quash warnings.
This is going to be rearranged anyway.
Staged:
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/link-fixes/index.html

Update index TOC

---

source/index.txt
source/services.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-9338
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-9338/services.html

(DOCSP-9338): Port Services Overview

---

conf.py
source/includes/run-webhook-as-options.rst
source/index.txt
source/services/twilio.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-9343
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-9343/services/twilio.html

(DOCSP-9343): Port Twilio Service Overview

---

conf.py
source/index.txt
source/services/push-notifications.txt

JIRA:
-----
* https://jira.mongodb.org/browse/DOCSP-9356
Original/Adjacent Stitch Doc:
-----------------------------
* https://docs.mongodb.com/stitch/services/push-notifications/
Stage:
-------
* https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-9356-Port-Push-Notifications/services/push-notifications.html

(DOCSP-9356) Port Push Notifications Page

---

source/index.txt
source/services/github.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-9354
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-9354/services/github.html

(DOCSP-9354): Port GitHub Service Overview

---

source/index.txt
source/services/http.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-9345
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-9345/services/http.html

(DOCSP-9345): Port HTTP Service Overview

---

source/index.txt
source/services/snippets/s3.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-9353
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-9353/services/snippets/s3.html

(DOCSP-9353): Port S3 Service Snippets

---

conf.py
source/index.txt
source/services/snippets/github.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-9355
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-9355/services/snippets/github.html

(DOCSP-9355): Port GitHub Service Snippets

---

source/index.txt
source/services/twilio-actions/send.txt
source/services/twilio.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-9344
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-9344/services/twilio-actions/send.html

(DOCSP-9344): Port twilio.send()

---

source/index.txt
source/services/call-a-service-action.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-9341
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-9341/services/call-a-service-action.html

(DOCSP-9341): Port Call a Service Action

---

source/includes/extracts-http-action.yaml
source/index.txt
source/services/http-actions/http.delete.txt
source/services/http-actions/http.get.txt
source/services/http-actions/http.head.txt
source/services/http-actions/http.patch.txt
source/services/http-actions/http.post.txt
source/services/http-actions/http.put.txt

Http.post()
----------
Jira: https://jira.mongodb.org/browse/DOCSP-9347
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/Port-Http-Methods/services/http-actions/http.post.html
Http.put()
----------
Jira: https://jira.mongodb.org/browse/DOCSP-9348
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/Port-Http-Methods/services/http-actions/http.put.html
Http.patch()
------------
Jira: https://jira.mongodb.org/browse/DOCSP-9349
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/Port-Http-Methods/services/http-actions/http.patch.html
Http.delete()
-------------
Jira: https://jira.mongodb.org/browse/DOCSP-9350
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/Port-Http-Methods/services/http- …

Port Http Methods

---

source/functions.txt

**_Port of https://github.com/10gen/baas-docs/pull/460_**
- [(DOCSP-8968): Document Supported Node Built-in Modules](https://jira.mongodb.org/browse/DOCSP-8968)
- [Function Constraints](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nick/node/functions.html#constraints)

(DOCSP-8968): Document Supported Node Built-in Modules

---

source/services/aws.txt

**_Port of https://github.com/10gen/baas-docs/pull/461_**
- [(DOCSP-8675): Add documentation for S3.PresignURL](https://jira.mongodb.org/browse/DOCSP-8675)
- [S3 PresignURL](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nick/aws/services/aws.html#s3-presignurl)

(DOCSP-8675): Add documentation for S3.PresignURL

---

conf.py
source/admin/api/v3.txt
source/by-example/read-and-write.txt
source/crud/collections.txt
source/crud/notifications.txt
source/crud/query-engine.txt
source/crud/reads.txt
source/crud/writes.txt
source/data-model/auxiliary-files.txt
source/data-model/migrations.txt
source/data-model/objects.txt
source/data-model/realms.txt
source/data-model/relationships.txt
source/data-model/threading.txt
source/get-started/glossary.txt
source/get-started/what-is-realm.txt
source/index.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-7038
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-7038/get-started/glossary.html

(DOCSP-7083): Glossary for Realm

---

source/mongodb/document-schemas.txt

JIRA:
-----
https://jira.mongodb.org/browse/DOCSP-9478
Original Stitch Doc:
-------------------
https://docs.mongodb.com/stitch/mongodb/document-schemas/
Stage:
------
https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-9478-Schema-Types/mongodb/document-schemas.html

(DOCSP-9478): Add mention to Realm Data Models in Document Schema Types Doc

---

source/get-started/glossary.txt
source/get-started/introduction-backend.txt
source/index.txt

https://jira.mongodb.org/browse/DOCSP-9481
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/intro-backend/get-started/introduction-backend.html

(DOCSP-9461): Introduction for backend developers

---

source/services/expression-variables.txt

Clarifications, typos
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/touchups/services/expression-variables.html

Fix up expression variables page

---

source/sync/sync-overview.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-9475
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-9475/sync/sync-overview.html

(DOCSP-9475): Update Sync Overview page for new product

---

source/functions.txt
source/functions/import-external-dependencies.txt
source/functions/upload-external-dependencies.txt

_**Port of https://github.com/10gen/baas-docs/pull/466**_

(DOCSP-8292,9651): Built-in Module Support + Transpilation

---

source/get-started/glossary.txt
source/mongodb/document-schemas.txt
source/sync/partitioning.txt
source/sync/sync-overview.txt

JIRA:
-----
https://jira.mongodb.org/browse/DOCSP-9750
STAGE:
-------
https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-9750-Realm-Data-Model-Glossary-Terms/get-started/glossary.html

(DOCSP-9750): Add glossary terms related to realm object models

---

snooty.toml

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/update-title/

Add title to snooty.toml

---

source/sync/partitioning.txt

as discussed on the realm docs channel

clarification about permissioning per-user per-realm

---

source/graphql/types-and-resolvers.txt
source/mongodb-realm.txt

_**Port of https://github.com/10gen/baas-docs/pull/473**_
- [(DOCSP-9831): GraphQL Query & Mutation Operators](https://jira.mongodb.org/browse/DOCSP-9831)
- [GraphQL Types, Resolvers, and Operators](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/graphql/graphql/types-and-resolvers.html)

(DOCSP-9831): GraphQL Query & Mutation Operators

---

source/includes/steps-install-carthage.yaml
source/includes/steps-install-cocoapods.yaml
source/includes/steps-install-dynamic-framework.yaml

https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/pod-fix/get-started/install-ios.html
https://jira.mongodb.org/browse/DOCSP-10015

DOCSP-10015 Update iOS install instructions for iOS

---

source/services/twilio-actions/send.txt

[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-10138/services/twilio-actions/send#usage)

(DOCSP-10138) - adds note about twilio whatsapp api

---

source/get-started/introduction-web.txt
source/index.txt

- [(DOCSP-9483): Intro for Web Devs](https://jira.mongodb.org/browse/DOCSP-9483)
- [Introduction to MongoDB Realm for Web Developers](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/intro-web/get-started/introduction-web.html)

(DOCSP-9483): Intro for Web Devs

---

source/get-started/configure-your-data-model.txt
source/index.txt
source/ios.txt
source/ios/quick-start.txt
source/procedures/create-realm-app.txt

- Seems to be missing a relationship example.
- Rewrap is not working for some reason. Will do a pass later.
https://jira.mongodb.org/browse/DOCSP-10332
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/quick-start/ios/quick-start.html

Add iOS quick start page

---

source/authentication/linking.txt
source/includes/steps-install-cocoapods.yaml
source/includes/steps-tutorial-ios-swift.yaml
source/index.txt
source/ios/install.txt
source/tutorial/ios-swift.txt

- Backend setup needed.
- Screenshots needed.
- Text mostly good.
- Based on https://docs.mongodb.com/stitch/tutorials/guides/todo-guide-1/ and https://docs.realm.io/sync/getting-started-1/step-1-my-first-realm-app
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/ios-tutorial/tutorial/ios-swift.html
https://jira.mongodb.org/browse/DOCSP-10293

Add text for the iOS Tutorial

---

source/billing.txt
source/index.txt

- [(DOCSP-8935): Realm Billing](https://jira.mongodb.org/browse/DOCSP-8935)
- [Billing](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/billing/billing.html)

(DOCSP-8935): Realm Billing

---

source/graphql.txt
source/graphql/expose-data.txt
source/graphql/note-temporary-graphql-limitations.rst
source/graphql/types-and-resolvers.txt

**Port of: https://github.com/10gen/baas-docs/pull/484**

(DOCSP-10306, 10283, 9961): GraphQL Updates

---

source/includes/steps-tutorial-ios-swift.yaml
source/tutorial/ios-swift.txt

See https://github.com/mongodb-university/realm-tutorial/pull/6

Update the tutorial text to match code per feedback

---

source/ios.txt
source/ios/authenticate.txt
source/ios/quick-start.txt

https://jira.mongodb.org/browse/DOCSP-7074
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/client-auth/ios/authenticate.html

DOCSP-7074 Add iOS client guide for authenticating a user

---

source/includes/steps-tutorial-ios-swift.yaml

https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/alpha-6/tutorial/ios-swift.html

Update for alpha.6 code

---

source/includes/steps-tutorial-android-kotlin.yaml

Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/realmjavarefactor/tutorial/android-kotlin.html

fixing tutorial to match refactored java API

---

source/examples/Relationships/ToMany/ToMany.m
source/examples/Schemas/PersonSchema.m
source/examples/Schemas/PersonSchema.swift
source/examples/Threading/Freeze.m
source/examples/Threading/Freeze.swift
source/index.txt
source/ios.txt
source/ios/authenticate.txt
source/ios/call-a-function.txt
source/ios/collections.txt
source/ios/init-realmclient.txt
source/ios/manage-email-password-users.txt
source/ios/migrations.txt
source/ios/notifications.txt
source/ios/objects.txt
source/ios/query-engine.txt
source/ios/realms.txt
source/ios/relationships.txt
source/ios/threading.txt
source/ios/writes.txt
source/procedures/init-realmclient.txt

- Adding or updating code examples
- Write "Call a Function", "Initialize the Realm App Client" and "Manage Email/Password Users"
- Clean up writing in all client guide pages
Please check all pages in the iOS client guide:
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/ios-cleanup/ios.html
https://jira.mongodb.org/browse/DOCSP-10658

(DOCSP-10658): iOS Client Guide Code Examples & Cleanup

---

source/android/realms.txt
source/dotnet/realms.txt
source/ios/collections.txt
source/ios/objects.txt
source/ios/realms.txt
source/node/realms.txt
source/react-native/realms.txt

A few grammar fixes for iOS guides.

grammar fixes for iOS guides

---

source/android.txt
source/android/authenticate.txt

Staging: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/AndroidLoginAnon/android/authenticate.html
You'll have to tab over to kotlin to see the code samples, unfortunately.

authentication first pass: android

---

source/index.txt
source/web/quickstart.txt

- [(DOCSP-10517): Realm Web Quick Start](https://jira.mongodb.org/browse/DOCSP-10517)
- [Web Quick Start](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/web-quickstart/web/quickstart.html)

(DOCSP-10517): Realm Web Quick Start

---

source/authentication/email-password.txt
source/web/authenticate.txt
source/web/create-manage-api-keys.txt
source/web/manage-email-password-users.txt

- [(DOCSP-10518): [Web SDK] Authentication]()
- [Authenticate a User](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/auth/web/authenticate.html)
- [Manage Email/Password Users](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/auth/web/manage-email-password-users.html)
- [Create & Manage API Keys](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/auth/web/create-manage-api-keys.html)

(DOCSP-10518): [Web SDK] Authentication

---

source/node/install.txt

jira: https://jira.mongodb.org/browse/DOCSP-10722
stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-10722-Node-Version/node/install.html

(DOCSP-10722): Fix Node Version in Realm Docs

---

source/procedures/create-realm-app.txt

jira: https://jira.mongodb.org/browse/DOCSP-10723
stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-10723-Atlas-Links-Fix/get-started/introduction-mobile.html#mongodb-atlas

(DOCSP-10723): Atlas-Links-Fix

---

source/includes/steps-task-tracker-server-data-model.yaml
source/includes/steps-task-tracker-web-apollo.yaml
source/includes/steps-task-tracker-web-realmapp.yaml
source/includes/steps-tutorial-android-kotlin.yaml
source/includes/steps-tutorial-ios-swift.yaml
source/includes/steps-tutorial-react-native.yaml
source/includes/task-tracker-web-operations.graphql
source/tutorial/web-graphql.txt

- `realm-dev` -> `realm`
- `Task.description` -> `Task.name`
- Web: add `git checkout todo`

Dev -> Prod Beta, Version Tweaks

---

source/get-started/introduction-backend.txt
source/get-started/introduction-mobile.txt
source/get-started/introduction-web.txt

https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/intro-next-steps/get-started/introduction-web.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/intro-next-steps/get-started/introduction-backend.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/intro-next-steps/get-started/introduction-mobile.html

Update intro next steps

---

config/redirects

- Product links to "tutorials"

(DOCSP-10734): Add tutorials -> tutorial redirect

---

source/node.txt
source/node/authenticate.txt
source/node/call-a-function.txt
source/node/create-manage-api-keys.txt
source/node/manage-email-password-users.txt
source/react-native/authenticate.txt
source/react-native/create-manage-api-keys.txt
source/react-native/manage-email-password-users.txt
source/web.txt
source/web/authenticate.txt
source/web/call-a-function.txt
source/web/manage-email-password-users.txt

https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/unify/web/call-a-function.html

Unify JS Guides content + Web Functions page

---

source/node/call-a-function.txt
source/react-native/call-a-function-from-react-native.txt

JIRA:
-----
* https://jira.mongodb.org/browse/DOCSP-10729
Stage:
------
* Node Call a Function: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-10729-Remove-Unneeded-URL-AppConfig-JS/node/call-a-function.html
*  React Native Call a Function: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-10729-Remove-Unneeded-URL-AppConfig-JS/react-native/call-a-function-from-react-native.html

(DOCSP-10729): Remove URL from App Config in JS SDK

---

source/includes/steps-tutorial-react-native.yaml

See also: https://github.com/mongodb-university/realm-tutorial/pull/26

Update RN tutorial text to match beta.4

---

source/admin/deployment-models-and-regions.txt
source/admin/users-and-groups.txt
source/authentication/email-password.txt
source/deploy/create-with-cli.txt
source/deploy/deploy-automatically-with-github.txt
source/get-started/introduction-backend.txt
source/get-started/introduction-web.txt
source/includes/steps-cli-export.yaml
source/includes/steps-define-a-function-import-export.yaml
source/includes/steps-define-custom-user-data-import-export.yaml
source/includes/steps-define-roles-and-permissions-cli.yaml
source/includes/steps-define-sync-rules-cli.yaml
source/includes/steps-deploy-cli.yaml
source/includes/steps-filter-incoming-queries-import-export.yaml
source/includes/steps-specify-cluster-read-preference-realm-ui.yaml
source/logs.txt
source/logs/changestream.txt
source/logs/function.txt
source/logs/service.txt
source/mongodb.txt
source/mongodb/enforce-a-document-schema.txt
source/mongodb/link-a-cluster.txt
source/sync/configure-your-data-model.txt
source/sync/partitioning.txt
source/triggers.txt
source/triggers/database-triggers.txt
source/tutorial/backend.txt
source/tutorial/realm-app.txt

jira: https://jira.mongodb.org/browse/DOCSP-10728
stage: https://docs-mongodborg-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-10728-MongoDBAtlas-referral-links/index.html

(DOCSP-10728): added some referral links to atlas

---

source/android/authenticate.txt
source/includes/steps-tutorial-android-kotlin.yaml

Staging: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/beta2/tutorial/android-kotlin.html

tutorial updated to match new tutorial code

---

source/includes/steps-tutorial-ios-swift.yaml
source/ios/quick-start.txt

Jira: https://jira.mongodb.org/browse/DOCSP-10744
Stage: 
* IOS tutorial: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-10744-Change-URL-to-prod-IOS-Swift/tutorial/ios-swift.html
* IOS Quick Start: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-10744-Change-URL-to-prod-IOS-Swift/ios/quick-start.html

(DOCSP-10744): Update IOS Swift Tutorial + QuickStart to remove cloud-dev

---

source/graphql/connect.txt

Staged: [Connect from a Client Application](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/graphql/graphql/connect.html)

(DOCSP-10520): Update GraphQL Connect Guide & CodeSandbox

---

source/includes/steps-task-tracker-server-data-model.yaml

- _partition must be required
- title must be capitalized

Update text for backend setup to match tutorial

---

source/includes/steps-task-tracker-server-data-model.yaml

GraphQL tutorial code will have to be updated

Remove enum from tutorial backend setup

---

source/tutorial/react-native.txt

stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/Fix-Node-Version-RN-Tutorial/tutorial/react-native.html#prerequisites

fixed node version in RN tutorial

---

source/includes/steps-install-node.yaml
source/includes/steps-install-react-native-pre-v60.yaml
source/includes/steps-install-react-native-v60-plus.yaml
source/includes/steps-tutorial-react-native.yaml
source/node/call-a-function.txt
source/node/quick-start.txt
source/react-native/call-a-function-from-react-native.txt
source/react-native/quick-start.txt

- SDK team recommends 10000 timeout
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/update-text/tutorial/react-native.html

Update RN tutorial text for beta.6 and update recommended timeout

---

source/includes/steps-install-cocoapods.yaml
source/ios/install.txt

https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/ios-min-versions/ios/install.html

Update min versions for iOS

---

source/get-started/glossary.txt
source/procedures/create-realm-app.txt
source/sync/partitioning.txt
source/tutorial/backend.txt
source/tutorial/realm-app.txt

https://jira.mongodb.org/browse/DOCSP-9751
https://jira.mongodb.org/browse/DOCSP-10785
https://jira.mongodb.org/browse/DOCSP-10786
Realm app: https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/fixes/get-started/glossary.html
Create Realm app: https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/fixes/procedures/create-realm-app.html
Partitioning: https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/fixes/sync/partitioning.html
Backend: https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/fixes/tutorial/backend.html
Realm app: https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/fixes/tutorial/realm-app.html

(DOCSP-9751, DOCSP-10785, DOCSP-10786): Fixes

---

source/includes/steps-auto-schema-generation.yaml
source/includes/steps-development-mode-realm-schema.yaml
source/sync/configure-your-data-model.txt

https://jira.mongodb.org/browse/DOCSP-10790
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/id-required/sync/configure-your-data-model.html

(DOCSP-10790): Add note that _id is required for sync models

---

source/android/objects.txt
source/android/realms.txt
source/android/threading.txt
source/dotnet/objects.txt
source/dotnet/realms.txt
source/dotnet/threading.txt
source/index.txt
source/ios/realms.txt
source/node/objects.txt
source/node/realms.txt
source/react-native/objects.txt
source/react-native/realms.txt

https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/fixes2/index.html

(DOCSP-10795, DOCSP-10797, DOCSP-13699): Fixes

---

source/includes/steps-tutorial-react-native.yaml

JIRA:  https://jira.mongodb.org/browse/DOCSP-10777
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-10777-RN-fix-registerEmail/tutorial/react-native.html#update-the-app-ui

(DOCSP-10777): fix rn register users note

---

source/index.txt
source/sync.txt

Stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-10787/sync/overview.html
JIRA: https://jira.mongodb.org/browse/DOCSP-10787

(DOCSP-10787): Swap overview and getting started in Sync TOC

---

source/android/realms.txt
source/dotnet/realms.txt
source/ios/realms.txt
source/node/realms.txt
source/react-native/realms.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-10794
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-10794/android/realms.html#realms-are-partitions-of-atlas-data
https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-10794/ios/realms.html#realms-are-partitions-of-atlas-data
https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-10794/dotnet/realms.html#realms-are-partitions-of-atlas-data
https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-10794/node/realms.html#realms-are-partitions-of-atlas-data
https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-10794/react-native/realms.html#realms-are-partitions-of-atlas-data

(DOCSP-10794): Better client realms pages links to partitioning

---

source/openapi-admin-v3.yaml

- Also fixed some substitutions that don't seem to work in the OpenAPI parser
https://jira.mongodb.org/browse/DOCSP-10587
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/measurements/admin/api/v3.html#billing-apis

(DOCSP-10587): Add API docs for measurements endpoint

---

source/examples/Relationships/ImplicitInverse/ImplicitInverse.swift

https://jira.mongodb.org/browse/DOCSP-10824
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/implicit-inverse-example/ios/relationships.html#implicit-inverse-relationships

(DOCSP-10824): Fix implicit inverse code example

---

source/index.txt
source/mongodb/link-a-cluster.txt
source/reference/issues-and-workarounds.txt

https://jira.mongodb.org/browse/DOCSP-10754
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/issues-and-workarounds/reference/issues-and-workarounds.html

(DOCSP-10754): Add issues and workarounds page

---

source/android/authenticate.txt

JIRA: https://jira.mongodb.org/browse/DOCS-13715
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-13715/android/authenticate.html

(DOCSP-13715): Add newly supported auth provider examples

---

source/android/authenticate.txt
source/android/quick-start.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-10929
Staging: 
https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-10929/android/install.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-10929/android/quick-start.html

(DOCSP-10929): Java snippets for Android SDK

---

source/includes/steps-tutorial-ios-swift.yaml

- See https://github.com/mongodb-university/realm-tutorial/pull/44
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/sort-by-id/tutorial/ios-swift.html
https://jira.mongodb.org/browse/DOCSP-10719

(DOCSP-10719): Update Swift tutorial text to sort Tasks by _id

---

source/ios.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-10943
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-10943/ios.html

(DOCSP-10943): MongoDB Data Access available in iOS SDK

---

source/android.txt
source/android/manage-email-password-users.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-10841
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-10841/android/manage-email-password-users.html

(DOCSP-10841): register/confirm/password reset examples for android email/password

---

source/node.txt
source/node/remotely-access-mongodb.txt
source/react-native.txt
source/react-native/remotely-access-mongodb.txt

Jira:
----
* https://jira.mongodb.org/browse/DOCSP-11045
Stage:
-------
* Node: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-11045-RemoteMongoClient/node/remotely-access-mongodb.html
* React Native: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-11045-RemoteMongoClient/react-native/remotely-access-mongodb.html

(DOCSP-11045): RemoteMongoClient Doc for Node + RN

---

source/ios/create-manage-api-keys.txt

https://jira.mongodb.org/browse/DOCSP-10813
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/api-keys/ios/create-manage-api-keys.html

(DOCSP-10813): Add swift and obj-c snippets for API keys

---

source/includes/steps-crud-snippets-android.yaml

Staging: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/nathan-contino-mongo-patch-4/mongodb/find-documents.html#snippet-setup
(and all other crud snippet "Setup" sections)

Update imports and setup information for mongodb data access

---

source/android/init-realmclient.txt

Content could confuse some users who just need to follow the basic initialization example.
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/nathan-contino-mongo-patch-3/android/init-realmclient.html

Clarify the use case for advanced options

---

source/includes/note-filters-no-mongodb-expansions.rst
source/openapi-admin-v3.yaml

- [(DOCSP-10978): Add %function support in query and projection in filters](https://jira.mongodb.org/browse/DOCSP-10978)
- [(DOCSP-10953): Add limit option for fetching logs](https://jira.mongodb.org/browse/DOCSP-10953)
- [Filter Incoming Queries](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/updates/mongodb/filter-incoming-queries.html#specify-the-apply-when-expression)
- [Query Filters](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/updates/mongodb/query-filters.html#query-filter-configuration)
- [Admin API: Logs](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/updates/admin/api/v3.html#get-/groups/%7Bgroupid%7D/apps/%7Bappid%7D/logs)

Small feature updates

---

source/includes/steps-configure-custom-function-auth-import-export.yaml

https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/remove-todo/authentication/custom-function.html

Fix TODOs in Custom Function configuration guide

---

source/examples/MultiUser/AddUser/AddUser.kt

- new is not a valid kotlin keyword
- getError() is not valid kotlin -- use error instead (getters and setters are simplified in kotlin)
- extra semicolons
- assert is never run in android unless you are in a special DEBUG mode -- switched to a if/else instead

Fix AddUser kotlin example to use valid kotlin

---

source/android/work-with-multiple-users.txt

staging: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/nathan-contino-mongo-patch-5/android/work-with-multiple-users.html

hide missing multi user examples

---

source/authentication/email-password.txt
source/authentication/user-objects.txt
source/includes/define-custom-user-data-example.rst
source/includes/seealso-client-guides-manage-email-password-users.rst
source/users/create.txt

- Also add seealso links to find user management in the client guides
https://jira.mongodb.org/browse/DOCSP-11231
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/user-data/users/define-custom-user-data.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/user-data/authentication/email-password.html
https://jira.mongodb.org/browse/DOCSP-11254
https://jira.mongodb.org/browse/DOCSP-11255
https://jira.mongodb.org/browse/DOCSP-11256
https://jira.mongodb.org/browse/DOCSP-11258

(DOCSP-11231): Remove non-function SDK snippets on User pages

---

source/node/quick-start.txt
source/react-native/quick-start.txt

Jira:
----
https://jira.mongodb.org/browse/DOCSP-10793
Stage: 
------
* Node: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-10793-QuickStart-Output-Node-RN/node/quick-start.html
* RN: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-10793-QuickStart-Output-Node-RN/react-native/quick-start.html
Changes:
---------
* Added output of "Complete Example" for node quick start
* Changes to existing docs to adhere to new SDK changes:
* Updated `user.identity` to `user.id`
* Fixed `'"myPartition"'` to `"myPartition"` 
* Added mandatory `_id` field to realm.create objects
* Fixed filtered task (previously, the filter was on 'complete = true' but there was no complete field of the collection)
* Fixed `object id?` to `objectId` in TaskModel

(DOCSP-10793): Updated QuickStarts for Node & RN + Added Output for Node

---

source/ios/call-a-function.txt

- Tested on beta.2
https://jira.mongodb.org/browse/DOCSP-11202
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/ios-function-fix/ios/call-a-function.html

(DOCSP-11202): Fix iOS function example

---

source/android/quick-start.txt

Staging: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/nathan-contino-tag-youre-it/android/quick-start.html#define-your-object-model

Replace undefined TAG variable with string

---

source/android/quick-start.txt

jira:
---
* https://jira.mongodb.org/browse/DOCSP-11274
stage:
------
* https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-11274-Quickstart-Output-Android-SDK/android/quick-start.html#complete-example

(DOCSP-11274): Android Quickstart Output

---

source/index.txt
source/sync/conflict-resolution.txt
source/sync/overview.txt

Based on https://docs.realm.io/sync/v/3.x/self-hosted/customize/conflict-resolution
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/sync-details/sync/conflict-resolution.html
https://jira.mongodb.org/browse/DOCSP-11291

(DOCSP-11291): Port conflict resolution page from old docs

---

source/node/sync-data.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-9416
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-9416/node/sync-data.html#session-multiplexing

(DOCSP-9416): session multiplexing guide for node

---

source/mongodb/service-limitations.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-11249
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-11249/mongodb/service-limitations.html

(DOCSP-11249): mongodb transactions are now supported in functions

---

source/node/quick-start.txt

Fix undefined user.id in node quick-start

---

source/deploy/application-configuration-files.txt
source/includes/appschema-mongodb.rst
source/includes/appschema-services.rst
source/mongodb/specify-cluster-read-preference.txt

- (DOCSP-10806): Add Sync Configuration Files
Shuffled around the MongoDB Service section and added the **Synced Cluster Configuration** section
- [Application Configuration Files > MongoDB](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/sync-config/deploy/application-configuration-files.html#appschema-mongodb)

(DOCSP-10806): Add Sync Configuration Files

---

source/ios/quick-start.txt

JIRA:
-----
* https://jira.mongodb.org/browse/DOCSP-11275
Stage:
-------
*  https://docs-mongodborg-staging.corp.mongodb.com/realm/mohammad.hunan/DOCPS-11275-IOS-QuickStart-Output/index.html

(DOCSP-11275): Added IOS QuickStart Output

---

source/includes/extracts-service-actions.yaml
source/mongodb/actions.txt
source/mongodb/actions/collection.distinct.txt

Add info about using `distinct` in realm functions. 
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/realm/caleb/distinct/mongodb/actions/collection.distinct.html#collection.distinct)
[Jira](https://jira.mongodb.org/browse/DOCSP-11076)

add 'distinct' info

---

conf.py
source/android/mongodb.txt
source/includes/aggregation-stages.rst
source/includes/mongodb-data-access-example-plant-documents.rst
source/includes/mongodb-data-access-query-filter-indeterminate-order-note.rst
source/includes/steps-crud-snippets-node.yaml
source/includes/steps-crud-snippets-react-native.yaml
source/node.txt
source/node/mongodb.txt
source/react-native.txt
source/react-native/mongodb.txt

Jira:
-----
* https://jira.mongodb.org/browse/DOCSP-11027
Stage:
-------
* Node: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-11027-Node-RN-MongoDB-DataAccess/node/mongodb.html
* React Native: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-11027-Node-RN-MongoDB-DataAccess/react-native/mongodb.html
Notes:
-------
* All the wording is the same for React Native as Node, just a few of the code snippets are slightly altered
* Most of the wording is heavily based off Nate's Android Data Access Page

(DOCSP-11027): Node & React Native MongoDB Data Access

---

source/authentication/anonymous.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-11353
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-11353/authentication/anonymous.html
Also took the liberty of converting the tabs on the anonymous auth page from legacy tabs to modern tabs. So shiny and new!

(DOCSP-11353): flesh out anonymous auth enable in UI steps

---

source/node/reads.txt
source/react-native/reads.txt

jira:
----
* https://jira.mongodb.org/browse/DOCSP-11451
stage:
------
* React Native: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-11451-RealmReads-Fix/react-native/reads.html
* Node: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-11451-RealmReads-Fix/node/reads.html

(DOCSP-1145): RN + Node - add note /reads.html to quickstart#openarealm

---

source/android/code-samples/quick-start.java
source/android/code-samples/quick-start.kt
source/android/code-samples/task.java
source/android/quick-start.txt

JIRA: https://jira.mongodb.org/browse/DOCS-13780
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-13780/android/quick-start.html

(DOCSP-13680): Android quick-start CRUD operations and Notifications

---

source/android/mongodb.txt

Staging: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/MongoDBDataAccessOnThisPage/android/mongodb.html

Added on this page to Android MongoDB Data Access page

---

conf.py
source/node/examples/node-quickstart.js
source/node/examples/node-quickstart.ts
source/node/quick-start.txt

- Tweaked code style in JS snippets & full example
- Added TypeScript snippets & full example
- (DOCSP-11469): Add TypeScript to Realm Node QuickStart
- [Node > Quick Start](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/node-qs-typescript/node/quick-start.html)

(DOCSP-11469): Add TypeScript to Realm Node QuickStart

---

source/openapi-admin-v3.yaml

- (DOCSP-10712): Realm Admin API Secrets Endpoint Corrections
- [Secrets APIs](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/admin-api/admin/api/v3.html#secrets-apis)

(DOCSP-10712): Realm Admin API Secrets Endpoint Corrections

---

source/ios.txt
source/ios/remotely-access-mongodb.txt

- Expecting API changes in next release, will need to revisit this.
- Quick version for now.
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/ios-mongodb/ios/remotely-access-mongodb.html
https://jira.mongodb.org/browse/DOCSP-11026

(DOCSP-11026): Add MongoDB Data Access for Swift

---

source/billing.txt

- (DOCSP-11116): Update Realm Sync free tier to 10,000 Hours
- [Billing](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/billing/billing.html)

(DOCSP-11116): Update Realm Sync free tier to 10,000 Hours

---

source/web/quickstart.txt

- (DOCSP-11586): Include script tag snippet on Realm Web install page
- [Realm Web Quick Start](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/realm-web-cdn/web/quickstart.html#install-the-web-sdk)

(DOCSP-11586): Include script tag snippet on Realm Web install page

---

source/includes/steps-tutorial-ios-swift.yaml
source/includes/steps-tutorial-react-native.yaml
source/tutorial/nodejs-cli.txt

https://jira.mongodb.org/browse/DOCSP-11473
https://jira.mongodb.org/browse/DOCSP-11475
https://jira.mongodb.org/browse/DOCSP-11476
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/unify-backend/tutorial/ios-swift.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/unify-backend/tutorial/react-native.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/unify-backend/tutorial/nodejs-cli.html
https://github.com/mongodb/docs-realm/pull/373

Update tutorial text for unified backend

---

source/authentication.txt
source/includes/appschema-configuration.rst
source/includes/custom-data-may-be-stale.rst
source/includes/use-custom-data-note.rst
source/includes/user-object-fields.rst
source/includes/write-access-to-custom-data-note.rst
source/node.txt
source/node/access-custom-user-data.txt
source/react-native.txt
source/react-native/access-custom-user-data.txt
source/services/expression-variables.txt
source/tutorial/web-graphql.txt
source/users/define-custom-user-data.txt
source/users/enable-custom-user-data.txt

Jira:
-----
* https://jira.mongodb.org/browse/DOCSP-11256
Stage:
-------
* Node: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-11256-AccessCustomUserData-NodeRN/node/access-custom-user-data.html
* React Native: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-11256-AccessCustomUserData-NodeRN/node/access-custom-user-data.html
* Link to this page from the "Enable Custom User Data" (formerly: "Define Custom Data") page:  https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-11256-AccessCustomUserData-NodeRN/users/enable-custom-user-data.html

(DOCSP-11256): Access Custom User Data Node/RN

---

source/web.txt
source/web/includes/remote-mongodb-find.html
source/web/remotely-access-mongodb.txt

- This is the simple version
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/web-mongodb/web/remotely-access-mongodb.html
https://jira.mongodb.org/browse/DOCSP-11028

(DOCSP-11028): Remote access MongoDB for Web

---

source/android/query-engine.txt
source/examples/Query/Accumulator.kt
source/examples/Query/Comparison.java
source/examples/Query/Comparison.kt
source/examples/Query/Logical.kt
source/examples/Query/String.java
source/examples/Query/String.kt
source/examples/Schemas/ProjectAndTask.java
source/examples/Schemas/ProjectAndTask.kt

https://jira.mongodb.org/browse/DOCSP-11639
[Android - Query Engine](https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-11639/android/query-engine.html)

(DOCSP-11639): Fix Android Query Engine examples, kotlin-java parity

---

source/android/authenticate.txt

[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/11179/android/authenticate.html#api-key)
[Jira](https://jira.mongodb.org/browse/DOCSP-11179)

Add API Key and Custom Func Auth

---

source/android/authenticate.txt
source/ios/authenticate.txt

[Jira](https://jira.mongodb.org/browse/DOCSP-11178)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/11178/ios/authenticate.html)

Add auth methods for iOS

---

source/android.txt
source/android/open-a-realm.txt
source/ios.txt
source/ios/open-a-realm.txt
source/ios/quick-start.txt
source/node.txt
source/node/open-a-realm.txt
source/react-native.txt
source/react-native/open-a-realm.txt

[Jira](https://jira.mongodb.org/browse/DOCSP-11463)
**Staged**
[Android](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/11463/android/open-a-realm.html)
[iOS](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/11463/ios/open-a-realm.html) and an update to [the Quick Start](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/11463/ios/quick-start.html).
[Node](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/11463/node/open-a-realm.html)
[React-Native](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/11463/react-native/open-a-realm.html)

DOCSP-11463

---

source/index.txt

https://jira.mongodb.org/browse/DOCSP-11503
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/v5-docs/index.html#realm-database-version-5-documentation

(DOCSP-11503): Add link to realm.io docs

---

source/android.txt

Remove double Sync Data on Android

---

source/ios/query-engine.txt

https://jira.mongodb.org/browse/DOCSP-11063
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/count-agg/ios/query-engine.html#aggregate-operators

(DOCSP-11063): Note that @count is only supported on relationship collections

---

source/get-started/glossary.txt
source/mongodb/document-schemas.txt
source/node.txt
source/node/embedded-objects.txt
source/node/relationships.txt
source/react-native.txt
source/react-native/embedded-objects.txt
source/react-native/relationships.txt

- (DOCSP-11033): Embedded Objects (Node/RN)
Note: These pages are essentially duplicates
- [Embedded Objects (Node)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/embedded/node/embedded-objects.html)
- [Embedded Objects (React Native)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/embedded/react-native/embedded-objects.html)

(DOCSP-11033): Embedded Objects (Node/RN)

---

source/functions/json-and-bson.txt

https://jira.mongodb.org/browse/DOCSP-11812
https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-11812-jsonandbson-syntax-fix/functions/json-and-bson.html#EJSON.parse

(DOCSP-11812): JSON & BSON page syntax fix

---

conf.py
source/includes/steps-react-web-quickstart.yaml
source/web.txt
source/web/react-web-quickstart.txt

- (DOCSP-11527): Port React web quickstart guide
- [MongoDB Realm - React Quickstart](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/web-quickstart-react/web/react-web-quickstart.html)

(DOCSP-11527): Port React web quickstart guide

---

source/mongodb.txt
source/mongodb/crud-snippets/setup.rst
source/mongodb/crud-snippets/transactions/transactions.js
source/mongodb/service-limitations.txt
source/mongodb/transactions.txt

- added example of executing a transaction with the Functions MQL connection
- removed tabs from the "setup" include for MongoDB CRUD Operations (only one tab just seemed silly)
- removed "transactions" limitation from service-limitations
https://jira.mongodb.org/browse/DOCSP-11249
https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-11249/mongodb/transactions.html

DOCSP-11249

---

source/android/open-a-realm.txt

Fix broken link in Open/Close a Realm

---

source/android/sync-data.txt
source/examples/MultiUser/AddUser/AddUser.swift
source/examples/MultiUser/LogoutUser/LogoutUser.swift
source/examples/QuickStarts/CompleteExample.swift
source/includes/steps-install-cocoapods.yaml
source/includes/steps-tutorial-ios-swift.yaml
source/ios.txt
source/ios/authenticate.txt
source/ios/call-a-function.txt
source/ios/create-manage-api-keys.txt
source/ios/init-realmclient.txt
source/ios/manage-email-password-users.txt
source/ios/quick-start.txt
source/ios/remotely-access-mongodb.txt
source/ios/sync-data.txt

Swift and Obj-C updates for the beta 3 release.
https://jira.mongodb.org/browse/DOCSP-10892
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/ios-beta-3/ios/quick-start.html

Updates for iOS Beta 3

---

source/includes/steps-tutorial-react-native.yaml

https://jira.mongodb.org/browse/DOCSP-11871
https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-11871-RN-UserID-docs/tutorial/react-native.html
https://github.com/realm/realm-js/releases

DOCSP-11871): replace user.identity w/ user.id per beta.9 docs

---

source/mongodb/service-limitations.txt

https://jira.mongodb.org/browse/DOCSP-11736
https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-11736-ServiceLimitations-FileUploadLimit-Note/mongodb/service-limitations.html#static-hosting

(DOCSP-11736): Service Limitations - 25 MB max file upload

---

source/web/quickstart.txt

- (DOCSP-11920): Remove mentions of Sync in web quickstart

(DOCSP-11920): Remove mentions of Sync in web quickstart

---

source/web.txt

(DOCSP-11920): Remove mentions of Sync in web client guide
https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/web-no-sync/web.html

(DOCSP-11920): Remove mentions of Sync in web client guide

---

source/index.txt
source/reference/third-party-licenses.txt

https://jira.mongodb.org/browse/DOCS-13361
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/third-party-license/reference/third-party-licenses.html

(DOCSP-13361): Add third-party license page

---

source/examples/EmbeddedObjects/CreateEmbeddedObject.m
source/examples/EmbeddedObjects/CreateEmbeddedObject.swift
source/examples/EmbeddedObjects/DefineEmbeddedObjects.m
source/examples/EmbeddedObjects/DefineEmbeddedObjects.swift
source/examples/EmbeddedObjects/QueryEmbeddedObjects.m
source/examples/EmbeddedObjects/QueryEmbeddedObjects.swift
source/examples/EmbeddedObjects/ReplaceEmbeddedObject.m
source/examples/EmbeddedObjects/ReplaceEmbeddedObject.swift
source/examples/EmbeddedObjects/UpdateEmbeddedObject.m
source/examples/EmbeddedObjects/UpdateEmbeddedObject.swift
source/get-started/glossary.txt
source/includes/embedded-object-json-schema.rst
source/ios.txt
source/ios/embedded-objects.txt
source/node/embedded-objects.txt
source/react-native/embedded-objects.txt

https://jira.mongodb.org/browse/DOCSP-11837
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/embedded-ios/ios/embedded-objects.html

(DOCSP-11837): Embedded Objects (iOS)

---

source/web.txt
source/web/access-custom-user-data.txt

- (DOCSP-11024): Custom User Data (Web)
- [Web > Access Custom User Data](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/web-custom-user-data/web/access-custom-user-data.html)

(DOCSP-11024): Custom User Data (Web)

---

source/functions/built-in-module-support.txt

https://jira.mongodb.org/browse/DOCSP-11952
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/dns-support/functions/built-in-module-support.html

(DOCSP-11952): Indicate support for dns node library

---

source/includes/data-lake-no-writes-note.rst
source/includes/data-lake-rules-note.rst
source/includes/data-lake-wire-protocol-note.rst
source/includes/data-source-configuration.rst
source/mongodb.txt
source/mongodb/delete-documents.txt
source/mongodb/insert-documents.txt
source/mongodb/update-documents.txt

- As requested/pointed out by Daniel
https://jira.mongodb.org/browse/DOCSP-11994
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/data-lake-quick-fix/mongodb.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/data-lake-quick-fix/mongodb/insert-documents.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/data-lake-quick-fix/mongodb/link-a-data-source.html

(DOCSP-11994): Data Lake quick fixes

---

source/includes/steps-configure-custom-function-auth-realm-ui.yaml

https://jira.mongodb.org/browse/DOCSP-11664
I'm not able to stage at the moment (still resolving AWS access key request).

DOCSP-11664: Clarify Custom Function Auth Example

---

source/android/access-custom-user-data.txt
source/android/mongodb.txt

https://jira.mongodb.org/browse/DOCSP-11854
[Android - Custom User Data](https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-11854/android/access-custom-user-data.html) (small update to java examples that used the wrong scoped Task when printing out an error)
[Android - MongoDB Data Access](https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-11854/android/mongodb.html) (updated syntax to match new API for MQL in beta 6)

(DOCSP-11854): Android MQL API update

---

source/billing.txt

https://jira.mongodb.org/browse/DOCSP-12039
Still unable to stage builds (due to missing AWS keys)

(DOCSP-12039): Clarify active sync connections for billing

---

source/android.txt
source/android/link-identities.txt

I would like to include some information about what happens to user ids, custom user data, etc. But I wanted to check first to make sure that's not going too far.
https://jira.mongodb.org/browse/DOCSP-12223
https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-12223/android/link-identities.html

(DOCSP-12223): Link User Identities, Android

---

source/mongodb/service-limitations.txt

- Also fix weird glitch at the bottom of the page.
https://mongodb.slack.com/archives/CLY6HQWUE/p1600213484036900
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/distinct-quickfix/mongodb/service-limitations.html

Quickfix: remove distinct() exception from limitations

---

source/functions/built-in-module-support.txt

https://jira.mongodb.org/browse/DOCSP-11097
https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/docsp-11907-dgram-node-function-dependency/functions/built-in-module-support.html#dgram

(DOCSP-11907): add dgram to partially supported module for mdb realm functions

---

source/triggers/database-triggers.txt

- (DOCSP-12169): $project for db trigger events
- [Database Trigger Configuration](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/triggers-project/triggers/database-triggers.html#database-trigger-configuration)

(DOCSP-12169): $project for db trigger events

---

conf.py
source/examples/CustomUserData/CreateCustomUserData.swift
source/examples/CustomUserData/UpdateCustomUserData.swift
source/examples/MultiUser/AddUser/AddUser.swift
source/includes/steps-install-cocoapods.yaml
source/includes/steps-tutorial-ios-swift.yaml
source/ios.txt
source/ios/authenticate.txt
source/ios/manage-email-password-users.txt
source/ios/remotely-access-mongodb.txt

https://jira.mongodb.org/browse/DOCSP-12292
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/ios-beta-5/ios.html
https://github.com/mongodb-university/realm-tutorial/pull/73

(DOCSP-12292): Update tutorial text and examples for iOS beta.5

---

source/includes/steps-task-tracker-enable-sync.yaml
source/includes/steps-task-tracker-server-auth.yaml
source/includes/steps-task-tracker-server-data-model.yaml
source/includes/steps-tutorial-android-kotlin.yaml
source/tutorial/android-kotlin.txt
source/tutorial/ios-swift.txt
source/tutorial/nodejs-cli.txt
source/tutorial/react-native.txt

See also: https://github.com/mongodb-university/realm-tutorial/pull/76
https://jira.mongodb.org/browse/DOCSP-12291
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/tutorial-phase1-backend/tutorial/realm-app.html

(DOCSP-12291): Update phase 1 User schema and other tutorial fixes

---

source/includes/steps-configure-custom-function-auth-import-export.yaml
source/includes/steps-configure-custom-function-auth-realm-ui.yaml

https://jira.mongodb.org/browse/DOCSP-12323
https://docs-mongodbcom-staging.corp.mongodb.com/realm/lisbethlazala/custom-auth-username/authentication/custom-function.html

(DOCSP-12323): Add support for setting user name in return result of custom function auth

---

source/authentication/custom-jwt.txt
source/includes/user-object-fields.rst

https://jira.mongodb.org/browse/DOCSP-12150
https://docs-mongodbcom-staging.corp.mongodb.com/realm/lisbethlazala/jwt-user-display-names/authentication/custom-jwt.html

(DOCSP-12150): JWT user display names

---

source/graphql/authenticate.txt

- (DOCSP-12349): Add Alert for GraphQL header authentication
- [Authenticate GraphQL Requests](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/graphql-auth-header/graphql/authenticate.html)

(DOCSP-12349): Add Alert for GraphQL header authentication

---

source/includes/steps-install-node-iot.yaml
source/includes/steps-install-node.yaml
source/includes/steps-install-react-native-pre-v60.yaml
source/includes/steps-install-react-native-v60-plus.yaml
source/includes/steps-tutorial-react-native.yaml

https://jira.mongodb.org/browse/DOCSP-12429
* Node: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/node-rn-version-quickfix/node/install.html#installation
* IOT: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/node-rn-version-quickfix/node/install.html#iot-installation
* React Native: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/node-rn-version-quickfix/react-native/install.html#installation
* React Native **Tutorial**: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/node-rn-version-quickfix/tutorial/react-native.html#install-dependencies
*  Spacing Fixes

update realm  node/rn/iot to most recent beta

---

conf.py
source/includes/steps-crud-snippets-node.yaml
source/includes/steps-crud-snippets-react-native.yaml
source/node/access-custom-user-data.txt
source/node/mongodb.txt
source/react-native/access-custom-user-data.txt
source/react-native/mongodb.txt
source/web/mongodb.txt

https://jira.mongodb.org/browse/DOCSP-12433
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/12433/index.html
https://jira.mongodb.org/browse/RJS-689
https://github.com/realm/realm-js/pull/3175/commits/0cb2199e7481cb11789bc5de7426721511b9d663

remove Remote from mongodb links. update master link to beta.13

---

conf.py

fix latest js link

---

source/functions.txt

Removes listed function constraints that are now supported. A more new reference page with detailed support information is planned as part of DOCSP-12450
- (DOCSP-12394): [REALMC] Add Extended JS String features
- (DOCSP-12404): [REALMC] Add Extended JS Array features
- (DOCSP-12460): [REALMC] Add Extended JS Object features
- [Functions > Constraints](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/functions/functions.html#constraints)

(DOCSP-12394, 12404, 12460): Extended ES6+ Support

---

source/node/quick-start.txt

https://jira.mongodb.org/browse/DOCSP-12500
https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/moe-node-quickstart-quickfix/node/quick-start.html#authenticate-a-user

replaced function call run() with handleLogin()

---

source/node.txt

N/A
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fix-node-link/node.html

Quick Fix: Fix broken link on node.txt

---

conf.py
source/billing.txt
source/get-started/glossary.txt
source/includes/steps-sync-protocol.yaml
source/sync.txt
source/sync/partitioning.txt
source/sync/protocol.txt

- (DOCSP-11287): Document Sync Protocol Details
- (DOCSP-10812): Add more detail on billing for Realm Requests for Sync Operations
- [Realm Sync Protocol](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/sync-protocol/sync/protocol.html)

(DOCSP-11287, 10812): Document Sync Protocol + Clarify Billing

---

snooty.toml

- (DOCSP-12279): Update snooty.toml to match conf.py

(DOCSP-12279): Update snooty.toml to match conf.py

---

source/includes/steps-tutorial-ios-swift.yaml
source/includes/steps-tutorial-react-native.yaml
tutorial/rn/.eslintrc.js
tutorial/rn/App.js
tutorial/rn/components/Logout.js
tutorial/rn/components/ManageTeam.js
tutorial/rn/components/TaskItem.js
tutorial/rn/getRealmApp.js
tutorial/rn/ios/Podfile.lock
tutorial/rn/package-lock.json
tutorial/rn/package.json
tutorial/rn/providers/AuthProvider.js
tutorial/rn/providers/TasksProvider.js
tutorial/rn/views/ProjectsView.js
tutorial/rn/views/TasksView.js
tutorial/rn/views/WelcomeView.js

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/bluehawk-rn/tutorial/react-native.html

Bluehawk RN

---

source/includes/steps-tutorial-android-kotlin.yaml

Missed once occurrence of emailPasswordAuth in the beta 8 refactor. Updating it here.

emailPasswordAuth -> emailPassword refactor

---

source/node/electron.txt

https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/electron-quickfix-rst-error/node/electron.html#working-with-realm-using-renderer-and-main-processes

Electron - fix missing underline

---

source/mongodb/crud-and-aggregation-apis.txt

https://jira.mongodb.org/browse/DOCSP-12355
https://docs-mongodbcom-staging.corp.mongodb.com/realm/lisbethlazala/bulkwrite-edit/mongodb/crud-and-aggregation-apis.html#bulk-write-operations

(DOCSP-12355): Examine accuracy of BulkWrite docs

---

source/includes/steps-realm-with-electron-using-create-react-app.yaml
source/includes/steps-realm-with-electron.yaml
source/node/electron.txt

https://jira.mongodb.org/browse/DOCSP-12650
https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-12650-Electron-QuickStart-Updates/node/electron.html

(DOCSP-12650) Electron Quick Start Updates

---

source/includes/steps-tutorial-react-native.yaml
source/tutorial/generated/code/final/AuthProvider.codeblock.user-realm-cleanup.js
tutorial/rn/providers/AuthProvider.js

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fix-rn-tutorial/tutorial/react-native.html

Fix RN tutorial code snippet

---

source/dotnet/compatibility.txt

https://jira.mongodb.org/browse/DOCSP-12478
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/dotnet-compat/dotnet/compatibility.html

(DOCSP-12478): Update dotnet compatibility table

---

examples/dotnet/Examples/DecimalFun.cs
examples/dotnet/Examples/Examples.cs
source/dotnet/objects.txt
source/examples/generated/code/start/DecimalFun.codeblock.decimal128.cs
source/examples/generated/code/start/DecimalFun.cs

https://jira.mongodb.org/browse/DOCSP-12126
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/decimal/dotnet/objects.html

add support for decimal128

---

examples/dotnet/Examples/ClientResetExamples.cs
examples/dotnet/Examples/CustomUserDataExamples.cs
source/dotnet/client-reset.txt
source/examples/generated/code/start/ClientResetExamples.codeblock.handle.cs
source/examples/generated/code/start/ClientResetExamples.codeblock.mongo-setup.cs
source/examples/generated/code/start/ClientResetExamples.cs

https://jira.mongodb.org/browse/DOCSP-12477
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/12477/dotnet/client-reset.html

Client Resets

---

examples/dotnet/Examples/Examples.cs
source/dotnet/link-identities.txt
source/examples/generated/code/start/Examples.codeblock.link.cs
source/examples/generated/code/start/Examples.codeblock.link2.cs
source/examples/generated/code/start/Examples.codeblock.logon_EP.cs
source/examples/generated/code/start/Examples.cs

https://jira.mongodb.org/browse/DOCSP-12483
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/link/dotnet/link-identities.html

add user linking

---

source/dotnet.txt
source/get-started/introduction-mobile.txt
source/includes/seealso-client-guides-manage-email-password-users.rst
source/index.txt

https://jira.mongodb.org/browse/DOCSP-12827
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/dotnetfinal/index.html

Dotnetfinal

---

README.rst

https://github.com/mongodb/docs-realm/tree/reamde-typo

fix readme typo

---

conf.py
examples/ios/Examples/MultipleUsers.swift
examples/ios/Podfile
examples/ios/Podfile.lock
examples/ios/README.md
source/examples/generated/code/start/MultipleUsers.codeblock.link-identity.swift
source/includes/steps-install-cocoapods.yaml
source/includes/steps-tutorial-ios-swift.yaml
source/ios.txt
source/ios/install.txt
source/tutorial/generated/code/final/ManageTeamViewController.codeblock.add-team-member.swift
source/tutorial/generated/code/final/ManageTeamViewController.codeblock.remove-team-member.swift
source/tutorial/generated/code/final/ProjectsViewController.codeblock.did-select-row-at.swift
source/tutorial/generated/code/final/SceneDelegate.codeblock.initialize-app.swift
source/tutorial/generated/code/final/WelcomeViewController.codeblock.sign-in.swift
source/tutorial/ios-swift.txt
tutorial/swift-ios/Podfile
tutorial/swift-ios/Podfile.lock
tutorial/swift-ios/Task Tracker/ManageTeamViewController.swift
tutorial/swift-ios/Task Tracker/ProjectsViewController.swift
tutorial/swift-ios/Task Tracker/WelcomeViewController.swift

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/ios10.1.0/tutorial/ios-swift.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/ios10.1.0/ios/install.html

Updates for Realm iOS 10.1.0

---

source/web/init-realmclient.txt

- (DOCSP-12888): Update realm-web for v10 GA
- [Staged]()

(DOCSP-12888): Update realm-web for v10 GA

---

source/dotnet.txt
source/index.txt

https://jira.mongodb.org/browse/DOCSP-12923
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/betabanner/dotnet.html

Betabanner

---

source/web/quickstart.txt

https://jira.mongodb.org/browse/DOCSP-13028
https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/hotfix-realm-web-UserFunctions-instead-of-AppFunctions/web/quickstart.html#call-a-function

(DOCSP-13028) - Replaced Realm.App.Functions with Realm.User.Functions for Realm Web rc1 and onward (including 10.0.0) release

---

source/web.txt
source/web/link-identities.txt

https://jira.mongodb.org/browse/DOCSP-12998
https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/docsp-12998-link-identity-web/web/link-identities.html
(Note: Currently our team has not decided on a cadence for testing Realm-Web code examples, so until we make a decision on that we are not placing realm-web code snippets in the /Examples/ directory. Temporarily, if you the reviewer/reader of this PR, are interested in testing this feature out, you can see these tests here: [javascript: /__tests__/web-link-identities.js](https://github.com/mongomoe/Unofficial-docs-realm-realm-web-tests/blob/master/__tests__/web-link-identities.js) or [typescript: /__tests__/web-link-identities.ts](https://github.com/mongomoe/Unofficial-docs-realm-realm-web-tests/blob/master/__tests__/web-li …

(DOCSP-12998): Link Identities Doc for Realm Web

---

examples/node/Examples/link-identities.js
examples/node/Examples/link-identities.ts
examples/node/package-lock.json
examples/node/package.json
source/examples/generated/code/start/link-identities.codeblock.link-identities.js
source/examples/generated/code/start/link-identities.codeblock.link-identities.ts
source/examples/generated/code/start/link-identities.js
source/node.txt
source/node/link-identities.txt
source/react-native.txt
source/react-native/link-identities.txt

https://jira.mongodb.org/browse/DOCSP-12222
* Node: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/docsp-12222-link-identity-javascript/node/link-identities.html
* React Native: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/docsp-12222-link-identity-javascript/react-native/link-identities.html

(DOCSP-12222): Link Credentials Node/React Native SDKs Doc(s)

---

source/android/authenticate.txt
source/android/create-manage-api-keys.txt
source/dotnet/authenticate.txt
source/dotnet/create-manage-api-keys.txt
source/includes/note-enable-facebook-auth.rst
source/includes/note-facebook-profile-picture-url.rst
source/includes/note-store-user-api-key-value.rst
source/ios/authenticate.txt
source/ios/create-manage-api-keys.txt
source/mongodb/define-roles-and-permissions.txt
source/node/authenticate.txt
source/node/create-manage-api-keys.txt
source/react-native/authenticate.txt
source/react-native/create-manage-api-keys.txt
source/sync/rules.txt
source/web/authenticate.txt
source/web/create-manage-api-keys.txt

- [Define Sync Rules](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/notes/sync/rules.html)
- [Define Roles & Permissions](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/notes/mongodb/define-roles-and-permissions.html)
- [Facebook OAuth (Android)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/notes/android/authenticate.html#android-login-facebook)
- [Facebook OAuth (iOS)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/notes/ios/authenticate.html#ios-login-facebook)
- [Facebook OAuth (Node)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/notes/node/authenticate.html#node-login-facebook)
- [Facebook OAuth (RN)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/notes/react-native/authenticate.html#react-na …

(DOCSP-12802, 13002, 13093): Add some helpful notes

---

source/react-native/quick-start.txt

https://jira.mongodb.org/browse/DOCSP-12855
https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-12855-Update-RN-QuickStart/react-native/quick-start.html

(DOCSP-12855): Fixed Syntax In React Native QuickStarts

---

examples/ios/Examples/CompleteQuickStart.swift
examples/ios/Examples/OpenCloseRealm.swift
examples/ios/Podfile
examples/ios/Podfile.lock
source/examples/generated/code/start/CompleteQuickStart.codeblock.complete-quick-start.swift
source/examples/generated/code/start/OpenCloseRealm.codeblock.open-synced-realm.swift

- Changed partition value to avoid conflict with other tests on other platforms
- 10.1.2 does not install - see ask-realm-sdks channel
https://jira.mongodb.org/browse/DOCSP-12926

(DOCSP-12926): Update for iOS 10.1.1

---

source/web/authenticate.txt

https://jira.mongodb.org/browse/DOCSP-12936
https://docs-mongodbcom-staging.corp.mongodb.com/realm/nathan.contino/DOCSP-12936/web/authenticate.html

(DOCSP-12936): Fixed typo

---

config/redirects

https://jira.mongodb.org/browse/DOCSP-12556

(DOCSP-12556): Add missing redirects for old stitch pages

---

conf.py
examples/ios/Examples/CompleteQuickStart.swift
examples/ios/Examples/OpenCloseRealm.swift
examples/ios/Podfile
examples/ios/Podfile.lock
source/examples/generated/code/start/CompleteQuickStart.codeblock.complete-quick-start.swift
source/examples/generated/code/start/OpenCloseRealm.codeblock.open-synced-realm-synchronously.swift
source/examples/generated/code/start/OpenCloseRealm.codeblock.open-synced-realm.swift
source/includes/steps-install-cocoapods.yaml
source/ios.txt

- No significant change required
- Missing "_id" now detected on sync realm classes, hence update to tests

Update iOS docs for 10.1.4

---

tutorial/swift-ios/Podfile
tutorial/swift-ios/Podfile.lock

Update tutorial for ios 10.1.4

---

source/node/open-a-realm.txt
source/react-native/open-a-realm.txt

https://jira.mongodb.org/browse/DOCSP-13017
Node: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-13017-JS-SDK-Open-Realm-Synchronously/node/open-a-realm.html
React Native: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-13017-JS-SDK-Open-Realm-Synchronously/react-native/open-a-realm.html

(DOCSP-13017): JS SDK Open a Realm Synchronously

---

source/mongodb/crud-and-aggregation-apis.txt

- (DOCSP-12861): currentOp
- (DOCSP-12864): $merge/$out & read preference
[CRUD & Aggregation APIs > Aggregation](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/mql/mongodb/crud-and-aggregation-apis.html#aggregation)

(DOCSP-12861, DOCSP-12864): MQL Updates

---

config/redirects

redirect for GraphQL Types & Resolvers Link in Manual

---

source/includes/steps-install-node-iot.yaml
source/includes/steps-install-node.yaml
source/includes/steps-install-react-native-pre-v60.yaml
source/includes/steps-install-react-native-v60-plus.yaml
source/node/open-a-realm.txt
source/node/sync-data.txt
source/react-native/open-a-realm.txt

https://jira.mongodb.org/browse/DOCSP-12854
* [Node] QuickStart: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-12854-RealmJS-10.0.1/node/install.html#id2
* [React Native] QuickStart: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-12854-RealmJS-10.0.1/react-native/install.html#install-realm-with-npm
* [Node] Open a Realm: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-12854-RealmJS-10.0.1/node/open-a-realm.html
* [React Native]  Open a Realm: https://docs-mongodborg-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-12854-RealmJS-10.0.1/index.html
* [Node] Sync Data: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-12854-RealmJS-10.0.1/node/sync-data.html#session-multiplexing

(DOCSP-12854): Update Realm JS Docs to 10.0.1

---

source/dotnet.txt
source/dotnet/auxiliary-files.txt
source/dotnet/client-reset.txt

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/qf/index.html

Quick fixes

---

source/functions.txt

(DOCSP-13416): Describe how to return JSON (not EJSON) from a function
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/ejson/functions#behavior

(DOCSP-13416): Describe how to return JSON (not EJSON) from a function

---

tutorial/rn/providers/AuthProvider.js

Code PR: https://github.com/mongodb-university/realm-tutorial-react-native/pull/1

Add missing hide-start to RN tutorial

---

source/includes/tutorial-request-for-feedback-note.rst
source/ios/swiftui.txt

(DOCSP-13426): Update references to feedback widget
https://docs-mongodborg-staging.corp.mongodb.com/realm/docsworker-xlarge/feedback-widget/

(DOCSP-13426): Update references to feedback widget

---

source/openapi-admin-v3.yaml

(DOCSP-12303): Admin API Users endpoint pagination parameters
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/user-pagination/admin/api/v3#users-apis

(DOCSP-12303): Admin API Users endpoint pagination parameters

---

source/android/reference.txt
source/includes/steps-install-android.yaml

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/android-sdk-v10.1.1/android/install

Bumped Android SDK to v10.1.1

---

source/android/reference.txt
source/dotnet/reference.txt
source/ios/reference.txt
source/node/reference.txt
source/react-native/reference.txt
source/web.txt

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/android-release-notes/android

android release notes

---

examples/ios/Examples/QueryEngine.m
examples/ios/Examples/QueryEngine.swift
examples/ios/Examples/TestSetup.swift
examples/ios/RealmExamples.xcodeproj/project.pbxproj
source/examples/generated/code/start/QueryEngine.codeblock.aggregate-operators.m
source/examples/generated/code/start/QueryEngine.codeblock.aggregate-operators.swift
source/examples/generated/code/start/QueryEngine.codeblock.comparison-operators.m
source/examples/generated/code/start/QueryEngine.codeblock.comparison-operators.swift
source/examples/generated/code/start/QueryEngine.codeblock.logical-operators.m
source/examples/generated/code/start/QueryEngine.codeblock.logical-operators.swift
source/examples/generated/code/start/QueryEngine.codeblock.models.m
source/examples/generated/code/start/QueryEngine.codeblock.models.swift
source/examples/generated/code/start/QueryEngine.codeblock.predicates.m
source/examples/generated/code/start/QueryEngine.codeblock.predicates.swift
source/examples/generated/code/start/QueryEngine.codeblock.set-operators.m
source/examples/generated/code/start/QueryEngine.codeblock.set-operators.swift
source/examples/generated/code/start/QueryEngine.codeblock.setup.m
source/examples/generated/code/start/QueryEngine.codeblock.setup.swift
source/examples/generated/code/start/QueryEngine.codeblock.string-operators.m
source/examples/generated/code/start/QueryEngine.codeblock.string-operators.swift
source/examples/generated/code/start/QueryEngine.codeblock.subquery.m
source/examples/generated/code/start/QueryEngine.codeblock.subquery.swift
source/examples/generated/code/start/QueryEngine.codeblock.substitutions.m
source/examples/generated/code/start/QueryEngine.codeblock.substitutions.swift
source/ios/query-engine.txt

https://jira.mongodb.org/browse/DOCSP-12990
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/query-engine/ios/query-engine

(DOCSP-12990): Add missing parts of query engine page

---

source/tutorial/realm-app.txt

Translate Whitelist to Access List in Tutorial backend setup

---

examples/ios/Examples/QueryEngine.m
examples/ios/Examples/QueryEngine.swift
source/examples/generated/code/start/QueryEngine.codeblock.comparison-operators.m
source/examples/generated/code/start/QueryEngine.codeblock.comparison-operators.swift
source/ios/query-engine.txt

https://jira.mongodb.org/browse/DOCSP-12990
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/ios-query-2/ios/query-engine

iOS Query Engine additional fixes

---

examples/node/Examples/authenticate.js
examples/node/Examples/authenticate.ts

https://jira.mongodb.org/browse/DOCSP-13495
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-13018-quickfix-authenticatedotts-bluehawkbug-with-generatedfile-replacewith/node/authenticate#email-password

(DOCSP-13018): Quick Fix - Changed to multiline comment for workaround to bluehawk bug w/ inline comments in `authenticate.ts|js` 

---

examples/android/tutorial/app/src/main/java/com/mongodb/realm/examples/java/AuthActivity.java
examples/android/tutorial/app/src/main/java/com/mongodb/realm/examples/kotlin/AuthActivity.kt
examples/android/tutorial/build.gradle
source/android/install.txt
source/android/reference.txt
source/examples/generated/android/code/final/AuthActivity.codeblock.google.java
source/examples/generated/android/code/final/AuthActivity.codeblock.google.kt
source/examples/generated/android/code/final/AuthActivity.java
source/examples/generated/android/code/final/AuthActivity.kt
source/examples/generated/android/code/final/build.codeblock.realm-dependency.gradle
source/examples/generated/android/code/start/AuthActivity.codeblock.google.java
source/examples/generated/android/code/start/AuthActivity.codeblock.google.kt
source/includes/steps-install-android.yaml

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/android10.2.0/android/install
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/android10.2.0/android/authenticate#std-label-android-login-google

Updated Android SDK docs to 10.2.0

---

examples/dotnet/Examples/Examples.cs
examples/dotnet/Examples/Examples.csproj
source/dotnet/reference.txt

[No ticket](https://www.youtube.com/watch?v=iHSPf6x1Fdo)
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/dotnetbeta3/dotnet

Upgrade Dotnet SDK docs to beta 3

---

source/mongodb/crud-and-aggregation-apis.txt
source/mongodb/update-documents.txt

(DOCSP-13253): [REALMC] $[] / $[\<identifier\>]
- [CRUD & Aggregation APIs > Array Update Operator Availability](http://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/mongodb/crud-and-aggregation-apis#array-update-operator-availability)
- [Update All Elements in an Array](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/positional/mongodb/update-documents#update-all-elements-in-an-array)
- [Update Specific Elements in an Array](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/positional/mongodb/update-documents#update-specific-elements-in-an-array)

(DOCSP-13253): [REALMC] $[] / $[<identifier>]

---

source/node/quick-start.txt

https://jira.mongodb.org/browse/DOCSP-13658
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/quickfix-node-quickstart-schema/node/quick-start

replaced TaskModel with TaskSchema

---

examples/dotnet/Examples/Relationships.cs
source/dotnet/relationships.txt
source/examples/generated/code/start/Relationships.codeblock.inverse-query.cs
source/examples/generated/code/start/Relationships.codeblock.inverse.cs

https://jira.mongodb.org/browse/DOCSP-13654
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/inverse-query/dotnet/relationships#inverse-relationship

how to query inverse

---

source/includes/task-tracker-web-client-base-file-structure.rst
source/tutorial/realm-app.txt
source/tutorial/web-graphql.txt

(DOCSP-13772): Audit & Update Realm Web Tutorial
- [Task Tracker (Web)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/web-tut/tutorial/web-graphql)
- [Set up the Task Tracker Tutorial Backend](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/web-tut/tutorial/realm-app)

(DOCSP-13772): Audit & Update Realm Web Tutorial

---

examples/ios/Examples/ExampleObjcTestCase.m
examples/ios/Examples/ExampleSwiftTestCase.swift
examples/ios/Examples/QueryEngine.m
examples/ios/Examples/QueryEngine.swift
examples/ios/Examples/ReadWriteData.m
examples/ios/Examples/ReadWriteData.swift
examples/ios/RealmExamples.xcodeproj/project.pbxproj
source/examples/generated/code/start/ExampleSwiftTestCase.swift
source/examples/generated/code/start/QueryEngine.codeblock.aggregate-operators.m
source/examples/generated/code/start/QueryEngine.codeblock.aggregate-operators.swift
source/examples/generated/code/start/QueryEngine.codeblock.setup.swift
source/examples/generated/code/start/ReadWriteData.codeblock.create-a-new-object.m
source/examples/generated/code/start/ReadWriteData.codeblock.create-a-new-object.swift
source/examples/generated/code/start/ReadWriteData.codeblock.find-a-specific-object-by-primary-key.m
source/examples/generated/code/start/ReadWriteData.codeblock.find-a-specific-object-by-primary-key.swift
source/examples/generated/code/start/ReadWriteData.codeblock.models.m
source/examples/generated/code/start/ReadWriteData.codeblock.models.swift
source/examples/generated/code/start/ReadWriteData.codeblock.query-a-relationship.m
source/examples/generated/code/start/ReadWriteData.codeblock.query-a-relationship.swift
source/examples/generated/code/start/ReadWriteData.codeblock.query-an-inverse-relationship.m
source/examples/generated/code/start/ReadWriteData.codeblock.query-an-inverse-relationship.swift

Examples only
Please review output in source/examples/generated/
https://jira.mongodb.org/browse/DOCSP-13324

(DOCSP-13324): Read & Write Data Swift & Obj-C examples

---

source/dotnet/migrations.txt
source/examples/Migrations/LocalMigration/LocalMigration.cs
source/examples/Migrations/PersonClassV1/PersonClassV1.cs
source/examples/Migrations/PersonClassV2/PersonClassV2.cs
source/examples/Migrations/PersonClassV3/PersonClassV3.cs
source/examples/Migrations/PersonClassV4/PersonClassV4.cs

https://jira.mongodb.org/browse/DOCSP-13329
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-13329/dotnet/migrations

DOCSP-13329: Modify an Object Schema (.NET)

---

source/sync/conflict-resolution.txt

https://jira.mongodb.org/browse/DOCSP-13621

(DOCSP-13621): Typo on conflict resolution page

---

examples/dotnet/Examples/AggregationExamples.cs
examples/dotnet/Examples/EmbeddedExamples.cs
examples/dotnet/Examples/Relationships.cs

Dotnet tests were broken. Fixed them.

fixed .NET tests

---

.github/workflows/android.yml
.github/workflows/dotnet-core.yml
.github/workflows/ios.yml
.github/workflows/node.js.yml

Better CI names

---

snooty.toml
source/cloud.txt
source/index.txt
source/sdk.txt
source/stitch.txt

(DOCSP-13816): Update TOC to new SDK/Cloud top-level IA
- [Realm Cloud (/realm/cloud)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/site-split/cloud)
- [Realm SDKs (/realm/sdk)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/site-split/sdk)

(DOCSP-13816): Update TOC to new SDK/Cloud top-level IA

---

config/redirects

DEPM-584: Redirect triggers overview to new triggers overview

---

source/dotnet/access-custom-user-data.txt
source/includes/steps-define-custom-user-data-import-export.yaml
source/includes/steps-define-custom-user-data-realm-ui.yaml
source/includes/user-object-fields.rst

customer -> custom

---

source/android/realms.txt

https://jira.mongodb.org/browse/DOCSP-14072
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14072/android/realms

(DOCSP-14072) Rewrite line to improve clarity

---

source/examples/Migrations/LocalMigration/LocalMigration-add-property.js
source/examples/Migrations/LocalMigration/LocalMigration-delete-property.js
source/examples/Migrations/LocalMigration/LocalMigration-modify-property-type.js
source/sdk.txt
source/sdk/node/examples/modify-an-object-schema.txt

https://jira.mongodb.org/browse/DOCSP-13330
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-13330-modify-an-object-schema/sdk/node/examples/modify-an-object-schema

(DOCSP-13330): modify an object schema

---

source/includes/note-electron-writes-from-both-processes.rst
source/node/electron-cra.txt
source/node/electron.txt

* https://jira.mongodb.org/browse/DOCSP-14132
* Electron: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/links-to-advanced-electron-guide/node/electron
* Electron with React: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/links-to-advanced-electron-guide/node/electron-cra

(DOCSP-14132): add note for electron writes from both processes

---

source/sdk/node/examples/multi-user-applications.txt

https://jira.mongodb.org/browse/DOCSP-14206
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14206-Multi-User-Apps/sdk/node/examples/multi-user-applications

(DOCS-14206): Multi User Applications [Node]

---

source/mongodb/service-limitations.txt
source/sync.txt

https://jira.mongodb.org/browse/DOCSP-14171
https://docs-mongodborg-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14171/
Specifically, I've updated these pages:
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14171/sync
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14171/mongodb/service-limitations
Link to build log confirming I have not introduced any new errors: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6012fc03687cdd451a27c519

(DOCSP-14171) Add best practices and service limitations for Realm Sync

---

source/admin/deployment-models-and-regions.txt

Adds new regions to the list.
https://jira.mongodb.org/browse/DOCSP-13629
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/new-regions/admin/deployment-models-and-regions#cloud-deployment-regions

(DOCSP-13629): Add new deployment regions

---

conf.py
source/android/sync-data.txt
source/cloud.txt
source/dotnet.txt
source/dotnet/reference.txt
source/dotnet/sync-data.txt
source/includes/sync-beta-note.rst
source/index.txt
source/ios/sync-data.txt
source/node/sync-data.txt
source/react-native/sync-data.txt
source/sdk.txt
source/sync.txt
source/sync/configure-your-data-model.txt
source/sync/conflict-resolution.txt
source/sync/enable-development-mode.txt
source/sync/get-started.txt
source/sync/partitioning.txt
source/sync/permissions.txt
source/sync/rules.txt

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/realm-ga/sync

Update for Realm Sync GA + .NET GA

---

examples/ios/Examples/Migrations.m
examples/ios/Examples/Migrations.swift
examples/ios/RealmExamples.xcodeproj/project.pbxproj
source/examples/generated/code/start/Migrations.codeblock.local-migration.m
source/examples/generated/code/start/Migrations.codeblock.local-migration.swift
source/examples/generated/code/start/Migrations.codeblock.model-v1.m
source/examples/generated/code/start/Migrations.codeblock.model-v1.swift
source/examples/generated/code/start/Migrations.codeblock.model-v2.m
source/examples/generated/code/start/Migrations.codeblock.model-v2.swift
source/sdk/ios/examples/modify-an-object-schema.txt

https://jira.mongodb.org/browse/DOCSP-13328
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/migrations/sdk/ios/examples/modify-an-object-schema

Complete Migrations page

---

examples/node/Examples/open-synced-realm.js
source/node/open-a-realm.txt
source/sdk/node/examples/sync-changes-between-devices.txt

https://jira.mongodb.org/browse/DOCSP-13339
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-13339-sync-changes-node/sdk/node/examples/sync-changes-between-devices

(DOCSP-13339): Sync Changes between devices [Node]

---

source/sdk/ios.txt
source/sdk/ios/install.txt
source/sdk/ios/integrations.txt
source/sdk/ios/integrations/swiftui.txt
source/sdk/ios/quick-start.txt

Migrating existing content. Nothing really to review, but please check that the TOC under iOS now looks good.
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/new-ia-ios-toc/sdk/ios

Migrate install and quickstarts

---

source/cloud.txt
source/index.txt
source/sdk.txt

Staged:
Side bar: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/rename-realm/
MongoDB Realm landing page: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/rename-realm/cloud/
SDK landing page: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/rename-realm/sdk/

Rename MongoDB Realm Application Services -> MongoDB Realm

---

source/web/quickstart.txt

(DOCSP-14261): Update Realm-Web Version from CDN Download

(DOCSP-14261): Update Realm-Web Version from CDN Download

---

source/includes/steps-tutorial-backend.yaml

https://jira.mongodb.org/browse/DOCSP-14407
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/update-wording-github-issue-tracker/tutorial/backend/#write-a-comment-when-a-document-is-inserted

(DOCSP-14407): Github Issue Tracker Tutorial - Wording Update 'personal access tokens'

---

examples/android/sync/app/src/main/java/com/mongodb/realm/examples/kotlin/MainActivity.kt

Fix endpoint that pointed at the wrong backend in Android tests

---

source/node/collections.txt
source/node/notifications.txt
source/sdk/node/examples/modify-an-object-schema.txt
source/sdk/node/fundamentals.txt
source/sdk/node/fundamentals/live-queries.txt
source/sdk/node/fundamentals/realms.txt
source/sdk/node/fundamentals/relationships-and-embedded-objects.txt
source/sdk/node/fundamentals/schema-versions-and-migrations.txt
source/sdk/node/fundamentals/write-transactions.txt

https://jira.mongodb.org/browse/DOCSP-13773
- [Realms](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/new-ia-fundamentals/sdk/node/fundamentals/realms/)
- [Live Queries](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/new-ia-fundamentals/sdk/node/fundamentals/live-queries/)
- [Write Transactions](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/new-ia-fundamentals/sdk/node/fundamentals/write-transactions/)
- [Relationships & Embedded Objects](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/new-ia-fundamentals/sdk/node/fundamentals/relationships-and-embedded-objects)
- [Schema Versions & Migrations](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/new-ia-fundamentals/s …

New IA - Fundamentals (Node)

---

source/sdk/ios/fundamentals.txt
source/sdk/ios/fundamentals/query-engine.txt

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/new-ia-ios-query-engine/sdk/ios/fundamentals/query-engine/

Restore query-engine.txt in iOS fundamentals

---

source/examples/generated/code/start/QuickStart.codeblock.complete-swiftui-combine-quick-start.swift
source/sdk/ios.txt
source/sdk/ios/examples.txt
source/sdk/ios/examples/filter-data.txt
source/sdk/ios/fundamentals.txt
source/sdk/ios/swiftui.txt
source/sdk/ios/upgrade-from-stitch-to-realm.txt

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/new-ia-ios-final/sdk/ios/

Yet more iOS new IA

---

.github/workflows/ios.yml
examples/ios/README.md

dubble the ios dubble the reliability dubble your fun

Run iOS CI twice to rule out spurious errors

---

examples/ios/Examples/AnonymouslyLoggedInTestCase.h
examples/ios/Examples/ExampleObjcTestCase.m
examples/ios/Examples/Functions.m
examples/ios/RealmExamples.xcodeproj/project.pbxproj
source/examples/generated/code/start/Functions.codeblock.call-a-function.m
source/sdk/android/data-types/embedded-objects.txt
source/sdk/dotnet/data-types/embedded-objects.txt
source/sdk/ios.txt
source/sdk/ios/data-types.txt
source/sdk/ios/data-types/collections.txt
source/sdk/ios/data-types/embedded-objects.txt
source/sdk/ios/data-types/supported-property-types.txt
source/sdk/ios/examples/call-a-function.txt
source/sdk/ios/examples/define-a-realm-object-model.txt
source/sdk/ios/examples/manage-user-api-keys.txt
source/sdk/ios/integrations.txt

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/new-ia-ios-final/sdk/ios/
- Add Data Types section
- Call a Function in Obj-C
- Link to the jazzy docs for Manage User API Keys

Remaining iOS Checklist

---

source/billing.txt

- Reported by Katherine
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fruit/billing/

Fix typo on Billing page

---

source/includes/steps-graphql-apollo-react-setup.yaml
source/web/graphql-apollo-react.txt

- Updates realm-web to the latest version (1.2.0) in the GraphQL example repo (https://github.com/mongodb-university/realm-graphql-apollo-react/commit/8a2ca7c788bbcaa17618a12f7dbb9dfbc2a7004c) 
- Update the CodeSandbox link to use the GitHub repo as the source of truth
- Mirror a helpful code comment from the GitHub source on this page
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fruit/web/graphql-apollo-react/

🍎  Update GraphQL QuickStart & CodeSandbox

---

source/sdk/ios/advanced-guides.txt
source/sdk/ios/advanced-guides/encrypt.txt
source/sdk/ios/advanced-guides/link-user-identities.txt
source/sdk/ios/examples.txt
source/sdk/ios/examples/connect-to-a-mongodb-realm-backend-app.txt
source/sdk/ios/quick-start.txt
source/sdk/ios/upgrade-from-stitch-to-realm.txt

- Encrypt a Realm
- Link User Identities
- Connect to a MongoDB Realm Backend App
- Fix some more broken refs/links
- 
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/encrypt-ios/sdk/ios/

Re-add more pages for iOS

---

tutorial/rn/package-lock.json
tutorial/rn/package.json

https://jira.mongodb.org/browse/DOCSP-14478
N/A

(DOCSP-14478): update realm (source)

---

source/sdk/android/examples.txt
source/sdk/android/examples/connect-to-mongodb-realm-backend-app.txt
source/sdk/dotnet/examples.txt
source/sdk/dotnet/examples/connect-to-mongodb-realm-backend-app.txt
source/sdk/node/examples.txt
source/sdk/node/examples/connect-to-mongodb-realm-backend-app.txt

https://jira.mongodb.org/browse/DOCSP-14671
* Node: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14671-Connect-to-MongoDB-Realm-Backend-App/sdk/node/examples/connect-to-mongodb-realm-backend-app/
* Android: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14671-Connect-to-MongoDB-Realm-Backend-App/sdk/android/examples/connect-to-mongodb-realm-backend-app/
* .NET: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14671-Connect-to-MongoDB-Realm-Backend-App/sdk/dotnet/examples/connect-to-mongodb-realm-backend-app/

(DOCSP-14671) Connect to MongoDB Realm Backend App

---

source/sdk/android/fundamentals/write-transactions.txt

more information about the transaction

one-transaction-clarification

---

source/sdk/android/examples.txt
source/sdk/dotnet/examples.txt
source/sdk/node/examples.txt

https://jira.mongodb.org/browse/DOCSP-14728
* Node: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/connect-to-realm-backend-order-fix/sdk/node/examples/connect-to-mongodb-realm-backend-app/
* Android: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/connect-to-realm-backend-order-fix/sdk/android/examples/connect-to-mongodb-realm-backend-app/
* .NET: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/connect-to-realm-backend-order-fix/sdk/dotnet/examples/connect-to-a-mongodb-realm-backend-app/

(DOCSP-14728): Connect to a Realm Backend TOC Order Fix

---

config/redirects

redirect updates

---

source/sdk/node/examples/define-a-realm-object-model.txt

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fix-tab-error/sdk/node/examples/define-a-realm-object-model/
compare to current:
https://docs.mongodb.com/realm/sdk/node/examples/define-a-realm-object-model/ (tab headers are removed now)
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=603682e375e817aef7c43283

Fix tab error

---

source/config/data_sources.txt
source/config/sync.txt
source/config/triggers.txt
source/includes/appschema-triggers.rst
source/includes/auth-provider-internal-names.rst
source/includes/trigger-event-ordering.rst
source/includes/trigger-match-expression.rst
source/includes/trigger-project-expression.rst
source/mongodb/connect-over-the-wire-protocol.txt
source/triggers/authentication-triggers.txt
source/triggers/database-triggers.txt
source/triggers/eventbridge.txt
source/triggers/scheduled-triggers.txt

- (DOCSP-14500): [Config Files] Trigger
- (DOCSP-14495): [Config Files] MongoDB Data Source
- (DOCSP-14496): [Config Files] Realm Sync
- [Triggers](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/app-structure/config/triggers/)
- [MongoDB Data Sources](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/app-structure/config/data_sources/)
- [Realm Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/app-structure/config/sync/)

[Round 2] Realm Application Configuration (Feature Branch)

---

.github/pull_request_template.md
REVIEWING.md

https://jira.mongodb.org/browse/DOCSP-14316
https://github.com/nathan-contino-mongo/docs-realm/blob/DOCSP-14316/REVIEWING.md

(DOCSP-14316): Review Guidelines for docs-realm

---

examples/node/Examples/sync-changes-between-devices.js
source/examples/generated/node/sync-changes-between-devices.codeblock.sync-changes-between-devices-check-network-connection.js
source/examples/generated/node/sync-changes-between-devices.codeblock.sync-changes-between-devices-check-upload-and-download-progress.js
source/examples/generated/node/sync-changes-between-devices.codeblock.sync-changes-between-devices-pause-or-resume-sync-session.js
source/sdk/node/examples/sync-changes-between-devices.txt

https://jira.mongodb.org/browse/DOCSP-14354
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14354-sync-changes-js-network-functionality/sdk/node/examples/sync-changes-between-devices/#pause-or-resume-a-sync-session
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6036827375e817aef7c41df3

(DOCSP-14354): sync changes js network functionality

---

source/sdk/android.txt

https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=NNNNNNNNNNNNNNNNNNNNNN

Table for Android Landing Page

---

source/authentication/api-key.txt
source/includes/steps-enable-sync-ui.yaml
source/sdk/ios/examples/sync-changes-between-devices.txt
source/tutorial/realm-app.txt

https://jira.mongodb.org/browse/DOCS-14136
https://jira.mongodb.org/browse/DOCSP-14897
https://jira.mongodb.org/browse/DOCSP-13880
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fruit-day-march-1/
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=603d5e6775e817aef7fcda5d

Small fixes for fruit day (DOCS-14136, DOCSP-14897, DOCSP-13880)

---

tutorial/node-cli/index.js
tutorial/node-cli/package.json
tutorial/node-cli/users.js

https://jira.mongodb.org/browse/DOCSP-13406
N/A
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=NNNNNNNNNNNNNNNNNNNNNN

(DOCSP-13406): upgrade realm for node-cli tutorial

---

source/sdk/android.txt

- staging and evaluating updates based on chats with Realm stakeholders
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/android-landing-page-subsections/sdk/android/
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=603d365075e817aef7f51bcf

Subsection organization for Android SDK landing page

---

source/functions.txt
source/mongodb/actions.txt

https://jira.mongodb.org/browse/DOCS-14076
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fruit/functions/
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=603d71ed75e817aef7008758

Add link to MongoDB Actions from Functions page

---

source/sdk/android.txt

More feedback from Drew and Sumedha
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/sdk-landing-page-round-2/sdk/android/

Additional SDK Landing Page Feedback

---

source/billing.txt

https://jira.mongodb.org/browse/DOCSP-14978
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14978/billing/#realm-requests

(DOCSP-14978): Clarify that Trigger requests billing includes functions called by a trigger

---

source/sdk/node.txt
source/sdk/node/advanced.txt

https://jira.mongodb.org/browse/DOCSP-15006
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/Node-Intro-Install-Description-Fix/sdk/node/#installation
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=603fd25275e817aef76c8455

(DOCSP-15006): Fix node.txt install description

---

examples/dotnet/LocalOnly/Program.cs
source/examples/generated/dotnet/Program.codeblock.subset.cs
source/sdk/dotnet/examples/open-and-close-a-local-realm.txt

https://jira.mongodb.org/browse/DOCSP-14595
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cht_carb/sdk/dotnet/examples/open-and-close-a-local-realm/
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=603fe31875e817aef76fbec1

add class subset info

---

.github/pull_request_template.md

Remove manual staging build link now that we have CI for this

---

examples/android/local/app/src/androidTest/java/com/mongodb/realm/examples/java/RealmObjectVsRealmModelTest.java
examples/android/local/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/RealmObjectVsRealmModelTest.kt
examples/android/local/app/src/main/java/com/mongodb/realm/examples/model/java/FrogRealmModelExample.java
examples/android/local/app/src/main/java/com/mongodb/realm/examples/model/kotlin/FrogRealmModelExampleKt.kt
source/examples/generated/android/local/FrogRealmModelExample.codeblock.complete.java
source/examples/generated/android/local/FrogRealmModelExample.codeblock.complete.java.code-block.rst
source/examples/generated/android/local/FrogRealmModelExampleKt.codeblock.complete.kt
source/examples/generated/android/local/FrogRealmModelExampleKt.codeblock.complete.kt.code-block.rst
source/examples/generated/android/local/RealmObjectVsRealmModelTest.codeblock.realm-object-vs-realm-model.java
source/examples/generated/android/local/RealmObjectVsRealmModelTest.codeblock.realm-object-vs-realm-model.kt
source/examples/generated/android/local/RealmTypesTest.codeblock.dynamic.kt.code-block.rst
source/examples/generated/android/local/RealmTypesTest.codeblock.in-memory.kt.code-block.rst
source/examples/generated/android/local/RealmTypesTest.codeblock.read-only.kt.code-block.rst
source/sdk/android/examples/define-a-realm-object-model.txt

https://jira.mongodb.org/browse/DOCSP-14618
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14618/sdk/android/examples/define-a-realm-object-model/#object-example (two codeblocks and relevant copy in the this section)

(DOCSP-14618): Create Realm Objects by implementing RealmModel - Android

---

source/services/expression-variables.txt

NEQ -> NE operator name fix

---

source/deploy/deploy-cli.txt
source/deploy/export-realm-app.txt
source/functions/define-a-function.txt
source/hosting/configure-file-metadata.txt
source/hosting/enable-hosting.txt
source/hosting/flush-the-cdn-cache.txt
source/hosting/host-a-single-page-application.txt
source/hosting/upload-content-to-realm.txt
source/hosting/use-a-custom-404-page.txt
source/hosting/use-a-custom-domain-name.txt
source/includes/note-procedure-uses-cli-v1.rst
source/includes/steps-upload-external-dependencies.yaml
source/mongodb/define-roles-and-permissions.txt
source/mongodb/enable-wire-protocol-connections.txt
source/mongodb/enforce-a-document-schema.txt
source/mongodb/filter-incoming-queries.txt
source/mongodb/link-a-data-source.txt
source/mongodb/specify-cluster-read-preference.txt
source/reference/cli-auth-with-api-token.txt
source/services/configure/service-rules.txt
source/services/configure/service-webhooks.txt
source/sync/enable-development-mode.txt
source/sync/rules.txt
source/triggers/authentication-triggers.txt
source/triggers/database-triggers.txt
source/triggers/scheduled-triggers.txt
source/users/enable-custom-user-data.txt
source/values-and-secrets/define-a-value.txt

* Opens ``cli`` feature branch pending release
* Adds a note to currently un-updated CLI procedures
- (DOCSP-14988): Add CLI V2 Note on Realm CLI Procedures
- [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli/)

(DOCSP-14988): Add CLI V2 Note on Realm CLI Procedures

---

source/includes/data-lake-rules-note.rst
source/includes/note-procedure-uses-cli-v2.rst
source/includes/steps-enforce-a-document-schema-import-export.yaml
source/mongodb/enforce-a-document-schema.txt

- (DOCSP-14948): [CLI V2] Enforce a Document Schema
- [MongoDB > Enforce a Document Schema (Realm CLI)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli/mongodb/enforce-a-document-schema)

(DOCSP-14948): [CLI V2] Enforce a Document Schema

---

source/functions/upload-external-dependencies.txt
source/includes/steps-define-a-function-import-export.yaml
source/includes/steps-upload-external-dependencies.yaml

https://jira.mongodb.org/browse/DOCSP-14954
https://jira.mongodb.org/browse/DOCSP-14955
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cht_cli/functions/define-a-function/
and
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cht_cli/functions/upload-external-dependencies/

Update "Define a Function" and "External Dependencies"

---

examples/android/local/app/src/androidTest/java/com/mongodb/realm/examples/java/WritesTest.java
examples/android/local/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/WritesTest.kt
source/examples/generated/android/local/WritesTest.codeblock.iterate.java
source/examples/generated/android/local/WritesTest.codeblock.iterate.kt
source/sdk/android/data-types/collections.txt
source/sdk/android/examples/read-and-write-data.txt

https://jira.mongodb.org/browse/DOCSP-14616
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14616/sdk/android/examples/read-and-write-data/#iteration (Iteration section)
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14616/sdk/android/data-types/collections/#iteration (Iteration section)

(DOCSP-14616): Iterations & Snapshots

---

examples/android/local/app/src/androidTest/java/com/mongodb/realm/examples/java/WritesTest.java

Fixing an Android Local example app test that broke during a merge conflict.

---

README.rst

Remove deprecated build instructions

---

examples/node/Examples/define-a-realm-object-schema.js
examples/node/Examples/open-and-close-a-local-realm.js
source/examples/generated/node/define-a-realm-object-schema.codeblock.define-a-realm-object-schema-define-js-classes.js
source/examples/generated/node/define-a-realm-object-schema.codeblock.define-a-realm-object-schema-js-classes-open-and-access-properties.js
source/examples/generated/node/open-and-close-a-local-realm.codeblock.open-local-realm-synchronously.js
source/examples/generated/node/open-and-close-a-local-realm.codeblock.open-local-realm-with-car-schema.js
source/sdk/node/examples/define-a-realm-object-model.txt
source/sdk/react-native/examples/define-a-realm-object-model.txt

https://jira.mongodb.org/browse/DOCSP-14629
* Node: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14629-Document-ES6-Classes/sdk/node/examples/define-a-realm-object-model/#define-realm-object-types-with-javascript-classes
* React Native: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14629-Document-ES6-Classes/sdk/react-native/examples/define-a-realm-object-model/#define-realm-object-types-with-javascript-classes

(DOCSP-14629) Document ES6 Classes

---

examples/android/local/app/src/androidTest/java/com/mongodb/realm/examples/java/WritesTest.java
examples/android/local/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/WritesTest.kt
examples/android/local/app/src/main/java/com/mongodb/realm/examples/model/java/HauntedHouse.java
examples/android/local/app/src/main/java/com/mongodb/realm/examples/model/kotlin/HauntedHouseKt.kt
source/examples/generated/android/local/HauntedHouse.codeblock.complete.java
source/examples/generated/android/local/HauntedHouseKt.codeblock.complete.kt
source/examples/generated/android/local/WritesTest.codeblock.counter-increment-decrement.java
source/examples/generated/android/local/WritesTest.codeblock.counter-increment-decrement.kt
source/examples/generated/android/local/WritesTest.codeblock.counter-set.java
source/examples/generated/android/local/WritesTest.codeblock.counter-set.kt
source/examples/generated/android/local/WritesTest.codeblock.create-an-object-json.kt
source/sdk/android/data-types.txt
source/sdk/android/data-types/counters.txt
source/sdk/android/examples/open-and-close-a-local-realm.txt

https://jira.mongodb.org/browse/DOCSP-14604
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14604/sdk/android/data-types/counters/ (entire page)

(DOCSP-14604): Android SDK Counters

---

source/includes/steps-define-roles-and-permissions-cli.yaml
source/includes/steps-filter-incoming-queries-import-export.yaml
source/mongodb/define-roles-and-permissions.txt
source/mongodb/filter-incoming-queries.txt

- (DOCSP-14949): [CLI V2] Define Roles And Permissions
- (DOCSP-14950): [CLI V2] Filter Incoming Queries
- [Define Roles And Permissions](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli-rules/mongodb/define-roles-and-permissions)
- [Filter Incoming Queries](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli-rules/mongodb/filter-incoming-queries)

[CLI V2] MongoDB Rules Configuration

---

source/authentication/anonymous.txt
source/authentication/api-key.txt
source/authentication/custom-jwt.txt
source/authentication/email-password.txt
source/authentication/facebook.txt
source/authentication/google.txt
source/includes/steps-apple-auth-configure.yaml
source/includes/steps-configure-custom-function-auth-import-export.yaml

- (DOCSP-14937): [CLI V2] Anonymous
- (DOCSP-14938): [CLI V2] Email/Password
- (DOCSP-14939): [CLI V2] Custom JWT
- (DOCSP-14940): [CLI V2] Custom Function
- (DOCSP-14941): [CLI V2] API Key
- (DOCSP-14942): [CLI V2] Facebook
- (DOCSP-14943): [CLI V2] Google
- (DOCSP-14944): [CLI V2] Apple
- [Anonymous](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli-auth/authentication/anonymous/#configuration)
- [Email/Password](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli-auth/authentication/email-password/#configuration)
- [Custom JWT](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli-auth/authentication/custom-jwt/#configuration)
- [Custom Function](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-x …

[CLI V2] Authentication Provider Configuration

---

source/get-started.txt
source/get-started/getting-help.txt

https://jira.mongodb.org/browse/DOCSP-14627
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14627-Getting-Help/get-started/getting-help/

(DOCSP-14627) Getting Help Doc

---

source/sdk/android/fundamentals/realms.txt

https://jira.mongodb.org/browse/DOCSP-14600
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14600/sdk/android/fundamentals/realms/#the-realm-lifecycle (linked section only)

(DOCSP-14600): Realm lifecycle - android sdk

---

source/sdk/android/advanced-guides/threading.txt

https://jira.mongodb.org/browse/DOCSP-14624
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14624/sdk/android/advanced-guides/threading/#intents (just the intents subsection)

(DOCSP-14624): Intents, Android SDK

---

source/authentication/user-objects.txt
source/users/enable-custom-user-data.txt

https://jira.mongodb.org/browse/DOCSP-15124
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fruit/users/enable-custom-user-data/
and
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fruit/authentication/user-objects/

Add .NET Links

---

source/sdk/android/examples/define-a-realm-object-model.txt
source/sdk/android/examples/filter-data.txt
source/sdk/android/fundamentals/object-models-and-schemas.txt
source/sdk/android/fundamentals/query-engine.txt
source/sdk/android/fundamentals/realms.txt

https://jira.mongodb.org/browse/DOCSP-14622
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14622/sdk/android/examples/filter-data/#sort-results (second admonition)
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14622/sdk/android/fundamentals/object-models-and-schemas/#realm-object-limitations (object limitations AND incremental builds)
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14622/sdk/android/fundamentals/query-engine/#string-operators (note)
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14622/sdk/android/fundamentals/realms/#multi-process (multi process section)

(DOCSP-14622): Limitations - Android SDK

---

source/sdk/android/advanced-guides/threading.txt
source/sdk/android/fundamentals/live-queries.txt
source/sdk/android/fundamentals/realms.txt

- Based on Christian's feedback to other realm.io final content rescue tickets.
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/christian_updates/sdk/android/fundamentals/live-queries/#managed-objects (managed objects and unmanaged objects sections)
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/christian_updates/sdk/android/fundamentals/realms/#the-realm-lifecycle (copy updates around the middle of "The Realm Lifecycle" section)

Realm.io final content rescue updates

---

examples/android/local/app/src/androidTest/java/com/mongodb/realm/examples/java/LandingPageTest.java
examples/android/local/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/LandingPageTest.kt
source/examples/generated/android/local/LandingPageTest.codeblock.complete-landing-tests.java
source/examples/generated/android/local/LandingPageTest.codeblock.live-objects.java
source/examples/generated/android/local/LandingPageTest.codeblock.live-objects.kt

Example didn't match comment description. Dachary brought this to my attention just now.
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/dachary_found_a_bug/sdk/android/#always-access-the-latest-data

Fixing small landing page bug

---

source/web.txt

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/web-quick-fix/web/

Update web intro text

---

source/includes/steps-define-sync-rules-cli.yaml
source/sync/rules.txt

https://jira.mongodb.org/browse/DOCSP-14951
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14951-Define-Sync-Rules-CLIV2/sync/rules/

(DOCSP-14951): Define Sync Rules for CLI V2

---

source/admin/api/v3.txt
source/includes/steps-deploy-cli.yaml
source/openapi-admin-v3.yaml
tools/autobuilder/src/index.ts

* Fixes all build warnings/errors
* Removes our single "expected" build error
* Updates the CI to also check for warnings in addition to errors
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/whack-a-mole/deploy/deploy-cli

Build Log Whack-a-Mole

---

source/sdk/ios/examples/open-and-close-a-local-realm.txt

I recently merged this PR, but @nlarew had a good suggestion to wordsmith the tip I added, so I'd like to incorporate that.
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14645-improvement/sdk/ios/examples/open-and-close-a-local-realm/

(DOCSP-14645 improvement): Update the tip to be less redundant.

---

source/sdk/android/advanced-guides/custom-user-data.txt
source/sdk/ios/advanced-guides/custom-user-data.txt
source/sdk/node.txt
source/sdk/react-native.txt

https://jira.mongodb.org/browse/DOP-1883
More wee edits to get rid of redirect chains 😁

(DOP-1883): updates links to JS SDK to use /latest/ & to use correct Compass link

---

examples/ios/Examples/ObjectModels.swift
source/examples/generated/code/start/ObjectModels.codeblock.any-realm-collection.swift
source/examples/generated/code/start/ObjectModels.codeblock.generic-collection.swift
source/sdk/ios/data-types/collections.txt

https://jira.mongodb.org/browse/DOCSP-14637
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/carb2/sdk/ios/data-types/collections/

(DOCSP-14637): Port 'Collections' to Fundamentals

---

source/sdk/dotnet/fundamentals/realms.txt

https://jira.mongodb.org/browse/DOCSP-14590
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/carb/sdk/dotnet/fundamentals/realms/#realm-files

add aux file info

---

source/tutorial/generated/node/config.codeblock.realmAppID.js
source/tutorial/generated/node/index.codeblock.getRealm.js
source/tutorial/generated/node/index.codeblock.openRealm.js
source/tutorial/generated/node/projects.codeblock.getProjects.js
source/tutorial/generated/node/schemas.codeblock.projectSchema.js
source/tutorial/generated/node/schemas.codeblock.taskSchema.js
source/tutorial/generated/node/schemas.codeblock.userSchema.js
source/tutorial/generated/node/tasks.codeblock.createTask.js
source/tutorial/generated/node/tasks.codeblock.deleteTask.js
source/tutorial/generated/node/tasks.codeblock.getTask.js
source/tutorial/generated/node/tasks.codeblock.getTasks.js
source/tutorial/generated/node/tasks.codeblock.modifyTask.js
source/tutorial/generated/node/team.codeblock.addTeamMember.js
source/tutorial/generated/node/team.codeblock.getTeamMembers.js
source/tutorial/generated/node/team.codeblock.removeTeamMember.js
source/tutorial/generated/node/users.codeblock.newRealmApp.js
source/tutorial/generated/node/users.codeblock.userLogin.js
source/tutorial/nodejs-cli.txt
tutorial/node-cli/config.js
tutorial/node-cli/index.js
tutorial/node-cli/main.js
tutorial/node-cli/manageTeam.js
tutorial/node-cli/package-lock.json
tutorial/node-cli/projects.js
tutorial/node-cli/schemas.js
tutorial/node-cli/tasks.js
tutorial/node-cli/team.js
tutorial/node-cli/users.js

- (Re-?)Adds schema instructions
- Move snippets to their own directory to avoid clobbering web/RN files
- Clean up unused code
- Also fix various error messages
https://jira.mongodb.org/browse/DOCS-14313
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/node-fix/tutorial/nodejs-cli/

(DOCS-14313): Update node-cli tutorial

---

source/sdk/ios/examples/react-to-changes.txt
source/sdk/ios/fundamentals/write-transactions.txt

https://jira.mongodb.org/browse/DOCSP-14654
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/carb3/sdk/ios/fundamentals/write-transactions/#interface-driven-writes

(DOCSP-14654): Port interface-driven write text

---

source/includes/steps-tutorial-android-kotlin.yaml
source/includes/steps-tutorial-dotnet.yaml
source/includes/steps-tutorial-ios-swift.yaml
source/includes/steps-tutorial-react-native.yaml
source/tutorial/nodejs-cli.txt
source/tutorial/web-graphql.txt
tools/autobuilder/src/index.ts

Various tutorial clients:
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/tutorial-branch/tutorial/ios-swift/

Update tutorial branch checkout instructions

---

config/redirects

- https://jira.mongodb.org/browse/DOP-1883 (every day I'm redirectin')

Add missing redirect for procedure/create-realm-app

---

source/index.txt
source/realm-legacy.txt

https://jira.mongodb.org/browse/DOCSP-15345
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/realm-legacy/

(DOCSP-15345): Add Realm legacy links

---

source/admin/deployment-models-and-regions.txt
source/authentication/email-password.txt
source/deploy/create-with-cli.txt
source/deploy/deploy-automatically-with-github.txt
source/get-started/create-realm-app.txt
source/get-started/glossary.txt
source/get-started/introduction-backend.txt
source/get-started/introduction-mobile.txt
source/get-started/introduction-web.txt
source/graphql.txt
source/includes/steps-cli-export.yaml
source/includes/steps-define-a-function-import-export.yaml
source/includes/steps-specify-cluster-read-preference-realm-ui.yaml
source/logs.txt
source/logs/changestream.txt
source/mongodb.txt
source/mongodb/link-a-data-source.txt
source/sdk/react-native/examples.txt
source/sync/configure-your-data-model.txt
source/sync/partitioning.txt
source/triggers.txt
source/triggers/database-triggers.txt
source/tutorial/backend.txt

- https://jira.mongodb.org/browse/DOCSP-15290
N/A
- job: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6061e281459c5eddf685a098

(DOCSP-15290): Switch Cloud Referrals to Direct to Realm Referrals

---

source/billing.txt

- https://jira.mongodb.org/browse/DOCSP-15353
- [Billing -> Monthly Free Tier section](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15353/billing/#monthly-free-tier)

(DOCSP-15353): Quick fix: on Billing page, change "organization" to "project"

---

examples/ios/Examples/LandingPageCodeExamples.swift
examples/ios/RealmExamples.xcodeproj/project.pbxproj
source/examples/generated/code/start/LandingPageCodeExamples.codeblock.always-access-the-latest-data.swift
source/examples/generated/code/start/LandingPageCodeExamples.codeblock.coffee-drink-object.swift
source/examples/generated/code/start/LandingPageCodeExamples.codeblock.query.swift
source/examples/generated/code/start/LandingPageCodeExamples.codeblock.update-live-objects.swift
source/examples/generated/code/start/LandingPageCodeExamples.codeblock.watch-for-object-updates.swift
source/examples/generated/code/start/LandingPageCodeExamples.codeblock.write-an-object.swift
source/sdk/ios.txt
source/sdk/ios/advanced-guides.txt

https://jira.mongodb.org/browse/DOCSP-14982
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14982/sdk/ios/
Build log is complaining about errors resolved in #914 , so please disregard build log failure. Log for reference: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=605a10ea2723a9e448e1ffcd

(DOCSP-14982): New Swift SDK landing page

---

source/sdk/ios/advanced-guides/encrypt-a-realm.txt

https://jira.mongodb.org/browse/DOCSP-14635
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14635/sdk/ios/advanced-guides/encrypt-a-realm/

(DOCSP-14635): Incorporate info on encrypted Realms and multiple processes

---

source/sdk/android/examples/modify-an-object-schema.txt

- https://jira.mongodb.org/browse/DOCSP-15324
- [Modify an Object Schema (tip at bottom of Migrations section)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15324/sdk/android/examples/modify-an-object-schema/#migration-functions)

(DOCSP-15324): Delete Realm if Migration Needed tip

---

source/mongodb/watch-documents.txt

- (DOCSP-14681): Document Realm Watch() Resumability Limitation
- [Watch for Document Changes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/watch/mongodb/watch-documents/#use-cases)

(DOCSP-14681): Document Realm Watch() Resumability Limitation

---

source/sdk/android/examples/sync-changes-between-devices.txt
source/sdk/ios/examples/sync-changes-between-devices.txt
source/sdk/node/examples/sync-changes-between-devices.txt
source/sdk/react-native/examples/sync-changes-between-devices.txt

(DOCSP-15304): Fill in working client reset example code snippets
- [Sync Changes Between Devices - iOS SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/client-reset-repo/sdk/ios/examples/sync-changes-between-devices/#reset-a-client-realm-file)
- [Sync Changes Between Devices - React Native SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/client-reset-repo/sdk/react-native/examples/sync-changes-between-devices/#react-native-perform-a-client-reset)
- [Sync Changes Between Devices - Node.js SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/client-reset-repo/sdk/node/examples/sync-changes-between-devices/#node-perform-a-client-reset)
[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING. …

(DOCSP-15304): Fill in working client reset example code snippets

---

examples/ios/Examples/ReadWriteData.m
examples/ios/Examples/ReadWriteData.swift
source/examples/generated/code/start/Encrypt.codeblock.background-app-refresh-encryption.swift
source/examples/generated/code/start/ReadWriteData.codeblock.chain-query.m
source/examples/generated/code/start/ReadWriteData.codeblock.chain-query.swift
source/examples/generated/code/start/ReadWriteData.codeblock.models.swift
source/sdk/ios/data-types/collections.txt
source/sdk/ios/examples/read-and-write-data.txt
source/sdk/ios/fundamentals/live-queries.txt

https://jira.mongodb.org/browse/DOCSP-14646
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/chain-query/sdk/ios/examples/read-and-write-data/#chain-queries

(DOCSP-14646): Port 'chain query' examples

---

source/sdk/ios.txt
source/sdk/ios/additional-examples.txt

- https://jira.mongodb.org/browse/DOCSP-12904
- [Additional Examples - iOS SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-12904-Link-to-supplementary-examples/sdk/ios/additional-examples/)

(DOCSP-12904): Link to Supplementary Examples - iOS SDK

---

examples/ios/Examples/Migrations.m
examples/ios/Examples/Migrations.swift
examples/ios/Examples/ReadWriteData.swift
source/examples/generated/code/start/Migrations.codeblock.rename-property.m
source/examples/generated/code/start/Migrations.codeblock.rename-property.swift
source/examples/generated/code/start/ReadWriteData.codeblock.models.m
source/sdk/ios/examples/modify-an-object-schema.txt
source/sdk/ios/fundamentals/schema-versions-and-migrations.txt

https://jira.mongodb.org/browse/DOCSP-14652
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/carb-migrations/sdk/ios/examples/modify-an-object-schema/

(DOCSP-14652): Update migrations examples

---

source/functions.txt
source/includes/deployment-region-auth-callback-urls.rst
source/includes/run-webhook-as-options.rst
source/includes/steps-graphql-apollo-react-setup.yaml
source/includes/steps-react-web-quickstart.yaml
source/mongodb/actions/collection.bulkWrite.txt
source/services/github.txt
source/services/http.txt
source/services/twilio.txt

- (DOCSP-14214): Add 'Schema Validation' to the list of things that a S… …
- (DOCSP-15347): Add new Realm regions in the Google Auth document
- (DOCSP-13988): Clarify return value for realm collection.BulkWrite
- (DOCSP-15362): Use npm on Typescript Quickstart and update base url
- [Google > Generate OAuth Client Credentials](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/rad/authentication/google/#generate-oauth-client-credentials)
- [collection.bulkWrite() > Return Value](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/rad/mongodb/actions/collection.bulkWrite/#return-value)
- [React Quickstart > Set up a New React App](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/rad/web/react-web-quickstart/#set-up-a-new-reac …

RAD: Small Tweaks and Fixes

---

source/includes/commit-process-diagram.rst
source/sdk/android/advanced-guides/threading.txt
source/sdk/dotnet/advanced-guides/threading.txt
source/sdk/ios/advanced-guides/threading.txt

- https://jira.mongodb.org/browse/DOCSP-15206
Mostly I just revisited the threading page and trimmed, reorganized, and reordered content. So I would just read through the whole page and treat the entire thing as novel content. Unfortunately we haven't really looked at this page as a whole any time recently, so it's about time we took another look at what's working and what isn't.
- [Android SDK - Threading -- edits span entire page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15206/sdk/android/advanced-guides/threading/)

(DOCSP-15206): Android Threading Page Polish

---

source/sdk.txt

Broken link in /sdk.txt

---

source/cloud.txt
source/index.txt
source/sdk.txt
source/sdk/android.txt

- https://jira.mongodb.org/browse/DOCSP-15064
- [Android SDK Landing Page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15064/sdk/android/#get-started)
- [SDK Landing Page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15064/sdk)
- [Realm Landing Page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15064/)
- [App Services Landing Page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15064/cloud)

(DOCSP-15064): Moar tables for landing pages

---

source/sdk/ios/examples/react-to-changes.txt

- https://jira.mongodb.org/browse/DOCSP-14656
- [React to Changes: Key Value Observation section](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14656/sdk/ios/examples/react-to-changes/#key-value-observation)

(DOCSP-14656): iOS: Port content on key-value observing

---

source/sdk/ios/advanced-guides.txt
source/sdk/ios/advanced-guides/bundle-a-realm.txt
source/sdk/ios/advanced-guides/bundle.txt
source/sdk/ios/advanced-guides/compacting.txt
source/sdk/ios/integrations/tvos.txt

https://jira.mongodb.org/browse/DOCSP-14631
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/bundle/sdk/ios/advanced-guides/bundle
Also: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/bundle/sdk/ios/advanced-guides/compacting/#make-a-compacted-copy

(DOCSP-14631): Port bundle a realm

---

source/functions/context.txt
source/services/expression-variables.txt
source/values-and-secrets.txt
source/values-and-secrets/define-environment-values.txt

- (DOCSP-15444): Update context reference with environment
- [context.environment](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/environment-context/functions/context/#context.environment)
- [%%environment](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/environment-context/services/expression-variables/#mongodb-json-expansion---environment)
- [Values & Secrets > Environment Values](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/environment-context/)
- [Define Environment Values](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/environment-context/)

(DOCSP-15444): Update context reference with environment

---

examples/ios/Examples/OpenCloseRealm.swift
examples/ios/Examples/ReadWriteData.m
examples/ios/Examples/ReadWriteData.swift
source/examples/generated/code/start/ReadWriteData.codeblock.json.m
source/examples/generated/code/start/ReadWriteData.codeblock.json.swift
source/functions/context.txt
source/sdk/ios/examples/read-and-write-data.txt

https://jira.mongodb.org/browse/DOCSP-14650
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/carb-json/sdk/ios/examples/read-and-write-data/#create-an-object-with-json

(DOCSP-14650): Port JSON section

---

examples/ios/Examples/ReadWriteData.m
examples/ios/Examples/ReadWriteData.swift
source/examples/generated/code/start/ReadWriteData.codeblock.models.m
source/examples/generated/code/start/ReadWriteData.codeblock.models.swift
source/examples/generated/code/start/ReadWriteData.codeblock.nested-objects.m
source/examples/generated/code/start/ReadWriteData.codeblock.nested-objects.swift
source/sdk/ios/examples/read-and-write-data.txt

https://jira.mongodb.org/browse/DOCSP-14651
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/carb-nested/sdk/ios/examples/read-and-write-data/#initialize-an-object-with-a-value

(DOCSP-14651): Initialize an object by value

---

examples/ios/Examples/ReadWriteData.m
examples/ios/Examples/ReadWriteData.swift
source/examples/generated/code/start/ReadWriteData.codeblock.models.m
source/examples/generated/code/start/ReadWriteData.codeblock.models.swift
source/examples/generated/code/start/ReadWriteData.codeblock.nested-objects.m
source/examples/generated/code/start/ReadWriteData.codeblock.nested-objects.swift
source/sdk/ios/examples/read-and-write-data.txt

Reverts mongodb/docs-realm#975

Revert "(DOCSP-14651): Initialize an object by value"

---

examples/ios/Examples/Threading.swift
source/examples/generated/code/start/Threading.codeblock.pass-across-threads.swift
source/examples/generated/code/start/Threading.codeblock.use-write-async-extension.swift
source/examples/generated/code/start/Threading.codeblock.write-async-extension.swift
source/sdk/ios/advanced-guides/threading.txt

https://jira.mongodb.org/browse/DOCSP-14636
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/threading/sdk/ios/advanced-guides/threading/#pass-instances-across-threads

(DOCSP-14636): Update threading with thread-safe reference docs

---

source/includes/steps-deploy-cli.yaml

- https://jira.mongodb.org/browse/DOCSP-15495
- [Step 1](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15495/deploy/deploy-cli/#log-in-to-mongodb-cloud)

DOCSP-15495 - broken link in deploy cli stepfile

---

examples/ios/Examples/ReadWriteData.m
examples/ios/Examples/ReadWriteData.swift
source/examples/generated/code/start/ReadWriteData.codeblock.partial-update.m
source/examples/generated/code/start/ReadWriteData.codeblock.partial-update.swift
source/sdk/ios/data-types/embedded-objects.txt
source/sdk/ios/examples/define-a-realm-object-model.txt
source/sdk/ios/examples/read-and-write-data.txt
source/sdk/ios/fundamentals/object-models-and-schemas.txt

https://jira.mongodb.org/browse/DOCSP-14638
- [Object Models & Schemas](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/carb-objects/sdk/ios/fundamentals/object-models-and-schemas/#primary-keys)
- [Upsert](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/carb-objects/sdk/ios/examples/read-and-write-data/#upsert-an-object)

(DOCSP-14638): Part 1: updates to object models - primary keys

---

examples/ios/Examples/CompleteQuickStart.swift
source/examples/QuickStarts/CompleteSwiftOutput
source/examples/generated/code/start/CompleteQuickStart.codeblock.authenticate-user.swift
source/examples/generated/code/start/CompleteQuickStart.codeblock.complete-quick-start.swift
source/examples/generated/code/start/CompleteQuickStart.codeblock.create-task.swift
source/examples/generated/code/start/CompleteQuickStart.codeblock.delete.swift
source/examples/generated/code/start/CompleteQuickStart.codeblock.filter.swift
source/examples/generated/code/start/CompleteQuickStart.codeblock.get-all-tasks.swift
source/examples/generated/code/start/CompleteQuickStart.codeblock.import-realm.swift
source/examples/generated/code/start/CompleteQuickStart.codeblock.initialize-app.swift
source/examples/generated/code/start/CompleteQuickStart.codeblock.invalidate-notification-token.swift
source/examples/generated/code/start/CompleteQuickStart.codeblock.logout.swift
source/examples/generated/code/start/CompleteQuickStart.codeblock.model.swift
source/examples/generated/code/start/CompleteQuickStart.codeblock.modify-write-block.swift
source/examples/generated/code/start/CompleteQuickStart.codeblock.open-realm.swift
source/examples/generated/code/start/CompleteQuickStart.codeblock.watch-for-changes.swift
source/sdk/ios/quick-start-with-sync.txt

- https://jira.mongodb.org/browse/DOCSP-14981
- [Quick Start with Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14981/sdk/ios/quick-start-with-sync/)

(DOCSP-14981): [iOS] Bluehawk-ify the Quick Start with Sync code snippets

---

tutorial/web/src/components/LoginScreen.js
tutorial/web/src/graphql/RealmApolloProvider.js

- https://jira.mongodb.org/browse/DOCSP-15467
n/a

(DOCSP-15467): WebGraphQL Tutorial Updates Based on User Feedback 

---

tools/autobuilder/src/index.ts

- This now waits up to 3 minutes for the build to start

Wait longer for build to start

---

source/sdk/ios.txt
source/sdk/ios/install.txt

https://jira.mongodb.org/browse/DOCSP-15694
- [Version Support](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/version-update/sdk/ios/#os-support)
- [Installation > Prerequisites](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/version-update/sdk/ios/install/#prerequisites)

(DOCSP-15694): Update iOS/macOS minimum versions for SPM

---

source/sdk/android/data-types/field-types.txt
source/sdk/android/fundamentals/object-models-and-schemas.txt

- https://jira.mongodb.org/browse/DOCSP-14575
- [Field Types (type lists and new "object ids and uuids" section)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14575/sdk/android/data-types/field-types/)
- [Object Models and Schemas (type lists)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14575/sdk/android/fundamentals/object-models-and-schemas/)

(DOCSP-14575): UUID Data Type - Android SDK

---

source/reference/service-limitations.txt

- https://jira.mongodb.org/browse/DOCSP-15575
- [Atlas Support](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15575/reference/service-limitations/#atlas-support)

(DOCSP-15575): Sync cannot use sharded clusters

---

source/functions/built-in-module-support.txt

- https://jira.mongodb.org/browse/DOCSP-15702
- [Built-In Module Support > Partially Supported Modules > Crypto](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-15702-crypto-not-fully-supported/functions/built-in-module-support/#crypto)

(DOCSP-15702): Crypto is not fully supported

---

source/sdk/ios/fundamentals/object-models-and-schemas.txt

https://jira.mongodb.org/browse/DOCSP-14638
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/inheritance/sdk/ios/fundamentals/object-models-and-schemas/#model-inheritance

(DOCSP-14638): Inheritance guidance on Swift

---

source/sdk/ios/data-types/supported-property-types.txt

- https://jira.mongodb.org/browse/DOCSP-14576
- [Supported Property Types - iOS SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14576/sdk/ios/data-types/supported-property-types/)

(DOCSP-14576): [iOS] Add UUID to Supported Property Types

---

source/functions/built-in-module-support.txt

- https://jira.mongodb.org/browse/DOCSP-15769
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15769-sort-partially-supported-modules/functions/built-in-module-support/#partially-supported-modules

(DOCSP-15769): Sort Partially Supported Modules in Alphabetical Order

---

source/sdk/ios/examples/sync-changes-between-devices.txt

https://jira.mongodb.org/browse/DOCSP-15427
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/log-level/sdk/ios/examples/sync-changes-between-devices/#set-the-client-log-level

(DOCSP-15427): Add log info to logging page

---

source/config/functions.txt

- (DOCSP-15841): [REALMC] Block App Imports that include nested Function Structure
- [Function Configuration Files](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/no-nested-functions/config/functions/)

(DOCSP-15841): [REALMC] Block App Imports that include nested Function Structure (ROLLBACK)

---

source/security.txt

- https://jira.mongodb.org/browse/DOCSP-15856
- [Security - Firewall Configuration](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCS-15856/security/#firewall-configuration)

(DOCSP-15856): Add new IP addresses for to suggested firewall allowlist

---

examples/ios/Examples/Authenticate.swift
examples/ios/Podfile
examples/ios/Podfile.lock
source/examples/generated/code/start/Authenticate.codeblock.facebook.swift

- [Authenticate Users -> Facebook User](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/specify-FBSDK-version/sdk/ios/examples/authenticate-users/#facebook-user)

[iOS]: Specify FBSDK version in Podfile, and list version in code example

---

examples/ios/Examples/Errors.m
examples/ios/Examples/Errors.swift
examples/ios/Examples/TestingAndDebugging.swift
source/examples/generated/code/start/Errors.codeblock.client-reset.m
source/examples/generated/code/start/Errors.codeblock.client-reset.swift
source/examples/generated/code/start/Errors.codeblock.create-error-handler.m
source/examples/generated/code/start/Errors.codeblock.create-error-handler.swift
source/get-started/glossary.txt
source/reference/terminating-and-reenabling-realm-sync.txt
source/sdk/ios/advanced-guides.txt
source/sdk/ios/advanced-guides/client-reset.txt
source/sdk/ios/examples/sync-changes-between-devices.txt
source/sdk/ios/fundamentals/realms.txt
source/sync/errors.txt

https://jira.mongodb.org/browse/DOCSP-14648
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/client-reset/sdk/ios/advanced-guides/client-reset/

(DOCSP-14648): iOS Client Reset

---

source/sdk/ios/advanced-guides/multi-user-applications.txt
source/sdk/node/advanced/multi-user-applications.txt

- https://jira.mongodb.org/browse/DOCSP-15749
- [iOS](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cht-15749/sdk/ios/advanced-guides/multi-user-applications/)
- [Node](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cht-15749/sdk/node/advanced/multi-user-applications/)

add overview info to ios and node multi-user pages

---

examples/ios/Examples/OpenCloseRealm.m
examples/ios/Examples/OpenCloseRealm.swift
source/examples/generated/code/start/Errors.codeblock.create-error-handler.m
source/examples/generated/code/start/Errors.codeblock.create-error-handler.swift
source/examples/generated/code/start/OpenCloseRealm.codeblock.handle-error.m
source/examples/generated/code/start/OpenCloseRealm.codeblock.handle-error.swift
source/sdk/ios/examples/configure-and-open-a-realm.txt

https://jira.mongodb.org/browse/DOCSP-14648
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/error-handling/sdk/ios/examples/configure-and-open-a-realm/

(DOCSP-14648): Error handling

---

source/sdk/dotnet/data-types/field-types.txt

fix format issue

---

examples/ios/Examples/Threading.swift
examples/ios/RealmExamples.xcodeproj/project.pbxproj
source/examples/Threading/Freeze.m
source/examples/generated/code/start/Threading.codeblock.freeze.swift
source/examples/generated/code/start/Threading.codeblock.thaw.swift
source/sdk/ios/advanced-guides/threading.txt

- https://jira.mongodb.org/browse/DOCSP-15555
- [Threading: Frozen Objects](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15555/sdk/ios/advanced-guides/threading/#frozen-objects)

(DOCSP-15555): Add "thaw" to frozen object documentation

---

.github/issue_template.md

Issue template so folks can report issues to us in a consistent way. This is just a first stab -- happy to overhaul this completely if folks have ideas!

Initial issue template

---

conf.py
examples/dotnet/Examples/AggregationExamples.cs
examples/dotnet/Examples/ClientResetExamples.cs
examples/dotnet/Examples/DataTypes.cs
examples/dotnet/Examples/ErrorHandler.cs
examples/dotnet/Examples/Examples.cs
examples/dotnet/Examples/MongoDBExamples.cs
examples/dotnet/Examples/QueryEngineExamples.cs
source/examples/generated/dotnet/DataTypes.codeblock.dictionaries.cs
source/examples/generated/dotnet/DataTypes.codeblock.sets.cs
source/sdk/dotnet/data-types/collections.txt
source/sdk/dotnet/data-types/dictionaries.txt
source/sdk/dotnet/data-types/sets.txt

There are several changes to the source code, which do not need to be reviewed. Please check the note on **source/sdk/dotnet/data-types/collections.txt**, which is the same as on **source/sdk/dotnet/data-types/sets.txt** and **source/sdk/dotnet/data-types/dictionaries.txt**. 
https://jira.mongodb.org/browse/DOCSP-15933
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/data_type_updates/sdk/dotnet/data-types/collections/
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/data_type_updates/sdk/dotnet/data-types/dictionaries/
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/data_type_updates/sdk/dotnet/data-types/sets/

Data type updates

---

examples/android/sync/.idea/gradle.xml
examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/java/MongoDBDataAccessTest.java
examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/MongoDBDataAccessTest.kt
examples/android/sync/app/src/main/java/com/mongodb/realm/examples/model/Plant.kt
examples/android/sync/app/src/main/java/com/mongodb/realm/examples/model/java/Plant.java
source/examples/generated/android/sync/MongoDBDataAccessTest.codeblock.aggregate-documents.java
source/examples/generated/android/sync/MongoDBDataAccessTest.codeblock.aggregate-documents.kt
source/examples/generated/android/sync/MongoDBDataAccessTest.codeblock.example-data.java
source/examples/generated/android/sync/MongoDBDataAccessTest.codeblock.example-data.kt
source/examples/generated/android/sync/MongoDBDataAccessTest.codeblock.find-a-single-document.java
source/examples/generated/android/sync/MongoDBDataAccessTest.codeblock.find-multiple-documents.java
source/examples/generated/android/sync/MongoDBDataAccessTest.codeblock.insert-a-single-document.kt
source/examples/generated/android/sync/MongoDBDataAccessTest.codeblock.insert-multiple-documents.kt
source/examples/generated/android/sync/MongoDBDataAccessTest.codeblock.instantiate-a-mongodb-collection-handle.java
source/examples/generated/android/sync/MongoDBDataAccessTest.codeblock.instantiate-a-mongodb-collection-handle.kt
source/examples/generated/android/sync/MongoDBDataAccessTest.codeblock.watch-documents-with-filter.java
source/examples/generated/android/sync/MongoDBDataAccessTest.codeblock.watch-documents.java
source/examples/generated/android/sync/Plant.codeblock.plant.java
source/examples/generated/android/sync/Plant.codeblock.plant.kt
source/includes/steps-crud-snippets-android.yaml
source/sdk/android/examples/mongodb-remote-access.txt

- https://jira.mongodb.org/browse/DOCSP-15846
- [MongoDB Data Access - all examples, and note in "Instantiate a MongoDB Collection Handle"](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15846/sdk/android/examples/mongodb-remote-access/)

(DOCSP-15846): Add POJO Codec Provider to Android MongoDB Data Access Page

---

source/functions/built-in-module-support.txt

https://jira.mongodb.org/browse/DOCSP-15925
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cht-15925/functions/built-in-module-support/

move http(s) out of full support and into partial

---

source/sdk/node.txt
source/sdk/node/data-types.txt
source/sdk/node/data-types/collections.txt
source/sdk/node/data-types/dictionaries.txt
source/sdk/node/data-types/embedded-objects.txt
source/sdk/node/data-types/field-types.txt
source/sdk/node/data-types/mixed.txt
source/sdk/node/data-types/sets.txt
source/sdk/node/data-types/uuid.txt

New data types node rn

---

source/includes/steps-realm-with-electron-using-create-react-app.yaml
source/sdk/node/integrations/electron-cra.txt

- https://jira.mongodb.org/browse/DOCSP-15916
- [Quick Start with Electron using React](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15916-Electron-CreateReactApp-Fixes/sdk/node/integrations/electron-cra/)

(DOCSP-15916): Electron CRA guide - Added Version Req Note + Remove Broken Dependency 

---

source/sdk/react-native/install.txt

Per realm-docs chat request by Steffen

Update CocoaPods minimum version requirement on RN install page

---

source/includes/custom-data-may-be-stale.rst
source/sdk/ios/advanced-guides/custom-user-data.txt

- https://jira.mongodb.org/browse/DOCSP-15924
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cht-15924/sdk/ios/advanced-guides/custom-user-data/

update info about when a token is auto-refreshed

---

source/sync/errors.txt

Android -> .NET typo fix

---

examples/dotnet/LocalOnly/Program.cs
source/examples/generated/dotnet/Program.codeblock.delete-realm-file.cs
source/sdk/dotnet/fundamentals/realms.txt

- https://jira.mongodb.org/browse/DOCSP-14592
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/14592/sdk/dotnet/fundamentals/realms/#deleting-a-realm-file

Add info about deleting Realm files

---

config/redirects

Quick fix to add missing arrows to redirects, enabling them to build.
- https://jira.mongodb.org/browse/DOCSP-16094

(DOCSP-16094): Add arrow to redirects, add missing trailing slash

---

examples/dotnet/Examples/Examples.cs
examples/dotnet/Examples/Objects.cs
source/examples/generated/dotnet/Objects.codeblock.custom-setter.cs
source/examples/generated/dotnet/Objects.codeblock.ignore.cs
source/sdk/dotnet/examples/define-a-realm-object-model.txt

- https://jira.mongodb.org/browse/DOCSP-14594
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/14594/sdk/dotnet/examples/define-a-realm-object-model/#custom-setters
- 

add custom setter info

---

source/authentication/api-key.txt
source/users/create.txt
source/users/delete-or-revoke.txt
source/users/find-and-view.txt

- (DOCSP-15857): [CLI Example] users create
- (DOCSP-15858): [CLI Example] users list
- (DOCSP-15862): [CLI Example] users delete
- (DOCSP-15859): [CLI Example] users disable
- (DOCSP-15860): [CLI Example] users enable
- (DOCSP-15861): [CLI Example] users revoke
- [Create an Email/Password User](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli/users/create/#manually-create-an-email-password-user)
- [Create a Server API Key](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli/authentication/api-key/#create-a-server-api-key)
- [Find a User](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli/users/find-and-view/#find-a-user)
- [Filter Users](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/c …

CLI V2 Phase 2 (Users)

---

source/config/triggers.txt
source/mongodb/data-sources.txt
source/mongodb/trigger-preimages.txt
source/triggers/database-triggers.txt

- Add screenshots to [View & Disable Trigger Preimages (Beta)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/preimage/mongodb/trigger-preimages) (pending UI)
- (DOCSP-15381): Database Trigger Pre-Images (Beta)
- (DOCSP-15382): Disable Trigger Pre-Images for a Collection
- [Database Triggers > Create a Database Trigger](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/preimage/triggers/database-triggers/#create-a-database-trigger)
- [Config Files > Database Triggers](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/preimage/config/triggers/#config-database-trigger)
- [View & Disable Trigger Preimages (Beta)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/preimage/mongodb/trigger-preimages) …

Database Trigger Preimages (Beta)

---

source/sdk/ios/fundamentals/object-models-and-schemas.txt

- https://jira.mongodb.org/browse/DOCSP-14564
- [Object Models & Schemas](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCS-14487/sdk/ios/fundamentals/object-models-and-schemas/#primary-keys): Updates the last bullet item in Primary Keys

(DOCS-14487): Fix duplicate "a" typo

---

source/sdk/dotnet.txt
source/sdk/dotnet/advanced-guides/threading.txt
source/sdk/dotnet/troubleshooting.txt

https://jira.mongodb.org/browse/DOCSP-14591
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/14591/sdk/dotnet/troubleshooting/

Add Troubleshooting Section to .NET docs

---

source/includes/steps-tutorial-ios-swift.yaml

add link to hyperlink github

---

source/includes/steps-tutorial-android-kotlin.yaml

add hyperlink to kotlin github

---

source/includes/steps-tutorial-dotnet.yaml

add hyperlink to dotnet github

---

source/includes/steps-tutorial-react-native-1.yaml

add hyperlink to RN github

---

source/sdk/dotnet/advanced-guides/threading.txt

https://jira.mongodb.org/browse/DOCSP-14585
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/14585/sdk/dotnet/advanced-guides/threading/

updating thread info

---

source/openapi-admin-v3.yaml

- https://jira.mongodb.org/browse/DOCS-13512
- [API Key APIs -> Delete session](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCS-13512/admin/api/v3/#delete-/auth/session): Change the response type
- [Application-Level APIs -> Create a Realm App](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCS-13512/admin/api/v3/#post-/groups/%7Bgroupid%7D/apps): Add a response body
- [Services APIs -> Get information about underlying Atlas mongod](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCS-13512/admin/api/v3/#get-/groups/%7Bgroupid%7D/apps/%7Bappid%7D/services/%7Bserviceid%7D/commands/build_info): Move this section from Admin APIs
- [Functions APIs -> Execute a …

(DOCS-13512): Fix errors and omissions in Admin API docs

---

source/functions/call-a-function.txt
source/logs.txt
source/logs/cli.txt

- https://jira.mongodb.org/browse/DOCSP-15863
- - https://jira.mongodb.org/browse/DOCSP-15864
- [Call a Function](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli/functions/call-a-function/)
- [View Logs with RealmCLI](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli/logs/cli/)

CLI V2 Phase 2 (Functions & Logs)

---

tutorial/dotnet/realm-tutorial-dotnet/AddMemberPage.xaml.cs
tutorial/dotnet/realm-tutorial-dotnet/App.xaml.cs
tutorial/dotnet/realm-tutorial-dotnet/ProjectPage.xaml.cs

-https://jira.mongodb.org/browse/DOCSP-16259

Add code to warn if user == null but don't require it

---

examples/dotnet/Examples/EmbeddedExamples.cs
source/examples/generated/dotnet/EmbeddedExamples.codeblock.embedded-classes.cs

- https://jira.mongodb.org/browse/DOCSP-15727
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/15727/sdk/dotnet/data-types/embedded-objects/#realm-object-models

remove unneeded props

---

source/sync/protocol.txt

https://jira.mongodb.org/browse/DOCSP-15923
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/delta/sync/protocol/#changeset

(DOCSP-15923): Call out "delta sync"

---

examples/ios/Examples/ReadWriteData.swift

https://jira.mongodb.org/browse/RCOCOA-1282

Temporary fix for Swift CI

---

source/includes/note-beta-feature.rst
source/sdk/android/data-types.txt
source/sdk/android/data-types/realmany.txt
source/sdk/android/data-types/realmdictionary.txt
source/sdk/android/data-types/realmset.txt
source/sdk/dotnet/data-types/dictionaries.txt
source/sdk/dotnet/data-types/field-types.txt
source/sdk/dotnet/data-types/sets.txt
source/sdk/ios/data-types/collections.txt
source/sdk/ios/data-types/supported-property-types.txt
source/sdk/node/data-types/dictionaries.txt
source/sdk/node/data-types/mixed.txt
source/sdk/node/data-types/sets.txt
source/sdk/react-native/data-types/dictionaries.txt
source/sdk/react-native/data-types/mixed.txt
source/sdk/react-native/data-types/sets.txt

- Does UUID need this note??
https://jira.mongodb.org/browse/DOCSP-16378
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/note-beta-data-types/sdk/android/data-types/realmset/
(etc)

(DOCSP-16378): Add 'beta' note to all new data types

---

source/logs.txt
source/logs/function.txt
source/logs/service.txt
source/logs/trigger.txt

https://jira.mongodb.org/browse/DOCSP-15755
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/console-256/logs/#log-lines
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/console-256/logs/trigger/

(DOCSP-15755): Update 256/10 bytes/lines truncation to 512/25

---

source/sdk/ios/data-types/embedded-objects.txt
source/sdk/ios/examples/modify-an-object-schema.txt

https://jira.mongodb.org/browse/DOCSP-14877
- [EmbeddedObjects](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/schema-migrations-embedded/sdk/ios/data-types/embedded-objects/)
- [Modify an Object Schema](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/schema-migrations-embedded/sdk/ios/examples/modify-an-object-schema/#convert-from-object-to-embeddedobject)

(DOCSP-14877): Add more information about migration of embedded objects

---

source/admin/deployment-models-and-regions.txt
source/deploy/create-with-cli.txt
source/includes/steps-cli-create.yaml

- (DOCSP-15870): [CLI Example] apps create
- [Create an App with Realm CLI](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli/deploy/create-with-cli)

(DOCSP-15870): [CLI Example] apps create

---

source/sdk/react-native/data-types/field-types.txt

- Field Types - React Native SDK (https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fixStringLink/)

DOCS-16459 fixed the string link

---

source/triggers.txt

https://jira.mongodb.org/browse/DOCSP-16558
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/16558/triggers/

update rate info to per-trigger

---

Makefile

Added the commands for the Snooty Autobuilder Pushless Staging, per the wiki. Verified this works on my local, and is awesome.

Update Makefile for pushless staging

---

examples/android/local/build.gradle
examples/android/sync/build.gradle
source/includes/steps-install-android.yaml
source/sdk/android/fundamentals/object-models-and-schemas.txt
source/sdk/android/install.txt

- https://jira.mongodb.org/browse/DOCSP-17064
- [Android SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17064/sdk/android)

(DOCSP-17064): Realm Java SDK Version 10.6.0

---

examples/android/local/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/DataTypesTest.kt
source/examples/generated/android/local/DataTypesTest.codeblock.realmset-notifications.kt

Fix broken hide annotation

---

source/sdk/android/data-types/collections.txt

- no jira today, just a typo i noticed as Steward of the Realm

List update: revenge of the forgotten types

---

source/release-notes/changelogs/backend/changelog-backend-2021.rst

- https://jira.mongodb.org/browse/DOCSP-16554
- [Release Notes - 16 June 2021](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16554/release-notes/backend/#16-june-2021-release)

(DOCSP-16554): Realm v20210616 release notes

---

source/examples/Query/Comparison.js

- Query Engine - React Native SDK(https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16535/sdk/react-native/advanced/query-engine/)

Docsp 16535

---

source/includes/note-beta-feature.rst

- https://jira.mongodb.org/browse/DOCSP-17130
- Any page with this include; for example, [the Android `RealmAny` page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17130/sdk/android/data-types/realmany/)

(DOCSP-17130): Update callout to warning and include details about dev mode

---

source/sdk/dotnet/examples/call-a-function.txt

https://jira.mongodb.org/browse/DOCSP-17072
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/17072/sdk/dotnet/examples/call-a-function/

add note about authenticating before calling a function

---

examples/dotnet/Examples/DataTypes.cs
examples/dotnet/Examples/Plant.cs
source/examples/generated/dotnet/DataTypes.codeblock.sets.cs
source/examples/generated/dotnet/Plant.codeblock.plant-class.cs

- Sets: https://jira.mongodb.org/browse/DOCSP-17183
- MongoDB: https://jira.mongodb.org/browse/DOCSP-17073
- [Set types](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/17073/sdk/dotnet/data-types/sets/#set-types)
- [Query MongoDB](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/17073/sdk/dotnet/examples/mongodb-remote-access/#mapping-classes)

Update code snippets to remove inheritance and note about embedded objects

---

source/includes/steps-enable-sync-ui.yaml

- Get Started with Sync(https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/indexPartition/sync/get-started/)

DOCSP-14053 added note about option to index the partition key

---

source/sdk.txt
source/sdk/android.txt
source/sdk/android/fundamentals/async-api.txt

- [Asynchronous API](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/kotlin-sdk-to-ext/sdk/android/fundamentals/async-api/) (links at bottom of page, kotlin extension sidebar link)

Kotlin SDK -> Kotlin Extensions refrole

---

source/sdk/android/fundamentals/object-models-and-schemas.txt

- [Android - Fundamentals - Object Models & Schemas - Relationships (see also)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/multilink-two-separate-lines-see-also/sdk/android/fundamentals/object-models-and-schemas/#relationships)

Fix seealso where all content appeared on one line

---

source/mongodb/document-schemas.txt
source/sync/configure-your-data-model.txt

- https://jira.mongodb.org/browse/DOCSP-16525
- [Document Schemas](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16525/mongodb/document-schemas/)
- [Configure Your Data Model - Property Schema](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16525/sync/configure-your-data-model/#property-schema)

(DOCSP-16525): realm schema definitions for new data types

---

source/examples/Migrations/PersonClassV4/PersonClassV4.java
source/examples/Migrations/PersonClassV4/PersonClassV4.kt

- [Android SDK - Modify an Object Schema](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/typo-fix/sdk/android/examples)

Fix kotlin/java typo

---

source/cloud.txt

- (DOCSP-17248): MongoDB Realm Root Landing Page Update
- [MongoDB Realm Application Services](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/lp-cloud/cloud/)

(DOCSP-17248): MongoDB Realm Root Landing Page Update

---

source/sync.txt
source/sync/get-started.txt

Looking for not only standard review feedback, but also things along the lines of:
- What do we want feature landing pages to look like?
- Is the tone too (in)formal?
- Would an image or two improve things or distract?
- etc.
- https://jira.mongodb.org/browse/DOCSP-16510
- 
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/sync_redux/sync/

Sync redux

---

source/release-notes/changelogs/backend/changelog-backend-2021.rst

- https://jira.mongodb.org/browse/DOCSP-17258
- [Release Notes - 06 30 2021](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17258/release-notes/backend/#june-30-2021-release)

(DOCSP-17258): June 30 2021 Release Notes

---

source/release-notes/changelogs/backend/changelog-backend-2021.rst

Reverts mongodb/docs-realm#1178

Revert "(DOCSP-17258): June 30 2021 Release Notes"

---

examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/java/MongoDBDataAccessTest.java
examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/MongoDBDataAccessTest.kt
source/examples/generated/android/local/OpenARealmTest.codeblock.open-a-realm-local.java
source/examples/generated/android/local/OpenARealmTest.codeblock.open-a-realm-local.kt
source/examples/generated/android/sync/MongoDBDataAccessTest.codeblock.update-a-single-document.java
source/examples/generated/android/sync/MongoDBDataAccessTest.codeblock.update-a-single-document.kt
source/examples/generated/android/sync/MongoDBDataAccessTest.codeblock.update-multiple-documents.java
source/examples/generated/android/sync/MongoDBDataAccessTest.codeblock.update-multiple-documents.kt
source/examples/generated/android/sync/MongoDBDataAccessTest.codeblock.upsert-a-single-document.java
source/examples/generated/android/sync/MongoDBDataAccessTest.codeblock.upsert-a-single-document.kt

- https://jira.mongodb.org/browse/DOCSP-17122
- [Android SDK - Examples - Query MongoDB - Update Single/Update Multiple/Upsert](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17122/sdk/android/examples/mongodb-remote-access/)

(DOCSP-17122):  $set for android sdk update mongodb examples

---

source/sdk/android/troubleshooting.txt

- https://jira.mongodb.org/browse/DOCSP-17280
- [Android SDK - Troubleshooting](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17280/sdk/android/troubleshooting/#configurations-cannot-be-different-if-used-to-open-the-same-file)

(DOCSP-17280): Configuration Equality Check Error -- Android SDK

---

source/sdk/android/examples/react-to-changes.txt
source/sdk/android/troubleshooting.txt

Note for technical reviewer: I'm not 100% sure if this is fixed in SDK version 10.6.0, please correct me if this is wrong.
- https://jira.mongodb.org/browse/DOCSP-16342
- [Android SDK - Examples - React to Changes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16342/sdk/android/examples/react-to-changes/)
- [Android SDK - Troubleshooting](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16342/sdk/android/troubleshooting/#change-listeners-in-android-12-with-sdk-versions-below-10.6.0)

(DOCSP-16342): Change listeners warning, Android 12

---

source/includes/user-object-fields.rst

- [functions - context - user](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/document-one-liner/functions/context/#context.user)

prevent "document" from being split across two lines

---

source/release-notes/changelogs/backend/changelog-backend-2021.rst

- https://jira.mongodb.org/browse/DOCSP-17258
- [Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17258/release-notes/backend/)

(DOCSP-17258): Release Notes, 07/02/2021

---

source/mongodb.txt
source/sdk/dotnet.txt
source/sync.txt
source/sync/errors.txt

https://jira.mongodb.org/browse/DOCSP-13396
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/13396/mongodb/#realm-sync-schema-data-consistency

Add info about unsyncable docs

---

source/tutorial/generated/swift-ios/sync/TasksViewController.codeblock.init.swift
tutorial/swift-ios/Task Tracker/ProjectsViewController.swift
tutorial/swift-ios/Task Tracker/SceneDelegate.swift
tutorial/swift-ios/Task Tracker/TasksViewController.swift
tutorial/swift-ios/Task Tracker/WelcomeViewController.swift

- https://jira.mongodb.org/browse/DOCSP-16429
- [iOS Tutorial](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16429/tutorial/ios-swift/)

(DOCSP-16429): Bluehawk multistate, iOS tutorial revamp

---

examples/dotnet/Examples/WorkWithRealm.cs
source/examples/generated/dotnet/WorkWithRealm.codeblock.object-notifications.cs

- https://jira.mongodb.org/browse/DOCSP-17308
-https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/17308/sdk/dotnet/examples/react-to-changes/#register-an-object-change-listener

update code snippet

---

source/sdk/ios/examples/modify-an-object-schema.txt

- https://jira.mongodb.org/browse/DOCSP-15323
- [Modify an Object Schema](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15323/sdk/ios/examples/modify-an-object-schema/#perform-a-schema-migration): New tip under the "Perform a Schema Migration" section linked here

(DOCSP-15323): [iOS] Add a tip about the deleteRealmIfMigrationNeeded method

---

source/sdk.txt

- (DOCSP-17247): Realm SDKs Root Landing Page Update
- [MongoDB Realm SDKs](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/lp-main/sdk/)

(DOCSP-17247): Realm SDKs Root Landing Page Update

---

source/index.txt

- (DOCSP-17245): MongoDB Realm Root Landing Page Update
- [MongoDB Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/lp-main/)

(DOCSP-17245): MongoDB Realm Root Landing Page Update

---

source/config.txt
source/config/template-expansions.txt
source/deploy/create-with-cli.txt
source/includes/steps-config-expansions.yaml
source/services/expression-variables.txt

- (DOCSP-16003): Work with Environments
- [Create Template Configurations with Expansions](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/config-expansions/config/template-expansions)

(DOCSP-16003): Work with Environments

---

source/triggers/eventbridge.txt

- https://jira.mongodb.org/browse/DOCSP-15121
- [Send Trigger Events to AWS EventBridge](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15121/triggers/eventbridge/#procedure): New Tip under the Procedure heading linked here

(DOCSP-15121): Add note about AWS entry size limit

---

source/sdk/ios/examples/sync-changes-between-devices.txt

- https://jira.mongodb.org/browse/DOCSP-14408
- [Sync Changes Between Devices - iOS SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14408/sdk/ios/examples/sync-changes-between-devices/)

(DOCSP-14408): Reorder sync open and asyncOpen, recommend async in login flow

---

source/sdk/ios/advanced-guides/compacting.txt
source/sdk/ios/fundamentals/realms.txt

- https://jira.mongodb.org/browse/DOCSP-15359
- [Realms: File Size](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15359/sdk/ios/fundamentals/realms/#file-size)
- [Advanced Guides: Compacting](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15359/sdk/ios/advanced-guides/compacting/)

(DOCSP-15359): [iOS] Link file size to compacting, restructure page for fewer grouped directives

---

source/sdk/dotnet.txt

https://jira.mongodb.org/browse/DOCSP-17352
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/17352/sdk/dotnet/

Change in version support for Xamarin.iOS 

---

source/tutorial/generated/swift-ios/local/Models.codeblock.task-model.swift
source/tutorial/generated/swift-ios/sync/Models.codeblock.project-model.swift
source/tutorial/generated/swift-ios/sync/Models.codeblock.task-model.swift
source/tutorial/generated/swift-ios/sync/Models.codeblock.user-model.swift
tutorial/swift-ios/Task Tracker/Models.swift

- https://jira.mongodb.org/browse/DOCSP-17492
- [Tutorial: iOS with Swift](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17492/tutorial/ios-swift/)
- [Define the Object Model](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17492/tutorial/ios-swift/#define-the-object-models): Update code example with `@Persisted` syntax, update `primaryKey` syntax, optimize `ObjectId` for the more performant syntax
- [Update Your App's Realm Models](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17492/tutorial/ios-swift/#define-the-object-models): Update code examples with `@Persisted` syntax, update `primaryKey` syntax, update `List` to `@Persisted` 
Verified that the app builds and runs successfully, both …

(DOCSP-17492): Update tutorial for realm-cocoa 10.10.0 SDK update

---

source/index.txt

- [Main PLP](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/sdk-plp-ref/)

Add Kotlin Multiplatform to main PLP, standardize SDK order

---

source/release-notes/changelogs/backend/changelog-backend-2021.rst

- https://jira.mongodb.org/browse/DOCSP-17499
- [Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17499/release-notes/backend/)

(DOCSP-17499): Mid-July 2021 Release

---

examples/dotnet/Examples/Examples.cs
source/examples/generated/dotnet/Examples.codeblock.pause-synced-realm.cs
source/sdk/dotnet/examples/sync-changes-between-devices.txt

https://jira.mongodb.org/browse/DOCSP-17570
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-17570/sdk/dotnet/examples/sync-changes-between-devices/#pause-or-resume-a-sync-session

Add Pause example for .NET

---

source/includes/extracts-mongodb-action.yaml
source/mongodb/transactions.txt

- https://jira.mongodb.org/browse/DOCSP-17653
- [Parameters of most mongodb action pages](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17653/mongodb/actions/collection.find/#parameters)

(DOCSP-17653): Clarify which actions support session as a parameter

---

examples/ios/Examples/Migrations.swift
source/examples/generated/code/start/Migrations.codeblock.model-v1-updated.swift
source/examples/generated/code/start/Migrations.codeblock.model-v1.swift
source/examples/generated/code/start/Migrations.codeblock.update-schema-version.swift
source/sdk/ios/examples/modify-an-object-schema.txt

- https://jira.mongodb.org/browse/DOCSP-17704
- [Modify an Object Schema](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17704/sdk/ios/examples/modify-an-object-schema/)

(DOCSP-17704): Update iOS migration docs for schema version and add SwiftUI tip

---

source/includes/mongodb-4.4-required-for-sync-admonition.rst
source/tutorial/realm-app.txt

in response to some feedback about 5.0 working for this: https://mongodb.slack.com/archives/CG53S529Y/p1626887374065000
- [Tutorial Backend](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/four-point-four-or-higher/tutorial/realm-app/)

4.4 -> 4.4 or higher

---

source/sdk/android/install.txt
tutorial/kotlin-android/build.gradle

and bump kotlin ext version
- in response to feedback widget
- [Android SDK - Install](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/version-fixes/sdk/android/install/)

Use android SDK version source constant everywhere

---

examples/dotnet/Examples/ErrorHandler.cs
source/examples/generated/dotnet/ErrorHandler.codeblock.customize-logging-function.cs
source/examples/generated/dotnet/ErrorHandler.codeblock.set-log-level.cs
source/sdk/dotnet/examples/sync-changes-between-devices.txt

- https://jira.mongodb.org/browse/DOCSP-14638
- [.NET SDK > Sync Changes Between Devices](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14638-Dotnet-Client-Log-Level-update/sdk/dotnet/examples/sync-changes-between-devices/)

(DOCSP-14638): .NET Log-Level code update

---

.github/workflows/push-to-artifact-repos.yml
tutorial/backend/README.md

- This prevents the CI from failing out due to no usage of state final

Use bluehawk state final in README

---

source/mongodb/data-sources.txt
source/mongodb/trigger-preimages.txt
source/release-notes/changelogs/backend/changelog-backend-2021.rst

- https://jira.mongodb.org/browse/DOCSP-17777
- [Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17777/release-notes/backend/)

(DOCSP-17777): 28 July 2021 Cloud Release

---

source/sdk/ios/data-types/supported-property-types.txt

- [Supported Property Types](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fix-supported-property-types/sdk/ios/data-types/supported-property-types/)

Change monospace to code blocks to improve table layout

---

examples/dotnet/Examples/Writes.cs
source/examples/generated/dotnet/Writes.codeblock.cascade-delete.cs
source/examples/generated/dotnet/Writes.codeblock.create-long-hand.cs
source/examples/generated/dotnet/Writes.codeblock.create.cs
source/examples/generated/dotnet/Writes.codeblock.delete-one.cs
source/examples/generated/dotnet/Writes.codeblock.transaction.cs
source/sdk/dotnet/fundamentals/write-transactions.txt

- https://jira.mongodb.org/browse/DOCSP-17717
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17717/sdk/dotnet/fundamentals/write-transactions/

Add info about other transaction methods

---

source/sdk/ios/examples/filter-data.txt

- https://jira.mongodb.org/browse/DOCSP-18053
- [Filter Data - iOS SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18053/sdk/ios/examples/filter-data/)
- Add Swift syntax and tabs to string operators note
- Correct the beginsWith explanation
- Move error message into a code block in the Important directive to fix truncated line

(DOCSP-18053): [iOS SDK Docs Feedback] Incorporate reader feedback

---

source/index.txt

- https://jira.mongodb.org/browse/DOCSP-17874
- [Realm PLP](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17874/)

(DOCSP-17874): Add Realm SDK link for SDKs card on Realm PLP

---

source/config/triggers.txt
source/triggers/database-triggers.txt

- https://jira.mongodb.org/browse/DOCSP-17919
- [Database Triggers](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17919/triggers/database-triggers/)

(DOCSP-17919): Remove "beta" tag from triggers preimage field

---

source/sdk/android.txt
source/sdk/android/install.txt

- https://jira.mongodb.org/browse/DOCSP-17910
- [Android SDK - Install](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17910/sdk/android/install/)

(DOCSP-17910): Clarify that the Android SDK supports Wear OS

---

source/sync/conflict-resolution.txt

- https://jira.mongodb.org/browse/DOCSP-16512
- [Conflict Resolution](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16512/sync/conflict-resolution/)

Docsp 16512 Conflict resolution edits

---

source/sdk/ios/examples/sync-changes-between-devices.txt

- https://jira.mongodb.org/browse/DOCSP-16245
- [Sync Changes Between Devices](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16245/sdk/ios/examples/sync-changes-between-devices/#open-a-synced-realm-with-swiftui): New section: "Open a Synced Realm with SwiftUI"

(DOCSP-16245): [iOS] SwiftUI AsyncOpen and AutoOpen docs

---

source/release-notes/changelogs/backend/changelog-backend-2021.rst

- https://jira.mongodb.org/browse/DOCSP-18057
- [Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18057-external-changelog-v20210811/release-notes/backend/#11-august-2021-release)

(DOCSP-18057): External Changelog v20210811 ; 11 August 2021 Cloud Release

---

source/sdk/dotnet/fundamentals/object-models-and-schemas.txt

https://jira.mongodb.org/browse/DOCSP-17725
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/binding/sdk/dotnet/fundamentals/object-models-and-schemas/#data-binding-and-mvvm

Data Binding with MVVM

---

examples/node/Examples/rn/using-change-listeners-functional-component.js
source/examples/generated/rn/using-change-listeners-functional-component.codeblock.using-change-listeners-functional-component.js.code-block.rst

- https://jira.mongodb.org/browse/DOCSP-18080
- [Use Change Listeners In Components - React Native SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18080-fix-removeAllListener-broken-snippet/sdk/react-native/examples/use-change-listeners-in-components/)

(DOCSP-18080): fix remove all listener broken snippet

---

source/get-started/glossary.txt
source/sdk/android/advanced-guides/client-reset.txt
source/sdk/android/examples/sync-changes-between-devices.txt
source/sync.txt
source/sync/client-resets.txt
source/sync/errors.txt
source/sync/pause-or-terminate-sync.txt

- (DOCSP-17170): [Concept] Client Reset
- [Client Resets](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/sync-client-reset/sync/client-resets/)

(DOCSP-17170): [Concept] Client Resets

---

source/includes/steps-define-sync-rules-api.yaml
source/includes/steps-define-sync-rules-cli.yaml
source/includes/steps-define-sync-rules-ui.yaml
source/sync/permissions.txt

- (DOCSP-16514): [Concept] Sync Permissions
- [Sync Permissions](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/sync-permissions/sync/permissions/)

(DOCSP-16514): [Concept] Sync Permissions

---

source/hosting/use-a-custom-domain-name.txt

- https://jira.mongodb.org/browse/DOCSP-17932
- [Use a Custom Domain Name](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17932/hosting/use-a-custom-domain-name/)

(DOCSP-17932): Realm AWS CAA clarification

---

source/sync/development-mode.txt

- https://jira.mongodb.org/browse/DOCSP-17933
- [Development Mode - Bypass Rules & Validation](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17933/sync/development-mode/#bypass-rules-and-validation)

(DOCSP-17933): Developer mode permissions editing

---

source/mongodb/bulk-write.txt
source/mongodb/crud-and-aggregation-apis.txt

- https://jira.mongodb.org/browse/DOCSP-18064
- [CRUD & Aggregation APIs - Bulk Write Operations](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18064/mongodb/crud-and-aggregation-apis/#bulk-write-operations)

(DOCSP-18064): Bulk Write is Supported

---

source/examples/QuickStarts/electron/quickstart-setup-react-electron.js
source/sdk/node/integrations/electron-cra.txt

- https://jira.mongodb.org/browse/DOCSP-18246
- [Electron CRA Integration Guide](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/quickfix-electron-cra-contextIsolation/sdk/node/integrations/electron-cra/)

(DOCSP-18246): Electron CRA Integration Guide - Version + Context Isolation fix

---

source/deploy/export-realm-app.txt

- https://jira.mongodb.org/browse/DOCSP-14684
- [Export an Existing Realm Application](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14684/deploy/export-realm-app/)

(DOCSP-14684): Add include-dependencies flag to export documentation

---

source/authentication/anonymous.txt

- https://jira.mongodb.org/browse/DOCSP-18184
- [Anonymous Authentication](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18184/authentication/anonymous/#account-linking): New paragraph at the beginning of the "Account Linking" section

(DOCSP-18184): Add language around anonymous user refreshToken expiration

---

source/sdk/android/advanced-guides.txt
source/sdk/android/advanced-guides/migrations.txt

- https://jira.mongodb.org/browse/DOCSP-18181
- [Android - Migrations](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18181/sdk/android/advanced-guides/migrations/#summary)

(DOCSP-18181): Update misleading Sync Migration documentation

---

source/includes/install-realm-cli-v1.rst
source/includes/install-realm-cli-v2.rst

- https://jira.mongodb.org/browse/DOCSP-18332
- [Realm CLI v2 -> Installation](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18332/cli/#installation)
- [Realm CLI v1 -> Installation](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18332/cli/realm-cli-reference-v1/#installation)

(DOCSP-18332): Update CLI install instructions to specify global install

---

source/sdk/ios/install.txt

- https://jira.mongodb.org/browse/DOCSP-18449
- [iOS - Install (Prerequisites)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18449/sdk/ios/install/#prerequisites)

(DOCSP-18449): Bump Xcode version requirement

---

source/includes/steps-tutorial-dotnet.yaml
tutorial/dotnet/realm-tutorial-dotnet/AddMemberPage.xaml.cs
tutorial/dotnet/realm-tutorial-dotnet/LoginPage.xaml.cs
tutorial/dotnet/realm-tutorial-dotnet/ProjectPage.xaml.cs
tutorial/dotnet/realm-tutorial-dotnet/TaskPage.xaml.cs

- https://jira.mongodb.org/browse/DOCSP-18240
- [.NET (Xamarin) Tutorial](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18240/tutorial/dotnet/)

(DOCSP-18240): Typo fixes, add method names, add code clues in comments

---

examples/ios/Examples/Functions.m
examples/ios/Examples/Functions.swift
source/examples/generated/code/start/Functions.codeblock.call-a-function.m
source/examples/generated/code/start/Functions.codeblock.call-a-function.swift
source/sdk/ios/examples/call-a-function.txt

- https://jira.mongodb.org/browse/DOCSP-18500
- [iOS - Call a Function](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18500/sdk/ios/examples/call-a-function/)

(DOCSP-18500): Show example of calling a function with BSON wrappers

---

source/tutorial/realm-app.txt

https://jira.mongodb.org/browse/DOCSP-18434

(DOCSP-18434): Update 'import' -> 'push' for CLI v2 naming

---

examples/ios/QuickStartSwiftUI/QuickStart.swift
source/examples/generated/swiftui/sync/QuickStart.codeblock.complete-swiftui-combine-quick-start.swift
source/examples/generated/swiftui/sync/QuickStart.codeblock.realm-content-view.swift
source/examples/generated/swiftui/sync/QuickStart.codeblock.sync-content-view.swift
source/sdk/ios/integrations/swiftui.txt

- https://jira.mongodb.org/browse/DOCSP-18501
- Swift UI & Combine: Updated the verbiage in the [Integrate MongoDB Realm and Sync section](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18501/sdk/ios/integrations/swiftui/#integrate-mongodb-realm-and-sync) to go along with the code updates

(DOCSP-18501): Update SwiftUI quickstart to fix logout bug

---

videos/scripts/backend.rst

- https://jira.mongodb.org/browse/DOCSP-18282
This PR is the script that will be read along with the screencast. It will also serve as the CC text for the video, so we want to:
1. Keep it friendly and informal, but
2. Make sure it is readable and serves well as accompanying text.
I've followed the backend tutorial throughout, but if you feel you have the time, go ahead and double-check!
The PR also includes the un-edited screencast videos, which will be spliced and cleaned up (in another ticket).

Video Backend Tutorial

---

source/release-notes/changelogs/backend/changelog-backend-2021.rst

- https://jira.mongodb.org/browse/DOCSP-18526
- [Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18526/release-notes/backend/)

(DOCSP-18526): September 8 2021 Release Notes

---

source/includes/steps-tutorial-ios-swift-local.yaml
source/tutorial/generated/swift-ios/local/ProjectsViewController.codeblock.user-in-realm-notification.swift

- https://jira.mongodb.org/browse/DOCS-14782
- iOS Swift Tutorial: [Specify the Realm to Open](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCS-14782/tutorial/ios-swift/#specify-the-realm-to-open) (New step)

(DOCS-14782): Add missing step

---

examples/ios/Examples/Notifications.swift
examples/ios/Podfile
examples/ios/Podfile.lock
source/examples/generated/code/start/Notifications.codeblock.register-a-keypath-change-listener.swift.code-block.rst
source/examples/generated/code/start/Notifications.codeblock.register-a-partial-keypath-change-listener.swift.code-block.rst
source/sdk/ios/examples/react-to-changes.txt

- https://jira.mongodb.org/browse/DOCSP-18362
- React to Changes: [Observe Partial Key Paths](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18362/sdk/ios/examples/react-to-changes/#observe-partial-key-paths) (New section)

(DOCSP-18362): Add PartialKeyPath for version 10.14.0

---

source/sdk/node/advanced/client-reset.txt

- https://jira.mongodb.org/browse/DOCSP-18516
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/realm-practice-link/sdk/node/advanced/client-reset/

(DOCSP-18516): Add link to realm-practice repo for client reset

---

source/reference/service-limitations.txt
source/release-notes/changelogs/backend/changelog-backend-2021.rst

- https://jira.mongodb.org/browse/DOCSP-18568
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/max-requests/reference/service-limitations/

(DOCSP-18568): Max requests

---

source/reference/service-limitations.txt

- https://jira.mongodb.org/browse/DOCSP-18603
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/atlas-limitations/reference/service-limitations/#time-series-collections

(DOCSP-18603): Add new Atlas limitations

---

source/sdk/android/fundamentals/live-queries.txt

- https://jira.mongodb.org/browse/DOCSP-18256
- [Android - Live Queries](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18256/sdk/android/fundamentals/live-queries/)

(DOCSP-18256): Clarify non-looper thread dangers for android

---

tutorial/kotlin-android/app/build.gradle
tutorial/kotlin-android/build.gradle
tutorial/kotlin-android/gradle/wrapper/gradle-wrapper.properties

- Updated gradle, jdk, dependencies for android tutorial + jcenter note

Android Tutorial Updates

---

source/logs/api.txt

- [Get Paginated Logs](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/log-example/logs/api/#get-paginated-logs)

Add missing variable declaration, tweak example

---

source/includes/note-alpha-sdk.rst
source/includes/note-preview-sdk.rst
source/sdk.txt
source/sdk/flutter.txt
source/sdk/kotlin-multiplatform.txt

- flutter SDK has been upgraded to alpha
- [Flutter SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/flutter-alpha/sdk/flutter/)

Flutter SDK is now in Alpha

---

source/deploy.txt
source/deploy/sdlc.txt

- (DOCSP-16262): Set Up a CI/CD Pipeline (Lauren's Blog)
- [Set Up a CI/CD Pipeline](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/sdlc/deploy/sdlc/)

(DOCSP-16262): Set Up a CI/CD Pipeline

---

examples/dotnet/Examples/QueryEngineExamples.cs
source/examples/generated/dotnet/QueryEngineExamples.codeblock.aggregate.cs
source/examples/generated/dotnet/QueryEngineExamples.codeblock.classes.cs
source/examples/generated/dotnet/QueryEngineExamples.codeblock.comparisons.cs
source/examples/generated/dotnet/QueryEngineExamples.codeblock.strings.cs
source/sdk/dotnet/fundamentals/query-engine.txt

https://jira.mongodb.org/browse/DOCSP-18346
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/18346/sdk/dotnet/fundamentals/query-engine/

Update Query Engine page with new info

---

source/openapi-admin-v3.yaml

- https://jira.mongodb.org/browse/DOCSP-16160
- [Admin API v3 # Security APIs - access_list](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16160-IP-Access-List/admin/api/v3/#security-apis)

(DOCSP-16160):  Admin API Endpoints for IP Access List

---

source/openapi-admin-v3.yaml

This reverts commit d4e3b1f1c68d910f26d507732cf163eb71c4e873.
- [Admin API #Security APIs](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/rollback-ip-access-admin/admin/api/v3/#security-apis)

Revert "(DOCSP-16160):  Admin API Endpoints for IP Access List (#1360)"

---

source/sdk/ios/integrations/swiftui.txt

- https://jira.mongodb.org/browse/DOCSP-18712
- [Swift UI & Combine](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18712/sdk/ios/integrations/swiftui/): New tip just above [Integrate MongoDB Realm and Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18712/sdk/ios/integrations/swiftui/#integrate-mongodb-realm-and-sync) heading.

(DOCSP-18712): [iOS] Add tip about ObservedRealmObject being a frozen object

---

source/mongodb.txt

- https://jira.mongodb.org/browse/DOCSP-18120
- TBD

(DOCSP-18120): Remove note about reviving documents with replace only

---

source/sync.txt
source/sync/production-load-testing.txt

- https://jira.mongodb.org/browse/DOCSP-18612
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/sync-load-testing/sync/production-load-testing/

(DOCSP-18612): Add sync production load testing doc

---

source/functions.txt

- https://jira.mongodb.org/browse/DOCSP-18774
- [Functions # Constraints ](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18774-function-request-timeout/functions/#constraints)

(DOCSP-18774): raised function request timeout from 90s to 120s

---

source/includes/steps-install-swiftpm.yaml

Update Xcode Realm install instructions to match the updated Xcode UI
- https://jira.mongodb.org/browse/DOCSP-18850
- [Install Realm for iOS, macOS, tvOS, and watchOS](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18850/sdk/ios/install/#std-label-ios-install)

(DOCSP-18850): Update Xcode Realm install instructions

---

source/includes/tutorial-request-for-feedback-note.rst

Updated the copy in the Give Feedback note at the bottom of the tutorial pages
- https://jira.mongodb.org/browse/DOCSP-18859
- [iOS tutorial](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18859/tutorial/ios-swift/#what-s-next-)
note that it's the same in the all the other tutorial pages as it's used as a `.. include::` 

(DOCSP-18859): Update give feedback copy

---

source/mongodb/enforce-a-document-schema.txt
source/sync.txt
source/sync/get-started.txt

- (DOCSP-16515): Set Up Sync (Get Started)
- [Sync > Get Started](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/sync-get-started/sync/get-started/)

(DOCSP-16515): Set Up Sync (Get Started)

---

source/tutorial/backend.txt
source/tutorial/realm-app.txt

- https://jira.mongodb.org/browse/DOCSP-18688
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/video_link/tutorial/realm-app/

Add note about tutorial video

---

source/manage-apps/deploy.txt
source/manage-apps/deploy/automated/sdlc.txt
source/manage-apps/deploy/manual.txt
source/manage-apps/deploy/manual/deploy-api.txt

- Added column to deployment methods table to show which methods are automatic/manual
- Added row to describe CI/CD deployment
- Included API Deployment guide from API reference in a page under the manual deployment section
- https://jira.mongodb.org/browse/DOCSP-18593
- [Application Deployment](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18593/manage-apps/deploy/)

(DOCSP-18593): Add info to deployment methods table and add API deploy page

---

source/functions.txt
source/release-notes/changelogs/backend/changelog-backend-2021.rst

- https://jira.mongodb.org/browse/DOCSP-18768
- Link to the IP Access List doc is pending in this ticket: https://jira.mongodb.org/browse/DOCSP-18772
- [Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18768/release-notes/backend/)

(DOCSP-18930): Release Notes, Oct 06 2021

---

source/reference/service-limitations.txt
source/triggers/database-triggers.txt
source/triggers/trigger-types.txt

- Finishing up the Triggers IA redesign epic.
- [Triggers](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/triggers-new-ia-updates/triggers/trigger-types/)

Small updates to triggers documentation based on user feedback

---

source/sdk/android/examples/react-to-changes.txt

- https://jira.mongodb.org/browse/DOCSP-18334
- [React to Changes - Java](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18334/sdk/android/examples/react-to-changes/#register-a-collection-change-listener)

(DOCSP-18334): Mention that listeners ought to maintain an object reference while listening

---

source/includes/steps-tutorial-unity-local.yaml

N/A
- [Unity Tutorial # Update the Stats and Watch for Changes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/quickfix-unity-rst-issue/tutorial/unity/#update-the-stats-and-watch-for-changes)
Broken RST in master: https://docs.mongodb.com/realm/tutorial/unity/#update-the-stats-and-watch-for-change

Unity Tutorial - fix broken rst on step 9

---

source/cloud.txt

- [Realm Application Services](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/lp-fix/)

Fix landing page card link

---

source/graphql/custom-resolvers.txt

- https://jira.mongodb.org/browse/DOCS-14872
- [Custom Query Resolver > Configuration](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fix-agg/graphql/custom-resolvers/#configuration)

(DOCS-14872): Aggregation Pipeline in Custom Resolver Example is buggy

---

examples/dotnet/Examples/DataTypes.cs
source/examples/generated/dotnet/DataTypes.codeblock.query-lists.cs
source/sdk/dotnet/data-types/collections.txt

- https://jira.mongodb.org/browse/DOCSP-19342
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19342-MakeRealmList-Queryable/sdk/dotnet/data-types/collections/#querying-lists

(DOCSP-19342): make realm list queryable .NET

---

examples/android/local/app/src/androidTest/java/com/mongodb/realm/examples/java/DataTypesTest.java
examples/android/local/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/DataTypesTest.kt
examples/android/local/app/src/main/java/com/mongodb/realm/examples/model/java/FrogEnum.java
examples/android/local/app/src/main/java/com/mongodb/realm/examples/model/java/FrogState.java
examples/android/local/app/src/main/java/com/mongodb/realm/examples/model/kotlin/FrogEnumKt.kt
examples/android/local/app/src/main/java/com/mongodb/realm/examples/model/kotlin/FrogStateKt.kt
examples/android/local/build.gradle
source/examples/generated/android/local/DataTypesTest.codeblock.realmenum.java
source/examples/generated/android/local/DataTypesTest.codeblock.realmenum.java.code-block.rst
source/examples/generated/android/local/DataTypesTest.codeblock.realmenum.kt
source/examples/generated/android/local/DataTypesTest.codeblock.realmenum.kt.code-block.rst
source/examples/generated/android/local/FrogEnum.codeblock.complete.java
source/examples/generated/android/local/FrogEnum.codeblock.complete.java.code-block.rst
source/examples/generated/android/local/FrogEnumKt.codeblock.complete.kt
source/examples/generated/android/local/FrogEnumKt.codeblock.complete.kt.code-block.rst
source/examples/generated/android/local/FrogState.codeblock.complete.java
source/examples/generated/android/local/FrogState.codeblock.complete.java.code-block.rst
source/examples/generated/android/local/FrogStateKt.codeblock.complete.kt
source/examples/generated/android/local/FrogStateKt.codeblock.complete.kt.code-block.rst
source/sdk/android/data-types.txt
source/sdk/android/data-types/enums.txt

- https://jira.mongodb.org/browse/DOCSP-17858
- [Android SDK - Enums](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17858/sdk/android/data-types/enums/)

(DOCSP-17858): Realm Java SDK enums

---

examples/node/Examples/data-types.js
source/examples/generated/node/data-types.codeblock.make-array-with-insertion-order-from-set.js
source/examples/generated/node/data-types.codeblock.traverse-a-set.js
source/sdk/node/data-types/sets.txt
source/sdk/react-native/data-types/sets.txt

Update info for traversing sets. Added **Traverse a Set** section. 
- https://jira.mongodb.org/browse/DOCSP-16147
- [Sets (React Native)](https://docs-mongodborg-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16147/sdk/react-native/data-types/sets/)
- [Sets (Node)](https://docs-mongodborg-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16147/sdk/node/data-types/sets/)

(DOCSP-16147): Node/RN - Update traversing set documentation

---

source/web/manage-email-password-users.txt

- https://jira.mongodb.org/browse/DOCSP-16372
- [Web SDK > Manage Email/Password Users # Retry User Confirmation Methods](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16372-retryCustomConfirmation-realmWeb/web/manage-email-password-users/#retry-user-confirmation-methods)

(DOCSP-16372): retry custom confirmation - Web SDK

---

source/get-started/introduction-web.txt
source/logs/function.txt
source/manage-apps/deploy.txt
source/reference/service-limitations.txt
source/triggers.txt
source/triggers/examples/send-events-aws-eventbridge.txt
source/triggers/trigger-types.txt

- [Reference - Service Limitations](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fix-link-leads-to-empty-landing-page/)

Fix link that leads to empty landing page

---

source/includes/steps-install-swiftpm.yaml

- https://jira.mongodb.org/browse/DOCSP-19554
- [Install Realm for iOS, macOS, etc.](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19554/sdk/ios/install/#specify-options): In the SwiftPM tab, step 3, added a `Tip` with the relevant info

(DOCSP-19554): Add tip around SPM with Xcode 13.1

---

source/web/manage-email-password-users.txt

Apply changes from https://github.com/mongodb/docs-realm/pull/1465 to Web SDK
- https://jira.mongodb.org/browse/DOCSP-19667
- [Manage Email/Password Users](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19667/web/manage-email-password-users/)

(DOCSP-19667): Add object arguments to web sdk email/pw auth

---

source/openapi-admin-v3.yaml

- https://jira.mongodb.org/browse/DOCSP-17771

(DOCSP-17771): add schedule trigger support

---

source/rules/examples.txt

- [Rule Examples](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/schemas-and-rules/rules/examples/)

Fix image widths

---

source/get-started/introduction-mobile.txt

- https://jira.mongodb.org/browse/DOCSP-18232
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/include-xamarin-tut/get-started/introduction-mobile/#get-started-with-mongodb-realm

(DOCSP-18232): Include xamarin tutorial in list of mobile tutorials

---

source/services/http-actions/request-authentication.rst

- https://jira.mongodb.org/browse/DOCSP-12836
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/get-action-auth/services/http-actions/http.get/#basic-authentication

(DOCSP-12836): Add context to HTTP auth snippets

---

source/get-started/introduction-web.txt

Edit the web developer introduction page for readability. 
To assess readability used the tools:  
- https://hemingwayapp.com/
- http://readable.com/
Refactored so that it acheived score on Readable of 'B', per [direction in the ticket's epic](https://jira.mongodb.org/browse/DOCSP-19160?focusedCommentId=4175080&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4175080).
- https://jira.mongodb.org/browse/DOCSP-19163
- [Introduction to MongoDB Realm for Web Developers](https://docs-mongodborg-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19163/get-started/introduction-web)

(DOCSP -19163): Refactor Intro for Web Devs for Readability  

---

source/billing.txt
source/release-notes/changelogs/backend/changelog-backend-2021.rst

- https://jira.mongodb.org/browse/DOCSP-19690
- [Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19690/release-notes/backend/)

(DOCSP-19690): Update Changelog for mid-november 2021 Release

---

source/sdk/android/examples/react-to-changes.txt
source/sdk/android/troubleshooting.txt

- Conversations in realm-java-team slack channel
- [Android - React to Changes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/android-12-warning-removal/sdk/android/examples/react-to-changes/)
- [Android - Troubleshooting](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/android-12-warning-removal/sdk/android/troubleshooting/#change-listeners-in-android-12-with-sdk-versions-below-10.5.1)

Remove Android 12 Spooky Warning

---

source/get-started/introduction-mobile.txt

Edit the mobile developer introduction page for readability. 
To assess readability used the tools:  
- https://hemingwayapp.com/
- http://readable.com/
Refactored so that it achieved score on Readable of 'B', per [direction in the ticket's epic](https://jira.mongodb.org/browse/DOCSP-19160?focusedCommentId=4175080&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4175080).
- https://jira.mongodb.org/browse/DOCSP-19162
- [Introduction to MongoDB Realm for Mobile Developers](https://docs-mongodborg-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19162/get-started/introduction-mobile)

(DOCSP-19162): Refactor Intro for Mobile Devs for Readability

---

examples/dotnet/Examples/DataTypes.cs
source/examples/generated/dotnet/DataTypes.codeblock.realmvalue.cs

- typo reported via feedback widget
- [staging](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/dotnet-proeriorty-typo/)

fix .NET SDK typo in "property"

---

source/sdk/ios/data-types/supported-property-types.txt

- https://jira.mongodb.org/browse/DOCSP-19807
- [Supported Property Types](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19807/sdk/ios/data-types/supported-property-types/): New row at bottom of table, note below table.

(DOCSP-19807): [iOS] Add User-defined Object @Persisted syntax details

---

source/web/quickstart.txt

- [Realm Web Quick Start > Install the Web SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cdn/web/quickstart/) (CDN tab)

Update CDN version + how to get the latest version

---

examples/ios/Examples/MongoDBRemoteAccess.swift
source/examples/generated/code/start/MongoDBRemoteAccess.codeblock.async-await-insert.swift
source/examples/generated/code/start/MongoDBRemoteAccess.codeblock.coffee-drink-model.swift
source/examples/generated/code/start/MongoDBRemoteAccess.codeblock.delete-one.swift
source/examples/generated/code/start/MongoDBRemoteAccess.codeblock.insert-many.swift
source/examples/generated/code/start/MongoDBRemoteAccess.codeblock.insert-one.swift
source/examples/generated/code/start/MongoDBRemoteAccess.codeblock.insert-sample-data.swift
source/examples/generated/code/start/MongoDBRemoteAccess.codeblock.update-one.swift
source/examples/generated/code/start/MongoDBRemoteAccess.codeblock.upsert.swift
source/examples/generated/code/start/Notifications.codeblock.alternate-dog-class-for-keypaths.swift
source/examples/generated/code/start/Notifications.codeblock.register-a-keypath-change-listener.swift

- This class isn't really used so it doesn't really matter. The schema is defined manually on the backend.
- Related to DOCSP-19833
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/partition-coffee/sdk/ios/examples/mongodb-remote-access/

Update CoffeeDrink schema to match backend schema

---

source/functions/call-a-function.txt

- [Call a Function > Call from Realm CLI](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli-function-run/functions/call-a-function/#call-from-realm-cli)

Better function CLI examples

---

source/sync/data-access-patterns/partitions.txt

https://jira.mongodb.org/browse/DOCSP-NNNNN](https://jira.mongodb.org/browse/DOCSP-19952
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/19952/sync/data-access-patterns/partitions/#partition-key

Remove Int from list of partition keys

---

source/sync/data-model/sync-schema-overview.txt

- https://jira.mongodb.org/browse/DOCSP-19998
- [Sync Schema Overview](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19998/sync/data-model/sync-schema-overview/#property-schema)

(DOCSP-19998): Update sync schema default to optional

---

source/sync/data-model/migrate-schema-partner-collection.txt

- https://jira.mongodb.org/browse/DOCS-14976
- 

(DOCS-14976): Fix typo

---

examples/dotnet/Examples/BundleARealmExamples.cs
examples/dotnet/Examples/Unity.cs
source/examples/generated/dotnet/BundleARealmExamples.codeblock.extract_and_copy_realm.cs
source/examples/generated/dotnet/Unity.codeblock.read_a_realm_unity.cs
source/sdk/dotnet/advanced-guides/bundle-a-realm.txt

This change adds feedback from Nikola and Nate about other concerns with bundling a synced realm.
- https://jira.mongodb.org/browse/DOCSP-19909
- [[PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/bundledsyncrealm/sdk/dotnet/advanced-guides/bundle-a-realm/)

Bundledsyncrealm

---

source/functions/access-function-context.txt
source/services/configure/services.txt
source/values-and-secrets/define-and-manage-secrets.txt

Added a small section to the Define and Manage Secrets page about accessing the contents of the secret. 
Also created 2 refs to help out w the new content. 
- https://jira.mongodb.org/browse/DOCSP-20027
- [Define and Manage Secrets, Access a Secret section](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20027/values-and-secrets/define-and-manage-secrets/#access-a-secret)

(DOCSP-20027): How to access a secret's value

---

source/sync/data-model/update-schema.txt

- https://jira.mongodb.org/browse/DOCSP-19852
- 

(DOCSP-19852): Clarify additive & destructive around required properties

---

source/endpoints/configure.txt
source/includes/steps-create-an-endpoint-ui.yaml

- [Configure HTTPS Endpoints > Configure Request Validation](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/https-endpoints/endpoints/configure/#configure-request-validation)

Fix table style & switch authz->validation

---

source/get-started/getting-help.txt
source/includes/steps-install-carthage.yaml
source/includes/steps-install-swift-static-framework.yaml
source/includes/steps-install-swiftpm.yaml
source/release-notes/swift.txt
source/sdk/swift.txt
source/sdk/swift/additional-examples.txt
source/sdk/swift/advanced-guides/bundle.txt
source/sdk/swift/examples/modify-an-object-schema.txt
source/sdk/swift/examples/react-to-changes.txt
source/sdk/swift/examples/read-and-write-data.txt
source/sdk/swift/fundamentals/object-models-and-schemas.txt
source/sdk/swift/integrations/tvos.txt

- https://jira.mongodb.org/browse/DOCSP-20140
- [Swift SDK Install page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20140/sdk/swift/install/)
- [Getting Help](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20140/get-started/getting-help/)
- [Swift SDK Changelog](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20140/release-notes/swift/)
- [Additional Examples](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20140/sdk/swift/additional-examples/)
- [Bundle a Realm File with Your App](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20140/sdk/swift/advanced-guides/bundle/)
- [Modify an Object …

(DOCSP-20140): [Swift] Update realm-cocoa references and URLs to realm-swift

---

source/sdk/flutter.txt
source/sdk/flutter/install.txt
source/sdk/flutter/preview-version.txt
source/sdk/flutter/quick-start.txt
source/sdk/flutter/realm-database.txt

Scaffold feature branch for changes to the flutter alpha SDK. having this branch as it is now will organize work for the other tickets in the [Flutter Alpha Epic](https://jira.mongodb.org/browse/DOCSP-19499). even if there are some changes to the pages, having this as the base reference will serve helpful. 
- https://jira.mongodb.org/browse/DOCSP-20217
- N/A

DOCSP-20217: Scaffold Flutter Alpha feature branch

---

source/sdk/flutter/realm-database.txt

Realm Database page. Just an include directive to the main content. same as other SDK pages. 
- https://jira.mongodb.org/browse/DOCSP-20151 
- [Realm Database - Flutter SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20151/sdk/flutter/realm-database/)

(DOCSP-20151): Flutter SDK Realm DB page

---

examples/node/Examples/realm-query-language.js
source/examples/generated/realm-query-language/realm-query-language.codeblock.aggregate-operators.js
source/examples/generated/realm-query-language/realm-query-language.codeblock.comparison-operators.js
source/examples/generated/realm-query-language/realm-query-language.codeblock.logical-operators.js
source/examples/generated/realm-query-language/realm-query-language.codeblock.predicate.js
source/examples/generated/realm-query-language/realm-query-language.codeblock.set-operators.js
source/examples/generated/realm-query-language/realm-query-language.codeblock.sort-distinct-limit.js
source/examples/generated/realm-query-language/realm-query-language.codeblock.string-operators.js
source/examples/generated/realm-query-language/realm-query-language.codeblock.subquery.js
source/reference.txt
source/reference/realm-query-language.txt

- https://jira.mongodb.org/browse/DOCS-14138
- [Realm Query Language](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCS-14138/reference/realm-query-language/): New page, based on iOS NSPredicate page, updated to remove SDK-specific references/examples, provide JSON (BSON) schema, and add SORT/DISTINCT/LIMIT

(DOCS-14138): Add SDK-agnostic Realm Query Language reference

---

source/reference/realm-query-language.txt
source/sync/data-access-patterns/flexible-sync.txt

- https://jira.mongodb.org/browse/DOCSP-19920
- [Realm Query Language](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19920/reference/realm-query-language/#flexible-sync-rql-limitations): This PR adds a section for Flexible Sync RQL Limitations

(DOCSP-19920): Add Flexible Sync RQL Limitations to RQL page

---

source/graphql/expose-data.txt
source/schemas.txt
source/schemas/relationships.txt

- (DOCSP-18468): [Schemas - Guide] Define a Relationship
- (DOCSP-18470): [Schemas - Concept] Relationships
- [Relationships](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/relationships/schemas/relationships/)

(DOCSP-18468,18470): Relationships

---

source/sdk/react-native/install.txt

- https://jira.mongodb.org/browse/DOCSP-20330
- [Install Realm for React Native # Using Realm with Expo](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20330-remove-expo-not-supported-react-native/sdk/react-native/install/)

(DOCSP-20330): expo support for realm RN

---

source/sdk/swift/fundamentals.txt
source/sdk/swift/fundamentals/realm-sync.txt
source/sdk/swift/fundamentals/realms.txt

Note for reviewer: there are some links we can't add until we've got all the pages merged into the feature branch.
- https://jira.mongodb.org/browse/DOCSP-19893
- [Realm Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19893/sdk/swift/fundamentals/realm-sync/)

(DOCSP-19893): SDK Fundamentals Sync page

---

source/sync/data-access-patterns/sync-mode.txt

This PR incorporates tech review comments from the already-merged #1515 
- [Sync Mode](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fs-concept-tech-review/sync/data-access-patterns/sync-mode/)

Flexible Sync Concept Content: Incorporate tech review feedback

---

conf.py
source/includes/note-flutter-local-realm-only.rst
source/includes/steps-install-flutter.yaml
source/sdk/flutter.txt
source/sdk/flutter/install.txt
source/sdk/flutter/preview-version.txt
source/sdk/flutter/quick-start.txt

consolidating changes from 3 in-progress branches into 1 PR b/c the tickets have a high degree of dependency on each other, and it's causing challenges to maintain them in isolation. 
i have noted the remaining work for these in comments that begin `TODO(TICKET-#)`. 
the tickets for these 3 branches are:
1. https://jira.mongodb.org/browse/DOCSP-20150
2. https://jira.mongodb.org/browse/DOCSP-20174
3. https://jira.mongodb.org/browse/DOCSP-20149
upon merge of this PR, i will delete my local branches for these tickets and complete the remaining todos in new branches on top of the changes from this branch. 
to preserve the review process on these tickets, i'll note on the final PR for each of the tickets all the relevant content that should be reviewed, including the changes from *this* PR, …

Flutter alpha rough draft

---

source/includes/note-flexible-sync-prerequisite.txt
source/sync/configure/enable-sync.txt
source/sync/data-access-patterns/flexible-sync.txt
source/sync/data-access-patterns/sync-mode.txt

N/A
- [Define Data Access Patterns > Choose Your Sync Mode](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)
- [Define Data Access Patterns > Flexible Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)
- [Configure Realm Sync > Enable Realm Sync # Enable Flexible Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/query-based-sync-prerequisites/sync/configure/enable-sync/#enable-flexible-sync/)

Quick Improvement - Add Note About Flexible Sync Prerequisites

---

.gitmodules
examples/dart/.gitignore
examples/dart/README.md
examples/dart/analysis_options.yaml
examples/dart/bin/myapp.dart
examples/dart/bin/myapp.g.dart
examples/dart/build.yaml
examples/dart/pubspec.yaml

add current version of the flutter alpha SDK to project as a git submodule. this'll serve as the 'package manager' til flutter sdk provides a better solution.
this *should* work well as a temporary solution as the unit tests should work the same here as in the packaged version. will allow code sample generation and playing with the SDK API. 
n/a
n/a

Flutter alpha packaged

---

source/sdk/flutter.txt

Flutter SDK homepage
- https://jira.mongodb.org/browse/DOCSP-20174
- [Flutter SDK homepage](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20174/sdk/flutter/)

DOCSP-20174: Flutter SDK homepage

---

examples/node/Examples/rn/sign-in-with-google.jsx
source/examples/generated/rn/sign-in-with-google.codeblock.react-native-sign-in-with-google.jsx
source/sdk/react-native/examples/authenticate-users.txt

Update info for google auth for React Native. include a code example. 
- https://jira.mongodb.org/browse/DOCSP-20083
- [Authenticate Users (React Native)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20083/sdk/react-native/examples/authenticate-users/#google-user)

DOCSP-20083: Update React Native Sign in with Google Info

---

source/cloud.txt
source/includes/note-third-party-services-deprecation.rst
source/push-notifications.txt

- request in slack: https://mongodb.slack.com/archives/CJ7QVGULV/p1643129894155700
- [Push Notifications](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/push-notifications-deprecation/push-notifications/)

Deprecate Push Notifications

---

source/includes/steps-cli-create.yaml
source/includes/valid-deployment-regions.rst
source/manage-apps/configure/config/app.txt

- (DOCSP-19386): Realm App Configuration Files location definition.
- [App Config](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/app-location/manage-apps/configure/config/app/)

(DOCSP-19386): Realm App Configuration Files location definition.

---

source/services.txt
source/services/replace-with-npm-modules.txt

- (DOCSP-20103): Replace Services with npm Modules
- [Replace Services with npm Modules](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/services-npm/services/replace-with-npm-modules/)

(DOCSP-20103): Replace Services with npm Modules

---

source/includes/steps-tutorial-react-native-2.yaml

- (DOCS-14951): Typo in RN Tutorial
- [RN Tutorial](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/rn-tut-typo/tutorial/react-native/#open-a-realm)

(DOCS-14951): Typo in RN Tutorial

---

source/sdk/node/examples/flexible-sync.txt

N/A
Addresses: https://github.com/mongodb/docs-realm/pull/1506#discussion_r788105620
- [Flex Sync - Node.js](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/quickfix-address-nicks-js-comments/sdk/node/examples/flexible-sync/)

quickfix - remove 'v' from version number

---

source/release-notes/changelogs/backend/changelog-backend-2022.rst

Note: Schema UI changes are coming in https://github.com/mongodb/docs-realm/pull/1591,
so they won't be visible on this staging site just yet.
- https://jira.mongodb.org/browse/DOCSP-20526
- [Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20526/release-notes/backend/)

January 26 2022 Release Notes

---

source/includes/note-flexible-sync-prerequisite.txt

- https://jira.mongodb.org/browse/DOCSP-15067
- [Configure Realm Sync > Enable Realm Sync # Flexible Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15067-fix-typo-in-fs-preqreqs/sync/configure/enable-sync/#enable-flexible-sync)
- [Define Data Access Patterns > Flexible Sync # Overview ](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15067-fix-typo-in-fs-preqreqs/sync/data-access-patterns/flexible-sync/#overview)
- [Define Data Access Patterns > Choose Your Sync Mode # Flexible Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15067-fix-typo-in-fs-preqreqs/sync/data-access-patterns/sync-mode/#flexible-sync)

(DOCSP-15067): fix typo in FS PreReqs Note, Node.js App -> Realm App

---

source/openapi-admin-v3.yaml

- (DOCSP-16297): [Admin API] Schema Endpoints
- [Admin API > Schema APIs](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/schema-api/admin/api/v3/#tag/schemas)

(DOCSP-16297): [Admin API] Schema Endpoints

---

source/sync/error-handling/client-resets.txt

- https://jira.mongodb.org/browse/DOCSP-20528
- [Client Resets](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20528/sync/error-handling/client-resets/)

(DOCSP-20528): global explanation of client reset strategies

---

source/billing.txt

- (DOCSP-19142): [REALMC] Don't Bill for Requests blocked by the Access List
- [Billing](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/billing/billing/)

(DOCSP-19142): [REALMC] Don't Bill for Requests blocked by the Access List
