mongodb/docs-realm

snooty.toml

Currently `pgp-version` references the `version` variable that was removed in 0db23f4ac6c8dcbe0f664689a4f91d4b3b682861

Remove `pgp-version` from snooty.toml

---

source/by-example/observe-changes.txt
source/crud/notifications.txt
source/examples/Notifications/CollectionNotification.kt
source/examples/Notifications/CollectionNotification.rst
source/examples/Notifications/ObjectNotification.kt
source/examples/Notifications/ObjectNotification.rst
source/examples/Notifications/RealmNotification.kt
source/examples/Notifications/RealmNotification.m
source/examples/Notifications/RealmNotification.rst
source/examples/Notifications/RealmNotification.swift
source/index.txt

- Adds Kotlin examples to the Notifications page.
- Adds "Observe" by example page. Reusing Notifications page examples.
- Putting in place for now and we can rework the divide between manual content
("Notifications") and example content ("By Example") later.
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/observe-by-example/by-example/observe-changes.html
https://jira.mongodb.org/browse/DOCSP-7491
https://jira.mongodb.org/browse/DOCSP-7072

(DOCSP-7491, 7072): Realm by Example: Observe and Kotlin examples

---

source/crud/collections.txt
source/crud/notifications.txt
source/crud/query-engine.txt
source/crud/reads.txt
source/crud/writes.txt
source/data-model/migrations.txt
source/data-model/objects.txt
source/data-model/realms.txt
source/data-model/relationships.txt
source/data-model/threading.txt

- Adds "Summary" section to the bottom of the content pages so far
- Added some missing links, other minor tweaks
https://jira.mongodb.org/browse/DOCSP-8371
Starting on:
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/recaps/data-model/realms.html
And on each page of the "Data Model" and "Read & Write" sections.

(DOCSP-8371): Recaps

---

source/index.txt
source/sync/sync-overview.txt

- Adds the Realm Sync overview page
- Based on various pages from realm.io with a focus on Full Sync.
- Deliberately not a deep dive since the implementation details may change.
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/sync-overview/sync/sync-overview.html
https://jira.mongodb.org/browse/DOCSP-7065

(DOCSP-7065): Sync Overview

---

source/data-model/auxiliary-files.txt
source/data-model/support-files.txt
source/examples/CRUD/Sort.swift
source/index.txt

(DOCSP-7078): Add support files page
- Added under Data Model section, but that may easily change
- Still lacking some info and this may change, so this is a
quick surface-level attempt to get something in place.
- The client reset section may no longer be relevant,
and will most likely move to another page about troubleshooting.
Bonus: PR includes code fix for Swift snippet that got past me earlier
https://jira.mongodb.org/browse/DOCSP-7078
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/realm-files/data-model/support-files.html

(DOCSP-7078): Add support files page

---

conf.py
source/authentication/facebook.txt
source/includes/deployment-region-auth-callback-urls.rst
source/includes/steps-auth-facebook-app-setup.yaml
source/index.txt

- Example SDK snippets cut... for now
- Step files to be replaced
https://jira.mongodb.org/browse/DOCSP-8764
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker/port-fb/authentication/facebook

(DOCSP-8764): Port auth provider: Facebook

---

source/authentication.txt
source/authentication/providers.txt
source/authentication/user-objects.txt
source/includes/user-object-fields.rst
source/index.txt

- Ports Users page
- Moves User Objects to its own page
- Identities and Sessions moved to Authentication & Users overview page
- User Metadata moved to Providers page
- Added summary sections
- Also trying out changing "System users" to singular "THE System user"
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker/users/authentication
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker/users/authentication/user-objects
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker/users/authentication/providers
https://jira.mongodb.org/browse/DOCSP-8768

(DOCSP-8768): User Accounts & Identities

---

source/includes/define-custom-user-data-example.rst
source/includes/steps-define-custom-user-data-import-export.yaml
source/includes/steps-define-custom-user-data-realm-ui.yaml
source/users/define-custom-user-data.txt

_**This is a duplicate/port of https://github.com/10gen/baas-docs/pull/443**_
- [(DOCSP-8042): Access Custom User Data from a Client SDK](https://jira.mongodb.org/browse/DOCSP-8042)
- [Configure Custom User Data](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker/auth-custom-data/users/define-custom-user-data)

(DOCSP-8042): Access Custom User Data from a Client SDK

---

source/hosting/enable-hosting.txt

stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/Fix-Accidental-Stitch-Word-Usage-For-Enable-Hosting/hosting/enable-hosting.html

Fix "Stitch UI" to be "Realm UI" in 'Enable Hosting'

---

source/hosting/flush-the-cdn-cache.txt
source/includes/steps-flush-the-cdn-cache-import-export.yaml
source/includes/steps-flush-the-cdn-cache-realm-ui.yaml
source/index.txt

- [(DOCSP-8928): Port: Flush the CDN Cache](https://jira.mongodb.org/browse/DOCSP-8928)
- [Flush the CDN Cache](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker/hosting-cache/hosting/flush-the-cdn-cache)

(DOCSP-8928): Port: Flush the CDN Cache

---

source/functions/upload-external-dependencies.txt
source/includes/steps-upload-external-dependencies.yaml
source/index.txt

Jira:
----
* https://jira.mongodb.org/browse/DOCSP-8947
Original/Adjacent Stitch Doc:
-----------------------------
* https://docs.mongodb.com/stitch/functions/upload-external-dependencies/
Stage:
------
* https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-8947-Port-Upload-External-Dependencies/functions/upload-external-dependencies.html

(DOCSP-8947): Port - Upload External Dependencies

---

source/functions/json-and-bson.txt
source/functions/utilities.txt
source/includes/shell-generate-an-rsa-key-pair.rst
source/index.txt

- Removes docs for `console`
- Splits `JSON`, `EJSON`, and `BSON` into a new page
- Adds brief context with links to additional resources for each format
- Adds examples for all methods
- This leaves `utils.jwt` and `utils.crypto` on a separate page for easier deprecation
- [(DOCSP-8952): Utility Packages](https://jira.mongodb.org/browse/DOCSP-8952)
- [Utility Packages](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nick/function-utils/functions/utilities.html)
- [JSON & BSON](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nick/function-utils/functions/json-and-bson.html)

(DOCSP-8952): Utility Packages

---

source/deploy/realm-cli-reference.txt
source/includes/steps-cli-create.yaml
source/includes/steps-cli-export.yaml
source/includes/steps-define-a-function-import-export.yaml
source/includes/steps-define-a-service-rule-cli.yaml
source/includes/steps-define-a-value-import-export.yaml
source/includes/steps-define-roles-and-permissions-cli.yaml
source/includes/steps-deploy-cli.yaml
source/includes/steps-enforce-a-document-schema-import-export.yaml
source/includes/steps-filter-incoming-queries-import-export.yaml
source/includes/steps-link-a-cluster-import-export.yaml

Changes in this PR:
--------------------
* Unified `realm-cli login` code snippets (sometimes the current snippets were using the old Username method and sometimes the current snippets did not have `<>` brackets)
* Unified `realm-cli login` code snippets to the following:
```
realm-cli login --api-key="<my api key>" --private-api-key="<my private api key>"
```
JIRA:
-----
* None

Unified `realm-cli login` Syntax

---

source/includes/define-custom-user-data-example.rst

Continuation of [this](https://jira.mongodb.org/browse/DOCSP-9610)

(DOCSP-9610) - removes incorrect object key `profile`

---

source/openapi-admin-v3.yaml

JIRA:
-----
* https://jira.mongodb.org/browse/DOCSP-8811
Stage:
------
* https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-8811-resume-triggers/admin/api/v3.html#put-/groups/{groupid}/apps/{appid}/triggers/{triggerid}/resume

(DOCSP-8811): Added 'empty object' needed for resume trigger api

---

source/includes/steps-enforce-a-document-schema-realm-ui.yaml

_**Port of https://github.com/10gen/baas-docs/pull/465**_

(DOCSP-9648): Array items should be an object schema

---

source/crud/query-engine.txt
source/crud/reads.txt
source/crud/writes.txt
source/data-model/objects.txt

- Rewrote intro. Original intro was better suited for Threading page (where the same idea is repeated).
- Reordered the sections to cover how to read first then "advanced" knowledge later.
Staged:
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/touchups2/crud/reads.html

Touch up Reads page

---

source/services/expression-variables.txt

[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker/DOCSP-9795/)
I can't direct link to it for some reason, it's on the Expression variables page.
This is the other 1/2 of [9795](https://jira.mongodb.org/browse/DOCSP-9795)

(DOCSP-9795) - add custom_data info

---

source/graphql.txt

[Version requirement note](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-9836/graphql)
[Transaction mention in mutations into paragraph](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-9836/graphql#mutations)

(DOCSP-9836): add version note and transaction mention for graphql

---

source/includes/steps-define-roles-and-permissions-cli.yaml

Adds missing fields to example definition file and instructs user what to set them to.

(DOCSP-9818): add missing fields

---

source/android.txt
source/client-sdk-key-concepts.txt
source/index.txt
source/ios.txt
source/mongodb-realm.txt
source/web.txt

- Adds "key concepts" section
- Rearranges MongoDB Realm section in a way that makes sense from a user journey perspective
(comments welcome)
Oldgen stage:
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/alpha-toc/index.html
Nextgen stage:
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/alpha-toc/

Rearrange TOC for Alpha release

---

source/includes/steps-admin-api-deploy-a-draft.yaml

Based on [JIRA](https://jira.mongodb.org/browse/DOCSP-10039) it looks like Stitch/Realm now enforces a content-type for this route.

(DOCSP-10039) - adds missing header info

---

source/authentication/email-password.txt
source/functions/json-and-bson.txt
source/openapi-admin-v3.yaml

_**Port of: https://github.com/10gen/baas-docs/pull/475**_
- [(DOCSP-9838): Missing Configuration File Options for Email/Password Auth](https://jira.mongodb.org/browse/DOCSP-9838)
- [(DOCSP-9847): BSON.Binary.fromBase64() does not support unpadded strings](https://jira.mongodb.org/browse/DOCSP-9847)
- [(DOCSP-9846): Document AWS EventBridge Triggers in Admin API](https://jira.mongodb.org/browse/DOCSP-9846)
- [Email/Password Authentication](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/fixes/authentication/email-password.html#configuration)
- [BSON.Binary.fromBase64()](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/fixes/functions/json-and-bson.html#BSON.Binary.fromBase64)
- [Create a Trigger (Admin API)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/ …

(DOCSP-9838,9847,9846): Quick Wins

---

source/mongodb/crud-and-aggregation-apis.txt
source/mongodb/service-limitations.txt
source/mongodb/supported-aggregation-stages.rst

In response to several tickets about inconsistent support for ops.
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-10218/)

clarify limitations

---

source/authentication/user-objects.txt
source/get-started/introduction-mobile.txt

This PR addresses both
[Correct ORM Link Staged](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/nl-10435-10437/get-started/introduction-mobile#summary)
[Link to user creation instead of user creation overview](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/nl-10435-10437/authentication/user-objects#summary)

incorporate suggestions from product

---

source/includes/extracts-mongodb-action.yaml

**Port of https://github.com/10gen/baas-docs/pull/485**
- [(DOCSP-10103): Descending sort uses -1, not 0](https://jira.mongodb.org/browse/DOCSP-10103)
- [(HELP-16003): Stitch Docs Decending Sort Operator](https://jira.mongodb.org/browse/HELP-16003)

(DOCSP-10103): Descending sort uses -1, not 0

---

source/authentication.txt
source/index.txt

This fixes the sidebar so that Auth Providers overview and providers section are together.
https://jira.mongodb.org/browse/DOCSP-10340
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/auth-providers-toc/authentication.html

Move Users & Authentication TOC to authentication.txt

---

source/node.txt
source/react-native.txt

- The Node.js and RN SDKs are the same. However, the documentation is different
in case we want more RN-specific code examples. This commit clarifies the note
that previously implied the two SDKs were not the same.
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/rn-text-update/node.html

Clarify note about Node.js/RN incompatibility

---

source/index.txt

- .NET is not available for .live, so we are temporarily removing it from the TOC.
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/intro/index.html

Rework landing page and TOC, remove .NET

---

source/android/install.txt
source/includes/steps-install-android.yaml
source/includes/steps-install-cocoapods.yaml
source/includes/steps-install-node.yaml
source/includes/steps-install-react-native-pre-v60.yaml
source/includes/steps-install-react-native-v60-plus.yaml
source/ios/install.txt

- Updates install pages to latest version
- Hides carthage & dynamic framework install tabs on iOS. Can be re-added later.
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/install/android/install.html

Update Install pages to latest version

---

source/authentication.txt
source/index.txt
source/mongodb.txt
source/mongodb/actions.txt
source/mongodb/crud-snippets.txt
source/web.txt

- Removes MongoDB pages from Web SDK
- Adds subsections to break up the MongoDB section
- Removes "late dropping" features like multi user, user linking
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/toc-cleanup/index.html)

TOC Cleanup

---

source/ios.txt

See sidebar https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/ios-sdk-links/ios.html

Add iOS SDK reference manuals to TOC

---

source/index.txt

- Tooling does not support having an uncategorized item (?) so I made a collection of items including the old SDK docs.
- Including repeated use of "Legacy" and "Stitch" to avoid having someone accidentally think this is the current SDK.
https://jira.mongodb.org/browse/DOCSP-10848
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/stitch-legacy/index.html

(DOCSP-10848): Add link to legacy Stitch docs on left-hand nav

---

source/deploy.txt
source/index.txt
source/logs.txt

**Jira:** [(DOCSP-10805): Clean up Application Management toctree](https://jira.mongodb.org/browse/DOCSP-10805)
- Adds **Logs** as a top level section
- Moves some pages between reference/deployment and various cloud sections
- Application Management -> Application Deployment
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/cleanup/index.html)

(DOCSP-10805): Clean up Application Management toctree

---

source/authentication/apple.txt
source/graphql/authenticate.txt
source/graphql/expose-data.txt
source/hosting/includes/metadata-config-json.rst

- Removes the **Set Up Your Client Application** procedure from [Apple ID Authentication](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/stitch/authentication/apple.html) that used old Stitch code
- Switch Stitch -> Realm in a GraphQL examples & hosting reference docs

Stitch -> Realm, Hide Stitch SDK code

---

source/android/objects.txt
source/dotnet/objects.txt
source/node/include/property-schema.rst
source/node/objects.txt
source/react-native/objects.txt

- Update Node + RN guides with proper syntax for defining properties
- Remove various instances of "given programming language", "client-specific...", etc.
- Add 'ObjectId' to supported types
https://jira.mongodb.org/browse/DOCSP-10796
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/language-specific/node/objects.html

(DOCSP-10796): Remove 'language specific' type verbiage in client guides

---

source/openapi-admin-v3.yaml

- Returned dates are actually RFC 3339
- Mem usage not returned in group result
- App ID and app name are returned in app result
- MILLIS unit removed
https://jira.mongodb.org/browse/DOCSP-10587
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/measurements/admin/api/v3.html#billing-apis

(DOCSP-10587): Update measurements endpoint docs

---

source/android/quick-start.txt
source/ios/quick-start.txt
source/react-native/quick-start.txt
source/tutorial/android-kotlin.txt
source/tutorial/ios-swift.txt
source/tutorial/react-native.txt
source/tutorial/web-graphql.txt
source/web/quickstart.txt

- [(DOCSP-10822): Add bidirectional links between quick starts and tutorials](https://jira.mongodb.org/browse/DOCSP-10822)
- [Web Tutorial](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/gs/tutorial/web-graphql.html)
- [iOS Tutorial](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/gs/tutorial/ios-swift.html)
- [Android Tutorial](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/gs/tutorial/android-kotlin.html)
- [React Native Tutorial](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/gs/tutorial/react-native.html)
- [Web Quick Start](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/gs/web/quickstart.html)
- [iOS Quick Start](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/gs/ios/quick-start.html)
- [Android …

(DOCSP-10822): Add bidirectional links between quick starts and tutorials

---

source/android/quick-start.txt
source/includes/steps-install-android.yaml
source/includes/steps-tutorial-android-kotlin.yaml

Description:
- split the app-level gradle build file into java/kotlin examples since there are significant differences
- updated the tutorial and installation pages to use Android beta 5
- condensed a confusing aside/runon sentence into a link to the partitioning doc
- various QOL improvements with highlighted lines in examples, some of which were broken
- callouts in the android quickstart for users who *may* have *accidentally* skipped parts or all of the installation page
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/InstallationAndQuickStartImprovements/android/quick-start.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/InstallationAndQuickStartImprovements/android/install.html

improved installation and quickstart instructions

---

conf.py
source/includes/steps-apple-auth-configure.yaml

- [(DOCSP-10952): Add gem install jwt to Apple auth guide](https://jira.mongodb.org/browse/DOCSP-10952)
- [4. Create the Client Secret JWT](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/gem/authentication/apple.html#create-the-client-secret-jwt)

(DOCSP-10952): Add gem install jwt to Apple auth guide

---

source/deploy.txt
source/deploy/deploy-automatically-with-github.txt
source/includes/steps-github-deploy.yaml

- [(DOCSP-10281): Ability to point Code Deployment to a Directory](https://jira.mongodb.org/browse/DOCSP-10281)
- [(DOCSP-10282): Support Branch Selection for Code Deployment](https://jira.mongodb.org/browse/DOCSP-10282)
- [Deployment Overview](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/deploy/deploy.html)
- [Deploy Automatically with GitHub](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/deploy/deploy/deploy-automatically-with-github.html)

(DOCSP-10281,10282): Code Deploy supports branch & directory

---

source/node/authenticate.txt
source/react-native/authenticate.txt
source/web/authenticate.txt

- DOCSP-11177
In this PR the updates to both pages are more or less direct copies - the only difference is web/node in the anchors.
- [Node: Authenticate a User](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/auth/node/authenticate.html#node-login-api-key)
- [Web: Authenticate a User](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/auth/web/authenticate.html#web-login-api-key)
_**Edit:**_ Forgot to include the RN guide initially, but it's also just a copy with updated refs
- [RN: Authenticate a User](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/auth/react-native/authenticate.html#react-native-login-api-key)

(DOCSP-11177): Add non-OAuth providers to JS Authentication Guides

---

source/includes/steps-install-node-iot.yaml
source/node/install.txt

JIRA: https://jira.mongodb.org/browse/DOCSP-10023
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-10023iot/node/install.html#iot-installation
We could also look into creating a separate tab for the IoT SDK, but since it doesn't deviate anywhere else I'm not sure if it's necessary. Open to the idea though if you think this layout is confusing or just too long though.

(DOCSP-10023): IoT SDK installation instructions

---

source/hosting/use-a-custom-domain-name.txt
source/includes/appschema-configuration.rst
source/includes/options-realm-cli.yaml
source/includes/realm-application-file-schema.rst
source/includes/steps-apple-auth-configure.yaml
source/includes/steps-cli-create.yaml
source/includes/steps-define-custom-user-data-import-export.yaml
source/includes/steps-deploy-cli.yaml
source/includes/steps-enable-hosting-import-export.yaml
source/includes/steps-github-deploy.yaml
source/includes/steps-host-a-single-page-application-code-deploy.yaml
source/includes/steps-use-a-custom-404-page-import-export.yaml
source/includes/steps-use-a-custom-domain-name-import-export.yaml

- (DOCSP-11084): Realm CLI documentation references realm.json instead of config.json
- [staged](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/realm.json/index.html)

(DOCSP-11084): Realm CLI documentation references realm.json instead of config.json

---

source/graphql/expose-data.txt

- (DOCSP-9796): Clarify where relationship definition goes on GraphQL page
- [Expose Data in a Collection > 3. Define Relationships to Other Collections](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/graphql-relationships/graphql/expose-data.html#define-relationships-to-other-collections)

(DOCSP-9796): Clarify where relationship definition goes on GraphQL page

---

source/get-started/glossary.txt

- Searched for other broken wikipedia links and fixed any
https://jira.mongodb.org/browse/DOCSP-11250
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/fix-wiki-link/get-started/glossary.html

(DOCSP-11250): Fix Wikipedia links

---

source/openapi-admin-v3.yaml

JIRA: https://jira.mongodb.org/browse/DOCSP-10905
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-10905/admin/api/v3.html#put-/groups/{groupid}/apps/{appid}/triggers/{triggerid}/resume

(DOCSP-10905): Empty body no longer required for trigger resume API

---

source/android/call-a-function.txt
source/android/init-realmclient.txt
source/android/quick-start.txt
source/includes/android-initialize-realm.rst

Quick start: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/moartabs/android/quick-start.html
- same content, refactored "Initialize Realm" into an includes file
Initialize the Realm Client: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/moartabs/android/init-realmclient.html
- Added "Initialize Realm" section that was already written for quick start, which contains details about where and why you need to run ``Realm.init()``
- Java/Kotlin tabbed examples where previously we only had Kotlin examples
Call a Function: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/moartabs/android/call-a-function.html
- Java/Kotlin tabbed examples where previously we only had Kotlin examples

kotlin java parity, init Realm as include file

---

source/includes/steps-tutorial-react-native.yaml

Jira:
-----
* https://jira.mongodb.org/browse/DOCS-13758
Stage:
-------
* https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-13758-RN-LogInView-Syntax-Fix/tutorial/react-native.html
Changes Related to Jira Ticket:
-------------------------------
* Fixed Step 8 name of file from `schemas.json` to `schemas.js`
Changes **Not** Made Related to Jira Ticket and Why:
-------------------------------------------------------
* Did not alter step 6 to include `export default LogInView` because the function is already exported in it's declaration as `export function LogInView() {` and this works fine (the reporter of this ticket may have forgotten to export the function and assumed it was a fault in the docs)
Changes Made Outside of the Scope of This Ticket: …

(DOCSP-13758) React Native Tutorial Fixes for Beta.9 + Typo in Docs

---

source/mongodb/insert-documents.txt

jira:https://jira.mongodb.org/browse/DOCSP-11349
stage: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-11349-Fix-MongoDB-InsertOne-Example/mongodb/insert-documents.html#insert-a-single-document

(DOCSP-11349): fix insertOne Example on mongodb/insert-documents

---

source/includes/steps-define-a-secret-realm-ui.yaml
source/values-and-secrets.txt

https://jira.mongodb.org/browse/DOCSP-11507
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/secret-max-length/values-and-secrets.html
Note: the CSS has changed. Platform is investigating.

(DOCSP-11507): Add character limit to Realm secret values

---

source/tutorial/realm-app.txt

Relatively small impact to the realm docs. We only mentioned the 4.4 beta in one spot.

(DOCS-13793): [Realm] Remove MongoDB 4.4 beta references

---

source/includes/mongodb-4.4-required-for-sync-admonition.rst
source/mongodb/link-a-cluster.txt
source/procedures/create-realm-app.txt
source/sync.txt
source/sync/overview.txt
source/tutorial/realm-app.txt

- Moves existing admonition to shared snippet
- Adds snippet on Get Started with Sync and Sync Overview pages
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/4.4/mongodb/link-a-cluster.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/4.4/tutorial/realm-app.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/4.4/sync/overview.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/4.4/sync.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/bush/4.4/procedures/create-realm-app.html#c-add-a-realm-app
https://jira.mongodb.org/browse/DOCSP-11521

(DOCSP-11521): Add admonition about 4.4 required for sync

---

source/mongodb/crud-and-aggregation-apis.txt
source/services/push-notifications.txt

- (DOCSP-11703): [REALMC] $unionWith
- (DOCSP-11512): FCM 'to' field description is incomplete
- [CRUD & Aggregation APIs](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/quickfix/mongodb/crud-and-aggregation-apis.html#aggregation)
- [Push Notifications (FCM)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/quickfix/services/push-notifications.html#push-notification-rules)

(DOCSP-11703,11512): Quick Wins

---

source/node/access-custom-user-data.txt

Old page contained garbage text (directly after first code sample):
https://docs.mongodb.com/realm/node/access-custom-user-data/
Doesn't seem to be tied in to any note, so I figured we should just delete it. If you can make sense of it, happy to turn into a note or paragraph.
DNE

textdump fix

---

source/ios/sync-data.txt

https://jira.mongodb.org/browse/DOCSP-11085
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/11085/ios/sync-data.html#background-data-sync

11085 - add info on background refresh

---

source/functions.txt
source/mongodb/service-limitations.txt

https://jira.mongodb.org/browse/DOCSP-11736
https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-11736-FileUploadLimitation/mongodb/service-limitations.html#http-requests-to-mongodb-realm-functions-and-webhooks

(DOCSP-11736): HTTP Requests to Webhooks 18MB Limit

---

source/graphql/authenticate.txt
source/graphql/expose-data.txt
source/index.txt
source/reference/authenticate-http-client-requests.txt

- (DOCSP-11859): [GraphQL] Credential Authentication in Request Headers
- [Authenticate GraphQL Requests (**new**)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/graphql-authenticate/graphql/authenticate.html)
- [Authenticate HTTP Client Requests (**moved**)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/graphql-authenticate/reference/authenticate-http-client-requests.html)

(DOCSP-11859): [GraphQL] Credential Authentication in Request Headers

---

source/includes/steps-tutorial-android-kotlin.yaml

tutorial repo update: https://github.com/mongodb-university/realm-tutorial/pull/64
https://jira.mongodb.org/browse/DOCSP-11855
https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-11855/tutorial/android-kotlin.html#install-realm-as-a-gradle-plugin

(DOCSP-11855): Update Android Tutorial to Beta 6

---

source/includes/steps-install-android.yaml

https://jira.mongodb.org/browse/DOCSP-11856
https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/DOCSP-11856/android/install.html#add-the-realm-dependency-to-the-project-level-build-gradle-file

(DOCSP-11856): Android quick-start install beta 6

---

source/includes/steps-define-sync-rules-api.yaml
source/includes/steps-define-sync-rules-cli.yaml
source/includes/steps-define-sync-rules-ui.yaml
source/sync.txt
source/sync/permissions.txt

- (DOCSP-11531): Document different ways to implement sync permissions
- [Sync Permission Strategies](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/sync-permissions/sync/permissions.html)
- [Define Sync Rules](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/sync-permissions/sync/rules.html)

(DOCSP-11531): Document different ways to implement sync permissions

---

source/graphql/authenticate.txt

- (DOCSP-12054): GraphQL API Key auth has incorrect header parameter
- [Authenticate GraphQL Requests > API Key](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/graphql-auth-header/graphql/authenticate.html#api-key)

(DOCSP-12054): GraphQL API Key auth has incorrect header parameter

---

source/web/authenticate.txt

- (DOCSP-11936): Remove Google Redirect Documentation in Realm-Web SDK
- [Google OAuth](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/google-redirect/web/authenticate.html#google-oauth)

(DOCSP-11936): Remove Google Redirect Documentation in Realm-Web SDK

---

source/android.txt
source/android/encrypt.txt
source/examples/Encrypt/StoreInKeychain.swift
source/examples/Encrypt/encrypt.java
source/examples/Encrypt/encrypt.js
source/examples/Encrypt/encrypt.kt
source/examples/Encrypt/encrypt.m
source/examples/Encrypt/encrypt.swift
source/ios.txt
source/ios/encrypt.txt
source/node.txt
source/node/encrypt.txt
source/react-native.txt
source/react-native/encrypt.txt

Adds the encryption pages based on https://realm.io/docs/swift/latest/#encryption
https://jira.mongodb.org/browse/DOCSP-11754
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/encryption/ios/encrypt.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/encryption/android/encrypt.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/encryption/node/encrypt.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/encryption/react-native/encrypt.html

(DOCSP-11754): Add encrypt a realm page

---

source/includes/steps-tutorial-ios-swift.yaml

Stage:
-------
* https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/Moe-IOS-Swift-Tutorial-Fixes/tutorial/ios-swift.html
Changes:
---------
* Added missing "import RealmSwift" to TaskViewController (if you don't import RealmSwift, you will see the error: "Use of undeclared type 'Realm'" as seen in the screenshot below
* Fixed syntax: `user.configuration(partitionValue: partitionValue) should be `user!.configuration(partitionValue: partitionValue)`

Syntax fixed for IOS Tutorial

---

source/android.txt
source/ios.txt

ios main page: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/android-ios-structure-parity/ios.html
android main page: https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/android-ios-structure-parity/android.html

fixed ios links; structuring android to match ios

---

source/ios/objects.txt

- Raised in #realm-users
- Typo fix
https://jira.mongodb.org/browse/DOCSP-12247
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/object-id-fix/ios/objects.html

(DOCSP-12247): Update iOS objects text to include String and Int types on _id

---

source/android/code-samples/quick-start.java
source/android/code-samples/quick-start.kt

https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/androidQuickStartRaceCoondition/android/quick-start.html

removing logout call from full quickstart because it triggers a race condition

---

source/android/authenticate.txt
source/includes/log-out-queries-in-progress.rst
source/ios/authenticate.txt
source/node/authenticate.txt
source/react-native/authenticate.txt

https://jira.mongodb.org/browse/RJAVA-669
https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/master/android/authenticate.html#log-out
https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/master/ios/authenticate.html#log-out
https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/master/node/authenticate.html#log-out
https://docs-mongodbcom-staging.corp.mongodb.com/realm/pegasus/master/react-native/authenticate.html#log-out

added warning to log out documentation about local realm access

---

source/android/embedded-objects.txt
source/ios/embedded-objects.txt
source/node/embedded-objects.txt
source/react-native/embedded-objects.txt

Regrettably, I couldn't single-source this content because I wanted to link to the relationships doc for each SDK.
https://jira.mongodb.org/browse/DOCSP-12151
React Native: https://docs-mongodbcom-staging.corp.mongodb.com/realm/nathan.contino/DOCSP-12151/react-native/embedded-objects.html
Android: https://docs-mongodbcom-staging.corp.mongodb.com/realm/nathan.contino/DOCSP-12151/android/embedded-objects.html
iOS: https://docs-mongodbcom-staging.corp.mongodb.com/realm/nathan.contino/DOCSP-12151/ios/embedded-objects.html
Node: https://docs-mongodbcom-staging.corp.mongodb.com/realm/nathan.contino/DOCSP-12151/node/embedded-objects.html

(DOCSP-12151): Cascading deletes callout for embedded objects

---

source/services/expression-variables.txt

- (DOCSP-12119): Realm %%prevRoot example is wrongly described

(DOCSP-12119): Realm %%prevRoot example is wrongly described

---

source/get-started/glossary.txt
source/includes/steps-define-sync-rules-api.yaml
source/includes/steps-define-sync-rules-cli.yaml
source/includes/steps-define-sync-rules-ui.yaml
source/sync/partitioning.txt

https://jira.mongodb.org/browse/DOCSP-11835
https://docs-mongodbcom-staging.corp.mongodb.com/realm/lisbethlazala/clarify-partition-key-handling/sync/rules.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/lisbethlazala/clarify-partition-key-handling/sync/partitioning.html#choose-a-partition-key

(DOCSP-11835): Clarify Partition Key handling on Client-side vs. Server-side

---

source/android/embedded-objects.txt
source/includes/directly-query-embedded-objects-note.rst
source/ios/embedded-objects.txt
source/node/embedded-objects.txt
source/react-native/embedded-objects.txt

https://jira.mongodb.org/browse/DOCSP-12267
At bottom of page -- removed "query directly" section from node/react-native, added a note to all pages.
https://docs-mongodbcom-staging.corp.mongodb.com/realm/nathan.contino/DOCSP-12267/node/embedded-objects.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/nathan.contino/DOCSP-12267/react-native/embedded-objects.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/nathan.contino/DOCSP-12267/android/embedded-objects.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/nathan.contino/DOCSP-12267/ios/embedded-objects.html

(DOCSP-12267): Remove direct embedded object query examples

---

source/android/objects.txt
source/ios/objects.txt
source/node/include/property-schema.rst

https://jira.mongodb.org/browse/DOCSP-11307
- android: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-11307-type-check-for-sync-client-guides/android/objects.html
- ios: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-11307-type-check-for-sync-client-guides/ios/objects.html
- node: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-11307-type-check-for-sync-client-guides/node/objects.html
doc w/ summary of types allowed/not allowed:
https://docs.google.com/document/d/1vSPniERWWe-CLh8vcAb9YMjKBozI9rXlzfzPFxXBi2k/edit?usp=sharing

(DOCSP-11307): type check for sync client guides

---

source/android.txt

The conf.py links had already been updated to the new format, but not the sidebar links.
N/A
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/update-sidebar-links/android.html

Update android SDK links in sidebar

---

source/admin/api/v3.txt
source/logs/api.txt

https://jira.mongodb.org/browse/DOCSP-12327
https://docs-mongodbcom-staging.corp.mongodb.com/realm/lisbethlazala/app-object-id-logs/logs/api.html

(DOCSP-12327): Show how to get App Object ID on Access Logs with the Admin API page

---

source/mongodb/crud-and-aggregation-apis.txt
source/mongodb/supported-aggregation-stages.rst

- Adds section to crud-and-aggregation-apis for aggregation operator support exceptions
https://jira.mongodb.org/browse/DOCSP-12343
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/function-agg-op/mongodb/crud-and-aggregation-apis.html#aggregation-pipeline-operator-availability

(DOCSP-12343): Specify $function operator support

---

source/android/auxiliary-files.txt
source/android/client-reset.txt
source/android/mongodb.txt

ENG [reviewed the beta 8 changes and had some suggestions](https://github.com/mongodb/docs-realm/pull/474). I noticed some random things that could be cleaned up. Notable changes:
- broken link fixes
- removed client reset description from the "auxiliary files" page (even I have only read it once) and merged it with the description on a the new client reset page
- improved text for the `watch` description
- new section for `watch` in the MongoDB page
https://docs-mongodbcom-staging.corp.mongodb.com/realm/nathan.contino/androidbeta8/android/client-reset.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/nathan.contino/androidbeta8/android/mongodb.html#watch-for-changes

Cleanup of android beta 8 changes based on eng suggestions

---

conf.py
source/android/encrypt.txt
source/android/mongodb.txt
source/authentication/google.txt
source/get-started/glossary.txt
source/graphql/types-and-resolvers.txt
source/includes/extracts-mongodb-action.yaml
source/includes/steps-auth-google-project-setup.yaml
source/mongodb/link-a-data-source.txt

This is a sibling PR that preps the Realm docs to match the updated Snooty config in https://github.com/mongodb/snooty-parser/pull/226
Some definitions for extlink roles in snooty ([rstspec.toml](https://github.com/mongodb/snooty-parser/blob/master/snooty/rstspec.toml) don't quite match our legacy definitions. Rather than renaming these in the centralized repo, this PR updates our local `conf.py` and all references to match.
- (DOCSP-12508): Centralize extlink definitions
(probably need to use the diff view for this PR but staged if you want to sanity check)
- [Realm Docs](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/snooty/index.html)

(DOCSP-12508): Update extlinks to match Snooty definitions

---

source/includes/steps-tutorial-ios-swift.yaml
tutorial/swift-ios/Podfile
tutorial/swift-ios/Podfile.lock
tutorial/swift-ios/Task Tracker/ManageTeamViewController.swift
tutorial/swift-ios/Task Tracker/Models.swift
tutorial/swift-ios/Task Tracker/ProjectsViewController.swift
tutorial/swift-ios/Task Tracker/SceneDelegate.swift
tutorial/swift-ios/Task Tracker/TasksViewController.swift
tutorial/swift-ios/Task Tracker/WelcomeViewController.swift

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/bluehawkify-ios/tutorial/ios-swift.html?a

Bluehawkify ios

---

source/android/sync-data.txt
source/includes/sync-beta-note.rst
source/index.txt
source/ios/sync-data.txt
source/node/sync-data.txt
source/react-native/sync-data.txt
source/sync.txt
source/sync/configure-your-data-model.txt
source/sync/conflict-resolution.txt
source/sync/enable-development-mode.txt
source/sync/overview.txt
source/sync/partitioning.txt
source/sync/permissions.txt
source/sync/rules.txt

https://jira.mongodb.org/browse/DOCSP-12501
- Added note to the "sync data" pages of each SDK: https://docs-mongodbcom-staging.corp.mongodb.com/realm/nathan.contino/DOCSP-12501/ios/sync-data.html
- Added note to all "sync" section pages
- Changed name of "sync" section to "Sync (Beta)" (though for some reason it isn't showing up in the TOC -- caching issues?)
https://docs-mongodbcom-staging.corp.mongodb.com/realm/nathan.contino/DOCSP-12501/sync/overview.html

(DOCSP-12501): Clearly state that Sync is a beta product

---

conf.py
examples/ios/Examples/Authenticate.swift
examples/ios/Podfile
examples/ios/Podfile.lock
examples/ios/RealmExamples.xcodeproj/project.pbxproj
source/examples/generated/code/start/Authenticate.codeblock.anonymous.swift
source/examples/generated/code/start/Authenticate.codeblock.api-key.swift
source/examples/generated/code/start/Authenticate.codeblock.apple.swift
source/examples/generated/code/start/Authenticate.codeblock.email-password.swift
source/examples/generated/code/start/Authenticate.codeblock.facebook.swift
source/examples/generated/code/start/Authenticate.codeblock.function.swift
source/examples/generated/code/start/Authenticate.codeblock.google.swift
source/examples/generated/code/start/Authenticate.codeblock.jwt.swift
source/examples/generated/code/start/Authenticate.codeblock.logout.swift
source/includes/steps-install-cocoapods.yaml
source/includes/steps-tutorial-ios-swift.yaml
source/ios.txt
source/ios/authenticate.txt

https://jira.mongodb.org/browse/DOCSP-12550
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/ios-beta-6/ios/authenticate.html

iOS beta 6

---

source/includes/steps-task-tracker-web-apollo.yaml
source/includes/steps-task-tracker-web-realmapp.yaml
source/includes/task-tracker-web-client-base-file-structure.rst
source/tutorial/web-graphql.txt
tutorial/web/package-lock.json
tutorial/web/src/App.js
tutorial/web/src/RealmApp.js
tutorial/web/src/components/EditPermissionsModal.js
tutorial/web/src/components/LoginScreen.js
tutorial/web/src/components/Sidebar.js
tutorial/web/src/graphql/RealmApolloProvider.js
tutorial/web/src/graphql/useProjects.js
tutorial/web/src/graphql/useTaskMutations.js

https://jira.mongodb.org/browse/DOCSP-12163
https://docs-mongodbcom-staging.corp.mongodb.com/realm/lisbethlazala/bluehawk-web/tutorial/web-graphql.html
TODO: Change the name of the tutorial in the sidebar.

(DOCSP-12163): Write Phase 2 Tutorial Text (Web)

---

source/tutorial/nodejs-cli.txt

https://jira.mongodb.org/browse/DOCSP-12167
https://docs-mongodbcom-staging.corp.mongodb.com/realm/lisbethlazala/bluehawk-node-edits/tutorial/nodejs-cli.html

Node-cli Tutorial Text Edits

---

source/dotnet.txt
source/dotnet/install.txt
source/dotnet/quick-start.txt
source/includes/steps-install-dotnet-vs-mac.yaml

**NOTE** I am intentionally hiding all of this from the TOC until release. You need to go to the links below to find the docs.
**NOTE** The majority of the quick-start was already merged in, so most of the changes are not in this PR, but the page still needs a good review. 
https://jira.mongodb.org/browse/DOCSP-12488
https://jira.mongodb.org/browse/DOCSP-12563
https://jira.mongodb.org/browse/DOCSP-12564
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/12563_4/dotnet.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/12563_4/dotnet/install.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/12563_4/dotnet/quick-start.html

landing page, install, and quickstart

---

source/includes/steps-tutorial-react-native.yaml
source/tutorial/nodejs-cli.txt
source/tutorial/react-native.txt

https://docs-mongodbcom-staging.corp.mongodb.com/realm/lisbethlazala/rn-phase2-edits/tutorial/react-native.html
https://docs-mongodbcom-staging.corp.mongodb.com/realm/lisbethlazala/rn-phase2-edits/tutorial/nodejs-cli.html

Edits to Node.js and React Native Tutorial Text

---

source/includes/steps-tutorial-android-kotlin.yaml
source/tutorial/android-kotlin.txt

https://docs-mongodbcom-staging.corp.mongodb.com/realm/lisbethlazala/android-phase2-edits/tutorial/android-kotlin.html

Android Tutorial Text Minor Edits

---

tutorial/backend/README.md
tutorial/web/src/components/Sidebar.js

Last fixes

---

source/includes/steps-tutorial-ios-swift.yaml
source/tutorial.txt
source/tutorial/android-kotlin.txt
source/tutorial/ios-swift.txt
source/tutorial/nodejs-cli.txt
source/tutorial/react-native.txt
source/tutorial/web-graphql.txt

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/more-phase-2-cleanup/index.html

Cleanup for tutorial phase 2

---

source/includes/steps-task-tracker-web-apollo.yaml
source/includes/steps-task-tracker-web-realmapp.yaml
source/tutorial/generated/code/final/App.codeblock.appID.js
source/tutorial/generated/code/final/App.codeblock.requireLoggedInUser.js
source/tutorial/generated/code/final/EditPermissionsModal.codeblock.useTeamMembers.js
source/tutorial/generated/code/final/LoginScreen.codeblock.handleLogin.js
source/tutorial/generated/code/final/LoginScreen.codeblock.handleRegistrationAndLogin.js
source/tutorial/generated/code/final/RealmApolloProvider.codeblock.createRealmApolloClient.js
source/tutorial/generated/code/final/RealmApolloProvider.codeblock.realmApolloProvider.js
source/tutorial/generated/code/final/RealmApp.codeblock.realmAppProvider.js
source/tutorial/generated/code/final/SceneDelegate.codeblock.initialize-app.swift
source/tutorial/generated/code/final/Sidebar.codeblock.sidebarContainer.js
source/tutorial/generated/code/final/Sidebar.codeblock.sidebarSetUp.js
source/tutorial/generated/code/final/getRealmApp.codeblock.get-realm-app.js
source/tutorial/generated/code/final/schemas.codeblock.react-native-task-schema.js
source/tutorial/generated/code/final/useProjects.codeblock.useProjects.js
source/tutorial/generated/code/final/useTaskMutations.codeblock.addTaskMutation.js
source/tutorial/generated/code/final/useTaskMutations.codeblock.deleteTaskMutation.js
source/tutorial/generated/code/final/useTaskMutations.codeblock.updateTaskMutation.js
source/tutorial/generated/code/final/useTaskMutations.codeblock.useAddTask.js
source/tutorial/generated/code/final/useTaskMutations.codeblock.useDeleteTask.js
source/tutorial/generated/code/final/useTaskMutations.codeblock.useUpdateTask.js
source/tutorial/web-graphql.txt
tutorial/rn/schemas.js

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/codeblocks/tutorial/web-graphql.html

Add Web code blocks

---

source/includes/steps-task-tracker-web-apollo.yaml
source/tutorial/nodejs-cli.txt
source/tutorial/web-graphql.txt

- Not supported in nextgen anyway

Remove emphasize-lines

---

source/billing.txt

- (DOCSP-12671): Billing Page Lists Sync Minutes in ms vs min
- [Billing](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/billing/billing.html#realm-sync)

(DOCSP-12671): Billing Page Lists Sync Minutes in ms vs min

---

source/includes/steps-tutorial-android-kotlin.yaml
source/includes/steps-tutorial-ios-swift.yaml
source/includes/steps-tutorial-react-native.yaml
source/tutorial/nodejs-cli.txt
source/tutorial/realm-app.txt
source/tutorial/web-graphql.txt

https://jira.mongodb.org/browse/DOCSP-12692
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/ssh2http/tutorial/ios-swift.html

(DOCSP-12692): Tutorial git clone ssh -> https

---

examples/ios/Examples/Authenticate.swift
source/android/authenticate.txt
source/examples/generated/code/start/Authenticate.codeblock.apple.swift
source/examples/generated/code/start/Authenticate.codeblock.facebook.swift
source/examples/generated/code/start/Authenticate.codeblock.google.swift

https://jira.mongodb.org/browse/DOCSP-12467
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/token/ios/authenticate.html

(DOCSP-12467): Update authentication examples

---

source/includes/steps-tutorial-android-kotlin.yaml
source/includes/steps-tutorial-ios-swift.yaml
source/includes/steps-tutorial-react-native.yaml
source/tutorial/nodejs-cli.txt
source/tutorial/web-graphql.txt

https://jira.mongodb.org/browse/DOCSP-12694
iOS Swift tutorial: https://docs-mongodbcom-staging.corp.mongodb.com/realm/lisbethlazala/add-sdk-tip-to-tutorials/tutorial/ios-swift.html#define-the-object-models
Android: https://docs-mongodbcom-staging.corp.mongodb.com/realm/lisbethlazala/add-sdk-tip-to-tutorials/tutorial/android-kotlin.html#implement-the-projects-list
React Native: https://docs-mongodbcom-staging.corp.mongodb.com/realm/lisbethlazala/add-sdk-tip-to-tutorials/tutorial/android-kotlin.html#implement-the-projects-list
Node.js: https://docs-mongodbcom-staging.corp.mongodb.com/realm/lisbethlazala/add-sdk-tip-to-tutorials/tutorial/nodejs-cli.html#e-implement-the-crud-methods
Web: https://docs-mongodbcom-staging.corp.mongodb.com/realm/lisbethlazala/add-sdk-tip-to-tutorials/tutorial/web …

(DOCSP-12694): Add "tip" to look at SDKs and Schemas page in the Realm UI to connect client models sections

---

source/web/authenticate.txt

- (DOCSP-12639): [realm-web] Update Google redirect deprecation note
- [Google OAuth](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/google-redirect/web/authenticate.html#google-oauth)

(DOCSP-12639): [realm-web] Update Google redirect deprecation note

---

source/android/init-realmclient.txt
source/ios/init-realmclient.txt
source/node.txt
source/node/init-realmclient.txt
source/react-native.txt
source/react-native/init-realmclient.txt
source/web.txt
source/web/init-realmclient.txt

https://jira.mongodb.org/browse/DOCSP-12596
* Node: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-12596-JS-Initialize-Realm-App/node/init-realmclient.html
* React Native: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-12596-JS-Initialize-Realm-App/react-native/init-realmclient.html
* Web: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-12596-JS-Initialize-Realm-App/web/init-realmclient.html
Note: 
* The method "Realm.App.getApp()" is not documented in this PR for the "realm-web" SDK. There is a merged PR on the package w/ this API method, so that method will not be made available until the next release. I have created a JIRA ticket for this documentation: https://jira.mongodb.org/browse/DOCSP-12708

(DOCSP-12596) JS Initialize Realm App

---

source/mongodb/crud-and-aggregation-apis.txt

https://jira.mongodb.org/browse/DOCSP-12707
https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-12707-Fix-Typos-BulkOps/mongodb/crud-and-aggregation-apis.html

(DOCSP-12707): Fix Typos on Bulk Operations Subsection of Crud and Aggregation APIs Page

---

source/functions.txt
source/functions/js-feature-compatibility.txt

- (DOCSP-12450): JS Compatibility Table
- [JavaScript Feature Compatibility](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/es6/functions/js-feature-compatibility.html)

(DOCSP-12450): JS Compatibility Table

---

source/node.txt

N/A - Quickfix to remove electron from TOC temporarily while JS SDK has an error in lib/analytics that prevents it from working w/ electron
https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/moe-rm-electron-quickstart-quickfix/index.html

quickfix - hide electron page

---

source/tutorial/generated/code/final/ManageTeamViewController.codeblock.add-team-member.swift
source/tutorial/generated/code/final/ManageTeamViewController.codeblock.fetch-team-members.swift
source/tutorial/generated/code/final/ManageTeamViewController.codeblock.remove-team-member.swift
tutorial/swift-ios/Task Tracker/ManageTeamViewController.swift

- If currentUser is not stored in a local variable, then its weak reference stored in functions is already nil by the time you actually call the function.
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/ios-fix/tutorial/ios-swift.html#implement-the-manage-team-view

Fix iOS swift tutorial issue with app.currentUser!.functions

---

examples/dotnet/Examples/EncryptionExamples.cs

- Oops! Encrypted ur realm and lost the key causing subsequent tests to fail.
- Deletes realm when done.
- You may need to `rm -rf ~/*.realm*`

Fix Encrypt unit test

---

examples/node/.gitignore
source/react-native/authenticate.txt

https://jira.mongodb.org/browse/DOCSP-12646
https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-12646-Update-API-Key-Method/react-native/authenticate.html#api-key

(DOCSP-12646): Update React Native to use Realm.Credentials.serverApiKey(apiKey);

---

source/mongodb/crud-snippets/deleteOne/functions.rst
source/mongodb/crud-snippets/findOneAndReplace/functions.rst
source/mongodb/crud-snippets/findOneAndUpdate/functions.rst
source/mongodb/crud-snippets/updateOneSetField/functions.rst
source/mongodb/delete-documents.txt
source/mongodb/update-documents.txt

"legos" isn't the plural for "Lego"

Shouldn't refer to "legos"

---

source/graphql.txt
source/graphql/custom-resolvers.txt
source/graphql/expose-data.txt
source/graphql/types-and-resolvers.txt
source/includes/steps-custom-resolvers-ui.yaml

(all graphql code snippets in the GraphQL section are effected)
https://docs-mongodbcom-staging.corp.mongodb.com/realm/nathan.contino/graphql-codeblocks/graphql.html
Restored graphql type to all codeblocks containing graphql, since the [fixit PR](https://github.com/mongodb/docs-realm/pull/578) changed these codeblocks to type "text" to remove oldgen/sphinx build warnings. Since nextgen has done away with pygments in favor of leafygreen syntax highlighting, graphql syntax will finally be supported.
Please do not merge this PR until we're ready for nextgen.

[NextGen Migration] restored graphql type to graphql codeblocks.

---

source/android/objects.txt
source/ios/objects.txt
source/node/include/property-schema.rst

This lists Decimal128 as being supported in iOS (Swift and ObjC), Java, and Node.
https://jira.mongodb.org/browse/DOCSP-12828
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-12828/ios/objects.html#object-model

add Decimal128 to supported types

---

source/includes/auth-provider-internal-names.rst

This lists Apple authentication as a potential value (via "oauth2-apple") to be used in authentication triggers.
https://jira.mongodb.org/browse/DOCSP-12862
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-12862/triggers/authentication-triggers.html#authentication-trigger-configuration

add apple auth to provider list for triggers docs

---

source/openapi-admin-v3.yaml

(instead of manual mongodb database user docs)
Credit to John Page for catching this issue.
https://mongodb.slack.com/archives/CLY6HQWUE/p1604668968221100
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/users-to-realm-users/admin/api/v3.html#users-apis

Point Admin API user links to Realm User docs

---

source/includes/steps-install-swiftpm.yaml
source/ios/install.txt

This adds SwiftPM steps to iOS installation and positions them above CocoaPods.
https://jira.mongodb.org/browse/DOCSP-12991
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-12991/ios/install.html#installation

Docsp 12991

---

source/authentication/anonymous.txt
source/authentication/api-key.txt
source/authentication/apple.txt
source/authentication/custom-function.txt
source/authentication/custom-jwt.txt
source/authentication/email-password.txt
source/authentication/facebook.txt
source/authentication/google.txt
source/functions/call-a-function.txt

https://jira.mongodb.org/browse/DOCSP-11206
All auth pages in the "Users & Authentication" section:
https://docs-mongodbcom-staging.corp.mongodb.com/realm/nathan.contino/DOCSP-12889/authentication/apple.html#examples
https://docs-mongodbcom-staging.corp.mongodb.com/realm/nathan.contino/DOCSP-12889/authentication/anonymous.html#examples
https://docs-mongodbcom-staging.corp.mongodb.com/realm/nathan.contino/DOCSP-12889/authentication/email-password.html#examples
https://docs-mongodbcom-staging.corp.mongodb.com/realm/nathan.contino/DOCSP-12889/authentication/custom-jwt.html#examples
https://docs-mongodbcom-staging.corp.mongodb.com/realm/nathan.contino/DOCSP-12889/authentication/custom-function.html#examples
https://docs-mongodbcom-staging.corp.mongodb.com/realm/nathan.contino/DOCSP-12889/authe …

(DOCSP-11206): Add links to client SDK examples of auth providers

---

source/functions/built-in-module-support.txt

https://jira.mongodb.org/browse/DOCSP-12954
https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-12954-Make-Util-Partially-Supported/functions/built-in-module-support.html

(DOCSP-12954): Moved Built In Module 'Util' To Partially Supported

---

source/dotnet.txt
source/dotnet/notifications.txt
source/examples/Notifications/NotificationUnsub.cs
source/examples/Notifications/ObjectNotification.cs

Trying to fix some broken links that currently point to this page (and boast about this functionality).
https://docs-mongodbcom-staging.corp.mongodb.com/realm/nathan.contino/dotnetnotificationsadd/dotnet/notifications.html

added notifications page back

---

source/dotnet/notifications.txt

There ain't 22 lines in that code snippet lol
https://docs-mongodbcom-staging.corp.mongodb.com/realm/nathan.contino/notificationsfix/dotnet/notifications.html
For some reason syntax highlights are still broken, though.

fixed emphasize-lines incorrect line

---

source/services/expression-variables.txt

- (DOCSP-12909): [REALMC] Support String/ObjectID Translation in JSON Expressions
- [Expression Variables > EJSON Conversion](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/oid/services/expression-variables.html#ejson-conversion)

(DOCSP-12909): [REALMC] Support String/ObjectID Translation in JSON Expressions

---

source/includes/deployment-region-auth-callback-urls.rst

(DOCSP-13520): OAuth redirect URLs use stitch instead of realm

(DOCSP-13520): OAuth redirect URLs use stitch instead of realm

---

source/node/include/property-schema.rst

(DOCSP-13419): Document Primitive List Types (JS)
- [Node](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/positional/node/objects#property-schema)
- [RN](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/positional/react-native/objects#property-schema)

(DOCSP-13419): Document Primitive List Types (JS)

---

source/node/install.txt

https://jira.mongodb.org/browse/DOCSP-13617
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-13617-quickfix-electron-support/node/install

(DOCSP-13617): QuickFix Remove Electron Not Supported 

---

source/android/migrate.txt

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/deprecated-to-removed/android/migrate

Move service advice into the table, no longer say "deprecated"

---

source/includes/steps-crud-snippets-react-native.yaml
source/includes/steps-crud-snippets-web.yaml
source/node/mongodb.txt
source/react-native/mongodb.txt
source/web/mongodb.txt

* Updates the setup instructions for Web/RN to show `User.mongoClient` instead of `App.services.mongodb`
* Updates Web/RN examples to use tested Bluehawk snippets (same as Node)
* Adds an "On this page" sidebar (i.e. `.. contents::`) to the Web/RN pages
(DOCSP-13771): Update JS MongoDB Service API
- [MongoDB Data Access (Web)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/mongodb/web/mongodb)
- [MongoDB Data Access (RN)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/mongodb/react-native/mongodb)
- [MongoDB Data Access (Node)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/mongodb/node/mongodb) (no user-facing changes here - Web/RN examples should be identical to this page but w/ modified refs & link targets)

(DOCSP-13771): Update JS MongoDB Service API

---

source/functions/js-feature-compatibility.txt

https://mongodb.slack.com/archives/CG53S529Y/p1610474713000600
https://docs-mongodborg-staging.corp.mongodb.com/realm/docsworker-xlarge/array-static-methods-are-not-supported-in-functions/

Remove claim that Realm Functions support static array funcs

---

source/android/authenticate.txt
source/authentication/google.txt
source/dotnet/authenticate.txt
source/ios/authenticate.txt
source/node/authenticate.txt
source/react-native/authenticate.txt
source/web/authenticate.txt

- Add OneTap (OpenID) instructions for web
- Re-add code sample for Google built-in flow (no OpenID)
- Adds info on iOS google credentials (`google` vs `googleId`)
(DOCSP-12984): [REALMC] Support OpenID with Google OAuth
- [Google Authentication](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/openid/authentication/google)
- [Authenticate > Google (Web)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/openid/web/authenticate#google-authentication)
- [Authenticate > Google (iOS)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/openid/ios/authenticate#google-authentication)

(DOCSP-12984): [REALMC] Support OpenID with Google OAuth

---

source/dotnet/migrations.txt
source/dotnet/notifications.txt
source/dotnet/objects.txt
source/dotnet/query-engine.txt

While looking for missing code examples, I found several places where the spacing of the literalinclude was wrong. This is just a cleanup PR. 
https://jira.mongodb.org/browse/DOCSP-13464
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/13464/

fix literalinclude spacings

---

source/examples/Notifications/ObjectNotification.js

- https://jira.mongodb.org/browse/DOCSP-14046
- node: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/Hotfix-ObjectNotifications-Snippet-JS-Conventions/node/notifications#object-notifications
- rn: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/Hotfix-ObjectNotifications-Snippet-JS-Conventions/react-native/notifications#object-notifications
- Changed "obj" in the callback to "_changedDog" to adhere to JS coding standards. 
- non-descriptive (notably the old variation had an "obj === dog" which seems counterintuitive, might as well describe the parameter upfront rather than in a comment)
- That parameter is unused. Unused parameters should have an underscore in front of them (see: …

(DOCSP-14046): Update "Object Notifications" code to adhere to JS conventions (unused parameters + descriptive variables)

---

source/ios/notifications.txt

Fix the reference to "Object Notifications" Swift example

---

source/cloud.txt
source/index.txt
source/sdk.txt

Per official naming guidance doc, "MongoDB Realm Cloud" is not the correct name for this section:
- "Realm Cloud" already exists as the legacy Realm platform
- "MongoDB Realm Cloud" would exist under "MongoDB Cloud" (Atlas, etc.)
URI `/cloud/` remains as shorthand because `/services/` is already used by 3rd party services.
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/rename-cloud

Rename "MongoDB Realm Cloud" -> "MongoDB Realm Application Services"

---

source/examples/QuickStarts/electron/quickstart-setup-react-electron.js
source/includes/steps-realm-with-electron-using-create-react-app.yaml

https://jira.mongodb.org/browse/DOCSP-14270
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14270-Electron-cra-broken-link/node/electron-cra

(DOCSP-14270): Fix broken literalinclude on Electron React QuickStart

---

source/get-started/introduction-mobile.txt

https://jira.mongodb.org/browse/DOCSP-14344
https://docs-mongodborg-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14344/
Specific page where I made the correction: 
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14344/get-started/introduction-mobile
Build log, confirming no new build errors:
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=601c0304ab23346c20f14f03

(DOCSP-14344): Remove unnecessary 'can' based on docs feedback

---

source/node/manage-email-password-users.txt
source/react-native/manage-email-password-users.txt
source/web/manage-email-password-users.txt

…/rn/web]
https://jira.mongodb.org/browse/DOCSP-14254
* Node: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14254-Node-resetPassword-order/node/manage-email-password-users/#complete-a-password-reset
* RN: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14254-Node-resetPassword-order/react-native/manage-email-password-users/#complete-a-password-reset
* Web: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14254-Node-resetPassword-order/web/manage-email-password-users/#complete-a-password-reset

(DOCSP-14254): Fix typo in resetPassword to correct param order [node/rn/web]

---

source/includes/steps-define-custom-user-data-import-export.yaml
source/includes/steps-define-custom-user-data-realm-ui.yaml

(DOCSP-13993): Add User Id Type for Realm Custom User Data
- [Enable Custom User Data > Procedure (Realm UI & CLI)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/custom-user-id/users/enable-custom-user-data/#procedure)
^ Each changed page maps to a tabbed procedure

(DOCSP-13993): Add User Id Type for Realm Custom User Data

---

source/sdk/ios/examples/modify-an-object-schema.txt
source/sdk/ios/fundamentals/schema-versions-and-migrations.txt

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/new-ia-ios-versions/sdk/ios/fundamentals/schema-versions-and-migrations/
Bonus: includes link to https://github.com/realm/realm-cocoa/pull/7102 content

Add schema versions and migrations page to iOS

---

source/sdk/android/fundamentals/object-models-and-schemas.txt
source/sdk/ios/fundamentals.txt
source/sdk/ios/fundamentals/object-models-and-schemas.txt

Adapted from Android. A lot of this is covered in the usage examples so I kept it more high-level.
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/new-ia-ios-schemas/sdk/ios/fundamentals/object-models-and-schemas/

Add iOS object schemas page

---

source/sdk/android/advanced-guides.txt
source/sdk/dotnet/advanced-guides.txt

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/resets/sdk/android/advanced-guides/client-reset/
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/resets/sdk/dotnet/advanced-guides/client-reset/

add link to Client Reset in dotnet and android SDKs

---

source/includes/steps-install-android.yaml

https://jira.mongodb.org/browse/DOCSP-14674
- made the existing (ty Chris Bush) explanation clearer (it's not that you *can* enable sync, it's that you *must* to use any sync functionality)
- added an addtional note to make the local use-case even more obvious (alternative is a "local" vs. "sync" tab for the full gradle file example)
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14674/sdk/android/install/#add-realm-to-the-application-level-build-gradle-file

(DOCSP-14674): Make Sync optional in the Install guide - Android

---

examples/node/Examples/sync-changes-between-devices.js
source/examples/generated/node/sync-changes-between-devices.codeblock.sync-changes-between-devices-perform-a-client-reset.js
source/sdk/node/advanced.txt
source/sdk/node/advanced/client-reset.txt
source/sdk/node/examples/sync-changes-between-devices.txt

https://jira.mongodb.org/browse/DOCSP-14353
* Sync Changes Between Devices > "Perform a Client Reset" Subsection: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14353-Node-Client-Resets/sdk/node/examples/sync-changes-between-devices/#perform-a-client-reset
* Node Client Reset Doc: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14353-Node-Client-Resets/sdk/node/advanced/client-reset/#std-label-node-client-resets

(DOCSP-14353): Node Client Resets Documentation

---

source/security.txt

- Adds a table to the reference/firewall-configuration page
https://jira.mongodb.org/browse/DOCSP-13655
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/firewall/security/

(DOCSP-13655): Add a list of Realm IPs to Realm Security

---

source/admin/api/v3.txt

In preparation for changes to the default way the `openapi` directive is parsed in the upcoming snooty release, we will be requiring the addition of the `uses-rst` flag for this repo's use case. Adding this flag will allow snooty to parse the contents of the OpenAPI spec file as it currently does.
The staging link below should show the contents rendered the same as it is on the actual site. Please feel free to merge this in after tomorrow's release. Thank you!
Staging link:
[Realm - /admin/api/v3](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/snooty-test-24022021/admin/api/v3/#resources)

Add :uses-rst: flag to openapi directive

---

examples/node/Examples/mongodb.js
examples/node/Examples/mongodb.ts
source/examples/generated/node/mongodb.codeblock.watch-a-collection-with-filter.js
source/examples/generated/node/mongodb.codeblock.watch-a-collection-with-filter.ts
source/examples/generated/node/mongodb.codeblock.watch-a-collection.js
source/examples/generated/node/mongodb.codeblock.watch-a-collection.ts
source/react-native/mongodb.txt
source/sdk/node/examples/query-mongodb.txt
source/web/mongodb.txt

Note: We should have a followup PR that regenerates all the examples in `/source/examples/<sdk>` instead of the full project structure that we currently use for most generated examples (i.e. with start/final states)
(DOCSP-14870): Fix filtered watch() example for web
- [Node.js > Query MongoDB > Watch for Changes in a Collection](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/watch-fix/sdk/node/examples/query-mongodb/#watch-for-all-changes-in-a-collection)
- Identical copies in rn/web docs

(DOCSP-14870): Fix filtered watch() example for web

---

source/includes/android-synchronous-reads-writes-ui-thread.rst
source/sdk/android/examples/open-and-close-a-local-realm.txt
source/sdk/android/examples/read-and-write-data.txt

https://jira.mongodb.org/browse/DOCSP-14603
- because the MongoDB Realm SDK disables synchronous operations on the UI thread by default, I'm just making the warning about this option more visible by including it on the "open a realm" page, and in both the "reads" and "writes" sections of the "read and write" page. Since UI thread sync operations are harder to do now, the ANR warning isn't really relevant any more.
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14603/sdk/android/examples/open-and-close-a-local-realm/#local-realm-configuration (new important admonition include)
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14603/sdk/android/examples/read-and-write-data/#read-from-realm-database (new important admonition …

(DOCSP-14603): Android UI Thread Reads & Writes

---

examples/node/Examples/open-and-close-a-local-realm.js
source/examples/generated/node/open-and-close-a-local-realm.codeblock.open-local-realm-synchronously.js
source/sdk/node/examples/open-and-close-a-local-realm.txt
source/sdk/react-native/examples/open-and-close-a-local-realm.txt

* https://jira.mongodb.org/browse/DOCSP-14626
* https://jira.mongodb.org/browse/DOCSP-14630
* Node: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14626-the-default-realm-js/sdk/node/examples/open-and-close-a-local-realm/
* React Native: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14626-the-default-realm-js/sdk/react-native/examples/open-and-close-a-local-realm/
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6042821975e817aef7ec3c60

(DOCSP-14626 & DOCSP-14630): Info about default realm + opening a local realm synchronously

---

config/redirects

Updates redirects to use canonical (with `/`) URLs to avoid an extra redirection step. This is part of the Croud SEO project that we're working on with Marketing.
https://jira.mongodb.org/browse/DOP-1883

DOP-1883: use canonical links for redirects

---

source/sdk/android.txt

Turns out the TOC links are also causing redirection woes 😁 
https://jira.mongodb.org/browse/DOP-1883
https://docs-mongodborg-staging.corp.mongodb.com/realm/docsworker-xlarge/DOP-1883-TOC/
Alternative solution would be to add `/kotlin-extensions/` after `10.3.1` for Kotlin and a trailing slash to the Javadoc link, but this seems like it would save some maintenance burden? Let me know what y'all would prefer.

DOP-1883:Update links to Android SDK to /latest

---

source/sdk/android/examples/react-to-changes.txt

https://jira.mongodb.org/browse/DOCSP-14623
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14623/sdk/android/examples/react-to-changes/#register-a-realm-change-listener (note at bottom of section)

(DOCSP-14623): Reusing RealmResults and RealmObjects, Android

---

examples/ios/Examples/ObjectModels.m
source/sdk/ios/data-types/supported-property-types.txt

Couple of notes:
- The property cheat sheet from the Realm legacy doc site lists Float, which is not on our current page listing supported property types, but there are tests for it in the realm-cocoa repo.
- The property cheat sheet page from the Realm legacy docs does _not_ list Decimal128, which _is_ on our current page listing supported property types, so I've attempted to add appropriate declarations, but would love confirmation that I've done it correctly.
The Jira ticket doesn't request the Objective-C property cheatsheet, but since both tabs exist in our current documentation set, I've ported over the Objective-C properties, too.
https://jira.mongodb.org/browse/DOCSP-14644
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14644/sdk/ios/data-types/suppor …

(DOCSP-14644) Add Property Cheatsheet for both Swift and Objective-C

---

source/includes/steps-development-mode-cli.yaml
source/sync/enable-development-mode.txt

https://jira.mongodb.org/browse/DOCSP-14952
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14952-Enable-Development-Mode/sync/enable-development-mode/

(DOCSP-14952): Update Enable Development Mode to CLI V2

---

examples/android/local/app/src/androidTest/java/com/mongodb/realm/examples/java/ThreadingTest.java
examples/android/local/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/ThreadingTest.kt
source/examples/generated/android/local/ThreadingTest.codeblock.freeze-objects.java
source/examples/generated/android/local/ThreadingTest.codeblock.freeze-objects.kt
source/examples/generated/android/local/ThreadingTest.codeblock.refresh-realm.java
source/examples/generated/android/local/ThreadingTest.codeblock.refresh-realm.kt
source/sdk/android/advanced-guides/threading.txt
source/sdk/android/data-types/counters.txt

https://jira.mongodb.org/browse/DOCSP-14602
Also includes a small fix to remove mentions of CRDTs from the Counters page (the mention of CRDTs in the realm.io docs was erroneous)
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14602/sdk/android/advanced-guides/threading/ (freeze objects and refresh examples)

(DOCSP-14602): Threading examples

---

examples/ios/Examples/ReadWriteData.swift
source/examples/generated/code/start/ReadWriteData.codeblock.object-id-model.swift
source/examples/generated/code/start/ReadWriteData.codeblock.query-object-id.swift
source/sdk/ios/examples/filter-data.txt
source/sdk/ios/examples/read-and-write-data.txt

Users can fall into the trap 
https://jira.mongodb.org/browse/DOCSP-15144
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fruit/sdk/ios/examples/read-and-write-data/#filter-on-object-id-properties
and new warning here:
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fruit/sdk/ios/examples/filter-data/#comparison-operators

(DOCSP-15144): Add ObjectId comparison example

---

source/deploy/deploy-cli.txt
source/includes/steps-deploy-cli.yaml
source/reference/cli-auth-with-api-token.txt

- (DOCSP-14963): [CLI V2] Deploy with Realm CLI
- (DOCSP-14964): [CLI V2] Realm CLI Authenticate With API Token
- [Deploy with Realm CLI](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli-guides/deploy/deploy-cli)
- [Realm CLI Authenticate With API Token](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli-guides/reference/cli-auth-with-api-token) **(No significant changes)**

[CLI V2] Generic CLI Deploy

---

source/config/data_sources.txt
source/includes/steps-enable-wire-protocol-import-export.yaml
source/includes/steps-link-a-data-source-import-export.yaml
source/includes/steps-specify-cluster-read-preference-import-export.yaml
source/mongodb/enable-wire-protocol-connections.txt
source/mongodb/link-a-data-source.txt
source/mongodb/specify-cluster-read-preference.txt

- (DOCSP-14945): [CLI V2] Link a MongoDB Data Source
- (DOCSP-14946): [CLI V2] Specify Read Preference for a MongoDB Cluster
- (DOCSP-14947): [CLI V2] Enable Wire Protocol Connections
- [Link a MongoDB Data Source](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli-datasource/mongodb/link-a-data-source)
- [Specify Read Preference for a MongoDB Cluster](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli-datasource/mongodb/specify-cluster-read-preference)
- [Enable Wire Protocol Connections](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli-datasource/mongodb/enable-wire-protocol-connections)

[CLI V2] MongoDB Data Source Configuration

---

source/config/auth.txt
source/config/data_sources.txt
source/config/http_endpoints.txt
source/config/services.txt
source/graphql/expose-data.txt
source/includes/extracts-service-actions.yaml
source/includes/steps-create-a-service-webhook-cli.yaml
source/includes/steps-define-custom-user-data-import-export.yaml
source/services/configure/service-webhooks.txt
source/services/http.txt
source/users/enable-custom-user-data.txt

- (DOCSP-14936): [CLI V2] Enable Custom User Data
- (DOCSP-14953): [CLI V2] Expose Data in a Collection
- (DOCSP-14957): [CLI V2] HTTP Service
- (DOCSP-14956): [CLI V2] Configure Service Webhooks
- [Enable Custom User Data](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli-grabbag/users/enable-custom-user-data)
- [Expose Data in a Collection](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli-grabbag/graphql/expose-data)
- [HTTP Service](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli-grabbag/services/http)
- [Configure Service Webhooks](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli-grabbag/services/configure/service-webhooks) …

[CLI V2] Custom User Data, GraphQL, and Incoming Webhooks

---

source/hosting/enable-hosting.txt
source/hosting/flush-the-cdn-cache.txt
source/hosting/host-a-single-page-application.txt
source/hosting/use-a-custom-404-page.txt
source/hosting/use-a-custom-domain-name.txt
source/includes/steps-enable-hosting-import-export.yaml
source/includes/steps-flush-the-cdn-cache-import-export.yaml
source/includes/steps-host-a-single-page-application-code-deploy.yaml
source/includes/steps-use-a-custom-404-page-import-export.yaml
source/includes/steps-use-a-custom-domain-name-import-export.yaml

- (DOCSP-14958): [CLI V2] Enable Hosting
- (DOCSP-14959): [CLI V2] Flush the CDN Cache
- (DOCSP-14959): [CLI V2] Host a Single-Page Application
- (DOCSP-14961): [CLI V2] Use a Custom 404 Page
- (DOCSP-14962): [CLI V2] Use a Custom Domain Name
- [Enable Hosting](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli-hosting/hosting/enable-hosting)
- [Flush the CDN Cache](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli-hosting/hosting/flush-the-cdn-cache)
- [Host a Single-Page Application](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli-hosting/hosting/host-a-single-page-application)
- [Use a Custom 404 Page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli-hosting/hosting/use-a-custom …

[CLI V2] Static Hosting

---

source/sdk/ios/advanced-guides.txt
source/sdk/ios/advanced-guides/auxiliary-files.txt

The Realm IA doc says this should go under Advanced Guides.
https://jira.mongodb.org/browse/DOCSP-14642
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/carb/sdk/ios/advanced-guides/auxiliary-files/

Port iOS 'auxiliary files' page

---

examples/ios/Examples/Functions.swift
source/examples/generated/code/start/Functions.codeblock.call-a-function.swift

The Functions example test was failing, with an error: `Unexpected non-double result: int64(3)`
@cbush noted a recent change to the JS VM caused similar issues for someone else. This fix resolves the issue.

Update function example to fix failing test

---

tutorial/dotnet/realm-tutorial-dotnet/LoginPage.xaml

There has been a long-standing iOS issue of the OS initial-capping the user's logon info. This fixes it.

finally fix auto-cap on iOS

---

source/tutorial/realm-app.txt

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/tutorial-backend-tip/tutorial/realm-app/#e.-use-the-realm-cli-to-create-a-new-task-tracker-backend-realm-app

Add tip to refer to app-configuration for backend tutorial

---

examples/ios/Examples/LocalOnlyCompleteQuickStart.swift
examples/ios/Examples/ReadWriteData.m
examples/ios/Examples/ReadWriteData.swift
source/examples/generated/code/start/LocalOnlyCompleteQuickStart.codeblock.complete-quick-start-local.swift
source/examples/generated/code/start/ReadWriteData.codeblock.copy-to-another-realm.m
source/examples/generated/code/start/ReadWriteData.codeblock.copy-to-another-realm.swift
source/sdk/ios/examples/read-and-write-data.txt

- Add obj-c and swift code example
- Change to LocalOnly is due to SwiftLint
https://jira.mongodb.org/browse/DOCSP-14647
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/carb5/sdk/ios/examples/read-and-write-data/#copy-an-object-to-another-realm

(DOCSP-14647): Port 'Copying objects between Realms' to Usage Examples

---

examples/ios/Examples/ReadWriteData.swift
source/examples/generated/code/start/ReadWriteData.codeblock.key-value-coding.swift
source/examples/generated/code/start/ReadWriteData.codeblock.models.swift
source/sdk/ios/examples/read-and-write-data.txt

Porting the KVC example from Realm.io legacy docs.
https://jira.mongodb.org/browse/DOCSP-14653
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14653/sdk/ios/examples/read-and-write-data/#update-properties-with-key-value-coding

(DOCSP-14653): Add key-value coding to docs

---

source/openapi-admin-v3.yaml

_**NOTE: The param is actually lowercase "atlas", not "Atlas"**_
(DOCSP-15199): Add 'product=Atlas' as a possible parameter for the /apps Admin API endpoint
- [GET /​groups/​{groupId}/​apps](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/atlas-query-param/admin/api/v3/#get-/groups/%7Bgroupid%7D/apps)

(DOCSP-15199): Add 'product=Atlas' as a possible parameter for the /apps Admin API endpoint

---

config/redirects
examples/ios/Examples/Encrypt.swift
examples/ios/Examples/ReadWriteData.swift
source/examples/generated/code/start/Encrypt.codeblock.background-app-refresh-encryption.swift
source/sdk/ios.txt
source/sdk/ios/examples.txt
source/sdk/ios/examples/configure-and-open-a-realm.txt
source/sdk/ios/examples/sync-changes-between-devices.txt
source/sdk/ios/fundamentals/realms.txt
source/sdk/node/examples.txt

- Not sure where this should go. Added "Considerations" to Realms fundamentals page.
- Theoretical Swift example doesn't need to be Bluehawked?
https://jira.mongodb.org/browse/DOCSP-14649
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/carb4/sdk/ios/examples/configure-and-open-a-realm/

(DOCSP-14649): Port "Initializing Swift properties using Realm APIs"

---

source/sdk/ios/advanced-guides/threading.txt
source/sdk/ios/fundamentals/object-models-and-schemas.txt
source/sdk/ios/fundamentals/realms.txt

https://jira.mongodb.org/browse/DOCSP-14639
New sections on the [Fundamentals -> Realms page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14639/sdk/ios/fundamentals/realms): 
- File Size
- Default Realm
New section on [Fundamentals -> Object Models & Schemas page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14639/sdk/ios/fundamentals/object-models-and-schemas/#property-attributes):
- Property Attributes

(DOCSP-14639): Port info about default realms, file size, and property attributes

---

.github/workflows/check-autobuilder.yml
source/sdk.txt
tools/autobuilder/src/index.ts

- Update autobuilder checker for new backend log style
- Reduce time waiting for ongoing builds if none exists

Fix Autobuilder CI

---

source/includes/realm-studio.rst
source/index.txt
source/studio.txt

The linked Jira ticket is for providing a prominent place per SDK for Realm Studio, but we're giving it a prominent place at top-level ToC, so I think that satisfies this ticket. After we merge this, I'll add links to any SDK debugging pages to point to the top-level Realm Studio page.
- https://jira.mongodb.org/browse/DOCSP-12903
- [Realm Studio](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-12903/studio/)

(DOCSP-12903): Add a Realm Studio page to the top-level ToC

---

examples/ios/Examples/Compacting.m
examples/ios/Examples/Compacting.swift
examples/ios/RealmExamples.xcodeproj/project.pbxproj
source/examples/generated/code/start/Compacting.codeblock.compacting.m
source/examples/generated/code/start/Compacting.codeblock.compacting.swift
source/sdk/ios/advanced-guides.txt
source/sdk/ios/advanced-guides/compacting.txt

The scope of this ticket is to port the content from the [compacting realms section of the legacy Swift docs](https://docs.mongodb.com/realm-legacy/docs/swift/latest/index.html#compacting-realms).
Specifically, this documentation covers `shouldCompactOnLaunch`.
However, PR #929 adds a section about File Size that lists another method to manage compacting: `writeCopy(toFile:encryptionKey:)`. That isn't covered in the legacy documentation.
I do plan to link between the two places, so it seems a bit odd to me that the File Sizes page lists two methods to manage compacting a Realm, but the actual page on compacting makes no mention of the second method. However, that seems out of scope for this ticket on porting legacy content.
Thoughts on how to proceed, reviewer?
- …

(DOCSP-14632): Port content on compacting from legacy Swift docs

---

source/security.txt

Context: https://mongodb.slack.com/archives/CLY6HQWUE/p1617641307068700
Staging link:
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/security-ip-hotfix/security/

Hotfix for security page incorrect IP

---

source/admin/api/v3.txt
source/graphql/custom-resolvers.txt
source/mongodb/query-roles.txt
source/triggers/trigger-snippets.txt

- snooty started to yell at us about duplicate contents directives on pages
- I removed the duplicates to stop the yelling
Errors:
ERROR(mongodb/query-roles.txt:56ish): Directive "contents" should only appear once per page
ERROR(triggers/trigger-snippets.txt:24ish): Directive "contents" should only appear once per page
ERROR(triggers/trigger-snippets.txt:115ish): Directive "contents" should only appear once per page
ERROR(graphql/custom-resolvers.txt:31ish): Directive "contents" should only appear once per page
ERROR(admin/api/v3.txt:166ish): Directive "contents" should only appear once per page
- [multiple pages](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/oneContentsDirPerPage/)

Removed duplicate contents directives on pages

---

source/sdk/ios/fundamentals/object-models-and-schemas.txt
source/sdk/ios/fundamentals/realms.txt
source/studio.txt

From the legacy doc [Swift: FAQ](https://docs.mongodb.com/realm-legacy/docs/swift/latest/index.html#faq)
I did not port content for:
- Is Realm open source?
- I see a network call to Mixpanel when I run my app
The first question seemed more like a top-level Realm docs question than a Realm Swift question, and I'm not sure it warrants a FAQ. 
The second bullet also seems to apply to more than just the Swift SDK, and I was uncertain how/where we'd want to comment on this, if at all. The example linked to in the ["source code" link](https://github.com/realm/realm-cocoa/blob/master/Realm/RLMAnalytics.mm) is the Realm Cocoa implementation of analytics, but I found stuff in several of the SDK repos related to this, so I think it applies more broadly.
And finally, I added info on finding the …

(DOCSP-14643): Port Swift FAQ info from Realm.io

---

source/get-started/create-realm-app.txt

"in your project" was repeated twice. Per feedback widget.

Fix typo in create-realm-app

---

source/sdk/android/examples/open-and-close-a-local-realm.txt
source/sdk/android/examples/sync-changes-between-devices.txt

- https://jira.mongodb.org/browse/DOCSP-15424
- [Set the Client Log Level (section)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15424/sdk/android/examples/open-and-close-a-local-realm/#set-the-client-log-level)

(DOCSP-15424): Set the Client Log Level move onto a sync-agnostic page

---

source/includes/steps-install-android.yaml

In android install documentation, jcenter() needs to be added into the repositories block, not dependencies block.

Fix android install steps - jcenter block

---

source/sdk/ios/examples/sync-changes-between-devices.txt

I've written a new section for this page: "Decide How to Open the Realm." This covers in more detail when to use `init` vs. `asyncOpen` when opening a realm.
- https://jira.mongodb.org/browse/DOCSP-12392
- [Sync Changes Between Devices: Decide How to Open the Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-12392/sdk/ios/examples/sync-changes-between-devices/#decide-how-to-open-the-realm)

(DOSCP-12392): [iOS] Clarify when to use init vs. asyncOpen

---

source/includes/embedded-object-json-schema.rst
source/sdk/ios/data-types/embedded-objects.txt

- Fixes embedded object JSON schema type declarations (shared across all SDKs)
- Slightly updates iOS Embedded Objects page to match other SDKs
- https://jira.mongodb.org/browse/DOCSP-15728
- [Embedded Objects (iOS)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/schema/sdk/ios/data-types/embedded-objects/)

(DOCSP-15728): JSON Schema declaration for embedded objects is incorrect

---

examples/ios/Examples/AnyRealmValue.swift
examples/ios/Examples/Models.swift
examples/ios/Examples/ObjectModels.swift
examples/ios/Podfile.lock
examples/ios/RealmExamples.xcodeproj/project.pbxproj
source/examples/generated/code/start/AnyRealmValue.codeblock.mixed-data-type.swift
source/examples/generated/code/start/Models.codeblock.person-model.swift
source/examples/generated/code/start/ObjectModels.codeblock.optional-required-properties.swift
source/examples/generated/code/start/ObjectModels.codeblock.realm-object-enum.swift
source/sdk/ios/data-types/supported-property-types.txt
source/sdk/ios/examples/define-a-realm-object-model.txt
source/sdk/ios/examples/filter-data.txt
source/sdk/ios/fundamentals/object-models-and-schemas.txt

The links to Jazzy docs for `RealmProperty` and `AnyRealmValue` are broken currently, but I believe they'll be valid once the auto-generated docs are updated.
As part of this work, I updated the docs where `RealmOptional` was specified. In most instances where, I replaced `RealmOptional` with `RealmProperty`, but on the Supported Properties page, I also added directives about the version in which this change occurred. I don't know the version number yet; I'll update that before I publish the docs.
I also updated the code examples that used `RealmOptional` to use `RealmProperty` and generated updated snippets with Bluehawk.
- https://jira.mongodb.org/browse/DOCSP-14568
- [Supported Property Types](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14568/sdk/ios/d …

(DOCSP-14568): [iOS] Add mixed type to Supported Property Types

---

examples/node/Examples/data-types.js
source/examples/generated/node/data-types.codeblock.create-an-embedded-object.js
source/examples/generated/node/data-types.codeblock.define-embedded-objects.js
source/examples/generated/node/data-types.codeblock.delete-an-embedded-object.js
source/examples/generated/node/data-types.codeblock.overwrite-an-embedded-object.js
source/examples/generated/node/data-types.codeblock.query-an-embedded-object.js
source/examples/generated/node/data-types.codeblock.update-an-embedded-object.js
source/sdk/node/data-types/embedded-objects.txt
source/sdk/node/fundamentals/relationships-and-embedded-objects.txt

- https://jira.mongodb.org/browse/DOCSP-15613
- [Node.js SDK > Data Types > Embedded Objects](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/Nodejs-embedded-objects-type/sdk/node/data-types/embedded-objects/)

(DOCSP-15613): Node.js embedded objects type

---

examples/node/Examples/data-types.js
source/examples/generated/node/data-types.codeblock.create-objects-with-mixed-values.js
source/examples/generated/node/data-types.codeblock.define-mixed-in-schema.js
source/examples/generated/node/data-types.codeblock.query-objects-with-mixed-values.js
source/sdk/node/data-types/mixed.txt

Docsp 14569 mixed data type

---

examples/node/Examples/data-types.js
examples/node/package-lock.json
examples/node/package.json
source/examples/generated/node/data-types.codeblock.add-a-listener-to-a-dictionary.js
source/examples/generated/node/data-types.codeblock.create-realm-obj-with-dictionary.js
source/examples/generated/node/data-types.codeblock.define-dictionary-in-schema.js
source/examples/generated/node/data-types.codeblock.query-a-dictionary.js
source/examples/generated/node/data-types.codeblock.remove-fields-of-the-dictionary.js
source/examples/generated/node/data-types.codeblock.set-additional-fields.js
source/examples/generated/node/data-types.codeblock.setting-new-dictionaries-to-existing-objects.js
source/examples/generated/node/data-types.codeblock.update-a-dictionary.js
source/sdk/node/data-types/dictionaries.txt

- https://jira.mongodb.org/browse/DOCSP-14565
- [Node.js > Data Types > Dictionary](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14565-Dictionary-Data-Type/sdk/node/data-types/dictionaries/)

(DOCSP-14565): Dictionary data type

---

examples/ios/Examples/ManageEmailPasswordUsers.m
examples/ios/Examples/ManageEmailPasswordUsers.swift
examples/ios/Podfile
examples/ios/Podfile.lock
examples/ios/RealmExamples.xcodeproj/project.pbxproj
source/examples/generated/code/start/ManageEmailPasswordUsers.codeblock.password-reset-function.swift
source/sdk/ios/examples/manage-email-password-users.txt

- https://jira.mongodb.org/browse/DOCSP-16089
- [Manage Email Password Users -> Run a Password Reset Function (New section)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16089/sdk/ios/examples/manage-email-password-users/#run-a-password-reset-function)
- [Manage Email Password Users -> Reset a User's Password (new verbiage above code examples)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16089/sdk/ios/examples/manage-email-password-users/#reset-a-user-s-password)

(DOCSP-16089): Draft section for running a password reset func, add Bluehawked example

---

examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/java/ManageEmailPasswordTest.java
examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/ManageEmailPasswordTest.kt
source/examples/generated/android/sync/ManageEmailPasswordTest.codeblock.run-password-reset-func.java
source/examples/generated/android/sync/ManageEmailPasswordTest.codeblock.run-password-reset-func.kt
source/sdk/android/examples/email-password-users.txt

- https://jira.mongodb.org/browse/DOCSP-16146
- [Manage Email/Password Users -> Run a Password Reset Function](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16146/sdk/android/examples/email-password-users/#run-a-password-reset-function):  new section
- [Manage Email/Password Users -> Reset a User's Password](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16146/sdk/android/examples/email-password-users/#reset-a-user-s-password): new verbiage before email reset section

(DOCSP-16146): Add run a password reset function to Android

---

source/includes/steps-tutorial-android-kotlin.yaml
tutorial/kotlin-android/app/src/main/java/com/mongodb/tasktracker/TaskTracker.kt

- fixing a crash due to an undefined `lateinit` variable in the `start` tutorial branch of android (credit goes to @dacharyc for discovering this)
- [Android Tutorial - Create the Realm App](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/android-tutorial-as-advertised/tutorial/android-kotlin/#create-the-realm-app)

Android App should display login screen in start state

---

examples/node/Examples/data-types.js
source/examples/generated/node/data-types.codeblock.add-items-to-set.js
source/examples/generated/node/data-types.codeblock.check-if-set-has-items.js
source/examples/generated/node/data-types.codeblock.check-set-size.js
source/examples/generated/node/data-types.codeblock.create-set-objects.js
source/examples/generated/node/data-types.codeblock.define-set-objects.js
source/examples/generated/node/data-types.codeblock.remove-all-items-from-set.js
source/examples/generated/node/data-types.codeblock.remove-specific-item-from-set.js
source/sdk/node/data-types/sets.txt

- https://jira.mongodb.org/browse/DOCSP-14573
- [Node.js > Data Types > Sets](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14573-Set-Data-Type/sdk/node/data-types/sets/)

(DOCSP-14573): set data type

---

source/tutorial/realm-app.txt

CLI v2 errors out and creates the app but doesn't create all the other app content
CLI 1.1.0 silently fails but has the same end result
CLI 1.3.4 is the way
- [backend app tutorial -- install realm cli](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli-that-actually-works-tutorial/tutorial/realm-app/#c.-install-the-realm-cli)

realm-cli version fix -- tutorial backend setup

---

source/sdk/android/data-types/realmset.txt
source/sdk/ios/data-types/collections.txt

For the reviewer: this ended up being minor. I already had info about it in a `See also` on the iOS page, so I added some more method names there. Android doesn't really have the set-specific methods that we were requested to highlight. And [.Net already links to HashSet](https://docs.mongodb.com/realm/sdk/dotnet/data-types/sets/) where those methods are documented. So I think this is mostly taken care of already, and has just involved some minor tweaks.
- https://jira.mongodb.org/browse/DOCSP-16164
- [Collections (iOS)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16164/sdk/ios/data-types/collections/#mutableset): Updated `See also` at the bottom of the MutableSet section
- [RealmSet (Android)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docswo …

(DOCSP-16164): Add info about set methods where applicable

---

source/includes/steps-tutorial-android-kotlin.yaml
source/tutorial/generated/code/final/ProjectActivity.codeblock.fetch-synced-user-safely.kt
source/tutorial/generated/code/final/ProjectActivity.codeblock.set-up-user-realm.kt
source/tutorial/generated/code/final/ProjectActivity.codeblock.user-init-change-listener.kt
source/tutorial/generated/code/final/TaskActivity.codeblock.fetch-tasks-for-project-sorted-by-id.kt
source/tutorial/generated/code/final/TaskAdapter.codeblock.change-task-status.kt
source/tutorial/generated/code/final/TaskAdapter.codeblock.delete-task.kt
source/tutorial/generated/code/final/TaskTracker.codeblock.initialize-realm-and-create-app.kt
tutorial/kotlin-android/app/src/main/java/com/mongodb/tasktracker/LoginActivity.kt
tutorial/kotlin-android/app/src/main/java/com/mongodb/tasktracker/MemberActivity.kt
tutorial/kotlin-android/app/src/main/java/com/mongodb/tasktracker/ProjectActivity.kt
tutorial/kotlin-android/app/src/main/java/com/mongodb/tasktracker/TaskActivity.kt
tutorial/kotlin-android/app/src/main/java/com/mongodb/tasktracker/TaskTracker.kt
tutorial/kotlin-android/app/src/main/java/com/mongodb/tasktracker/model/Project.kt
tutorial/kotlin-android/app/src/main/java/com/mongodb/tasktracker/model/Task.kt
tutorial/kotlin-android/app/src/main/java/com/mongodb/tasktracker/model/TaskAdapter.kt
tutorial/kotlin-android/app/src/main/java/com/mongodb/tasktracker/model/User.kt

- Enables personal project writes in the Android tutorial even when permissions/functions/triggers have not been set up.
- Still requires email/password auth (with automatic confirmation) and Sync enabled with a required String partition key named `_partition`.
- [Android Tutorial - Implement the Projects List](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/android-tutorial-ian-fix/tutorial/android-kotlin/#implement-the-projects-list)

Android Tutorial: Failing Upwards

---

source/includes/steps-tutorial-android-kotlin.yaml

Few more minor tweaks:
- Move a paragraph describing where logic is stored to above the list of files, so users have a bit more orientation as to what's where in the project structure _before_ they start going through the files. Change `models` to `model` to match the project structure
- The todos in the `ProjectActivity.kt` for `onStop()` and `onDestroy()` are in the opposite order as they're listed here in the tutorial doc. Swapping stop/destroy code snippets here in the tutorial doc so they're in the same order in both places.
- `ProjectActivity` was listed twice in one section, but I think one of them was supposed to be `TaskActivity` so I've swapped it here
- https://jira.mongodb.org/browse/DOCSP-16175
- [Android Kotlin Tutorial](https://docs-mongodbcom-staging.corp.mongodb.com/realm/ …

(DOCSP-16175): Android tutorial maintenance - minor tweaks and fixes

---

source/sdk.txt

I've been thinking more about the user journey of folks who come to the Realm docs, and some of the discussions we've had about discoverability and IA, and thought this might be a nice quick win for fruit day:
Added three new sections to the Realm SDK landing page:
- CRUD Operations
- User Management
- Application Lifecycle
How do we feel about these buckets? Do we think things are missing/misplaced?
- [Realm SDKs landing page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/improve-sdk-docs-discoverability/sdk/)

Fruit Day: Add more SDK docs to landing page to improve user journey/discoverability

---

source/includes/encrypt-use-strong-cryptographic-hash.rst
source/sdk/android/advanced-guides/encryption.txt
source/sdk/dotnet/examples/encrypt-a-realm.txt
source/sdk/ios/advanced-guides/encrypt-a-realm.txt
source/sdk/node/advanced/encrypt.txt
source/sdk/react-native/advanced/encrypt.txt

- https://jira.mongodb.org/browse/DOCSP-16234
This is one new warning inserted as an include on all of the SDK encryption pages:
- [Encrypt a Realm - Android](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16234/sdk/android/advanced-guides/encryption/)
- [Encrypt a Realm - iOS](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16234/sdk/ios/advanced-guides/encrypt-a-realm/)
- [Encrypt a Realm - .Net](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16234/sdk/dotnet/examples/encrypt-a-realm/)
- [Encrypt a Realm - Node.js](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16234/sdk/node/)
- [Encrypt a Realm - React …

(DOCSP-16234): Warn against using cryptographically-weak hashes on SDK encryption pages

---

source/authentication/apple.txt
source/includes/authorization-appleidcredential-string.rst
source/includes/steps-apple-auth-configure.yaml
source/sdk/android/examples/authenticate-users.txt
source/sdk/dotnet/examples/authenticate.txt
source/sdk/ios/examples/authenticate-users.txt
source/sdk/node/examples/authenticate-users.txt
source/sdk/react-native/examples/authenticate-users.txt
source/web/authenticate.txt

- https://jira.mongodb.org/browse/DOCSP-13175
- [Apple ID Authentication](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-13175/authentication/apple/)
New tip added to all of the SDK authentication pages:
- [Authenticate Users - Android SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-13175/sdk/android/examples/authenticate-users/#apple-user)
- [Authenticate Users - iOS SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-13175/sdk/ios/examples/authenticate-users/#apple-user)
- [Authenticate Users - .Net SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-13175/sdk/dotnet/examples/authenticate/#apple-user)
- [Authenticate Users - Node …

(DOCSP-13175): Update Apple ID Authentication walkthrough, add tip to SDKs

---

source/deploy/create-with-cli.txt
source/deploy/realm-cli-reference.txt
source/get-started/create-realm-app.txt

- https://jira.mongodb.org/browse/DOCS-14165
- [Realm CLI Reference -> Import an Application](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCS-14165/deploy/realm-cli-reference/#import-an-application): Added a tip with Project Owner requirement and a link to Atlas docs
- [Create a Realm App with Realm CLI](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCS-14165/deploy/create-with-cli/): Added a "Project Owner" requirement line to the prerequisite about having a programmatic API key, with a link to the Atlas docs
- [Create a Realm App (Realm UI)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCS-14165/get-started/create-realm-app/) Added "Project Owner" requirement to the prerequisites …

(DOCS-14165): Add Atlas Project Owner requirement to create/import Realm App procedures

---

source/mongodb/connect-over-the-wire-protocol.txt

- https://jira.mongodb.org/browse/DOCSP-10137
- [Connect Over the Wire Protocol](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-10137/mongodb/connect-over-the-wire-protocol/): Second paragraph in the overview is new

(DOCSP-10137): Clarify that wire protocol is for languages without SDKs

---

source/sdk/node/data-types/field-types.txt

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/realm-js-link-fix/sdk/node/data-types/field-types/

Quick fix: JS links on field-types page

---

tutorial/rn/ios/Podfile

why are we making our docs users go through an extra step to run the app? the final app should be as close to clone and go as possible - it seems odd to include this since we do not support flpper 

remove flipper

---

source/sdk/android/fundamentals/object-models-and-schemas.txt

- https://jira.mongodb.org/browse/DOCSP-16060
"See also" links on the "fundamentals" Object Models and Schemas page don't link to the correct location in the "examples" Define a Realm Object Model page.
- [All "See also" links on this page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16060/sdk/android/fundamentals/object-models-and-schemas/#primary-keys)
- [anchors on this page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16060/sdk/android/examples/define-a-realm-object-model/)

Bullet point-ify seealso

---

source/functions/built-in-module-support.txt

- Note: built-in punycode is actually deprecated in node (see https://nodejs.org/docs/v10.18.1/api/punycode.html)
- Confirmed in realm-users that the userland version is supported
https://jira.mongodb.org/browse/DOCSP-15057
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/punycode/functions/built-in-module-support/#fully-supported-modules

(DOCSP-15057): Indicate punycode support in built-in modules

---

examples/android/local/app/src/androidTest/java/com/mongodb/realm/examples/java/DataTypesTest.java
examples/android/local/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/DataTypesTest.kt
source/examples/generated/android/local/DataTypesTest.codeblock.realmany-notifications.java
source/examples/generated/android/local/DataTypesTest.codeblock.realmany-notifications.kt
source/examples/generated/android/local/DataTypesTest.codeblock.realmany.java
source/examples/generated/android/local/DataTypesTest.codeblock.realmdictionary-notifications.java
source/examples/generated/android/local/DataTypesTest.codeblock.realmdictionary-notifications.kt
source/examples/generated/android/local/DataTypesTest.codeblock.realmset-notifications.java
source/examples/generated/android/local/DataTypesTest.codeblock.realmset-notifications.kt
source/sdk/android/data-types/realmany.txt
source/sdk/android/data-types/realmdictionary.txt
source/sdk/android/data-types/realmset.txt

Apologies that the links aren't working -- seems to be a platform issue where anchor links, uh, don't work?
- https://jira.mongodb.org/browse/DOCSP-16339
- [RealmAny -- Notifications](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16339/sdk/android/data-types/realmany/#notifications)
- [RealmSet -- Notifications](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16339/sdk/android/data-types/realmset/#notifications)
- [RealmDictionary -- Notifications](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16339/sdk/android/data-types/realmdictionary/#notifications)

(DOCSP-16339): Java SDK 'new' data type notifications

---

source/sdk/android/examples/read-and-write-data.txt

Known issue: the anchor link doesn't work right, so you'll have to ctrl+f for "dependent objects" on the page. DOP issue: https://jira.mongodb.org/browse/DOP-2232
- https://jira.mongodb.org/browse/DOCSP-13154
- [Delete an Object and its Dependent Objects](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-13154/sdk/android/examples/read-and-write-data/#delete-an-object-and-its-dependent-objects)

(DOCSP-13154): Cascading deletes don't really cascade, so rename

---

source/sdk/ios/data-types.txt
source/sdk/ios/data-types/anyrealmvalue.txt
source/sdk/ios/data-types/map.txt
source/sdk/ios/data-types/mutablesets.txt
source/sdk/ios/data-types/supported-property-types.txt
source/sdk/ios/examples/define-a-realm-object-model.txt
source/sdk/ios/fundamentals/object-models-and-schemas.txt

- https://jira.mongodb.org/browse/DOCSP-17063
- [Maps (beta)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17063/sdk/ios/data-types/map/): Add "(beta)" to title, ToC, remove "beta" from "New in version" directive, add `include` for the beta feature note.
- [MutableSets (beta)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17063/sdk/ios/data-types/mutablesets/): Add "(beta)" to title, ToC, remove "beta" from "New in version" directive
- [AnyRealmValue (beta)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17063/sdk/ios/data-types/anyrealmvalue/): Add "(beta)" to title, ToC, remove "beta" from "New in version" directive, point SDK reference doc link to 'latest' instead of a specific beta …

(DOCSP-17063): [iOS] Remove beta designation from 10.8.0 versions, add beta callouts

---

source/openapi-admin-v3.yaml

Correcting links related to secrets to point to updated path.
- https://jira.mongodb.org/browse/DOCSP-17068
- [Realm Admin API -> Create a new Secret](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17068/admin/api/v3/#post-/groups/%7Bgroupid%7D/apps/%7Bappid%7D/secrets)
- [Realm Admin API -> Modify a Secret](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17068/admin/api/v3/#put-/groups/%7Bgroupid%7D/apps/%7Bappid%7D/secrets/%7Bsecretid%7D)
- [Realm Admin API -> Delete a Secret](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17068/admin/api/v3/#delete-/groups/%7Bgroupid%7D/apps/%7Bappid%7D/secrets/%7Bsecretid%7D)

(DOCSP-17068): Change secret link to point to updated path

---

source/openapi-admin-v3.yaml

- https://jira.mongodb.org/browse/DOCSP-16307
- [Realm Administration API -> Event Trigger APIs (both POST and PUT)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16307/admin/api/v3/#post-/groups/%7Bgroupid%7D/apps/%7Bappid%7D/triggers): Add `full_document_before_change` bool to the request body, with a link to the `Preimages` feature which must be enabled to use this functionality

(DOCSP-16307): Add 'full_document_before_change' to trigger endpoint documentation

---

source/functions/json-and-bson.txt

- https://developer.mongodb.com/community/forums/t/is-double-quotes-on-property-names-required-for-bson-ejson-parse/112167
- [JSON & BSON](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/ejson-fix/functions/json-and-bson/)

JSON requires double-quoted property names

---

source/includes/note-beta-feature.rst

[Realm Studio 11.0.0 has released](https://github.com/realm/realm-studio/releases/tag/v11.0.0), which supports the new data types. I've removed the warning about the Realm Studio 11.0.0 beta not supporting the data types from the `include` about the beta state of the new types.
- The warning on any page that features the new data types, such as: [Android -> RealmAny(beta)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/remove-studio-warning/sdk/android/data-types/realmany/)

Remove warning about Realm Studio not supporting the new data types

---

source/tutorial/realm-app.txt

* Adds `@beta` to the CLI install
* Points v1 CLI users to the new [final-v1](https://github.com/mongodb-university/realm-tutorial-backend/tree/final-v1) branch
- (DOCSP-17343): Add note to tutorial for CLI v1 users
- [Set up the Task Tracker Tutorial Backend](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/tutfix/tutorial/realm-app/)

(DOCSP-17343): Add note to tutorial for CLI v1 users

---

source/admin/api/v3.txt

- (DOCSP-17333): [Realm Admin API] Use App._id not App.client_app_id
- [Admin API > Project & Application IDs](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/apifix/admin/api/v3/#std-label-realm-api-project-and-application-ids)

(DOCSP-17333): [Realm Admin API] Use App._id not App.client_app_id

---

source/config/http_endpoints.txt
source/includes/steps-create-a-service-webhook-ui.yaml

- (DOCSP-10284): Webhook settings option for fetching custom user data
- (DOCSP-10285): Webhook settings option for creating a user with application auth
- [Config > HTTP Endpoints > Incoming Webhooks](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/webhooks/config/http_endpoints/#incoming-webhooks)
- [Create a Service Webhook > Configure User Authentication](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/webhooks/services/configure/service-webhooks/#configure-user-authentication-1)

[Webhooks] Application User Settings

---

examples/ios/Examples/ManageEmailPasswordUsers.swift
examples/ios/Podfile
examples/ios/Podfile.lock
source/examples/generated/code/start/ManageEmailPasswordUsers.codeblock.resend-confirmation-email.swift
source/examples/generated/code/start/ManageEmailPasswordUsers.codeblock.retry-confirmation-function.swift
source/sdk/ios/examples/manage-email-password-users.txt

The linked Jira ticket here is just to add an example of the new `retryCustomConfirmation` API, but I realized we don't have the send email method documented either, so I added both.
- https://jira.mongodb.org/browse/DOCSP-16460
- [Manage Email/Password Users](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16460/sdk/ios/examples/manage-email-password-users/#retry-user-confirmation-methods): added the  Retry User Confirmations section, with examples

(DOCSP-16460): Add examples for retrying confirmation methods

---

examples/ios/QuickStartSwiftUI/QuickStart.swift
source/examples/generated/swiftui/local/QuickStart.codeblock.complete-swiftui-combine-quick-start.swift
source/examples/generated/swiftui/local/QuickStart.codeblock.models.swift
source/examples/generated/swiftui/sync/QuickStart.codeblock.complete-swiftui-combine-quick-start.swift
source/examples/generated/swiftui/sync/QuickStart.codeblock.models.swift
source/sdk/ios/integrations/swiftui.txt

- https://jira.mongodb.org/browse/DOCSP-17493
- [Use Realm Database with SwiftUI and Combine](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17493/sdk/ios/integrations/swiftui/): 
- Added SDK version requirement to Prerequisites section
- Updated code examples to show: 
- `@Persisted` syntax
- New way of declaring `primaryKey` 
- More performant `ObjectId`
- New way of declaring `LinkingObjects`
Note for @cbush: when I updated the `LinkingObjects` syntax, I got an error message until I added `@Persisted` to the `var items` in line 62. It was _not_ declared as `@objc dynamic` in the pre-10.10.0 version of this app. Confirmed the app works with this syntax, but am wondering if I'm missing some reason to have not done it this way. …

(DOCSP-17493): Update SwiftUI example app for cocoa 10.10.0 syntax

---

source/sdk.txt

I noticed the Android card on the new SDK landing page is the only one that doesn't mention the SDK's languages. This PR adds Java and Kotlin to the Android card.
- [Realm SDKs](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/update-sdk-lp/sdk/): Update the Android card

Update Android card on SDK landing page

---

examples/kmm/shared/src/commonMain/kotlin/com/mongodb/realm/realmkmm/Greeting.kt
source/examples/generated/kmm/Greeting.codeblock.change-listeners.kt
source/sdk/kotlin-multiplatform.txt
source/sdk/kotlin-multiplatform/frozen-arch.txt

Response to feedback on [this PR](https://github.com/mongodb/docs-realm/pull/1229).
Major changes (still not very big) to:
- the landing page, specifically the alpha warning (downgraded to "important" yellow box, less spooky wording)
- the frozen arch page, added explicit Flow change listening since before we observed but didn't actually do anything
- small wording fix related to freezing live objects retrieved in write transactions
- added more information about write transactions implicitly advancing a frozen realm's version
- [Kotlin Multiplatform SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/christian-comments-kmm-sdk/sdk/kotlin-multiplatform/)

Christian/Nabil feedback on Kotlin Multiplatform 0.4.0 docs update

---

source/includes/steps-enable-sync-ui.yaml

- https://jira.mongodb.org/browse/DOCSP-17462
- [Realm Sync > Get Started with Sync#Sync Data from a Client](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17462-missing-csharp-syncdata-link/sync/get-started/#sync-data-from-a-client)

(DOCSP-17462): Add Missing .NET Link in /sync/get-started

---

source/sdk/android/fundamentals/object-models-and-schemas.txt

The [current documentation](https://docs.mongodb.com/realm/sdk/android/fundamentals/object-models-and-schemas/#primary-keys), which uses the `versionadded` directive, currently displays the following nonsensical text:
*New in version Since*: version 10.6.0, Realm Database automatically indexes primary keys.
Changed to a note to make this clearly not broken for readers.
[Staging Build](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/version-added-to-note/sdk/android/fundamentals/object-models-and-schemas/#primary-keys)

Change nonsensical version added to note

---

tutorial/rn/providers/TasksProvider.js

The example app in the MongoDB Realm documentation implements Sync, but is not really offline capable. The example app using Realm Sync does not actually illustrate offline-first: Once offline no tasks will be loaded, and even online the unmodified app took between 1000 and 4000 ms (depending on server region) to load a handful of tasks, which shows it is loading these from the MongoDB Atlas server first.
I have tested both the iOS Swift and the React Native 'Task Tracker' app and they are for the most part not offline-first capable as currently implemented.
Try to disconnect from the network while in the 'Projects' view of the app. Then click on 'My Project' which is supposed to display a list of tasks. In React Native it will show an empty list while the iOS Swift implementation will …

enable offline-first in TaskProvider, syncing changes in the background

---

tutorial/swift-ios/Task Tracker.xcodeproj/project.pbxproj
tutorial/swift-ios/Task Tracker/ProjectsViewController.swift

After trying out the tutorial updates arty-fact pushed from https://github.com/mongodb/docs-realm/pull/1271 , I've discovered a couple of other issues I'd like to correct. This should enable local build (right now it fails if you try to build from the local branch) and removes the deprecated `Pods` directory from the project.

[iOS Tutorial Updates] Tweak the Swift tutorial updates

---

examples/ios/Examples/Notifications.swift
examples/ios/Podfile
examples/ios/Podfile.lock
source/examples/generated/code/start/Notifications.codeblock.alternate-dog-class-for-keypaths.swift.code-block.rst
source/examples/generated/code/start/Notifications.codeblock.register-a-keypath-change-listener.swift.code-block.rst
source/sdk/ios/examples/react-to-changes.txt
source/sdk/ios/integrations/swiftui.txt

- https://jira.mongodb.org/browse/DOCSP-16244
- [React to Changes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16244/sdk/ios/examples/react-to-changes/#register-a-key-path-change-listener): new section: "Register a Key Path Change Listener"
- [SwiftUI & Combine](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16244/sdk/ios/integrations/swiftui/#views-and-observed-objects): "Tip" after the second code example: "Starting in SDK version 10.12.0..."

(DOCSP-16244): [iOS] Key path filtering for change notifications

---

source/sdk/ios/examples/modify-an-object-schema.txt

This update is based on discussions in a couple of Slack threads and a DevHub forum question. Clarify that added required fields must have a migration to set default values, while added optional fields can be migrated automatically with just a `schemaVersion` bump.
- [Modify an Object Schema](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/ios-update-migration-docs/sdk/ios/examples/modify-an-object-schema/)

[iOS] Modify a schema: more clearly outline when a migration is required

---

source/sdk/dotnet/data-types.txt
source/sdk/dotnet/data-types/dictionaries.txt
source/sdk/dotnet/data-types/realm-integer.txt
source/sdk/dotnet/data-types/realm-value.txt
source/sdk/dotnet/data-types/sets.txt
source/sdk/flutter.txt
source/sdk/ios/data-types/anyrealmvalue.txt
source/sdk/ios/data-types/map.txt
source/sdk/ios/data-types/mutablesets.txt
source/sdk/node/data-types.txt
source/sdk/node/data-types/dictionaries.txt
source/sdk/node/data-types/field-types.txt
source/sdk/node/data-types/mixed.txt
source/sdk/node/data-types/sets.txt
source/sdk/node/data-types/uuid.txt
source/sdk/react-native/data-types.txt
source/sdk/react-native/data-types/dictionaries.txt
source/sdk/react-native/data-types/field-types.txt
source/sdk/react-native/data-types/mixed.txt
source/sdk/react-native/data-types/sets.txt
source/sdk/react-native/data-types/uuid.txt

- https://jira.mongodb.org/browse/DOCSP-17990
- Also standardized versionadded directives between SDKs to *only* mention the version, no type reference (since the entire page is about the type)
- Also removed "beta" warnings from the .NET RealmInteger page, because that type isn't in beta and it's been around since 10.0.0.
- And removed direct links to the first beta release that mentioned the new types in the Node and React Native SDKs.
- Fixed broken link to a .NET reference page (link target used <T>, which naturally confused RST mightily)
- [All Data Types Pages in All SDKs](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17990)

(DOCSP-17990): Remove beta suffixes from versionadded directives

---

source/sdk/ios/examples/sync-changes-between-devices.txt
source/sdk/node/examples/sync-changes-between-devices.txt
source/sdk/react-native/examples/sync-changes-between-devices.txt

- https://jira.mongodb.org/browse/DOCSP-17278
- [iOS SDK - Sync Changes Between Devices](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17278/sdk/ios/examples/sync-changes-between-devices/#suspend-or-resume-a-sync-session)
- [Node.js SDK - Sync Changes Between Devices](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17278/sdk/node/examples/sync-changes-between-devices/#pause-or-resume-a-sync-session)
- [React Native SDK - Sync Changes Between Devices](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17278/sdk/react-native/examples/sync-changes-between-devices/#pause-or-resume-a-sync-session)

(DOCSP-17278): Scope pausing and resuming sync to a realm's sync session

---

source/includes/steps-github-deploy.yaml

- https://jira.mongodb.org/browse/DOCSP-18233
- [Deploy Automatically with GitHub](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18233/deploy/deploy-automatically-with-github/#initialize-the-repository): "Important" directive in "Step 3: Initialize the Repository"

(DOCSP-18233): Provide CLI v2 alternative for deprecated flag when deploying with GitHub

---

tutorial/rn/components/ActionSheet.js
tutorial/rn/components/ManageTeam.js
tutorial/rn/components/TaskItem.js
tutorial/rn/package.json
tutorial/rn/views/ProjectsView.js

Fix for deprecated ListItem title in the RN tutorial.
Reference: https://reactnativeelements.com/blog/2020/08/10/2.3-upgrade-guide/#listitem
Running the RN tutorial throws the following warning.
`[Sat Jun 19 2021 05:03:22.951]  WARN     'ListItem.title' prop has been deprecated and will be removed in the next version. `
This PR updates the `ListItem` code according to the following React Native Elements upgrade guide.
https://reactnativeelements.com/blog/2020/08/10/2.3-upgrade-guide/#listitem
N/A
N/A

Fix for deprecated ListItem title

---

source/config.txt

* Adds `services` to the config file directory tree example on the root page
* Re-arranges the corresponding links to match the order of their counterparts in the example
- (DOCSP-17829): Add services to config file structure
- [Realm App Configuration](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/config-fix/config)

(DOCSP-17829): Add services to config file structure

---

source/sdk/android/data-types.txt
source/sdk/android/data-types/realmany.txt
source/sdk/android/data-types/realmdictionary.txt
source/sdk/android/data-types/realmset.txt
source/sdk/dotnet/data-types.txt
source/sdk/dotnet/data-types/dictionaries.txt
source/sdk/dotnet/data-types/realm-value.txt
source/sdk/dotnet/data-types/sets.txt
source/sdk/ios/data-types.txt
source/sdk/ios/data-types/anyrealmvalue.txt
source/sdk/ios/data-types/map.txt
source/sdk/ios/data-types/mutablesets.txt
source/sdk/node/data-types.txt
source/sdk/node/data-types/dictionaries.txt
source/sdk/node/data-types/mixed.txt
source/sdk/node/data-types/sets.txt
source/sdk/react-native/data-types.txt
source/sdk/react-native/data-types/dictionaries.txt
source/sdk/react-native/data-types/mixed.txt
source/sdk/react-native/data-types/sets.txt

- new data types are GA as of https://mongodb.slack.com/archives/CLY6HQWUE/p1631540175060600
- removed (beta) tag from page names, links
- removed beta warning from top of "new data type" pages
- [All SDK Data Types sections](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/new-data-types-ga/)

New Data Types are GA

---

config/redirects

- I realized after merging in the new IA that I should have done this before. My bad.
- [Staging build](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/triggers-ia-redirects/triggers/) (should lead you to trigger-types based on the redirect, but I don't think redirects work in staging)

Redirects for Triggers IA rework

---

source/get-started/glossary.txt
source/includes/note-details-about-pause.rst
source/sdk/android/examples/sync-changes-between-devices.txt
source/sdk/dotnet/examples/sync-changes-between-devices.txt
source/sdk/ios/examples/sync-changes-between-devices.txt
source/sdk/node/examples/sync-changes-between-devices.txt
source/sdk/react-native/examples/sync-changes-between-devices.txt

added information about pausing realm sync to SDK examples pages for Sync Changes Between Devices to clarify how it should be used. 
included for:
- Android
- iOS
- .NET
- Node
- React Native
*note*: not relevant for the other SDKs 
given that the pause method has different names depending on SDK, created reusable note with insertable function name per SDK so general content name could stay same with method name changing. 
also added a ref to link to compaction, which is referenced in the note about pausing. 
- https://jira.mongodb.org/browse/DOCSP-18713
- [Android SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18713/sdk/android/examples/sync-changes-between-devices/)
- [iOS SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/D …

Docsp 18713: add infobox about pausing syncing

---

.github/workflows/ios.yml
examples/ios/Examples/Authenticate.swift
examples/ios/Examples/Sync.swift
examples/ios/Podfile
examples/ios/Podfile.lock
examples/ios/RealmExamples.xcodeproj/project.pbxproj
examples/ios/RealmExamples.xcodeproj/xcshareddata/xcschemes/Test Examples.xcscheme
source/examples/generated/code/start/Authenticate.codeblock.async-await.swift
source/examples/generated/code/start/Sync.codeblock.async-await-open-synced-realm.swift
source/examples/generated/code/start/Sync.codeblock.open-synced-realm.swift
source/examples/generated/code/start/Sync.codeblock.specify-download-behavior.swift
source/examples/generated/code/start/Sync.codeblock.specify-download-behavior.swift.code-block.rst
source/sdk/ios/examples.txt
source/sdk/ios/examples/authenticate-users.txt
source/sdk/ios/examples/sync-changes-between-devices.txt
source/sdk/ios/examples/sync-realm-open-legacy.txt

This PR documents the changes that were introduced in [10.15.0](https://github.com/realm/realm-cocoa/releases/tag/v10.15.0) - new async support for `App.login` and `asyncOpen`, and the introduction of `OpenBehavior` and the `downloadBeforeOpen` param. There will be a separate PR for the rest of the async/await changes when they are released.
- https://jira.mongodb.org/browse/DOCSP-18707
- [Authenticate Users](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18707/sdk/ios/examples/authenticate-users/#async-await-login): New section for Async/Await Login
- [Sync Changes Between Devices](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18707/sdk/ios/examples/sync-changes-between-devices)
- New Swift text and code example: [Open a …

(DOCSP-18707): [iOS] Add async/await methods for App.login and asyncOpen

---

source/security.txt
source/sync/protocol.txt

added info about TLS 1.3 and network security to Realm Sync docs. 
- https://jira.mongodb.org/browse/DOCSP-18744
- [Security](https://docs-mongodborg-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18744/security)
- [Sync Protocol](https://docs-mongodborg-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18744/sync/protocol/#network-security)

(DOCSP-18744): Make docs reference TLS 1.3

---

examples/ios/Examples/Functions.swift
examples/ios/Examples/ManageEmailPasswordUsers.swift
examples/ios/Examples/MongoDBRemoteAccess.swift
examples/ios/Examples/MultipleUsers.swift
examples/ios/Podfile
examples/ios/Podfile.lock
source/examples/generated/code/start/Functions.codeblock.async-call-a-function.swift
source/examples/generated/code/start/ManageEmailPasswordUsers.codeblock.confirm-new-user-email.swift
source/examples/generated/code/start/ManageEmailPasswordUsers.codeblock.password-reset-function.swift
source/examples/generated/code/start/ManageEmailPasswordUsers.codeblock.register-email-completion-handler.swift
source/examples/generated/code/start/ManageEmailPasswordUsers.codeblock.resend-confirmation-email.swift
source/examples/generated/code/start/ManageEmailPasswordUsers.codeblock.reset-password.swift
source/examples/generated/code/start/ManageEmailPasswordUsers.codeblock.retry-confirmation-function.swift
source/examples/generated/code/start/MongoDBRemoteAccess.codeblock.async-await-insert.swift
source/examples/generated/code/start/MultipleUsers.codeblock.async-link-identity.swift
source/sdk/ios/advanced-guides/link-user-identities.txt
source/sdk/ios/examples/call-a-function.txt
source/sdk/ios/examples/manage-email-password-users.txt
source/sdk/ios/examples/mongodb-remote-access.txt

UPDATE: These updates have been released as 10.16.0. I've resolved these todos and this PR is ready for merging after review.
_This update is for a not-yet-released version of the Cocoa SDK_. Prior to merging this PR, but after release, resolve these todos:
- https://jira.mongodb.org/browse/DOCSP-17883
- [Docs Kickoff Outline](https://docs.google.com/document/d/1bXuJz3ggWAI60Bg16PTqWUuQXSf3TYgvH5cA95qETaY/edit?usp=sharing): This PR is for the async methods for: 
- EmailPasswordAuth
- User.linkUser
- MongoCollection
- User.functions
- [Manage Email/Password Users](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17883/sdk/ios/examples/manage-email-password-users/): Update all methods on the page for async/await, and add a completion handler example for folks …

(DOCSP-17883): [iOS] Async-await doc updates and code examples for 10.16.0 release

---

source/examples/QuickStarts/electron/quickstart-main.js
source/examples/QuickStarts/electron/quickstart-setup-main.js
source/includes/steps-realm-with-electron.yaml

As of Electron v12, `contextIsolation` is enabled by default: https://www.electronjs.org/docs/breaking-changes#default-changed-contextisolation-defaults-to-true. This prevents you from calling `require` in the render process. This quick fix ensures that the Realm quickstart can be built with newer version of Electron - it might make sense to refactor it to work with the default of `contextIsolation` enabled in future.
~- https://jira.mongodb.org/browse/DOCSP-NNNNN~
~- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)~

Add `contextIsolation: false` to node setup to enable `require`

---

source/includes/steps-deploy-draft-ui-changes.yaml
source/includes/steps-disable-deployment-drafts.yaml
source/manage-apps/deploy.txt
source/manage-apps/deploy/deployment-draft.txt
source/manage-apps/deploy/disable-deployment-drafts.txt
source/manage-apps/deploy/manual/deploy-ui.txt

- this PR goes after [this one](https://github.com/mongodb/docs-realm/pull/1401) and the branch pulls in those changes
- https://jira.mongodb.org/browse/DOCSP-18595
- [Disable Deployment Drafts](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18595/manage-apps/deploy/disable-deployment-drafts/)

(DOCSP-18595): Add guide to disable deployment drafts

---

tutorial/rn/providers/TasksProvider.js

If schema not downloaded from Atlas first, this error results
- See mongodb-university/realm-tutorial-react-native#10
- Original Source: https://stackoverflow.com/questions/68796677/error-object-type-task-not-found-in-schema

RN tutorial fix: missing Task in schema error

---

config/redirects

fix issue with malformatted redirect. updated the config so that the page https://docs.mongodb.com/realm/sdk/node/examples/open-and-close-a-local-realm/ correctly redirects to https://docs.mongodb.com/realm/sdk/node/examples/open-and-close-a-realm/
- N/A
- N/A (redirects don't show up in staging unfortunately)

Fix: properly format redirect to node/examples/open-and-close-a-realm/

---

config/redirects
examples/node/Examples/open-and-close-a-realm.js
source/examples/generated/node/open-and-close-a-realm.codeblock.open-synced-realm-with-background-sync.js
source/includes/react-native-open--synced-realm.rst
source/includes/react-native-open-a-synced-realm.rst
source/sdk/react-native.txt
source/sdk/react-native/examples.txt
source/sdk/react-native/examples/open-and-close-a-realm.txt
source/sdk/react-native/examples/sync-changes-between-devices.txt
source/sdk/react-native/fundamentals/realms.txt

Refresh page content for React native SDK page "Open a Synced Realm". 
This is largely a copy and paste job from the newly created Node docs (https://jira.mongodb.org/browse/DOCSP-17709). It's a separate PR w the content copy-pasted instead of just using an include b.c the refs need to change. 
Content changes focus on using the method `Realm.open()` to open a new realm instead of `new Realm()`, as this is the currently preferred method per the JS SDK team.
Additional changes: 
* In addition to main changes on the page `source/sdk/react-native/examples/open-and-close-a-realm.txt`, there are updates to the refs in the page and renaming the text in links to the page. 
* redirect from old page URL to the new
- https://jira.mongodb.org/browse/DOCSP-19020
- [Open & Close a Realm (React …

(DOCSP-19020): React Native JS SDK refresh of page "Open a Synced Realm"

---

source/openapi-admin-v3.yaml

Update the OpenAPI spec route for POST `/groups/{groupId}/apps` to include information about adding a template to app creation. 
Note that while updating the spec, a bug with our OpenAPI spec renderer was discovered in which the `data_source` field is marked as required when it's not, presumably because some of its own fields are required _iff_ the data_source is included. However there is no adverse effect of of always the user to always include the data_source field. 
- https://jira.mongodb.org/browse/DOCSP-17188
- [Realm Administration API](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17188/admin/api/v3/#post-/groups/%7Bgroupid%7D/apps)

(DOCSP-17188): Update OpenAPI spec with add template for creating new application

---

source/authentication/custom-jwt.txt

Add note about escape characters to metadata path name information. Updating documentation to reflect previously undocumented feature. 
Periods are supported as part of valid JSON keys, but also serve to semantically break down nested keys in this path. Using escape character `\` allows for using periods in paths for JWT metadata config. 
- https://jira.mongodb.org/browse/DOCSP-19347
- [Custom JWT Authentication](https://docs-mongodborg-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19347/authentication/custom-jwt/#metadata-fields)

(DOCSP-19347): Add note about escape characters to path name explanation

---

source/hosting/enable-hosting.txt
source/hosting/host-a-single-page-application.txt
source/hosting/upload-content-to-realm.txt
source/includes/enable-hosting-in-ui-note.rst
source/includes/steps-host-a-single-page-application-code-deploy.yaml
source/includes/steps-use-a-custom-domain-name-import-export.yaml

Refactor the docs about static hosting to take into account the fact that the feature for enabling static hosting from the CLI is not working, and won't be working for another couple of months, per https://jira.mongodb.org/browse/REALMC-10454.  
Removed procedure for enabling hosting with CLI, and for other CLI-related pages, added note about need to enable hosting with the UI first.
All stuff that should be removed was prepended with a comment `TODO(DOCSP-19662):`. [DOCSP-19662](https://jira.mongodb.org/browse/DOCSP-19662) is the ticket to revert the content to its previous state. 
Also added a few slight tweaks to observed errors in CLI examples. 
- https://jira.mongodb.org/browse/DOCSP-19661
- [Enable Hosting](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCS …

(DOCSP-19661): Temporarily refactor CLI hosting docs

---

source/sdk/node/examples/manage-email-password-users.txt
source/sdk/react-native/examples/manage-email-password-users.txt

- https://jira.mongodb.org/browse/DOCSP-19563
- [Manage Email/Password Users - React Native SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19563-custom-confirm-fix-node-rn/sdk/react-native/examples/manage-email-password-users/)
- [Manage Email/Password Users - Node.js SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19563-custom-confirm-fix-node-rn/sdk/node/examples/manage-email-password-users/)

(DOCSP-19563): Add support for Retry Custom Confirmation Functions + Copy improvements to Manage Email Pass Users [Node/RN]

---

source/sync/get-started.txt

- Just an error I noticed browsing the docs.
- [Get Started with Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/client-reset-link-fix/sync/get-started/)

Fix broken link to client reset page

---

source/functions/utilities.txt

Update the information for the `utils.jwt.decode()` method used by Realm functions. Added argument for `acceptedSigningMethods` along w info about it's usage. 
- https://jira.mongodb.org/browse/DOCSP-15666
- [Utility Packages, `utils.jwt.decode()` section](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15666/functions/utilities/#mongodb-method-utils.jwt.decode)

(DOCSP-15666): Update documentation for utils.jwt.decode() method

---

source/graphql/types-and-resolvers.txt

This pull request updates the GraphQL documentation to make it so that arrays are not required to have values in them. 
It should be noted that this is actually contrary to the GraphQL specification. However this change updates the documentation to reflect the current state of our GraphQL implementation. For more information on the subject, see https://jira.mongodb.org/browse/REALMC-9030. 
- https://jira.mongodb.org/browse/DOCSP-19805
- [GraphQL Types, Resolvers, and Operators](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19805/graphql/types-and-resolvers/)

(DOCSP-19805): Change Array documentation to exclude required values with `!`

---

source/includes/steps-install-swift-static-framework.yaml
source/sdk/ios/install.txt

This ticket ports over the Static Framework install instructions from the legacy Realm docs. I manually verified these instructions in a new Xcode Swift project and they work as written.
- https://jira.mongodb.org/browse/DOCSP-19833
- [Install Realm](https://docs-mongodbcom-staging.corp.mongodb.com/52907b97/8682f5b/realm/docsworker-xlarge/master/sdk/ios/install/#installation): New tab: **Static Framework**

(DOCSP-19833): [iOS] Add static framework install instructions

---

examples/dotnet/Examples/BundleARealmExamples.cs
examples/dotnet/Examples/ClientResetExamples.cs
examples/dotnet/Examples/DataSyncExamples.cs
examples/dotnet/Examples/ErrorHandler.cs
examples/dotnet/Examples/ProgressNotifications.cs
source/examples/generated/dotnet/BundleARealmExamples.codeblock.copy_a_synced_realm.cs
source/examples/generated/dotnet/DataSyncExamples.codeblock.pause-synced-realm.cs
source/examples/generated/dotnet/ProgressNotifications.codeblock.upload-download-progress-notification.cs
source/examples/generated/dotnet/ProgressNotifications.codeblock.wait-for-changes-to-download-async-progress-notification.cs
source/sdk/dotnet/advanced-guides/bundle-a-realm.txt
source/sdk/dotnet/examples/sync-changes-between-devices.txt

- [Bundle Synced Realm](https://jira.mongodb.org/browse/DOCSP-16502)
- [Replace GetSession()](https://jira.mongodb.org/browse/DOCSP-19890)
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/bundledsyncrealm/sdk/dotnet/advanced-guides/bundle-a-realm/
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/bundledsyncrealm/sdk/dotnet/examples/sync-changes-between-devices

Add info on bundling a synced realm; add new code snippet; replace deprecated GetSession()

---

source/tutorial/generated/node/projects.codeblock.getProjects.js
source/tutorial/nodejs-cli.txt
tutorial/node-cli/package-lock.json
tutorial/node-cli/package.json
tutorial/node-cli/projects.js
tutorial/node-cli/users.js
tutorial/rn/ios/Podfile.lock
tutorial/rn/package-lock.json
tutorial/rn/package.json
tutorial/web/package-lock.json
tutorial/web/package.json

This PR was initiated by this issue - https://github.com/mongodb/docs-realm/issues/1498 
While addressing the issue by bumping the Realm JS version in the web tutorial and across the docs-realm repo, a couple of other issues were encountered and addressed: 
- the Node tutorial `getProjects()` function for getting custom user data was updated to use the `refreshCustomData()` method and have error handling for slow to fire triggers. 
- changed the ESLint version of the web tutorial to be compatible with Create React App
- https://jira.mongodb.org/browse/DOCSP-19905 
- [NodeJS CLI Tutorial](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fix_realm_js_versions/tutorial/nodejs-cli/)

(DOCSP-19905): Fix realm JS SDK versions update Node Tutorial user custom data access, and eslint for web tutorial 

---

source/web/authenticate.txt
source/web/call-a-function.txt
source/web/create-manage-api-keys.txt
source/web/init-realmclient.txt
source/web/manage-email-password-users.txt
source/web/work-with-multiple-users.txt

Remove all TypeScript examples that
* don't provide useful information
* are the same as the JS examples
* do not use type inference
this was done to streamline docs and remove errors where switching between language tabs causes the interface to jerk around the page. 
- https://jira.mongodb.org/browse/DOCSP-20055
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20055/web/init-realmclient/
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20055/web/authenticate/
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20055/web/manage-email-password-users/
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20055/web/create-manage-api-keys/
- …

(DOCSP-20055): Remove unnecessary TypeScript examples from Web SDK 

---

source/authentication/google.txt
source/includes/note-secrets-not-exported.rst
source/web/authenticate.txt

* update examples for Google Auth for Web SDK
* moved the set up `Set Up a Project in the Google API Console` section b/c it's the first action you should do when setting up google auth for project
- https://jira.mongodb.org/browse/DOCSP-19356
- [Authentication, Google Authentication section (Web SDK)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19356/web/authenticate/#google-authentication)
- [Google Authentication](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19356/authentication/google/)

(DOCSP-19356): Update Google Auth for Web SDK

---

source/sync.txt

It was pointed out that the UI links directly to the `/sync` page, which is now an empty container page. This PR adds a text link to the content that used to live on this page as an interim fix until UI can change the URL directly.
- [Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/add-sync-redirect-note/sync)

[Sync] Add a link to moved content

---

source/sdk/swift/install.txt
source/sdk/swift/swiftui.txt
source/tutorial/ios-swift.txt

Note: the upstream PR referenced in this Jira ticket has been merged, but the changes won't apply until the next Swift SDK release, so don't merge until the next Cocoa release.
- https://jira.mongodb.org/browse/DOCSP-19366
- [Install Realm for iOS](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19366/sdk/ios/install/)
- [Quick Start with SwiftUI](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19366/sdk/ios/swiftui/)
- [iOS Swift Tutorial](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19366/tutorial/ios-swift/#part-1--set-up-the-mobile-app)

(DOCSP-19366): Bump minimum required Xcode version for Swift SDK to 12.4

---

source/openapi-admin-v3.yaml

Tweaked info about pagination to make clearer which endpoints use. 
wasn't able to implement as much change as i would have liked here due to feature limitation of snooty's openapi parse. see ticket for more info. 
- https://jira.mongodb.org/browse/DOCSP-19319
- [Admin API Reference](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19319/admin/api/v3/)

(DOCSP-19319): Add info about pagination to Admin API 

---

source/includes/note-unsupported-flex-sync-rql-operators.rst
source/sdk/swift/fundamentals/realm-sync.txt
source/sync/configure/enable-sync.txt

The Flexible Sync content was created in several different PRs. This PR links the content that has now been merged to the query-based-sync branch. It adds a note/include that we should include on all of the SDK Flexible Sync pages regarding Realm Query Operators. And also some (very) minor wording tweaks and link cleanup for pages that are not yet merged.
- [Realm Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/link-concept-configure-content/sdk/swift/fundamentals/realm-sync/)
- [Enable Realm Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/link-concept-configure-content/sync/configure/enable-sync/)

Flexible Sync: Link Concept & Configure content

---

source/sync/data-access-patterns/permissions.txt

- (DOCS-15026): [Realm] wrong JSON expression syntax for arrays
- [Sync Rules and Permissions > Permission Strategies](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/json-expression-arrays/sync/data-access-patterns/permissions/#permission-strategies)

(DOCS-15026): [Realm] wrong JSON expression syntax for arrays

---

source/sync/configure/enable-sync.txt

N/A
- [Configure Realm Sync > Enable Realm Sync # Enable Flexible Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/quickfix-sync-doesnt-require-schema-with-devmode/sync/configure/enable-sync/)

Quick fix -  enabling sync doesn't require a schema if you are using dev mode

---

source/includes/steps-configure-flexible-sync-api.yaml
source/includes/steps-configure-flexible-sync-cli.yaml
source/reference/realm-query-language.txt

Based on [Nick's comment on the query-based-sync feature branch](https://github.com/mongodb/docs-realm/pull/1506#discussion_r788103245)
This also fixes a couple of broken :ref:s that are in master 
- [Realm Query Language](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fs-fixups-round-one/reference/realm-query-language/): Swap very similar verbiage for an existing `include`

Flexible Sync: Switch 'important' directive to very similar include

---

source/includes/steps-configure-flexible-sync-ui.yaml

Multiple people have run into a state where a cluster is grayed out and not selectable in the UI when they try to enable Flexible Sync. This note explains this state at the point in the procedure when someone would encounter this state.
- [Enable Realm Sync -> Flexible Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/add-ineligible-cluster-note-to-flex-sync-config/sync/configure/enable-sync/#enable-flexible-sync): Adds note in Step 2

Add note about ineligible clusters in Enable Flexible Sync docs

---

examples/ios/Examples/FlexibleSync.swift
examples/ios/Podfile
examples/ios/Podfile.lock
examples/ios/RealmExamples.xcodeproj/project.pbxproj
source/examples/generated/code/start/FlexibleSync.codeblock.add-multiple-subscriptions.swift
source/examples/generated/code/start/FlexibleSync.codeblock.add-single-subscription.swift
source/examples/generated/code/start/FlexibleSync.codeblock.add-subscription-with-oncomplete.swift
source/examples/generated/code/start/FlexibleSync.codeblock.flex-sync-open-realm.swift
source/examples/generated/code/start/FlexibleSync.codeblock.flexible-sync-models.swift
source/examples/generated/code/start/FlexibleSync.codeblock.query-subscription-by-name.swift
source/examples/generated/code/start/FlexibleSync.codeblock.query-subscription-without-name.swift
source/examples/generated/code/start/FlexibleSync.codeblock.remove-all-subscriptions.swift
source/examples/generated/code/start/FlexibleSync.codeblock.remove-single-subscription.swift
source/examples/generated/code/start/FlexibleSync.codeblock.remove-subscriptions-to-object-type.swift
source/examples/generated/code/start/FlexibleSync.codeblock.update-subscription-by-name.swift
source/examples/generated/code/start/FlexibleSync.codeblock.update-subscription.swift
source/sdk/swift/examples.txt
source/sdk/swift/examples/configure-and-open-a-realm.txt
source/sdk/swift/examples/flexible-sync.txt
source/sdk/swift/examples/sync-changes-between-devices.txt
source/sdk/swift/fundamentals/realm-sync.txt
source/sync/data-access-patterns/flexible-sync.txt

This PR replaces #1540 which was against the `query-based-sync` branch that has now been merged to `master`.
Note for reviewer: the Flexible Sync examples can't currently be tested in our Swift SDK unit test framework. I created an independent project and verified that the syntax compiles, but haven't tested these code examples against a backend. We'll need to update with tested code examples after the feature is live.
- https://jira.mongodb.org/browse/DOCSP-19418
- [Flexible Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19418/sdk/swift/examples/flexible-sync/): Net new content about managing subscriptions using the Swift SDK API
- [Sync Changes Between Devices](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19418/sdk/s …

(DOCSP-19418): Swift SDK Flexible Sync

---

source/sync/data-model/sync-schema-overview.txt

- https://jira.mongodb.org/browse/DOCSP-19900
Note: the Jira ticket calls for this update to be putting the Partition-Based Sync Schema in a tab, and adding another tab for a Flexible Sync Schema object, but as the only difference was a partition field, I decided a callout was a better solution.
- [Sync Schema Overview](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19900/sync/data-model/sync-schema-overview/#object-schema): New Tip after the schema code block

(DOCSP-19900): Add note about partition field in schema

---

source/functions/built-in-module-support.txt

- https://jira.mongodb.org/browse/DOCSP-15044
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/http2-finally/functions/built-in-module-support/#http--http-2-and-https

(DOCSP-15044): Add http/2 to partially supported built-in modules

---

source/openapi-admin-v3.yaml

Note: This is the only endpoint in the Admin API that specifically shows a Sync object, and this endpoint only shows partition field data when PBS is enabled. When Flexible Sync is enabled, it returns an empty object. So I think this is the only update that will be needed relative to Flexible Sync.
- https://jira.mongodb.org/browse/DOCSP-19894
- [Admin API -> GET sync/data](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19894/admin/api/v3/#operation/adminGetSync): Adds a description stating that this endpoint returns partition field data when using Partition-Based Sync.

(DOCSP-19894): Add Partition-Based Sync info to Sync data endpoint

---

source/get-started/glossary.txt
source/includes/appschema-mongodb.rst
source/includes/note-beta-feature.rst
source/includes/realm-database.rst
source/includes/steps-configure-flexible-sync-ui.yaml
source/includes/steps-development-mode-cli.yaml
source/includes/steps-development-mode-realm-schema.yaml
source/includes/steps-development-mode-ui.yaml
source/includes/steps-disable-development-mode-cli.yaml
source/includes/steps-disable-development-mode-ui.yaml
source/includes/steps-disable-trigger-realm-ui.yaml
source/logs/schema.txt
source/manage-apps/configure/config/sync.txt
source/manage-apps/deploy/automated/sdlc.txt
source/sdk/android/examples/modify-an-object-schema.txt
source/sdk/android/quick-start-sync.txt
source/sdk/dotnet/quick-start-with-sync.txt
source/sdk/node/quick-start.txt
source/sdk/react-native/quick-start.txt
source/sdk/swift/quick-start-with-sync.txt
source/sync/configure/enable-sync.txt
source/sync/data-model/development-mode.txt
source/sync/learn/overview.txt

- https://jira.mongodb.org/browse/DOCSP-20605
While I was scouring the docs for Development Mode references, I found some places where naming was inconsistent (developer mode, dev mode) and have also updated those references in this PR.
Removed inaccurate info:
- [Development Mode Glossary entry](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20605/get-started/glossary/)
- [Application Configuration Files (Legacy)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20605/manage-apps/configure/config/legacy/#synced-cluster-configuration)
- [Enable or Disable Development Mode](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20605/sync/data-model/development-mode/)
Updated naming:
- [Enable or Disable …

(DOCSP-20605): Remove inaccurate Development Mode info

---

source/users/enable-custom-user-data.txt

Adds guidance around size limitations of custom user data since the data is stored in the access token.
However, not sure if this is actually a good change since any limitations/the meaning of "small" would depend on the other infrastructure of the user's site.
Is this a product issue? Should the custom user data be fetched in the access token at all?
Opening for discussion.
- https://jira.mongodb.org/browse/DOCSP-19777
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/user-data-size/users/enable-custom-user-data/

(DOCSP-19777): Add size limit guidance to custom user data

---

examples/ios/Examples/Compacting.swift
source/examples/generated/code/start/Compacting.codeblock.async-compact.swift
source/sdk/android/fundamentals/realms.txt
source/sdk/dotnet/advanced-guides/compact-realm.txt
source/sdk/dotnet/fundamentals/realms.txt
source/sdk/node/fundamentals/realms.txt
source/sdk/react-native/fundamentals/realms.txt
source/sdk/swift/advanced-guides/compacting.txt
source/sdk/swift/fundamentals/realms.txt

After a reviewer weighs in on the wording/value of these additions, I'll port the relevant bits to the other SDKs.
- https://jira.mongodb.org/browse/DOCSP-15678
- [Swift SDK - Compact a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15678/sdk/swift/advanced-guides/compacting/#std-label-ios-when-to-compact-a-realm): Renamed "Best Practices" to "When to Compact a Realm", added Swift async compact example
- [Swift SDK - Realms: File Size](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15678/sdk/swift/fundamentals/realms/#file-size): Add a callout that all production applications should implement compacting, with a link to compacting docs
- [Android SDK - Realms: File Size/Compact a …

(DOCSP-15678): Add more explicit guidance to compacting documentation

---

source/includes/non-sync-rules-note.txt
source/rules.txt
source/rules/examples.txt
source/rules/filters.txt
source/rules/roles.txt
source/sync/data-access-patterns/permissions.txt
source/sync/learn/overview.txt

Updates to clarify flexible sync roles
- Rename "role" to "session role" in the context of flexible sync
- Reorganize page to put session roles first, then rules
- Add note to non-sync rules and roles content
- https://jira.mongodb.org/browse/DOCSP-21050
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/sync-roles/sync/data-access-patterns/permissions/

(DOCSP-21050): Sync roles updates

---

examples/node/Examples/data-types.js
examples/node/Examples/mongodb.js
examples/node/Examples/realm-query-language.js
examples/node/jest.config.js
examples/node/testSetup.js

Make Jest work with Realm Sync. Also included a couple of other Jest-related tweaks that make the unit tests work more consistently with Jest.
- https://jira.mongodb.org/browse/DOCSP-21093
N/A

(DOCSP-21093): Make Jest work with Realm Sync

---

examples/ios/Examples/Authenticate.swift
examples/ios/Examples/DeleteUsers.swift
examples/ios/Podfile
examples/ios/Podfile.lock
examples/ios/RealmExamples.xcodeproj/project.pbxproj
source/examples/generated/code/start/DeleteUsers.codeblock.async-await-delete-user.swift
source/examples/generated/code/start/DeleteUsers.codeblock.closure-delete-user.swift
source/includes/apple-account-deletion-requirements.rst
source/includes/note-delete-user.rst
source/sdk/swift/examples/users/create-and-delete-users.txt
source/sdk/swift/examples/users/manage-email-password-users.txt
source/sdk/swift/examples/users/user-metadata.txt
source/sdk/swift/examples/work-with-users.txt
source/users/create.txt
source/users/delete-or-revoke.txt

- https://jira.mongodb.org/browse/DOCSP-20092
- [Create and Delete Users (Swift SDK)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20092/sdk/swift/examples/users/create-and-delete-users/): New page w/new code examples for deleting the user
- [Work with Users/Create and Delete Users](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20092/sdk/swift/examples/work-with-users/#create-and-delete-users): New section on existing page
- [Create a User (Cloud)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20092/users/create/): Added a section about first authentication automatically creating user objects, and a link to SDK pages where devs can create email/password users
- [Delete a User …

(DOCSP-20092): [Swift SDK] Delete user documentation

---

examples/ios/Examples/ConvertSyncLocalRealms.swift
examples/ios/Podfile.lock
examples/ios/RealmExamples.xcodeproj/project.pbxproj
source/examples/generated/code/start/ConvertSyncLocalRealms.codeblock.convert-local-to-sync.swift
source/examples/generated/code/start/ConvertSyncLocalRealms.codeblock.convert-sync-to-local.swift
source/examples/generated/code/start/ConvertSyncLocalRealms.codeblock.convert-sync-to-sync.swift
source/sdk/swift/examples/configure-and-open-a-realm.txt

- https://jira.mongodb.org/browse/DOCSP-20221
- [Configure & Open a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20221/sdk/swift/examples/configure-and-open-a-realm/): The linked Jira ticket only mentions converting a local realm to a synced realm, but updates to writeCopy provide three conversion options, each of which gets a new section:
- [Open a Synced Realm as a Non-Synced Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20221/sdk/swift/examples/configure-and-open-a-realm/#open-a-synced-realm-as-a-non-synced-realm)
- [Open a Synced Realm as a Different Sync User](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20221/sdk/swift/examples/configure-and-open-a-realm/#open-a-synced-r …

(DOCSP-20221): [Swift SDK] Add docs for converting between non-synced and synced realms

---

source/sdk/flutter.txt
source/sdk/flutter/open-and-close-a-realm.txt

Create Flutter 'Open & Close a Realm' page. 
note that for now the page largely duplicate of content on quickstart page, as there aren't yet advanced configuration options for Flutter realms. in the future, this page will grow with the SDK. 
- https://jira.mongodb.org/browse/DOCSP-21139
- [Open & Close a Realm (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21139/sdk/flutter/open-and-close-a-realm)

(DOCSP-21139): Flutter Open & Close a Realm page

---

.github/workflows/docusaurus-staging.yml

Make Docusaurus staging action get files in subdirectories.
right now it only gets files in `docusaurus`, not `docusaurus/path/to/myfile.md`.
this should fix per https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

Get files in subdirectories

---

.github/workflows/bluehawk.yml
.github/workflows/check-autobuilder.yml
.github/workflows/docusaurus-push-to-production.yml
.github/workflows/docusaurus-staging.yml
.github/workflows/dotnet-core.yml
.github/workflows/ios.yml
.github/workflows/java_local.yml
.github/workflows/java_sync.yml
.github/workflows/kotlin.yml
.github/workflows/node.js.yml
.github/workflows/push-to-artifact-repos.yml

Checking if v3 supports the pull_request_target event to actually check out the PR branch by default

Upgrade actions/checkout to v3

---

.github/workflows/docusaurus-push-to-production.yml

Previously always failed in forks due to missing access key for S3.
Based on https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-run-job-for-specific-repository

Only attempt to deploy from upstream

---

docusaurus/src/theme/DocCard/index.js

fix current bug where broken image appears if no img in static directory provided for homepage cards. now will default to emoji, as per original behavior. (see getting started page)

Fix card icons if no img provided

---

source/includes/realm-database.rst
source/includes/steps-github-deploy.yaml
source/logs/schema.txt
source/sdk/flutter/realm-database.txt
source/sdk/java/advanced-guides/manual-client-reset-data-recovery.txt
source/sdk/java/examples/modify-an-object-schema.txt
source/sdk/java/examples/reset-a-client-realm.txt
source/sdk/kotlin/realm-database/overview.txt
source/sdk/node/examples/modify-an-object-schema.txt
source/sdk/node/fundamentals/schema-versions-and-migrations.txt
source/sdk/react-native/examples/modify-an-object-schema.txt
source/sdk/react-native/fundamentals/schema-versions-and-migrations.txt
source/studio/modify-schema.txt
source/sync/data-model/development-mode.txt
source/sync/error-handling/client-resets.txt

- https://jira.mongodb.org/browse/DOCSP-21350
- [Schema Logs](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21350/logs/schema/): Updated intro with new language
- [Flutter Realm DB Overview](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21350/sdk/flutter/realm-database/#schemas): Updated Schemas section with new language
- [Java SDK - Manual Client Reset Data Recovery](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21350/sdk/java/advanced-guides/manual-client-reset-data-recovery/): Updated destructive/additive language
- [Java SDK - Modify an Object Schema](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21350/sdk/java/examples/modify-an-object-schema/): Update …

(DOCSP-21350): Update additive and destructive changes to breaking and non-breaking

---

source/sync/data-access-patterns/permissions.txt

- https://jira.mongodb.org/browse/DOCSP-21381
- https://jira.mongodb.org/browse/DOCSP-21376
- [Sync Rules & Permissions](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21381/sync/data-access-patterns/permissions/#flexible-sync-session-roles-and-rules): Update JSON permission examples for Flexible Sync

(DOCSP-21381): Fix broken Rule syntax and broken JSON in permission examples

---

source/sync/error-handling/client-resets.txt

- https://jira.mongodb.org/browse/DOCSP-21443
- [Client Resets](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21443/sync/error-handling/client-resets/)

(DOCSP-21443): Client reset + flex sync session role cause

---

examples/dart/bin/models/car.dart
examples/dart/bin/models/car.g.dart
examples/dart/test/define_realm_model_test.g.dart
examples/dart/test/open_realm_test.dart
examples/dart/test/task_project_models_test.g.dart
source/examples/generated/flutter/open_realm_test.codeblock.fifo-file.dart
source/examples/generated/flutter/open_realm_test.codeblock.in-memory-realm.dart
source/examples/generated/flutter/open_realm_test.codeblock.read-only-realm.dart
source/sdk/flutter/open-and-close-a-realm.txt

add sections for:
* open read-only realm
* open in-memory realm
* set custom FIFO special file path
- https://jira.mongodb.org/browse/DOCSP-21503
- [Open and Close a Realm (Flutter SDK)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21503/sdk/flutter/open-and-close-a-realm/#open-a-read-only-realm)

(DOCSP-21503): Expand Open Realm docs for Flutter SDK

---

examples/dart/bin/models/car.g.dart
examples/dart/test/define_realm_model_test.g.dart
examples/dart/test/read_write_data_test.dart
examples/dart/test/read_write_data_test.g.dart
examples/dart/test/task_project_models_test.g.dart
source/examples/generated/flutter/read_write_data_test.codeblock.query-realm-list.dart
source/sdk/flutter.txt
source/sdk/flutter/read-and-write-data.txt

Add docs for querying RealmList of RealmObjects.
also removed note about flutter for linux desktop not being supported 
- https://jira.mongodb.org/browse/DOCSP-21502
- [Read and Write Data (Flutter SDK)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21502/sdk/flutter/read-and-write-data/)

(DOCSP-21502): Query RealmList of RealmObjects - Flutter SDK

---

source/includes/android-6-trusted-certificate.rst
source/sdk/java/install.txt
source/sdk/java/troubleshooting.txt

- https://jira.mongodb.org/browse/DOCSP-21579
(This is the same `/include` on two different pages)
- [Install](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21579/sdk/java/install/#prerequisites): Added as an include in Prerequisites
- [Troubleshooting](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21579/sdk/java/troubleshooting/#android-6-or-lower-devices-can-t-connect-to-realm-cloud-services): New section with this info

(DOCSP-21579): [Java] Add note about ISRG Root X1 certificate w/Android 6 devices

---

examples/ios/Examples/Threading.swift
source/examples/generated/code/start/Threading.codeblock.use-realm-with-serial-queue.swift
source/sdk/swift/advanced-guides/threading.txt

- https://jira.mongodb.org/browse/DOCSP-21675
- [Threading](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21675/sdk/swift/advanced-guides/threading/#create-a-serial-queue-to-use-realm-on-a-background-thread): Add section about Realm only supporting serial queues for background activity

(DOCSP-21675): [Swift] Add info about only using realm on a serial queue

---

source/functions/add-external-dependencies.txt

- https://jira.mongodb.org/browse/DOCSP-21660
- [Add External Dependencies](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21660/functions/add-external-dependencies/)

(DOCSP-21660): Increase external dependency size cap to 15MB

---

source/sdk/node/examples/sync-changes-between-devices.txt
source/sdk/react-native/examples/sync-changes-between-devices.txt

Couple of small clarifications to the RN and Node "Sync Changes between Devices" page:
1. bit of clarification regarding what session multiplexing is and when to use
2. remove unclear note abt deprecated `new Realm()` method to open realms
3. clarify description of parameters for `syncSession.addProgressNotification()`
- https://jira.mongodb.org/browse/DOCSP-20792
- [Sync Changes between Devices (Node)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20792/sdk/node/examples/sync-changes-between-devices/)
- [Sync Changes between Devices (RN)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20792/sdk/react-native/examples/sync-changes-between-devices/)

(DOCSP-20792): RN/Node "Sync Changes between Devices" page clarifications

---

source/includes/warn-terminate-sync-client-reset.rst
source/reference/upgrade-shared-cluster.txt
source/sync/configure/pause-or-terminate-sync.txt
source/sync/data-access-patterns/partitions.txt
source/sync/data-model/migrate-schema-partner-collection.txt
source/sync/error-handling/client-resets.txt

- https://jira.mongodb.org/browse/DOCSP-22031
- [Upgrade a Shared Tier Cluster](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22031/reference/upgrade-shared-cluster/): Add an include w/details about terminating sync causing a client reset
- [Pause or Terminate Sync - Terminate Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22031/sync/configure/pause-or-terminate-sync/#terminate-sync): Move the content about terminating sync causing a client reset to an include
- [Partitions](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22031/sync/data-access-patterns/partitions/#partition-key): Add include to the partition page where we mention you can change a partition key when you terminate and …

(DOCSP-22031): Add client reset warning to docs that mention terminating sync

---

source/sdk/swift/examples/define-a-realm-object-model.txt

- https://jira.mongodb.org/browse/DOCSP-21981
- [Define a Realm Object Schema -> Define a To-One Relationship Property](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21981/sdk/swift/examples/define-a-realm-object-model/#define-a-to-one-relationship-property): Add a note about to-one relationships being optional

(DOCSP-21981): Add note about to-one relationships being optional

---

examples/ios/Examples/Authenticate.swift
source/examples/generated/code/start/Authenticate.codeblock.offline-login.swift
source/includes/offline-login.rst
source/sdk/swift/examples/configure-and-open-a-realm.txt
source/sdk/swift/examples/users/authenticate-users.txt
source/sdk/swift/examples/work-with-users.txt

Note for reviewer: the CI is broken due to GitHubActions not currently supporting macOS-12/Xcode 13.3. However, the tests pass locally:
> Test Suite 'All tests' passed at 2022-04-14 11:07:52.723.
Executed 214 tests, with 0 failures (0 unexpected) in 54.816 (54.964) seconds
- https://jira.mongodb.org/browse/DOCSP-22032
- [Authenticate Users](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22032/sdk/swift/examples/users/authenticate-users/#offline-login): New "Offline Login" section w/include we can use across docs
- [Open and Configure a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22032/sdk/swift/examples/configure-and-open-a-realm/#open-a-synced-realm-offline): New "Open a Synced Realm Offline" section that uses the …

(DOCSP-22032): Add details for Swift SDK offline login

---

.github/workflows/ios.yml
examples/ios/Examples/Threading.swift
source/examples/generated/code/start/Threading.codeblock.append-to-frozen-collection.swift
source/sdk/swift/advanced-guides/threading.txt

Note for reviewer: yay, the CI is working again! But boo, now a test that is completely unrelated to this PR is failing in CI. It still passes locally, though:
> Test Suite 'All tests' passed at 2022-04-15 10:56:08.659.
Executed 214 tests, with 0 failures (0 unexpected) in 54.560 (54.706) seconds
I've made a Jira ticket to remind me to fix this later: https://jira.mongodb.org/browse/DOCSP-22067
- https://jira.mongodb.org/browse/DOCSP-21980
- [Threading (Swift SDK) -> Append to a Frozen Collection](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21980/sdk/swift/advanced-guides/threading/#append-to-a-frozen-collection): New subsection about appending a frozen object to a frozen collection
[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWIN …

(DOCSP-21980): [Swift SDK] Add section to docs about appending frozen objects to frozen collections

---

source/endpoints.txt
source/includes/steps-create-an-endpoint-cli.yaml
source/includes/steps-create-an-endpoint-ui.yaml
source/services/convert-webhooks-to-endpoints.txt

update docs to reflect the fact that users can use the endpoint function return value along with the function's `response` object methods. 
(previously it'd been only the response object or the endpoint function return value, not combo of both)
- https://jira.mongodb.org/browse/DOCSP-21708
- [Create HTTPS Endpoint](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21708/endpoints/configure/#configure-the-endpoint-response)
- [Convert Webhooks to Endpoints](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21708/services/convert-webhooks-to-endpoints/)

(DOCSP-21708): Use endpoints `response` object with  function returns as body

---

source/reference/realm-query-language.txt

remove inaccuracy stating that RQL supports RQL `@avg` on arrays
N/A 
- [RQL](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/rql_flex_sync_no_avg/reference/realm-query-language/)

Remove support for `@avg` for Flexible Sync arrays

---

source/schemas/enforce-a-schema.txt

Document how to add null support for optional types in a realm schema
- https://jira.mongodb.org/browse/DOCSP-20436
- [Enforce a Schema page > Validate Null Types section](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20436/schemas/enforce-a-schema#validate-null-types)

(DOCSP-20436): Add Null Support for Optional Types in Realm Schema

---

source/index.txt
source/realm-legacy.txt
source/sdk.txt

Removes legacy links from sidebars for SEO.
See https://jira.mongodb.org/browse/DOP-2938 for context.
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/remove-legacy-links/ (see sidebar)

Remove legacy links

---

source/reference/realm-query-language.txt
source/sync/data-access-patterns/flexible-sync.txt
tools/autobuilder/src/index.ts

https://jira.mongodb.org/browse/DOCSP-22050
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22050/reference/realm-query-language/
and
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22050/sync/data-access-patterns/flexible-sync/#eligible-field-types
Change to autobuilder/src/index.ts is a work-around for a borked autobuilder. Change should only be needed for the short term, but does no harm being in there for ever.

remove limits around arrays and clarify text - DOCSP-22050

---

source/sdk/dotnet/fundamentals/device-sync.txt
source/sdk/flutter/app-services.txt
source/sdk/flutter/sync.txt
source/sdk/flutter/users/multiple-users.txt
source/sdk/java/api/io/realm/mongodb/AppConfiguration.txt
source/sdk/java/fundamentals/device-sync.txt
source/sdk/kotlin/app-services/overview.txt
source/sdk/kotlin/sync/overview.txt
source/sdk/node/fundamentals/device-sync.txt
source/sdk/react-native/fundamentals/device-sync.txt
source/sdk/swift/fundamentals/device-sync.txt

Changed to "an" instead of "a" where it is needed.

Fix type mistakes because of renaming

---

examples/ios/Examples/FlexibleSync.swift
examples/ios/RealmExamples.xcodeproj/project.pbxproj
examples/ios/RealmExamples.xcodeproj/xcshareddata/xcschemes/RealmExamplesHostApp.xcscheme
source/examples/generated/code/start/FlexibleSync.snippet.add-initial-subscriptions-rerun-on-open.swift
source/examples/generated/code/start/FlexibleSync.snippet.flexible-sync-models.swift
source/sdk/swift/examples/flexible-sync.txt

In addition to the Jira ticket linked below, this PR also updates a skipped (failing) test - instead of commenting the test, the unit test suite is now skipping it. I have a separate Jira ticket to fix that failing test.
- https://jira.mongodb.org/browse/DOCSP-23116
- [Flexible Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-23116/sdk/swift/examples/flexible-sync/#bootstrap-the-realm-with-initial-subscriptions): Update the second example in "Bootstrap the Realm with Initial Subscriptions" to show a more applicable `rerunOnOpen` example that re-computes date-related variables on app startup.

(DOCSP-23116): [Swift] Update Flex Sync rerunOnOpen example to show re-computing vars

---

source/sdk/react-native/install.txt

- https://jira.mongodb.org/browse/DOCSP-23439
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-23439-Expo-v45-not-supported/sdk/react-native/install/

(DOCSP-23439): Expo v45 not supported note

---

source/sdk/react-native/install.txt

- https://jira.mongodb.org/browse/DOCSP-23563
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-23563-Expo-SDK-v45-github-issue-tracking/sdk/react-native/install/

(DOCSP-23563): Expo V45 not compatible with Android

---

source/includes/rql-aggregation.rst
source/includes/rql.rst
source/reference/realm-query-language.txt

document querying ObjectID & UUID. 
also removed some unnecessary whitespace.
- https://jira.mongodb.org/browse/DOCSP-19870
- [RQL Reference](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19870/reference/realm-query-language#objectid-and-uuid-operators)
- note: content included in a couple of pages

(DOCSP-19870): RQL for ObjectId & UUID

---

source/sdk/node/examples/flexible-sync.txt
source/sdk/react-native/examples/flexible-sync.txt

- https://jira.mongodb.org/browse/DOCSP-24209
- [Flexible Sync - Node.js SDK # Bootstrap the Realm with Initial Subscriptions](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/remove-rerunonopen-js/sdk/node/examples/flexible-sync/#bootstrap-the-realm-with-initial-subscriptions)
- [Flexible Sync - React Native SDK # Bootstrap the Realm with Initial Subscriptions](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/remove-rerunonopen-js/sdk/react-native/examples/flexible-sync/#bootstrap-the-realm-with-initial-subscriptions)

(DOCSP-24209): Remove `reRunOnOpen` API for realm-js docs

---

source/includes/note-writecopy-pbs-only.rst
source/sdk/node/examples/open-and-close-a-realm.txt
source/sdk/react-native/examples/open-and-close-a-realm.txt
source/sdk/swift/sync/configure-and-open-a-synced-realm.txt

- https://jira.mongodb.org/browse/DOCSP-24293
- [Open & Close a Realm - Node.js SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24293/sdk/node/examples/open-and-close-a-realm/#copy-data-and-open-a-new-realm)
- [Open & Close a Realm - RN SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24293/sdk/react-native/examples/open-and-close-a-realm/#copy-data-and-open-a-new-realm)
- [Configure & Open a Synced Realm - Swift SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24293/sdk/swift/sync/configure-and-open-a-synced-realm/#open-non-synced-realm-as-a-synced-realm)

(DOCSP-24293): Add note about writeCopy only supporting PBS

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-24141

(DOCSP-24141): Add docs release notes for w/e August 5

---

source/sdk/swift/react-to-changes.txt

- https://jira.mongodb.org/browse/DOCSP-24604
- [React to Changes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24604/sdk/swift/react-to-changes/#notification-delivery): New "Notification Delivery" section describing notification delivery guarantees relative to an issue that can be triggered when you try to notify while within a write transaction.

(DOCSP-24604): Add information about notification delivery

---

examples/ios/Examples/EmbeddedObjects.m
examples/ios/Examples/ObjectModels.m
examples/ios/Examples/QueryEngine.m
examples/ios/Examples/ReadWriteData.m
examples/ios/Examples/Relationships.m
examples/ios/RealmExamples.xcodeproj/xcshareddata/xcschemes/RealmExamplesHostApp.xcscheme
source/examples/generated/code/start/EmbeddedObjects.snippet.models.m
source/examples/generated/code/start/ObjectModels.snippet.array-declaration.m
source/examples/generated/code/start/QueryEngine.snippet.models.m
source/examples/generated/code/start/ReadWriteData.snippet.models.m
source/examples/generated/code/start/Relationships.snippet.inverse-relationship.m
source/examples/generated/code/start/Relationships.snippet.to-many-relationship.m
source/examples/generated/code/start/Relationships.snippet.to-one-relationship.m
source/sdk/swift/model-data/define-model/object-models.txt
source/sdk/swift/model-data/define-model/relationships.txt

- https://jira.mongodb.org/browse/DOCSP-24797
Small updates to Objective-C code examples & accompanying text where it mentions the deprecated `RLM_ARRAY_TYPE` on these pages:
- [Model Data -> Object Models](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24797/sdk/swift/model-data/define-model/object-models/)
- [Model Data -> Relationships](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24797/sdk/swift/model-data/define-model/relationships/)

(DOCSP-24797): Update deprecated RLM_ARRAY_TYPE to RLM_COLLECTION_TYPE macro

---

source/sdk/kotlin/sync/subscribe.txt

Fixes a typo. The header currently has a floating backtick.
Current header: https://www.mongodb.com/docs/realm/sdk/kotlin/sync/subscribe/#subscriptionset.state---enum
Interestingly, only one backtick appears and the space between the backticks and the word "Enum" does not render. I'm not sure what happens with monospace titles in the new site styling but it might be worth previewing to be sure this is OK.

Fix section header monospacing typo

---

source/sdk/swift.txt
source/sdk/swift/quick-start-index.txt
source/sdk/swift/swiftui.txt

- https://jira.mongodb.org/browse/DOCSP-24897
- [Swift SDK landing page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24897/sdk/swift/#swiftui): Added a SwiftUI header w/example and link to docs
- [SwiftUI landing page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24897/sdk/swift/swiftui/): Added a link to the template apps
I also moved the "SwiftUI Quick Start" from the "Quick Starts" ToC to the SwiftUI ToC. Once we unify the non-Sync/Sync quick start, I think I'll move the Xcode Playground page to the top level of the ToC and get rid of the quick starts directory.

(DOCSP-24897): Small SwiftUI discoverability improvements

---

examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/QuickStartTest.kt
source/examples/generated/kotlin/QuickStartTest.snippet.quick-start-open-a-synced-realm.kt

N/A
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/kotlin-revamped-quickstart-quick-bug-fix/sdk/kotlin/quick-start/#open-a-synced-realm

Quickfix - typo - set query to "owner_id == user.identity", **not** "owner_id == user"

---

examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/QuickStartTest.kt
source/examples/generated/kotlin/QuickStartTest.snippet.quick-start-open-a-synced-realm.kt
source/examples/generated/kotlin/QuickStartTest.snippet.quick-start.kt
source/sdk/kotlin/quick-start.txt

N/A
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/quickfixes-quickstart/sdk/kotlin/quick-start/
- Swaps "ownerId" as a queryable field with "owner_id" (which is the correct field)
- Fixes spacing in opening the synced realm with flex sync

Quickfixes quickstart

---

source/index.txt

fix broken landing page button link. previously was directing to mongodb.com/tutorial. 
now redirects to correct page by making link relative. 
note that if this button ever moves to another page, the link won't work b/c it's path dependent. (for more info, see [absolute v. relative link](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks#absolute_versus_relative_urls) docs)
n/a. issue reported on slack. 
- [index page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fix_broken_link/)

Fix broken link button

---

source/sdk/flutter/install.txt

note Realm Dart/Flutter incompatible with Dart 2.17.3
- https://jira.mongodb.org/browse/DOCSP-24661
- [Install (flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24661/sdk/flutter/install)

(DOCSP-24661): note Realm Dart/Flutter incompatible with Dart 2.17.3

---

.github/workflows/ios.yml
examples/ios/Examples/AddSyncToApp.swift
examples/ios/Examples/BundleRealms.swift
examples/ios/Examples/ConvertSyncLocalRealms.swift
examples/ios/Examples/FlexibleSync.swift
examples/ios/Examples/LocalOnlyCompleteQuickStart.swift
examples/ios/Examples/OpenCloseRealm.swift
examples/ios/Examples/QuickStartFlexSync.swift
examples/ios/Examples/Sync.m
examples/ios/Examples/Threading.swift
examples/ios/RealmExamples.xcodeproj/project.pbxproj
examples/ios/RealmExamples.xcodeproj/xcshareddata/xcschemes/RealmExamplesHostApp.xcscheme

This PR fixes threading-related issues in most of the tests, and adds back a model deleted in #2156 that some other tests depend on. Two tests are still disabled and will be addressed in separate Jira tickets.
Also updates the GitHub CI to run on Xcode 14.
- https://jira.mongodb.org/browse/DOCSP-25225

(DOCSP-25225): Fix build errors, update unit tests for Xcode 14

---

examples/node/Examples/realm-query-language.js
source/examples/generated/realm-query-language/realm-query-language.snippet.list-comparisons-parameterized.js
source/examples/generated/realm-query-language/realm-query-language.snippet.nil-type-parameterized-query.js
source/examples/generated/realm-query-language/realm-query-language.snippet.nil-type.js
source/examples/generated/realm-query-language/realm-query-language.snippet.simple-query.js
source/realm-query-language.txt
source/sdk/node/examples/query-data.txt
source/sdk/react-native/examples/query-data.txt

- Document RQL `nil` type
- add tested code example and remove "TODO" from docs
- https://jira.mongodb.org/browse/DOCSP-24835
- [Realm Query Language](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24835/realm-query-language#nil-type)
- [Query Data (Node)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24835/sdk/node/examples/query-data)
- [Query Data (React Native)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24835/sdk/react-native/examples/query-data) (same as Node)

(DOCSP-24835): Document RQL `nil` type && fix untested code ex

---

.github/workflows/ios.yml
examples/ios/Examples/AsymmetricSync.swift
examples/ios/RealmExamples.xcodeproj/project.pbxproj
source/examples/generated/code/start/AsymmetricSync.snippet.asymmetric-model.swift
source/examples/generated/code/start/AsymmetricSync.snippet.connect-and-authenticate.swift
source/examples/generated/code/start/AsymmetricSync.snippet.create-asymmetric-object.swift
source/examples/generated/code/start/AsymmetricSync.snippet.open-asymmetric-sync-realm.swift
source/sdk/swift/crud/create.txt
source/sdk/swift/model-data/define-model/object-models.txt
source/sdk/swift/sync.txt
source/sdk/swift/sync/configure-and-open-a-synced-realm.txt
source/sdk/swift/sync/flexible-sync.txt
source/sdk/swift/sync/stream-data-to-atlas.txt

- https://jira.mongodb.org/browse/DOCSP-23333
- [Model Data/Define an Object Model](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-23333/sdk/swift/model-data/define-model/object-models/#define-an-asymmetric-object): New "Define an Asymmetric Object" section
- [CRUD/Create](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-23333/sdk/swift/crud/create/#create-an-asymmetric-object): New "Create an Asymmetric Object" section
- [Sync Data/Configure & Open a Synced Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-23333/sdk/swift/sync/configure-and-open-a-synced-realm/#open-a-synced-realm-for-flexible-sync): Update note to specify Asymmetric Sync does not require a subscription
- [Sync Data/Manage …

(DOCSP-23333): Asymmetric Sync docs for Swift SDK

---

source/sdk/flutter/realm-database/define-realm-object-schema.txt

Public realm models with `$` prefix on class names. 
note that not heavily documenting this functionality b/c the SDK team advocates defining all models in a single file. 
- https://jira.mongodb.org/browse/DOCSP-24223
- [Define Realm Object Schema (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24223/sdk/flutter/realm-database/define-realm-object-schema)

(DOCSP-24223): Flutter public realm models with `$`

---

examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
source/examples/generated/kotlin/AuthenticationTest.snippet.anonymous-authentication-reuse-existing.kt
source/sdk/kotlin/app-services/authenticate-users.txt

- https://jira.mongodb.org/browse/DOCSP-25095
- [Authenticate Users - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/reuse-existing-anon-credential/sdk/kotlin/app-services/authenticate-users/)

(DOCSP-25095): document 'reuseExisting' support for Realm Kotlin

---

source/sdk/swift.txt
source/web.txt

remove `.. introduction:: ` directive at top of new SDK landing pages, which was making the content just be in 1 column.
n/a
- [Swift SDK (landing page)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/landing_page_fix/sdk/swift)
- [Web SDK (landing page)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/landing_page_fix//web)

landing page fix

---

source/sdk/flutter/users/email-password-users.txt

Add warning admonition about breaking change to email/password authentication in SDK v0.5.0
- https://jira.mongodb.org/browse/DOCSP-25668
- [Authenticate Users (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-25668/sdk/flutter/users/authenticate)

(DOCSP-25668): Flutter email/password auth breaking change note

---

source/sdk/dotnet.txt

remove the `.. introduction::` directive so that the first line of the landing page stretches across the entire screen width.
n/a
- [.NET SDK (landing page)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/dotnet_landing_page_fix/sdk/dotnet)

Fix .NET landing page spacing

---

examples/ios/Examples/ClientReset.swift
examples/ios/RealmExamples.xcodeproj/project.pbxproj
source/examples/generated/code/start/ClientReset.snippet.client-reset-with-blocks.swift
source/examples/generated/code/start/ClientReset.snippet.manual-fallback-error-handler.swift
source/examples/generated/code/start/ClientReset.snippet.specify-client-reset-mode.swift
source/examples/generated/code/start/ClientReset.snippet.specify-discard.swift
source/examples/generated/code/start/ClientReset.snippet.specify-manual.swift
source/includes/client-recovery-rules.rst
source/sdk/swift/sync/handle-sync-errors.txt

Note for reviewer: there are a couple of :ref:s that won't work until the App Services Client Reset PR is merged ([#165](https://github.com/mongodb/docs-app-services/pull/165)).
Todo before merging:
- https://jira.mongodb.org/browse/DOCSP-23489
- [Handle Sync Errors](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-23489/sdk/swift/sync/handle-sync-errors/#client-reset): Revised Client Reset section

(DOCSP-23489): Swift client reset with recovery docs

---

source/sdk/flutter/app-services.txt
source/sdk/flutter/quick-start.txt
source/sdk/flutter/realm-database/define-realm-object-schema.txt
source/sdk/flutter/users/authenticate.txt
source/sdk/flutter/users/multiple-users.txt
source/sdk/node/examples/reset-a-client-realm.txt

Remove all `.. seealso::` directives in the Realm Flutter SDK.
replaced all these with "For more information [about a topic (sometimes)], refer to :ref:`Page Title <top-of-page-ref>`."
**Note:** i've prefixed all of the page title links with "refer to". not committed to using this longer-term. did this b/c there were already some "refer to"s spread throughout the flutter docs. there's been some docs team discussion abt what the verb should be here ("see", "go to", maybe something else?). if we want to change "refer to" to something else, it would be a simple find-replace operation.
n/a
- [Flutter SDK (changes throughout section)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/remove_flutter_see_also/sdk/flutter) …

Remove Flutter `seealso` directives

---

source/sdk/java.txt
source/sdk/java/examples/open-and-close-a-realm.txt

Note for reviewer: I left out the "Learning Paths" since the Java SDK does not have a Flexible Sync template app or tutorial. I instead put the local quick start link in the "Recommended Reading" section.
The Java SDK _does_ have three quick starts, though - one for local Realm DB, one for Realm Sync (but it's still Partition-Based Sync), and one for using Realm with Android's Live Data. I could potentially put those in the "learning paths" but there isn't a good Flexible Sync learning resource. Thoughts?
- https://jira.mongodb.org/browse/DOCSP-25988
- [Java SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-25988/sdk/java/)

(DOCSP-25988): Update Java SDK landing page for new format

---

examples/ios/Examples/OpenCloseRealm.swift
examples/ios/RealmExamples.xcodeproj/project.pbxproj
examples/ios/RealmExamplesHostApp.entitlements

This PR adds an App Group corresponding to the `tvOS` test: `group.com.mongodb.realm.examples.extension`
Fixes a build failure related to finding nil when unwrapping because this App Group did not exist.
- https://jira.mongodb.org/browse/DOCSP-25247

(DOCSP-25427): Add App Group corresponding to tvOS test to fix tvOS test failure

---

examples/dart/test/read_write_data_test.dart
source/examples/generated/flutter/read_write_data_test.snippet.write-async.dart
source/sdk/flutter/realm-database/read-and-write-data.txt

- https://jira.mongodb.org/browse/DOCSP-24587
- [Read & Write Data](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24587/sdk/flutter/realm-database/read-and-write-data/#background-writes): New "Background Writes" section w/writeAsync example

(DOCSP-24587): Add writeAsync example to Flutter docs

---

examples/ios/Examples/Threading.swift
source/examples/generated/code/start/Threading.snippet.threadsafe-wrapper-function-parameter.swift

- https://jira.mongodb.org/browse/DOCSP-26187
- [Threading - Use the ThreadSafe Wrapper](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26187/sdk/swift/crud/threading/#use-the--threadsafe-wrapper): Update the example in the "example" box showing how to use `@ThreadSafe` on a function parameter

(DOCSP-26187): Update ThreadSafe wrapper Parameter example to work with Swift actors

---

source/sdk/dotnet.txt
source/sdk/flutter.txt
source/sdk/java.txt
source/sdk/kotlin.txt
source/sdk/node.txt
source/sdk/react-native.txt
source/sdk/swift.txt
source/web.txt

Made new SDK landing pages more uniform in following ways:
- same images for relevant similar sections
- removed code examples for working with app services
- standardized general phrasing to remove "For more information..." in each step.
- https://jira.mongodb.org/browse/DOCSP-26005
- [changes across all SDK landing pages](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26005/)

(DOCSP-26005): make SDK landing pages more uniform

---

source/introduction.txt

Update 'Get Started with Realm' section of Introduction. Removed outdated references to Task Tracker tutorial. Just redirected users to each SDK's landing page b/c now they've been filled with all kinds of useful introduction/getting started tasks.
n/a
- [Introduction](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/intro_tweak/introduction)

Update get started intro section

---

examples/node/Examples/realm-query-language.js
source/examples/generated/realm-query-language/realm-query-language.snippet.sort-distinct-limit.js
source/includes/flex-sync-limitations.rst
source/realm-query-language.txt

- (DOCSP-24154) [BAAS] Support new IN syntax in RQL for Flexible Sync
- [Realm Query Language](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/rql-in/realm-query-language/#list-queries)

(DOCSP-24154) [BAAS] Support new IN syntax in RQL for Flexible Sync

---

source/sdk/dotnet/fundamentals/write-transactions.txt

Added a note indicating that the new methods take a cancellationToken. Since these methods use the token as all other C# async methods do, no need to add explanation or code example to our docs.
https://jira.mongodb.org/browse/DOCSP-22721
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cancel_token/sdk/dotnet/fundamentals/write-transactions/

Add info about cancellationToken

---

examples/dart/test/compact_realm_test.dart
source/examples/generated/flutter/compact_realm_test.snippet.compact-with-callback-and-logic.dart
source/examples/generated/flutter/compact_realm_test.snippet.compact-with-callback.dart
source/sdk/flutter/realm-database.txt
source/sdk/flutter/realm-database/compact.txt
source/sdk/flutter/realm-database/open-and-close-a-realm.txt

This adds a page for compacting a Realm, showing the use of the `shouldCompactCallback()` API that is currently available.
- https://jira.mongodb.org/browse/DOCSP-26316
- [Compact a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24586/sdk/flutter/realm-database/compact/): New page
- [Open & Close a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24586/sdk/flutter/realm-database/open-and-close-a-realm/#compact-a-realm): New subsection mentioning compacting a realm and linking to the new page

(DOCSP-26316): Flutter - new Compact a Realm page

---

source/index.txt
source/sdk.txt
source/sdk/flutter.txt

Update the docs to refer to Flutter as RC instead of Beta. 
Flutter SDK going RC early November 2022.
- https://jira.mongodb.org/browse/DOCSP-26274
- [Flutter SDK landing page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26274/sdk/flutter)

(DOCSP-26274): Update Flutter docs to reference RC release

---

source/sdk/swift/install.txt

This is required for simulators on m1 macs and is quite a bit simpler as a bonus.

Update the Carthage installation instructions to use xcframeworks

---

examples/node/Examples/client-reset.js
examples/node/package-lock.json
examples/node/package.json
source/examples/generated/node/client-reset.snippet.discard-unsynced-changes-after-destructive-schema-changes.js
source/examples/generated/node/client-reset.snippet.discard-unsynced-changes.js
source/examples/generated/node/client-reset.snippet.manual-client-reset-onmanual.js
source/examples/generated/node/client-reset.snippet.recover-or-discard-unsynced-changes.js
source/examples/generated/node/client-reset.snippet.recover-unsynced-changes.js
source/examples/generated/node/client-reset.snippet.recovery-fallback.js
source/sdk/node/advanced/client-reset-data-recovery.txt
source/sdk/node/examples/reset-a-client-realm.txt
source/sdk/react-native/advanced/client-reset-data-recovery.txt
source/sdk/react-native/examples/reset-a-client-realm.txt
source/sdk/swift/sync/handle-sync-errors.txt

document automatic client reset w recovery for Node.js SDK and React Native SDK.
includes a more or less total refactor of the client reset documentation to accommodate this.
additionally small copy edit fix to Swift SDK client reset docs.
note that the `"discardUnsyncedChanges"` client reset mode doesn't include the `onFallback` callback, unlike the equivalent modes for other SDKs. the docs reflect this accurately.
- https://jira.mongodb.org/browse/DOCSP-23425
- [Client Reset Data Recovery (Node.js)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-23425/sdk/node/examples/reset-a-client-realm/)
- [Client Reset Data Recovery (React Native)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-23425/sdk/react-native/examples/reset-a-cl …

(DOCSP-23425): JS automatic client reset with recovery

---

examples/dart/test/data_types_test.dart
source/examples/generated/flutter/data_types_test.snippet.embedded-object-examples.dart
source/sdk/flutter/realm-database/data-types.txt

- https://jira.mongodb.org/browse/DOCSP-26329
- [Data Types/Embedded Objects](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26329/sdk/flutter/realm-database/data-types/#embedded-objects): Update example to show accessing the parent from an embedded object, link to property in API reference

(DOCSP-26329): Flutter: Add documentation for embedded object parent property

---

source/sdk/dotnet/install.txt

I am just removing a note that is related to versions of Xamarin.iOS and Realm that are now more than 1 year old, so it can be safely removed.

Removed note related to old versions

---

examples/ios/Examples/Task.swift
examples/ios/RealmExamples.xcodeproj/project.pbxproj
source/sdk/swift.txt
source/sdk/swift/app-services/call-a-function.txt
source/sdk/swift/realm-files/compacting.txt
source/sdk/swift/swift-concurrency.txt
source/sdk/swift/users/authenticate-users.txt

The original scope for this Jira ticket was to document what you can do with Realm in a Swift `Task`. After looking around at various discussions in the community, I've expanded this to incorporate general guidance on using Realm with Swift concurrency features.
- https://jira.mongodb.org/browse/DOCSP-23501
- [Swift Concurrency](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-23501/sdk/swift/swift-concurrency/)

(DOCSP-23501): Add a new Swift Concurrency page to Swift SDK docs

---

source/sdk/flutter/quick-start.txt

Slim down Flutter Quick Start to align w content in other sdks' quick start pages.
- https://jira.mongodb.org/browse/DOCSP-26572
- [Quick Start (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26572/sdk/flutter/quick-start)

(DOCSP-26572): Slim down Flutter Quick Start

---

.github/workflows/readability.yml

In an attempt to fix the readability workflow check, I'm updating the workflow to a more recent version of the setup-python GitHub action, updating to a newer version of Python, and removing the x64 architecture since that's the default when unspecified. 🤞

Fix Readability workflow

---

source/includes/access-app-id.rst
source/sdk/dotnet/quick-start.txt
source/sdk/flutter/quick-start.txt
source/sdk/java/quick-start-sync.txt
source/sdk/kotlin/quick-start.txt
source/sdk/node/quick-start.txt
source/sdk/react-native/quick-start.txt
source/sdk/swift/quick-start.txt
source/web/quickstart.txt

- https://jira.mongodb.org/browse/DOCSP-26271
"Find your App ID" procedure should be linked out in every SDK quick start
- [Staged Changes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-26271-app-id/sdk/java/quick-start-sync/#initialize-the-app)

(DOCSP-26271): Adding link to find App ID to quick start

---

source/sdk/swift/realm-files/configure-and-open-a-realm.txt

This is a quick tweak based on a comment I left on #2325 - changing the link to a more appropriate spot based on language used in context around the link.
- [Configure & Open a Realm/Realm Files](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/tweak-swift-file-path-link/sdk/swift/realm-files/configure-and-open-a-realm/#key-concept--realm-files): Changed the "at a specific path" link to point to the Swift docs section about how to define a file URL path for your realm

Update link in Swift docs to point to a more relevant section

---

examples/dart/test/access_token_test.dart
examples/dart/test/add_sync_to_app.dart
examples/dart/test/add_sync_to_app.g.dart
source/examples/generated/flutter/add_sync_to_app.snippet.connect-to-app.dart
source/examples/generated/flutter/add_sync_to_app.snippet.log-in.dart
source/examples/generated/flutter/add_sync_to_app.snippet.opened-synced-realm.dart
source/examples/generated/flutter/add_sync_to_app.snippet.write.dart
source/sdk/flutter/sync.txt
source/sdk/flutter/sync/add-sync-to-app.txt

Flutter Add Sync to App page
- https://jira.mongodb.org/browse/DOCSP-26794
- [Add Sync to App (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26794/sdk/flutter/sync/add-sync-to-app)

(DOCSP-26794): Flutter Add Sync to App page

---

examples/ios/Examples/ObjectModels.swift
examples/ios/RealmExamples.xcodeproj/project.pbxproj
source/examples/generated/code/start/ObjectModels.snippet.rename-a-property.swift
source/sdk/swift/model-data/define-model/object-models.txt

The eng PR that implements this functionality is still in review. Waiting for SDK release for this feature. Prior to merging:
- https://jira.mongodb.org/browse/DOCSP-26357
- [Object Models - Swift SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26357/sdk/swift/model-data/define-model/object-models/#rename-a-property): New "Rename a Property" section

(DOCSP-26357): Document the ability to rename a property in Swift

---

examples/ios/Examples/Authenticate.swift
source/examples/generated/code/start/Authenticate.snippet.get-user-access-token.swift
source/examples/generated/code/start/Authenticate.snippet.refresh-user-access-token-function.swift
source/sdk/swift/users/authenticate-users.txt

Note for reviewer: the CI is failing to build properly, so the failure here doesn't reflect a test failure - it's an issue with the build script. The test did pass locally: 
```shell
Test Suite 'Authenticate' passed at 2022-12-01 16:36:31.424.
Executed 13 tests, with 0 failures (0 unexpected) in 4.627 (4.631) seconds
Test Suite 'RealmExamples.xctest' passed at 2022-12-01 16:36:31.425.
Executed 13 tests, with 0 failures (0 unexpected) in 4.627 (4.632) seconds
Test Suite 'Selected tests' passed at 2022-12-01 16:36:31.425.
Executed 13 tests, with 0 failures (0 unexpected) in 4.627 (4.633) seconds
```
- https://jira.mongodb.org/browse/DOCSP-26766
- [Authenticate Users](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26766/sdk/swift/users/authenticate-users/#get-a …

(DOCSP-26766): [Swift] Get a User Access Token

---

source/sdk/dotnet/quick-start.txt
source/sdk/java/quick-start-local.txt
source/sdk/java/quick-start-sync.txt
source/sdk/kotlin/quick-start.txt
source/sdk/node/examples/query-mongodb.txt
source/sdk/node/quick-start.txt
source/sdk/react-native/app-services/query-mongodb.txt
source/sdk/react-native/quick-start.txt
source/sdk/swift/quick-start.txt

https://jira.mongodb.org/browse/DOCSP-26588
- Removing serverless note from all SDK Quick Start pages (done as part of a previous [PR](https://github.com/mongodb/docs-realm/pull/1993/files))
- Adding note to any SDK Query MongoDB pages with _Watch for Changes_ section where it's not already there
- [various SDK Quick Start and Query MongoDB pages](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-26588-fix-serverless-note/sdk/java/quick-start-sync/#watch-for-changes)

(DOCSP-26588): Removing serverless note from Quick Start pages

---

examples/dart/README.md

All links should point to `main` branch now instead of `master` branch

use main instead of master

---

source/sdk/flutter/sync.txt

Add synced realm overview content to Flutter Sync landing page.
(taken and adapted from [.NET docs](https://www.mongodb.com/docs/realm/sdk/dotnet/sync/configure-and-open-a-synced-realm/#key-concept--synced-realms))
- https://jira.mongodb.org/browse/DOCSP-26796
- [Sync Data (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26796/sdk/flutter/sync/)

(DOCSP-26796): Add synced realm content to sync landing page

---

source/includes/find-realm-file-flutter.rst
source/includes/find-realm-file-kotlin.rst
source/studio/modify-schema.txt
source/studio/open-realm-file.txt

The Realm Studio docs were missing some SDKs in tabbed content.
- https://jira.mongodb.org/browse/DOCSP-26785
- [Open a Realm File](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26785/studio/open-realm-file/#find-a-realm-file). Added code samples for finding a realm (Flutter and Kotlin).
- [Modify Schema in a Realm Studio](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26785/studio/modify-schema/#perform-a-migration). Added a link to Flutter's migration content.
- [ n/a ] Create Jira ticket for corresponding docs-app-services update(s), if any
- [ n/a ] Checked/updated Admin API
- [ n/a ] Checked/updated CLI …

(DOCSP-26785): Add missing SDKs to Realm Studio docs

---

source/sdk/flutter/app-services.txt
source/sdk/flutter/model-data/define-realm-object-schema.txt
source/sdk/java/api/io/realm/mongodb/AppConfiguration.txt

No Jira - Fixing small article typo found in Flutter docs ("a App" > "an App")
- [Define a Realm Object Schema](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/flutter-define-rom-typo/sdk/flutter/model-data/define-realm-object-schema/#using-schemas-with-device-sync)

Fixing article typo in Flutter docs

---

examples/dart/test/write_to_synced_realm_test.dart
examples/dart/test/write_to_synced_realm_test.g.dart
source/examples/generated/flutter/write_to_synced_realm_test.snippet.compensating-write.dart
source/examples/generated/flutter/write_to_synced_realm_test.snippet.realm-model.dart
source/examples/generated/flutter/write_to_synced_realm_test.snippet.subscription-setup.dart
source/examples/generated/flutter/write_to_synced_realm_test.snippet.write-synced-realm.dart
source/sdk/flutter/sync.txt
source/sdk/flutter/sync/manage-sync-subscriptions.txt
source/sdk/flutter/sync/write-to-synced-realm.txt

- Add new page about constraints on writing data when writing to a synced realm
- add a conceptual section to 'Manage Sync Subscriptions' page about how subscriptions need to align with backend.
- add bit of info about how subscription sets persist across sessions. 
Note: also created the Bushicorp app write-flex-sync-data-hvpxi to have a dedicated app for the permissions required by this PR.
- https://jira.mongodb.org/browse/DOCSP-26797
- [Write to a Synced Realm (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26797/sdk/flutter/sync/write-to-synced-realm/)
- [Manage Sync Subscriptions (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26797/sdk/flutter/sync/manage-sync-subscriptions/)
If your PR modifies the …

(DOCSP-26797): Flutter - Improve sync subscription documentation

---

source/sdk/kotlin/quick-start.txt

No Jira 
> "tutorial" brings us to https://www.mongodb.com/docs/manual/tutorial/#std-label-tutorial rather than https://www.mongodb.com/docs/atlas/app-services/tutorial/kotlin/
- [Quick Start - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fix-kotlin-link/sdk/kotlin/quick-start/#next--check-out-the-template-apps-and-tutorial)

Fixing link to Kotlin Tutorial page

---

source/sdk/cpp/model-data/relationships.txt

Oops - I missed changing this and introduced an ambiguous ref target. This PR should fix any Snooty autobuilder failures resulting from this.

Fix copy-paste error causing ambiguous target

---

source/includes/note-sync-state-complete.rst
source/sdk/dotnet/sync/flexible-sync.txt
source/sdk/flutter/sync/manage-sync-subscriptions.txt
source/sdk/java/examples/flexible-sync.txt
source/sdk/kotlin/sync/subscribe.txt
source/sdk/node/examples/flexible-sync.txt
source/sdk/react-native/sync-data/flexible-sync.txt
source/sdk/swift/sync/flexible-sync.txt

- Adds a note to detail the completed state in general. Included the note on each relevant SDK.
- Clarified and tightened up the various sections on subscription states.
- Added links to SDK reference manual if needed.
- Debated whether to add a Table for this listing all of the states, but that info is already in the SDK reference docs.
- https://jira.mongodb.org/browse/DOCSP-26899
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/subscriptions-state/sdk/dotnet/sync/flexible-sync/#subscription-state
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/subscriptions-state/sdk/flutter/sync/manage-sync-subscriptions/#subscription-state
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/subscriptions-state/sdk/kotlin/sync/ …

(DOCSP-26899): Clarify "completed" subscription state

---

examples/dart/test/app_services_test.dart
source/examples/generated/flutter/app_services_test.snippet.custom-ssl-cert.dart
source/sdk/flutter/app-services/connect-to-app.txt

Add documentation section about custom HTTP client for Android <= 7.
- https://jira.mongodb.org/browse/DOCSP-26512
- [Connect to App Services > Connect Using Android 7 or Older section](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26512/sdk/flutter/app-services/connect-to-app/)

(DOCSP-26512): Info about custom HTTP client for Android <= 7

---

source/sdk/flutter/sync/manage-sync-session.txt

Remove download progress notification from Flutter docs. Done b/c this behavior isn't currently supported due to some Sync server issues. 
- https://jira.mongodb.org/browse/DOCSP-27056
- [Manage Sync Session (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27056/sdk/flutter/sync/manage-sync-session/)

(DOCSP-27056): Flutter - Remove download progress notification docs

---

source/sdk/flutter.txt

Add tab section about Atlas App Services to Flutter SDK landing page
- https://jira.mongodb.org/browse/DOCSP-27161
- [Flutter SDK (landing page)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27161/sdk/flutter/)

(DOCSP-27161): Flutter add App Services to landing page

---

examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/RQLTest.kt
source/examples/generated/kotlin/RQLTest.snippet.rql-schema-example.kt
source/realm-query-language.txt

- https://jira.mongodb.org/browse/DOCSP-27146
- Updated Kotlin example to use `ObjectId`   
- [Realm Query Language](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-27146-kotlin-rql-update/realm-query-language/#examples-on-this-page) example (Kotlin tab)

(DOCSP-27146): Updating Kotlin example in RQL docs

---

examples/react-native/.eslintrc.js
examples/react-native/__tests__/js/models/Cat.js
examples/react-native/__tests__/js/realm-database/schemas/mixed-tests.jsx
examples/react-native/__tests__/ts/models/Cat.ts
examples/react-native/__tests__/ts/realm-database/schemas/mixed-test.tsx
examples/react-native/testSetup.js
source/examples/generated/react-native/js/Cat.snippet.js-cat-schema.js
source/examples/generated/react-native/js/mixed-tests.snippet.create-mixed-object.jsx
source/examples/generated/react-native/js/mixed-tests.snippet.query-mixed-object.jsx
source/examples/generated/react-native/ts/Cat.snippet.ts-cat-schema.ts
source/examples/generated/react-native/ts/mixed-test.snippet.create-mixed-object.tsx
source/examples/generated/react-native/ts/mixed-test.snippet.query-mixed-object.tsx
source/sdk/react-native/realm-database/schemas/mixed.txt

- https://jira.mongodb.org/browse/DOCSP-26984
- [Mixed - React Native SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/mixed-object/sdk/react-native/realm-database/schemas/mixed/)

(DOCSP-26984): @realm/reactify: Mixed - React Native SDK

---

examples/react-native/.eslintrc.js
examples/react-native/.prettierrc.js
examples/react-native/__tests__/js/models/Profile.js
examples/react-native/__tests__/js/realm-database/schemas/uuid.test.jsx
examples/react-native/__tests__/ts/models/Profile.ts
examples/react-native/__tests__/ts/realm-database/schemas/uuid.test.tsx
source/examples/generated/react-native/js/Profile.snippet.js-profile-schema.js
source/examples/generated/react-native/js/uuid.test.snippet.create-uuid-object.jsx
source/examples/generated/react-native/ts/Profile.snippet.ts-profile-schema.ts
source/examples/generated/react-native/ts/uuid.test.snippet.create-uuid-object.tsx
source/sdk/react-native/realm-database/schemas/uuid.txt

- https://jira.mongodb.org/browse/DOCSP-26985
- [UUID - React Native SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26985-uuid-object/sdk/react-native/realm-database/schemas/uuid/)

(DOCSP-26985): @realm/reactify: UUID - React Native SDK 

---

examples/react-native/__tests__/js/Models/Person.js
examples/react-native/__tests__/js/realm-database/change-an-object-model-test.jsx
examples/react-native/__tests__/ts/Models/Person.ts
examples/react-native/__tests__/ts/realm-database/change-an-object-model-test.tsx
source/examples/generated/react-native/js/Person.snippet.js-person-schema.js
source/examples/generated/react-native/js/change-an-object-model-test.snippet.add-a-property-to-schema.jsx
source/examples/generated/react-native/js/change-an-object-model-test.snippet.delete-a-property-from-a-schema.jsx
source/examples/generated/react-native/js/change-an-object-model-test.snippet.modify-a-property-type.jsx
source/examples/generated/react-native/js/change-an-object-model-test.snippet.rename-a-property-of-a-schema.jsx
source/examples/generated/react-native/ts/Person.snippet.ts-person-schema.ts
source/examples/generated/react-native/ts/change-an-object-model-test.snippet.add-a-property-to-schema.tsx
source/examples/generated/react-native/ts/change-an-object-model-test.snippet.delete-a-property-from-a-schema.tsx
source/examples/generated/react-native/ts/change-an-object-model-test.snippet.modify-a-property-type.tsx
source/examples/generated/react-native/ts/change-an-object-model-test.snippet.rename-a-property-of-a-schema.tsx
source/sdk/react-native/realm-database/change-an-object-model.txt

- https://jira.mongodb.org/browse/DOCSP-26981
- [Change an Object Model - React Native](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26981-Change-A-ROM/sdk/react-native/realm-database/change-an-object-model/)

(DOCSP-26981): @realm/reactify - Change an Object Model - React Native

---

examples/react-native/__tests__/js/Models/Invoice.js
examples/react-native/__tests__/ts/Models/Invoice.ts
source/examples/generated/react-native/js/Invoice.snippet.js-invoice-schema.js
source/examples/generated/react-native/ts/Invoice.snippet.ts-invoice-schema.ts
source/sdk/react-native/realm-database/schemas/asymmetric-object.txt

- https://jira.mongodb.org/browse/DOCSP-26994
- [Define an Asymmetric Object - React Native SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26994-asymmetric-object/sdk/react-native/realm-database/schemas/asymmetric-object/)

(DOCSP-26994): @realm/react-ify 'Define an Asymmetric Object - React Native SDK'

---

source/web.txt
source/web/users.txt

Couple small fixes in Web SDK TOC:
- move Next.js guide up to more visible location
- Add API key management page to TOC (mistake that not currently in there)
n/a
- [Web SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/web_mng_api_key_auth/web)

Web TOC fixes

---

examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/QuickStartTest.kt
source/examples/generated/kotlin/QuickStartTest.snippet.quick-start-open-a-local-realm.kt
source/sdk/kotlin/quick-start.txt

Regenerated the `open-a-realm` snippet and added small blurb about using `RealmConfiguration.create()` (per [Kotlin Sync Feedback Document changes](https://github.com/mongodb/docs-realm/pull/2405#discussion_r1049208862) PR)
- https://jira.mongodb.org/browse/DOCSP-27332
- [Kotlin Quick Start: Open a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-27332-open-realm-fix/sdk/kotlin/quick-start/#open-a-realm)

(DOCSP-27332): Regenerating Kotlin Open a Realm code

---

source/includes/sync-errors-in-app-services.rst
source/sdk/dotnet/sync/handle-sync-errors.txt
source/sdk/flutter/sync/handle-sync-errors.txt
source/sdk/java/examples/sync-changes-between-devices.txt
source/sdk/kotlin/errors/app.txt
source/sdk/node/examples/sync-changes-between-devices.txt
source/sdk/react-native/sync-data/handle-sync-errors.txt
source/sdk/swift/sync/handle-sync-errors.txt

This PR is a quick bandaid to expose more information about Sync errors in the SDK docs in response to this issue: https://github.com/mongodb/docs-realm/issues/2481
We should follow up with a larger project to expand our Sync error handling documentation across SDKs, and ensure consistency with API documentation & documented error codes in Core.
- https://jira.mongodb.org/browse/DOCSP-27391
- [Handle Sync Errors - Flutter SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27391/sdk/flutter/sync/handle-sync-errors/)
- [Sync Changes Between Devices - Java SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27391/sdk/java/examples/sync-changes-between-devices/#handle-sync-errors)
- [Handle App Errors - Kotlin …

(DOCSP-27391): Add a link to App Services Sync Errors from SDKs

---

examples/dart/pubspec.lock
examples/dart/pubspec.yaml
examples/dart/test/access_token_test.dart
examples/dart/test/authenticate_users_test.dart
examples/dart/test/data_types_test.dart
examples/dart/test/data_types_test.g.dart
examples/dart/test/manage_sync_session_test.dart
source/examples/generated/flutter/data_types_test.snippet.realm-value-from.dart
source/examples/generated/flutter/data_types_test.snippet.realm-value-model.dart
source/examples/generated/flutter/data_types_test.snippet.realm-value-type-value.dart
source/sdk/flutter/model-data/data-types.txt
source/sdk/flutter/model-data/property-annotations.txt

Flutter RealmValue documentation.
Note that the reference docs link won't work until the next release which'll include reference docs for this feature.
Note also that the description makes reference to the fact that RealmValue can't be a 'collection', w no further explanation of collections. There is future work for documenting collections, and i'll hyperlink to that here ([ticket](https://jira.mongodb.org/browse/DOCSP-27153)).
- https://jira.mongodb.org/browse/DOCSP-26117
- [Data Types (Flutter) > 'RealmValue' section](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26117/sdk/flutter/model-data/data-types#realmvalue) …

(DOCSP-26117): Flutter RealmValue

---

source/examples/generated/flutter/migrations_test.snippet.migrations-rename-property.dart
source/sdk/flutter/model-data/update-realm-object-schema.txt

Fix Rename property code example.
Adding the code bluehawk code example as part of this PR bc was removed as part of recent update to remove unused examples. no new code written here. code example works.
- https://jira.mongodb.org/browse/DOCSP-27434
- [Update Realm Object Schema](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27434/sdk/flutter/model-data/update-realm-object-schema#rename-a-property)

(DOCSP-27434): Fix Rename property code example

---

examples/node/Examples/authenticate.js
source/examples/generated/node/authenticate.snippet.user-metadata.js
source/includes/configure-user-metadata.rst
source/includes/stale-user-metadata.rst
source/includes/update-user-metadata.rst
source/sdk/dotnet/manage-users/user-metadata.txt
source/sdk/flutter/users/user-metadata.txt
source/sdk/node/examples.txt
source/sdk/node/examples/user-metadata.txt

In addition to adding a new user metadata page for the Node.js SDK, I abstracted the generic info that applies across SDKs into some new includes files. These chunks don't have any SDK-specific content so it'll be easier to maintain them in one spot.
- https://jira.mongodb.org/browse/DOCSP-27372
- [User Metadata](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27372/sdk/node/examples/user-metadata/)

(DOCSP-27372) Add Node.js user metadata page

---

source/sdk/swift/app-services/call-a-function.txt
source/sdk/swift/sync/write-to-synced-realm.txt

- https://jira.mongodb.org/browse/DOCSP-27220
- [Write Data to a Synced Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27220/sdk/swift/sync/write-to-synced-realm/#don-t-write-to-a-synced-realm-in-an-app-extension): New section "Don't Write to a Synced Realm in an App Extension"

(DOCSP-27220): Add information about using a synced realm in an App Extension

---

source/sdk/kotlin/install/kotlin-multiplatform.txt

Correcting version number in KMM Install sample, as reported in https://github.com/realm/realm-kotlin/issues/1224
- https://jira.mongodb.org/browse/DOCSP-15827
- [Install (Kotlin Multiplatform) - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-15827-version-number-fix/sdk/kotlin/install/kotlin-multiplatform/#installation)

(DOCSP-15827): Fix version number in KMM Install code sample

---

examples/cpp/CMakeLists.txt
examples/cpp/authentication.cpp
examples/cpp/define-object-model.cpp
examples/cpp/examples.cpp
examples/cpp/supported-types.cpp
examples/cpp/testHelpers.hpp
examples/cpp/testHelpersTests.cpp

Just trying to update the C++ unit test suite to use & build with the changes introduced in realm-cpp PR # 20. Ran into a bunch of issues, so I've commented out a lot of things just to get the tests to build. We should re-add relevant tests & regenerate Bluehawk snippets as we go through the update tickets in Jira.
@cbush - in particular I'd love for you to take a look at the removeAll testHelpers - I wasn't sure how to address the errors that was throwing so I commented out the whole thing & removed it in the CMakeLists.txt file, but I'd love to add that back in and use it in tests as we re-add stuff.
Also, as you go through the commented-out code, you'll notice I've removed all the primary keys. There was an internal conversion error in the cpp-sdk when I tried to set any type as a …

C++: Update unit test suite for realm-cpp PR #20

---

examples/cpp/define-object-model.cpp
examples/cpp/examples.cpp
source/examples/generated/cpp/define-object-model.snippet.check-size-and-access-results.cpp
source/examples/generated/cpp/define-object-model.snippet.create-embedded-object.cpp
source/examples/generated/cpp/define-object-model.snippet.create-object-with-to-many-relationship.cpp
source/examples/generated/cpp/define-object-model.snippet.create-object-with-to-one-relationship.cpp
source/examples/generated/cpp/define-object-model.snippet.filter-using-type-safe-query.cpp
source/examples/generated/cpp/define-object-model.snippet.model-with-embedded-object.cpp
source/examples/generated/cpp/define-object-model.snippet.model-with-embedded-object.cpp.rst
source/examples/generated/cpp/define-object-model.snippet.model-with-ignored-field.cpp
source/examples/generated/cpp/define-object-model.snippet.to-many-relationship.cpp
source/examples/generated/cpp/define-object-model.snippet.to-one-relationship.cpp
source/examples/generated/cpp/define-object-model.snippet.update-embedded-object.cpp
source/examples/generated/cpp/examples.snippet.define-models.cpp
source/examples/generated/cpp/examples.snippet.open-a-synced-realm.cpp
source/examples/generated/cpp/examples.snippet.single-object-model.cpp
source/examples/generated/cpp/examples.snippet.update-an-object.cpp
source/sdk/cpp/model-data/object-models.txt
source/sdk/cpp/model-data/relationships.txt
source/sdk/cpp/model-data/supported-types.txt

DO NOT MERGE until realm-cpp merges PR # 42
- https://jira.mongodb.org/browse/DOCSP-27498
- [Object Types and Schemas](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27498/sdk/cpp/model-data/object-models/): Update object models for CRTP, add info to "Define a New Object Type" around CRTP
- [Supported Data Types](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27498/sdk/cpp/model-data/supported-types/): Remove required embedded object, as I was only able to get an embedded object to work as an optional
- [Relationships](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27498/sdk/cpp/model-data/relationships/): Update models for CRTP, change to-one relationship model to dog/favorite toy as doubles …

(DOCSP-27498): C++: Update object models and related examples for CRTP

---

examples/cpp/examples.cpp
source/examples/generated/cpp/examples.snippet.open-realm-at-path.cpp
source/sdk/cpp.txt
source/sdk/cpp/install.txt
source/sdk/cpp/realm-database.txt
source/sdk/cpp/realm-files/configure-and-open-a-realm.txt

DO NOT MERGE until realm-cpp merges PR # 42. Once that happens & the API reference docs update, the `async_open` link on this page will break and need to be updated before merging this.
- https://jira.mongodb.org/browse/DOCSP-27502
- [Configure & Open a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27502/sdk/cpp/realm-files/configure-and-open-a-realm/#open-a-realm-at-a-file-path): Update the path example, tweak related text
- [Why Realm Database?](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27502/sdk/cpp/realm-database/): Ported page from Swift because it contains relevant info about realm file stuff, removed some links to pages that don't exist yet in C++ SDK docs
- …

(DOCSP-27502): C++: Update the path example and related text

---

examples/dart/pubspec.lock
examples/dart/pubspec.yaml
examples/dart/test/write_copy_test.dart
examples/dart/test/write_copy_test.g.dart
source/examples/generated/flutter/write_copy_test.snippet.in-memory-to-local.dart
source/examples/generated/flutter/write_copy_test.snippet.unencrypted-to-encrypted.dart
source/sdk/flutter/realm-database/configure-and-open.txt

Flutter copy data to a new realm
- https://jira.mongodb.org/browse/DOCSP-26115
- [Configure and Open a Realm (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26115/sdk/flutter/realm-database/configure-and-open/)

(DOCSP-26115): Flutter copy data to a new realm

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-27548

(DOCSP-27548): Add docs release notes for w/e January 27

---

examples/cpp/CMakeLists.txt
examples/cpp/define-object-model.cpp
examples/cpp/examples.cpp
examples/cpp/supported-types.cpp
source/examples/generated/cpp/define-object-model.snippet.create-embedded-object.cpp
source/examples/generated/cpp/define-object-model.snippet.create-object-with-to-one-relationship.cpp
source/examples/generated/cpp/define-object-model.snippet.model-with-embedded-object.cpp
source/examples/generated/cpp/define-object-model.snippet.to-one-relationship.cpp
source/examples/generated/cpp/examples.snippet.define-models.cpp
source/examples/generated/cpp/supported-types.snippet.optional-object-id.cpp
source/examples/generated/cpp/supported-types.snippet.required-object-id.cpp
source/sdk/cpp/model-data/object-models.txt
source/sdk/cpp/model-data/supported-types.txt

This PR initially just updated the code examples for the primary key fix in the C++ SDK PR # 42. There was no corresponding Jira ticket for that. However, since I'm now showing `object_id` primary keys in some of these code examples, I've added the Jira ticket for that work to this PR retroactively.
- https://jira.mongodb.org/browse/DOCSP-27497
- [Object Types & Schemas/Specify a Primary Key](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/primary-key-fix/sdk/cpp/model-data/object-models/#specify-a-primary-key): Add a list of supported primary key data types
- [Supported Types](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/primary-key-fix/sdk/cpp/model-data/supported-types/): Add `object_id` to supported types list
- …

Update C++ code examples for C++ SDK primary key fix

---

examples/cpp/CMakeLists.txt
examples/cpp/flexible-sync.cpp
source/examples/generated/cpp/flexible-sync.snippet.change-subscription-query.cpp
source/examples/generated/cpp/flexible-sync.snippet.clear-all-subscriptions.cpp
source/examples/generated/cpp/flexible-sync.snippet.flexible-sync-prerequisites.cpp
source/examples/generated/cpp/flexible-sync.snippet.refresh-the-realm.cpp
source/examples/generated/cpp/flexible-sync.snippet.remove-subscription-by-name.cpp
source/examples/generated/cpp/flexible-sync.snippet.subscribe-to-all-objects-of-a-type.cpp
source/examples/generated/cpp/flexible-sync.snippet.subscribe-to-objects-matching-a-query.cpp
source/examples/generated/cpp/flexible-sync.snippet.subscription-count-and-find-subscription.cpp
source/sdk/cpp.txt
source/sdk/cpp/sync/sync-subscriptions.txt

Note for reviewer: I expect a Snooty build error for the ref `cpp-authenticate-users`. That ref is introduced in PR #2531 which will also be merging into this feature branch before merging to master.
- https://jira.mongodb.org/browse/DOCSP-26734
- [Sync Subscriptions](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26734/sdk/cpp/sync/sync-subscriptions/): New page

(DOCSP-26734): C++: Add a Sync Subscriptions page

---

examples/cpp/examples.cpp
snooty.toml
source/examples/generated/cpp/deleteCustomUserData.snippet.delete-custom-user-data.js
source/examples/generated/cpp/examples.snippet.create-custom-user-data.cpp
source/examples/generated/cpp/examples.snippet.delete-custom-user-data.cpp
source/examples/generated/cpp/examples.snippet.read-custom-user-data.cpp
source/examples/generated/cpp/examples.snippet.update-custom-user-data.cpp
source/examples/generated/cpp/updateCustomUserData.snippet.update-custom-user-data.js
source/sdk/cpp.txt
source/sdk/cpp/manage-users.txt
source/sdk/cpp/users/custom-user-data.txt

Now that we've got a few user-related pages, grouping them together in the ToC under a new "Manage Users" section. However, the directory structure for the pages hasn't changed so no redirects are needed.
- https://jira.mongodb.org/browse/DOCSP-27632
- [Custom User Data](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27632/sdk/cpp/users/custom-user-data/): New page
- [Manage Users](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27632/sdk/cpp/manage-users/): New ToC entry + relevant content from the corresponding Swift SDK page, minus the stuff that isn't implemented yet in the C++ SDK …

(DOCSP-27632): C++: Add a Custom User Data page

---

source/includes/flex-sync-limitations.rst

Clarify Flex Sync RQL queries can't compare 2 lists
- https://jira.mongodb.org/browse/DOCSP-27552
- [Realm Query Language](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27552/realm-query-language/)

(DOCSP-27552): Clarify Flex Sync RQL queries can't compare 2 lists

---

examples/react-native/__tests__/ts/app-services/atlas-functions.test.tsx
source/examples/generated/react-native/ts/atlas-functions.test.snippet.call-function.tsx
source/sdk/react-native/app-services/call-a-function.txt

Call a Function for React Native w @realm/react 
- https://jira.mongodb.org/browse/DOCSP-27000
- [Call a Function (RN)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27000/sdk/react-native/app-services/call-a-function/)

(DOCSP-27000): Call a Function for React Native

---

examples/dart/bin/myapp.dart
source/examples/generated/flutter/myapp.snippet.create-synced-bundle.dart
source/sdk/flutter/realm-database/realm-files/bundle.txt

update the bundle a realm page to talk about synced realm.
> **Note**
>
> The ticket specified to use Realm.writeCopy() for this, but based upon my understanding of that API and creating realms generally, I think it's actually more straightforward to just have the user create and copy a realm, as documented here. 
- https://jira.mongodb.org/browse/DOCSP-26118
- [Bundle a Realm (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26118/sdk/flutter/realm-database/realm-files/bundle)

(DOCSP-26118): updated bundle a realm page

---

examples/cpp/examples.cpp
source/examples/generated/cpp/examples.snippet.notifications-object.cpp
source/examples/generated/cpp/examples.snippet.notifications-property-changes.cpp
source/sdk/cpp.txt
source/sdk/cpp/react-to-changes.txt

Note for reviewer: Git shenanigans resulted in #2568 being closed when the feature branch it was working against got merged. This PR was approved in #2568 but had a couple of pieces of feedback, which I incorporated here. 
- https://jira.mongodb.org/browse/DOCSP-26730
- [React to Changes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26730/sdk/cpp/react-to-changes/)

(DOCSP-26730): C++: Add a React to Changes page

---

examples/react-native/__tests__/ts/authentication/delete-user.test.tsx
source/examples/generated/react-native/ts/delete-user.test.snippet.delete-user.tsx
source/sdk/react-native/manage-users/create-and-delete-users.txt

@realm/react-ify Create and Delete Users page
- https://jira.mongodb.org/browse/DOCSP-27002
- [Create & Delete Users (React Native)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27002/sdk/react-native/manage-users/create-and-delete-users/)

(DOCSP-27002): @realm/react-ify Create and Delete Users page

---

examples/cpp/CMakeLists.txt
examples/cpp/quick-start.cpp
snooty.toml
source/examples/generated/cpp/quick-start.snippet.authenticate-user.cpp
source/examples/generated/cpp/quick-start.snippet.connect-to-backend.cpp
source/examples/generated/cpp/quick-start.snippet.create-todo.cpp
source/examples/generated/cpp/quick-start.snippet.delete.cpp
source/examples/generated/cpp/quick-start.snippet.filter.cpp
source/examples/generated/cpp/quick-start.snippet.get-all-todos.cpp
source/examples/generated/cpp/quick-start.snippet.includes.cpp
source/examples/generated/cpp/quick-start.snippet.model.cpp
source/examples/generated/cpp/quick-start.snippet.modify-write-block.cpp
source/examples/generated/cpp/quick-start.snippet.open-synced-realm.cpp
source/examples/generated/cpp/quick-start.snippet.realm-open.cpp
source/examples/generated/cpp/quick-start.snippet.watch-for-changes.cpp
source/examples/generated/cpp/quick-start.snippet.write-to-synced-realm.cpp
source/includes/note-unsupported-flex-sync-rql-operators.rst
source/sdk/cpp.txt
source/sdk/cpp/application-services.txt
source/sdk/cpp/model-data/object-models.txt
source/sdk/cpp/quick-start.txt

As part of this work, I removed the "LINQ" reference in the include that was shared across all the SDKs, and replaced it with the more generic "the SDK's query engine."
- https://jira.mongodb.org/browse/DOCSP-26735
- [Quick Start](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26735/sdk/cpp/quick-start/)
- [App Services](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26735/sdk/cpp/application-services/)

(DOCSP-26735): C++: Add a Quick Start page

---

examples/cpp/CMakeLists.txt
examples/cpp/examples.cpp
source/examples/generated/cpp/examples.snippet.notifications-object.cpp
source/examples/generated/cpp/examples.snippet.notifications-results.cpp
source/examples/generated/cpp/examples.snippet.notifications-unregister.cpp
source/sdk/cpp/react-to-changes.txt

DO NOT MERGE until PR 43 in realm-cpp is merged.
- https://jira.mongodb.org/browse/DOCSP-28143
- [React to Changes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28143/sdk/cpp/react-to-changes/)

(DOCSP-28143): C++: Add docs for unregistering a notification token

---

source/sdk/flutter/sync/write-to-synced-realm.txt
source/sdk/swift/sync/write-to-synced-realm.txt

- https://jira.mongodb.org/browse/DOCSP-26779
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/permissions-v2/

Update for Rules v2: remove "Device Sync Permissions"

---

examples/cpp/quick-start.cpp
snooty.toml
source/examples/generated/cpp/quick-start.snippet.sync-session.cpp
source/examples/generated/cpp/quick-start.snippet.sync-state.cpp
source/examples/generated/cpp/quick-start.snippet.wait-for-download.cpp
source/examples/generated/cpp/quick-start.snippet.wait-for-upload.cpp
source/sdk/cpp.txt
source/sdk/cpp/application-services.txt
source/sdk/cpp/sync.txt
source/sdk/cpp/sync/manage-sync-session.txt
source/sdk/dotnet/sync.txt
source/sdk/flutter/sync.txt
source/sdk/react-native/sync-data/overview.txt
source/sdk/swift/application-services.txt

- https://jira.mongodb.org/browse/DOCSP-28151
- [Manage Sync Sessions](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28151/sdk/cpp/sync/manage-sync-session/): New page
- [Sync Data](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28151/sdk/cpp/sync/): New page containing existing content to serve as a container page for the Sync session, now that we have more than a couple of sync-related pages

(DOCSP-28151): Add Sync Session documentation for C++

---

examples/ios/SwiftUICatalog/SwiftUICatalogApp.swift
examples/ios/SwiftUICatalog/Views/FilterData.swift
examples/ios/SwiftUICatalogUITests/SwiftUICatalogUITests.swift
source/examples/generated/swiftui/FilterData.snippet.sort-descriptor.swift
source/sdk/swift/swiftui/react-to-changes.txt

- https://jira.mongodb.org/browse/DOCSP-27433
- [React to Changes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27433/sdk/swift/swiftui/react-to-changes/): New "Sort Observed Results" subsection with example

(DOCSP-27433): SwiftUI: Add sort example for ObservedResults

---

examples/dart/test/sync_log_level_test.dart
source/examples/generated/flutter/sync_log_level_test.snippet.log-level.dart
source/sdk/flutter/sync.txt
source/sdk/flutter/sync/log-level.txt

Flutter set sync client log level
- https://jira.mongodb.org/browse/DOCSP-26501
- [Set Sync Client Log Level (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26501/sdk/flutter/sync/log-level/)

(DOCSP-26501): Flutter set sync client log level

---

examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SchemaTest.kt
source/examples/generated/kotlin/SchemaTest.snippet.declare-properties.kt
source/examples/generated/kotlin/SchemaTest.snippet.persisted-name.kt
source/sdk/kotlin/realm-database/define-realm-object-model.txt
source/sdk/kotlin/realm-database/schemas.txt
source/sdk/kotlin/realm-database/schemas/remap.txt

Add documentation for `@PersistedName` annotation 
- https://jira.mongodb.org/browse/DOCSP-26538
- new page: [Remap a Property - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-26538-persisted/sdk/kotlin/realm-database/schemas/remap/)
- updated page: [Define a Realm Object Model - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-26538-persisted/sdk/kotlin/realm-database/define-realm-object-model/#map-a-property-to-a-different-name)

(DOCSP-26538): Kotlin @PersistedName annotation documentation

---

examples/ios/Examples/Threading.swift
examples/ios/RealmExamples.xcodeproj/xcshareddata/xcschemes/RealmExamplesHostApp.xcscheme
source/examples/generated/code/start/Threading.snippet.pass-across-threads.swift
source/examples/generated/code/start/Threading.snippet.threadsafe-wrapper.swift
source/examples/generated/code/start/Threading.snippet.write-async-extension.swift
source/sdk/swift/crud/threading.txt

- https://jira.mongodb.org/browse/DOCSP-18207
- [Threading](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18207/sdk/swift/crud/threading/): Updates several code examples on the page, but also a minor copy tweak in the Use the Same Realm Across Threads section

(DOCSP-18207): Swift: Remove autorelease blocks in DispatchQueues

---

examples/dart/test/task_project_models_test.dart
examples/dotnet/Examples/RqlSchemaExamples.cs
examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/RQLTest.kt
examples/node/Examples/realm-query-language.js
examples/node/Examples/rql-data-models.js
examples/node/Examples/schemas/rql-data-models.js
source/examples/generated/dotnet/RqlSchemaExamples.snippet.rql-schema-examples.cs
source/examples/generated/flutter/task_project_models_test.snippet.task-project-models.dart
source/examples/generated/kotlin/RQLTest.snippet.rql-schema-example.kt
source/examples/generated/node/rql-data-models.snippet.rql-data-models.js
source/examples/generated/realm-query-language/realm-query-language.snippet.aggregate-operators.js
source/examples/generated/realm-query-language/realm-query-language.snippet.backlinks-aggregate-operators.js
source/examples/generated/realm-query-language/realm-query-language.snippet.backlinks-atCount.js
source/examples/generated/realm-query-language/realm-query-language.snippet.backlinks-atLinks.js
source/examples/generated/realm-query-language/realm-query-language.snippet.backlinks-collection-operators.js
source/examples/generated/realm-query-language/realm-query-language.snippet.backlinks-linkingObjects.js
source/examples/generated/realm-query-language/realm-query-language.snippet.list-comparisons-collection.js
source/examples/generated/realm-query-language/realm-query-language.snippet.list-comparisons-parameterized.js
source/examples/generated/realm-query-language/realm-query-language.snippet.set-operators.js
source/examples/generated/realm-query-language/realm-query-language.snippet.simple-query.js
source/examples/generated/realm-query-language/realm-query-language.snippet.subquery.js
source/realm-query-language.txt

Rename `task` to `item` in RQL examples and generated code samples
- https://jira.mongodb.org/browse/DOCSP-27197
- [Realm Query Language](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-27197-rename-task-rql/realm-query-language/)

(DOCSP-27197): Rename 'task' to 'item' in RQL examples

---

source/sdk/swift/sync/handle-sync-errors.txt

Oops - I just merged #2662 but noticed I had forgotten to save the file that had a new ref target I'm using in that PR. Adding the ref target here to fix impending build errors.

(DOCSP-28642): Add missing ref target

---

examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SchemaTest.kt
source/examples/generated/kotlin/SchemaTest.snippet.add-all-to-realm-set.kt
source/examples/generated/kotlin/SchemaTest.snippet.add-item-to-realm-set.kt
source/examples/generated/kotlin/SchemaTest.snippet.cancel-job.kt
source/examples/generated/kotlin/SchemaTest.snippet.remove-item-from-set.kt
source/examples/generated/kotlin/SchemaTest.snippet.remove-multiple-items-from-set.kt
source/examples/generated/kotlin/SchemaTest.snippet.set-contains-multiple-items.kt
source/examples/generated/kotlin/SchemaTest.snippet.set-contains.kt
source/sdk/kotlin/realm-database/schemas/realm-set.txt

Fix failing RealmSet test and generate corrected Bluehawk examples
- https://jira.mongodb.org/browse/DOCSP-27265
- [RealmSet - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-27265-fix-realmset/sdk/kotlin/realm-database/schemas/realm-set/)

DOCSP-27265): Fix failing RealmSet test

---

source/includes/note-realmreact-version-requirements-for-realmjs.rst
source/sdk/react-native.txt
source/sdk/react-native/bootstrap-with-expo.txt
source/sdk/react-native/install.txt
source/sdk/react-native/use-realm-react.txt

- Refactor 'Use Realm React' page to '@realm/react Reference'.
- Per internal discussion, we are not doing a full overhaul of this page since we are supposed to be getting full generated reference docs for @realm/react sometime soon. The idea is to reorient this page to be more reference-style overview of all the @realm/react members. However, we are not doing a full overhaul here.
- Consistently refer to package as `@realm/react` (not 'Realm React') throughout docs.
- https://jira.mongodb.org/browse/DOCSP-DOCSP-28668
- [@realm/react Reference](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28668/sdk/react-native/use-realm-react) …

(DOCSP-28668): Refactor 'Use Realm React' page to '@realm/react Reference'

---

source/sdk/swift/sync/handle-sync-errors.txt

No Jira ticket - this is a quickie fix based on some docs feedback.
- [Handle Sync Errors](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fix-wrong-api-reference-link/sdk/swift/sync/handle-sync-errors/)

Swift: Fix incorrect API reference link

---

examples/cpp/CMakeLists.txt
examples/cpp/sync-errors.cpp
source/examples/generated/cpp/sync-errors.snippet.create-error-handler.cpp
source/sdk/cpp/sync.txt
source/sdk/cpp/sync/handle-sync-errors.txt

- https://jira.mongodb.org/browse/DOCSP-28198
- [Handle Sync Errors](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28198/sdk/cpp/sync/handle-sync-errors/)

(DOCSP-28198): C++: Add a Handle Sync Errors page

---

source/includes/note-writecopy-local-to-sync.rst
source/includes/note-writecopy-pbs-only.rst
source/includes/note-writecopy-same-type-sync-only.rst
source/sdk/dotnet/realm-files/bundle-a-realm.txt
source/sdk/dotnet/sync/convert-realm.txt
source/sdk/java/examples/bundle-a-realm.txt
source/sdk/kotlin/realm-database/realm-files/open-and-close-a-realm.txt
source/sdk/node/advanced/bundle.txt
source/sdk/node/examples/open-and-close-a-realm.txt
source/sdk/react-native/realm-database/bundle.txt
source/sdk/react-native/sync-data/partition-based-sync.txt
source/sdk/swift/sync/configure-and-open-a-synced-realm.txt

- https://jira.mongodb.org/browse/DOCSP-26866
- [.NET - Bundle a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26866/sdk/dotnet/realm-files/bundle-a-realm/)
- [.NET - Convert Between Non-Synced and Synced Realms](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26866/sdk/dotnet/sync/convert-realm/)
- [Java - Bundle a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26866/sdk/java/examples/bundle-a-realm/)
- [Kotlin - Open & Close a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26866/sdk/kotlin/realm-database/realm-files/open-and-close-a-realm/)
- [Node.js - Open & Close a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-x …

(DOCSP-26866): Clarify supported writeCopy operations for to Flex Sync

---

.github/workflows/ios.yml
examples/ios/Examples/EventLibrary.swift
examples/ios/Examples/MongoDBRemoteAccess.swift
examples/ios/RealmExamples.xcodeproj/project.pbxproj
source/examples/generated/code/start/CustomUserData.snippet.update-custom-user-data.m
source/examples/generated/code/start/MongoDBRemoteAccess.snippet.change-event-delegate.swift
source/examples/generated/code/start/MongoDBRemoteAccess.snippet.watch-collection-async-sequence.swift
source/examples/generated/code/start/MongoDBRemoteAccess.snippet.watch-collection-with-filter.swift
source/examples/generated/code/start/MongoDBRemoteAccess.snippet.watch-collection-with-match.swift
source/examples/generated/code/start/MongoDBRemoteAccess.snippet.watch-collection.swift
source/sdk/swift/app-services/mongodb-remote-access.txt

This PR also adds back the formerly failing Event Library tests, as SDK version 10.37.2 fixes the issue that was causing the failure.
The new async sequence test requires Xcode 14.3, which is not yet available in the GitHub action that runs our iOS CI. So that test won't actually run in CI. Here is the output of running it locally:
```console
Delete all users result: document(["$undefined": Optional(RealmSwift.AnyBSON.bool(true))])
Removing all users...
Test Suite 'Selected tests' started at 2023-03-31 14:23:34.674
Test Suite 'RealmExamples.xctest' started at 2023-03-31 14:23:34.675
Test Suite 'MongoDBRemoteAccessTestCase' started at 2023-03-31 14:23:34.675
Test Case '-[RealmExamples.MongoDBRemoteAccessTestCase testAsyncStreamWatchForChangesInMDBCollection]' started.
Successfully inserted …
```

(DOCSP-28641): Swift: Add Watch section to Query MongoDB page

---

examples/react-native/__tests__/js/CRUD/create-test.jsx
examples/react-native/__tests__/js/CRUD/delete-test.jsx
examples/react-native/__tests__/js/CRUD/read-test.jsx
examples/react-native/__tests__/js/CRUD/update-test.jsx
examples/react-native/__tests__/js/realm-database/schemas/dictionary-test.jsx
examples/react-native/__tests__/js/realm-database/schemas/embedded-objects-test.jsx
examples/react-native/__tests__/js/realm-database/schemas/mixed-test.jsx
examples/react-native/__tests__/js/realm-database/schemas/sets-test.jsx
examples/react-native/__tests__/js/realm-database/schemas/uuid.test.jsx
examples/react-native/__tests__/ts/CRUD/create-test.tsx
examples/react-native/__tests__/ts/CRUD/delete-test.tsx
examples/react-native/__tests__/ts/CRUD/read-test.tsx
examples/react-native/__tests__/ts/CRUD/update-test.tsx
examples/react-native/__tests__/ts/realm-database/schemas/dictionary-test.tsx
examples/react-native/__tests__/ts/realm-database/schemas/embedded-objects-test.tsx
examples/react-native/__tests__/ts/realm-database/schemas/mixed-test.tsx
examples/react-native/__tests__/ts/realm-database/schemas/sets-test.tsx
examples/react-native/__tests__/ts/realm-database/schemas/uuid.test.tsx
source/examples/generated/react-native/js/create-test.snippet.crud-create-object.jsx
source/examples/generated/react-native/js/dictionary-test.snippet.create-object-with-dictionary-value.jsx
source/examples/generated/react-native/js/embedded-objects-test.snippet.create-embedded-object.jsx
source/examples/generated/react-native/js/mixed-test.snippet.create-mixed-object.jsx
source/examples/generated/react-native/js/sets-test.snippet.create-set-object.jsx
source/examples/generated/react-native/js/uuid.test.snippet.create-uuid-object.jsx
source/examples/generated/react-native/ts/create-test.snippet.crud-create-object.tsx
source/examples/generated/react-native/ts/mixed-test.snippet.create-mixed-object.tsx
source/examples/generated/react-native/ts/sets-test.snippet.create-set-object.tsx
source/examples/generated/react-native/ts/update-test.snippet.crud-update-object.tsx
source/examples/generated/react-native/ts/uuid.test.snippet.create-uuid-object.tsx
source/sdk/react-native/realm-database/crud/create.txt

Instead of creating realm objects with the class constructor (`new Cat( realm, {...}`), we should use `realm.create()`.
I've re-factored all the instances of using `new` for object creation that could find. Also fixed a couple tests with async issues.
- https://jira.mongodb.org/browse/DOCSP-28190
- [Throughout the RN SDK docs](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28190-avoid-using-constructor/sdk/react-native/realm-database/crud/create/)

(DOCSP-28190) Refactor to avoid calling model constructor

---

source/sdk/react-native/bootstrap-with-expo.txt

We are going TS only now for the templates.  In that light, we have created `@realm/expo-template` to be a typescript template and will not be updating `expo-template-js` or `expo-template-ts` anymore.

Update Expo Template References

---

examples/dart/test/car.dart
examples/dart/test/car.g.dart
examples/dart/test/data_types_test.dart
examples/dart/test/data_types_test.g.dart
examples/dart/test/react_to_changes_test.dart
examples/dart/test/react_to_changes_test.g.dart
source/examples/generated/flutter/car.snippet.define-model-dart.dart
source/examples/generated/flutter/car.snippet.define-model-flutter.dart
source/examples/generated/flutter/data_types_test.snippet.data-types-example-model.dart
source/examples/generated/flutter/data_types_test.snippet.datetime-model.dart
source/examples/generated/flutter/data_types_test.snippet.datetime-use.dart
source/examples/generated/flutter/data_types_test.snippet.embedded-object-examples.dart
source/examples/generated/flutter/data_types_test.snippet.embedded-object-model.dart
source/examples/generated/flutter/data_types_test.snippet.realmlist-model.dart
source/examples/generated/flutter/data_types_test.snippet.realmlist-use.dart
source/examples/generated/flutter/react_to_changes_test.snippet.sample-data-models.dart
source/examples/generated/flutter/react_to_changes_test.snippet.sample-data-seed.dart

- https://jira.mongodb.org/browse/DOCSP-25840
- [Quick Start](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-25840/sdk/flutter/quick-start/)
- [Data Types](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-25840/sdk/flutter/realm-database/model-data/data-types/)
- [React to Changes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-25840/sdk/flutter/realm-database/react-to-changes/)

(DOCSP-25840): Flutter: Update models to use ObjectId primary keys

---

source/includes/swift-api-sendable-thread-confined-reference.rst
source/sdk/swift/crud/threading.txt
source/sdk/swift/swift-concurrency.txt

- https://jira.mongodb.org/browse/DOCSP-26714
This PR adds a new shared include at the bottom of these two pages:
- [Threading](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26714/sdk/swift/crud/threading/#sendable--non-sendable-and-thread-confined-types)
- [Swift Concurrency](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26714/sdk/swift/swift-concurrency/#sendable--non-sendable-and-thread-confined-types)

(DOCSP-26714): Swift: Add reference table of sendable, non-sendable & thread-confined types

---

source/sdk/kotlin/sync/handle-sync-errors.txt

Related to https://jira.mongodb.org/browse/DOCSP-28993 and https://jira.mongodb.org/browse/DOCSP-25431
Fix ref to Kotlin Client Reset section on Sync Errors page 
- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/no-jira-reset-link/)

Fix ref for kotlin client reset page

---

examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
source/examples/generated/kotlin/AuthenticationTest.snippet.auth-change-listener.kt
source/sdk/kotlin/realm-database/react-to-changes.txt
source/sdk/kotlin/users/authenticate-users.txt

- https://jira.mongodb.org/browse/DOCSP-29572
- [Authenticate Users](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29572/sdk/kotlin/users/authenticate-users/#authentication-changes-as-a-flow): New section w/tested example
- [React to Changes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29572/sdk/kotlin/realm-database/react-to-changes/): Mention auth change listener, link to section on Authenticate Users page

(DOCSP-29572): Kotlin: Authentication change listener as a flow

---

examples/node/Examples/open-and-close-a-realm.js
examples/node/Examples/open-and-close-a-realm.ts
examples/node/package.json
examples/react-native/.gitignore
examples/react-native/__tests__/js/realm-database/configure-realm-path.test.jsx
examples/react-native/__tests__/ts/realm-database/configure-realm-path.test.tsx
examples/react-native/package-lock.json
examples/react-native/package.json
source/examples/generated/node/open-and-close-a-realm.snippet.set-absolute-path.ts
source/examples/generated/react-native/js/configure-realm-path.test.snippet.configure-realm-path.jsx
source/examples/generated/react-native/ts/configure-realm-path.test.snippet.configure-realm-path.tsx
source/sdk/node/sync/configure-and-open-a-synced-realm.txt
source/sdk/react-native/sync-data/configure-a-synced-realm.txt

Note about the tests: currently, the React Native test is only for relative paths. The Node.js test is only for absolute paths. I tried to standardize, but ran into issues and figured it was better to get this content up than toil on the samples for too much longer.
They serve the same purpose: testing that setting an absolute path works.
- https://jira.mongodb.org/browse/DOCSP-28798
- [Node.js - Configure a Synced Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28798/sdk/node/sync/configure-and-open-a-synced-realm/#open-synced-realm-at-specific-path)
- [React Native - Configure a Synced Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28798/sdk/react-native/sync-data/configure-a-synced-realm/#open-synced-realm-at-s …

(DOCSP-28798) Expose App.Configuration.baseFilePath

---

examples/ios/Examples/MongoDBRemoteAccess.swift
source/examples/generated/code/start/MongoDBRemoteAccess.snippet.find-and-sort.swift
source/sdk/swift/app-services/mongodb-remote-access.txt

- https://jira.mongodb.org/browse/DOCSP-29641
- [Query MongoDB](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29641/sdk/swift/app-services/mongodb-remote-access/#find-and-sort-documents): New "Find and Sort Documents" section with Bluehawked code example illustrating the `sorting` API

(DOCSP-29641): Swift: Add new sorting API to Query MongoDB page

---

source/examples/generated/kotlin/SyncTest.snippet.add-a-subscription.kt
source/examples/generated/kotlin/SyncTest.snippet.configure-a-synced-realm.kt
source/examples/generated/kotlin/SyncTest.snippet.define-custom-logger.kt
source/examples/generated/kotlin/SyncTest.snippet.discard.kt
source/examples/generated/kotlin/SyncTest.snippet.fallback.kt
source/examples/generated/kotlin/SyncTest.snippet.open-a-synced-realm.kt
source/examples/generated/kotlin/SyncTest.snippet.recover-discard.kt
source/examples/generated/kotlin/SyncTest.snippet.set-custom-logger-deprecated.kt
source/examples/generated/kotlin/SyncTest.snippet.set-log-level-deprecated.kt
source/examples/generated/kotlin/SyncTest.snippet.set-log-level-realmlog.kt
source/examples/generated/kotlin/SyncTest.snippet.sync-error-handler.kt
source/examples/generated/kotlin/SyncTest.snippet.update-subscriptions-by-query.kt
source/examples/generated/kotlin/SyncTest.snippet.wait-for-subscription-changes.kt

Just regenerating a handful of Bluehawked code examples that Android Studio has linted. No code changes.
- https://jira.mongodb.org/browse/DOCSP-29868
- [Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29868/)

(DOCSP-29868): Kotlin: Lint SyncTest code examples

---

examples/cpp/CMakeLists.txt
examples/cpp/quick-start.cpp
examples/cpp/sync-errors.cpp
examples/cpp/threading.cpp
source/examples/generated/cpp/sync-errors.snippet.create-error-handler.cpp
source/examples/generated/cpp/threading.snippet.scheduler.cpp

Updating the C++ test suite to use versioned releases!
A few minor code changes to fix build errors, but the only visible changes are listed in the Staged Changes section.
- https://jira.mongodb.org/browse/DOCSP-29536
- [Handle Sync Errors](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29536/sdk/cpp/sync/handle-sync-errors/): Remove `error_code()` as it is no longer available 
- [Threading](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29536/sdk/cpp/crud/threading/#schedulers--run-loops-): Overriding `invoke` in a custom scheduler now requires `realm::Function` instead of `std::function`. I also added some minimal code to get past build errors, but that code is not reflected in the published code snippet.
If your PR …

(DOCSP-29536): C++: update test suite to v0.1.1-alpha

---

source/examples/Migrations/LocalMigration/LocalMigration-modify-property-type.js
source/examples/Migrations/LocalMigration/LocalMigration.js
source/sdk/react-native/model-data/change-an-object-model.txt

Also, update erroneous Node samples. These Node samples aren't unit tested. I have a ticket in the Node.js Docs Upgrade epic to convert them to tests. For now, they should at least have the correct syntax.
- [React Native: Change an Object Model](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fix-rn-migration-emphasis/sdk/react-native/model-data/change-an-object-model/#rename-a-property). Rename a property and modify a property type examples.
- [Node: Change an Object Model](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fix-rn-migration-emphasis/sdk/node/model-data/modify-an-object-schema/#rename-a-property). Rename a property and modify a property type examples.
[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING. …

Quick fix: React Native migration sample line emphasis

---

examples/dart/README.md
examples/dart/pubspec.lock
examples/dart/pubspec.yaml
examples/dart/test/task_project_models_test.g.dart
examples/dart/test_sdk_example/pubspec.yaml
source/sdk/flutter/install.txt
source/sdk/flutter/quick-start.txt
source/sdk/flutter/realm-database/model-data/define-realm-object-schema.txt
source/sdk/flutter/test-and-debug.txt

Update Flutter SDK versions in the Flutter tests. Also, replace all instances of `flutter pub run` with `dart run`. The former is being deprecated.
Note: waiting for the next Flutter SDK release to merge.
- https://jira.mongodb.org/browse/DOCSP-30014
Very small change on these pages: `flutter pub run` -> `dart run`.
- [Install](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-30014/sdk/flutter/install/)
- [Quickstart](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-30014/sdk/flutter/quick-start/)
- [Define a Realm Object Schema](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-30014/sdk/flutter/realm-database/model-data/define-realm-object-schema/)
- [Test & …

(DOCSP-30014) Update Flutter SDK versions, replace to-be-deprecated command

---

source/sdk/swift/model-data/supported-types.txt

- https://jira.mongodb.org/browse/DOCSP-30328
- [Supported Types/MutableSet](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-30328/sdk/swift/model-data/supported-types/#mutable-set)

(DOCSP-30328): Swift MutableSet: Add missing supported types

---

source/sdk/kotlin/realm-database/serialization.txt

This PR updates the Kotlin Serializer section with updated information. The ObjectId serializer was needed in an earlier iteration of the API, but it turned out to not be needed for the final release.

Remove Serializer not needed

---

source/sdk/node/realm-files/bundle.txt
source/sdk/node/realm-files/open-and-close-a-realm.txt
source/sdk/node/sync.txt
source/sdk/node/sync/configure-and-open-a-synced-realm.txt
source/sdk/node/sync/partition-based-sync.txt

The Node.js docs have references to Partition-Based Sync sprinkled throughout. We should shift this content to a single page dedicated to Partition-Based Sync. That way, the rest of the docs default to Flexible Sync.
This should be similar in nature to the App Services page for PBS: https://www.mongodb.com/docs/atlas/app-services/reference/partition-based-sync/#overview
This involves:
- Finding PBS content in the Node.js SDK and moving it to a new dedicated PBS page
- May need to write new Flexible Sync test
- Ensure internal links go to new locations
- https://jira.mongodb.org/browse/DOCSP-29870
- [Partition-Based Sync - Node.js SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29870b/sdk/node/sync/partition-based-sync/)
- [Sync Data – Node.js …

(DOCSP-29870b) Relocate Partition-Based Sync Content

---

examples/cpp/beta/local/crud.cpp
examples/ios/Examples/CreateRealmObjects.swift
examples/ios/RealmExamples.xcodeproj/project.pbxproj
examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/CreateTest.kt
examples/node/legacy/Examples/data-types.js
source/examples/generated/code/start/CreateRealmObjects.snippet.percent-encode-disallowed-map-keys.swift
source/examples/generated/cpp/crud.snippet.percent-encode-disallowed-characters.cpp
source/examples/generated/kotlin/CreateTest.snippet.percent-encode-disallowed-characters.kt
source/examples/generated/node/data-types.snippet.percent-encode-disallowed-characters.js
source/includes/map-key-string-limitations.rst
source/sdk/cpp/crud/create.txt
source/sdk/cpp/model-data/supported-types.txt
source/sdk/dotnet/model-data/data-types/dictionaries.txt
source/sdk/kotlin/realm-database/crud/create.txt
source/sdk/kotlin/realm-database/schemas/supported-types.txt
source/sdk/node/model-data/data-types/dictionaries.txt
source/sdk/react-native/model-data/data-types/dictionaries.txt
source/sdk/swift/crud/create.txt
source/sdk/swift/model-data/supported-types.txt

Note for reviewer: the iOS tests are passing locally - the failure appears to be a problem with the CI. It's not actually running the tests - it's failing before the tests start running. I'll look into this in a separate ticket.
Test output from the local run is:
```
Test Suite 'RealmExamples.xctest' passed at 2023-07-14 16:37:33.861.
Executed 270 tests, with 0 failures (0 unexpected) in 160.970 (161.067) seconds
Test Suite 'Selected tests' passed at 2023-07-14 16:37:33.861.
Executed 270 tests, with 0 failures (0 unexpected) in 160.970 (161.067) seconds
```
- https://jira.mongodb.org/browse/DOCSP-31233
- [Realm SDK docs](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31233/) …

(DOCSP-31233): Add info to docs around map key limitations

---

examples/dart/pubspec.lock
examples/dart/pubspec.yaml
examples/dart/test/backlinks_test.g.dart
source/sdk/flutter/realm-database/model-data/relationships.txt

Updated the `graphql` dependency for the Flutter SDK test suite. Also clarified how backlinks work (or, rather, don't) with unmanaged objects.
- https://jira.mongodb.org/browse/DOCSP-31037
- https://jira.mongodb.org/browse/DOCSP-30208
- [Relationships](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31037/sdk/flutter/realm-database/model-data/relationships/#inverse-relationship)

(DOCSP-31037, DOCSP-30208) Address backlinks and unmanaged objects

---

source/sdk/react-native/app-services/connect-to-app-services-app.txt
source/sdk/react-native/app-services/query-mongodb.txt
source/sdk/react-native/bootstrap-with-expo.txt
source/sdk/react-native/crud.txt
source/sdk/react-native/manage-users/authenticate-users.txt
source/sdk/react-native/manage-users/manage-email-password-users.txt
source/sdk/react-native/manage-users/manage-user-api-keys.txt
source/sdk/react-native/manage-users/multi-user-applications.txt
source/sdk/react-native/model-data.txt
source/sdk/react-native/quick-start.txt
source/sdk/react-native/realm-files/configure-a-realm.txt
source/sdk/react-native/sync-data/configure-a-synced-realm.txt
source/sdk/react-native/sync-data/flexible-sync.txt
source/sdk/react-native/sync-data/handle-sync-errors.txt
source/sdk/react-native/sync-data/manage-sync-session.txt
source/sdk/react-native/sync-data/partition-based-sync.txt
source/sdk/react-native/use-realm-react.txt

In the initial `realm/react` work, we decided to use angle brackets to highlight providers. The React Native docs use this convention (inconsistently) when referring the React Native components.
After thinking it over, the convention is easily conflated with our style guide's placeholder variable convention, which also uses angle brackets.
We should remove all instances of angle brackets for providers for two reasons:
Prevent confusion with placholder variables
Visually clean up docs flow
- https://jira.mongodb.org/browse/DOCSP-29773
- [Lots of Pages – all in React Native SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29773/) …

(DOCSP-29773) Remove angle brackets from provider references

---

source/sdk/kotlin/sync/log-level.txt

No Jira - fixing version numbers throughout [Set the Client Log Level](https://www.mongodb.com/docs/realm/sdk/kotlin/sync/log-level/#realm-kotlin-sdk-v10.8.0-and-later) page (should be `1.x.x` not `10.x.x`)
- [Set the Client Log Level - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/no-jira-version-fix/sdk/kotlin/sync/log-level/)

Fix version number on log level page

---

examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SyncTest.kt
source/examples/generated/kotlin/SyncTest.snippet.add-a-named-subscription.kt
source/examples/generated/kotlin/SyncTest.snippet.add-a-subscription.kt
source/examples/generated/kotlin/SyncTest.snippet.flexible-sync-models.kt
source/examples/generated/kotlin/SyncTest.snippet.initialize-subscribe-query-realm-app-rerun.kt
source/examples/generated/kotlin/SyncTest.snippet.initialize-subscribe-query-realm-app.kt
source/examples/generated/kotlin/SyncTest.snippet.open-flex-sync-app.kt
source/examples/generated/kotlin/SyncTest.snippet.remove-all-subscriptions-to-an-object-type.kt
source/examples/generated/kotlin/SyncTest.snippet.remove-all-subscriptions.kt
source/examples/generated/kotlin/SyncTest.snippet.remove-all-unnamed-subscriptions.kt
source/examples/generated/kotlin/SyncTest.snippet.remove-single-subscription.kt
source/examples/generated/kotlin/SyncTest.snippet.subscribe-named-query.kt
source/examples/generated/kotlin/SyncTest.snippet.subscribe-unnamed-query.kt
source/examples/generated/kotlin/SyncTest.snippet.subscribe-wait-for-sync.kt
source/examples/generated/kotlin/SyncTest.snippet.update-query-by-name.kt
source/examples/generated/kotlin/SyncTest.snippet.update-subscriptions-by-name.kt
source/examples/generated/kotlin/SyncTest.snippet.update-subscriptions-by-query.kt
source/examples/generated/kotlin/SyncTest.snippet.wait-for-subscription-changes.kt
source/sdk/kotlin/sync/open-a-synced-realm.txt
source/sdk/kotlin/sync/subscribe.txt

- Add [`.subscribe()`](https://www.mongodb.com/docs/realm/sdk/kotlin/sync/subscribe/) info to existing [Manage Subscriptions](https://www.mongodb.com/docs/realm/sdk/kotlin/sync/subscribe/) page
- Update existing examples to use new `Team` and `Task` object models for consistency
- https://jira.mongodb.org/browse/DOCSP-30216
- [Manage Sync Subscriptions - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-30216-flex-sync/sdk/kotlin/sync/subscribe/)

DOCSP-30216: Document Kotlin Subscription API 

---

source/sdk/node/sync.txt
source/sdk/node/sync/flexible-sync.txt
source/sdk/node/sync/manage-sync-session.txt
source/sdk/node/sync/partition-based-sync.txt

- https://jira.mongodb.org/browse/DOCSP-31532
- [Sync Data](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31532/sdk/node/sync/): Remove PBS, add tip about PBS being an older sync mode and recommending new apps use Flexible Sync 
- [Partition-Based Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31532/sdk/node/sync/partition-based-sync/): Add Migration info to page, move Progress Notification docs from Manage a Sync Session to this page since they only work with PBS right now
- [Manage a Sync Session](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31532/sdk/node/sync/manage-sync-session/): Remove Progress Notification documentation from the page since it only works with PBS
If your PR …

(DOCSP-31532): Node.js migrate PBS to FS updates

---

source/sdk/react-native/sync-data.txt
source/sdk/react-native/sync-data/manage-sync-session.txt
source/sdk/react-native/sync-data/partition-based-sync.txt

- https://jira.mongodb.org/browse/DOCSP-31533
- [Sync Data](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31533/sdk/react-native/sync-data/): Remove PBS, add tip about PBS being an older sync mode and recommending new apps use Flexible Sync
- [Partition-Based Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31533/sdk/react-native/sync-data/partition-based-sync/): Add Migration info to page, move Progress Notification docs from Manage a Sync Session to this page since they only work with PBS right now
- [Manage a Sync Session](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31533/sdk/react-native/sync-data/manage-sync-session/): Remove Progress Notification documentation from the page since …

(DOCSP-31533): RN migrate PBS to FS updates

---

source/sdk/kotlin/sync.txt
source/sdk/kotlin/sync/open-a-synced-realm.txt
source/sdk/kotlin/sync/partition-based-sync.txt
source/sdk/kotlin/sync/write-to-synced-realm.txt

- https://jira.mongodb.org/browse/DOCSP-31530
- [Sync Device Data](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31530/sdk/kotlin/sync/): Remove PBS info
- [Partition-Based Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31530/sdk/kotlin/sync/partition-based-sync/): New page with PBS info
- [Configure & Open a Synced Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31530/sdk/kotlin/sync/open-a-synced-realm/): Remove PBS info to new PBS page
- [Write Data to a Synced Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31530/sdk/kotlin/sync/write-to-synced-realm/): Move "Group Write" info to the recently-added page where it seems more relevant
If your …

(DOCSP-31530): Kotlin SDK migrate PBS to FS updates

---

config/redirects
source/sdk/node/sync/manage-sync-session.txt
source/sdk/node/sync/partition-based-sync.txt
source/sdk/react-native/sync-data/manage-sync-session.txt
source/sdk/react-native/sync-data/partition-based-sync.txt
source/sdk/swift/sync/partition-based-sync.txt
source/sdk/swift/sync/sync-session.txt

I moved the progress notification documentation to the new PBS page as part of the PBS to FS migration work, but upload progress works for both FS and PBS - the only thing that doesn't work properly in FS is download progress. Moving the content back onto the relevant pages.
- [Node.js - Manage a Sync Session](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/revert-sync-progress-changes/sdk/node/sync/manage-sync-session/): Re-add progress notification info
- [Node.js - PBS](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/revert-sync-progress-changes/sdk/node/sync/partition-based-sync/): Remove progress notification info
- [React Native - Manage a Sync Session](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/revert-sy …

Revert Sync progress change updates

---

source/sdk/kotlin.txt
source/sdk/kotlin/logging.txt
source/sdk/kotlin/sync/log-level.txt

- Move v1.8.0 logging API content from Sync logging page to a new Logging page. 
- Note Sync logging page as deprecated 
- https://jira.mongodb.org/browse/DOCSP-31396
- [Logging - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-31396-logging/sdk/kotlin/logging/#std-label-kotlin-logging) - new page
- [Set the Client Log Level - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-31396-logging/sdk/kotlin/sync/log-level/) - updated page

DOCSP-31396: Kotlin - Break Logging docs out from Sync logger

---

examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SchemaTest.kt
source/examples/generated/kotlin/SchemaTest.snippet.inverse-relationship-user.kt
source/sdk/kotlin/realm-database/schemas/relationships.txt

Correct example that shows a null list of realm objects. Lists of ``RealmObjects`` cannot be `null`; should initialize with an empty list instead. 
- https://jira.mongodb.org/browse/DOCSP-31611
- [Relationships - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-31611/sdk/kotlin/realm-database/schemas/relationships/#inverse-relationships)

DOCSP-31611: Update inverse relationship example to initialize with empty list

---

examples/java/sync/app/src/androidTest/java/com/mongodb/realm/examples/java/FlexibleSyncTest.java
examples/java/sync/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/FlexibleSyncTest.kt
examples/java/sync/build.gradle
source/examples/generated/java/sync/FlexibleSyncTest.snippet.fs-allow-queries-on-ui-thread.java
source/examples/generated/java/sync/FlexibleSyncTest.snippet.fs-allow-queries-on-ui-thread.kt
source/includes/java-synchronous-reads-writes-ui-thread-fs.rst
source/sdk/java/sync.txt
source/sdk/java/sync/configure-and-open-a-synced-realm.txt
source/sdk/java/sync/partition-based-sync.txt

- https://jira.mongodb.org/browse/DOCSP-31727
- [Sync Data](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31727/sdk/java/sync/): Remove PBS mentions
- [Partition-Based Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31727/sdk/java/sync/partition-based-sync/): New page with moved PBS info and PBS to FS migration info
- [Configure & Open a Synced Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31727/sdk/java/sync/configure-and-open-a-synced-realm/): Remove PBS info, update the "Synchronous Reads & Writes on the UI Thread" `Important` callout to show FS code examples …

(DOCSP-31727): Java SDK Migrate PBS to FS Updates

---

examples/dotnet/Examples/ClientResetExamples.cs
examples/dotnet/Examples/FlexibleSyncExamples.cs
examples/dotnet/Examples/OpenARealmExamples.cs
source/examples/generated/dotnet-flexible-sync/FlexibleSyncExamples.snippet.open-a-flexible-synced-realm.cs
source/examples/generated/dotnet-flexible-sync/FlexibleSyncExamples.snippet.open-fs-realm-offline.cs
source/examples/generated/dotnet-flexible-sync/FlexibleSyncExamples.snippet.open-fs-realm.cs
source/examples/generated/dotnet/OpenARealmExamples.snippet.open-synced-realm-synchronously.cs
source/examples/generated/dotnet/OpenARealmExamples.snippet.open-synced-realm.cs
source/sdk/dotnet/sync.txt
source/sdk/dotnet/sync/configure-and-open-a-synced-realm.txt
source/sdk/dotnet/sync/flexible-sync.txt
source/sdk/dotnet/sync/partition-based-sync.txt
source/sdk/dotnet/sync/sync-progress.txt

- https://jira.mongodb.org/browse/DOCSP-31531
- [Sync Data](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31531/sdk/dotnet/sync/): Remove PBS info
- [Configure & Open a Synced Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31531/sdk/dotnet/sync/configure-and-open-a-synced-realm/): Remove PBS info to new PBS page. Add new Flexible Sync code examples for opening a realm. The other examples on this page should also be updated to show FS instead of PBS, but aren't necessarily a blocker for this PR.
- [Partition-Based Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-31531/sdk/dotnet/sync/partition-based-sync/): New page with moved PBS content and new migration info
If your PR modifies …

(DOCSP-31531): NET SDK Migrate PBS to FS updates

---

examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/ManageSyncSession.kt
source/examples/generated/kotlin/ManageSyncSession.snippet.get-network-connection.kt
source/examples/generated/kotlin/ManageSyncSession.snippet.monitor-network-connection.kt
source/examples/generated/kotlin/ManageSyncSession.snippet.monitor-progress.kt
source/examples/generated/kotlin/ManageSyncSession.snippet.pause-resume-sync.kt
source/examples/generated/kotlin/ManageSyncSession.snippet.wait-upload-download.kt
source/examples/generated/kotlin/RealmModels.snippet.landing-page-model.kt
source/sdk/kotlin/sync.txt
source/sdk/kotlin/sync/manage-sync-session.txt
source/sdk/kotlin/sync/partition-based-sync.txt

Add new Manage Sync Session page for Kotlin (progress listener added in https://github.com/realm/realm-kotlin/pull/1118)
> NOTE: Kotlin SDK doesn't currently support progress listener for Flexible Sync; only supported for PBS
- https://jira.mongodb.org/browse/DOCSP-30337
- [Manage Sync Session](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-30337-manage-sync-sessions/sdk/kotlin/sync/manage-sync-session/) - new page
- [Partition-Based Sync](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-30337-manage-sync-sessions/sdk/kotlin/sync/partition-based-sync/#check-upload---download-progress-for-a-sync-session) - updated page
pages. Check if completed or …

DOCSP-30337: Add Manage Sync Session - Kotlin SDK page

---

source/sdk/kotlin/install.txt

Update Kotlin Install page to remove duplicate subheadings in tabbed procedure
> NOTE: Confirmed the supported/unsupported environments list is still accurate.
- https://jira.mongodb.org/browse/DOCSP-30338
- [Install - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/) - updated page

DOCSP-30338: Remove dupe headings on Kotlin Install page

---

examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/RealmTest.kt
source/examples/generated/kotlin/AuthenticationTest.snippet.get-user-metadata.kt
source/sdk/dotnet/manage-users/user-metadata.txt
source/sdk/kotlin/users.txt
source/sdk/kotlin/users/user-metadata.txt
source/sdk/swift/users/user-metadata.txt
source/sdk/swift/work-with-users.txt

Add new User Metadata - Kotlin SDK page
- https://jira.mongodb.org/browse/DOCSP-30334
- [User Metadata](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-30334-user-metadata/sdk/kotlin/users/user-metadata/) - new page
- [Manage Users](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-30334-user-metadata/sdk/kotlin/users/) - updated page

DOCSP-30334: Add Kotlin User Metadata page

---

source/sdk/kotlin/realm-database/write-transactions.txt

Add section describing managed vs. unmanaged objects to existing [Read and Write Data](https://www.mongodb.com/docs/realm/sdk/kotlin/realm-database/write-transactions/) page
- https://jira.mongodb.org/browse/DOCSP-30342
- [Read & Write Data](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-30342-manage-section/sdk/kotlin/realm-database/write-transactions/) - updated page

DOCSP-30342: Update Read & Write Data page with info on managed and unmanaged objects

---

source/includes/map-to-bson-type.rst
source/sdk/cpp/model-data/supported-types.txt
source/sdk/dotnet/model-data/data-types/field-types.txt
source/sdk/flutter/realm-database/model-data/data-types.txt
source/sdk/kotlin/realm-database/schemas/supported-types.txt
source/sdk/node/model-data/data-types/field-types.txt
source/sdk/react-native/model-data/data-types/property-types.txt
source/sdk/swift/model-data/supported-types.txt

Bug Bash ticket: Point users to where they can see property type > BSON type mappings 
- https://jira.mongodb.org/browse/DOCSP-28410
- [C++](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-28410-data-model-mapping/sdk/cpp/model-data/supported-types/#property-cheat-sheet)
- [Flutter](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-28410-data-model-mapping/sdk/flutter/realm-database/model-data/data-types/)
- [Kotlin](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-28410-data-model-mapping/sdk/kotlin/realm-database/schemas/supported-types/)
- [.NET](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-28410-data-model-mapping/sdk/dotnet/model-data/data-types/field-types/)
- …

DOCSP-28410: Add link from SDK Model pages to App Services schema mapping page

---

examples/node/v12/__tests__/define-a-realm-object-schema.test.js
examples/node/v12/__tests__/define-a-realm-object-schema.test.ts
examples/node/v12/package-lock.json
examples/node/v12/package.json
source/examples/generated/node/v12/define-a-realm-object-schema.test.snippet.remap-class-name.js
source/examples/generated/node/v12/define-a-realm-object-schema.test.snippet.remap-class-name.ts
source/sdk/flutter/realm-database/model-data/define-realm-object-schema.txt
source/sdk/flutter/realm-database/model-data/property-annotations.txt
source/sdk/node/model-data/define-a-realm-object-model.txt

The Jira ticket also requests adding this in Java and React Native, which I'm not doing in this ticket. We're generally not updating the Java docs except for bugs, so that's a won't do. With the v12 release it probably makes sense to do the React Native stuff in v12, so I'll split that to a separate ticket for later. This functionality is not available in Swift, and already has examples in Flutter - I've just cross-posted them for this ticket.
- https://jira.mongodb.org/browse/DOCSP-29619
- [Node.js - Define an Object Model](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29619/sdk/node/model-data/define-a-realm-object-model/#map-a-property-or-class-to-a-different-name)
- [Flutter - Define an Object …

(DOCSP-29619): Map a Class to a Different Persisted Name

---

source/sdk/node/quick-start.txt

Bug bash: Link should point to [BSON package](https://www.mongodb.com/docs/manual/reference/method/ObjectId/)
- https://jira.mongodb.org/browse/DOCSP-28146
- [Quick Start - Node.js SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-28146-js-objectid/sdk/node/quick-start/#define-your-object-model)

DOCSP-28146: Fix incorrect ObjectId link in Node Quick Start

---

source/sdk/kotlin/realm-database/crud/read.txt
source/sdk/kotlin/realm-database/realm-files/compact-realm.txt
source/sdk/kotlin/realm-database/schemas/property-annotations.txt

https://github.com/mongodb/snooty-parser/pull/506 will update `kotlin-sdk` role to point to the base library. This replaces any current instances of the `kotlin-sdk` role with source constants, so links don't break after that PR merges. 
[DOCSP-32519](https://jira.mongodb.org/browse/DOCSP-32519) will replace all source constants with the newly defined kotlin roles after the merge 🎉 
- https://jira.mongodb.org/browse/DOCSP-32246
- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-32246-kotlin-sdk-role/

DOCSP-32246: Remove instances of `kotlin-sdk` role

---

examples/ios/Examples/MongoDBRemoteAccess.swift
examples/ios/Examples/MongoDBRemoteAccessAggregate.swift
source/examples/generated/code/start/MongoDBRemoteAccess.snippet.async-await-insert.swift
source/examples/generated/code/start/MongoDBRemoteAccess.snippet.coffee-drink-model.swift
source/examples/generated/code/start/MongoDBRemoteAccess.snippet.delete-one.swift
source/examples/generated/code/start/MongoDBRemoteAccess.snippet.find-many.swift
source/examples/generated/code/start/MongoDBRemoteAccess.snippet.find-one.swift
source/examples/generated/code/start/MongoDBRemoteAccess.snippet.insert-many.swift
source/examples/generated/code/start/MongoDBRemoteAccess.snippet.insert-one.swift
source/examples/generated/code/start/MongoDBRemoteAccess.snippet.insert-sample-data.swift.rst
source/examples/generated/code/start/MongoDBRemoteAccess.snippet.update-many.swift
source/examples/generated/code/start/MongoDBRemoteAccess.snippet.update-one.swift
source/examples/generated/code/start/MongoDBRemoteAccess.snippet.upsert.swift
source/examples/generated/code/start/MongoDBRemoteAccess.snippet.watch-collection-async-sequence.swift
source/examples/generated/code/start/MongoDBRemoteAccess.snippet.watch-collection-with-filter.swift
source/examples/generated/code/start/MongoDBRemoteAccess.snippet.watch-collection-with-match.swift
source/examples/generated/code/start/MongoDBRemoteAccess.snippet.watch-collection.swift
source/examples/generated/code/start/MongoDBRemoteAccessAggregate.snippet.aggregation-add-fields.swift
source/examples/generated/code/start/MongoDBRemoteAccessAggregate.snippet.aggregation-group.swift
source/examples/generated/code/start/MongoDBRemoteAccessAggregate.snippet.aggregation-match.swift
source/examples/generated/code/start/MongoDBRemoteAccessAggregate.snippet.aggregation-project.swift
source/examples/generated/code/start/MongoDBRemoteAccessAggregate.snippet.store-document-example.swift
source/examples/generated/code/start/MongoDBRemoteAccessAggregate.snippet.unwind-test-document.swift
source/sdk/swift/app-services/mongodb-remote-access.txt

The linked Jira ticket requests fixing some failing tests, but we've got other tickets to remove PBS examples from the docs. Since I'm touching the page anyway, I've switched the PBS examples. While I'm in here, I've added IO code blocks which were not available when this page was created.
- https://jira.mongodb.org/browse/DOCSP-32426
- [Query MongoDB](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-32426/sdk/swift/app-services/mongodb-remote-access/)

(DOCSP-32426): Swift: Query MongoDB Test Fixes and Remove PBS from Examples

---

source/facets.toml
source/sdk/dotnet/facets.toml
source/sdk/flutter/facets.toml
source/sdk/java/facets.toml
source/sdk/kotlin/facets.toml
source/sdk/node/facets.toml
source/sdk/react-native/facets.toml
source/sdk/swift/facets.toml
source/web/facets.toml

Reverts mongodb/docs-realm#2982
Currently, Snooty is unable to build docs-realm with an error that platform theorizes is related to this file: https://github.com/mongodb/docs-realm/pull/2982/files#diff-59b2cb232ab8f22d89bc70df42f016b1489393983e4791fa811cb0f60534e23a
Reverting this to enable docs-realm to build again - we can try again with a fresh run once the script has been tweaked.

Revert "DOCSP-32483 programmatic tagging script for realm repo"

---

source/sdk/node/model-data/data-types/collections.txt
source/sdk/node/model-data/data-types/dictionaries.txt
source/sdk/node/model-data/data-types/field-types.txt
source/sdk/node/model-data/data-types/mixed.txt

- https://jira.mongodb.org/browse/DOCSP-32529
- [Collections](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32529/sdk/node/model-data/data-types/collections/)
- [Dictionaries](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32529/sdk/node/model-data/data-types/dictionaries/)
- [Field Types](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32529/sdk/node/model-data/data-types/field-types/)
- [Mixed](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32529/sdk/node/model-data/data-types/mixed/)

(DOCSP-32529): Node.js Data Types: Update JS API reference links for v12

---

source/sdk/node/app-services/call-a-function.txt
source/sdk/node/app-services/query-mongodb.txt

The linked Jira ticket calls for all three App Services pages to be updated, but I did the Connect to an App Services App page as part of another PR.
- https://jira.mongodb.org/browse/DOCSP-32533
- [Call a Function](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32533/sdk/node/app-services/call-a-function/)
- [Query MongoDB](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32533/sdk/node/app-services/query-mongodb/)

(DOCSP-32533): Update JS API reference links for v12

---

examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/ReadTest.kt
source/examples/generated/kotlin/ReadTest.snippet.kotlin-fts-property.kt
source/examples/generated/kotlin/ReadTest.snippet.kotlin-fts-query.kt
source/sdk/kotlin/realm-database/crud/read.txt
source/sdk/kotlin/realm-database/schemas/property-annotations.txt

Update FTS documentation to include support for prefix searches (requires Kotlin v1.11.0 and later)
- https://jira.mongodb.org/browse/DOCSP-32919
- [Read - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-32919-fts-prefix/sdk/kotlin/realm-database/crud/read/#filter-with-full-text-search) - updated section
- [Property Annotations](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-32919-fts-prefix/sdk/kotlin/realm-database/schemas/property-annotations/#full-text-search-indexes) - updated section

DOCSP-32919: Update Kotlin FTS doc with prefix search

---

config/redirects
examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/OpenARealmTest.kt
snooty.toml
source/examples/generated/kotlin/OpenARealmTest.snippet.delete-realm-if-migration-needed.kt
source/examples/generated/kotlin/OpenARealmTest.snippet.find-realm-path.kt
source/examples/generated/kotlin/OpenARealmTest.snippet.in-memory-to-local-realm.kt
source/examples/generated/kotlin/OpenARealmTest.snippet.initial-data-callback.kt
source/examples/generated/kotlin/OpenARealmTest.snippet.open-a-default-realm.kt
source/examples/generated/kotlin/OpenARealmTest.snippet.open-a-realm.kt
source/examples/generated/kotlin/OpenARealmTest.snippet.open-an-in-memory-realm.kt
source/examples/generated/kotlin/OpenARealmTest.snippet.open-realm-object-schemas.kt
source/examples/generated/kotlin/OpenARealmTest.snippet.sync-to-local-realm.kt
source/examples/generated/kotlin/OpenARealmTest.snippet.unencrypted-to-encrypted-realm.kt
source/sdk/kotlin/realm-database.txt
source/sdk/kotlin/realm-database/open-and-close-a-realm.txt
source/sdk/kotlin/realm-database/realm-files.txt
source/sdk/kotlin/realm-database/realm-files/delete-a-realm.txt
source/sdk/kotlin/realm-database/realm-files/open-and-close-a-realm.txt

- Convert existing [Manage Realm Files](https://www.mongodb.com/docs/realm/sdk/kotlin/realm-database/realm-files/) page to container
- Move relevant info to existing [Configure & Open a Realm](https://www.mongodb.com/docs/realm/sdk/kotlin/realm-database/realm-files/open-and-close-a-realm/) page
- Update examples 
- Move Configure & Open a Realm page out of Manage Realm Files container 
- https://jira.mongodb.org/browse/DOCSP-30339
- [Configure & Open a Realm - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-30339-manage-realm-files/sdk/kotlin/realm-database/realm-files/open-and-close-a-realm/) …

DOCSP-30339: Convert Manage Realm Files landing page

---

examples/cpp/beta/local/CMakeLists.txt
examples/cpp/beta/local/crud.cpp
source/examples/generated/cpp/crud.snippet.beta-realm-specify-classes.cpp
source/examples/generated/cpp/crud.snippet.beta-update-an-object.cpp
source/examples/generated/cpp/crud.snippet.beta-update-embedded-object.cpp
source/sdk/cpp/realm-files/configure-and-open-a-realm.txt

In updating to the current version of the C++ SDK, I also had to change `value()` to `detach()` as it has been renamed.
Prior to merging:
- https://jira.mongodb.org/browse/DOCSP-32291
- [Configure & Open a Realm](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32291/sdk/cpp/realm-files/configure-and-open-a-realm/#provide-a-subset-of-classes-to-a-realm): New "Provide a Subset of Classes to a Realm" section

(DOCSP-32291): C++: Open a realm overload now takes a db::config

---

examples/cpp/beta/local/CMakeLists.txt
examples/cpp/beta/local/supported-types.cpp
source/examples/generated/cpp/supported-types.snippet.beta-optional-decimal128.cpp
source/examples/generated/cpp/supported-types.snippet.beta-required-decimal128.cpp
source/sdk/cpp/model-data/supported-types.txt

This is currently blocked pending the upcoming release of the C++ SDK. DO NOT MERGE until that release.
Before merging:
- https://jira.mongodb.org/browse/DOCSP-29738
- [Supported Types](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29738/sdk/cpp/model-data/supported-types/)

(DOCSP-29738): C++: Add Decimal128 to supported types

---

examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/ManageSyncSession.kt
examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/RealmTest.kt
source/examples/generated/kotlin/ManageSyncSession.snippet.app-sync-reconnect.kt
source/examples/generated/kotlin/ManageSyncSession.snippet.open-sync-session.kt
source/sdk/kotlin/sync/manage-sync-session.txt

Add `App.Sync.reconnect()` method to existing page
> NOTE: the related `app.sync.waitForSessionsToTerminate()` method is purposefully omitted until it's confirmed to be working as expected and ready to be documented 
- https://jira.mongodb.org/browse/DOCSP-32198
- [Manage a Sync Session - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-32918-sync-reconnect/sdk/kotlin/sync/manage-sync-session/)

DOCSP-32918: Document .reconnect() for Kotlin SDK

---

examples/dart/pubspec.lock
examples/dart/pubspec.yaml
examples/dart/test/data_ingest.test.dart
examples/dart/test/data_ingest.test.g.dart
examples/dart/test_sdk_example/pubspec.lock
examples/dart/test_sdk_example/pubspec.yaml
source/examples/generated/flutter/data_ingest.test.snippet.asymmetric-sync-object.dart
source/examples/generated/flutter/data_ingest.test.snippet.write-asymmetric-object.dart
source/sdk/flutter/realm-database/model-data/define-realm-object-schema.txt
source/sdk/flutter/sync.txt
source/sdk/flutter/sync/stream-data-to-atlas.txt

This PR adds docs and tests for Data Ingest. Note that the Flutter SDK doesn't have a mongoClient yet. It's not really feasible to test that asymmetric objects make it to the backend without the mongoClient. However, we can test that the write occurs and the object is deleted after it's synced.
- https://jira.mongodb.org/browse/DOCSP-33149
- [Stream Data to Atlas](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-33149/sdk/flutter/sync/stream-data-to-atlas/). New page.
- [Define a Realm Object Schema](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-33149/sdk/flutter/realm-database/model-data/define-realm-object-schema/#define-an-asymmetric-object). New section for defining an asymmetric object. …

(DOCSP-33149) Add Data Ingest docs for Flutter

---

source/example-projects.txt
source/index.txt
source/sdk.txt
source/sdk/java.txt
source/sdk/kotlin.txt
source/sdk/kotlin/install.txt
source/sdk/kotlin/quick-start.txt
source/sdk/kotlin/realm-database/frozen-arch.txt
source/sdk/kotlin/users/authenticate-users.txt

Per [JetBrains](https://blog.jetbrains.com/kotlin/2023/07/update-on-the-name-of-kotlin-multiplatform/): `Kotlin Multiplatform Mobile (KMM)` is deprecated and should be replaced with From now on, `Kotlin Multiplatform (KMP)`
- https://jira.mongodb.org/browse/DOCSP-33430
https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-33430-KMM-to-KMP/sdk/kotlin/install/

DOCSP-33430: Rename KMM refs to KMP

---

examples/dotnet/Examples/Compact.cs
source/examples/generated/dotnet/Compact.snippet.config-compact.cs
source/sdk/dotnet/realm-files/compact-realm.txt
source/sdk/node/realm-files/compact-realm.txt
source/sdk/react-native/realm-files/compact-realm.txt

Made sure file compacted when used bytes was _less than_ 50% of total bytes in examples for the Node.js, .NET, and React Native SDKs.
- https://jira.mongodb.org/browse/DOCSP-33313
- [Reduce Realm File Size - .NET](https://preview-mongodblindseymoore.gatsbyjs.io/realm/DOCSP-33313/sdk/dotnet/realm-files/compact-realm/#realm-configuration-file)
- [Reduce Realm File Size - Node.js](https://preview-mongodblindseymoore.gatsbyjs.io/realm/DOCSP-33313/sdk/node/realm-files/compact-realm/#tips-for-manually-compacting-a-realm)
- [Reduce Realm File Size - React Native](https://preview-mongodblindseymoore.gatsbyjs.io/realm/DOCSP-33313/sdk/react-native/realm-files/compact-realm/) …

DOCSP-33313 Manual Compaction Example Fix

---

source/sdk/swift/model-data/object-models.txt
source/sdk/swift/sync/stream-data-to-atlas.txt

- https://jira.mongodb.org/browse/DOCSP-33260
- [Define a Realm Object Model](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-33260/sdk/swift/model-data/object-models/#define-an-asymmetric-object)
- [Stream Data to Atlas](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-33260/sdk/swift/sync/stream-data-to-atlas/#sync-data-unidirectionally-from-a-client-application)

(DOCSP-33260): Swift: Asymmetric objects can now link to non-embedded types

---

examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/DataTypesTest.kt
examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/DeleteTest.kt
source/examples/generated/kotlin/DataTypesTest.snippet.update-embedded-object.kt
source/examples/generated/kotlin/DeleteTest.snippet.chain-delete-realm-list.kt
source/examples/generated/kotlin/DeleteTest.snippet.clear-set.kt
source/examples/generated/kotlin/DeleteTest.snippet.delete-all-realm-object-types.kt
source/examples/generated/kotlin/DeleteTest.snippet.delete-all-realm-objects.kt
source/examples/generated/kotlin/DeleteTest.snippet.delete-embedded-object-through-parent.kt
source/examples/generated/kotlin/DeleteTest.snippet.delete-embedded-object.kt
source/examples/generated/kotlin/DeleteTest.snippet.delete-multiple-realm-objects.kt
source/examples/generated/kotlin/DeleteTest.snippet.delete-one-realm-object.kt
source/examples/generated/kotlin/DeleteTest.snippet.delete-realm-dictionary.kt
source/examples/generated/kotlin/DeleteTest.snippet.delete-realm-object-with-related-objects.kt
source/examples/generated/kotlin/DeleteTest.snippet.delete-realmany-property.kt
source/examples/generated/kotlin/DeleteTest.snippet.fetch-latest-to-delete-object.kt
source/examples/generated/kotlin/DeleteTest.snippet.list-clear.kt
source/examples/generated/kotlin/DeleteTest.snippet.remove-item-from-set.kt
source/examples/generated/kotlin/DeleteTest.snippet.remove-items-from-list.kt
source/sdk/kotlin/realm-database/crud/delete.txt
source/sdk/kotlin/realm-database/frozen-arch.txt

Update existing [Delete](https://www.mongodb.com/docs/realm/sdk/kotlin/realm-database/crud/delete/) page with missing content and updated code examples 
- https://jira.mongodb.org/browse/DOCSP-30346
- [Delete Realm Objects - Kotlin SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-30346-delete-page/sdk/kotlin/realm-database/crud/delete/)

DOCSP-30346: Update Kotlin Delete page

---

source/includes/note-java-maintenance-mode.rst
source/sdk/java.txt
source/sdk/java/install.txt

Indicate to users that the Java SDK is in a best-effort maintenance mode and no longer receiving any new features.
And, per [Slack convo](https://mongodb.slack.com/archives/CL9JSLTGE/p1698666451443479), confirm you can use other SDKs in a Java project.
- https://jira.mongodb.org/browse/DOCSP-33261
- [Java SDK landing](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-33261-java-sdk-guidance/sdk/java/)
- [Install - Java SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-33261-java-sdk-guidance/sdk/java/install/)

DOCS-33261: Add note that Java SDK is in Maintenance Mode

---

examples/react-native/legacy/__tests__/js/quickstart/quickstart-sync.test.jsx
examples/react-native/legacy/__tests__/js/realm-database/configure-realm-sync-offline.test.jsx
examples/react-native/legacy/__tests__/js/realm-database/configure-realm-sync-timeout.test.jsx
examples/react-native/legacy/__tests__/js/sync/data-ingest.test.jsx
examples/react-native/legacy/__tests__/ts/quickstart/quickstart-sync.test.tsx
examples/react-native/legacy/__tests__/ts/realm-database/configure-realm-sync-offline.test.tsx
examples/react-native/legacy/__tests__/ts/realm-database/configure-realm-sync-timeout.test.tsx
examples/react-native/legacy/__tests__/ts/realm-database/configure-realm-sync.test.tsx
examples/react-native/legacy/__tests__/ts/sync/data-ingest.test.tsx
source/examples/generated/react-native/js/data-ingest.test.snippet.open-realm.jsx
source/examples/generated/react-native/js/quickstart-sync.test.snippet.quickstart-setup.jsx
source/examples/generated/react-native/ts/configure-realm-sync-offline.test.snippet.offline-config.tsx
source/examples/generated/react-native/ts/data-ingest.test.snippet.open-realm.tsx
source/examples/generated/react-native/ts/quickstart-sync.test.snippet.quickstart-setup.tsx

Several of our examples had a bad error handler construction. This PR removes that construction. In all cases, the error handling bit wasn't necessary.
[Multiple places in the React Native docs](https://preview-mongodbkrollinsmdb.gatsbyjs.io/realm/remove-bad-on-error/sdk/react-native/)

React Native: Remove bad onError configuration

---

examples/react-native/v12/TestApp/babel.config.cjs
examples/react-native/v12/TestApp/jest.config.ts
examples/react-native/v12/TestApp/src/components/authentication/login/Login.test.tsx
examples/react-native/v12/TestApp/src/components/subscribe-api/SubscribeApi.test.tsx
examples/react-native/v12/TestApp/testSetup.ts

A previous PR commented out `module:metro-react-native-babel-preset` in `bable.config.cjs`. This line is necessary for CI Jest tests to work. So, it should remain uncommented in the source repo. However, it needs to be commented out to work with Metro and run local simulators.
Still haven't been able to figure out a real fix for this issue.
This PR also includes a couple minor changes to test code to account for configuration changes.
- https://jira.mongodb.org/browse/DOCSP-33596

(DOCSP-33596) Fix React Native test suite issue

---

examples/cpp/beta/local/supported-types.cpp
source/examples/generated/cpp/supported-types.snippet.beta-required-set.cpp
source/sdk/cpp/model-data/supported-types.txt

Noticed this quick fix while I was putting together release notes.
- [Supported Types](https://preview-mongodbdacharyc.gatsbyjs.io/realm/fix-missed-set-code-snippet/sdk/cpp/model-data/supported-types/)

C++: Add generated Set snippet to the supported types table

---

examples/cpp/beta/local/CMakeLists.txt
examples/cpp/beta/local/realm-files.cpp
examples/cpp/beta/sync/CMakeLists.txt
examples/cpp/beta/sync/app.cpp
source/examples/generated/cpp/app.snippet.encrypt-metadata.cpp
source/examples/generated/cpp/app.snippet.set-custom-headers-for-app.cpp
source/examples/generated/cpp/realm-files.snippet.beta-open-encrypted-realm.cpp
source/sdk/cpp.txt
source/sdk/cpp/app-services/connect-to-app.txt
source/sdk/cpp/realm-database.txt
source/sdk/cpp/realm-files.txt
source/sdk/cpp/realm-files/encrypt-a-realm.txt

- https://jira.mongodb.org/browse/DOCSP-33831
- [Encrypt a Realm](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-33831/sdk/cpp/realm-files/encrypt-a-realm/): New page based on similar pages in other SDKs
- [Connect to App Services](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-33831/sdk/cpp/app-services/connect-to-app/#encrypt-app-metadata): Add a section about encrypting metadata. Update custom HTTP section for deprecated `realm::App(...)`

(DOCSP-33831): C++: Add docs for encryption and metadata encryption

---

examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AppClientTest.kt
examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/EncryptARealmTest.kt
source/examples/generated/kotlin/AppClientTest.snippet.configure-app-client.kt
source/examples/generated/kotlin/AppClientTest.snippet.encrypted-app-client.kt
source/examples/generated/kotlin/AppClientTest.snippet.set-custom-http-headers.kt
source/examples/generated/kotlin/EncryptARealmTest.snippet.encrypt-a-realm.kt
source/examples/generated/kotlin/EncryptARealmTest.snippet.encrypt-synced-realm.kt
source/sdk/dotnet/realm-files/encrypt-a-realm.txt
source/sdk/flutter/realm-database/realm-files/encrypt.txt
source/sdk/kotlin/app-services/connect-to-app-services-backend.txt
source/sdk/kotlin/realm-database/realm-files/encrypt-a-realm.txt
source/sdk/node/realm-files/encrypt.txt
source/sdk/react-native/realm-files/encrypt.txt
source/sdk/swift/realm-files/encrypt-a-realm.txt

Update existing [Encrypt a Realm](https://www.mongodb.com/docs/realm/sdk/kotlin/realm-database/realm-files/encrypt-a-realm/) and [Connect to App Services](https://www.mongodb.com/docs/realm/sdk/kotlin/app-services/connect-to-app-services-backend/) pages with info on App metadata encryption.
- https://jira.mongodb.org/browse/DOCSP-34240
- [Encrypt a Realm - Kotlin SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-34240-encrypt-app-metadata/sdk/kotlin/realm-database/realm-files/encrypt-a-realm/#std-label-kotlin-encryption-and-device-sync)
- [Connect to Atlas App Services - Kotlin SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-34240-encrypt-app-metadata/sdk/kotlin/app-services/connect-to-app-services-backend/#encrypt-app-metadata)
If your PR modifies the docs, …

DOCSP-34240: Document metadata encryption in Kotlin SDK

---

examples/kotlin/README.md

Rename Kotlin Multiplatform Mobile (KMM) to Kotlin Multiplatform (KMP), as KMM is deprecated

Update Kotlin example README.md

---

source/introduction.txt
source/sdk/swift.txt

There is no Jira ticket for this one; it just came up during the Realm Team's taxonomy training workshop session.  We determined not to put a genre tag for any Realm landing pages.  @dacharyc, if all looks good, will you please merge?
- https://preview-mongodbsarahemlin.gatsbyjs.io/realm/untag-landing-pages/

Remove genre tag from 2 landing pages

---

.github/workflows/readability.yml

The existing readability workflow points to a ref that existed on the old source repo (my fork of Chris's branch) but that ref does not exist on Chris's branch. Attempting to check out a version tag instead of a branch ref that doesn't exist to fix the failing workflow.

Readability workflow: Check out a version tag instead of missing branch

---

examples/react-native/v12/TestApp/App.tsx
examples/react-native/v12/TestApp/babel.config.cjs
examples/react-native/v12/TestApp/package-lock.json
examples/react-native/v12/TestApp/package.json
examples/react-native/v12/TestApp/src/components/authentication/login/Login.test.tsx
examples/react-native/v12/TestApp/src/components/authentication/login/Login.tsx
examples/react-native/v12/TestApp/src/components/authentication/login/LoginWithEmail.tsx
examples/react-native/v12/TestApp/src/components/authentication/login/LoginWithFunction.tsx
examples/react-native/v12/TestApp/src/components/authentication/login/LoginWithJwt.tsx
examples/react-native/v12/TestApp/src/components/authentication/login/RealmWrapper.tsx
examples/react-native/v12/TestApp/testSetup.ts
source/examples/generated/react-native/v12/LoginWithFunction.snippet.login-function.tsx.rst
source/examples/generated/react-native/v12/LoginWithJwt.snippet.login-jwt.tsx.rst
source/examples/generated/react-native/v12/RealmWrapper.snippet.configure-user-provider.tsx.rst
source/examples/generated/react-native/v12/RealmWrapper.snippet.refresh-access-token.tsx.rst
source/sdk/react-native/manage-users/authenticate-users.txt

This PR adds tests and content updates for lots of authentication content. For Facebook, Google, and Apple auth, I updated examples, but not they're not part of the test suite. Setting up real auth through these services would take considerable time.
- Custom JWT
- Custom function
- Facebook
- Google
- Apple
- Get a User Access Token
I didn't get to updating the offline login example in this PR. I'll take another look at it later in this little epic.
I also fixed several annoying bugs in the React Native test suite itself and refactored some other auth examples to make them less brittle.
**CI Tests**
Seems like the CI tests are still a bit flaky. But they pass consistently locally. I don't have time to make CI happy right now, but here's a screenshot of local tests passing:
- …

(DOCSP-33535) React Native: Update more user authentication examples

---

source/example-projects.txt
source/sdk/dotnet.txt
source/sdk/swift.txt

- Intelligent Cache (.NET)
- In-App Purchases (Swift)
- https://jira.mongodb.org/browse/DOCSP-34421
- [Example Projects](https://preview-mongodblindseymoore.gatsbyjs.io/realm/DOCSP-34421/example-projects/)

DOCSP-34421 Update Example Projects Page

---

examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SchemaSync.kt
examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SchemaSyncTest.kt
source/examples/generated/kotlin/SchemaSync.snippet.sync-define-embedded-object.kt
source/examples/generated/kotlin/SchemaSync.snippet.sync-define-inverse-relationship.kt
source/examples/generated/kotlin/SchemaSync.snippet.sync-define-realm-object.kt
source/examples/generated/kotlin/SchemaSync.snippet.sync-define-to-many-relationship.kt
source/examples/generated/kotlin/SchemaSync.snippet.sync-define-to-one-relationship.kt
source/sdk/kotlin/realm-database/schemas.txt
source/sdk/kotlin/realm-database/schemas/define-realm-object-model.txt
source/sdk/kotlin/realm-database/schemas/model-data-device-sync.txt
source/sdk/kotlin/realm-database/schemas/property-annotations.txt
source/sdk/kotlin/sync/add-sync-to-app.txt
source/sdk/kotlin/sync/subscribe.txt

Add new Model Data with Device Sync page for Kotlin to the Model Data section, similar to the existing [Swift](https://www.mongodb.com/docs/realm/sdk/swift/model-data/model-data-device-sync/#create-object-models-and-schemas) page.
- https://jira.mongodb.org/browse/DOCSP-30332
- [Model Data with Device Sync - Kotlin SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-30332-model-data-sync/sdk/kotlin/realm-database/schemas/model-data-device-sync/)
- Realm/Model Data: 
- Model Data with Device Sync: Add new page with tested, Bluehawked code examples that describes how to map data from the …

DOCSP-30332: Model Data with Device Sync page for Kotlin

---

examples/cpp/beta/sync/CMakeLists.txt
examples/cpp/beta/sync/app.cpp
source/examples/generated/cpp/app.snippet.set-proxy-config.cpp
source/sdk/cpp/app-services/connect-to-app.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-34628
- [Connect to an App Services App](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-34628/sdk/cpp/app-services/connect-to-app/#use-an-http-proxy-with-realm)
- **C++ SDK**
- App Services/Connect to an App Services App: Add a "Use an HTTP Proxy with Realm" section with details and Bluehawked code example.

(DOCSP-34268): C++ SDK: Add HTTP tunneling details to docs

---

source/sdk/dotnet/sync/asymmetric-sync.txt
source/sdk/flutter/realm-database/model-data/define-realm-object-schema.txt
source/sdk/kotlin/realm-database/schemas/define-realm-object-model.txt
source/sdk/node/model-data/define-a-realm-object-model.txt
source/sdk/react-native/model-data/define-a-realm-object-model.txt

Jira ticket: 
- https://jira.mongodb.org/browse/DOCSP-33255
- https://jira.mongodb.org/browse/DOCSP-33256
- https://jira.mongodb.org/browse/DOCSP-33257
- https://jira.mongodb.org/browse/DOCSP-33258
- https://jira.mongodb.org/browse/DOCSP-33259
- [Flutter - Define a Realm Object Schema](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-33255/sdk/flutter/realm-database/model-data/define-realm-object-schema/#define-an-asymmetric-object)
- [Kotlin - Define an Object Model](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-33255/sdk/kotlin/realm-database/schemas/define-realm-object-model/#define-an-asymmetric-object-type)
- [.NET - Stream Data to Atlas](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-33255/sdk/dotnet/sync/asymmetric-sync/#sync-data-unidirecti …

(DOCSP-33255): Add asymmetric object link details for SDKs

---

source/sdk/node/sync/configure-and-open-a-synced-realm.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-34827
- [Configure & Open a Synced Realm](https://preview-mongodbkrollinsmdb.gatsbyjs.io/realm/DOCSP-34827/sdk/node/sync/configure-and-open-a-synced-realm/#open-synced-realm-at-specific-path): Replace `sßet` with `set`.
- genre

(DOCSP-34827) Fix one-character typo in Node.js docs

---

.github/workflows/kotlin.yml
examples/kotlin/androidRealmKMMApp/build.gradle.kts
examples/kotlin/androidRealmKMMApp/src/main/AndroidManifest.xml
examples/kotlin/build.gradle.kts
examples/kotlin/gradle/wrapper/gradle-wrapper.properties
examples/kotlin/settings.gradle.kts
examples/kotlin/shared/build.gradle.kts
examples/kotlin/shared/src/androidMain/AndroidManifest.xml
examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/EncryptARealmTest.kt
examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/Serialization.kt
examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SyncTest.kt

I had to upgrade a lot of Kotlin docs test suite dependencies in order to successfully upgrade to realm-kotlin version 1.13.0. I've fixed, removed, or commented out failing test assertions after upgrading realm-kotlin versions. A couple of docs tickets rely on these updates, so merging them separately to unblock work on the docs tickets.
Running Bluehawk after this PR generates three changes to Serialization code examples based on failing test assertions, but I'm not re-generating those in this PR. I've flagged this info to the Kotlin SDK team and believe this issue may be some kind of bug, so we can rework or fix those examples after I have more info.

Kotlin: Update unit test suite for v 1.13.0

---

.github/workflows/ios.yml
examples/ios/Examples/MongoDBRemoteAccess.swift
examples/ios/Examples/Sync.swift
examples/ios/RealmExamples.xcodeproj/project.pbxproj
examples/ios/RealmExamples.xcodeproj/xcshareddata/xcschemes/Test Examples.xcscheme
source/examples/generated/code/start/Sync.snippet.awaitable-wait-for-upload-download.swift
source/examples/generated/code/start/Sync.snippet.callback-wait-for-upload-download.swift
source/examples/generated/code/start/Sync.snippet.open-synced-realm.swift
source/sdk/swift/sync/sync-session.txt

While the eng PR this documents has been merged to master, it is not yet released. Wait for the next release before publishing. Before publishing:
- https://jira.mongodb.org/browse/DOCSP-34055
- [Manage Sync Sessions](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-34055/sdk/swift/sync/sync-session/#wait-for-changes-to-upload-or-download)
- Sync Data/Manage Sync Sessions: New "Wait for Changes to Upload or Download" section with Bluehawked, tested code examples.

(DOCSP-34055): Swift: Add docs for wait for upload/download

---

examples/cpp/beta/local/CMakeLists.txt
examples/cpp/beta/local/threading.cpp
source/examples/generated/cpp/threading.snippet.append-to-frozen-collection.cpp
source/examples/generated/cpp/threading.snippet.beta-scheduler.cpp
source/examples/generated/cpp/threading.snippet.beta-thread-safe-reference.cpp
source/examples/generated/cpp/threading.snippet.freeze.cpp
source/examples/generated/cpp/threading.snippet.is-frozen.cpp
source/examples/generated/cpp/threading.snippet.item-model.cpp
source/examples/generated/cpp/threading.snippet.model-with-collection-property.cpp
source/examples/generated/cpp/threading.snippet.thaw.cpp
source/sdk/cpp/crud/threading.txt
source/sdk/swift/crud/threading.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-34627
- [Threading (C++ SDK)](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-34627/sdk/cpp/crud/threading/#pass-immutable-copies-across-threads): Add a "Pass Immutable Copies Across Threads" section about freeze/thaw
- [Threading (Swift SDK)](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-34627/sdk/swift/crud/threading/#frozen-objects): Typo fix
Note: This PR is currently pending some additional work in the C++ SDK to add freeze/thaw for an object, and a managing realm getter. The existing code example will be extended/fixed, and a new example added, when this work is done in the SDK - PRIOR to merging these docs.
- **C++ SDK**
- CRUD/Threading: Add …

(DOCSP-34627): C++ SDK: Add freeze/thaw documentation

---

examples/dart/scripts/bluehawk_create_snippets.sh
examples/dart/test/manage_sync_session_test.dart
source/examples/generated/flutter/manage_sync_session_test.snippet.session-reconnect.dart
source/sdk/flutter/sync/manage-sync-session.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-26119
Staged changes: [Manage a Sync Session](https://preview-mongodbkrollinsmdb.gatsbyjs.io/realm/DOCSP-26119/sdk/flutter/sync/manage-sync-session/#manually-reconnect-all-sync-sessions)
The work described in the ticket links to four other RDART tickets. Three of those weren't implemented. The only sync client method to document is `App.reconnect()`.
- genre
- Sync/Manage A Sync Session: Add documentation for `App.reconnect()`.

(DOCSP-26119) Add sync client reconnect docs [Flutter]

---

examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/NotificationsTest.kt
source/examples/generated/kotlin/NotificationsTest.snippet.nested-keypath-listener.kt
source/examples/generated/kotlin/NotificationsTest.snippet.realm-object-keypath-listener.kt
source/examples/generated/kotlin/NotificationsTest.snippet.wildcard-keypath-listener.kt
source/includes/note-key-path-notification-execution.rst
source/sdk/kotlin/realm-database/react-to-changes.txt
source/sdk/swift/react-to-changes.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-34741
- [React to Changes](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-34741/sdk/kotlin/realm-database/react-to-changes/#register-a-key-path-change-listener): New "Register a Key Path Change Listener" section with details and tested, Bluehawked code examples.
- genre
- **Kotlin SDK**
- Realm/React to Changes: Add a new "Register a Key Path Change Listener" section with details and tested, Bluehawked code examples for key path filtering.

(DOCSP-34741): Kotlin: Add key path change listener documentation

---

examples/dart/test/manage_sync_session_test.dart
examples/dart/test/utils.dart
source/examples/generated/flutter/manage_sync_session_test.snippet.cancel-waitfor.dart
source/sdk/flutter/sync/manage-sync-session.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-34476
Staged link: [Manage a Sync Session](https://preview-mongodbkrollinsmdb.gatsbyjs.io/realm/DOCSP-34476/sdk/flutter/sync/manage-sync-session/#wait-for-changes-to-upload-and-download): Added example for using `cancellationToken`.
- genre
- Sync/Manage A Sync Session: Add cancellationToken parameter to Session.wait methods.

(DOCSP-34476) Add cancellationToken parameter to Session.wait methods [Dart/Flutter]

---

examples/dart/test/authenticate_users_test.dart
examples/dart/test/open_flexible_sync_realm_test.dart
source/sdk/flutter/sync/write-to-synced-realm.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-35099
The remaining failing test is in `manage_sync_session_test.dart`, which Kyle modified and may have fixed in #3122 ? 
- Internal: Fix failing code example tests related to SDK changes.

(DOCSP-35099): Flutter: fix failing unit tests

---

examples/dart/test/manage_sync_subscription_test.dart
source/examples/generated/flutter/manage_sync_subscription_test.snippet.add-subscription-subscribe-api.dart
source/examples/generated/flutter/manage_sync_subscription_test.snippet.remove-subscription-unsubscribe-api.dart
source/examples/generated/flutter/manage_sync_subscription_test.snippet.update-subscription-subscribe-api.dart
source/examples/generated/flutter/manage_sync_subscription_test.snippet.wait-first-time-subscribe-api.dart
source/examples/generated/flutter/manage_sync_subscription_test.snippet.wait-with-timeout-subscribe-api.dart
source/sdk/flutter/sync/manage-sync-subscriptions.txt
source/sdk/react-native/sync-data/flexible-sync.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-34729
- [Manage Subscriptions - Flutter SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-34729-subscribe-api/sdk/flutter/sync/manage-sync-subscriptions/#subscribe-to-queries): Update page with new documentation for new .subscribe() and .unsubscribe() methods, similar to the other SDKs.
- genre
- Sync Device Data/Manage Subscriptions: Update page to document the new Subscribe API with tested, Bluehawked code examples.

DOCSP-34729: Update Manage Subscriptions page with Subscribe API for Flutter

---

examples/react-native/v12/TestApp/src/components/subscribe-api/AlwaysWait.tsx
examples/react-native/v12/TestApp/src/components/subscribe-api/BasicSubscription.tsx
examples/react-native/v12/TestApp/src/components/subscribe-api/WaitFirstTime.tsx
source/examples/generated/react-native/v12/AlwaysWait.snippet.always-sync.tsx.rst
source/examples/generated/react-native/v12/BasicSubscription.snippet.subscribe-query.tsx.rst
source/examples/generated/react-native/v12/WaitFirstTime.snippet.wait-firsttime.tsx.rst
source/sdk/react-native/crud/create.txt
source/sdk/react-native/crud/delete.txt
source/sdk/react-native/crud/query-data.txt
source/sdk/react-native/crud/read.txt
source/sdk/react-native/model-data/data-types/dictionaries.txt
source/sdk/react-native/model-data/data-types/embedded-objects.txt
source/sdk/react-native/model-data/data-types/mixed.txt
source/sdk/react-native/model-data/data-types/sets.txt
source/sdk/react-native/model-data/define-a-realm-object-model.txt
source/sdk/react-native/quick-start.txt
source/sdk/react-native/sync-data/flexible-sync.txt

Due to code format changes, highlighting was incorrect in a large number of samples. Eventually, I want to migrate all of the manual highlighting to use Bluehawk :emphasize: tags, but that's beyond the scope of this simple fix-it PR.
- [Manage Sync Subscriptions](https://preview-mongodbkrollinsmdb.gatsbyjs.io/realm/fix-rn-highlighting/sdk/react-native/sync-data/flexible-sync/)
- [Dictionaries](https://preview-mongodbkrollinsmdb.gatsbyjs.io/realm/fix-rn-highlighting/sdk/react-native/model-data/data-types/dictionaries/)
- [Mixed](https://preview-mongodbkrollinsmdb.gatsbyjs.io/realm/fix-rn-highlighting/sdk/react-native/model-data/data-types/mixed/)
- [Sets](https://preview-mongodbkrollinsmdb.gatsbyjs.io/realm/fix-rn-highlighting/sdk/react-native/model-data/data-types/sets/)
- …

Fix React Native sample highlighting

---

source/sdk/react-native/model-data/data-types/dictionaries.txt

Typo fix. Suggested through the feedback widget by a reader.

Remove extra "define"

---

source/sdk/cpp/app-services/call-a-function.txt
source/sdk/cpp/app-services/connect-to-app.txt
source/sdk/cpp/crud/create.txt
source/sdk/cpp/crud/delete.txt
source/sdk/cpp/crud/read.txt
source/sdk/cpp/crud/threading.txt
source/sdk/cpp/crud/update.txt
source/sdk/cpp/model-data/object-models.txt
source/sdk/cpp/model-data/relationships.txt
source/sdk/cpp/model-data/supported-types.txt
source/sdk/cpp/realm-files/configure-and-open-a-realm.txt
source/sdk/cpp/realm-files/encrypt-a-realm.txt
source/sdk/cpp/sync/manage-sync-session.txt
source/sdk/cpp/sync/stream-data-to-atlas.txt
source/sdk/cpp/sync/sync-subscriptions.txt
source/sdk/cpp/sync/write-to-synced-realm.txt
source/sdk/cpp/users/authenticate-users.txt
source/sdk/cpp/users/custom-user-data.txt
source/sdk/cpp/users/manage-email-password-users.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-34763
- [C++ Staged Docs](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-34763/sdk/cpp/): Remove version directives that still exist in the docs after removing the experimental namespace. As part of removing the experimental namespace, I removed the "Current" and "Deprecated" tabs, so version directives that exist in those tabs have already been removed in the related PR (#3113 ). Apparently I also removed one on the Quick Start page that was next to a code example I updated. So these changes only touch version directives that were not touched in that PR.
I did a search for all the `.. version` directives in C++, and then I did a search for any remaining "version" references, and I compared every instance against the related PR, …

(DOCSP-34763): C++: Remove version directives

---

examples/cpp/compact/CMakeLists.txt
examples/cpp/compact/compact.cpp
source/examples/generated/cpp/compact.snippet.compact-database.cpp
source/sdk/cpp/realm-files.txt
source/sdk/cpp/realm-files/compact-realm.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-35190
- [Reduce Realm File Size](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-35190/sdk/cpp/realm-files/compact-realm/): New page with example for compacting a realm in C++ SDK.
Note: This example is in a new one-off unit test suite and uses the experimental namespace. When the SDK merges the PR that removes the experimental namespace, I'll get my corresponding docs PR merged and then move this into the local test suite established there, and remove this from the experimental namespace. 
- genre
- **C++ SDK**
- Realm Files/Compact a Realm: New page with example for compacting a realm in C++ SDK. …

(DOCSP-35190): C++: Add docs for compacting a realm

---

examples/cpp/client-reset/CMakeLists.txt
examples/cpp/client-reset/client-reset.cpp
source/examples/generated/cpp/client-reset.snippet.before-after-blocks.cpp
source/examples/generated/cpp/client-reset.snippet.discard-unsynced-changes.cpp
source/examples/generated/cpp/client-reset.snippet.manual-client-reset.cpp
source/examples/generated/cpp/client-reset.snippet.recover-unsynced-changes.cpp
source/sdk/cpp/sync/handle-sync-errors.txt
source/sdk/swift/sync/handle-sync-errors.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-34760
- [Handle Sync Errors](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-34760/sdk/cpp/sync/handle-sync-errors/#client-reset): New Client Reset section, with details and code examples showing client reset methods.
- genre
- **C++ SDK**
- Sync Data/Handle Sync Errors: Add information and code examples for client reset.

(DOCSP-34760): C++: Add client reset docs

---

examples/cpp/sync/authentication.cpp
source/examples/generated/cpp/authentication.snippet.google-auth-code.cpp
source/examples/generated/cpp/authentication.snippet.google-id-token.cpp
source/sdk/cpp/users/authenticate-users.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-35187
- [Manage Users/Authenticate Users](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-35187/sdk/cpp/users/authenticate-users/#google-user): Update the Google auth code examples to use the new naming introduced in [v0.6.0](https://github.com/realm/realm-cpp/blob/main/CHANGELOG.md#060-release-notes-2023-12-18).

(DOCSP-35187): C++: Update Google Auth examples for v0.6.0

---

examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AppClientTest.kt
source/examples/generated/kotlin/AppClientTest.snippet.configure-app-client.kt
source/examples/generated/kotlin/AppClientTest.snippet.enable-multiplexing-with-timeout.kt
source/examples/generated/kotlin/AppClientTest.snippet.enable-multiplexing.kt
source/examples/generated/kotlin/AppClientTest.snippet.sync-timeout-configuration.kt
source/includes/kotlin-note-sync-config-option.rst
source/sdk/kotlin/app-services/connect-to-app-services-backend.txt
source/sdk/kotlin/sync/open-a-synced-realm.txt

Jira tickets: 
https://jira.mongodb.org/browse/DOCSP-34740
https://jira.mongodb.org/browse/DOCSP-34816
- [Connect to Atlas App Services - Kotlin SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-34740-sync-timeout/sdk/kotlin/app-services/connect-to-app-services-backend/#share-sync-connections): Document the new session multiplexing and sync timeout App configuration options added in [v1.13.0](https://github.com/realm/realm-kotlin/blob/main/CHANGELOG.md#1130-2023-12-01)
- [Configure & Open a Synced Realm - Kotlin SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-34740-sync-timeout/sdk/kotlin/sync/open-a-synced-realm/#configure-a-synced-realm): Update "Configure a Synced Realm" section with sync timeout information
Before merging your PR, make sure to check a few …

(DOCSP-34740 & DOCSP-34816): Add Kotlin multiplexing and sync timeout options

---

examples/cpp/sync/CMakeLists.txt
examples/cpp/sync/authentication.cpp
examples/cpp/sync/call-function.cpp
examples/cpp/sync/custom-user-data.cpp
source/examples/generated/cpp/authentication.snippet.custom-function.cpp
source/examples/generated/cpp/call-function.snippet.call-a-function.cpp
source/examples/generated/cpp/custom-user-data.snippet.create.cpp
source/examples/generated/cpp/custom-user-data.snippet.delete.cpp
source/examples/generated/cpp/custom-user-data.snippet.read.cpp
source/examples/generated/cpp/custom-user-data.snippet.update.cpp
source/sdk/cpp/app-services/call-a-function.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-35186
- [Call a Function](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-35298/sdk/cpp/app-services/call-a-function/): Update examples to remove BSON
- [Custom User Data](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-35298/sdk/cpp/users/custom-user-data/): Update examples to remove BSON
- [Authentication/Custom Function User](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-35298/sdk/cpp/users/authenticate-users/#custom-function-user): Update example to remove BSON

(DOCSP-35298): C++: Remove BSON from Function examples

---

examples/cpp/asymmetric/CMakeLists.txt
examples/cpp/local/CMakeLists.txt
examples/cpp/scripts/bluehawk.sh
examples/cpp/sync/CMakeLists.txt
source/includes/note-cpp-supports-subset-of-rql.rst
source/sdk/cpp/crud/filter-data.txt
source/sdk/cpp/realm-files.txt
source/sdk/cpp/sync/sync-subscriptions.txt

This ticket incorporates a few outstanding review comments from #3140, and it updates the unit test suites to use the release version - `v1.0.0`.
- [CRUD/Filter Data](https://preview-mongodbdacharyc.gatsbyjs.io/realm/cpp-ga-fast-follows/sdk/cpp/crud/filter-data/): Update the note about supporting a subset of RQL and make it an include.
- [Sync Data/Manage Sync Subscriptions](https://preview-mongodbdacharyc.gatsbyjs.io/realm/cpp-ga-fast-follows/sdk/cpp/sync/sync-subscriptions/#subscribe-to-objects-that-match-a-query): Add the note about C++ supporting a subset of RQL to the section about subscribing to objects that match a query.
- [Realm Files](https://preview-mongodbdacharyc.gatsbyjs.io/realm/cpp-ga-fast-follows/sdk/cpp/realm-files/): Add ToC to the blank container page in case someone …

C++ GA Fast Follows

---

examples/cpp/local/crud.cpp
source/examples/generated/cpp/crud.snippet.create-an-object.cpp
source/examples/generated/cpp/crud.snippet.define-model.cpp
source/examples/generated/cpp/crud.snippet.dog-map-model.cpp
source/examples/generated/cpp/crud.snippet.dog-model-shows-namespace.cpp
source/examples/generated/cpp/crud.snippet.employee-model.cpp
source/examples/generated/cpp/crud.snippet.model-with-embedded-object.cpp
source/examples/generated/cpp/crud.snippet.model-with-map-property.cpp
source/examples/generated/cpp/crud.snippet.model-with-set-property.cpp
source/sdk/cpp/crud/create.txt
source/sdk/cpp/model-data/object-models.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-35191
- [Define an Object Model](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-35191/sdk/cpp/model-data/object-models/#define-a-new-object-type): Minor updates throughout the page for consistency, including naming updates. The main change as requested in the Jira ticket is in the "Define a New Object Type" section.
- [CRUD/Create](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-35191/sdk/cpp/crud/create/#create-a-new-object): Explicitly mention that when you define a new object, you must do it using the `realm` namespace.
- genre
- **C++ SDK*
- Model Data/Define an Object Model: Add information and update code examples to show …

(DOCSP-35191): C++: Add details around REALM_SCHEMA and namespace realm

---

examples/backend/functions/deleteAUser.js
examples/backend/functions/deleteAllUsers.js
examples/cpp/README.md
examples/dart/test/graphql_test.dart
examples/dotnet/README.md
examples/ios/Examples/RealmApp.swift
examples/ios/README.md
examples/java/sync/README.md
examples/web/nextjs/.env.local.example
examples/web/src/__tests__/apollo-graphql-client.test.jsx
examples/web/src/realm.config.json
source/examples/generated/code/start/RealmApp.snippet.realm-app-config.swift
source/examples/generated/web/apollo-graphql-client.test.snippet.create-apollo-client.jsx
source/examples/generated/web/apollo-graphql-client.test.snippet.set-up-user-auth.jsx
source/sdk/flutter/sync/write-to-synced-realm.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-35269
- [Flutter/Write Data to a Synced Realm](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-35269/sdk/flutter/sync/write-to-synced-realm/): Updated code examples show new base URL.
- [Swift/Connect to an App Services App](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-35269/sdk/swift/app-services/connect-to-app-services-backend/): Updated code example shows new base URL.
- [Web/Apollo GraphQL Client (React)](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-35269/web/graphql-apollo-react/#create-an-apollo-graphql-client): Updated code examples show new base URL.
Note for reviewer regarding failing tests: failing tests are unrelated to this change, and are resolved in:
- #3151 
- #3152 
- Throughout Docs
- Update …

(DOCSP-35269): Update base URL to new App Services base URL

---

source/sdk/cpp/crud/threading.txt
source/sdk/flutter/crud/read.txt
source/sdk/flutter/users/access-token.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-35706
Fix broken links, per the "Broken Links in Docs" report.
C++:
- [CRUD/Threading](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-35706/sdk/cpp/crud/threading/#pass-instances-across-threads): Fix a broken API reference link to `thread_safe_reference`.
Flutter:
- [Realm Database/CRUD/Read](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-35706/sdk/flutter/crud/read/#query-lists): Fix a broken API reference link to `RealmObjects`.
- [Manage Users/Get an Access Token](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-35706/sdk/flutter/users/access-token/#refresh-the-access-token): Fix a broken link to Dart `Timer.periodic()`.
- genre
- …

(DOCSP-35706): Fix broken links

---

examples/ios/Examples/Sync.swift
examples/ios/RealmExamples.xcodeproj/project.pbxproj
source/examples/generated/code/start/Sync.snippet.open-synced-realm-in-memory.swift
source/sdk/swift/realm-files/configure-and-open-a-realm.txt
source/sdk/swift/sync/configure-and-open-a-synced-realm.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-35365
- [Configure & Open a Realm](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-35365/sdk/swift/realm-files/configure-and-open-a-realm/#open-an-in-memory-realm): Note that as of 10.46.0, you can use in-memory realms with `syncConfiguration`.
- [Configure & Open a Synced Realm](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-35365/sdk/swift/sync/configure-and-open-a-synced-realm/#open-a-synced-realm-in-memory): New "Open a Synced Realm In Memory" section with details and a tested, Bluehawked code example.
- genre
- Realm Files/Configure & Open a Realm: Note that as of 10.46.0, you can use in-memory realms with …

(DOCSP-35365): Swift: Sync supports in-memory realms

---

source/sdk/swift/app-services/connect-to-app-services-backend.txt
source/sdk/swift/install.txt
source/sdk/swift/telemetry.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-35366
- [Install](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-35366/sdk/swift/install/#apple-privacy-manifest): New "Apple Privacy Manifest" section detailing what's covered in the SDK privacy manifest, additional disclosures that developers may need to make, and links out to the Apple documentation.
- [Connect to App Services](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-35366/sdk/swift/app-services/connect-to-app-services-backend/): Add a note that developers may need to make additional disclosures about data collection in the privacy manifest, and link to the new section on the Install page.
- [SDK Telemetry](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-35366/sdk/swift/telemetry/): Note that the SDK's …

(DOCSP-35366): Swift: Add details about Apple Privacy Manifest

---

source/sdk/swift/app-services/connect-to-app-services-backend.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-35852
- [Connect to an App Services Backend](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-35852/sdk/swift/app-services/connect-to-app-services-backend/#configuration): Note that starting in 10.46.0, you can change a `baseURL` and the App client no longer uses the cached value.
- genre
- Application Services/Connect to an App Services App: Note that starting in 10.46.0, you can change a `baseURL` and the App client no longer uses the cached value.

(DOCSP-35852): Swift: Base URL can change in App config

---

source/sdk/node/sync/log-level.txt
source/sdk/react-native/sync-data/log-level.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-35919
- [Set the Client Log Level - Node.js](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-35919/sdk/node/sync/log-level/): Update the version number for using the old syntax.
- [Set the Client Log Level - React Native](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-35919/sdk/react-native/sync-data/log-level/): Update the version number for using the old syntax.
- genre
- **Node.js SDK**
- Sync Data/Set the Client Log Level: Correct the JS SDK version number for using the old syntax from 11.9.0 to 11.10.2.
- **React Native SDK**
- Sync Data/Set the Client Log Level: Correct the JS SDK version number for using the old syntax from …

(DOCSP-35919): Fix JS SDK version in deprecated logger

---

examples/dart/pubspec.lock
examples/dart/test/app_services_test.dart
source/examples/generated/flutter/app_services_test.snippet.access-app-by-id.dart
source/examples/generated/flutter/app_services_test.snippet.app-client-advanced-configuration.dart
source/sdk/flutter/app-services/connect-to-app.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-35807
- [Connect to App Services - Flutter SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-35807-app-isolates/sdk/flutter/app-services/connect-to-app/): Add new "Get App by ID" section with a tested, Bluehawked code example to document new `getById()` method, and update existing section with new behavior when opening an App on a background isolate.
- genre
- Atlas App Services/Connect to App Services: Add new "Get App by ID" section with tested, Bluehawked code example that documents how to access an App instance on a background isolate.

DOCSP-35807: Add new Flutter getById() method to Connect to App page

---

examples/dart/bundle_example/pubspec.lock
examples/dart/pubspec.lock
examples/dart/test/data_types_test.dart
examples/dart/test/data_types_test.g.dart
examples/dart/test/geospatial_data_test.dart
source/examples/generated/flutter/data_types_test.snippet.map-model.dart
source/examples/generated/flutter/data_types_test.snippet.map-work-with.dart
source/examples/generated/flutter/geospatial_data_test.snippet.define-geopoint-class.dart
source/sdk/flutter/realm-database/model-data/data-types.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-35259
Staged changes: 
- [Data Types](https://preview-mongodbkrollinsmdb.gatsbyjs.io/realm/DOCSP-35259/sdk/flutter/realm-database/model-data/data-types/): Add new documentation for the RealmMap data type, which supports native Dart maps.
- genre
- **Flutter SDK** 
- Realm Database/Model Data/Data Types: Add new documentation for the RealmMap data type, which supports native Dart maps.

(DOCSP-35259) Add Map data type docs

---

examples/dart/test/app_services_test.dart
source/sdk/flutter/app-services/connect-to-app.txt
source/sdk/flutter/crud/read.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-35846
- [Connect to App Services - Flutter SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-35846-dart-baseurl/sdk/flutter/app-services/connect-to-app/): Replaced the sharedInclude with new note indicating that, starting in v1.8.0, the ``baseUrl`` is no longer cached in the ``AppConfig``
- genre
- Atlas App Services/Connect to App Services: Note that, starting in v1.8.0, you can update the baseUrl in the AppConfiguration because the App client no longer caches it.

DOCSP-35846: Update BaseUrl in Flutter SDK

---

source/sdk/swift/swiftui-tutorial.txt

[Jira ticket](https://jira.mongodb.org/browse/DOCSP-36290)
[Realm with SwiftUI QuickStart](https://preview-mongodbmongocaleb.gatsbyjs.io/realm/DOCSP-36290/sdk/swift/swiftui-tutorial/): Code elements are now code-blocks not bold. 
[Build Log](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65c404696b2f17c95af2a7a9)

replace bold with code-block`

---

examples/ios/Examples/Geospatial.swift
examples/ios/RealmExamples.xcodeproj/project.pbxproj
source/examples/generated/code/start/Geospatial.snippet.companies.swift
source/examples/generated/code/start/Geospatial.snippet.custom-geopoint.swift
source/examples/generated/code/start/Geospatial.snippet.geobox-query.swift
source/examples/generated/code/start/Geospatial.snippet.geobox.swift
source/examples/generated/code/start/Geospatial.snippet.geocircle-query.swift
source/examples/generated/code/start/Geospatial.snippet.geocircle.swift
source/examples/generated/code/start/Geospatial.snippet.geopoint-model.swift
source/examples/generated/code/start/Geospatial.snippet.geopolygon-query.swift
source/examples/generated/code/start/Geospatial.snippet.geopolygon.swift
source/examples/generated/code/start/Geospatial.snippet.geowithin.swift
source/examples/generated/code/start/Geospatial.snippet.nspredicate-query.swift
source/sdk/swift/crud/filter-data.txt
source/sdk/swift/crud/read.txt
source/sdk/swift/model-data/supported-types.txt

DO NOT MERGE until the Swift SDK makes a release containing this functionality. Prior to merging:
Jira ticket: https://jira.mongodb.org/browse/DOCSP-32521
- [Supported Types](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32521/sdk/swift/model-data/supported-types/#geospatial-data): New section with info about persisting geospatial data types
- [CRUD/Read](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32521/sdk/swift/crud/read/#query-geospatial-data): New section with info about querying geospatial data 
- [CRUD/Filter Data](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-32521/sdk/swift/crud/filter-data/#geospatial-operators): New sections for both query engines about querying geospatial data
- genre
- …

(DOCSP-32521): Swift: Add docs for new geospatial data type

---

examples/dart/test/authenticate_users_test.dart
source/examples/generated/flutter/authenticate_users_test.snippet.user-change-listener.dart
source/sdk/flutter/realm-database/react-to-changes.txt
source/sdk/flutter/users.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-36259
- [React to Changes - Flutter SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-36259-dart-user-changes/sdk/flutter/realm-database/react-to-changes/#register-a-user-instance-change-listener): Add new Register a User Instance Change Listener section 
- [User Management - Flutter SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-36259-dart-user-changes/sdk/flutter/users/): Add new Listen for User Changes section that links to the React to Changes page's new section
- genre
- Realm Database/React to Changes: Add new Register a User Instance Change Listener section documenting how to listen for user …

DOCSP-36259: Add user.changes documentation for Flutter

---

source/sdk/react-native/model-data/data-types/dictionaries.txt

- [Dictionaries](https://preview-mongodbdacharyc.gatsbyjs.io/realm/fix-bullet-formatting/sdk/react-native/model-data/data-types/dictionaries/): Fix bullet list formatting.
- genre
- **React Native SDK**
- Model Data/Data Types/Dictionaries: Fix bullet list formatting.

RN Dictionary Page: Fix bullet formatting

---

examples/dart/test/task_project_models_test.dart
examples/dart/test/task_project_models_test.g.dart
examples/dotnet/Examples/RqlSchemaExamples.cs
examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/RQLTest.kt
examples/node/legacy/Examples/realm-query-language.js
examples/node/legacy/Examples/schemas/rql-data-models.js
examples/node/v12/__tests__/models/rql-data-models.ts
examples/node/v12/__tests__/realm-query-language.test.js
source/examples/generated/dotnet/RqlSchemaExamples.snippet.rql-schema-examples.cs
source/examples/generated/flutter/task_project_models_test.snippet.task-project-models.dart
source/examples/generated/kotlin/RQLTest.snippet.rql-schema-example.kt
source/examples/generated/node/rql-data-models.snippet.rql-data-models.js
source/examples/generated/realm-query-language/realm-query-language.test.snippet.rql-fts.js
source/realm-query-language.txt
source/sdk/dotnet/crud/filter.txt
source/sdk/dotnet/model-data/define-object-model.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-33414
- [Realm Query Language](https://preview-mongodblindseymoore.gatsbyjs.io/realm/DOCSP-33414/realm-query-language/#full-text-search): Update overall code examples with FTS annotation on `Item.name` property. Add section on FTS. Behind the scenes, started a new RQL test file to reflect new JSv12 standards. 
- genre
**Other**
- Realm Query Language: Update RQL reference with information on querying with full-text search.

DOCSP-33414 Add section on FTS to RQL reference

---

config/redirects
source/sdk/node.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-37163
- [Node](https://preview-mongodblindseymoore.gatsbyjs.io/realm/DOCSP-37163/sdk/node/): removed Integration Guides section from TOC.
- genre
**Node.js SDK**
- Integration Guides: Remove Integration Guides section from TOC, as these electron guides are outdated.

DOCSP-37163 Remove Outdated Electron Guides from TOC

---

config/redirects
source/sdk/node.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-37163
- [Node Landing Page](https://preview-mongodblindseymoore.gatsbyjs.io/realm/DOCSP-37163/sdk/node/)
- genre
**Node SDK**
- Landing Page: Remove link to outdated electron guide from Node.js landing page. 

DOCSP-37163 Remove url link to electron guide

---

source/includes/user-access-token.rst
source/index.txt
source/introduction.txt
source/sdk.txt
source/sdk/cpp/users/authenticate-users.txt
source/sdk/flutter.txt
source/sdk/flutter/app-services.txt
source/sdk/flutter/app-services/graphql-api.txt
source/sdk/flutter/users/access-token.txt
source/sdk/kotlin/users/authenticate-users.txt
source/sdk/swift/sync/write-to-synced-realm.txt
source/sdk/swift/users/authenticate-users.txt
source/web.txt
source/web/api-reference.txt
source/web/atlas-app-services.txt
source/web/graphql-apollo-react.txt
source/web/nextjs.txt
source/web/quickstart.txt
source/web/users.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-36783
Staged site: https://preview-mongodbkrollinsmdb.gatsbyjs.io/realm/DOCSP-36783/sdk/flutter/app-services/graphql-api/
Lots of small changes on a bunch of pages. The primary goals:
- Add deprecation notices to pages with substantial GraphQL content
- Remove high-level references to our GraphQL API to make the feature less discoverable
This PR doesn't remove any GraqphQL content. I also didn't add tags to all the pages I touched, as that seems a lot of weakly-related work for a PR that touches a lot of files.
There's an autobuilder error because I've included a ref to a page that doesn't exist yet. It's added in the [App Services PR](https://github.com/mongodb/docs-app-services/pull/702).
Before merging your PR, make sure to check a few …

(DOCSP-36783) Add deprecation banners for GraphQL API

---

examples/cpp/local/crud.cpp
source/examples/generated/cpp/crud.snippet.open-db-at-path.cpp

Jira ticket: https://jira.mongodb.org/browse/DOCSP-37136
- [Configure & Open a Realm](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-37136/sdk/cpp/realm-files/configure-and-open-a-realm/#open-a-realm-at-a-file-path): Fixed truncated "Open a Realm at a File Path" code example.
- genre
- **C++ SDK**
- Realm Files/Configure & Open a Realm: Fixed truncated "Open a Realm at a File Path" code example.

(DOCSP-37136): Fix truncated code example

---

examples/ios/Examples/MongoDBRemoteAccess.swift
examples/ios/Examples/MongoDBRemoteAccessAggregate.swift
examples/ios/Examples/Sync.swift
examples/ios/RealmExamples.xcodeproj/project.pbxproj
source/examples/generated/code/start/Sync.snippet.open-realm-partition-based-sync.swift
source/sdk/swift/sync/partition-based-sync.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-37396
- [Partition-Based Sync](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-37396/sdk/swift/sync/partition-based-sync/#open-a-partition-based-sync-realm): Correctly display a Partition-Based Sync example of opening the realm instead of a Flexible Sync example.
- genre
- Sync/Partition-Based Sync: Correctly display a Partition-Based Sync example of opening the realm instead of a Flexible Sync example.

(DOCSP-37396): Swift: Fix PBS page showing FS example

---

source/sdk/swift/install.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-37617
- [Install](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-37617/sdk/swift/install/#apple-privacy-manifest): Make the privacy manifest info more generic and link out to the manifests themselves for details.
- genre
- Install: Remove API info from the privacy manifest details and link out to the manifests themselves, instead.

(DOCSP-37617): Swift SDK: Update privacy manifest documentation

---

examples/dart/test/data_types_test.dart
examples/dart/test/data_types_test.realm.dart
examples/dart/test/task_project_models_test.dart
examples/dart/test/task_project_models_test.realm.dart
source/examples/generated/flutter/data_types_test.snippet.data-types-example-model.dart
source/examples/generated/flutter/data_types_test.snippet.datetime-model.dart
source/examples/generated/flutter/data_types_test.snippet.embedded-object-model.dart
source/examples/generated/flutter/data_types_test.snippet.map-work-with.dart
source/examples/generated/flutter/data_types_test.snippet.objectid-model.dart
source/examples/generated/flutter/data_types_test.snippet.realm-set-examples.dart
source/examples/generated/flutter/data_types_test.snippet.realm-value-model.dart
source/examples/generated/flutter/data_types_test.snippet.realmlist-use.dart
source/examples/generated/flutter/data_types_test.snippet.uuid-model.dart
source/examples/generated/flutter/task_project_models_test.snippet.task-project-models.dart
source/sdk/flutter/realm-database/model-data/data-types.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-37354
- [Data Types - Flutter SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-37354-dynamic-get/sdk/flutter/realm-database/model-data/data-types/#realmset): Document `dynamic.getList()`, `dynamic.getMap()`, and `dynamic.getSet()` methods. 
- Additional snippet and schema formatting corrections 
- genre
- Realm/Realm Database/Model Data/Data Types: Update code examples with 'dynamic.getList()', 'dynamic.getSet()', and 'dynamic.getMap()' methods 

DOCSP-37354: Add Flutter dynamic.get methods

---

config/redirects
snooty.toml

Jira ticket: https://jira.mongodb.org/browse/DOP-4452
[Here](https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/atlas/device-sdks/) is a staging link - unfortunately, however, redirects do not work in preprod :sob:
- genre
This adds redirects from /docs/realm/ to /docs/atlas/device-sdks/ for routes not covered by the [AWS bucket routing rules](https://github.com/mongodb/docs-worker-pool/pull/1026) added for top-level directories. I believe I have covered all pages that still seem to have content/exist (out of top-level routes), but might be missing some things if they're hidden outside of the `/source` folder.
I also updated the title to be plural so that it shows up as such in the …

DOP-4452: Rehoming /docs/realm pages to /docs/atlas/device-sdks/

---

examples/ios/Examples/MongoDBRemoteAccess.swift
examples/ios/Examples/RealmActor.swift
examples/ios/RealmExamples.xcodeproj/project.pbxproj
source/sdk/swift/install.txt
source/sdk/swift/test-and-debug.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39147
- [Install](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-39147/sdk/swift/install/): Update the Swift Package Manager and Privacy Manifest sections with information about building as a dynamic framework and linking only to one package.
- [Test and Debug](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-39147/sdk/swift/test-and-debug/#swift-package-target-cannot-be-built-dynamically): Add info for the error related to linking to both `Realm` and `RealmSwift`.
- genre
- Install: Update the Swift Package Manager and Privacy Manifest sections with information about building as a dynamic framework and linking only …

(DOCSP-39147): Update SPM install instructions and privacy manifest details

---

examples/dart/pubspec.lock
examples/dart/pubspec.yaml
examples/dart/test/app_services_test.dart
source/examples/generated/flutter/app_services_test.snippet.change-base-url.dart
source/examples/generated/flutter/app_services_test.snippet.custom-base-url.dart
source/examples/generated/flutter/app_services_test.snippet.import-experimental.dart
source/sdk/flutter/app-services/connect-to-app.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39164
- [Connect to App Services - Flutter SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-39164-flutter-baseurl/sdk/flutter/app-services/connect-to-app/#connect-to-a-specific-server): New "Connect to a Specific Server" section with baseURL info. New "Connect to a Different Server During Runtime" subsection with info about the experimental API.
- 
- genre
- Atlas App Services/Connect to App Services: New "Connect to a Specific Server" section with baseURL info. New "Connect to a Different Server During Runtime" subsection with info about the experimental API. …

DOCSP-39164: Flutter: Change baseURL during runtime

---

examples/kotlin/settings.gradle.kts
examples/kotlin/shared/build.gradle.kts
examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AppClientTest.kt
examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/RealmTest.kt
source/examples/generated/kotlin/AppClientTest.snippet.change-base-url.kt
source/examples/generated/kotlin/AppClientTest.snippet.custom-base-url.kt
source/examples/generated/kotlin/AppClientTest.snippet.experimental-opt-in.kt
source/sdk/kotlin/app-services/connect-to-app-services-backend.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39166
- [Connect to Atlas App Services - Kotlin SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-39166-kotlin-baseurl/sdk/kotlin/app-services/connect-to-app-services-backend/#connect-to-a-specific-server): New "Connect to a Specific Server" section with baseURL info. New "Connect to a Different Server During Runtime" subsection with info about the experimental API
- genre
- **Kotlin** SDK
- Connect to Atlas/Connect to App Services: New "Connect to a Specific Server" section with baseUrl info. New "Connect to a Different Server During Runtime" subsection with info about the experimental API. …

DOCSP-39166: Kotlin: Change baseURL during runtime

---

examples/cpp/sync/quick-start.cpp
source/examples/generated/cpp/quick-start.snippet.model.cpp

- [Quick Start](https://preview-mongodbdacharyc.gatsbyjs.io/realm/cpp-add-missing-namespace/sdk/cpp/quick-start/): Add the missing `namespace` line to the quick start model.
- genre
- **C++ SDK**
- Quick Start: Fix omitted `namespace` line in the object model.

Add missing namespace to quick start snippet

---

examples/ios/Examples/MongoDBRemoteAccessAggregate.swift
examples/ios/Examples/RealmApp.swift
examples/ios/HostApp/Info.plist
examples/ios/RealmExamples.xcodeproj/xcshareddata/xcschemes/Test Examples.xcscheme
source/examples/generated/code/start/RealmApp.snippet.change-base-url.swift
source/examples/generated/code/start/RealmApp.snippet.custom-base-url.swift
source/examples/generated/code/start/RealmApp.snippet.import-experimental.swift
source/examples/generated/code/start/RealmApp.snippet.realm-app-config.swift
source/sdk/swift/app-services/connect-to-app-services-backend.txt
source/sdk/swift/sync/sync-session.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39162
- [Connect to an App Services App](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-39162/sdk/swift/app-services/connect-to-app-services-backend/#connect-to-a-specific-server): New "Connect to a Specific Server" section with baseURL info. New "Connect to a Different Server During Runtime" subsection with info about the new experimental API.
Note for reviewer: the failing test is related to the MongoClient API. One operation is failing with a timeout. It all passes locally, so I'm inclined to think this is CI latency issues and we can disregard this failure.
- genre
- Application Services/Connect to an App Services App: …

(DOCSP-39162): Swift: Change baseURL during runtime

---

examples/dart/test/manage_sync_session_test.dart
source/examples/generated/flutter/manage_sync_session_test.snippet.monitor-progress.dart
source/sdk/flutter/sync/manage-sync-session.txt
source/sdk/flutter/upgrade-to-v2.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-37885
- [Manage a Sync Session - Flutter SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-37885-dart-progress-notifications/sdk/flutter/sync/manage-sync-session/#monitor-sync-upload-and-download-progress): Replace `transferredBytes` and `transferrableBytes` with `progressEstimate`. Update code example.
- genre
- Sync Device Data/Manage Sync Session: Update the progress notification documentation in the "Monitor Sync Upload and Download Progress" section for compatibility with Flexible Sync.

DOCSP-37885: Flutter: Update progress notification documentation

---

examples/dart/test/react_to_changes_test.dart
source/examples/generated/flutter/react_to_changes_test.snippet.pause-resume-subscription.dart
source/examples/generated/flutter/react_to_changes_test.snippet.query-change-listener.dart
source/examples/generated/flutter/react_to_changes_test.snippet.realm-list-change-listener.dart
source/examples/generated/flutter/react_to_changes_test.snippet.realm-object-change-listener.dart
source/sdk/flutter/realm-database/react-to-changes.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-38015
- [React to Changes - Flutter SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-38015-dart-react-to-changes-updates/sdk/flutter/realm-database/react-to-changes/): Add new `isCleared` and `isCollectionDeleted` properties to list, set, and map tabs
- genre
- Realm Database/React to Changes: Update "Register Collection Change Listeners" section to document the `isCollectionDeleted` property for list, set, and map collections and the `isCleared` property for map collections.

DOCSP-38015: Add new collection listener properties

---

source/includes/dotnet-frameworks.rst
source/sdk/flutter/app-services/call-function.txt
source/sdk/flutter/install.txt
source/sdk/flutter/realm-database/realm-files/delete.txt
source/sdk/flutter/telemetry.txt
source/sdk/flutter/users.txt
source/sdk/react-native/install.txt
source/sdk/swift/install.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39270
- [Install - Flutter SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-39270-dart-privacy-manifest/sdk/flutter/install/): Add "Apple Privacy Manifest" section; reformat page to use tabs
- [Telemetry - Flutter SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-39270-dart-privacy-manifest/sdk/flutter/telemetry/): Add "Apple Privacy Manifest" section
- genre
- Install: Add new "Apple Privacy Manifest" section with information on the manifest included with SDK v2.2.0.
- SDK Telemetry: Add new "Apple Privacy Manifest" section to clarify the SDK does not collect telemetry on builds for the App Store. …

DOCSP-39270: Flutter: Add Privacy Manifest information 

---

.github/pull_request_template-base.md
.github/pull_request_template.md

This PR updates the PR template to add consolidation-specific checklists for the PR author and reviewer.
I've renamed the existing template to `pull_request_template-base.md` to preserve it in the repo, so we can easily switch back to it after the consolidation project is complete.

Update PR template for the docs consolidation project

---

source/example-projects.txt
source/sdk/cpp.txt

*Staged Pages*
- [C++ Landing Page](https://preview-mongodbdacharyc.gatsbyjs.io/realm/add-cpp-template-app/sdk/cpp/): Add "Learning Paths" section with links to the C++ quick start, template app, and tutorial, similar to the other SDKs.
- [Example Projects](https://preview-mongodbdacharyc.gatsbyjs.io/realm/add-cpp-template-app/example-projects/): Add C++ to the list of SDK example apps.
- C++ SDK
- Landing Page: Add "Learning Paths" section with links to the C++ quick start, template app, and tutorial.
- Example Projects: Add the C++ template app to the SDK template app list.

Add C++ template app and tutorial to SDK docs

---

.github/workflows/dotnet-core.yml
examples/dotnet/Examples/AggregationExamples.cs
examples/dotnet/Examples/BaseURLChange.cs
examples/dotnet/Examples/DataTypesSectionExamples.cs
examples/dotnet/Examples/Examples.csproj
examples/dotnet/Examples/MongoDBExamples.cs
examples/dotnet/Examples/ProgressNotifications.cs
examples/dotnet/README.md
source/examples/generated/dotnet/BaseURLChange.snippet.custom-base-url.cs
source/examples/generated/dotnet/BaseURLChange.snippet.experimental-import.cs
source/examples/generated/dotnet/BaseURLChange.snippet.update-base-url.cs
source/sdk/dotnet/app-services/connect-to-app-services-backend.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39161
- [Connect to App Services Backend](https://preview-mongodblindseymoore.gatsbyjs.io/realm/DOCSP-39161/sdk/dotnet/app-services/connect-to-app-services-backend/)
- Note: Commented out failing tests. Fixing them will be a part of this ticket: https://jira.mongodb.org/browse/DOCSP-39638.
- genre
- .NET SDK
- Application Services/Connect to an App Services App: Add a section on updating the base URL during runtime. 

DOCSP-39161 .NET updateBaseURL

---

examples/ios/Examples/RealmApp.swift
examples/ios/RealmExamples.xcodeproj/project.pbxproj
source/examples/generated/code/start/RealmApp.snippet.change-base-url.swift
source/examples/generated/code/start/RealmApp.snippet.custom-base-url.swift

Fixes broken `baseURL` and SwiftUI property wrapper behavior.

Update Swift test suite to 10.50.1

---

examples/dotnet/Examples/BaseURLChange.cs
source/examples/generated/dotnet/BaseURLChange.snippet.experimental-import.cs
source/sdk/dotnet/app-services/connect-to-app-services-backend.txt

Related to Jira ticket: https://jira.mongodb.org/browse/DOCSP-39161
*Staged Page*
- [.NET Connect to App Services Backend](https://preview-mongodblindseymoore.gatsbyjs.io/realm/node-baseurl-additions/sdk/dotnet/app-services/connect-to-app-services-backend/#connect-to-a-specific-server)

Review comments for DOCSP-39161 .NET baseurl

---

source/sdk/swift/install.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-40014
*Staged Page*
- [Install - Swift SDK](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-40014/sdk/swift/install/): Remove outdated information. Rename "Static Framework" install instructions to "Dynamic Framework."
- Swift SDK
- Install: Remove outdated information. Rename "Static Framework" install instructions to "Dynamic Framework."

(DOCSP-40014): Update Swift 'static' framework install instructions

---

source/includes/note-java-and-realmany.rst
source/sdk/dotnet/compatibility.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-36167
*Staged Page*
- [Platform and Framework Compatibility - .NET SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-36167-compatibility/sdk/dotnet/compatibility/)
- **.NET SDK** 
- Compatibility: Added note with minimum framework requirements when using the new source model generator.

DOCSP-36167: Update .NET compatibility with note on source generator model requirements

---

source/sdk/dotnet/model-data/data-types/realm-value.txt
source/sdk/dotnet/model-data/define-object-model.txt
source/sdk/flutter/realm-database/model-data/data-types.txt
source/sdk/flutter/realm-database/model-data/define-realm-object-schema.txt
source/sdk/kotlin/realm-database/schemas/define-realm-object-model.txt
source/sdk/kotlin/realm-database/schemas/supported-types.txt
source/sdk/node/model-data.txt
source/sdk/node/model-data/data-types/mixed.txt
source/sdk/node/model-data/define-a-realm-object-model.txt
source/sdk/react-native/model-data.txt
source/sdk/react-native/model-data/data-types/mixed.txt
source/sdk/react-native/model-data/define-a-realm-object-model.txt
source/sdk/swift/model-data.txt
source/sdk/swift/model-data/object-models.txt
source/sdk/swift/model-data/supported-types.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39924
For each of the following SDK pages: 
- Define data model: add `Model Unstructured Data` section to define data model page 
- Mixed data property: update with support for holding lists & dicts, and add `Collections as Mixed` subsection
**Kotlin (v2.0.0):** 
- [Define an Object Model - Kotlin SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-39924-unstructured-data/sdk/kotlin/realm-database/schemas/define-realm-object-model/#model-unstructured-data) & [Supported Data Types - Kotlin SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-39924-unstructured-data/sdk/kotlin/realm-database/schemas/supported-types/#realmany--mixed-)
**.NET (v12.22.0):** 
- [Define an Object Model - .NET …

DOCSP-39924: Update eligible SDKs with collections in mixed info

---

source/includes/api-details/cpp/users/create-delete-users-delete-users-not-supported.rst
source/includes/api-details/cpp/users/create-delete-users-remove-users-not-supported.rst
source/includes/api-details/csharp/users/create-delete-users-delete-users-description.rst
source/includes/api-details/csharp/users/create-delete-users-remove-users-description.rst
source/includes/api-details/dart/users/create-delete-users-delete-users-description.rst
source/includes/api-details/dart/users/create-delete-users-remove-users-description.rst
source/includes/api-details/java/users/create-delete-users-delete-users-not-supported.rst
source/includes/api-details/java/users/create-delete-users-remove-users-description.rst
source/includes/api-details/javascript/users/create-delete-users-delete-users-js-ts-description.rst
source/includes/api-details/javascript/users/create-delete-users-remove-users-js-ts-description.rst
source/includes/api-details/kotlin/users/create-delete-users-delete-users-description.rst
source/includes/api-details/kotlin/users/create-delete-users-remove-users-description.rst
source/includes/api-details/objectivec/users/create-delete-users-delete-users-description.rst
source/includes/api-details/objectivec/users/create-delete-users-remove-users-description.rst
source/includes/api-details/swift/users/create-delete-users-delete-users-description.rst
source/includes/api-details/swift/users/create-delete-users-remove-users-description.rst
source/includes/sdk-examples/users/create-delete-users-delete-users-from-atlas.rst
source/includes/sdk-examples/users/create-delete-users-remove-users-from-device.rst
source/sdk/users.txt
source/sdk/users/authenticate-users.txt
source/sdk/users/create-and-delete-users.txt
source/sdk/users/manage-email-password-users.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39525
*Staged Page*
- [Create, Delete, and Remove Users](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-39525/sdk/users/create-and-delete-users/)
*Page Source*
Add links to every SDK's pages where you got the SDK-specific information:
- [Flutter: Delete a User](https://www.mongodb.com/docs/atlas/device-sdks/sdk/flutter/users/delete-user/)
- [Java: Create and Delete Users](https://www.mongodb.com/docs/atlas/device-sdks/sdk/java/users/create-delete-users/)
- [Kotlin: Delete Users](https://www.mongodb.com/docs/atlas/device-sdks/sdk/kotlin/users/delete-users/)
- [.NET: Create and Delete Users](https://www.mongodb.com/docs/atlas/device-sdks/sdk/dotnet/manage-users/create-and-delete-users/)
- [Node.js: Create and Delete …

(DOCSP-39525): Consolidate Create and Delete Users page

---

examples/web/package.json
examples/web/src/__tests__/authentication-link-identities.test.js
examples/web/yarn.lock

Closes #3304
Closes #3305
Closes #3307
Closes #3308
After upgrading `realm-web` to 2.0.1, the link users test started failing with the error:
`"Request failed (POST...): linking forbidden without first specifying allowed request origins (status 403 Forbidden)"`
I've skipped this test, as we don't want to be forced to enable Allowed request origins on the App Services app that we run these tests against.

Web SDK: Update dependencies to resolve security vulnerabilities

---

source/includes/api-details/csharp/sync/manage-sync-sessions-check-upload-and-download-progress-description.rst
source/includes/api-details/javascript/crud/create-counter-property-type-description.rst
source/includes/api-details/javascript/crud/create-counter-property-type-not-supported.rst
source/includes/api-details/typescript/crud/create-counter-property-type-not-supported.rst
source/includes/sdk-examples/crud/create-counter-property-type.rst
source/includes/sdk-examples/sync/manage-sync-sessions-check-upload-download-progress.rst
source/sdk/crud/create/create-property-types.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-41633
Re: counters, the only info I'm pulling in here is for the "Create" page. The rest of the Counter info will be incorporated as we work on other PRs in the consolidation project (for defining a counter property and updating a counter property).
*Staged Page*
- [Create Property Types/Counters](https://preview-mongodbdacharyc.gatsbyjs.io/realm/incorporate-counters/sdk/crud/create/create-property-types/#create-a-counter-property): Add info for JavaScript and TypeScript about creating objects with the new JS counter type.
- [Manage Sync Sessions](https://preview-mongodbdacharyc.gatsbyjs.io/realm/incorporate-counters/sdk/sync/manage-sync-sessions/#check-upload-and-download-progress): Add the .NET example for the new estimate-based …

(DOCSP-41633): Consolidation: Incorporate Counter and Progress Notifications updates

---

examples/dotnet/Examples/BundleARealmExamples.cs
examples/dotnet/Examples/DataSyncExamples.cs
source/examples/generated/dotnet/BundleARealmExamples.snippet.extract_and_copy_realm.cs
source/examples/generated/dotnet/BundleARealmExamples.snippet.get-session-state.cs
source/examples/generated/dotnet/BundleARealmExamples.snippet.get-sync-session.cs
source/examples/generated/dotnet/BundleARealmExamples.snippet.pause-synced-realm.cs
source/examples/generated/dotnet/DataSyncExamples.snippet.get-session-state.cs
source/examples/generated/dotnet/DataSyncExamples.snippet.get-sync-session.cs
source/examples/generated/dotnet/DataSyncExamples.snippet.pause-synced-realm.cs
source/sdk/dotnet/sync/sync-session.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-40247
*Staged Page*
n/a
**Get sync session**
`source/examples/generated/dotnet/DataSyncExamples.snippet.get-sync-session.cs`
**Check sync state**
`source/examples/generated/dotnet/DataSyncExamples.snippet.get-session-state.cs`
**Upload and Download Progress**
`source/examples/generated/dotnet/ProgressNotifications.snippet.upload-download-progress-notification.cs`

Add tests & snippets for sync session

---

source/includes/api-details/csharp/crud/create-copy-object-to-another-database-not-supported.rst
source/includes/api-details/csharp/crud/create-unmanaged-copy-of-object-not-supported.rst
source/sdk/crud/create.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-41466
*Staged Page*
- [Create](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-41466/sdk/crud/create/): New C# API descriptions for "Create an unmanaged copy of an object" and "Copy an object to another database" advising developers to use third-party libraries for this functionality.

(DOCSP-41466): Create: Use third-party libraries for some C# operations

---

source/sdk/dotnet/model-data/data-types/realm-value.txt
source/sdk/dotnet/model-data/define-object-model.txt

12.22.0 was supposed to be 12.2.0
Jira ticket: DOCSP-41878
*Staged Page*
- [Define an Object Model](https://preview-mongodbmongocaleb.gatsbyjs.io/realm/DOCSP-41878/sdk/dotnet/model-data/define-object-model/)
- [Value Type](https://preview-mongodbmongocaleb.gatsbyjs.io/realm/DOCSP-41878/sdk/dotnet/model-data/data-types/realm-value/)

fix DOTNET version number

---

source/help.txt
source/includes/sdk-examples/sync/manage-sync-sessions-check-network-connection.rst
source/includes/sdk-examples/sync/manage-sync-sessions-check-sync-state.rst
source/includes/sdk-examples/sync/manage-sync-sessions-check-upload-download-progress.rst
source/includes/sdk-examples/sync/manage-sync-sessions-get-sync-session.rst
source/includes/sdk-examples/sync/manage-sync-sessions-manually-reconnect-sync-sessions.rst
source/includes/sdk-examples/sync/manage-sync-sessions-pause-resume.rst
source/includes/sdk-examples/sync/manage-sync-sessions-wait-for-changes-to-upload-or-download.rst

Jira ticket: https://jira.mongodb.org/browse/DOCSP-42045
*Staged Page*
- [Manage Sync Sessions](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-42045/sdk/sync/manage-sync-sessions/): Page correctly changes code examples when you switch language tabs.
- [Help](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-42045/help/): The Help page was using realm-sdks tab set - I changed it to Drivers tab set so it would preserve the language selection when the user switched to the page. I also added a couple of notes related to naming because there are some naming things here that still reflect the old name, and we can't change them.

(DOCSP-42045): Fix wrong C++ tab ID

---

source/includes/tip-realm-query-language-reference-examples.rst
source/sdk/crud/query-engines/filter-data-swift-sdk.txt
source/sdk/crud/read.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39519
This is a port of the existing Swift page - we decided to maintain these SDK-specific query engines as one-off pages because they are too dissimilar to consolidate. I have updated the Realm naming and refs to use the `sdk` ref targets.
I switched from the Realm languages tab group to the Drivers tab group, so if someone has selected "Swift" or "Objective-C" from another page, I believe the selection should carry over. There are some examples that don't exist or apply in the other language, so if you have selected "Swift" you will still see some Objective-C examples in the NSPredicate part of the page, and if you have selected Objective-C, you will still see the entire Swift Type-Safe Query API and some Swift examples in the …

(DOCSP-39519): Port Swift Filter Data page for consolidated docs

---

source/sdk/flutter/realm-database/configure-and-open.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-40103
<li><a href=https://deploy-preview-3366--docs-realm.netlify.app/sdk/flutter/realm-database/configure-and-open>sdk/flutter/realm-database/configure-and-open</a></li>
- Flutter SDK
- Realm Database/Configure & Open a Realm: Fix typo in "Add Initial Data to Realm" section.

(DOCSP-40103): Fix typo on Flutter: Configure & Open a Realm page

---

examples/node/legacy/Examples/client-reset.js
source/examples/generated/node/client-reset.snippet.discard-unsynced-changes-after-destructive-schema-changes.js

Jira ticket: https://jira.mongodb.org/browse/DOCSP-40225
- [Handle Sync Errors - Node.js](https://deploy-preview-3367--device-sdk.netlify.app/sdk/node/sync/handle-sync-errors/#discard-unsynced-changes-after-breaking-schema-changes)
- Node.js SDK
-  Sync Data/Handle Sync Errors: Correct a parameter in the error handler code from `error` to `onError`.

(DOCSP-40225): Node.js Error Handler: Typo Fix

---

source/includes/api-details/csharp/sync/add-sync-to-app-define-sync-configuration-description.rst
source/includes/api-details/csharp/sync/add-sync-to-app-example-data-model-description.rst
source/includes/api-details/csharp/sync/add-sync-to-app-use-synced-database-description.rst
source/includes/api-details/dart/sync/add-sync-to-app-define-sync-configuration-description.rst
source/includes/api-details/dart/sync/add-sync-to-app-example-data-model-description.rst
source/includes/api-details/dart/sync/add-sync-to-app-open-synced-database-description.rst
source/includes/api-details/dart/sync/add-sync-to-app-use-synced-database-description.rst
source/includes/api-details/kotlin/sync/add-sync-to-app-define-sync-configuration-description.rst
source/includes/api-details/kotlin/sync/add-sync-to-app-example-data-model-description.rst
source/includes/api-details/kotlin/sync/add-sync-to-app-open-synced-database-description.rst
source/includes/api-details/kotlin/sync/add-sync-to-app-prerequisites-description.rst
source/includes/api-details/kotlin/sync/add-sync-to-app-use-synced-database-description.rst
source/includes/api-details/swift/sync/add-sync-to-app-define-sync-configuration-description.rst
source/includes/api-details/swift/sync/add-sync-to-app-example-data-model-description.rst
source/includes/api-details/swift/sync/add-sync-to-app-use-synced-database-description.rst
source/includes/sdk-examples/sync/add-sync-to-app-authenticate-user.rst
source/includes/sdk-examples/sync/add-sync-to-app-connect-to-atlas.rst
source/includes/sdk-examples/sync/add-sync-to-app-define-sync-configuration.rst
source/includes/sdk-examples/sync/add-sync-to-app-example-data-model.rst
source/includes/sdk-examples/sync/add-sync-to-app-open-synced-database.rst
source/includes/sdk-examples/sync/add-sync-to-app-use-synced-database.rst
source/sdk/crud/threading.txt
source/sdk/sync/add-sync-to-app.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39533
*Staged Page*
- [Add Sync to an App](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-39533/sdk/sync/add-sync-to-app/)
Note for reviewer: some of the API descriptions are intentionally missing because there isn't necessarily anything else relevant to add.
*Page Source*
Add links to every SDK's pages where you got the SDK-specific information:
- [Flutter: Add Sync to an App](https://www.mongodb.com/docs/atlas/device-sdks/sdk/flutter/sync/add-sync-to-app/)
- [Kotlin: Add Sync to an App](https://www.mongodb.com/docs/atlas/device-sdks/sdk/kotlin/sync/add-sync-to-app/)
- [.NET: Add Sync to an App](https://www.mongodb.com/docs/atlas/device-sdks/sdk/dotnet/sync/add-sync-to-app/)
- [Swift: Add Sync to an …

(DOCSP-39533): Consolidate Add Sync to an App page

---

.github/pull_request_template.md
.github/workflows/netflify-preview-links.yml
examples/dotnet/Examples/WorkWithRealm.cs
source/examples/generated/dotnet/WorkWithRealm.snippet.field-notifications.cs
source/sdk/dotnet/react-to-changes.txt

Jira ticket: [DOCSP-34405](https://jira.mongodb.org/browse/DOCSP-34405)
<li><a href=https://deploy-preview-3362--device-sdk.netlify.app/sdk/dotnet/react-to-changes/#watch-for-collection-changes>sdk/dotnet/react-to-changes</a></li>
- **.NET SDK**
- Add KeyPathsCollection information & code snippet.

Add description and new code example

---

config/redirects

Jira ticket: https://jira.mongodb.org/browse/DOCSP-45013

(DOCSP-45013) Add specific redirects for pages that 404

---

config/redirects

Jira ticket: https://jira.mongodb.org/browse/DOCSP-48490
Note for future us: I manually verified that the pages we're trying to redirect to do actually exist. 🤞 switching from `base` to `deviceSDKsBase` fixes the issue for this handful of URLs.

Fix broken 404 redirects

---

config/redirects

Jira ticket: https://jira.mongodb.org/browse/DOCSP-48512
The former `Introduction` page had some outdated messaging. It has been removed from the repo, but was still available when browsed to via URL. Adding a redirect to make sure the outdated messaging is not available and it points to the correct content.

(DOCSP-48512): Add redirect from introduction to deprecation

---

config/redirects

Jira ticket: https://jira.mongodb.org/browse/DOCSP-48490
Related to PR #3389 : per convo with DOP, the blanket redirect applies before these page-level redirects, so trying `deviceSDKsBase` on the left side of the redirect to resolve these issues.

(DOCSP-48490): 404 redirect finagling
